### ISSUE TITLE
Docker is stopped and settings keep on loading

### ISSUE THREAD

**Issue by YashKamboj** [docker/for-win#12555] opened 2022-02-14 12:32 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D2D43616-4A55-4308-920B-E59B8D88BF96/20220214121542

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by YashKamboj** [comment] 2022-02-14 14:50
@mat007 Installed yesterday so i think the latest

**Comment by mat007** [comment] 2022-02-14 15:42
Right, yes then I believe it’s likely a duplicate of #12545.
I’ll close this one, but feel free to comment again if you think it’s different.

**Closed by mat007** 2022-02-14 15:42 UTC
