### ISSUE TITLE
Docker Engine crashes while starting

### ISSUE THREAD

**Issue by hepter** [docker/for-win#11647] opened 2021-07-12 07:18 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 71E9D3A7-2400-46B1-924C-1B270C2467B6/20210712070340

### Actual behavior

![image](https://user-images.githubusercontent.com/14141071/125245072-caf8c580-e2f8-11eb-830d-07fa579234ac.png)
 ```
  See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Docker.ApiServices.Notifications.BackendInstallFeatureException: BackendInstallFeatureException
   at Docker.Engines.LinuxHyperVEngine.<DoCheckPreconditionsAsync>d__18.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.TaskExtension.<Forget>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\Extensions.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Docker Desktop
    Assembly Version: 1.0.0.0
    Win32 Version: 3.5.2.66501
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker%20Desktop.exe
----------------------------------------
Docker.Core
    Assembly Version: 1.0.0.0
  ```
### Information

  - Windows Version: Windows 10 19043.1083
  - Docker Desktop Version:  3.5.2(66501)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Not virtualized

### Steps to reproduce the behavior

No action is required, it encounters an error every time while opening the Docker Desktop Engine.

I encountered the first error while using version **3.5.1** and updated it to **3.5.2(66501)**. I keep getting the same error even though I upgraded to the latest version and also did "Reset to factory defaults" and "Clean / Purge data" nothing changed

**Comment by lorenrh** [comment] 2021-07-12 09:17
This seems like a duplicate of #11601.

Would you mind trying the build mentioned in https://github.com/docker/for-win/issues/11601#issuecomment-877171395 and see if it solves the issue?

**Comment by lorenrh** [comment] 2021-07-12 15:37
Since I saw you commented in the original issue, I'll close this to keep the issue tracker a bit tidy.

**Closed by lorenrh** 2021-07-12 15:37 UTC
