### ISSUE TITLE
Docker fails to start after upgrade: ArgumentNullException in Path.Combine

### ISSUE THREAD

**Issue by heaths** [docker/for-win#4343] opened 2019-07-31 18:18 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 099D6802-78A9-4C31-A4CE-18370DCC4A36/20190731181045

### Expected behavior

Docker starts successfully.

### Actual behavior

Docker fails to start with the following stack:
```
Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Docker.Core.DynamicPaths.GetPkiFolder(Settings settings)
   at Docker.Backend.Processes.ApiProxy.CommonArgs(Settings settings)
   at Docker.Backend.Processes.ApiProxy.StartWinNamedPipe(Settings settings, String daemonNamedPipe, Boolean runAsSystem)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Windows Version: Windows 10 version 1903 build 18362.267
  - Docker Desktop Version: Docker version 19.03.1, build 74b1e89

### Steps to reproduce the behavior

  1. Try to start "Docker for Windows".

FWIW, I do have and have had (for a couple years) a custom location and daemon.json file in %ProgramData%\Docker\config\daemon.json like so:

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true,
  "graph": "E:\\Docker",
  "hosts": [
    "npipe://"
  ],
  "storage-opts": [
    "size=127G"
  ]
}
```

My machine is also a swarm manager with a separate VM running on my machine that is joined to the swarm (testing out scenarios on a pretty beefy dev machine). Everything was working fine before the upgrade.

**Comment by BSSIRajbir** [comment] 2019-07-31 18:23
The same thing Happened on My Window just after the update.

**Comment by mschonwe** [comment] 2019-07-31 20:18
Same error here too.

**Comment by heaths** [comment] 2019-07-31 20:24
For those having similar issues, using the +1 reaction on the OP might make it easier for support to view the discussion and get a better sense of how many others are having the same issue. 😉

**Comment by Robot1que** [comment] 2019-08-01 09:36
Docker does not crash anymore after uninstalling and installing the latest version.

**Comment by mikeparker** [comment] 2019-08-01 09:42
I think this is because settings.json has a `"dataFolder" : null` entry. Could you check please?

**Comment by mikeparker** [comment] 2019-08-01 10:08
Also could you confirm if this is on stable or edge release?

**Comment by mschonwe** [comment] 2019-08-01 10:12
The contents of `C:\ProgramData\Docker\config\daemon.json` is:

```{"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": false}```

Not sure about stable vs edge, `File Version : 2.1.0.36874`

**Comment by mikeparker** [comment] 2019-08-01 10:27
Looks like its the same issue as https://github.com/docker/for-win/issues/3375 which got closed as stale but didn't get fixed. Will fix now.

The settings file is at C:\Users\<username>\AppData\Roaming\Docker usually

**Comment by mschonwe** [comment] 2019-08-01 11:22
The crash error prevents the whale menu from appearing in the systray.

Editing the settings file is at C:\Users<username>\AppData\Roaming\Docker\settings.json to change `"dataFolder" : null` to `"dataFolder" : ""`, prevents the crash.  

Oddly the first time I made this change, I got a red whale with a path warning error.  I changed it back to `null` to see if the systray icon would appear (it didn't).  Then when changing back to `"dataFolder" : ""` and starting, it started w/o any errors at all.

Now that it is running, I can confirm this is on stable release.

**Comment by mikeparker** [comment] 2019-08-01 11:26
Great, thanks!

**Comment by mikeparker** [comment] 2019-08-01 11:30
To confirm, this is a duplicate of https://github.com/docker/for-win/issues/3375 so i'm closing, but we are fixing the root cause. Please see https://github.com/docker/for-win/issues/3375#issuecomment-515808417 for a workaround.

**Closed by mikeparker** 2019-08-01 11:30 UTC
Labels: status/1-acknowledged

**Comment by mikeparker** [comment] 2019-08-08 12:19
Docker Desktop 2.1.0.1 stable has been released with a fix for this now.
