### ISSUE TITLE
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by Venkateshkuntla** [docker/for-win#1825] opened 2018-03-13 09:00 UTC
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by heidricha** [comment] 2018-03-13 12:14
same for me. service looks like running, but no client can connect. user- or elevated level of command line.

G508031@RMM-P7000032FW MINGW64 /
$ net start com.docker.service
The Docker for Windows Service service is starting.
The Docker for Windows Service service was started successfully.


G508031@RMM-P7000032FW MINGW64 /
$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

G508031@RMM-P7000032FW MINGW64 /
$ net start com.docker.service
The requested service has already been started.

**Comment by shaneasullivan** [comment] 2018-03-14 01:25
I had the same issue - I was able to resolve the issue by running power shell with Admin privs.  I validated this was the same behavior for running the commands via elevated cmd prompt.  It also enabled `docker run hello-world` command which was returning the error message `...Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

**Comment by mmggbj** [comment] 2018-03-15 07:57
i have the same problem,how to resovle?

**Comment by heidricha** [comment] 2018-03-15 08:09
Solved for me. Run docker desktop app, check in notification. Setup if necessary...
Be happy.

**Comment by rn** [comment] 2018-04-30 15:00
Closing this issue. @Venkateshkuntla, if you still have the problem, please re-open and supply a diagnostics ID and detaisl of your setup (Docker for Windows version etc).

**Closed by rn** 2018-04-30 15:00 UTC

**Comment by girishgodage** [comment] 2018-07-18 05:41
I had the same issue - I was able to resolve the issue by running power shell with Admin privs.

**Comment by rorygilfillan** [comment] 2018-08-03 08:43
I have the same issue since I upgraded. Powershell in admin mode doesn't help.

PS C:\WINDOWS\system32> docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by mlenser** [comment] 2018-08-28 08:27
Same issue as @rorygilfillan. Docker is on my PATH, but I get:
`
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
`

**Comment by fluggo** [comment] 2018-09-01 19:16
Same issue. Diagnostics ID 67ED6A1F-C0B5-466D-9BC3-DF0228895023/20180901135537

**Comment by Relaxe111** [comment] 2018-09-11 22:05
same issue:
Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by ducquoc** [comment] 2018-09-25 14:12
I fixed this issue by settings the certificate environment variables (for SSH/TLS): 

```
SET DOCKER_CERT_PATH=%UserProfile%\.docker\machine\machines\HypervDefault
SET DOCKER_MACHINE_NAME=HypervDefault
SET DOCKER_HOST=tcp://192.168.1.15:2376
SET DOCKER_TLS_VERIFY=1
```

The problem began when I created the "HypervDefault" machine, and deleted the "default" machine, which can be verified with docker-machine commands: 
```
docker-machine ls
docker-machine env HypervDefault
FOR /f "tokens=*" %i IN ('docker-machine env HypervDefault') DO @%i
```

The above commands might need to run with Admin privileges (elevated), and make sure docker service is running: `net start com.docker.service` . Then the docker commands can run well: 
```
docker ps
docker image ls
docker container ls --all
```

-Duc

**Comment by blueyestar** [comment] 2018-10-19 14:05
@ducquoc does not work at step FOR /f "tokens=*" %i IN ('docker-machine env HypervDefault') DO @%i

Windows 10 Home/ AMD64

**Comment by zilurrane** [comment] 2018-10-28 16:16
```
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon
```
In Powershell elevated access solved my issue.

**Comment by prabuddha93** [comment] 2018-10-30 11:37
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> In Powershell elevated access solved my issue.

Thanks!

**Comment by ManikantaCV** [comment] 2018-11-21 08:44
@prabuddha93: Issue solved with your solution. Thank you

**Comment by mikfaina** [comment] 2018-11-22 15:18
Me too

**Comment by alkreddy** [comment] 2018-11-26 17:09
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon

Especially on windows machine when you see the above error after a docker update, try the above commands. It appears like the Docker Desktop UI may indicate that you are already using Linux Containers, but the update may have messed up that setting. Running the above commands will set to Linux Containers and there after you can work happily.

**Comment by bhanotra** [comment] 2018-12-04 05:59
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> In Powershell elevated access solved my issue.

worked for me as well

**Comment by muedd** [comment] 2018-12-06 06:49
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon 

this worked for me..Thank you very much

**Comment by naywin-programmer** [comment] 2018-12-07 05:52
open with powershell, It work for me.

**Comment by ngie-eign** [comment] 2018-12-10 18:37
> > ```
> > cd "C:\Program Files\Docker\Docker"
> > ./DockerCli.exe -SwitchDaemon
> > ```
> > In Powershell elevated access solved my issue.
> 
> Thanks!

This isn't a workable solution, to be honest, since it [likely] papers over an issue with Linux Containers and switches it over to Windows containers.

There's a problem with the interoperability of Docker, HyperV, Linux containers, and security levels (in my case) that are preventing me from making progress.

I'm going to look around a bit more for instructions, and if all else fails, screw it and install a Unix desktop on my corporate laptop in order to get my job done.

**Comment by ngie-eign** [comment] 2018-12-10 18:59
For anyone else reading this thread, the error message is coming from HyperV.

**Comment by ngie-eign** [comment] 2018-12-19 00:52
> > ```
> > cd "C:\Program Files\Docker\Docker"
> > ./DockerCli.exe -SwitchDaemon
> > ```
> > In Powershell elevated access solved my issue.
> 
> Thanks for this. It solve my issue.

As noted previously, this switches Docker from Linux to Windows containers. This doesn't likely fix the underlying issue; it only papers over the fact that there's an issue with HyperV interacting with Docker.

**Comment by StudioDove** [comment] 2018-12-29 15:42
I had the same issue very recently and was able to get it working again pretty easily:

`Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
`

I fixed it by using "Reset to factory defaults..." under Settings > Reset.

Of course I had to sign in again and all my containers were gone, so I had to re-download everything but that's not a big deal, after all that is what docker is for, right!

**Comment by doomtoo** [comment] 2019-01-09 23:44
Seems docker toolbox gets messed up when you reinstall it/ uninstall/ reinstall it. 

I had to first delete the path variables, then run C:\Program Files\Docker Toolbox\start.sh, and was able to run 'docker info' without the error.

**Comment by serdarulutas** [comment] 2019-01-15 20:17
Running PowerShell as Admin sold my issue as well.

**Comment by yasemindogan93** [comment] 2019-01-17 08:59
Solved: 
- Go to Docker-Icon -- >right click and select settings. 
- activating "expose daemon on tcp://...without tls".
- check in powershell by simple 'docker ps'

**Comment by jorbensaaltink** [comment] 2019-01-18 19:24
Switch from Windows containers to Linux containers. Works for me ;)

**Comment by jorbensaaltink** [comment] 2019-01-18 19:50
Switch from Windows containers to Linux containers. Works for me ;)

**Comment by yasemindogan93** [comment] 2019-01-18 20:19
Seems there are several reasons after docket updates on windows. 
Should be more consistent.

**Comment by yoesak** [comment] 2019-01-20 09:56
I also get this error message, 

and this solution 
`cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon`

only switch from Linux Container to Windows Container, 

But in my case, the problem was somehow the permission to the 'C:\ProgramData\Docker\config\daemon.json' is missing, so the docker read the configration file, by granted the 'CREATOR OWNER' user to access the file, the problem gone

**Comment by adinunzio84** [comment] 2019-02-13 21:04
Same issue, and like @ngie-eign we need to use Linux containers. Anyone find a solution for Linux containers on Windows with hyper-v?

**Comment by levdikpavel** [comment] 2019-02-21 07:04
Had the same issue

I just run "DockerCli.exe -SwitchDaemon" twice, to switch back to Linux containers, and the error has gone, and I got back my 270 images, now I am happy

**Comment by olavorn** [comment] 2019-02-22 11:07
For me, this issue happened in My Windows 10 Pro when it recovered from a hibernation. 
```
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon
```
Didn't solve cause daemon was already started. So there was an access denied error. 

I suspect if the DockerCli already running, you can set and unset "Expose daemon on tcp:..."
![image](https://user-images.githubusercontent.com/3752407/53238648-94af4280-3678-11e9-8337-6e478742e312.png)

That worked for me.

**Comment by ngie-eign** [comment] 2019-02-22 15:57
@olavorn: that exposes the docker daemon over unencrypted TLS, which is obviously insecure. Check the firewall and permissions for the daemon.

**Comment by olavorn** [comment] 2019-02-22 18:35
@ngie-eign: That's why i mentioned "set and **unset**" ;)

**Comment by RatanGithub** [comment] 2019-03-27 00:09
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> In Powershell elevated access solved my issue.

This resolved  the issue

**Comment by pengfeidip** [comment] 2019-04-06 00:54
> Solved:
> 
> * Go to Docker-Icon -- >right click and select settings.
> * activating "expose daemon on tcp://...without tls".
> * check in powershell by simple 'docker ps'

----
@yasemindogan93  win10 pro , useful!

**Comment by Baharul1** [comment] 2019-04-07 16:03
Hi ,

I am also getting same error. I am have tried with AWS & Azure VM . Also have tried with windows powershell , but still getting same error always.

**Comment by alian-sevatec** [comment] 2019-04-18 20:38
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> 
> this worked for me..Thank you very much

This worked for me after trying many things without success. Thank you so much!

**Comment by thiagosrios** [comment] 2019-04-23 13:21
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> In Powershell elevated access solved my issue.

This solved for me. Thanks!!

**Comment by erzhu4** [comment] 2019-05-01 16:14
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

OMG You are a life saver!!!!

**Comment by olisteadman** [comment] 2019-05-22 10:39
For me the error was resolved by **stopping a virtual Ubuntu instance** that'd been running in Hyper-V:

`The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

Once Ubuntu instance had been stopped, and Docker Desktop had been restarted, my usual docker commands ran just fine. 

PS: I had the idea to try this because of an Error Log that Docker Desktop had helpfully compiled and offered to send to Docker Hub as user feedback... the log appeared to indicate that **my machine was short on RAM**, and Docker was failing for this very simple reason. Killing the Ubuntu instance solved that.

**Comment by tschach** [comment] 2019-06-07 07:39
I solved this issue by switching from executing `docker pull ...` in `powershell` to executing it in `cmd`. Elevated powershell did not work for me, I did not try the other solutions.

**Comment by sammy111286** [comment] 2019-07-08 07:25
I faced the same issue . I tried the elevated powershell but it was of no use . So I tried restarting the system , but still it didn't work for a few minutes. The thing was , it takes some time to bring up the docker sometimes even when the docker icon in the taskbar is stable . Once it is stable you can execute "net start com.docker.service" on the powershell .  It would generate the message - "The requested service has already been started." if it is already up. and then try the docker commands.

**Comment by ank2311** [comment] 2019-07-11 19:48
Please help with docker  Diagonse ID : 7313DB8A-55BD-4221-81CE-61FCF9C43151/20190711154240

Error during connect.
Please assist.

**Comment by PatOShea** [comment] 2019-07-16 16:38
I got this when trying to pull from my own registry. Once I logged in the pull worked fine:
* docker login URL:port 
(prompts for login credentials)
* docker pull URL:port/path <- successful this time

**Comment by niemyjski** [comment] 2019-07-30 16:00
The powershell tip helped me but then I got `ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version           `

**Comment by abdulqadir53** [comment] 2019-08-19 07:13
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

Worked like a charm! Many thanks

**Comment by abhikrr** [comment] 2019-09-03 11:26
Got the same error. When i checked the notification it asked me to login with docker account and then it worked.

**Comment by inspiretk** [comment] 2019-09-06 06:24
I had same problem Windows 7. Tried some of the above, nothing worked. I fixed mine by going into Docker Toolbox folder, and double clicking start.sh

C:\Program Files\Docker Toolbox
Find start.sh
Double click start.sh

Wait for it to finish, then it'll work.

> docker is configured to use the default machine with IP 192.168.99.101
> For help getting started, check out the docs at https://docs.docker.com
> 
> 
> Start interactive shell

**Comment by kid1412621** [comment] 2019-09-06 06:31
also found this error will show when docker desktop is updating

**Comment by inspiretk** [comment] 2019-09-07 04:32
I fixed my error properly with this:
Find your shortcut (should be on desktop): Docker Quickstart Terminal
- Right click that file > Go to Properties > Target: C:\Program\Git\bin\bash.exe  
Make sure the bash.exe is pointing to the correct git bash file. I changed mine to the correct path and it worked.
Full Target path is C:\Program\Git\bin\bash.exe --login -i "C:\Program Files\Docker Toolbox\start.sh"

Now double click on that shortcut (Docker Quickstart Terminal), and it will work.

**Comment by soldierm** [comment] 2019-09-10 06:08
> I had same problem Windows 7. Tried some of the above, nothing worked. I fixed mine by going into Docker Toolbox folder, and double clicking start.sh
> 
> C:\Program Files\Docker Toolbox
> Find start.sh
> Double click start.sh
> 
> Wait for it to finish, then it'll work.
> 
> > docker is configured to use the default machine with IP 192.168.99.101
> > For help getting started, check out the docs at https://docs.docker.com
> > Start interactive shell

This helps me! tks

**Comment by AlexandroGonSan** [comment] 2019-10-01 23:49
Usa o Docker QuickStart Terminal .

**Comment by tharindu-kalhara** [comment] 2019-11-21 09:44
if you are on windows please make sure you have checked this.
![ScreenShot_20191121174317](https://user-images.githubusercontent.com/20641865/69326332-8c774880-0c86-11ea-87a5-aa079dc7a151.png)

**Comment by qub1n** [comment] 2019-12-02 13:07
Just run Docker desktop. The message is pretty bad, they are talking about "default deamon", but in reality, you need to run Docker Desktop.

It is possible to change the message to "Docker desktop is not running, please start it."?

**Comment by sandep1987** [comment] 2019-12-03 13:38
This worked for me, thank you!!

cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

**Comment by vishalkumar392392** [comment] 2019-12-19 05:37
> Solved for me. Run docker desktop app, check in notification. Setup if necessary...
> Be happy.

can please elobrate your answer step by step

**Comment by MukeshMohanty** [comment] 2019-12-25 11:00
this solved for me

```
docker-machine env docker01 
docker-machine env docker01 | Invoke-Expression
```

basically this sets the evironment variables like host, tlc etc. which is required for docker to connect

**Comment by leolovesmile** [comment] 2019-12-27 09:09
First, make sure you have at least a `docker-machine` and it running without any problem:
```
docker-machine ls
```

In my case, I have no docker-machine, so I created one, based on virtualbox driver:
```
docker-machine create -d virtualbox leolovesmile
```

After this, run `docker-machine env` to make sure the environment is updated based on the latest system status. In the output of the command execution, it suggested me that:
> REM Run this command to configure your shell:
> REM     @FOR /f "tokens=*" %i IN ('"C:\Users\leolovesmile\scoop\apps\docker\current\docker-machine.exe" env') DO @%i  

So, run the command as asked:
```
@FOR /f "tokens=*" %i IN ('"C:\Users\leolovesmile\scoop\apps\docker\current\docker-machine.exe" env') DO @%i
```
Then, everything should works well.

**Comment by aanchal960** [comment] 2020-01-09 09:06
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> This helped

**Comment by jofisiva** [comment] 2020-01-29 03:25
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

worked for  me as well

**Comment by DeividReinkeSchiitz** [comment] 2020-02-01 02:19
worked for me running the Docker Desktop as a admin

**Comment by hajimurtaza** [comment] 2020-02-20 16:31
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

Can you elaborate what you resolved?

**Comment by StanleyNdunwere** [comment] 2020-02-22 01:08
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

Worked! 💯

**Comment by paynetechnologies** [comment] 2020-03-09 15:32
On Windows 10 - Hyper-V was not running.

**Comment by Cloudmersive** [comment] 2020-03-11 23:07
This is still completely broken.  How is this closed?

**Comment by hejunion** [comment] 2020-03-14 19:48
> 
> 
> I fixed this issue by settings the certificate environment variables (for SSH/TLS):
> 
> ```
> SET DOCKER_CERT_PATH=%UserProfile%\.docker\machine\machines\HypervDefault
> SET DOCKER_MACHINE_NAME=HypervDefault
> SET DOCKER_HOST=tcp://192.168.1.15:2376
> SET DOCKER_TLS_VERIFY=1
> ```
> 
> The problem began when I created the "HypervDefault" machine, and deleted the "default" machine, which can be verified with docker-machine commands:
> 
> ```
> docker-machine ls
> docker-machine env HypervDefault
> FOR /f "tokens=*" %i IN ('docker-machine env HypervDefault') DO @%i
> ```
> 
> The above commands might need to run with Admin privileges (elevated), and make sure docker service is running: `net start com.docker.service` . Then the docker commands can run well:
> 
> ```
> docker ps
> docker image ls
> docker container ls --all
> ```
> 
> P.S: If your local IP Address (NAT) changes, for example: 192.168.1.3 --> 192.168.1.15 ; you can re-generate the certs (and it will auto update `config.json` for the machine respectively)
> `docker-machine regenerate-certs [machine-name]`
> 
> -Duc

Right for me.

**Comment by imoisharma** [comment] 2020-03-24 12:10
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

I am trying to run but not able to resolve the issue and secondly, after installing I've only docker toolbox inside program files because of windows 10 basic. Kindly help me to resolve the issue

**Comment by qinyanjuidavid** [comment] 2020-03-28 05:43
I used Anaconda it worked but on cmd it failed.

**Comment by letmerecall** [comment] 2020-04-17 14:35
In my case docker service was not running.

Steps to start:
Check `Docker Desktop Service` in Services (run > services.msc).
Sart that if not running.

![docker](https://user-images.githubusercontent.com/19938474/79580479-abb7bc00-80e6-11ea-9945-f75d10e3d45a.PNG)

**Comment by XimikRU** [comment] 2020-04-21 12:47
> 
> 
> I fixed this issue by settings the certificate environment variables (for SSH/TLS):
> 
> ```
> SET DOCKER_CERT_PATH=%UserProfile%\.docker\machine\machines\HypervDefault
> SET DOCKER_MACHINE_NAME=HypervDefault
> SET DOCKER_HOST=tcp://192.168.1.15:2376
> SET DOCKER_TLS_VERIFY=1
> ```
> 

Helped.

**Comment by darshankumarys** [comment] 2020-04-30 23:46
This fixed the issue in Windows machine.

MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

**Comment by sinistram** [comment] 2020-05-13 13:51
I had the same problem in Win Server 2019. I just opened Services and started Docker Engine service.
It is strangely, but the service does not starting after installation in his own.

**Comment by akoua** [comment] 2020-05-14 10:40
> @ducquoc does not work at step FOR /f "tokens=*" %i IN ('docker-machine env HypervDefault') DO @%i
> 
> Windows 10 Home/ AMD64

You must already change EditionID  on register there Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion

**Comment by eaniket** [comment] 2020-05-15 15:21
1. Run 'dockerd.exe' located in 'C:\Program Files\Docker\Docker\resources' .
2. Now execute 'docker version' on a new powershell as administrator

**Comment by hoanganh130893** [comment] 2020-05-27 16:09
Hey it fixed ,  
Try to run this command :
`docker-machine env`
You will see this:
`export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\LAP13670-local\.docker\machine\machines\default"
export DOCKER_MACHINE_NAME="default"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env)
`
then run this command on your shell
`eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env)`

=> Your problem was solved
![image](https://user-images.githubusercontent.com/36719435/83044895-01c93900-a06f-11ea-80b1-f539b24b52ab.png)

**Comment by vivekarya-code** [comment] 2020-06-04 19:44
I ran Docker Desktop and restarted my system and it worked.

**Comment by WuYouyan** [comment] 2020-06-07 17:19
> I had same problem Windows 7. Tried some of the above, nothing worked. I fixed mine by going into Docker Toolbox folder, and double clicking start.sh
> your installation directory\Docker Toolbox
> Find start.sh
> Double click start.sh
> Wait for it to finish, then it'll work.
> docker is configured to use the default machine with IP 192.168.99.101
> For help getting started, check out the docs at https://docs.docker.com
> Start interactive shell

Win 10 familly/ intel i5
This helps me too! tks

**Comment by taro-hida** [comment] 2020-06-11 03:00
I'm encountered same error in powershell on Windows10 Pro, Version 1909. I run docker on HyperV.

Docker Desktop Service was runnning. Restarting Docker Desktop Service finished successfully but same error appeared.
I restart OS, but same error appeared.

I ran docker desktop app, and did tutorial.
Tutorial has finished successfully, And after that, I successfully run docker command.

PS > docker --version
Docker version 19.03.8, build afacb8b

Installed Docker Desktop for Windows's channel is "stable" one.

**Comment by AnujSR02** [comment] 2020-06-11 09:35
> ### Expected behavior
> ### Actual behavior
> ### Information
> * Diagnostic ID from "Diagnose & Feedback" in the menu.
> * a reproducible case if this is a bug, Dockerfiles FTW
> * page URL if this is a docs issue or the name of a man page
> * host distribution and version (Windows version, build number, etc)
> 
> ### Steps to reproduce the behavior
> 1.  Installing the latest version of Virtual Box resolved this issue.

**Comment by eschrader** [comment] 2020-06-27 01:33
I uninstalled the Hyper-V service and network adapters a while ago. I think that broke my docker install

**Comment by aritrey** [comment] 2020-06-27 21:33
I had the same error message and for me it was my antivirus program that interfered with running docker. I had to switch of the real time scan. (I use avira).

**Comment by carlosb-awlatam** [comment] 2020-07-03 00:38
Run 'dockerd.exe' located in 'C:\Program Files\Docker' work for me

**Comment by danielsouzasp** [comment] 2020-07-05 22:53
I had the same problem but I'm using "minkube", then I just ran: "minikube docker-env" to see  and se the correct env on windows prompt.

**Comment by bin-y** [comment] 2020-07-10 17:15
If anyone getting error like "error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/ ... archive/tar: write too long"
the problem seems caused by symlinks in the folder.
I solved the problem by removing symlinks inside the folder
reference: https://github.com/kubernetes/kompose/issues/656

**Comment by alvaromon** [comment] 2020-07-15 18:53
This is an issue for me i downloaded the latest docker and Terraform. I cant use the Docker provider because the docker_host value isnt working ive look everywhere tried all solutions:

- turn on experimental cli mode
- using localhost as docker host
- using named pipe as docker host
- restarting docker service
- using dockertools for docker-machine to see VM host value

after using docker machine and creating a VM i noticed the VM was using IPv6? what does this mean

docker env output:
```
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://[fe80::215:5dff:fe10:900]:2376
SET DOCKER_CERT_PATH=C:\Users\nomsuser\.docker\machine\machines\mydockervm
SET DOCKER_MACHINE_NAME=mydockervm
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env mydockervm') DO @%i
```

 useful info:
- i am on a brand new Windows Server 2019
- to create VM using docker-machine i had to create a external switch in HyperV Manager
- used `docker-machine.exe create --driver hyperv --hyperv-virtual-switch "myexternalswitch" --hyperv-cpu-count "1" --hyperv-memory "1024" --hyperv-disk-size "20000" mydockervm` to create VM

**Comment by earagol** [comment] 2020-07-18 19:58
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon

Muchas gracias...

**Comment by dhb33** [comment] 2020-07-23 21:57
> This fixed the issue in Windows machine.
> 
> MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon

Elevated, this solve the issue. I really think the problem came my return to my good old win10 version. The newest version can make Docker run without Hyper-V. The 1st thing that happened when running the new Win10 version is Docker telling me he will use the new capacity.

**Comment by funkkyexalter** [comment] 2020-07-30 21:40
There was no such folder in my Windows 10:
> "C:\Program Files\Docker\Docker"

I got it running by the following command in windows PowerShell:
`& "C:\ProgramData\chocolatey\lib\docker-machine\bin\docker-machine.exe" env dev | Invoke-Expression`

And then I was able to get the following output:
```
PS C:\WINDOWS\system32> docker version
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        0ed913b8-
 Built:             07/28/2020 16:36:03
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by ImanCol** [comment] 2020-08-10 18:10
> For anyone else reading this thread, the error message is coming from HyperV.

Running pre-create checks...
Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"
Looks like something went wrong in step ´Checking if machine default exists´... Press any key to continue..

![image](https://user-images.githubusercontent.com/26169049/89815716-df41aa80-db0a-11ea-8929-8a8b443b4b57.png)

**Comment by stidiovip** [comment] 2020-08-11 10:10
> ```
> cd "C:\Program Files\Docker\Docker"
> ./DockerCli.exe -SwitchDaemon
> ```
> 
> In Powershell elevated access solved my issue.

This is the solution. Juste wait sill docker service notifies before trying your docker command again ;)
