### ISSUE TITLE
Need a host network/driver for windows like linux has

### ISSUE THREAD

**Issue by AlexisColes** [docker/for-win#1843] opened 2018-03-16 11:47 UTC
**docker network ls**

### Expected behavior
list a host network
**eaf790e6dacb        host                host                local**

### Actual behavior
No host network :(

**Comment by rn** [comment] 2018-03-16 19:43
this issue has no details about versions, if you use windows or Linux containers or LCOW etc and what the issue is, so closing.

**Closed by rn** 2018-03-16 19:43 UTC
