### ISSUE TITLE
Can't execute any docker commands on Windows10

### ISSUE THREAD

**Issue by TapaniRundgren** [docker/for-win#465] opened 2017-02-06 07:24 UTC
### Expected behavior
docker ps
<list running processes>
### Actual behavior
$ docker ps
Exception 0xc0000005 0x0 0x0 0x18000890a
PC=0x18000890a

syscall.Syscall(0x7ffe6030dc40, 0x2, 0x284, 0x3, 0x0, 0x0, 0x0, 0x288)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x284, 0x203, 0x0, 0xffffffff)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:88 +0x6f
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.makeWin32File(0x284, 0xc0423e1890, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:78 +0xd8
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.DialPipe(0xc0420d30e8, 0x16, 0xc0423e1980, 0x0, 0x1130920, 0xc041fe0aff, 0xc0423e19f8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/pipe.go:188 +0x537
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc0420d30e8, 0x16, 0x773594000, 0xc04203c001, 0x1000000000010, 0x100, 0x100)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xba4a6f, 0x3, 0xc0423a55a0, 0x19, 0x60, 0x0, 0xc0423e8001, 0xc0423e4180)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0423d4870, 0xf10040, 0xc042044198, 0xba4a6f, 0x3, 0xc0423a55a0, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:829 +0x82
net/http.(*Transport).dialConn(0xc0423d4870, 0xf10040, 0xc042044198, 0x0, 0xba519b, 0x4, 0xc0423a55a0, 0x19, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:967 +0x1a8c
net/http.(*Transport).getConn.func4(0xc0423d4870, 0xf10040, 0xc042044198, 0xc0423caff0, 0xc0423d2d80)
        /usr/local/go/src/net/http/transport.go:885 +0x7f
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x3a8

goroutine 1 [select]:
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do(0xf10300, 0xc0420453c8, 0xc0423caf30, 0xc0423d4960, 0xc0423d4960, 0xc0421779e0, 0x59998c)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x40a
github.com/docker/docker/client.(*Client).doRequest(0xc0423d6200, 0xf10300, 0xc0420453c8, 0xc0423d4960, 0x6, 0x0, 0x0, 0x0, 0xc0423d4960, 0x0)
        /go/src/github.com/docker/docker/client/request.go:127 +0x75
github.com/docker/docker/client.(*Client).Ping(0xc0423d6200, 0xf10300, 0xc0420453c8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/client/ping.go:17 +0x1d4
github.com/docker/docker/cli/command.(*DockerCli).Initialize(0xc0421b34a0, 0xc042310e20, 0x2, 0xc0423a38c0)
        /go/src/github.com/docker/docker/cli/command/cli.go:158 +0x181
main.newDockerCommand.func2(0xc0423a38c0, 0xf67690, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/docker/docker.go:48 +0xa9
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc0423a38c0, 0xc04204a3b0, 0x0, 0x0, 0xc0423a38c0, 0xc04204a3b0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:628 +0x578
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042091680, 0xc042091b00, 0xc04232aca0, 0xc042070420)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x37e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042091680, 0xc042091680, 0xf07d40)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:104 +0xeb

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 19 [select]:
net/http.(*Transport).getConn(0xc0423d4870, 0xc0423a5580, 0x0, 0xba519b, 0x4, 0xc0423a55a0, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:890 +0x9d3
net/http.(*Transport).RoundTrip(0xc0423d4870, 0xc0423d4960, 0xc0423d4870, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:367 +0x30e
net/http.send(0xc0423d4960, 0xf07700, 0xc0423d4870, 0x0, 0x0, 0x0, 0x8, 0xc042070558, 0x411cef)
        /usr/local/go/src/net/http/client.go:256 +0x166
net/http.(*Client).send(0xc0423caf30, 0xc0423d4960, 0x0, 0x0, 0x0, 0xc042070558, 0x0, 0x1)
        /usr/local/go/src/net/http/client.go:146 +0x109
net/http.(*Client).doFollowingRedirects(0xc0423caf30, 0xc0423d4960, 0xc28d00, 0x3, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:528 +0x5ec
net/http.(*Client).Do(0xc0423caf30, 0xc0423d4960, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:184 +0x1f1
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc0423caf30, 0xc0423d4960, 0xc28620, 0xc0423d2d20)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:51 +0xe4

goroutine 33 [syscall, locked to thread]:
syscall.Syscall6(0x7ffe60306bf0, 0x5, 0x288, 0xc0423dbf5c, 0xc0423dbf60, 0xc0423dbf68, 0xffffffff, 0x0, 0x7ffe5bc63040, 0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x288, 0xc0423dbf5c, 0xc0423dbf60, 0xc0423dbf68, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:76 +0xc6
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x288)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:129 +0x82
created by github.com/docker/docker/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
rax     0x0
rbx     0xc04203c368
rcx     0x284
rdi     0x2f2000
rsi     0xc0423e17a0
rbp     0xc0423e1750
rsp     0x14cfd98
r8      0x1
r9      0x0
r10     0x284
r11     0x131dbb8
r12     0x0
r13     0xd3
r14     0xc24eb7
r15     0x3
rip     0x18000890a
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
681F4ADB-8A80-44D0-BE66-808A23B787C3/2017-02-06_08-16-22
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise
Version 1607
OS build 14393.693
Docker Version 1.13.1-rc1-beta40 (9961)
Channel: beta
0d026e1

### Steps to reproduce the behavior
Have reinstalled Docker, even tested with Stable version - same result - will rollback lates security update 
to check if that caused the problem.
Have been working very well until this happened few days ago

**Comment by rneugeba** [comment] 2017-02-06 11:04
Looks like you are hitting the same issues others are hitting. The issue is already tracked:
- https://github.com/docker/docker/issues/27423
- https://github.com/Microsoft/go-winio/issues/34
so I'm closing this issue.
Thanks for reporting.

**Closed by rneugeba** 2017-02-06 11:04 UTC
