### ISSUE TITLE
An error occurred when launching

### ISSUE THREAD

**Issue by stemurphy** [docker/for-win#3917] opened 2019-05-15 07:58 UTC
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544

### Expected behavior
Docker to launch when started

### Actual behavior
An Error Occurred

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'LAPTOP25VUASVQ' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
  - Is it reproducible?
 Yeah the issue occurs every time I try to launch Docker. If I click "Reset to factory defaults" it presents the error once again
  - Is the problem new?
first time installation on this machine and always occurs
  - Did the problem appear with an update?
N/A
  - A reproducible case if this is a bug, Dockerfiles FTW.
1. Start Windows 10 
2. Launch Docker
  - Windows Version: 
10.0.17763 (Build 17763)
  - Docker for Windows Version: 
2.0.0.3 (31259)

### Docker log.txt

Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/05/15 08:45:38.689
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\STEPHENMurphy\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[08:45:38.932][GUI            ][Info   ] Starting...
[08:45:39.066][ComponentVersions][Info   ] Edition community
[08:45:39.069][GUI            ][Error  ] An instance is already running. Exiting.
[08:45:39.052][HyperV         ][Info   ] Script started at 08:45:39.045
[08:45:42.092][HyperV         ][Info   ] Modules loaded at 08:45:42.092
[08:45:42.362][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[08:45:42.362][HyperV         ][Debug  ] [stop] took 00:00:04.2703494 to run
[08:45:42.363][OptimizeDisk   ][Info   ] Optimize
[08:45:42.364][PowerShell     ][Info   ] Run script...
[08:45:42.452][Moby           ][Info   ] Stop
[08:45:42.464][HyperVGuids    ][Info   ] Installing GUIDs...
[08:45:42.464][PowerMode      ][Info   ] Start
[08:45:42.467][HyperVGuids    ][Info   ] GUIDs installed
[08:45:42.469][HyperV         ][Info   ] Create
[08:45:42.472][Firewall       ][Info   ] Removing all existing rules...
[08:45:42.483][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[08:45:42.494][HyperV         ][Info   ] Script started at 08:45:42.494
[08:45:42.528][Firewall       ][Info   ] All existing rules are removed.
[08:45:42.528][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[08:45:42.530][HyperV         ][Info   ] Modules loaded at 08:45:42.530
[08:45:42.544][Firewall       ][Info   ] Opening ports for SMB...
[08:45:42.564][Firewall       ][Info   ] Ports are opened
[08:45:42.793][HyperV         ][Info   ] Creating Switch: DockerNAT...
[08:45:43.087][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '[LAPTOPNAME_NOSPECIALCHARACTERS]' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411. Let's retry
[08:45:43.150][HyperV         ][Info   ] Hyper-V is running
[08:45:43.150][PowerMode      ][Info   ] Stop
[08:45:43.151][HyperV         ][Info   ] Stop
[08:45:43.151][PowerShell     ][Info   ] Run script with parameters: -Stop True
[08:45:43.159][HyperV         ][Info   ] Script started at 08:45:43.159
[08:45:43.181][HyperV         ][Info   ] Modules loaded at 08:45:43.180
[08:45:43.282][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[08:45:43.282][HyperV         ][Debug  ] [stop] took 00:00:00.1314397 to run
[08:45:43.282][OptimizeDisk   ][Info   ] Optimize
[08:45:43.282][PowerShell     ][Info   ] Run script...
[08:45:43.359][Moby           ][Info   ] Stop
[08:45:43.365][HyperV         ][Info   ] Destroy
[08:45:43.366][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[08:45:43.375][HyperV         ][Info   ] Script started at 08:45:43.375
[08:45:43.387][HyperV         ][Info   ] Modules loaded at 08:45:43.387
[08:45:43.467][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[08:45:43.471][HyperV         ][Info   ] Destroying Switch DockerNAT...
[08:45:43.634][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[08:45:43.733][HyperV         ][Debug  ] [destroy] took 00:00:00.3679263 to run
[08:45:43.734][Firewall       ][Info   ] Closing ports...
[08:45:43.734][Firewall       ][Info   ] Removing all existing rules...
[08:45:43.856][Firewall       ][Info   ] All existing rules are removed.
[08:45:43.856][Firewall       ][Info   ] Ports are closed
[08:45:43.857][HyperVGuids    ][Info   ] Removing GUIDs...
[08:45:43.862][HyperVGuids    ][Info   ] GUIDs removed
[08:45:43.862][HyperV         ][Info   ] Create
[08:45:43.862][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[08:45:43.873][HyperV         ][Info   ] Script started at 08:45:43.873
[08:45:43.886][HyperV         ][Info   ] Modules loaded at 08:45:43.886
[08:45:44.050][HyperV         ][Info   ] Creating Switch: DockerNAT...
[08:45:44.321][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '[LAPTOPNAME_NOSPECIALCHARACTERS]' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 125
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[08:45:44.433][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '[LAPTOPNAME_NOSPECIALCHARACTERS]' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[08:45:44.443][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '[LAPTOPNAME_NOSPECIALCHARACTERS]' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[08:45:44.494][NamedPipeClient][Info   ] Sending Version()...
[08:45:44.496][NamedPipeClient][Info   ] Received response for Version
[08:45:44.496][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\STEPHENMurphy\AppData\Local\Temp\ gather -id D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544, C:\Users\STEPHENMurphy\AppData\Local\Temp\D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544.zip)...
[08:45:44.495][NamedPipeServer][Info   ] Version()
[08:45:44.495][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:45:44.497][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\STEPHENMurphy\AppData\Local\Temp\ gather -id D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544, C:\Users\STEPHENMurphy\AppData\Local\Temp\D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544.zip)
[08:47:06.466][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[08:47:06.465][NamedPipeServer][Info   ] GatherDiagnostics done in 00:01:21.9676949.
[08:47:06.492][GUI            ][Info   ] Sending Bugsnag report 066a00e2-8c01-41f2-8172-a1408381766c...
[08:47:07.184][GUI            ][Info   ] Bugsnag report 066a00e2-8c01-41f2-8172-a1408381766c sent
[08:47:28.699][CrashReport    ][Info   ] Uploading diagnostics D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544
[08:47:52.750][CrashReport    ][Info   ] Uploaded succesfully diagnostics D966230B-A323-4C2E-A56A-FB5647E91EAF/20190515084544
[08:52:08.836][ErrorReportWindow][Info   ] Open logs

**Comment by ollisommer** [comment] 2019-05-15 09:19
I got the same issue. So far, I could only solve it, by disabling the Hyper-V, and installing Docker Toolbox (which is using VirtualBox instead Hyper-V).

**Comment by mikeparker** [comment] 2019-05-28 17:20
Possible duplicate of https://github.com/docker/for-win/issues/2110
May be caused by a windows update breaking Hyper-V, see 
https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt for fix

**Comment by mikeparker** [comment] 2019-05-30 15:00
Closing as duplicate of #2110

**Closed by mikeparker** 2019-05-30 15:00 UTC
Labels: area/hyper-v, related/windowsupdate, version/2.0.0.3
