### ISSUE TITLE
Docker Desktop 3.3.3 does not show container log while "docker logs" does

### ISSUE THREAD

**Issue by zam6ak** [docker/for-win#11251] opened 2021-05-19 17:57 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
for official image of PostgreSQL container, once query logging is enabled, the logs in Docker Desktop app stop displaying.
if I run "docker logs postgres" logging is shown.
I initially thought there was issue with container image itself and posted issue at:
https://github.com/docker-library/postgres/issues/845

But as described, its only in the desktop app that I am unable to see logs...

### Expected behavior

To be able to see "docker logs" output when I click on the container in the Desktop app

### Information

  - Windows Version:   Windows 10 Pro 20H2
  - Docker Desktop Version: 3.3.3 (64133)
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

In shell  no. 1
  1. `docker run -d --name postgres -e POSTGRES_PASSWORD=pass postgres -c log_statement=all`
  2. `docker exec -it postgres bash -c "psql -U postgres -c 'select version();'" `

In shell  no. 2
   1. `docker logs --follow postgres`

The shell no. 2 will display 
> 2021-05-19 17:53:56.520 UTC [89] LOG:  statement: select version();

but the same log entry is not visible in LOGS tab of the running container

**Comment by twkrol** [comment] 2021-05-19 19:31
Same problem here.
When I start my containers with docker-compose up (without -d) I can observe live logs on my shell console, but not in Docker Desktop anymore.

**Comment by yamamoo** [comment] 2021-05-19 19:53
I have the same problem. For example, when I run `docker run -d --name jenkins jenkins/jenkins:lts`, I see only the first two lines of log messages in the log viewer like this:
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
```
But if I run `docker logs jenkins`, I see all the logs as expected.
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-05-18 02:43:55.728+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @305ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-05-18 02:43:55.829+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2021-05-18 02:43:56.827+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2021-05-18 02:43:56.872+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.39.v20210325; built: 2021-03-25T14:42:11.471Z; git: 9fc7ca5a922f2a37b84ec9dbc26a5168cee7e667; jvm 1.8.0_292-b10
2021-05-18 02:43:57.107+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
... more lines ...
```
I see this on both Windows and Mac version of Docker Desktop 3.3.3.

**Comment by StefanScherer** [comment] 2021-05-20 06:47
@zam6ak Thank you for reporting this. It looks like the Docker Desktop UI does not show the stderr logs. I've created an internal ticket to track this issue. We'll update this public issue once we've fixed it.

**Comment by thaJeztah** [comment] 2021-05-20 06:54
Ah! I thought of that possibility wanted to test that after I posted

**Comment by thaJeztah** [comment] 2021-05-20 06:55
Ah! Thought of that possibility after I posted, but didn't test that yet; thanks!

**Comment by segatrade** [comment] 2021-05-29 08:56
Same problem on
Windows Version: Windows 10 Pro 21H1
Docker Desktop Version: 3.3.3 (64133)
WSL2 or Hyper-V backend? WSL 2
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

**Comment by segatrade** [comment] 2021-05-29 10:20
Reinstalled to Docker Desktop Version: 3.3.2 (63878)
and got the same problem(

"I confirm that downgrade to Docker Desktop v3.3.1 resolved my issue." Should I try 3.3.1?

**Comment by mat007** [comment] 2021-06-10 06:51
A fix has been released in Docker Desktop 3.4.0, see [the release notes](https://docs.docker.com/docker-for-windows/release-notes/#bug-fixes-and-minor-changes)!

**Comment by twkrol** [comment] 2021-06-10 07:33
Installed 3.4.0 and it works, but... the live log is somehow broken - extra newline is added after every new line, but historical log entries (eg. when you switch to/from another container) are displayed without newlines between entries.

**Comment by mat007** [comment] 2021-06-10 07:50
@twkrol thanks for the feedback, we’ll look into it.
Sorry about that!

**Comment by zam6ak** [comment] 2021-06-11 22:44
Not only are new lines added (as @twkrol  mentioned), the formatting of the log message is completely "stripped".
If the log entry itself has tab or space indentations, they seem to be removed.
Looking at the output of EXPLAIN ANALYZE for example (via auto explain module) on PostgreSQL

This is what docker logs shows
```
2021-06-11 18:35:40 EDT [7871]: [7-1] user=postgres,db=pacs_live,app=pgAdmin 4 - CONN:3049286,client=192.168.168.6 LOG:  duration: 179.172 ms  plan:
        Query Text: select * from cpt_codes where not has_deleted or deleted_dt is null

        Seq Scan on public.cpt_codes  (cost=0.00..1533.72 rows=13972 width=1112) (actual time=0.011..22.485 rows=13972 loops=1)
          Output: id, ref_code, display_code, short_description, display_description, linked_cpt_codes, duration, units, body_part, orientation, color_code, is_mammo_cpt, mammo_type, additional_info, is_non_transcribable, is_batch, notes, facilities, modalities, require_wai
ting_time, waiting_time, is_active, has_deleted, deleted_dt, company_id, icd_codes, is_default, code_type, created_dt, linked_cpt_ids, exam_prep_instructions, rvu, sde_study, can_ahs_icd_required, can_ahs_valid_gender, can_ahs_valid_age_from, can_ahs_valid_age_to, can_ahs_t
ooth_code_required, can_ahs_tooth_surface_required, can_ahs_effective_date, can_ahs_end_date, ndc_info
          Filter: ((NOT cpt_codes.has_deleted) OR (cpt_codes.deleted_dt IS NULL))
          Buffers: shared hit=1394
        Settings: effective_cache_size = '3GB', effective_io_concurrency = '200', max_parallel_workers = '4', random_page_cost = '1.1', search_path = 'public, extensions', work_mem = '8MB'
```

and this is what Docker Desktop log pane shows

````
2021-06-11 18:35:40 EDT [7871]: [7-1] user=postgres,db=pacs_live,app=pgAdmin 4 - CONN:3049286,client=192.168.168.6 LOG: duration: 179.172 ms plan:

Query Text: select * from cpt_codes where not has_deleted or deleted_dt is null


Seq Scan on public.cpt_codes (cost=0.00..1533.72 rows=13972 width=1112) (actual time=0.011..22.485 rows=13972 loops=1)

Output: id, ref_code, display_code, short_description, display_description, linked_cpt_codes, duration, units, body_part, orientation, color_code, is_mammo_cpt, mammo_type, additional_info, is_non_transcribable, is_batch, notes, facilities, modalities, require_waiting_time, waiting_time, is_active, has_deleted, deleted_dt, company_id, icd_codes, is_default, code_type, created_dt, linked_cpt_ids, exam_prep_instructions, rvu, sde_study, can_ahs_icd_required, can_ahs_valid_gender, can_ahs_valid_age_from, can_ahs_valid_age_to, can_ahs_tooth_code_required, can_ahs_tooth_surface_required, can_ahs_effective_date, can_ahs_end_date, ndc_info

Filter: ((NOT cpt_codes.has_deleted) OR (cpt_codes.deleted_dt IS NULL))

Buffers: shared hit=1394

Settings: effective_cache_size = '3GB', effective_io_concurrency = '200', max_parallel_workers = '4', random_page_cost = '1.1', search_path = 'public, extensions', work_mem = '8MB'
````

**Comment by mat007** [comment] 2021-06-30 13:57
Sorry it took a while but we now have an internal build that should fix it, if you wanted to give it a try:
https://desktop-stage.docker.com/win/stable/amd64/66242/Docker%20Desktop%20Installer.exe

**Comment by twkrol** [comment] 2021-06-30 15:32
Thanks @mat007
Testing

**Comment by twkrol** [comment] 2021-07-07 13:43
The internal build works better, but after some time (hard to say how log, just in the 2-nd day of development) the logs on DockerDesktop are not updated anymore.
I have to down the containers, start them up, and it works again.

**Comment by mat007** [comment] 2021-07-07 14:31
@twkrol thanks for testing!
Just closing and re-opening the dashboard isn’t enough?

**Comment by twkrol** [comment] 2021-07-07 15:27
Unfortunately not.
Switching output logs from container to container doesn't help either.

I'm still using this version daily, will let you know if I find anything worth mention.

**Comment by mat007** [comment] 2021-07-07 15:45
Right, so this looks like a separate issue then, not dashboard related. 🤔

**Comment by thaJeztah** [comment] 2021-07-07 16:05
@twkrol if you're in that situation, does viewing the logs through the command line (`docker logs <container>` / `docker container logs <container>`) still work, or does that also fail? (trying to deduct where the issue is in that situation)

**Comment by twkrol** [comment] 2021-07-07 17:16
Yeah, I'm using `docker-compose logs -f` to have a continous log view, but DockerDesktop was a bit more convenient for single docker logs.
btw: I'm wrong or some old version of DockerDesktop presented all docker stack logs together? (like docker-compose logs for all containters)

**Comment by JasonHao123** [comment] 2021-07-20 12:37
version 3.3.3(64133) Mac version, same issue here.

**Comment by ulyssessouza** [comment] 2021-08-11 16:57
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.

**Closed by ulyssessouza** 2021-08-11 16:57 UTC
Labels: version/3.3.2, version/3.3.3
