### ISSUE TITLE
Latest version (2.2.0.3) not seeing file changes

### ISSUE THREAD

**Issue by andzejsw** [docker/for-win#5799] opened 2020-02-17 14:58 UTC
I am using docker for my Angular project. 
I often need to rebuild project files. Everything was good in all previous releases until i installed latest Docker version on my Windows machine!
Now after project rebuild very often files are being cached and i can't see file changes. Only way to see them is to close running docker task and then run command  `docker-compose.exe up`

**Comment by stephen-turner** [comment] 2020-02-17 15:00
Thank you for the report, but there is not enough information here to enable us to debug the issue. Please have a look at the other recent issues in this repo and see if your problem is the same as any of them. If it is not, please supply reproduction steps and upload diagnostics. Thank you.

**Comment by jeacott1** [comment] 2020-04-23 02:50
@stephen-turner 

I'm using docker 2.2.0.5 in win 10 pro, and am noticing significant delays and inconsistencies in my volume mounts. 

mounts generally ordinary looking.
```
     "Type": "bind",
                "Source": "/host_mnt/c/app/test/gen/target",
                "Destination": "/files/scratch",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
```

if I 'docker run -it ... --entrypoint bash ..'
and then try something like mkdir -p /files/scratch/.metadata
it probably wont work, failing silently, but if I wait a while and try again it might.
I can get to weird situations where I cant see a folder but I cant create it either because it exists.
```
root@3340faa66341:/# ls -la /files/scratch
total 4
drwxrwxrwx 1 root root    0 Apr 23 01:45 .
drwxrwxrwx 1 root root 4096 Apr 23 01:56 ..
drwxrwxrwx 1 root root    0 Apr 23 01:45 test1
root@3340faa66341:/# mkdir -p /files/scratch/.metadata
mkdir: cannot create directory '/files/scratch/.metadata': File exists
```

if the mkdir does succeed and then I subsequently delete the created folder via windows, the created file is properly gone from dockers view too, but subsequent mkdir always fail without error.

```
root@686816b9c164:/# ls -la /files/scratch
total 4
drwxrwxrwx 1 root root    0 Apr 23 02:37 .
drwxrwxrwx 1 root root 4096 Apr 23 02:37 ..
drwxrwxrwx 1 root root    0 Apr 23 01:45 test1

root@686816b9c164:/# mkdir -p /files/scratch/.metadata
root@686816b9c164:/# mkdir -p /files/scratch/.metadata
root@686816b9c164:/# ls -la /files/scratch
total 4
drwxrwxrwx 1 root root    0 Apr 23 02:37 .
drwxrwxrwx 1 root root 4096 Apr 23 02:37 ..
drwxrwxrwx 1 root root    0 Apr 23 01:45 test1

```

if I try creating a different named directory it seems to work ok.
```
root@686816b9c164:/# mkdir -p /files/scratch/.metadatax
root@686816b9c164:/# ls -la /files/scratch
total 4
drwxrwxrwx 1 root root    0 Apr 23 02:47 .
drwxrwxrwx 1 root root 4096 Apr 23 02:37 ..
drwxrwxrwx 1 root root    0 Apr 23 02:47 .metadatax
drwxrwxrwx 1 root root    0 Apr 23 01:45 test1
```

but again, if deleted via windows and then try to recreate via docker shell, it fails.
very easy to reproduce.

this problem is making docker almost unusable for me.

**Comment by mat007** [comment] 2020-04-23 06:40
Thanks for the report @jeacott1, is there a chance you could try the latest Edge release as we’ve made many fixes to the file sharing since 2.2.0.5?
Edge 2.3.0.0: https://download.docker.com/win/edge/Docker%20Desktop%20Installer.exe

Thanks!

**Comment by jeacott1** [comment] 2020-04-23 08:24
@mat007 muuuuch better!!
that appears to resolve my issues, working nicely now.

many thanks!!

**Comment by stephen-turner** [comment] 2020-04-23 08:34
Thanks @jeacott1. I'm going to close this ticket because the original reporter didn't reply, and the new issue is fixed in the latest build.

**Closed by stephen-turner** 2020-04-23 08:34 UTC

**Comment by jeacott1** [comment] 2020-04-23 23:34
@stephen-turner , actually I'm not sure this is 100% fixed. 
its certainly better, but I'm still noticing delays when running mixed build code (some in docker, some outside), where inconsistencies cause failures. it does at least catch up now, but the sync doesn't seem perfect yet.
