### ISSUE TITLE
no matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by flavinhonunes** [docker/for-win#2764] opened 2018-10-18 18:22 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment] 2018-10-19 16:51
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by Krishnaarunangsu** [comment] 2018-10-23 16:50
Sending build context to Docker daemon  5.672MB
Step 1/1 : FROM tomcat:8-jre8
8-jre8: Pulling from library/tomcat
no matching manifest for unknown in the manifest list entries

**Comment by scirciu** [comment] 2018-11-28 14:49
the problem is with your local images and containers if you do a proper cleanup.
if all containers are stopped and you don t care about the imlages stored on your machine then do:
docker rm $(docker ps -aq)
docker rmi $(docker images -aq)
and retry  it will work

**Comment by sandeeptiwari** [comment] 2018-12-16 03:59
I have tried : https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries

And my issue has been resolved

**Closed** 2019-01-17 09:03 UTC

**Comment by srifromchennai** [comment] 2019-04-22 07:57
Below solution worked for me,

type docker info 
Look for the Operation System.
My Operating sysytem said Windows 10 Enterprise Version 1803

Now I pulled windows/nanoserver:1803
Then it worked.

**Comment by joedragons** [comment] 2019-07-30 18:38
In case it helps anyone, in my case it was that the Windows OS version I was on did not support the tag I was trying to download.  Utilizing an older tag allowed me to get this to work.
