### ISSUE TITLE
Docker Desktop for 4.17.1 breaks any --gpu usage for existing installations

### ISSUE THREAD

**Issue by quantumtec** [docker/for-win#13324] opened 2023-03-22 09:37 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

After upgrade to 4.17.1 from 4.17.0, containers with `--gpu`
- do not start correctly anymore (starting up)
- such starting containers become unkillable (#13320)
- they are not displayed in the UI but still block ports (potentially also ressources
- down and up do not work correctly anymore

### Expected behavior

Docker containers should be startable, docker-compose should work

### Information

  - Windows Version: 11
  - Docker Desktop Version: 14.17.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

WSL-Version: 1.1.3.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.49
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22621.1413

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? [   17.619831] EXT4-fs error (device sdd): ext4_put_super:1188: comm Xwayland: Couldn't clean up the journal
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[WARN] DD0029: is the WSL 2 Linux filesystem corrupt? [   17.619831] EXT4-fs error (device sdd): ext4_put_super:1188: comm Xwayland: Couldn't clean up the journal
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wkrasnicki** [comment] 2023-03-22 14:35
This also happens on my Windows 11 machine. Rebooting WSL, Windows or reinstalling the software doesn't help. I'm downgrading to previous version for now.

**Comment by gustavozantut** [comment] 2023-03-22 15:09
Here too, mainly when trying to use gpu

**Comment by henry-hsiao** [comment] 2023-03-22 15:11
My condition: after upgrading to 4.17.1 from 4.17.0, "--gpus" not work anymore. Downgrading to 4.17.0 solves the issue.

**Comment by thekevshow** [comment] 2023-03-22 17:18
> Here too, mainly when trying to use gpu

yeah anything where --gpu all or (index of GPU) it just hangs and nothing happens. I figured it was this update smh. Spent multiple hours trying to fix this already, does anyone have a solution?

**Comment by gustavozantut** [comment] 2023-03-22 18:04
> > Here too, mainly when trying to use gpu
> 
> yeah anything where --gpu all or (index of GPU) it just hangs and nothing happens. I figured it was this update smh. Spent multiple hours trying to fix this already, does anyone have a solution?
> 
> EDIT:
> @henry-hsiao downgrading is the way 

Downgrade to 4.17.0

**Comment by xtrm0** [comment] 2023-03-22 22:20
Same here, exact issue with broken --gpu  downgradign to 4.17.0 fixed the issue

**Comment by Mark-Beaty** [comment] 2023-03-23 23:30
Same issue for me, downgrading does resolve the issue

**Comment by peterbandi** [comment] 2023-03-24 15:58
I cannot downgrade either. Windows defender identifier the installer of [4.17.0](https://docs.docker.com/desktop/release-notes/#4170) as a threat: `Trojan:Script/Wacatac.H!ml`

**Comment by Mark-Beaty** [comment] 2023-03-24 16:04
> I cannot downgrade either. Windows defender identifier the installer of [4.17.0](https://docs.docker.com/desktop/release-notes/#4170) as a threat: `Trojan:Script/Wacatac.H!ml`

I had this as well, I allowed it though windows defender and it worked just fine, though I won’t recommend it as a smart solution

**Comment by nicks** [comment] 2023-03-24 17:56
thanks for the report! we believe there's a regression in 4.17.1 and are currently investigating

**Comment by shawnaxsom** [comment] 2023-03-24 21:32
Thanks again for the report!

We've been able to reproduce and narrow down the problem to an upstream dependency.

We're testing out a fix now that we aim to include in an RC next week, to be released in v4.18.0 in the coming weeks.

**Comment by Bathsheba** [comment] 2023-03-25 01:10
On the one hand, thanks!
on the other hand...weeks? I hope 4.17.1 will not be pushed automatically during that time.

**Comment by gustavozantut** [comment] 2023-03-25 01:14
4.17.1 must be excluded from upgrades options, there can't be any auto update, specially with a broken version. I hope they don't fup again, first the docker teams then the docker xitgrade and now an autoxitgrade? That's 2munch 4 me

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UTshion** [comment] 2023-03-26 13:23
I had this issue too, downgrading Docker desktop worked for me!
Thanks!

**Comment by gvalenzuelarg** [comment] 2023-03-27 16:51
Downgrading to 4.17.0 also didn't solve the problem.  Version 4.16.3 however works for me.

**Comment by malcolmradelet** [comment] 2023-03-28 23:00
> Downgrading to 4.17.0 also didn't solve the problem. Version 4.16.3 however works for me.

This is the version I had to downgrade to as well. Unfortunately lost all my volumes during the process.

**Comment by qingfengfenga** [comment] 2023-03-30 06:32
> > Downgrading to 4.17.0 also didn't solve the problem. Version 4.16.3 however works for me.
> 
> This is the version I had to downgrade to as well. Unfortunately lost all my volumes during the process.

When demoting or uninstalling docker desktop, you only need to use the wsl export command to export docker desktop data as a file to back up all data

**Comment by dodgio** [comment] 2023-04-03 03:55
Downgrading worked here, too. Thanks

**Comment by damienallen** [comment] 2023-04-03 09:59
In our case, downgrading to v4.17.0 (after uninstalling v4.1.7.1) was enough to fix the regression.

**Comment by JL1829** [comment] 2023-04-03 12:53
For my case, downgrade to `4.17.0` good enough

**Comment by anak1st** [comment] 2023-04-05 08:19
Downgrading worked for me too. Thanks.

**Comment by lorenrh** [comment] 2023-04-05 17:43
Closing this issue because a fix has been released in Docker Desktop 4.18.0. See the [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Closed by lorenrh** 2023-04-05 17:43 UTC
Labels: status/1-acknowledged
