### ISSUE TITLE
Running Windows containers in Kubernetes in Docker Desktop (on Windows)

### ISSUE THREAD

**Issue by fschmied** [docker/for-win#11631] opened 2021-07-09 07:27 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior

When enabling Kubernetes in Docker Desktop on Windows, no Windows node/kubelet seems to be set up, so running Windows containers doesn't seem to be supported out of the box. In fact, the Docker Desktop settings don't even show the "Kubernetes" part unless switching to Linux containers. If you do enable Kubernetes in Linux containers mode and try to create a Pod referencing a Windows image, the Pod will still end up in `ImagePullBackOff` status (with `kubectl describe` explaining that no linux image was found for the given repository and tag).

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  16s                default-scheduler  Successfully assigned default/winpod to docker-desktop
  Normal   Pulling    16s                kubelet            Pulling image "mcr.microsoft.com/windows/nanoserver:1903"
  Warning  Failed     15s                kubelet            Failed to pull image "mcr.microsoft.com/windows/nanoserver:1903": rpc error: code = Unknown desc = no matching manifest for linux/amd64 in the manifest list entries
  Warning  Failed     15s                kubelet            Error: ErrImagePull
  Normal   BackOff    14s (x2 over 15s)  kubelet            Back-off pulling image "mcr.microsoft.com/windows/nanoserver:1903"
  Warning  Failed     14s (x2 over 15s)  kubelet            Error: ImagePullBackOff
```

### Expected behavior

It would be great if Docker Desktop could also set up a Windows kubelet when enabling Kubernetes so we could run pods with Windows containers.

### Information
  - Windows Version: 20H2 (19042.1052)
  - Docker Desktop Version: 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
To reproduce, apply this yaml using `kubectl apply`:
```
apiVersion: v1
kind: Pod
metadata:
  name: winpod
spec:
  containers:
  - name: nanoserver
    image: mcr.microsoft.com/windows/nanoserver:1903
```

**Comment by lorenrh** [comment] 2021-07-09 10:43
Indeed, the Docker Desktop integration of Kubernetes is not available in Windows Containers. This is not a bug so I'm closing this issue, For a feature request, feel to to open a new ticket in https://github.com/docker/roadmap/issues.

**Closed by lorenrh** 2021-07-09 10:43 UTC
Labels: version/20H2
