### ISSUE TITLE
Unable to run Docker Desktop for Windows UI in 2.2.0.0 without elevated rights for REG.EXE

### ISSUE THREAD

**Issue by briz240978** [docker/for-win#5726] opened 2020-02-10 15:38 UTC
Starting with Version 2.2.0.0, the Docker for Windows UI attempts to run REG.EXE  to run a QUERY to obtain a MachineGuid in the background when trying to click on a menu item like Settings. This fails in our environment, as access to REG.EXE is prohibited for regular users and won´t be granted either due to security concerns. This results in the Docker for Windows UI being unusable when you have no rights to run REG.EXE.
Is it possible to re-evalute the usage of REG.EXE during runtime and either perform it during installation where elevated rights may be granted or fallback to some other mechanism to obtain this MachineGuid?

**Comment by stephen-turner** [comment] 2020-02-10 15:43
Thanks for the report, I think this is a duplicate of #5536.

**Closed by stephen-turner** 2020-02-10 15:43 UTC
