### ISSUE TITLE
Unable to install Docker desktop on Windows 10 version 1909

### ISSUE THREAD

**Issue by rameshkumarg** [docker/for-win#7016] opened 2020-06-02 14:18 UTC
I am trying to install Docker for windows and getting the following error towards the end of installation:

I am using Windows 10 Enterprise version 1909
OS build 18363.836
System type: 64-bit operating system, x64 based processor
[install-log.txt](https://github.com/docker/for-win/files/4717690/install-log.txt)

Docker Desktop 2.3.0.3
Installation failed

Failed to start service: The service did not respond to the start or control request in a timely fashion
   at CommunityInstaller.Service.Service.<StartAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.Service.Manager.<AddServiceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ServiceAction.<DoAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()

**Comment by mat007** [comment] 2020-06-03 06:43
Most likely a duplicate of #6091

**Closed by mat007** 2020-06-03 06:43 UTC
