### ISSUE TITLE
Container get out of time sync

### ISSUE THREAD

**Issue by mrmunch** [docker/for-win#245] opened 2016-11-21 14:40 UTC
### Expected behavior
`docker run busybox date` always shows the correct datetime (or at least always the same difference to actual host timezone)

### Actual behavior
`docker run busybox date` only shows the correct datetime after resetting Docker to factory default, but then gets completely out of time sync: After a few days, the command above is some hours behind. After a few weeks it is a few days behind.
I don't think it has something to do with setting timezones in Docker because (a) I already tried to set the timezone in the container & also during image creation and (b) it's not exact X hours and zero minutes behind - it's X hours and Y minutes behind.
Also deleting the busybox image and download it again didn't change anything.
It's not only about busybox (this is just a minimal example) it happens to all container.

### Information

  - Diagnostic ID: 5310F7E3-CF56-4A86-970F-959298383937/2016-11-21_15-33-16
  - Windows 10 Enterprise, Version 1511 (Build 10586.679)

### Steps to reproduce the behavior
  
  - Sadly, I have no idea how to reproduce, but it happened to me 3 times in a row

**Comment by rneugeba** [comment] 2016-11-21 15:35
@mrmunch thanks for your report. Does your computer go into sleep mode or is it always on?

**Comment by mrmunch** [comment] 2016-11-21 15:49
@rneugeba it's a notebook and it also goes into sleep mode or I shut it down nearly every day.

**Comment by rneugeba** [comment] 2016-11-21 16:19
Thanks for the quick reply. This looks like a duplicate of https://github.com/docker/for-win/issues/72 so I'm closing this. I suggest you watch that issue for updates

**Closed by rneugeba** 2016-11-21 16:19 UTC
Labels: area/hyper-v, area/linux, status/0-triage
