### ISSUE TITLE
Please don't opt users into "experimental" features without asking (compose V2) 

### ISSUE THREAD

**Issue by vpmv** [docker/for-win#11742] opened 2021-07-23 14:50 UTC
This is essentially a copy of https://github.com/docker/for-mac/issues/5800, but for Windows.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Expected behavior

Docker-compose should be fully backwards compatible and not confuse the user with all kinds of errors, that weren't there before the DfW client decided to turn on experimental features, without consent of the user.

### Actual behavior

Some users are getting the "Use Docker Compose v2" experimental setting enabled for them when (auto) upgrading to a new Docker for Windows client.

### Information

Coming fresh from a Linux-only environment, I was happy I finally got the whole thing setup! I don't expect apps turning on experimental features without prior warning/consent. 
I spent valuable time to find the source of issues that weren't there yesterday (e.g. containers not found, volumes not mounting). 

I don't agree with your 4 step plan, described in the original issue. This is a very "Microsoft" way of doing things. Don't waste a developer's/company's time with unannounced changes, without proper guidance.

**Comment by stephen-turner** [comment] 2021-07-28 08:14
This is a dupe of docker/for-mac#5800, and there's no point in discussing all the same arguments here. But in summary: it's been in testing for over six months. At that point we had the choice of either turning it on immediately for everybody, or rolling it out gradually, and we chose the later. Let's continue further discussion on the other ticket.

**Comment by stephen-turner** [comment] 2021-07-28 08:15
You can still turn it off in the settings, and report issues at docker/compose-cli.

**Closed by stephen-turner** 2021-07-28 08:14 UTC
