### ISSUE TITLE
Unable to start docker.

### ISSUE THREAD

**Issue by kolodach** [docker/for-win#3891] opened 2019-05-10 10:17 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 18BB71A8-4C1A-41F6-B837-C02C81CF62FD/20190510130815

### Expected behavior
Docker for Windows starts normally.

### Actual behavior
An error occurred during Docker launch.

### Information

  - Windows Version: Windows 10 Pro 1809
  - Docker for Windows Version: 18.09.2, build 6247962

### Steps to reproduce the behavior

  After Windows just started, Docker fails to start with following message:
  `Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'OBEZHENAR' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   в Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) в C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:строка 36
   в Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) в C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:строка 92
   в Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() в C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:строка 74
   в Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() в C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:строка 59`

**Comment by mikeparker** [comment] 2019-05-30 18:40
Duplicate of https://github.com/docker/for-win/issues/1221

* Your Hyper-V configuration is likely broken. This may be caused by a windows update.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 18:40 UTC
