### ISSUE TITLE
Docker Engine to accept all incoming connections

### ISSUE THREAD

**Issue by libsamek** [docker/for-win#564] opened 2017-03-09 14:35 UTC
### Expected behavior

Docker Engine to accept all incoming connections from all interfaces on port 2375/tcp.

### Actual behavior

When applying new configuration I get this error msg:

```
Docker daemon failed with message:
unable to configure the Docker daemon with file C:\ProgramData\docker\config\daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [npipe:////./pipe/docker_engine_windows], from file: [tcp://0.0.0.0:2375 npipe://])



   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

It would be nice to know how to configure Docker Engine to listen to all incoming connections on all interfaces.

```
C:\Program Files\Docker\Docker\resources> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.03.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 11.88 GiB
Name: windows
ID: xxx
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-03-09T15:36:24.0323428+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Steps to reproduce the behavior

In tab Daemon, choose Advanced, JSON config:

```
{
  "hosts": [
    "tcp://0.0.0.0:2375",
    "npipe://"
  ]
}
```

**Comment by davidshen84** [comment] 2017-03-10 03:58
From https://docs.microsoft.com/en-us/virtualization/windowscontainers/management/manage_remotehost, it is clear that docker for Windows is capable of listening on the host IP. However, it is supported on Windows Server edition only.

Can we expect to have this feature on Windows desktop version as well?

**Comment by libsamek** [comment] 2017-03-10 08:04
@davidshen84: currently it listens only localhost, which is fine, but for cases when you want to expose API to other services it becomes useless. One example is Portainer, I could not get it to work.

**Comment by friism** [comment] 2017-03-10 19:51
Portainer works fine on Docker for Windows:

     docker run -v "/var/run/docker.sock:/var/run/docker.sock" -d -p 9000:9000 portainer/portainer

**Comment by friism** [comment] 2017-03-10 20:21
I've sent a PR to make that clearer: https://github.com/portainer/portainer/pull/645

**Comment by libsamek** [comment] 2017-03-10 20:35
@friism: To be exact, I'm using Windows Containers, not Linux containers in Hyper-V virtual machine. For the Linux containers there is no problem since you can use socket, however this is not supported in Windows containers ...

**Comment by friism** [comment] 2017-03-10 21:00
@libsamek Understood, thx. If you don't need the rest of Docker for Windows, it's an option to install Docker directly on Windows: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

**Comment by friism** [comment] 2017-03-10 21:02
I'm closing this as a duplicate of https://github.com/docker/for-win/issues/225 - you can keep track of progress there.

**Closed by friism** 2017-03-10 21:02 UTC
