### ISSUE TITLE
Windows 10 crashes on docker-machine start default command

### ISSUE THREAD

**Issue by reyou** [docker/for-win#1452] opened 2017-12-20 21:34 UTC
### Expected behavior
Should start default machine, or handle error gradually. At least do not crash the OS.
### Actual behavior
Windows 10 crashes.

![image](https://user-images.githubusercontent.com/6571483/34229780-835f0d84-e5a3-11e7-8efd-1a4f8ddb260b.png)

### Information

![image](https://user-images.githubusercontent.com/6571483/34229537-ad369d80-e5a2-11e7-8ca6-29030cad542f.png)

![image](https://user-images.githubusercontent.com/6571483/34229578-d6b55822-e5a2-11e7-9bb2-6e650820d844.png)

![image](https://user-images.githubusercontent.com/6571483/34229660-1df28412-e5a3-11e7-8184-1d8899ca324d.png)

### Steps to reproduce the behavior

  1. Open powershell
  2. List machines with `docker-machine ls`
  3. **Beware! this can crash your machine as well.** Execute `docker-machine start default`

**Comment by code2node** [comment] 2017-12-27 17:01
me too getting Same problem

**Comment by AVenezuela** [comment] 2018-01-15 12:48
Same problem as well

**Comment by lemoinem** [comment] 2018-02-16 17:54
I had this problem.
The issue is that HyperV has been enabled for a reason or another.
HyperV and VirtualBox are incompatible and your default docker machine must be configured with VirtualBox.

You basically have two choices:

- Replace your default machine by an Hyper-V based VM: https://docs.docker.com/machine/drivers/hyper-v/
 - Disable HyperV: https://forums.docker.com/t/running-docker-and-virtualbox-on-the-same-machine/23578/8

**Comment by reyou** [comment] 2018-02-16 18:06
@lemoinem hmm, my HyperV was disable at the time I was getting crash. I will take a look in first option.

**Comment by rn** [comment] 2018-04-30 14:33
This issue tracker is for the Docker for Windows application, not `docker-machine`. As mentioned above, Docker for Windows uses Hyper-V which is incompatible with VirtualBox (both try to use the same virtualisation features in the CPU). Docker for Windows does try to enable Hyper-V if it is not enabled. In the past we certainly have seen issues when switching between the two, e.g. VirtualBox doesn't get un-installed cleanly and then Hyper-V fails to start (although it claims it is enabled).

Neither the Docker for Windows application nor `docker-machine` should cause a BSOD, though is is possible that the VirtualBox kernel module may cause it.

In any case, as said, this does not look a issue specific to Docker for Windows, so I'm closing this issue. Please feel free to continue the discussion, there, though

**Closed by rn** 2018-04-30 14:33 UTC

**Comment by ggajos** [comment] 2018-12-21 12:18
If you still need to use VirtualBox and cannot use Hyper-V. [You might find this article about alternative way of configuring Docker on Windows interesting](https://medium.com/devopslinks/hey-docker-why-you-hate-windows-so-much-de7a7aa4dd7).
