### ISSUE TITLE
Where are descriptions for error codes that have nothing in logs?

### ISSUE THREAD

**Issue by DanJ210** [docker/for-win#680] opened 2017-04-26 19:59 UTC
I keep launching an asp.net core container and running the application via Linux and Windows containers, no problem. When I try to do the same thing to another project of almost identical files... Running the container gives a hash string as being successful but is not running. Status says it has exited with error (145). I've searched everywhere and cannot find anything about docker error codes. I've searched through the logs and the entries don't show anything about what's going on with error code 145 and they are very hard to understand.

Docker is the latest version, all downloaded and installed form docker.com yesterday. What can I do to find out what these errors are and why something identical to another project that works, won't work?

Thanks.

**Comment by DanJ210** [comment] 2017-04-26 20:19
I should also state that I get error code 134 as well. The logs show successful everything when trying to start a container that doesn't start. Shows absolutely nothing about any error or the code 134 or anything to why that container is not running.

**Comment by friism** [comment] 2017-04-26 20:27
Please post a Dockerfile and/or docker-compose file and relevant source code and steps to reproduce the problem.

Also Docker version (`docker version`) that you're using.

**Comment by DanJ210** [comment] 2017-04-27 14:42
@friism Ok. I mean. Could I just know where the descriptions to error codes are? There seems to be no documentation on them.
Version: Version: 17.03.1-ce-win5 (10743)

To post source codes and all that... The only thing I can see about doing is posting an entire project but the project has sensitive data so that's not really possible. I'm not sure any way around this. The docker files match almost exactly those from Microsoft themselves on docker hub, except for file names... https://hub.docker.com/r/microsoft/aspnetcore/ 

Sometimes I'll see the containers run for a few seconds but then they go away with an error code. The log shows all successes with no reference to a code or error at all. I'll post the text document of the last run of the container getting an error. I named the container a vulgar name so disregard that. You can see no mention of an error. 

[dockerlog.txt](https://github.com/docker/for-win/files/961935/dockerlog.txt)

Can I just know what the error code means. Is this not possible?

**Comment by friism** [comment] 2017-04-27 14:56
Docker does not emit nonsense numerical error codes, Microsoft products like `dotnet` do that. I googled a little bit, and I suspect that you're maybe encountering this problem: http://stackoverflow.com/questions/42346498/dotnet-aspnetcore-docker-build-fails-with-a-145-error-code

Let us know if that's not the case.

**Comment by DanJ210** [comment] 2017-04-27 15:30
I don't know enough to say that's not the case. I'm not getting errors with dotnet and building. Here's a screenshot of the error code I'm talking about. It shows when listing all containers and viewing their exit status via `docker ps -a` I've also done what's shown in that link, published the app and am using it's .dll so I shouldn't need dotnet SDK and no dotnet commands are being run so that shouldn't be the error.

Does the container status show error codes from other places? Like the reason why something stopped even if it wasn't a docker reason? I'm getting 145 but now 134 in the status. Where do these codes come from?

![Container Status](https://cloud.githubusercontent.com/assets/16159685/25490877/3ad30560-2b3c-11e7-9985-d3acb4e0911d.PNG)

**Comment by friism** [comment] 2017-04-28 04:46
145 is the exit code of the `dotnet` process that you run inside of the Docker container: https://github.com/friism/aspnetcore-multi-stage-build

(You'll need Docker 17.04 or later to use that because it uses multi-stage builds)

Again, if you could provide a minimal repro (for example with the default ASP.NET Core sample app) and the Dockerfile you want to use, maybe we can help identify the problem.

**Comment by DanJ210** [comment] 2017-04-28 15:34
Ok so I should be looking up error codes for dotnet. I assume what's happening then is dotnet is throwing the error inside of the container and the container is relaying that info back to me. So docker isn't getting an error it's dotnet that's preventing the container from running and giving it the error.

I'm using the repo here as a guideline [dotnet-docker-samples](https://github.com/dotnet/dotnet-docker-samples). The specific one is `aspnetapp` without any other name. That example is exactly what my app is. I can run the example with a dicker container no problem on either Linux or the Windows Nano Server but when I try to do the same thing with my app, I am not getting much luck with error (134). 

Below is a screenshot of my app showing my entire file structure and the docoker/docker.build files I'm using. I did publish the app so either should work. I've moved them around to see if it changes anything.

I'm using this tutorial for the docker.build file [docker build](https://store.docker.com/community/images/microsoft/aspnetcore-build). And I'm using this one for everything else [docker dotnet](https://hub.docker.com/r/microsoft/dotnet/)

![myapp](https://cloud.githubusercontent.com/assets/16159685/25535657/e10e29c2-2c05-11e7-8836-2314975b7f6e.PNG)

**Comment by DanJ210** [comment] 2017-04-28 15:35
I appreciate all the help so far and I'm happy with the result I have in now knowing where the error codes are coming from. So you all don't have to waste time on silly stuff like this as I'm sure it's not easy trying to find a solution in a screenshot.

Thanks for the help though.

**Comment by friism** [comment] 2017-04-28 17:17
Here's what I would try (you can find the image id with `docker images`):

    docker run -ti --entrypoint bash <image-id>

That gets you a shell in the image. From there you can try `dotnet your-dll.dll` and see what happens.

Ultimately, I recommend that you try to understand what the Dockerfile does and figure out how to debug steps that go wrong. Let us know if you don't get unstuck.

**Comment by DanJ210** [comment] 2017-04-28 17:59
Ok I will try that out and continue my learning with those goals in mind. I appreciate your help and you're welcome to go ahead and close this issue. In time I may post back but only after I make sure I get some good progress on learning.

Thanks again.

**Comment by DanJ210** [comment] 2017-04-28 18:12
Last thing is running the .dll like you said is allowing me to see all the errors. So thanks again. Very helpful.

**Comment by friism** [comment] 2017-05-03 00:27
Closing for now, please re-open if you get stuck again.

**Closed by friism** 2017-05-03 00:27 UTC
Labels: status/0-more-info-needed
