### ISSUE TITLE
Docker Desktop is starting forever

### ISSUE THREAD

**Issue by pathikreet** [docker/for-win#7118] opened 2020-06-08 12:23 UTC
- [ No] I have tried with the latest version of my channel (Stable or Edge)
  - [ Yes] I have uploaded Diagnostics
  - Diagnostics ID: 1F6AC538-7576-4F96-AEA3-8A9E79E4681A/20200608120959

### Expected behavior
Docker should start running
### Actual behavior
Docker is starting
### Information

  - Windows Version: 10 Enterprise
  - Docker Desktop Version: 2.1.0.5 (40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. I had installed updates for Cisco AnyConnect Client and thereafter on restarting my system, Docker is not starting anymore.
  2. It is always in "Docker is starting mode".

**Comment by stephen-turner** [comment] 2020-06-08 13:02
Thanks for the report. I think this is a dupe of #2050. Several people have reported that Cisco AnyConnect blocks Docker Desktop. It doesn't seem to be possible for us to fix it on our end.

**Closed by stephen-turner** 2020-06-08 13:02 UTC
Labels: version/2.1.0.5
