### ISSUE TITLE
Docker4Windows: File Sharing Needs Password, My Computer Doesn't Have One

### ISSUE THREAD

**Issue by EnzoTheBrown** [docker/for-win#366] opened 2017-01-01 19:43 UTC
### Expected behavior
make C:// a shared drive
### Actual behavior
Asking a password I don't have can't go further
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment] 2017-01-02 14:05
Hi @EnzoTheBrown By design, we rely on authenticated samba shares, so you need to protect your user account with a password to enable drive sharing

**Comment by rneugeba** [comment] 2017-01-05 11:51
closing as this won't fix

**Closed by rneugeba** 2017-01-05 11:51 UTC
Labels: status/0-wont-fix

**Comment by d4nc00per** [comment] 2017-02-12 21:55
Is it possible to add something to the UI that explains why a password is enforced?

**Comment by Almusamim** [comment] 2018-04-19 16:52
I hate passwords! :(

**Comment by Cperbony** [comment] 2018-06-09 21:58
One solution found was create a User Windows Password.

**Comment by Cperbony** [comment] 2018-06-09 21:59
One solution found was create a User Windows Password.

**Comment by Almusamim** [comment] 2018-06-14 11:05
@Cperbony that is not a solution!

**Comment by Deilan** [comment] 2018-07-18 13:06
@rn What's the problem with letting to enter a blank password? If it's not valid it would be rejected anyway.

![image](https://user-images.githubusercontent.com/4777512/42883463-536c2250-8aa4-11e8-99a2-6c9bbd0e2e28.png)

**Comment by WiseUA** [comment] 2018-07-18 21:45
Maybe you are using a windows account, in which case you must enter a password here from the microsoft account.
For me it works.

**Comment by adrianotsi** [comment] 2018-07-29 02:22
Yes,  thanks @WiseUA works for me🥇

**Comment by mansoncui** [comment] 2018-10-08 02:45
I still can't use the Microsoft Windows password

**Comment by mansoncui** [comment] 2018-10-08 02:46
I still can't use my Microsoft password

**Comment by mozzgov** [comment] 2018-11-02 17:22
You can create a new user (DockerUser) with a password and make it shared. FAQ - [http://peterjohnlightfoot.com/docker-for-windows-on-hyper-v-fix-the-host-volume-sharing-issue/](url)

**Comment by sicdigital** [comment] 2018-12-21 03:40
I used my the default username and my Microsoft password.

**Comment by ahmetanbar** [comment] 2019-01-14 19:10
> @Deilan Maybe you are using a windows account, in which case you must enter a password here from the microsoft account.
> For me it works.
Thanks it works for me.

**Comment by minhlong** [comment] 2019-05-29 10:23
Thanks @WiseUA It works

**Comment by okumo** [comment] 2020-01-20 04:30
Thanks @WiseUA

**Comment by petermorlion** [comment] 2020-01-27 07:18
Yes, I can confirm: if you have a Microsoft account, remove the <computer>\<user> username entirely, and enter your Microsoft account's email address (x.y@outlook.com for example). Then enter that account's password. Works.

**Comment by IronSean** [comment] 2020-02-14 15:59
Note for those still having trouble, a Microsoft account is not the same as an Azure ActiveDirectory account which is what your School or Work might have for you. So if your proper Microsoft/AzureAD password isn't working, making another local user on the machine might be easiest.
