### ISSUE TITLE
Do not force users into updating when starting docker desktop

### ISSUE THREAD

**Issue by Pomax** [docker/for-win#10606] opened 2021-03-10 15:01 UTC
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: none of this is relevant in this case

### Actual behavior

Docker Desktop pops up UAC in order to update itself before it does anything else when starting up.

### Expected behavior

Docker Desktop should start as it normally does _first_, and then generate a windows notification that there's an update available that the user can click to initial the update, and an icon context menu "update now" option as well as an update option in the desktop UI.

**Comment by stephen-turner** [comment] 2021-03-10 15:26
Closing as dupe of docker/roadmap#183

**Closed by stephen-turner** 2021-03-10 15:26 UTC

**Comment by Pomax** [comment] 2021-03-11 16:03
Not quite sure why: that might be the "docker itself" side of things, but all the necessary UI aspects of the update process are pretty docker-win specific, since they concern the GUI?
