### ISSUE TITLE
`docker info` takes really long tim

### ISSUE THREAD

**Issue by ido-ran** [docker/for-win#10675] opened 2021-03-16 17:06 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `2EF2531D-301F-45E6-A863-73581BD98CDF/20210316142533`

### Actual behavior

`dockre info` takes 34 seconds to run.

```
[27 ms] Start: Check Docker is running
[27 ms] Start: Run: docker info
[348523 ms] Start: Run: docker-compose version --short
```

### Expected behavior

get result from `docker info` after few ms.

### Information

  - Windows Version: 10.0.19041.867
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior

  1. run `docker info` from `cmd` or PowerShell.
 
If I run `docker info` from wsl it finish in less then a second.
VS Code runs this command every time Dev Container is opened.

**Comment by stephen-turner** [comment] 2021-03-16 18:49
If it runs quickly from WSL 2, that suggests that Docker itself is fast. Do you have any corporate security software that could be inserting itself on the network path?

**Comment by ido-ran** [comment] 2021-03-16 19:26
Yes, I have a corporate VPN application but I have been using it for over 7 month and only now this issue started to happen.
I will try to shutdown the VPN and see if it cause any improvement.

**Comment by ido-ran** [comment] 2021-03-18 10:42
I can confirm this is issue cause by the corporate VPN.
Is there any way to get a bit more information about what is happening inside `docker info` command to try and understand what is taking 5 minutes instead of 1 second or less?

**Comment by stephen-turner** [comment] 2021-03-18 12:11
Most likely the VPN is blocking the path between your host terminal and the Linux VM where docker runs.

**Comment by EricHripko** [comment] 2021-03-18 12:24
I'm seeing the same issue as @ido-ran. Trying to gather more logs now, but I can't imagine that VPN is blocking communications with the Linux VM since other commands on Windows are instant (e.g., `docker images`). It appears that it's just `docker info` that's somehow now trying to reach the Internet.

**Comment by EricHripko** [comment] 2021-03-18 14:00
This seems to happen after restart of Docker Desktop:
```
> Measure-Command { docker info }
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support


Days              : 0
Hours             : 0
Minutes           : 5
Seconds           : 19
Milliseconds      : 645
Ticks             : 3196456747
TotalDays         : 0.00369960271643519
TotalHours        : 0.0887904651944444
TotalMinutes      : 5.32742791166667
TotalSeconds      : 319.6456747
TotalMilliseconds : 319645.6747
```

**Comment by EricHripko** [comment] 2021-03-18 14:41
Interestingly, occasionally after running other docker command in the same shell (e.g., `docker images`) the invocations of `docker info` become instant for a brief time period:
```
> docker images
REPOSITORY                                        TAG       IMAGE ID       CREATED        SIZE
...
>  Measure-Command { docker info }
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 225
Ticks             : 42250135
TotalDays         : 4.8900619212963E-05
TotalMinutes      : 0.0704168916666667
TotalSeconds      : 4.2250135
TotalMilliseconds : 4225.0135



PS C:\Users\HripkoEric>  Measure-Command { docker info }
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 474
Ticks             : 4743327
TotalDays         : 5.48996180555556E-06
TotalHours        : 0.000131759083333333
TotalMinutes      : 0.007905545
TotalSeconds      : 0.4743327
TotalMilliseconds : 474.3327



PS C:\Users\HripkoEric>  Measure-Command { docker info }
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support


Days              : 0
Hours             : 0
Minutes           : 5
Seconds           : 45
Milliseconds      : 599
Ticks             : 3455991093
TotalDays         : 0.00399998969097222
TotalHours        : 0.0959997525833333
TotalMinutes      : 5.759985155
TotalSeconds      : 345.5991093
TotalMilliseconds : 345599.1093
```

**Comment by stephen-turner** [comment] 2021-03-18 16:55
That's very odd. @ido-ran Is that what you're seeing too: that `docker info` is slow but all other `docker` commands are fast?

**Comment by ido-ran** [comment] 2021-03-18 22:25
Yes, 5 minutes when vpn is connected, 5 seconds or less when disconnected when running `docker info`.
Other docker commands run just fine all the time.

**Comment by StefanScherer** [comment] 2021-03-23 14:24
@ido-ran We cannot reproduce it on our machines. Could you run the following commands, we want to bisect the problem?

```
PS C:\> (Measure-Command {docker info}).TotalSeconds
0.6865705

PS C:\> (Measure-Command {& com.docker.cli --context default context inspect default}).TotalSeconds
0.1713139

PS C:\> (Measure-Command {com.docker.cli info}).TotalSeconds
0.3619914

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-app.exe' docker-cli-plugin-metadata}).TotalSeconds
0.1763265

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-buildx.exe' docker-cli-plugin-metadata}).TotalSeconds
0.1399166

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-scan.exe' docker-cli-plugin-metadata}).TotalSeconds
0.1409913
```

And I have some other questions :-)
- Since which version did you encounter the problem? Was it working in previous versions of Docker Desktop?
- Is your Windows machine joined to Active Directory? We had something like that for some `docker context` commands in the past.

**Comment by ido-ran** [comment] 2021-03-23 20:55
Hi,
Some good and bad news - I have update VS Code (which run `docker info` upon opening DevContainer and that's why I ran into this issue) and it seems that the new VS Code version (see bellow all version info) is not using `docker info` but now uses `docker version` which run in ~400ms.

From what I remember docker 3.2.2 was the first version that had this issue.
No, my computer is not part of an Active Directory domain, it is in a workgroup.


VS Code Version Info
```
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by stephen-turner** [comment] 2021-03-24 07:38
Thank you for the update, @ido-ran. That's interesting that VS Code now uses `docker version`.

We would still be interested in seeing the timings that Stefan suggested if you or @EricHripko could run them from a PowerShell window.

**Comment by EricHripko** [comment] 2021-04-09 12:19
Apologies for the delay - I've attached the timings below. It looks like after the first (very long delay), follow-up Docker commands work fine for a brief period of time:
```
> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
331.228712
> (Measure-Command {& com.docker.cli --context default context inspect default}).TotalSeconds
0.0709302
> (Measure-Command {com.docker.cli info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
0.3021588
> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-app.exe' docker-cli-plugin-metadata}).TotalSeconds
0.3818938
> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-buildx.exe' docker-cli-plugin-metadata}).TotalSeconds
0.5797506
> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-scan.exe' docker-cli-plugin-metadata}).TotalSeconds
0.151424
> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
3.1500902
> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
0.4980028
```

If I wait a little bit and re-run `docker info`, I observe the same issue again though:
```
> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
345.4827514
```

**Comment by ido-ran** [comment] 2021-04-09 12:29
Hi,
I can confirm it is the same here.

```
> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
350.0544969

>  (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
0.5326005

>  (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
0.4954999
```

Is there anything I can do to help identify where the slowness coming from?

**Comment by StefanScherer** [comment] 2021-04-09 12:30
Thanks @EricHripko for the measurements.  
Could you do another test with just running each of the three cli-plugin and measure the time? And please wait a bit between each call. That would help us to understand if one of these plugins cause the delay. Thanks.

**Comment by ido-ran** [comment] 2021-04-28 08:42
Hi, I fail to notice the request for running the plugins again.
Here are the times I've collected with the VPN connected.

```
PS C:\> (Measure-Command {docker info}).TotalSeconds
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
241.5187797

{{ At least 10 minutes passed here }}

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-app.exe' docker-cli-plugin-metadata}).TotalSeconds
308.9317475

{{ At least 10 minutes passed here }}

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-buildx.exe' docker-cli-plugin-metadata}).TotalSeconds
0.6578922

{{ At least 10 minutes passed here }}

PS C:\> (Measure-Command {& 'C:\Program Files\Docker\Docker\resources\cli-plugins\docker-scan.exe' docker-cli-plugin-metadata}).TotalSeconds
0.1878236
```


Another issue that started to happen is that running `docker-compose build` (even for containers that are fully built and only use cached layers) run all the way to the end and then the command seem like stuck for about 8 minutes and only then it finishes.
This is again issue for VS Code as it waits for docker-compose to finish building before open the remote Dev Container.

```
 => exporting to image                                                     0.1s
 => => exporting layers                                                    0.0s
 => => writing image sha256:218faaba89477cd6d5030cf96f7e020900002b8057d26  0.0s
 => => naming to docker.io/library/goblins_dev                             0.0s
{{ Between those lines 8 minutes passed }}
Successfully built 218faaba89477cd6d5030cf96f7e020900002b8057d26d46acefe0e335360222
```

**Comment by ido-ran** [comment] 2021-04-28 08:42
Another issue that started to happen is that running `docker-compose build` (even for containers that are fully built and only use cached layers) run all the way to the end and then the command seem like stuck for about 8 minutes and only then it finishes.
This is again issue for VS Code as it waits for docker-compose to finish building before open the remote Dev Container.

```
 => exporting to image                                                     0.1s
 => => exporting layers                                                    0.0s
 => => writing image sha256:218faaba89477cd6d5030cf96f7e020900002b8057d26  0.0s
 => => naming to docker.io/library/goblins_dev                             0.0s
{{ Between those lines 8 minutes passed }}
Successfully built 218faaba89477cd6d5030cf96f7e020900002b8057d26d46acefe0e335360222
```

**Comment by ido-ran** [comment] 2021-04-29 15:09
I have collected some more details about `docker-compose build` and it does seem related to this issie:

![image](https://user-images.githubusercontent.com/187938/116574060-44d9ff00-a905-11eb-9b90-ad7ab14c5d32.png)


command line: `C:\ProgramData\Docker\cli-plugins\docker-app.exe docker-cli-plugin-metadata`

**Comment by StefanScherer** [comment] 2021-04-29 20:45
Thanks @ido-ran for the investigation. Indeed it seems like only the `docker-app.exe` plugin causes the sporadic delay.
We'll discuss in the team how to move forward.

**Comment by EricHripko** [comment] 2021-05-17 11:20
Hi folks 👋 Were you able to discuss this? I've noticed various Docker versions having these issues sporadically on Windows. For example, it sometimes manifests with Docker Desktop not being able to restart under VPN but working just fine without. Is something in the daemon trying to reach the Internet by default now?

**Comment by ido-ran** [comment] 2021-06-13 21:23
@StefanScherer any update? 😃

**Comment by StefanScherer** [comment] 2021-06-14 05:08
@ido-ran Yes, there's an update. We have removed the `docker-app` CLI plugin in Docker Desktop 3.4.0, so when you update DD you shouldn't encounter this problem any longer.

**Comment by StefanScherer** [comment] 2021-06-14 05:10
I'll close this ticket as the problem is solved now. But it's still possible to comment to give feedback. :-)

**Closed by StefanScherer** 2021-06-14 05:10 UTC
Labels: version/1.54.3, version/3.2.2

**Comment by ido-ran** [comment] 2021-06-14 10:13
Thank you very much, I've confirmed that a simple `docker build` that was stuck yesterday after completing everything for about 3 minutes finish normally today.
