### ISSUE TITLE
Unable to start: The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by Gmanweb** [docker/for-win#219] opened 2016-11-11 11:14 UTC
### Expected behavior
To get docker to start, after upgrade to 1.12.3 from 1.12.1.
### Actual behavior

```
Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
### Information

  - Diagnostic ID `99B58F21-250D-4D9C-8AE9-87CB40C68087/2016-11-11_10-59-27`

  - Docker Version: `Docker version 1.12.3, build 6b644ec`
  
  - Windows version, build number: `Windows 10 Pro, version 1607, OS Build 14393.447`

### Steps to reproduce the behavior

  1. ... Start up windows, docker says starting for a minute or two maybe three.
  2. ... Just error message above.

Tried to uninstall, clean machine and reinstall but still no joy.

**Comment by rneugeba** [comment] 2016-11-11 12:55
@Gmanweb thanks for filing this as a separate issue.

From the logs it seems that your system is *very* slow. It took something like
- 20s to open up firewall ports
- 60+s to create a VM a Lot spent in the initial powershell script startup
- 90+ seconds to boot Linux (this normally takes a few seconds)

Is there a heavy load on your system when you start it?

**Comment by Gmanweb** [comment] 2016-11-11 13:44
No Heavy load, its just a `Dell Precision M4800` for testing, its was running fine with `Docker Version 1.12.1 `for the last month and as soon as I updated (because docker suggested it) the problem is happening.  can you suggest anything?

**Comment by Gmanweb** [comment] 2016-11-11 15:10
@rneugeba right I managed to get it running, I just gave it more **CPUs and RAM**. :) 

**Step to help others:**

Open docker settings --> Advanced --> `CPUs 4` and `Memory 3328 M`B and Apply

**Comment by rneugeba** [comment] 2016-11-11 16:12
Thanks for following up and glad to hear that it's working now.

FWIW I don't think the issue is related to the number of CPUs/amount of memory you configured but more likely some transient load on your system.  To give you an example, the VM creation on your system took 60s. On one of my systems, which is similarly spec'ed it takes less than 10s. This is independent of the CPUs you have assigned to the VM etc. 

I'm closing this issue as it seem to be fixed for you, but feel free to try returning to 2CPUs and 2G of memory and report back if that is still working. When it's not working it might be worth looking at the performance tab in the task manager and see if there is anything obvious standing out.

**Closed by rneugeba** 2016-11-11 16:12 UTC
Labels: area/hyper-v, status/0-triage
