### ISSUE TITLE
Debug SAM applications breaks with Docker 2.2.0.0 on VS Code (Windows 10)

### ISSUE THREAD

**Issue by manucohenyashar** [docker/for-win#5573] opened 2020-01-23 16:14 UTC
After upgrading to version 2.2.0.0 debugging SAM applications stopped working in ALL runtimes (Python, node, etc). Running the application works but attaching the debugger breaks with the error: "docker.errors.APIError: 500 Server Error: Internal Server Error ("error while creating mount source path '/host_mnt/c/Users/{user name}/AppData/Local/Temp/aws-toolkit-vscode/vsctkDZvlgv/output/awsToolkitSamLocalResource': mkdir /host_mnt/c/Users/{user name}: file exists")"

I disabled the local firewall to make sure no network errors cause the issue. Also, the fact that running the application (sam local invoke) works tells me that mounting works.

  - [*] I have tried with the latest version of my channel (Stable or Edge)
  - [ *] I have uploaded Diagnostics
  - Diagnostics ID: A70E650C-EEE0-423B-A795-55F2DD760CFD/20200123155536

### Expected behavior
The debugger should attach (using the default port 5858)
### Actual behavior
Attach debugger fails with the error: 

docker.errors.APIError: 500 Server Error: Internal Server Error ("error while creating mount source path '/host_mnt/c/Users/{my user name}/AppData/Local/Temp/aws-toolkit-vscode/vsctkDZvlgv/output/awsToolkitSamLocalResource': mkdir /host_mnt/c/Users/{my user name}: file exists")
### Information

  - Windows Version: Windows 10.0.18362 
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Create a new SAM application in VS Code or SAM init, The runtime is not important, the problems happen in ALL runtimes.
  2. Click "Debug Locally" (Code lens in VS Code)

**Comment by stephen-turner** [comment] 2020-01-23 16:18
Dupe of #5516.

**Closed by stephen-turner** 2020-01-23 16:18 UTC

**Comment by manucohenyashar** [comment] 2020-01-23 16:32
Issue 5516 does not provide a workaround or a solution when using tools that internally use upper case when mounting, so I think this issue should be reopened.

**Comment by stephen-turner** [comment] 2020-01-23 17:16
We will have a fix for #5516, we're not expecting people to rely on the workaround.

**Comment by manucohenyashar** [comment] 2020-02-03 13:29
Just got the build (ver 2.2.0.1) which fixed the issue.
