### ISSUE TITLE
Object reference not set to an instance of an object when starting docker for windows

### ISSUE THREAD

**Issue by devedse** [docker/for-win#464] opened 2017-02-04 15:21 UTC
**Description**

I installed Docker onto my computer but got a blue screen after the installation. (Due to an unrelated problem where I can't create HyperV VHD's on my C Drive due to a Bios NVME driver).

I created a symlink for the c:\users\....\.docker\machine\machines folder to another drive which would solve the issue of the blue screen.

However when I now start Docker for Windows.exe I only see the following error:

![image](https://cloud.githubusercontent.com/assets/2350015/22564612/72d4d1da-e985-11e6-9231-eab1aa16868a.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

I already tried reinstalling docker and Hyper-V without any luck. I also tried manually creating a new VM with the following command:
docker-machine create --driver hyperv vm

However this didn't solve the issue.

Also running any commands with docker run give errors. E.g.:
```
C:\Users\Davy>docker pull hello-world
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/create?fromImage=hello-world&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My enviroment is Windows 10 with Docker for Windows which I want to run in the linux VM.

**Comment by rneugeba** [comment] 2017-02-05 11:30
@devedse With Docker for Windows you don't need to play with `docker-machine`. Just start the application and it will create thew Linux VM for you. There should be an icon in the systray

**Comment by devedse** [comment] 2017-02-05 12:22
Hey meugeba, thanks for your advice, but as I described in my post, the issue is that I can't start the docker application. So no matter how bad I would like to do that, that is actually the main issue :).

**Comment by rneugeba** [comment] 2017-02-05 12:43
can you send the crash report and report the Diagnostics ID?

**Comment by devedse** [comment] 2017-02-05 13:08
I uploaded the log as:
![image](https://cloud.githubusercontent.com/assets/2350015/22626389/7c601d62-ebac-11e6-88f9-ad73dc159c49.png)

**Comment by simonferquel** [comment] 2017-02-06 14:39
@devedse can you try to remove everything in C:\Users\<username>\AppData\Roaming\Docker ?

**Comment by devedse** [comment] 2017-02-09 14:06
Will check that out

**Comment by rneugeba** [comment] 2017-02-14 13:38
A few more pointers:
- Could you send us a crash report/diagnostics and report the diagnostics ID here?
- Could you check with `Get-Service com.docker.service` if the service is running?

**Comment by devedse** [comment] 2017-02-15 23:06
rneugeba, I tried to do that but as you can see in the screenshot above the diagnostic id is unreadable.

I will have access to this machine next week again, so then I will continue my investigation.

**Comment by rneugeba** [comment] 2017-02-16 11:16
@devedse thanks for getting back

**Comment by audioboxer217** [comment] 2017-02-22 22:37
I'm seeing the same issue.  I confirmed that the 'com.docker.service' does show RUNNING. I sent a crash report (Diag ID: 83E0204E-E01B-4DEA-ABAB-726BE7C306C9/2017-02-22_16-29-13).  Screenshot of the message and the log.txt below

I was also getting Blue Screen at boot for a while until I disabled Docker for Win as a Startup item.  Not sure if that's related or not because if I manually start it a little later I don't get the Blue Screens anymore, just the error message from Docker for Win

![image](https://cloud.githubusercontent.com/assets/6342499/23235860/a8460662-f91c-11e6-9865-51146550f2c7.png)

**Comment by audioboxer217** [comment] 2017-02-28 22:01
Somehow I missed @simonferquel 's suggestion to remove everything from the AppData/Roaming folder.  That resolved the issue for me.

**Comment by devedse** [comment] 2017-03-03 09:42
Indeed remove AppData/Roaming/Docker also solved this issue for me. I think the settings.json file in there was corrupted.

Maybe we need to change the code a little bit so that Docker is able to recover from corrupted settings files?

**Comment by rneugeba** [comment] 2017-03-03 16:52
@devedse thanks for reporting back. There has been other reports of the settings file being corrupted here #455 and we have an internal issue tracking it. so I'm closing this issue.

**Closed by rneugeba** 2017-03-03 16:52 UTC
Labels: status/0-more-info-needed

**Comment by jayfresh** [comment] 2017-06-08 12:01
Deleting AppData/Roaming/Docker worked for me too. 👍

**Comment by nithishpk** [comment] 2019-03-23 17:04
Deleting AppData/Roaming/Docker worked for me
