### ISSUE TITLE
2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914

### ISSUE THREAD

**Issue by hsolomon35** [docker/for-win#3967] opened 2019-05-24 03:11 UTC
My email address is hsolomon35@gmail.com

After loading Docker it does not start IO get the following log file:

Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/05/23 21:59:11.547
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\hsolo\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[21:59:11.649][GUI            ][Info   ] Starting...
[21:59:11.717][ComponentVersions][Info   ] Edition community
[21:59:12.399][Tracking       ][Info   ] Crash report and usage statistics are enabled
[21:59:12.402][SegmentApi     ][Info   ] Usage statistic: appLaunched
[21:59:12.455][SegmentApi     ][Info   ] Usage statistic: heartbeat
[21:59:12.458][SegmentApi     ][Info   ] Usage statistic: Identify
[21:59:13.137][NamedPipeClient][Info   ] Sending Version()...
[21:59:13.141][NamedPipeClient][Info   ] Received response for Version
[21:59:13.142][NamedPipeClient][Info   ] Sending MigrateApp()...
[21:59:13.144][NamedPipeClient][Info   ] Received response for MigrateApp
[21:59:13.146][Notifications  ][Info   ] Docker Desktop is starting...
[21:59:13.141][NamedPipeServer][Info   ] Version done in 00:00:00.
[21:59:13.143][NamedPipeServer][Info   ] MigrateApp()
[21:59:13.144][NamedPipeServer][Info   ] MigrateApp done in 00:00:00.0009974.
[21:59:13.158][NamedPipeClient][Info   ] Sending Version()...
[21:59:13.159][NamedPipeClient][Info   ] Received response for Version
[21:59:13.159][NamedPipeClient][Info   ] Sending RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)...
[21:59:13.161][NamedPipeClient][Info   ] Received response for RegisterFileAssociations
[21:59:13.159][NamedPipeServer][Info   ] Version()
[21:59:13.162][NamedPipeClient][Info   ] Sending Version()...
[21:59:13.159][NamedPipeServer][Info   ] Version done in 00:00:00.
[21:59:13.163][NamedPipeClient][Info   ] Received response for Version
[21:59:13.163][NamedPipeClient][Info   ] Sending EnableVersionPack(default, Docker.Core.Settings)...
[21:59:13.160][NamedPipeServer][Info   ] RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)
[21:59:13.166][NamedPipeClient][Info   ] Received response for EnableVersionPack
[21:59:13.160][FileTypeRegistrar][Info   ] Registering file association for extension .ddvp
[21:59:13.161][NamedPipeServer][Info   ] RegisterFileAssociations done in 00:00:00.0010015.
[21:59:13.169][NamedPipeClient][Info   ] Sending Version()...
[21:59:13.163][NamedPipeServer][Info   ] Version()
[21:59:13.170][NamedPipeClient][Info   ] Received response for Version
[21:59:13.170][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[21:59:13.163][NamedPipeServer][Info   ] Version done in 00:00:00.
[21:59:13.164][NamedPipeServer][Info   ] EnableVersionPack(default, Docker.Core.Settings)
[21:59:13.166][NamedPipeServer][Info   ] EnableVersionPack done in 00:00:00.0020029.
[21:59:13.170][NamedPipeServer][Info   ] Version()
[21:59:13.170][NamedPipeServer][Info   ] Version done in 00:00:00.
[21:59:13.172][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[21:59:13.172][PowerMode      ][Info   ] Stop
[21:59:13.172][HyperV         ][Info   ] Stop
[21:59:13.173][PowerShell     ][Info   ] Run script with parameters: -Stop True
[21:59:13.179][HyperV         ][Info   ] Script started at 21:59:13.179
[21:59:13.192][HyperV         ][Info   ] Modules loaded at 21:59:13.192
[21:59:13.200][NPS            ][Info   ] NPS last local survey date: 5/24/2019 1:40:59 AM +00:00
[21:59:13.204][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[21:59:13.204][HyperV         ][Debug  ] [stop] took 00:00:00.0319950 to run
[21:59:13.204][OptimizeDisk   ][Info   ] Optimize
[21:59:13.204][PowerShell     ][Info   ] Run script...
[21:59:13.213][Moby           ][Info   ] Stop
[21:59:13.222][HyperV         ][Info   ] Create
[21:59:13.222][HyperVGuids    ][Info   ] Installing GUIDs...
[21:59:13.222][PowerMode      ][Info   ] Start
[21:59:13.222][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[21:59:13.223][Firewall       ][Info   ] Removing all existing rules...
[21:59:13.225][HyperVGuids    ][Info   ] GUIDs installed
[21:59:13.230][HyperV         ][Info   ] Script started at 21:59:13.230
[21:59:13.241][HyperV         ][Info   ] Modules loaded at 21:59:13.241
[21:59:13.251][Firewall       ][Info   ] All existing rules are removed.
[21:59:13.252][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[21:59:13.256][Firewall       ][Info   ] Opening ports for SMB...
[21:59:13.265][Firewall       ][Info   ] Ports are opened
[21:59:13.281][HyperV         ][Info   ] Creating Switch: DockerNAT...
[21:59:13.887][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411. Let's retry
[21:59:13.896][HyperV         ][Info   ] Hyper-V is running
[21:59:13.896][PowerMode      ][Info   ] Stop
[21:59:13.896][HyperV         ][Info   ] Stop
[21:59:13.896][PowerShell     ][Info   ] Run script with parameters: -Stop True
[21:59:13.903][HyperV         ][Info   ] Script started at 21:59:13.903
[21:59:13.918][HyperV         ][Info   ] Modules loaded at 21:59:13.917
[21:59:13.926][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[21:59:13.927][HyperV         ][Debug  ] [stop] took 00:00:00.0309964 to run
[21:59:13.927][OptimizeDisk   ][Info   ] Optimize
[21:59:13.927][PowerShell     ][Info   ] Run script...
[21:59:13.935][Moby           ][Info   ] Stop
[21:59:13.942][HyperV         ][Info   ] Destroy
[21:59:13.943][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[21:59:13.949][HyperV         ][Info   ] Script started at 21:59:13.949
[21:59:13.960][HyperV         ][Info   ] Modules loaded at 21:59:13.959
[21:59:13.970][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[21:59:13.971][HyperV         ][Info   ] Destroying Switch DockerNAT...
[21:59:13.996][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[21:59:14.004][HyperV         ][Debug  ] [destroy] took 00:00:00.0620011 to run
[21:59:14.004][Firewall       ][Info   ] Closing ports...
[21:59:14.004][Firewall       ][Info   ] Removing all existing rules...
[21:59:14.061][Firewall       ][Info   ] All existing rules are removed.
[21:59:14.061][Firewall       ][Info   ] Ports are closed
[21:59:14.061][HyperVGuids    ][Info   ] Removing GUIDs...
[21:59:14.061][HyperVGuids    ][Info   ] GUIDs removed
[21:59:14.061][HyperV         ][Info   ] Create
[21:59:14.062][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[21:59:14.068][HyperV         ][Info   ] Script started at 21:59:14.068
[21:59:14.081][HyperV         ][Info   ] Modules loaded at 21:59:14.081
[21:59:14.110][HyperV         ][Info   ] Creating Switch: DockerNAT...
[21:59:14.426][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 125
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[21:59:14.465][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[21:59:14.467][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[21:59:14.490][NamedPipeClient][Info   ] Sending Version()...
[21:59:14.491][NamedPipeClient][Info   ] Received response for Version
[21:59:14.491][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\hsolo\AppData\Local\Temp\ gather -id 2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914, C:\Users\hsolo\AppData\Local\Temp\2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914.zip)...
[21:59:14.491][NamedPipeServer][Info   ] Version()
[21:59:14.491][NamedPipeServer][Info   ] Version done in 00:00:00.
[21:59:14.492][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\hsolo\AppData\Local\Temp\ gather -id 2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914, C:\Users\hsolo\AppData\Local\Temp\2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914.zip)
[22:00:45.132][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[22:00:45.131][NamedPipeServer][Info   ] GatherDiagnostics done in 00:01:30.6384904.
[22:00:45.149][GUI            ][Info   ] Sending Bugsnag report 8ecbb506-a48b-44f0-b2b6-c592b6670380...
[22:00:45.770][GUI            ][Info   ] Bugsnag report 8ecbb506-a48b-44f0-b2b6-c592b6670380 sent
[22:00:48.006][CrashReport    ][Info   ] Uploading diagnostics 2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914
[22:00:51.036][CrashReport    ][Info   ] Uploaded succesfully diagnostics 2B21543C-4CE3-4446-8A87-D8F6ADF7B878/20190523215914
[22:01:37.807][ErrorReportWindow][Info   ] Open logs
[22:02:32.833][ErrorReportWindow][Info   ] Open logs
[22:04:38.044][ErrorReportWindow][Info   ] Open logs
[22:05:38.558][SegmentApi     ][Info   ] Usage statistic: actionMenuRestart
[22:05:38.559][App            ][Info   ] User clicked on restart
[22:05:38.560][SegmentApi     ][Info   ] Usage statistic: actionRestart
[22:05:38.561][Notifications  ][Info   ] Docker Desktop will restart...
[22:08:44.540][ErrorReportWindow][Info   ] Open logs

**Comment by mikeparker** [comment] 2019-05-30 13:52
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 13:52 UTC
Labels: version/2.0.0.3
