### ISSUE TITLE
Docker failed to start - Issue : 'An unexcepted error occured'

### ISSUE THREAD

**Issue by DonovanDumeige** [docker/for-win#14459] opened 2024-12-02 09:27 UTC
### Description

Hello,

I have a issue when I launch Desktop for Windows. Finds below the error message printed on my screen: 

`running engine: waiting for the Docker API: engine linux/wsl failed to run: starting WSL engine: error spotted in wslbootstrap log: "[2024-12-02T09:25:58.486811330Z][wsl-bootstrap][F] more than one sd* disk in /sys/block with wwid ending by 57de6aa93848de02790adcb4: /dev/sdc,/dev/sde"`

Could you help me please ?

Thanks

PS : I'm not english native, sorry for my mistakes

### Reproduce

Just launch Docker

### Expected behavior

Docker runs correctly

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/version": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
```

### docker info

```bash
Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-ai.exe
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.18.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/info": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

730DA111-236F-498E-8713-7FEBB6B4447B/20241202085310

**Comment by andrea-reale** [comment] 2024-12-02 10:40
Hey @DonovanDumeige this seems to be a duplicate of [this existing issue](https://github.com/docker/for-win/issues/14453).

The problem arises due to other WSL2 distributions integrated with docker holding some state during the update.

You can either go back to 4.35.1, wait for 4.37 or try out the [development build](https://github.com/docker/for-win/issues/14453#issuecomment-2508117527) I have shared on the other GitHub issue page, that should address the problem. You may need to disable the WSL integration with your other distro and enable it again after passing to the new build.

Please, let us know how that goes, possibly on the other issue page.

[Closing as duplicate]

**Closed as not planned by andrea-reale** 2024-12-02 10:40 UTC
Labels: status/duplicate, version/4.36.0
