### ISSUE TITLE
Switch to windows containers fails

### ISSUE THREAD

**Issue by seals55** [docker/for-win#90] opened 2016-09-18 01:21 UTC
### Expected behavior

Run Windows Containers
### Actual behavior

Docker crashes
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.
  162DAE84-1A39-4CBD-9225-B35B0AEAFDF6/2016-09-17_21-06-13  
- a reproducible case if this is a bug, Dockerfiles FTW
  Can't get that far
- page URL if this is a docs issue or the name of a man page
- host distribution and version (Windows version, build number, etc)
  Windows 10 Enterprise version 1607 build 14393.105
### Steps to reproduce the behavior
1. Upgraded to Beta 26
2. Switched to Windows containers
3. Rebooted  
4. Crashed 

```
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

I also tried to reset to factory defaults, same errors.

Are there some manual steps needed to run Windows containers? 

Switching back to Linux containers works fine, docker run hello-world downloads and runs without issue.

Thanks!

```
[21:13:47.487][Notifications  ][Info   ] Docker is restarting...
[21:13:47.502][NamedPipeClient][Info   ] Sending Stop()...
[21:13:47.506][NamedPipeServer][Info   ] Stop()
[21:13:47.515][ApiProxy       ][Info   ] Killing existing com.docker.proxy with PID 20040
[21:13:47.527][NamedPipeClient][Info   ] Received response for Stop
[21:13:47.523][NamedPipeServer][Info   ] Stop done.
[21:13:47.530][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[21:13:47.537][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[21:13:48.423][WindowsDockerDaemon][Info   ] Starting...
[21:13:48.443][WindowsDockerDaemon][Info   ] Started
[21:13:48.450][ApiProxy       ][Info   ] Starting...
[21:13:48.483][WindowsDockerDaemon][Info   ] time="2016-09-17T21:13:48.482871900-04:00" level=info msg="Windows default isolation mode: hyperv" 
[21:13:48.499][ApiProxy       ][Info   ] Started
[21:13:48.500][WindowsDockerDaemon][Info   ] time="2016-09-17T21:13:48.500872500-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
[21:13:48.506][WindowsDockerDaemon][Info   ] time="2016-09-17T21:13:48.500872500-04:00" level=info msg="Loading containers: start." 
[21:13:48.522][ApiProxy       ][Info   ] docker proxy (on deprecated port): ready
[21:13:48.528][ApiProxy       ][Info   ] docker proxy: ready
[21:13:48.586][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:48.589][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:48.636][ApiProxy       ][Info   ] i/o timeout
[21:13:48.681][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:48.688][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:48.731][ApiProxy       ][Info   ] i/o timeout
[21:13:48.785][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:48.789][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:48.836][ApiProxy       ][Info   ] i/o timeout
[21:13:48.898][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:48.907][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:48.948][ApiProxy       ][Info   ] i/o timeout
[21:13:49.030][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.038][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.080][ApiProxy       ][Info   ] i/o timeout
[21:13:49.143][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.149][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.193][ApiProxy       ][Info   ] i/o timeout
[21:13:49.243][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.249][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.256][WindowsDockerDaemon][Info   ] Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Unspecified error
[21:13:49.262][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[21:13:49.265][WindowsDockerDaemon][Error  ] Process died
[21:13:49.335][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.339][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.343][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[21:13:49.380][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.383][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.386][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[21:13:49.421][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:13:49.424][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[21:13:49.427][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[21:13:49.425][NamedPipeServer][Error  ] Unable to execute Start: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
    at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[21:13:49.434][NamedPipeClient][Error  ] Unable to send Start: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

[21:13:49.443][Notifications  ][Error  ] Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

[21:13:49.450][Program        ][Info   ] Sending Bugsnag report 794ce8bd-0958-485d-bde0-408edc420d56...
[21:13:49.792][Program        ][Info   ] Bugsnag report 794ce8bd-0958-485d-bde0-408edc420d56 sent
[21:13:49.803][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[21:13:49.806][NamedPipeServer][Info   ] DownloadVmLogs()
[21:13:49.810][PowerShell     ][Info   ] Run script...
[21:13:49.856][HyperV         ][Warning] Unable to download logs: 2016/09/17 21:13:49 Failed to Dial 9a49ab65-e092-41df-a1bb-c108bf9a44c7 445ba2cb-e69b-4912-8b42-d7f494d007ea : The requested address is not valid in its context.

[21:13:49.863][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[21:13:49.860][NamedPipeServer][Info   ] DownloadVmLogs done.
```

**Comment by davidobrien1985** [comment] 2016-09-27 09:15
Same here on my Windows 10 machine.

**Comment by dgageot** [comment] 2016-09-29 11:12
@seals55 @davidobrien1985 This should be fixed in Beta27. However, as noted in the changelog, Windows Containers will really work with Windows 10 Pro as soon as the `KB3192366` update becomes public.
You might be able to go as far as running a `docker info` or `docker pull` though

**Comment by stopthatastronaut** [comment] 2016-09-29 23:24
> This should be fixed in Beta27

Ummm... yeah, nah. Updated to Beta27, still the same issue.

**Comment by stopthatastronaut** [comment] 2016-09-29 23:26
```
]> docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      windows/amd64
 Experimental: true
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
```

**Comment by BarnumD** [comment] 2016-09-30 13:17
Win 10 anniversary update applied. Beta 27 - build 7450.
Switch to windows containers..
`Error response from daemon: i/o timeout

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Backend.Backend.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)`

**Comment by dgageot** [comment] 2016-10-01 17:13
Can you make sure you have all the latest Windows updates? See here: Microsoft/Virtualization-Documentation#358

**Comment by davidobrien1985** [comment] 2016-10-02 08:47
Just updated Win10 to build 14936.

Crash log ID: 7FF335B8-A6FB-4C48-BC1E-B9F79F69CB3A/2016-10-02_19-45-36

```
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Backend.Backend.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by StefanScherer** [comment] 2016-10-14 05:48
There is a test script from Microsoft to check the system and get some more details.

```powershell
wget https://github.com/Microsoft/Virtualization-Documentation/blob/master/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing | iex
```

(It's like the check-config.sh script on Linux, and I like this idea).

The script explicitly checks that Windows 10 build should not be 14936.

**Comment by StefanScherer** [comment] 2016-10-14 07:27
This might help, got this from a Slack channel:

I managed to get it to work by deleting my NAT and nat'ed vSwitch, and then re-install.

( re-created the NAT vswitch following this: https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/setup_nat_network the "Multiple Applications using the same NAT")

**Comment by rs38** [comment] 2016-10-16 07:52
[-> deep link](https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/setup_nat_network#multiple-applications-using-the-same-nat)
which slack channel are you referring?

**Comment by enricosada** [comment] 2016-10-17 11:22
Same for me like @StefanScherer 

I just used https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/setup_nat_network the "Multiple Applications using the same NAT", no need for reinstall

Also i **didnt** do step 2, the remove of containernerwork ( `Get-ContainerNetwork | Remove-ContainerNetwork -force` ), so just recreated nat and dockernat and restarted the service

**Comment by friism** [comment] 2016-10-17 19:02
@seals55 have you checked whether this works with the latest Docker for Windows beta and with your Windows 10 system fully patched?

**Comment by seals55** [comment] 2016-10-19 00:32
@friism no, all windows updates + docker 1.12.2-beta28 (7813) still failed.

I followed the steps @enricosada linked and now it works

```
Get-ContainerNetwork | Remove-ContainerNetwork -force
Get-NetNat | Remove-NetNat
New-ContainerNetwork -Name nat -Mode NAT –subnetprefix 10.0.76.0/24
Remove-NetNAT
New-NetNat -Name DockerNAT -InternalIPInterfaceAddressPrefix 10.0.0.0/17
```

So some kind of issue with older docker setup in hyper-v I guess?

**Comment by b69ca** [comment] 2016-10-20 15:32
This issue appears to exist because you can only have a single hyper-v NAT network at present. When the switch to Windows containers happens, it seems to create a NAT network, resulting in this issue if one already exists.

**Comment by ac** [comment] 2016-10-26 04:20
1.12.3-rc1-beta29 (8202)
open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

**Comment by dfjackson** [comment] 2016-11-04 03:00
I ran the commands from @seals55 and it fixed the issue for me.  I'm running 1.12.3 beta 29.3

**Comment by MikkelHegn** [comment] 2016-11-11 16:56
I tried the above suggestion @seals55 without success.

My problem was a conflict with a config file, left over from a previous docker window 1.30 installation.

I fixed it by removing the file: c:\ProgramData\docker\config\daemon.json

**Comment by marjorienorm** [comment] 2016-11-24 04:53
I have a similar problem.  Everything works on the anniversary build, but when I upgraded to the Windows 10 insider build (fast ring) 14971.rs_prerelease.161111-1700 Windows Containers no longer work.  Switching the engine causes the following error

Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by rneugeba** [comment] 2016-11-25 10:07
@marjorienorm in general we can't support all insider builds, and Windows containers have known to be broken on some builds. Microsoft has utility which performs a number of checks https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

maybe you could try that?

**Comment by marjorienorm** [comment] 2016-11-25 20:50
Thanks for the pointer @rneugeba.  I ran the test and they all passed except for the items below.  I tried disabling and enabling the Windows 10 Container services to no avail.  Will revert back to anniversary or wait for a fix.

Describing Windows container settings are correct
 [-] Do not have DisableVSmbOplock set to 1 27ms
   Expected: {0}
   But was:  {1}
   72:              $regvalue.VSmbDisableOplocks | Should Be 0
   at <ScriptBlock>, C:\Dev\Microsoft\Tools\Virtualization-Documentation\windows-server-container-tools\Debug-ContainerHost\Debug-ContainerHost.ps1: line 72
 [+] Do not have zz values set 17ms
Describing The right container base images are installed
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 68ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, an
d then try the command again.
   at <ScriptBlock>, C:\Dev\Microsoft\Tools\Virtualization-Documentation\windows-server-container-tools\Debug-ContainerHost\Debug-ContainerHost.ps1: line 96
Describing Container network is created
 [-] Error occurred in Describe block 1.04s
   RuntimeException: Cannot index into a null array.
   at <ScriptBlock>, C:\Dev\Microsoft\Tools\Virtualization-Documentation\windows-server-container-tools\Debug-ContainerHost\Debug-ContainerHost.ps1: line 125

**Comment by MikkelHegn** [comment] 2016-11-28 17:15
I only got this to work with the 1.30 version (Not Docker for Windows), the caveat seems to be not being able to remove an old stucked ContainerNetwork, but if I stopped the HNS service (Stop-Service hns) I could remove it, and after restarting that service, unregistering docker and reregister, I can now run containers with network again.

**Comment by StefanScherer** [comment] 2016-11-30 07:54
I'm testing the Debug-ContainerHost.ps1 script of PR https://github.com/Microsoft/Virtualization-Documentation/pull/503 and also found that on Windows 10 after switching to Windows Containers the script complains about the `DisableVSmbOplock` registry key.

```
Describing Windows container settings are correct
 [-] Do not have DisableVSmbOplock set to 1 117ms
   Expected: {0}
   But was:  {1}
   75:              $regvalue.VSmbDisableOplocks | Should Be 0
   at <ScriptBlock>, C:\vagrant\resources\check.ps1: line 75
```

Using Windows 10 14393.447 + D4W Beta 30.1

**Comment by rs38** [comment] 2016-11-30 09:00
I also noticed that recently and deleted the reg key. From what I understand, this was a workaround for a bug some months ago?! I cannot confirm 100% but I think this could indeed be a lost setting as my PC was already used with testing containers in Q2 2016 with Insider Preview.

**Comment by dgageot** [comment] 2016-11-30 09:44
@amalm @pmsousa Beta 31 was just released with an updated `dockerd`. Please give it a try and leet us know if it's better!

**Comment by jornh** [comment] 2016-11-30 20:34
I'm on the beta channel. Have been experiencing the error + red whale icon on switching to Windows too.
@dgageot after I received the Beta 31 labelled `Version 1.13.0-rc2-beta31` today it looks like this error is gone for me 👍

**Comment by dgageot** [comment] 2016-12-01 06:09
Hi everyone, I'm going to close this issue. It seems like recent builds fix the original issue. Some issues like the invalid [DisableVSmbOplock](https://github.com/docker/for-win/issues/269) are reported elsewhere. As usual, feel free to reopen if you don't agree!

**Closed by dgageot** 2016-12-01 06:09 UTC
Labels: area/wincon, area/windows, kind/bug, status/0-more-info-needed, version/beta26

**Comment by dheater** [comment] 2016-12-02 05:14
I just started getting this error when I updated to `Version 1.13.0-rc2-beta31`

`DisableVSmbOplock` was set to `1`. I've changed it to `0` and confirmed that I no longer get an error message from the debug script (see below).

Crash report: 400BFA24-1C02-4015-98FA-CF9C153CE0A1/2016-12-01_23-13-55


Tried the NAT steps from @seals55 

PS C:\WINDOWS\system32> Get-ContainerNetwork | Remove-ContainerNetwork -force
PS C:\WINDOWS\system32> Get-NetNat | Remove-NetNat
PS C:\WINDOWS\system32> New-ContainerNetwork -Name nat -Mode NAT –subnetprefix 10.0.76.0/24

Name Id                                   Subnets        Mode SourceMac DNSServers DNSSuffix
---- --                                   -------        ---- --------- ---------- ---------
nat  842ba9dc-5b48-4c8b-9b83-99a0da75c7af {10.0.76.0/24} NAT


PS C:\WINDOWS\system32> Remove-NetNAT

Confirm
Are you sure you want to perform this action?
Performing operation Delete on Target H842ba9dc-5b48-4c8b-9b83-99a0da75c7af PolicyStore Local
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
PS C:\WINDOWS\system32> New-NetNat -Name DockerNAT -InternalIPInterfaceAddressPrefix 10.0.0.0/17


Name                             : DockerNAT
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 10.0.0.0/17
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True



PS C:\WINDOWS\system32> docker run -it -v c:\data:c:\data microsoft/nanoserver powershell
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified..
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\WINDOWS\system32> wget https://github.com/Microsoft/Virtualization-Documentation/raw/master/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing |
iex
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 149ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 39ms
 [+] Is not a build with blocking issues 34ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  46ms
 [+] Service is running 21ms
 [+] Docker.exe is in path 2.06s
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 37ms
Describing Windows container settings are correct
 [-] Do not have DisableVSmbOplock set to 1 44ms
   Expected: {0}
   But was:  {1}
   72:              $regvalue.VSmbDisableOplocks | Should Be 0
   at <ScriptBlock>, <No file>: line 72
 [+] Do not have zz values set 51ms
Describing The right container base images are installed
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 106ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command
 again.
   at <ScriptBlock>, <No file>: line 96
Describing Container network is created
 [-] Error occurred in Describe block 1.03s
   RuntimeException: Cannot index into a null array.
   at <ScriptBlock>, <No file>: line 125
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Warnings & errors from the last 24 hours
Logs saved to C:\WINDOWS\system32\logs_20161201-230139.csv

**Comment by hinell** [comment] 2017-08-09 10:29
Had this problem but solved by turning ``Containers`` feature ON through Windows Featureы manager.

![screenshot_1](https://user-images.githubusercontent.com/8136158/29115806-88e62fea-7d01-11e7-9f7f-72bb86d5b3d1.png)

Now switching between Linux and Windows containers works well: 
![screenshot_2](https://user-images.githubusercontent.com/8136158/29116061-56ced772-7d02-11e7-9601-6d1ab9750347.png)

The source of problem was following. Since I've had turned ON ``Hyper-V`` VM manually before allowing the docker to do it by itself seemingly it has failed to properly check out that all features are set on (or even ignored that checks) and just  passed installation silently so that I discovered problem only after installation.  That's it.

**Comment by DealWithMeal** [comment] 2018-10-23 12:22
Was able to switch after I did the Network reset (and restarted the PC) from the network menu
