### ISSUE TITLE
Dcker failed to initialize

### ISSUE THREAD

**Issue by ramubandela** [docker/for-win#11348] opened 2021-05-31 13:51 UTC
System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 281

  System.ArgumentException:
  Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.ArgumentException:
         Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
            at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
            at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Reflection.TargetInvocationException:
              Exception has been thrown by the target of an invocation.
                 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                 at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
              
                    System.Runtime.InteropServices.COMException:
                    Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
                       at Docker.Notifications.BackgroundUpdateWatcher..ctor(ISystrayNotifications systray, IUpdateStateNotifier updateStateNotifier) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Notifications\BackgroundUpdateWatcher.cs:line 12

**Comment by mat007** [comment] 2021-06-10 07:25
This may be similar to #11273 although the error is slightly different.
Can you check the `Background Intelligent Transfer Service` in the system service list?

**Comment by mat007** [comment] 2021-06-28 08:58
Closing as duplicate of #11273

**Closed by mat007** 2021-06-28 08:58 UTC
