### ISSUE TITLE
GUI not working on 2.2.0.0 with policy preventing access to windows registry

### ISSUE THREAD

**Issue by Malanius** [docker/for-win#5536] opened 2020-01-22 12:06 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B9AF104A-DE69-4983-9EAF-019F50D0C383/20200122114911

### Expected behavior

1. Select an option from the context menu of docker desktop that should open a window (settings, about...)
1. This windows should be opened.

### Actual behavior

Instead of a window opening, this message pops up:
![docker-fail](https://user-images.githubusercontent.com/6827667/72892015-ceb81700-3d15-11ea-85a1-3d99af72892c.png)

### Information

  - Windows Version: W10 1803 (build 17134.1246)
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no
 
This machine has set up policies to prevent users, even with administrator access, to modify windows registries. Unfortunately, I don't have any possibility to change the policies on this device.

### Steps to reproduce the behavior

Managed to reproduce with docker desktop 2.2.0.0 and W10 1909 (build 18363.592) on a device I have fully under control.

  1. Set up windows policy preventing registry editing
    1. Run gpedit
    1. Navigate to `User Configuration > Administrative tools > System`
    1. Enable policy `Prevent access to registry editing tools`
  1. Try to access docker desktop 2.2.0.0 GUI

**Comment by mat007** [comment] 2020-01-22 14:36
Thank you for the detailed reproduction steps, we were able to replicate this issue.

**Comment by MyDigitalLife** [comment] 2020-02-06 08:18
Is there any timeline when this will be fixed? We need version 2.2.0.0 to work with volumes but we can't do any setting changes because of this bug.

**Comment by mat007** [comment] 2020-02-06 08:33
We’ve fixed the bug and we’re looking at releasing a new public version hopefully within 2 weeks.

**Comment by stephen-turner** [comment] 2020-02-11 13:32
We have just released 2.2.0.3, which fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

**Closed by stephen-turner** 2020-02-11 13:32 UTC
Labels: status/1-acknowledged, version/2.2.0.0
