### ISSUE TITLE
docker not loading 

### ISSUE THREAD

**Issue by kifeakor** [docker/for-win#4382] opened 2019-08-01 15:49 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
[log.txt](https://github.com/docker/for-win/files/3457547/log.txt)

### Information

  - Windows Version: 10
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. download docker for windows 
  2. install and try to open

**Comment by mikeparker** [comment] 2019-08-02 12:23
```
[16:39:45.612][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'THD09' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
```

**Comment by mikeparker** [comment] 2019-08-02 14:55
Closing as duplicate of https://github.com/docker/for-win/issues/1221

* Your Hyper-V configuration is likely broken. This may be caused by a windows update.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-08-02 14:55 UTC
Labels: status/0-triage
