### ISSUE TITLE
2020-05 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4551853) BREAKS Swarm network

### ISSUE THREAD

**Issue by djarvis** [docker/for-win#6787] opened 2020-05-18 20:52 UTC
Windows Server 2019 running Docker/Swarm, ingress network was working fine until this was installed:

2020-05 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4551853)

This broke something with the ingress network such that no traffic could enter through any exposed/published ports, either from the local machine or remotely.

Uninstalling this update made it all work again.

**Comment by metrotyranno** [comment] 2020-05-19 06:17
Docker is also unable to update with this KB installed. Installer shows (2.3.0.2): 

Docker Desktop requires Windows 10 Pro/Enterprise (15063+) or Windows 10 Home (19018+).

Version	10.0.17763 Build 17763 (Server 2019 Standard)

**Comment by stephen-turner** [comment] 2020-05-19 07:58
@djarvis It sounds like that is an issue in the Engine, not in Docker Desktop. Could you please file the bug at moby/moby instead? (Sorry, I would move it myself, but I can't because the Engine is not even part of the docker org).

**Comment by stephen-turner** [comment] 2020-05-19 08:02
@metrotyranno Your issue is completely different, and is a dupe of #6769. Please try not to mix up two bugs in one ticket, thanks.

**Closed** 2020-05-19 08:02 UTC

**Comment by jabteles** [comment] 2020-05-27 13:33
@djarvis I also have this issue and I'm trying to uninstall this update, can you send me the link for the bug at moby/moby?

**Comment by djarvis** [comment] 2020-05-27 13:37
@jabteles https://github.com/moby/moby/issues/40998
