### ISSUE TITLE
error perform `docker login` command

### ISSUE THREAD

**Issue by aleksey-dv** [docker/for-win#12500] opened 2022-01-18 15:13 UTC
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: CA94A84A-DFD8-4ED0-ACBB-C8D30FE36785/20220118150827

After upgrade to ver 4.4.3 (73365) can not perform docker login.
Factory reset, full reinstall and switch between WSL2/Hyper-V doesn't help.

### Actual behavior
```
[018:18:08:09.734][E] (a5a7c7ad) 0b49d028-CredentialHelperPKG C<-S NoResponse POST /registry/credstore-updated (2.0008ms): Post "http://ipc/registry/credstore-updated": open /run/host-services/backend.sock: The system cannot find the path specified.
[common/pkg/backend.(*backendClient).NotifyCredstoreUpdated(0xdb8751)
[       common/pkg/backend/client.go:358 +0x42
[main.addCredentialsHelperCommand.func1.1()
[       common/cmd/docker-credential-desktop/main.go:21 +0x31
[common/pkg/docker-credential-desktop.Helper.Add({0xc0002021c0, 0xdeddc0}, 0xc0002264b0)
[       common/pkg/docker-credential-desktop/helper.go:59 +0xf4
[github.com/docker/docker-credential-helpers/credentials.Store({0xea5710, 0xc0002100f0}, {0xe95180, 0xc000006010})
[       vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:107 +0x229
[github.com/docker/docker-credential-helpers/credentials.HandleCommand({0xea5710, 0xc0002100f0}, {0xc0000320a0, 0xea5710}, {0xe95180, 0xc000006010}, {0xe951c0, 0xc000006018})
[       vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:71 +0xf3
[github.com/docker/docker-credential-helpers/credentials.Serve({0xea5710, 0xc0002100f0})
[       vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:58 +0xf4
[main.addCredentialsHelperCommand.func1(0xc000474280, {0xdacfd4, 0x0, 0x0})
[       common/cmd/docker-credential-desktop/main.go:23 +0x2a
[github.com/spf13/cobra.(*Command).execute(0xc000474280, {0x138e420, 0x0, 0x0})
[       vendor/github.com/spf13/cobra/command.go:860 +0x5f8
[github.com/spf13/cobra.(*Command).ExecuteC(0xc000474000)
[       vendor/github.com/spf13/cobra/command.go:974 +0x3bc
[github.com/spf13/cobra.(*Command).Execute(...)
[       vendor/github.com/spf13/cobra/command.go:902
[main.main()
[       common/cmd/docker-credential-desktop/main.go:45 +0x107
[018:18:08:09.819][E] (a5a7c7ad-1) 0b49d028-CredentialHelperPKG C<-S NoResponse GET /ping (519.4µs): Get "http://ipc/ping": open /run/host-services/backend.sock: The system cannot find the path specified.
```

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? = Yes
  - Is the problem new? = Yes 
  - Did the problem appear with an update? = Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
--> docker login -u user any.priv.registry
  - Windows Version: 10
  - Docker Desktop Version: 4.3.3
  - WSL2 or Hyper-V backend?  Both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by mat007** [comment] 2022-01-19 05:39
Thank you for the report, we are looking into this.
Same as https://github.com/docker/docker-credential-helpers/issues/213

**Comment by mat007** [comment] 2022-01-19 05:41
Are you running `docker login` in a WSL 2 shell?
Does it work from a Windows shell or Powershell?
Does signing in from the UI work?

**Comment by aleksey-dv** [comment] 2022-01-19 08:56
> Thank you for the report, we are looking into this. Same as [docker/docker-credential-helpers#213](https://github.com/docker/docker-credential-helpers/issues/213)
Looks like this is same issue.

> Are you running docker login in a WSL 2 shell?
Yes. WSL 2 Ubuntu 18.04

> Does it work from a Windows shell or Powershell?
Yes. It works normally from native cmd and Powershell

>  Does signing in from the UI work?
Sorry, but I didn't find out, how to do this :)

**Comment by mat007** [comment] 2022-01-19 09:00
> Sorry, but I didn't find out, how to do this :)

Either by selecting `Sign in` in the task bar menu, or by opening the UI and clicking the `Sign in` button in the top right corner.
But I guess it will work if it works from a native cmd shell :)

**Comment by mat007** [comment] 2022-01-21 06:10
I will close this issue as a duplicate of https://github.com/docker/docker-credential-helpers/issues/213 which contains a workaround and a link to a new Docker Desktop build.
We will likely shortly release a Docker Desktop 4.4.4 with a fix.

**Comment by mat007** [comment] 2022-01-21 09:42
Actually, I’ll re-open this issue as that other one had a different initial root cause.

**Comment by mat007** [comment] 2022-01-25 06:42
We have release Docker Desktop 4.4.4 with a fix for this issue.
Thank you!

**Closed by mat007** 2022-01-25 06:42 UTC

**Comment by MihailProcudin** [comment] 2022-02-08 17:12
I am on docker desktop 4.4.4 and having this issue

**Comment by aswin-in-philips** [comment] 2022-02-09 05:33
i have updated to Docker Desktop 4.4.4 and after that all the RUN commands in my Dockerfile are throwing below errors.

Please can someone assist me here

Warning: rning] The requested image's platform (linux/amd64) does not match the detected host platform (windows/amd64) and no specific platform was requested

The command '/bin/sh -c yarn' returned a non-zero code: 4294967295: failed to shutdown container: container 607947ad1ea515f0a52d1442674124f7b9f8ad12535e06da62c8ff60a011e24f encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 607947ad1ea515f0a52d1442674124f7b9f8ad12535e06da62c8ff60a011e24f encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)
