### ISSUE TITLE
Volume mounts do not work on windows 10

### ISSUE THREAD

**Issue by billhab** [docker/for-win#77] opened 2016-09-13 14:06 UTC
### Expected behavior
docker run -it -v //c/Users://c/users Ubuntu bash
ls -al /c/users should show windows usernames

### Actual behavior
Volume is created but /c/users is empty

### Information

I have read all the issues where this has been reported before.  Nothing I have tried makes any difference. It doesn't work.  Even though volume is created in the container, it does not show any directories and files from the source path.  Neither Issue #25 or Issue #50 solve this problem. 

1. Have disabled the firewall.
2. Shared c in docker settings.  have reset and supplied credentials.
3. Have tried all variations of command syntax for volume parameter
4. No help from freenode docker channel. 
5. Java client api using mounts works fine if Linux -> Linux.  Same code fails with windows.
6. When I inspect container it contains the proper source location.
7. Fails the same whether run under powershell or cmd. 

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

A86A3BDC-3635-4682-A3B1-467D8ABE2260/2016-09-13_09-56-40

### Steps to reproduce the behavior

  1. ... docker run -it  -v //c/Users:/users Ubuntu bash
  2. ...ls -al /users  
Volume is mounted but nothing in the directory.

**Comment by billhab** [comment] 2016-09-13 14:13
Fails the same way if powershell or cmd

If I inspect the container the mount appears with proper source location. 

Running on Windows 10 pro

Found dns server 192.168.1.1
[09:49:11.084][ApiProxy       ][Info   ] Forward DNS query on udp to 192.168.1.1:53
[09:49:11.085][ApiProxy       ][Info   ] Forward DNS query on udp to 192.168.1.1:53
[09:49:11.090][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[a5be] 192.168.65.2:37451 <- secondary(wrapped) (a5be Response:0 na:c:r:ra 3 <qs:moby.local. <A|IN>> <an:> <au:> <ad:>)
[09:49:11.090][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 42430 ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.local.	IN	 A 
[09:49:11.092][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 42430 ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.local.	IN	 A 
[09:49:11.092][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 13135 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.	IN	 A 
[09:49:11.091][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[a5be] 192.168.65.2:37451 <- secondary(wrapped) (a5be Response:0 na:c:r:ra 3 <qs:moby.local. <A|IN>> <an:> <au:> <ad:>)
[09:49:11.091][VpnKit         ][Info   ] ICMP Destination Unreachable: Destination port unreachable
[09:49:11.101][VpnKit         ][Info   ] ICMP Destination Unreachable: Destination port unreachable
[09:49:11.100][ApiProxy       ][Info   ] Forward DNS query on udp to 192.168.1.1:53
[09:49:11.103][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 13135 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.	IN	 A 
[09:49:11.104][ApiProxy       ][Info   ] Forward DNS query on udp to 192.168.1.1:53
[09:49:11.104][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NOERROR, id: 13135 ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.	IN	 A  ;; ANSWER SECTION: moby.	0	IN	A	92.242.140.21 
[09:49:11.104][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NOERROR, id: 13135 ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;moby.	IN	 A  ;; ANSWER SECTION: moby.	0	IN	A	92.242.140.21 
[09:49:11.101][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] 192.168.65.2:51648 -> 192.168.65.1 334f Query:0 na:c:r:rn 0 <qs:moby. <A|IN>> <an:> <au:> <ad:>
[09:49:11.108][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] 192.168.65.2:51648 -> 192.168.65.3 334f Query:0 na:c:r:rn 0 <qs:moby. <A|IN>> <an:> <au:> <ad:>
[09:49:11.108][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[09:49:11.109][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] Forwarding to 10.0.75.1 (primary(sole))
[09:49:11.109][VpnKit         ][Debug  ] com.docker.slirp.exe: Socket.Datagram.input 192.168.65.2:51648-10.0.75.1:53 (DNS[334f]): creating UDP NAT rule
[09:49:11.110][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[09:49:11.110][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] Forwarding to 10.0.75.1 (secondary(wrapped))
[09:49:11.111][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] 192.168.65.2:51648 <- secondary(wrapped) (334f Response:0 na:c:r:ra 0 <qs:moby. <A|IN>> <an:moby <IN|0> [A (92.242.140.21)]> <au:> <ad:>)
[09:49:11.111][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[334f] 192.168.65.2:51648 <- secondary(wrapped) (334f Response:0 na:c:r:ra 0 <qs:moby. <A|IN>> <an:moby <IN|0> [A (92.242.140.21)]> <au:> <ad:>)
[09:49:11.471][VpnKit         ][Info   ] com.docker.slirp.exe: hvsock connected successfully
[09:49:11.485][VpnKit         ][Info   ] com.docker.slirp.exe: Using protocol TwoThousand msize 8192
[09:49:11.795][HyperV         ][Info   ] Wait for the VM to get an IP address
[09:49:12.984][HyperV         ][Info   ] Wait for the VM to get an IP address
[09:49:14.001][HyperV         ][Info   ] Wait for the VM to get an IP address
[09:49:15.099][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[09:49:15.099][ApiProxy       ][Info   ] Dial Hyper-V socket fe450b69-c677-4610-9937-8b0a5cd1a5ac:23a432c2-537a-4291-bcb5-d62504644739
[09:49:23.999][ApiProxy       ][Info   ] proxy << GET /v1.24/containers/json
[09:49:24.001][Cmd            ][Info   ] CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[09:49:24.009][DockerDaemonChecker][Info   ] Docker daemon is running
[09:49:24.013][NamedPipeClient][Info   ] Received response for Start
[09:49:24.011][NamedPipeServer][Info   ] Start done.
[09:49:24.017][NamedPipeClient][Info   ] Sending TryShare(C, bihaber:**********)...
[09:49:24.018][NamedPipeServer][Info   ] TryShare(C, bihaber:**********)
[09:49:24.058][Cmd            ][Info   ] Share name        C
[09:49:24.059][Cmd            ][Info   ] Path              C:\
[09:49:24.059][Cmd            ][Info   ] Remark            
[09:49:24.060][Cmd            ][Info   ] Maximum users     No limit
[09:49:24.061][Cmd            ][Info   ] Users             
[09:49:24.062][Cmd            ][Info   ] Caching           Manual caching of documents
[09:49:24.062][Cmd            ][Info   ] Permission        Everyone, FULL
[09:49:24.063][Cmd            ][Info   ] 
[09:49:24.063][Cmd            ][Info   ] The command completed successfully.
[09:49:24.063][Cmd            ][Info   ] 
[09:49:24.064][SambaShare     ][Info   ] "C" is shared
[09:49:24.064][SambaShare     ][Info   ] Challenging credentials with host
[09:49:24.110][SambaShare     ][Info   ] Challenging credentials with host succeeded
[09:49:24.111][NamedPipeServer][Info   ] TryShare done.
[09:49:24.112][NamedPipeClient][Info   ] Received response for TryShare
[09:49:24.113][NamedPipeClient][Info   ] Sending Mount(C, bihaber:**********)...
[09:49:24.114][NamedPipeServer][Info   ] Mount(C, bihaber:**********)
[09:49:24.114][HyperV         ][Info   ] Mount C
[09:49:24.341][NamedPipeClient][Info   ] Received response for Mount
[09:49:24.342][NamedPipeClient][Info   ] Sending TryShare(D, bihaber:**********)...
[09:49:24.340][NamedPipeServer][Info   ] Mount done.
[09:49:24.343][NamedPipeServer][Info   ] TryShare(D, bihaber:**********)
[09:49:24.368][Cmd            ][Info   ] Share name        D
[09:49:24.369][Cmd            ][Info   ] Path              D:\
[09:49:24.370][Cmd            ][Info   ] Remark            
[09:49:24.370][Cmd            ][Info   ] Maximum users     No limit
[09:49:24.371][Cmd            ][Info   ] Users             
[09:49:24.371][Cmd            ][Info   ] Caching           Caching disabled
[09:49:24.371][Cmd            ][Info   ] Permission        BIHABER-PC\bihaber, FULL
[09:49:24.372][Cmd            ][Info   ] 
[09:49:24.373][Cmd            ][Info   ] The command completed successfully.
[09:49:24.373][Cmd            ][Info   ] 
[09:49:24.373][SambaShare     ][Info   ] "D" is shared
[09:49:24.374][SambaShare     ][Info   ] Challenging credentials with host
[09:49:24.415][SambaShare     ][Info   ] Challenging credentials with host succeeded
[09:49:24.416][NamedPipeServer][Info   ] TryShare done.
[09:49:24.417][NamedPipeClient][Info   ] Received response for TryShare
[09:49:24.418][NamedPipeClient][Info   ] Sending Mount(D, bihaber:**********)...
[09:49:24.419][NamedPipeServer][Info   ] Mount(D, bihaber:**********)
[09:49:24.419][HyperV         ][Info   ] Mount D
[09:49:24.632][NamedPipeClient][Info   ] Received response for Mount
[09:49:24.633][Notifications  ][Info   ] Docker is running
[09:49:24.631][NamedPipeServer][Info   ] Mount done.
[09:49:41.922][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/create [rewriteBinds]
[09:49:41.922][ApiProxy       ][Info   ] Rewrote mount //c/Users://c/users (volumeDriver=) to /c/Users://c/users
[09:49:41.982][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/create
[09:49:41.983][ApiProxy       ][Info   ] Dial Hyper-V socket fe450b69-c677-4610-9937-8b0a5cd1a5ac:23a432c2-537a-4291-bcb5-d62504644739
[09:49:42.491][ApiProxy       ][Info   ] proxy << POST /v1.24/containers/create
[09:49:42.494][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/attach?stderr=1&stdin=1&stdout=1&stream=1
[09:49:42.496][ApiProxy       ][Info   ] Dial Hyper-V socket fe450b69-c677-4610-9937-8b0a5cd1a5ac:23a432c2-537a-4291-bcb5-d62504644739
[09:49:42.511][ApiProxy       ][Info   ] Upgrading to raw stream
[09:49:42.513][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/start [start]
[09:49:42.514][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/start
[09:49:42.516][ApiProxy       ][Info   ] Dial Hyper-V socket fe450b69-c677-4610-9937-8b0a5cd1a5ac:23a432c2-537a-4291-bcb5-d62504644739
[09:49:43.455][ApiProxy       ][Info   ] proxy << POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/start
[09:49:43.457][ApiProxy       ][Info   ] proxy >> POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/resize?h=50&w=120
[09:49:43.459][ApiProxy       ][Info   ] Dial Hyper-V socket fe450b69-c677-4610-9937-8b0a5cd1a5ac:23a432c2-537a-4291-bcb5-d62504644739
[09:49:43.475][ApiProxy       ][Info   ] proxy << POST /v1.24/containers/55a8494d9b9d9b60c5c6b3e8801c345837e67a984e1bea2b09b5323a3770050a/resize?h=50&w=120
[09:50:26.883][FeedbackSettings][Info   ] Open logs

**Comment by billhab** [comment] 2016-09-13 18:34
![snap1](https://cloud.githubusercontent.com/assets/4042769/18486466/1c03ee4e-79bf-11e6-96cc-5d96d236b967.gif)

**Comment by MadLittleMods** [comment] 2016-09-14 02:05
@billhab I think you are experiencing Hyper-V driver not supporting mounting volumes, see https://github.com/docker/docker/issues/22981

> I don't think the hyper-v driver does host (win) to guest (boot2docker) filesharing, so volume-mounting from the host windows 10 filesystem is not expected to work.
>
>https://github.com/docker/docker/issues/22981#issuecomment-221637488

> Ah! Yes, the Hyper-V machines don't have this as an option, only VirtualBox (and Docker for Windows)
>
> https://github.com/docker/docker/issues/22981#issuecomment-221638656

**Comment by billhab** [comment] 2016-09-14 02:27
I think this is going in the direction that I will not be able to mount volumes successfully in a Windows environment.  What good is docker if I can't access my data?  I have read so many comments the past couple days that make my head spin.  Do this: turn off your firewall or change firewall rules, play with domain user name, remove passwords with funny characters,  reset credentials/restart Docker.   Is there ANYTHING which works here?  Would going to virtual box solve the problem?  Maybe not because some people report that doesn't work either.  Excuse me but I'm really frustrated with this scenario and no reliable answers.

**Comment by friism** [comment] 2016-09-14 02:30
@MadLittleMods that's not the case - Docker for Windows supports volume mounting.

@billhab can you try the test command suggested in the app?

    docker run --rm -v c:/Users:/data alpine ls /data

**Comment by billhab** [comment] 2016-09-14 02:43
@MadLittleMods - If you look at the screen shot which is the above you'll see I have done that. In fact I have done it about a hundred times when trying different combinations of suggestions from various people.  It simply doesn't work.  Now I heard that using hyper-v with Docker which is my setup does not support mounting volumes. 
Is my only recourse to uninstall docker and reinstall with virtualbox???

**Comment by MadLittleMods** [comment] 2016-09-14 03:09
@friism What are the intricacies/caveats of it? Here is a quote I found from you:

> I don't think volumes are expected to work with the hyper-v driver. You should use the (default) virtualbox driver.
>
> https://github.com/docker/docker/issues/21909#issuecomment-207885513

---

Trying not to butt into this issue but here is an example:

```
// Trying any of these combos
SET WORKSPACE=.
for /f "delims=" %a in ('pwd') do @set WORKSPACE=%a
for /f "delims=" %a in ('cd') do @set WORKSPACE=%a
```

`docker-compose.yml`
```
mongosetup:
  image: mongo:3.2
  volumes:
   - ${WORKSPACE}:/src
  working_dir: /src
  entrypoint: [ "/src/mongo-setup.sh" ]
```


```
> docker inspect mongosetup_1
...
"Mounts": [
            {
                "Source": "/c/Users/MLM/Documents/GitHub/something",
                "Destination": "/src",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
...
```

But the entrypoint can't be found

```
> docker-compose up -d --no-recreate
ERROR: for mongosetup  Cannot start service mongosetup: oci runtime error: exec: "/src/mongo-setup.sh": stat /src/mongo-setup.sh: no such file or directory
```

**Comment by friism** [comment] 2016-09-14 03:11
@MadLittleMods that comment was talking about something created with  `docker-machine create` using the hyper-v driver. Volume mounting from host won't work with that.

This question is about Docker for Windows, which has host volume mounting support and is different than docker machine.

**Comment by billhab** [comment] 2016-09-14 03:29
I'm sorry guys. this isn't helping me.  I just want to have access to a windows set of files (about 40gb of data) in a directory tree from a docker container.  Mounting the path as a volume doesn't work.   I'd like to find out how to make it work.  If there isn't a way to get it working then I'd like to know so I can move on to finding another solution.

**Comment by phinz** [comment] 2016-09-14 08:22
i have the same issue. The example command has a empty result:
```
> docker run --rm -v c:/Users:/data alpine ls /data
>
``` 

Until i tried to mount a subfolder:
```
> docker run --rm -v c:/Users/phinz:/data alpine ls /data
>
> docker run --rm -v c:/Users:/data alpine ls /data
> phinz
```
That seems very strange, because there are still more user folders in the path "c:/Users".

```
> ls c:/Users
drwxr-xr-x 1 phinz 1049089   0 Jan  4  2016 ./
drwxr-xr-x 1 phinz 1049089   0 Sep  8 09:24 ../
lrwxrwxrwx 1 phinz 1049089  14 Okt 30  2015 All Users -> c:/ProgramData/
drwxr-xr-x 1 phinz 1049089   0 Jan  4  2016 Default/
lrwxrwxrwx 1 phinz 1049089  16 Okt 30  2015 Default User -> c:/Users/Default/
drwxr-xr-x 1 phinz 1049089   0 Sep 13 17:43 phinz/
drwxr-xr-x 1 phinz 1049089   0 Jan  4  2016 Public/
```
```
> docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

OS: Windows 10 Enterprise
```

**Comment by marc1404** [comment] 2016-09-14 09:57
Experiencing the same problems as @phinz 
Windows 10 Pro, Version 1511
Docker for Windows, Version 1.12.0-stable, Build 5968

**Comment by billhab** [comment] 2016-09-14 13:48
Not only do you not see the content of the volume but you can't write back into it.  The source never sees what has been copied there.  This may be related or a different issue. 

PS C:\Users\bihaber> docker run -it -v //d/scratch:/scratch bills:1.2 bash
root@b73c99d9b2c5:/# ls scratch
root@b73c99d9b2c5:/# ls -al scratch
total 4
drwxr-xr-x   2 root root   40 Sep 13 21:27 .
drwxr-xr-x 210 root root 4096 Sep 14 13:42 ..
root@b73c99d9b2c5:/# cp /bin/runtests.sh /scratch/runtests.sh
root@b73c99d9b2c5:/# ls -al scratch
total 16
drwxr-xr-x   2 root root   60 Sep 14 13:43 .
drwxr-xr-x 210 root root 4096 Sep 14 13:42 ..
-rwxr-xr-x   1 root root 9143 Sep 14 13:43 runtests.sh
root@b73c99d9b2c5:/#

**Comment by dgageot** [comment] 2016-09-16 16:50
@billhab Have you tried version Beta26? Both @marc1404 and @phinz report that it fixes their issue

**Comment by billhab** [comment] 2016-09-16 17:10
Is it newer than what I am running and if so how do I get it?
PS C:\Users\bihaber> docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
PS C:\Users\bihaber>

**Comment by thasmo** [comment] 2016-09-16 17:16
@dgageot I'm running Docker for Windows version `1.12.1-beta26` and Docker doesn't mount the specified directory. Running `docker run --rm -v c:/Users:/data alpine ls -al /data` lists an empty directory, although I've enabled to share `C:` in the Docker UI settings.

**Comment by billhab** [comment] 2016-09-16 17:24
I just tried Docker for Windows version 1.12.1.beta26 and it doesn't work either. 
Can I get this to work if I use Docker Toolbox instead??

**Comment by billhab** [comment] 2016-09-16 18:27
I have uninstalled Docker, then installed Docker toolbox.   Neither work. 
I reinstalled 1.12.0 stable then got notice of new stable version. 
I installed stable version but installer told me it didn't have privileges to install new services. 
I'm done playing games here.

**Comment by thasmo** [comment] 2016-09-16 21:06
So, after trying over a dozen different tweaks, settings and changes it suddenly works but I'm not able to break it on purpose so I've no idea what it did it. :(

**Comment by protubero** [comment] 2016-09-19 08:08
I'm trying to Mount host volumes for some weeks now, without success. Log files tell me, that sharing works, but the Directory Content shown only lists previously mounted Folders and nothing else. I'm Kind of frustrated with this.

D9E7060A-B59A-4546-BAB8-3E537A4C22D6/2016-09-19_10-04-47

**Comment by josemanners** [comment] 2016-09-20 07:29
I followed the instructions in this article https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

and after a few tries the way I made it work was by giving Docker the local computer name as part of the credential (i.e. MYCOMPUTER\DockerHost )

**Comment by billhab** [comment] 2016-09-20 13:48
josemanners - is your system windows 10 with hyper-v?

**Comment by dgageot** [comment] 2016-09-21 14:49
@billhab @thasmo @protubero @josemanners Stay tuned and thank your for being really patient. A better file sharing should ship in next beta!

**Comment by josemanners** [comment] 2016-09-21 15:36
@billhab to answer your question, I'm running Windows 10 Enterprise Build 14393.105

**Comment by moler** [comment] 2016-09-22 07:28
I had the similar issue with Docker 1.12.0-stable (Hyper-V) on Windows 10. I thing that the main problem was with my firewall which blocked Hyper-V Virtual Ethernet Adapter (DockerNAT). I did follow:

1. Updated to new stable version 1.12.1
2. Shared c in Docker settings and restarted Docker via Setting-Reset-Restart Docker
3. Turned off antivirus software including firewall
4. Restarted Docker via Setting-Reset-Restart Docker

You can try it.

**Comment by billhab** [comment] 2016-09-22 13:43
@moler All that was tried. Didn't work.  I have McAfee firewall. Turning it off didn't help.

**Comment by billhab** [comment] 2016-09-22 13:44
@dgageot  What makes you believe that the next beta will fix this issue?

**Comment by dgageot** [comment] 2016-09-28 19:46
@billhab Beta27 was released today with hardened file sharing feature. Could you take a look and close this issue if it is fixed? Thanks a lot!

**Comment by billhab** [comment] 2016-09-29 01:14
It seemed to work on Beta27 before Docker crashed.  Beta27 is very unstable.  Since it crashed I can't get Docker to run again.

**Comment by dgageot** [comment] 2016-09-29 11:41
@billhab Do you have a log or a diagnostic id to share?

**Comment by billhab** [comment] 2016-09-29 12:38
Every time Docker crashed it took a diagnostic dump which it said was being uploaded. So I assume someplace that information is available.

**Comment by dgageot** [comment] 2016-09-29 12:44
@billhab if you give me a diagnostic id for a recent crash, yes I can find this information.

**Comment by billhab** [comment] 2016-09-29 13:04
I noticed several diagnostic ids in the crash notifications. How do I find what those Ids are?

**Comment by protubero** [comment] 2016-10-02 18:43
I tested it again without success with the folowing version of Docker:
Docker version 1.12.2-rc1, build 45bed2c, experimental

It fails when i enter my credentials. The log file says:

[20:36:16.082][SambaShare     ][Error  ] Unable to mount C drive: mount error(115): Operation in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
mount: mounting //10.0.75.1/C on /c failed: Invalid argument

**Comment by protubero** [comment] 2016-10-02 18:51
Now it works! I ended Kasperski Endpoint Security 10 for Windows, and it immediatly worked ;-)

**Comment by billhab** [comment] 2016-10-08 12:55
This thing still doesn't work!!   I have drive C and drive D shared.  Docker asked for credentials and the setting panel shows both drives check.  But when I try the volume mount I get. 

com.github.dockerjava.api.exception.InternalServerErrorException: D: drive is not shared. Please share it in Docker for Windows Settings

**Comment by billhab** [comment] 2016-10-08 13:13
Everytime I try to set the drives to be shared and Accept,  I enter credentials it spins for a minute and then removes the checks from the drives.

**Comment by billhab** [comment] 2016-10-08 14:11
It works only if I am not connected to my VPN and the firewall is turned off.

**Comment by dgageot** [comment] 2016-10-18 14:26
@billhab @protubero Thanks a lot for your feedback. I'm going to close this issue as a duplicate of https://github.com/docker/for-win/issues/114

**Closed** 2016-10-18 14:31 UTC
Labels: area/mounts, kind/bug, version/beta28

**Comment by richarddowner** [comment] 2017-05-27 22:45
Encountered this issue today, May 2017 
docker for windows version `17.03.1-ce-win12 (12058)`
Resolved it by unsharing C drive then resharing. 
Hopefully that helps someone

**Comment by dharmeshkakadia** [comment] 2017-05-30 00:08
+1

**Comment by vladyslavmunin** [comment] 2017-06-06 10:04
I also encountered this issue,
resolved it with setting  in HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters 
EnableAuthenticateUserSharing to 1
maybe it can  helps someone

**Comment by enlyn** [comment] 2017-06-12 07:28
+1

**Comment by jasonbivins** [comment] 2017-06-12 14:28
Hi @vladyslavmunin    I'll capture that and turn it into a KB article, thanks!

**Comment by WizX20** [comment] 2017-06-30 18:59
Does not work on 17.06.0-ce-win18 (12627) windows 10. Tried re-sharing drives, and editing the reg-key. When I change a volume to D:\My-Path, and enable volume sharing, it will always map to the default location. Then the container will fail to boot: Operation not permitted, terminating.

**Comment by zbennett10** [comment] 2017-08-08 23:17
Just wanted to chime in to say @richarddowner solution worked for me

**Comment by akhchan** [comment] 2018-02-28 22:56
Works great with richarddowner's solutiion.  Thanks.

**Comment by Puetz** [comment] 2018-05-15 09:29
I just wanted to mount a local folder to my container and used the exact same commands that worked multiple times in the past
```
docker run -d --name core --mount type=bind,source="C:\Users\...\myapp",target=/app python
docker run -d --name core -v "C:/Users/.../myapp":/app python
```
but non of them worked.
I also used 
`docker commit <container_id> my-broken-container && docker run -it my-broken-container /bin/bash`
in order to take a look into the app folder and it was empty. 

I reset my credentials, changed my password and even reinstalled Docker but it's still not working. Does anybody have an idea how I can fix this?
Thanks.

**Comment by sharkvan** [comment] 2018-07-12 04:21
Just and FYI, 

I was running into this issue where the folder mounting was not working. I was trying to run docker via the terminal Cmder. Cmder was doing something that was making the mount operation fail. So if you're reading this and using Cmder, switch to powershell on Windows. 

On a side note, I was docker a lot on linux, I can't believe how slow it is on Windows, PAINFUL.

**Comment by liesislukas** [comment] 2018-08-12 01:08
I think it was related to password change on windows user. I used @richarddowner solution to fix.

**Comment by Noext** [comment] 2018-09-05 10:51
@liesislukas is right, i have change my windows password and disk sharing was **** up after that, need to unshare and share all driver after that

**Comment by navarq** [comment] 2018-11-05 10:35
Resetting credentials via the tray icon, in settings, shared drive 

Then specifying the full location of the directory to be mounted solved the issue for me.

**Comment by LeonardAB** [comment] 2018-12-04 06:51
experienced same condition as @liesislukas and @Noext , I have to change password regularly and did not realize that it affected the docker drive sharing credential. @richarddowner solution worked like a charm. Thanks a lot!!! 

It might be good if when the mounting fails, docker can give an error message.

**Comment by higkoo** [comment] 2018-12-05 08:18
https://github.com/docker/for-win/issues/77#issuecomment-306440370

error is still exist.
> docker version
> Client: Docker Engine - Community
>  Version:           18.09.0
>  API version:       1.39
>  Go version:        go1.10.4
>  Git commit:        4d60db4
>  Built:             Wed Nov  7 00:47:51 2018
>  OS/Arch:           windows/amd64
>  Experimental:      false

> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.0
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.4
>   Git commit:       4d60db4
>   Built:            Wed Nov  7 00:55:00 2018
>   OS/Arch:          linux/amd64
>   Experimental:     false

>   [16:13:26.271][SambaShare     ][Error  ] Unable to mount C drive: 10.22.33.1 (10.22.33.1:445) open
>   rm: cannot remove '/c': No such file or directory
>   rm: cannot remove '/C': No such file or directory
>   umount: /host_mnt/c: not mounted.
>   mount.cifs kernel mount options: 
>   ip=10.22.33.1,unc=\\10.22.33.1\C,noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,sec=ntlmsspi,user=higkoo,domain=BILIOPS,pass=********
>   mount error(13): Permission denied
>   Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**Comment by alitarraf** [comment] 2019-03-02 20:22
For those using docker toolbox, what worked for me is adding shared drive in the virtual box machine. See [this link for details.](https://medium.com/@Charles_Stover/fixing-volumes-in-docker-toolbox-4ad5ace0e572) I had the same issue on Windows 10 Home edition, where running `docker run --rm -v //c/:/data ls /data/` was not displaying the content of my C drive. Hope helps.

**Comment by alanamircruz** [comment] 2019-03-20 16:37
I tried several things to try to make run this stuff on my Windows 10 Laptop. All configurations are set (I am truly sure I did them all), so anyone can please have a clue on this by this open thread on Windows + docker + Hyper-V in 2019 ?

I do see my shared directories, but no heck sign of my files there...
´c:\test>docker run --rm -v //c/:/data alpine ls -ltRr /data/´
´/data/:´
´total 0´
´drwxr-xr-x    2 root     root            40 Mar 20 17:16 Users´
´drwxr-xr-x    2 root     root            40 Mar 20 17:30 test´
´/data/Users:´
´**total 0**´
´/data/test:´
´**total 0**´

**Comment by ihopit** [comment] 2019-04-16 11:30
I had a few issues with docker on my windows machine:

- since windows switched from password  to pin on my computer - the shared drives still showed to be ok under docker-settings/shared drives, but actually were not working correctly any more. They had to be mounted again

- firewalls (windows & in my case Kaspersky) blocked

- on the drive, you want to share, the privileges have to be set correctly

**Comment by SCWTechJB** [comment] 2019-04-22 17:55
> For those using docker toolbox, what worked for me is adding shared drive in the virtual box machine. See [this link for details.](https://medium.com/@Charles_Stover/fixing-volumes-in-docker-toolbox-4ad5ace0e572) I had the same issue on Windows 10 Home edition, where running `docker run --rm -v //c/:/data ls /data/` was not displaying the content of my C drive. Hope helps.

THANK YOU. I can see my files after mounting both ways now with Docker ToolBox

**Comment by dodoslav** [comment] 2019-06-13 19:58
What helped me was reseting credentionals in Docker Desktop->Settings->Shared Drives.

**Comment by devhandle** [comment] 2019-07-10 12:51
@dodoslav's solution worked for me.

**Comment by smarwei** [comment] 2019-09-10 08:37
@dodoslav worked for me as well.

**Comment by Nassh04** [comment] 2019-09-18 03:49
If you are still facing the issue, try the same set of commands to mount the drives using Powershell CLI and it'll prompt you to allow shared drives post which you'll be able to mount drives to containers with ease.

**Comment by jojurajan** [comment] 2019-11-06 07:48
Adding on to the thread. I was facing an intermittent issue with the mounted directory. The files were shared to Docker and it was working fine until the docker service got stuck for some reason. After that, if I ran the container command again, it showed an empty directory. Restarting docker did not work, but restarting the system did the trick.

Docker version: Docker version 19.03.4, build 9013bf5
OS: Windows 10

**Comment by kingdavid72** [comment] 2019-12-17 15:50
> Encountered this issue today, May 2017
> docker for windows version `17.03.1-ce-win12 (12058)`
> Resolved it by unsharing C drive then resharing.
> Hopefully that helps someone

It worked to me by unclick (Unshare) apply and click (share again) and apply worked.
I never expected to work but simple enough works.. I should have tried this method first.

**Comment by VanVan** [comment] 2020-02-26 00:51
I can confirm that unshare and share again did the click. However, it requires two successive docker restarts, which takes a long time.
On my side, unshare and share again from Docker Desktop settings prevents docker from restarting and makes it crash, a restart of the machine is necessary.
I guess this bug will never be fixed, until we migrate to WSL2.

**Comment by VanVan** [comment] 2020-02-26 00:52
On my side, unshare and share again from Docker Desktop settings prevents docker from restarting and makes it crash, a restart of the machine is necessary.
I guess this bug will never be fixed, until we migrate to WSL2.

**Comment by tarunjuneja** [comment] 2020-03-30 14:42
**Don't rush - Read it carefully**

So guys i spent whole day, whole night fixing this problem and finally i got the problem

Here i am mapping my webapp folder to node on folder docker
docker run -v d://Work/sample/nxt/examples/webapp:/node -u 0 --rm --name=dockername -it -p 8080:8080 somepath/dockername

See d:// here, if you have a drive and so colon in it it must be //

Also Make sure don't mount using $PWD on windows somehow it does not map to correct path. Use physical path as i have shown above

I am sure it will make many days of many folks

Happy coding 

Cheers!

**Comment by abbasnikbakht** [comment] 2020-04-17 22:48
> **Don't rush - Read it carefully**
> 
> So guys i spent whole day, whole night fixing this problem and finally i got the problem
> 
> Here i am mapping my webapp folder to node on folder docker
> docker run -v d://Work/sample/nxt/examples/webapp:/node -u 0 --rm --name=dockername -it -p 8080:8080 somepath/dockername
> 
> See d:// here, if you have a drive and so colon in it it must be //
> 
> Also Make sure don't mount using $PWD on windows somehow it does not map to correct path. Use physical path as i have shown above
> 
> I am sure it will make many days of many folks
> 
> Happy coding
> 
> Cheers!

Thanks, this helped me.
