### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by pradeeppaneru2** [docker/for-win#6974] opened 2020-05-31 07:59 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
A2E0EB64-F5AB-452A-AEE9-8869D1292B67/20200531075520

**Comment by pradeeppaneru2** [comment] 2020-05-31 08:00
A2E0EB64-F5AB-452A-AEE9-8869D1292B67/20200531075520

**Comment by stephen-turner** [comment] 2020-06-01 09:04
Closing as dupe of #6975.

**Closed by stephen-turner** 2020-06-01 09:04 UTC
