### ISSUE TITLE
Kubernetes feature doesn't start successfully after enabling in Docker Desktop

### ISSUE THREAD

**Issue by Vyjayanthrobonaut** [docker/for-win#12724] opened 2022-05-15 14:06 UTC
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C51FC60F-E125-4C77-A863-AB4B7D9C46FB/20220515135205

### Actual behavior
After Docker Desktop is installed, enabling Kubernetes feature is going further and stopping kubernetes instances.

### Expected behavior
After Docker Desktop is installed, enabling Kubernetes feature should enable kubernetes cluster.

### Information

  - Windows Version: Windows 11 Pro
  - Docker Desktop Version: Docker Desktop 4.8.1 (78998)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

C:\Users\Vyjayanth>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

C:\Users\Vyjayanth>

**Comment by laurazard** [comment] 2022-05-17 10:50
Hi @afattahi54, thank you for your report!

I believe the errors you are seeing have to do with a regression that was introduced in version 4.8 related to manual proxy override settings.

We are preparing a 4.8.2 release to address those issues here:
- [RC mac Intel build](https://desktop-stage.docker.com/mac/main/amd64/79289/Docker.dmg)
- [RC mac ARM build](https://desktop-stage.docker.com/mac/main/arm64/79289/Docker.dmg) 
- [RC Windows build](https://desktop-stage.docker.com/win/main/amd64/79289/Docker%20Desktop%20Installer.exe) 
 
Would you mind checking them out and seeing if the issue is addressed? Thank you!

**Comment by Vyjayanthrobonaut** [comment] 2022-05-20 13:36
Hi Laurazard,

Thank you for replying. As recently installed Docker Desktop, I don't have any .yaml files yet. Clicking on "Reset Kubernetes Cluster" is insisting that it deletes all stacks and resources.

**Comment by Vyjayanthrobonaut** [comment] 2022-05-20 13:42
Hi,

Thanks for the assistance, looks like resetting the cluster has worked. the entire cluster is up and running now. I didn't have to use CTL apply, as docker-desktop restarted the cluster.

Cheers 

> **_`JZD`_**

**Comment by laurazard** [comment] 2022-05-21 15:24
I'm glad it helped 🎉 . Since there's nothing else, I'll close the issue.

**Closed by laurazard** 2022-05-21 15:24 UTC
