### ISSUE TITLE
k8s system containers visible in WSL2 bash (but not windows powershell)

### ISSUE THREAD

**Issue by jonaskello** [docker/for-win#7002] opened 2020-06-01 19:47 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
### Expected behavior

Doing `docker ps` in WSL2 (Ubuntu-18.04) with the option "Show system containers (advanced)" in the Kubernetes section in settings is off. Expected to not see any k8s system containers.

### Actual behavior

All k8s system containers are visible in the output of `docker ps`.

### Information

 It seems the setting "Show system containers (advanced)" does not affect the behavior in WSL2, it only affects behavior in Windows (powershell/cmd).

  - Windows Version: 10
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Set "Show system containers (advanced)" to off.
  2. Start WSL2 terminal.
  3. Enter `docker ps`.
  4. Fins k8s system containers in output.

**Comment by mat007** [comment] 2020-06-02 05:22
Thanks for the report, closing as a duplicate of #6725

**Closed by mat007** 2020-06-02 05:22 UTC
