### ISSUE TITLE
I have trouble with starting container.

### ISSUE THREAD

**Issue by AhnMo** [docker/for-win#361] opened 2016-12-28 16:13 UTC
I installed docker as shown on the Microsoft homepage(https://docs.microsoft.com/ko-kr/virtualization/windowscontainers/quick_start/quick_start_windows_10).

Then I try to start container, but there is a problem as shown below.

> PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
9f41f09e9678        microsoft/nanoserver   "cmd"               20 minutes ago      Created                                 quizzical_goodall
PS C:\WINDOWS\system32> docker start quizzical_goodall -i
Error response from daemon: container 9f41f09e96782f4ff3b23deb84aade4b8cb874da5d41f61b8d9c685a71d8c00e encountered an error during CreateContainer: failure in a Windows system call: The handle is invalid. (0x6)
PS C:\WINDOWS\system32>

And `docker event` output has nothing special...

> PS C:\WINDOWS\system32> docker events
2016-12-29T01:10:04.331161700+09:00 container attach 9f41f09e96782f4ff3b23deb84aade4b8cb874da5d41f61b8d9c685a71d8c00e (image=microsoft/nanoserver, name=quizzical_goodall)
2016-12-29T01:10:04.709193500+09:00 network connect e4eaa39f1fbe8043361ff93ea0be451f91728b039eb2b92dd0c8a7be3394937d (container=9f41f09e96782f4ff3b23deb84aade4b8cb874da5d41f61b8d9c685a71d8c00e, name=nat, type=nat)
2016-12-29T01:10:05.392166500+09:00 network disconnect e4eaa39f1fbe8043361ff93ea0be451f91728b039eb2b92dd0c8a7be3394937d (container=9f41f09e96782f4ff3b23deb84aade4b8cb874da5d41f61b8d9c685a71d8c00e, name=nat, type=nat)
[NO MORE]

Also here is my `docker info`.

> PS C:\WINDOWS\system32> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.913 GiB
Name: DESKTOP-GAMESHN
ID: RMXO:BH2E:HT6D:YNNK:QJ5Y:GDL7:G7HK:5HDH:UMAX:E4HS:TMKI:ZO5C
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
PS C:\WINDOWS\system32>

What can I do to solve this problem? Any suggestions?

**Comment by friism** [comment] 2016-12-28 16:58
I cannot reproduce this. Can you provide a full repro, eg. how did you create the container in the first place?

**Comment by AhnMo** [comment] 2016-12-28 17:52
Oh! Here it is.

> PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS
   NAMES
9f41f09e9678        microsoft/nanoserver   "cmd"               2 hours ago         Created
   quizzical_goodall
PS C:\WINDOWS\system32> docker run -it microsoft/nanoserver cmd
c:\program files\docker\docker.exe: Error response from daemon: container 73bc6ac7b17b8f5bf6ff72d8c845606d858a52badcc0a6
6d81713ff0a7113263 encountered an error during CreateContainer: failure in a Windows system call: The handle is invalid.
 (0x6).
PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS
   NAMES
73bc6ac7b17b        microsoft/nanoserver   "cmd"               7 seconds ago       Created
   adoring_ritchie
9f41f09e9678        microsoft/nanoserver   "cmd"               2 hours ago         Created
   quizzical_goodall
PS C:\WINDOWS\system32>

And `docker events

> `PS C:\WINDOWS\system32> docker events
2016-12-29T02:50:40.758619200+09:00 container create 73bc6ac7b17b8f5bf6ff72d8c845606d858a52badcc0a66d81713ff0a7113263 (i
mage=microsoft/nanoserver, name=adoring_ritchie)
2016-12-29T02:50:40.759617800+09:00 container attach 73bc6ac7b17b8f5bf6ff72d8c845606d858a52badcc0a66d81713ff0a7113263 (i
mage=microsoft/nanoserver, name=adoring_ritchie)
2016-12-29T02:50:41.244616700+09:00 network connect e4eaa39f1fbe8043361ff93ea0be451f91728b039eb2b92dd0c8a7be3394937d (co
ntainer=73bc6ac7b17b8f5bf6ff72d8c845606d858a52badcc0a66d81713ff0a7113263, name=nat, type=nat)
2016-12-29T02:50:42.575627800+09:00 network disconnect e4eaa39f1fbe8043361ff93ea0be451f91728b039eb2b92dd0c8a7be3394937d
(container=73bc6ac7b17b8f5bf6ff72d8c845606d858a52badcc0a66d81713ff0a7113263, name=nat, type=nat)
[NO MORE]

As you see there is nothing special event log...

**Comment by rneugeba** [comment] 2016-12-28 17:57
@AhnMo this issue tracker is for issues related to the Docker for Windows application. You seem to be using a docker engine version (`1.14.0-dev`) which we don't ship as part of that application. Your issue also seems to be more related to the core docker engine so I'm closing this issue. Could you instead open an issue on https://github.com/docker/docker/issues with the details?
Thanks

**Closed by rneugeba** 2016-12-28 17:57 UTC
Labels: area/wincon, status/0-more-info-needed

**Comment by partialinfinity** [comment] 2018-02-13 16:46
This happens to me on occasion. Restarting WMI Service (or rebooting the host) fixes it for me.

**Comment by stalker314314** [comment] 2018-09-11 11:56
FYI: restarting host helps me too. Killing WmiPrvSE.exe is not helping.
