### ISSUE TITLE
Docker startup failure Windows 10 Pro build 1809

### ISSUE THREAD

**Issue by Stanelis** [docker/for-win#3532] opened 2019-03-09 10:19 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 39CDEEAB-0443-40F2-AB15-06CDFC94DB39/20190309120158

### Expected behavior
Docker should start normaly.
### Actual behavior
On docker startup I am getting error:

Stable version error:
> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
> at New-Switch, <No file>: line 121
> at <ScriptBlock>, <No file>: line 411
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
>    at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Edge version error:
> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
> at New-Switch, <No file>: line 111
> at <ScriptBlock>, <No file>: line 409
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
>    at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0()
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()

I am not sure if this is dockers fault or Windows 10 problem. But I can't start docker and after googling I tried to create new virtual switches in hyper-v with no success. 
For me this started when I tried to change docker network settings, changing IP and DNS.

### Information

  - Windows Version: Windows 10 Pro build 1809
  - Docker for Windows Version: stable - v2.0.0.3; edge - v2.0.3.0

**Comment by rbairwell** [comment] 2019-03-09 11:09
Same issue here.
Diagnostics ID: 5F151709-BF99-491A-BE3A-6C11512ECADE/20190309110251
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

Docker Desktop Community v 2.0.0.3 (31259) stable build 8858db3
English 18.09.2
Notary 0.6.1
Compose 1.23.2
Credential helpers 0.6.0
Machine 0.16.1
Kubernetes 1.10.11
Host: Windows 10 Pro 1809 (OS Build 17763.253).

**Comment by Stanelis** [comment] 2019-03-10 15:42
**Update on the problem:** 
After windows 10 full restore, all data deleted from C driver, docker is up and running. Starts all good and works as expected. It's unfortunate that now, only solution, to get it working again is to reset windows.

**Comment by mikeparker** [comment] 2019-05-30 13:56
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 13:56 UTC
