### ISSUE TITLE
Win10 : virtualization enabled but Docker does not see it - will not load

### ISSUE THREAD

**Issue by Ltek** [docker/for-win#412] opened 2017-01-23 02:08 UTC
### Expected behavior
Docker would start

### Actual behavior
Getting this error on Docker startup...
"Hardware assisted virtualization and data execution protection must be enabled in the BIOS"

### Information

 - Diagnostic ID from "Diagnose & Feedback" in the menu: Docker will
 not run, dont see a way to do this
- log.txt attached
 - host distribution and version : Win 10, latest version of Docker

My system is a Dell 7040 - latest BIOS installed and all Virtualization settings are ON.

Intel I5-6500T specs, supports these:
Intel® Virtualization Technology (VT-x)
Intel® Virtualization Technology for Directed I/O (VT-d)
Intel® VT-x with Extended Page Tables (EPT)
Trusted Execution Technology
Execute Disable Bit

I confirmed with OS "sees" this since under Virtualization status is "Enabled" in Task Manager -> Performance -> CPU tab. 

### Steps to reproduce the behavior

 start docker

**Comment by friism** [comment] 2017-01-23 02:14
Can you create a Hyper-V manually? (you can create any old linux or windows VM to test)

**Comment by Ltek** [comment] 2017-01-23 02:26
I don't know, I don't use Hyper-V for anything else. Hyper-V starts and there are no Event Log errors (I read the Microsoft Hyper-V troubleshooting guide)

here's all the specs from systeminfo command:


Host Name:                 OFFICE
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Aaron
Original Install Date:     10/21/2016, 12:06:27 PM
System Boot Time:          1/22/2017, 12:28:13 PM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 7040
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2396 Mhz
BIOS Version:              Dell Inc. 1.5.7, 12/21/2016
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     8,077 MB
Available Physical Memory: 3,307 MB
Virtual Memory: Max Size:  8,077 MB
Virtual Memory: Available: 3,136 MB
Virtual Memory: In Use:    4,941 MB
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB3176935
                           [02]: KB3176937
                           [03]: KB3199209
                           [04]: KB3199986
                           [05]: KB3214628
                           [06]: KB3213986
Network Card(s):           5 NIC(s) Installed.
                           [01]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (External VM Switch)
                                 Status:          Media disconnected
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (DockerNAT)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.0.75.1
                                 [02]: fe80::3110:c649:aa91:fda9
                           [03]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.2.1
                                 IP address(es)
                                 [01]: 192.168.2.145
                                 [02]: fe80::4cab:b972:6043:2a35
                           [04]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by rneugeba** [comment] 2017-01-23 11:11
Could you supply a diagnostics ID? We collect a bunch of additional data which may help us to debug.

Also, in Hyper-V Manager, if you just create an empty VM. `New -> Virtual Machine` and then just click through the defaults. Once the VM is created, select it, click on `Connect` and power it up. If hyper-v is working you should see something like this:

![screen shot 2017-01-23 at 11 09 51](https://cloud.githubusercontent.com/assets/3338098/22201720/bd55b26e-e15c-11e6-9b96-cb9d64180f14.png)

**Comment by Ltek** [comment] 2017-01-23 23:44
If I knew how to create a diagnostics ID I would… how can it be done when Docker will not run/load?

 

I’m going to uninstall and reinstall both Hyper-V and docker – let you know how that goes

**Comment by rneugeba** [comment] 2017-02-04 11:59
How did the re-install go?

**Comment by Ltek** [comment] 2017-02-04 19:50
reinstall didnt help a bit ... there is a serious problem with Docker on Win10. I did web searches and there are MANY reports of the exact same problem with no real fix... a few people have only gotten it to work out of dumb luck.

Too bad the dev team is ignoring this problem.

**Comment by rneugeba** [comment] 2017-02-04 21:53
@Ltek thanks for getting back. We are not ignore the problems, but the main issues are pretty much out of our control. We simply utilise some Microsoft technologies like Hyper-V. Unfortunately, on some systems Hyper-V is not working as expected and we try our best with the resource available to handle those cases.

Have you tried manually creating a Hyper-V VM as I suggested above? If that is not working then the issue is not specific to Docker for Windows.

Thanks

**Comment by Ltek** [comment] 2017-02-07 21:37
Yes, I can create, and run, other Hyper-V VMs just fine.

**Comment by ColumbiaBlooms** [comment] 2017-03-16 15:12
I'm having the same problem and have gone through the same procedures with no success. Does anyone have a solution to this? Is there some way I can help you get more documentation.

**Comment by mehmetgndzks** [comment] 2017-03-21 15:36
HI guys. 

I had the the same problem (I guess). The solution worked for me was to disable the Windows-feature "Hyper-V ( Windows-features --> Hyper-V then uncheck Hyper-V-Platform and Hyper-V-Administration-tool)  Windows will then restart and when windows starts again, docker will say that it needs to reactivate this options. just say ok and windows will restart again. Docker should work now. 
Please let me know if it worked

Best regards, 

Mehmet G.

**Comment by saschb2b** [comment] 2017-03-25 12:26
@mehmetgndzks Thanks! That fixed it for me.

**Comment by rlammersmagenta** [comment] 2017-03-30 07:45
@mehmetgndzks Thank! For me too.

**Comment by wizston** [comment] 2017-06-01 10:23
@mehmetgndzks Thanks!

**Comment by wildan2711** [comment] 2017-06-06 14:20
@mehmetgndzks love you

**Comment by Gemorroj** [comment] 2017-06-26 07:43
I have `intel I5-6500` too and windows 10 x64.
same problem.

https://gist.github.com/humbertodias/e44b9413f22e3990118306f189cbbf45
I helped point `b` (start powershell and execute `bcdedit /set hypervisorlaunchtype auto`)

**Comment by zhaoyao91** [comment] 2017-07-03 16:53
@mehmetgndzks thank god, you saved my life!

**Comment by PhillipMwaniki** [comment] 2017-07-25 11:55
This worked for me though both virtualbox and android emulators are now disabled. Thanks for the fix.

**Comment by Matty666** [comment] 2017-08-22 20:51
I'll add a me too... nothing in this thread has fixed it for me. I have hyper-v enabled, and can create virtual machines, but docker for windows refuses to think that hyper-v is enabled. Going back to legacy docker-machine...

**Comment by saschb2b** [comment] 2017-08-22 21:23
@Matty666 you should disable it as @mehmetgndzks mentioned

> The solution worked for me was to disable the Windows-feature "Hyper-V ( Windows-features --> Hyper-V then uncheck Hyper-V-Platform and Hyper-V-Administration-tool) Windows will then restart and when windows starts again, docker will say that it needs to reactivate this options. just say ok and windows will restart again. Docker should work now.

**Comment by Matty666** [comment] 2017-08-22 22:45
@saschb2b I'll give it another try tonight, but I did try all the things in this issue to try and fix it, including disabling hyper-v and letting docker-for-win try and enable it and that still failed.

**Comment by Matty666** [comment] 2017-08-25 23:28
@saschb2b it's definitely not working for me... disabled hyper-v by unchecking those two features, restarted. DFW runs and says its not enabled, but fails to enable it. Tried running as admin and it's the same thing

**Comment by LEEVE** [comment] 2017-10-12 18:20
I'm with you Matty666 none has worked for me either and I've spent 5 hours on this. I'll ditch DIVIO  and move on with my life

**Comment by H35am** [comment] 2017-10-14 13:00
Same here, spent lots of time, tried everything mentioned here, but nothing works.

**Comment by H35am** [comment] 2017-10-14 13:25
Same here, spent lots of time, tried everything mentioned here, but nothing works.

**Comment by H35am** [comment] 2017-10-14 13:58
Same here, spent lots of time, tried everything mentioned here, but nothing works, but this worked for me:
Enable-WindowsOptionalFeature –Online -FeatureName Microsoft-Hyper-V –All -NoRestart

**Comment by aswanevelder** [comment] 2017-10-18 14:06
@mehmetgndzks Thanks that worked. This solution should be added to the article that appears as a help when Docker can't start https://docs.docker.com/docker-for-windows/troubleshoot/#hyper-v

**Comment by aswanevelder** [comment] 2017-10-18 14:09
@Matty666 uninstall Hyper-V from Windows Features, restart and let Docker start, it will ask to enabled Hyper-V, Ok, restart, working.

**Comment by H35am** [comment] 2017-10-18 14:22
@aswanevelder, Did this for several times but it didn't work!

**Comment by xmnboy** [comment] 2017-10-27 21:04
A colleague of mine and I were having the same problem. We:

1. confirmed that the processor supports all three VT-x features in [ark.intel.com](https://ark.intel.com/) 
2. confirmed that all VT-x features were enabled in the BIOS
3. disabled VBS (Virtualization Based Security)
4. disabled the entire Hyper-V platform in **Windows Features**

_You might first try doing just steps 1, 2 and 4 above (skip step 3)._ 

In step 4 it's easiest to disable Hyper-V entirely, because Docker for Windows will turn it all back on for you (assuming that is the source of the problem). To disable Hyper-V:

* copy this path `Control Panel\Programs\Programs and Features` into a File Explorer address bar 
* click **Turn Windows feature on or off** on the left side of the Control Panel
* clear the checkmark next to **Hyper-V** in the features
* restart your PC
* start Docker for Windows (or reinstall if necessary)

If that doesn't work, then VBS might be interfering and needs to be disabled. Try the following to disable Virtualization Based Security (VBS):

* open the **Local Group Policy Editor** (`gpedit.msc`)
* goto `Computer Configuration\Administrative Templates\System\Device Guard`
* disable VBS ([see this image](https://www.tenforums.com/attachments/tutorials/108894d1485973713-enable-disable-credential-guard-windows-10-a-device_guard_gpedit-1.png)) ([more details here](https://www.tenforums.com/tutorials/68935-enable-disable-credential-guard-windows-10-a.html))

If that doesn't work, then try [this VMware KB article](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2146361) which is designed to allow one to use an alternate hypervisor. It worked for us on two different machines.

**Comment by quyle1703** [comment] 2017-11-20 12:24
Thank you so much @mehmetgndzks It worked for me :)

**Comment by ayZagen** [comment] 2017-11-24 21:39
@mehmetgndzks you saved us thank you very much

**Comment by jasonbivins** [comment] 2017-12-06 17:15
Closing - this is a Hyper-V issue
See this article for resolution: https://success.docker.com/article/Manually_enable_Docker_for_Windows_prerequisites

**Closed by jasonbivins** 2017-12-06 17:15 UTC
Labels: area/hyper-v, status/0-triage

**Comment by xhchrn** [comment] 2018-06-04 20:04
It seems a problem that the core isolation in Windows is enabled. See here:
https://stackoverflow.com/a/50403200/8585276

**Comment by alexxgathp** [comment] 2019-03-23 16:14
My solution included a few more steps, but I have a Gigabyte motherboard and Ryzen 5 processor.

- I did all the uninstall steps and turning off as above including Windows Hypervisor (though probably unrelated), turned off anti-virus just in case, 

- then I re-flashed the BIOS, 

- Verified SVM was off, rebooted, then turned it back on. 

- Then, turned the features back on. Re-installed Docker. Working now.

I believe when I upgraded the BIOS last, that screwed up everything (docker was already installed and working), because flashing the BIOS made it go back to default settings with SVM off.

**Comment by SCBbestof** [comment] 2019-05-29 17:29
> I have `intel I5-6500` too and windows 10 x64.
> same problem.
> 
> https://gist.github.com/humbertodias/e44b9413f22e3990118306f189cbbf45
> I helped point `b` (start powershell and execute `bcdedit /set hypervisorlaunchtype auto`)

This worked for me. Kinda' annoying that it get's bugged like this though 😞

**Comment by akoolshrestha** [comment] 2019-08-14 09:05
> HI guys.
> 
> I had the the same problem (I guess). The solution worked for me was to disable the Windows-feature "Hyper-V ( Windows-features --> Hyper-V then uncheck Hyper-V-Platform and Hyper-V-Administration-tool) Windows will then restart and when windows starts again, docker will say that it needs to reactivate this options. just say ok and windows will restart again. Docker should work now.
> Please let me know if it worked
> 
> Best regards,
> 
> Mehmet G.

This worked for me but, I had to add another step as well.
i.e. re-installation of docker if it doesn't enable hyper-v by itself.

**Comment by tag** [comment] 2019-09-19 20:57
> I have `intel I5-6500` too and windows 10 x64.
> same problem.
> 
> https://gist.github.com/humbertodias/e44b9413f22e3990118306f189cbbf45
> I helped point `b` (start powershell and execute `bcdedit /set hypervisorlaunchtype auto`)

Super helpful, thanks.

As one who had to help numerous students with their Docker installations this semester, it would be hugely helpful if the Docker error messages (and documentation) were more specific with regard to not starting. For example, in the case of the current student I'm helping, every indicator in Windows (as guided but the Docker docs) was showing Hyper-V was enabled, but Hyper-V was prevented by `bcdedit` settings (which is not part of Docker's documentation). A more specific error message that pointed directly to this cause would have been very welcome.

**Comment by gbattra** [comment] 2020-02-09 01:58
Why is this issue closed? This is still very much an issue YEARS later. What is going on Docker team? Are you just going to continue to ignore this?
