### ISSUE TITLE
Docker Disk Image Location couldn't be moved

### ISSUE THREAD

**Issue by harvic3** [docker/for-win#14142] opened 2024-06-17 16:58 UTC
### Description

After my last update to Docker v4.31.1 I lost my local disk data trying to change its location because the strategy changed and now the process could not be executed by wsl migration, now it's through Docker options in Resources menu. 

The problem was that I hadn't my disk docker_data in C, it had in disk E, but after the update this setup was lost, and trying to update the location by the Docker Resources option, docker delete my current docker_data. :'( 

So, I restart it from a old backup and try to change its default location (C) in many ways to my desire E location, and it was imposible, event restarting the original docker disk data from scratch. 

The error showed is the next pic
![image](https://github.com/docker/for-win/assets/16002685/c284c814-e09a-4555-9fb3-8186b08a4583)

To summarize, at this moment for me was imposible move the Docker disk image data to other different location from C directory on Windows 11. 

### Reproduce

// List images
```console
wsl --list 
```
// Try to set your current docker image data to docker - Unregister it
```console
wsl --unregister docker-desktop-data
```
// Try to set your current docker image data to docker - Register the new one
```console
wsl --import-in-place docker-desktop-data "My-Local-Path"
```
The message result is everything is going to be ok, but not, it doesn't work. 

As the typical option does not work, then checking in the Docker configuration I see that this option can be done in a simpler way, but when I do it I get the error of the screenshot provided above.

### Expected behavior

Be able to set/move my current docker-desktop-data to other directory different from C.

### docker version

```bash
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:54 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.31.1 (153621)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.36GiB
 Name: docker-desktop
 ID: b6a36f6f-0276-4f07-9269-8cff86affea3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

Pic provided is the only one.

**Comment by andrea-reale** [comment] 2024-06-18 07:23
Hi @harvic3,

I am sorry for the bad experience. This is a known issue and a development build addressing it is shared in [this thread and comment](https://github.com/docker/for-win/issues/14126#issuecomment-2163504585).

Unless you have manually uninstalled or factory reset Docker Desktop, you'll be able to get back all your data by using the linked build.

--- 

I'll close this issue as a duplicate of https://github.com/docker/for-win/issues/14126

**Closed as completed by andrea-reale** 2024-06-18 07:23 UTC
Labels: status/duplicate, needs-triage, version/4.31.1

**Comment by ngbrown** [comment] 2024-06-20 04:31
@andrea-reale I'm getting the same error message (on Windows 11). The new architecture doesn't allow moving the disk image location to another drive, even if fully empty after a "Reset to factory defaults".

Both this issue and #14126 are closed. Can one of the two be open for the issue of the "Disk image location" selection not working in v4.31.1?

**Comment by andrea-reale** [comment] 2024-06-20 08:04
Hi @ngbrown. We're actively working on a fix: you can follow the progress on this issue: #13384
