### ISSUE TITLE
Hyper-V and Containers features are not enabeld.

### ISSUE THREAD

**Issue by princedeekay** [docker/for-win#2265] opened 2018-07-25 19:40 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment] 2018-07-25 21:35
Closing as a duplicate of https://github.com/docker/for-win/issues/2262.
As a workaround, you can enable "Hyper-V" and "containers" features in "Windows Features" (search for "Turn Windows features on"), that will need a computer restart, then start Docker for Windows

**Closed by gtardif** 2018-07-25 21:35 UTC
