### ISSUE TITLE
DNS resolution issues with AnyConnect VPN with Split-DNS

### ISSUE THREAD

**Issue by l8nite** [docker/for-win#43] opened 2016-08-17 19:59 UTC
### Expected behavior

Expect "google.com" to resolve while connected to VPN

### Actual behavior

"google.com" does not resolve while connected to VPN

### Information

  - Diagnostic ID: D90C5FE2-32AC-486E-AB8E-EF1EF4E0036E/2016-08-17_12-45-07
  - Windows 10 Enterprise 10511 (Build 10586.545)
  - Docker for Windows Beta

### Steps to reproduce the behavior

  1. Connect to AnyConnect VPN with split DNS enabled
  2. Start a docker container (i.e., alpine) and attempt to ping google.com

Conversely, if I am NOT connected to the VPN, I can successfully resolve google.com (however, not any internal network names).

### Additional Notes

It appears that the com.docker.slirp.exe proxy process is intercepting the DNS queries successfully but instead of sending them through the AnyConnect interface, it is attempting to forward the query directly to my corporate network's DNS server (probably the default on the interface), which doesn't allow external domains to be resolved. 

You can see this behavior below, logs were gathered with:
`gc $(gi $env:LocalAppData\Docker\* | sort LastAccessTime -Desc | select -First 1) -Wait`

```
[12:57:52.243][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[c968] 192.168.65.2:40099 -> 192.168.65.1 c968 Query:0 na:c:r:rn 0 <qs:google.com. <A|IN>> <an:> <au:> <ad:>
[12:57:52.244][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[c968] 192.168.65.2:40099 -> 192.168.65.3 c968 Query:0 na:c:r:rn 0 <qs:google.com. <A|IN>> <an:> <au:> <ad:>
[12:57:52.244][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 -> 192.168.65.1 cd50 Query:0 na:c:r:rn 0 <qs:google.com. <AAAA|IN>> <an:> <au:> <ad:>
[12:57:52.244][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 51560 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 A
[12:57:52.245][ApiProxy       ][Info   ] Search for dns server...
[12:57:52.245][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[12:57:52.247][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 52560 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 AAAA
[12:57:52.248][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[c968] Forwarding to 10.0.75.1 (secondary(wrapped))
[12:57:52.249][VpnKit         ][Debug  ] com.docker.slirp.exe: Socket.Datagram.input 192.168.65.2:40099-10.0.75.1:53 (DNS[c968]): creating UDP NAT rule
[12:57:52.249][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 51560 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 A
[12:57:52.250][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[12:57:52.250][ApiProxy       ][Info   ] Handle DNS query ;; opcode: QUERY, status: NOERROR, id: 52560 ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 AAAA
[12:57:52.250][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[c968] Forwarding to 10.0.75.1 (primary(sole))
[12:57:52.252][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[12:57:52.252][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] Forwarding to 10.0.75.1 (primary(sole))
[12:57:52.253][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 -> 192.168.65.3 cd50 Query:0 na:c:r:rn 0 <qs:google.com. <AAAA|IN>> <an:> <au:> <ad:>
[12:57:52.253][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")
[12:57:52.254][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] Forwarding to 10.0.75.1 (secondary(wrapped))
[12:57:54.233][ApiProxy       ][Info   ] Server:  hqdc1.hq.practicefusion.com
[12:57:54.234][ApiProxy       ][Info   ] Address:  10.17.14.11
[12:57:54.234][ApiProxy       ][Info   ]
[12:57:54.235][ApiProxy       ][Info   ]
[12:57:54.236][ApiProxy       ][Info   ] Found dns server 10.17.14.11
[12:57:54.237][ApiProxy       ][Info   ] Forward DNS query on udp to 10.17.14.11:53
[12:57:54.237][ApiProxy       ][Info   ] Forward DNS query on udp to 10.17.14.11:53
[12:57:54.238][ApiProxy       ][Info   ] Forward DNS query on udp to 10.17.14.11:53
[12:57:54.239][ApiProxy       ][Info   ] Forward DNS query on udp to 10.17.14.11:53
[12:57:54.240][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 <- secondary(wrapped) (c968 Response:0 na:c:r:rn 3 <qs:google.com. <A|IN>> <an:> <au:> <ad:>)
[12:57:54.240][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 51560 ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 A
[12:57:54.241][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 <- secondary(wrapped) (cd50 Response:0 na:c:r:rn 3 <qs:google.com. <AAAA|IN>> <an:> <au:> <ad:>)
[12:57:54.242][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 52560 ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 AAAA
[12:57:54.242][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 <- secondary(wrapped) (cd50 Response:0 na:c:r:rn 3 <qs:google.com. <AAAA|IN>> <an:> <au:> <ad:>)
[12:57:54.246][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 52560 ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 AAAA
[12:57:54.247][ApiProxy       ][Info   ] Got response ;; opcode: QUERY, status: NXDOMAIN, id: 51560 ;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0  ;; QUESTION SECTION: ;google.com.        IN
 A
[12:57:54.247][VpnKit         ][Info   ] ICMP Destination Unreachable: Destination port unreachable
[12:57:54.246][VpnKit         ][Debug  ] com.docker.slirp.exe: DNS[cd50] 192.168.65.2:40099 <- secondary(wrapped) (c968 Response:0 na:c:r:rn 3 <qs:google.com. <A|IN>> <an:> <au:> <ad:>)
[12:57:54.248][VpnKit         ][Info   ] ICMP Destination Unreachable: Destination port unreachable
[12:57:57.250][VpnKit         ][Debug  ] com.docker.slirp.exe: ARP responding to: who-has 192.168.65.1?
[12:57:57.251][VpnKit         ][Debug  ] com.docker.slirp.exe: ARP responding to: who-has 192.168.65.3?
```

**Comment by rneugeba** [comment] 2016-08-18 10:19
@l8nite Thanks for your detailed report and analysis. You are correct, we intercept DNS query and currently only forward it to one (the first) DNS server. We are working on fixing this

**Comment by l8nite** [comment] 2016-08-22 21:25
@rneugeba any ideas on a workaround I can use in the meantime? Is the DNS proxy source around here somewhere? Wondering if I can tweak it for my specific use-case (i.e., pick a different nameserver if the domain being queried isn't my corporate domain).

**Comment by rneugeba** [comment] 2016-09-01 18:19
@l8nite we have a PR for hopefully fixing the DNS issue, so it should hopefully show up in the next Beta

**Comment by dgageot** [comment] 2016-09-08 14:36
@l8nite A new version (Beta25) was released yesterday with fixes to the network/dns stack. Could you please give it a try and tell us if you see an improvement? Thanks a lot!

**Comment by l8nite** [comment] 2016-09-09 17:20
@dgageot unfortunately it doesn't appear to have been resolved. It's actually worse now, as when I'm connected to the VPN I can no longer resolve internal OR external names.

**Comment by dgageot** [comment] 2016-09-14 06:59
ping @ebriney Coud you please try to debug @l8nite's DNS configuration and understand why we don't pick the right one? Thanks

**Comment by ebriney** [comment] 2016-09-15 08:37
@l8nite Can you give me a new diagnostic id?

Because using your user id D90C5FE2-32AC-486E-AB8E-EF1EF4E0036E, there is only the previous bug report info.

Thanks for the help.

**Comment by l8nite** [comment] 2016-09-15 23:29
@ebriney I will reproduce and provide a new diagnostic ID this weekend. I don't have access to my windows machine at the moment.

**Comment by rneugeba** [comment] 2016-09-28 22:12
@l8nite is there any update? We are keen to improve the experience for VPN users but if the update helped we would like to close this issue
thanks

**Comment by dgageot** [comment] 2016-10-10 15:52
I'm going to close the issue since nobody complained nor responded lately. Feel free to reopen in case the issue is still there of course!

**Closed by dgageot** 2016-10-10 15:52 UTC
Labels: area/network, kind/bug, will-be-closed

**Comment by CloningMishap** [comment] 2016-10-10 16:50
@dgageot Thanks! I just tested it out and it appears to be fixed. I can now ping google.com from inside the container while connected to my Split-VPN through AnyConnect.

**Comment by l8nite** [comment] 2016-10-13 17:17
@dgageot This is still failing here on latest beta version. I am connected to VPN in both of the below examples.

When running ping outside of a docker container, everything works as expected:

```
# Outside of a docker container
$ ping google.com
Pinging google.com [216.58.193.78] with 32 bytes of data:

$ ping stash.hq.practicefusion.com
Pinging uw2prdstash01.hq.practicefusion.com [10.15.208.11] with 32 bytes of data:

$ ping pf-int-cake1.hq.practicefusion.com
Pinging pf-int-cake1.hq.practicefusion.com [10.12.242.151] with 32 bytes of data:
```

Inside the container this time, I get a DNS resolution (but to IPv6) that I can't route to. And internal DNS names are not resolved

```
$ docker run --rm -it alpine sh
/ # ping google.com
PING google.com (2607:f8b0:4005:808::200e): 56 data bytes
ping: sendto: Network unreachable

/ # ping stash.hq.practicefusion.com
ping: bad address 'stash.hq.practicefusion.com'

/ # ping pf-int-cake1.hq.practicefusion.com
ping: bad address 'pf-int-cake1.hq.practicefusion.com'
```

New Diagnostic ID here: 65D06FF4-BA21-452C-9BC6-466F91C0C53A/2016-10-13_10-16-17
