### ISSUE TITLE
Unable to build images: "Unknown instruction: CURL"

### ISSUE THREAD

**Issue by oliversalzburg** [docker/for-win#288] opened 2016-12-05 11:32 UTC
### Expected behavior
Previously, I was able to build images with the `docker build` command.

### Actual behavior
When I run `docker build`, it gives me the error `Error response from daemon: Unknown instruction: CURL`.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu:  E068E1FF-4B34-4943-A387-A74951CF6150/2016-12-05_12-31-16

**Comment by justincormack** [comment] 2016-12-05 12:12
There were some Docker file parsing changes in 1.13, which are probably
going to be reverted soon.

However it does mean your Docker file is fairly ambiguous, either with
comments or spaces after \ continuation or similar.


On 5 Dec 2016 11:32 a.m., "Oliver Salzburg" <notifications@github.com>
wrote:

Expected behavior

Previously, I was able to build images with the docker build command.
Actual behavior

When I run docker build, it gives me the error Error response from daemon:
Unknown instruction: CURL.
Information

   - Diagnostic ID from "Diagnose & Feedback" in the menu:
   E068E1FF-4B34-4943-A387-A74951CF6150/2016-12-05_12-31-16

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/for-win/issues/288>, or mute the thread

**Comment by oliversalzburg** [comment] 2016-12-05 12:20
> either with comments or spaces after \ continuation or similar.

Yeah, we have *tons* of that going on. Should that be considered a problem or should we just hang tight until the fix rolls out?

**Comment by rneugeba** [comment] 2016-12-30 11:58
@justincormack do you know if the relevant changes in 1.13 have been reverted? Is there an issue/PR for it?
@oliversalzburg have you tried 1.13.0-rc4 which ships with Bets34?

**Comment by justincormack** [comment] 2016-12-30 12:12
I think they were all reverted by 1.13.0-rc4.

**Comment by oliversalzburg** [comment] 2016-12-30 19:43
@rneugeba I'm on 1.12.5 for now

**Comment by rneugeba** [comment] 2016-12-30 21:26
@oliversalzburg thanks for getting back. I'm closing this issue for now assuming it is fixed as per @justincormack comment. Please re-open if the issue is still present the next time you try 1.13.
thanks

**Closed by rneugeba** 2016-12-30 21:26 UTC
Labels: status/0-more-info-needed, status/1-acknowledged
