### ISSUE TITLE
 Interactive run error - 'The parameter is incorrect'

### ISSUE THREAD

**Issue by bobbyAtSperry** [docker/for-win#8] opened 2016-07-29 15:33 UTC
I've just started with Docker for Windows 10. Went through some getting started examples yesterday fine. Today, after updating to the latest stable release, I'm getting "The parameter is incorrect" coming up when I try to run containers. They run OK and can be seen with the ps command but they are not interactive.

Here is a simple example:

```
PS > docker run -it ubuntu bash
The parameter is incorrect.

PS > docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6541c014737d        ubuntu              "bash"              11 seconds ago      Up 10 seconds                           adoring_hamilton

PS >
```
I only get the error when the -i flag is present.

My version info is as follows:
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

My diagnostic id is:
C8BAF08A-4F77-40FD-A92B-420733400683/2016-07-29_16-27-40

**Comment by rneugeba** [comment] 2016-07-29 16:08
which shell are you using? It works for me:
```
PS C:\Users\docker> docker run -it ubuntu bash
root@905cd1e711a7:/# exit
PS C:\Users\docker>
```

**Comment by bobbyAtSperry** [comment] 2016-07-29 16:12
Windows powershell. I might try a) rebooting, b) the command line prompt. I'll let you know how I get on.

I've already tried resetting docker to factory settings.

**Comment by rneugeba** [comment] 2016-07-29 16:15
Can you make sure you are picking up `docker.exe` from `C:\Program Files\Docker\Docker\resources\bin\docker.exe`. The installer should add this to you path

**Comment by bobbyAtSperry** [comment] 2016-07-29 16:21
I think it must be as that is the only docker.exe that shows up when I search the c drive.

**Comment by bobbyAtSperry** [comment] 2016-07-29 16:29
OK, i've just tried it from Command Prompt and it works fine. Still doesn't work from Windows PowerShell though. So it appears that I have a workaround. Strange that it doesn't work in Powershell. I could have sworn that's what I was using yesterday when it worked OK but I may be mistaken.

Thanks for the help @rneugeba

**Comment by rneugeba** [comment] 2016-07-30 12:20
Could it be something in your powershell profile?

Could you try: `powershell -noprofile` and then on the new command line:
```
& 'C:\Program Files\Docker\Docker\resources\bin\docker.exe' run -it ubuntu bash
```

**Comment by rneugeba** [comment] 2016-08-01 15:39
Closing this issue for now, as it seems specific to your setup. I can't reproduce it with a variety of Windows builds. Please feel free to re-open and/or provide additional information.

Thanks

**Closed by rneugeba** 2016-08-01 15:39 UTC
Labels: kind/bug

**Comment by bobbyAtSperry** [comment] 2016-08-01 16:06
Thanks @rneugeba 

I tried your suggestion above and it all worked. I then tried it opening as usual and it also worked!?

Only thing I can think is that the machine has been rebooted (though I thought I'd already tried that?). All working now anyway. If it happens again I'll try 
- rebooting
- command prompt workaround
- -noprofile workaround.

Thanks again.

**Comment by vidhutsingh** [comment] 2019-04-04 10:40
On Windows 2016 , i am facing the same issue . 
I tried all the workaround suggested in the post and still this error comes . 
1. Rebooted the system 
2. Used command prmopt 
3. powershell -noprofile. 


C:\>dir
 Volume in drive C has no label.
 Volume Serial Number is 6CB0-880C
PS C:\Users\Administrator> docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        1ac774dfdd
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       1ac774dfdd
  Built:            02/10/2019 04:13:25
  OS/Arch:          windows/amd64
  Experimental:     false
PS C:\Users\Administrator>


C:\Users\Administrator>docker run -ti --rm -v vol2:c:\vol2 microsoft/nanoserver cmd

Directory of C:\

11/20/2016  04:32 AM             1,894 License.txt
07/16/2016  05:20 AM    <DIR>          Program Files
07/16/2016  05:09 AM    <DIR>          Program Files (x86)
04/04/2019  03:33 AM    <DIR>          Users
04/04/2019  03:33 AM    <SYMLINKD>     vol2 [\\?\ContainerMappedDirectories\01D8FACA-4E53-4348-9441-1C70C2E8F6EC]
04/04/2019  03:33 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,243,265,024 bytes free

C:\>cd vol2
The parameter is incorrect.


Appreciate any help on this , thanks . 
Vidhut
