### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by swetharaju14** [docker/for-win#13171] opened 2023-01-17 07:21 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by swetharaju14** [comment] 2023-01-17 07:21
docker still shows 'starting'

**Comment by NortaBirdo** [comment] 2023-01-17 10:55
The same issues for me. I've tried restarts, reinstalls, trraubleshooting purge, wsl --unregister, delete the appdata Docker folder. Nothing changed.

**Comment by gabrewer** [comment] 2023-01-17 19:54
I have this same issue.  I was able to roll back to 4.15.0 after deleting the uninstall registry key and shutting down wsl.  Tried to do the update again and still stuck on starting.

**Comment by leonhui** [comment] 2023-01-18 17:27
I have the same issue.   It won't start when set to Linux containers.

I'm on Windows 10.   I've "cleaned" and "reset" my WSL2.  It seems that with 4.16.0/1 it doesn't create the docker-desktop* distros for WSL2, whereas with 4.15.0 it does.

**Comment by mat007** [comment] 2023-01-19 08:03
Closing this issue as a duplicate of #13165.
We have identified the root cause, and will be releasing a Docker Desktop 4.6.2 shortly (hopefully today).

**Closed by mat007** 2023-01-19 08:03 UTC
