### ISSUE TITLE
Docker for Windows - high CPU usage when service is stopped

### ISSUE THREAD

**Issue by dermeister0** [docker/for-win#430] opened 2017-01-25 10:24 UTC
### Expected behavior

Docker service is stopped.

Docker logo in tray does not consume much resources. The Settings dialog shows 'Docker is stopped' message.

### Actual behavior

Docker service is stopped.

    PS C:\Users\anton> Get-Service com.docker.service

    Status   Name               DisplayName
    ------   ----               -----------
    Stopped  com.docker.service Docker for Windows Service

All Docker interface windows are closed.

**Docker for Windows.exe** consumes ~30% CPU (Intel Core i5 6400).

![2017-01-25_1714](https://cloud.githubusercontent.com/assets/4054844/22286706/ad4de662-e322-11e6-967b-5a97d699932f.png)

--

The Settings dialog shows 'Docker is running' message.

When I start the Docker service again, **Docker for Windows.exe** consumes 0% CPU.

### Information

  - Diagnostic ID: F0A02330-1871-4BFD-83F8-86402B74876B/2017-01-25_17-07-40
  - OS: Windows 10 Pro x64

### Steps to reproduce the behavior

  1. Stop Docker service.
  2. Check CPU usage of **Docker for Windows.exe** process.

**Comment by rneugeba** [comment] 2017-01-29 11:23
@dermeister0 thanks for the report. I can reproduce it.

The service is actually required to run when the application is running. And simply restarting the service does makes the CPU load go away, but then the app doesn't work. So basically you shouldn't really stop the service without quitting the application.

Why were you stopping the service?

**Comment by dermeister0** [comment] 2017-02-01 10:33
I decided to move Docker directory to another drive. So I stopped the Docker service and modified the daemon.json file:

    {  "graph": "D:\\Docker" }

Then I moved content from C:\ProgramData\docker directory to D:\Docker, except *config* folder.

Is it correct way?

**Comment by rneugeba** [comment] 2017-02-01 10:45
The UI has a settings menu, which should allow you to edit the daemon.json file both for windows and linux containers. Once you apply, it should restart the daemon.

**Comment by dermeister0** [comment] 2017-02-01 10:46
Yes, but I need to move the content (images and volumes). I don't want to download all images again.

**Comment by rneugeba** [comment] 2017-02-01 10:52
Understood (they are not small). Maybe stop docker for windows, copy the content, start docker for window, edit the config file, and then remove the old content.

We have an internal issue tracking adding a UI element to change the windows container storage location. I've tagged this issue there.

**Comment by rneugeba** [comment] 2017-02-14 13:34
I've also filed an internal issue regarding the UI consuming 100% CPU. While an un-usual case  I think we should better just quit the application if that happens. Thanks for reporting

**Comment by dgageot** [comment] 2017-02-22 18:34
@dermeister0 We just release version `17.03.0-rc1` of Docker for Windows. Please give it a try and tell us if it's better now.

**Comment by rneugeba** [comment] 2017-02-27 01:34
Closing as we released the fix in Beta. Please re-open if it is not fixed.
thanks
for reporting

**Closed by rneugeba** 2017-02-27 01:34 UTC
Labels: area/gui, status/1-acknowledged, status/3-fixed

**Comment by dermeister0** [comment] 2017-03-15 14:04
It's fixed. Thanks.

**Comment by Salfai77210** [comment] 2017-12-05 16:32
Still not in the Stable version. it's fixed in the Edge version thought.

But i guess it's not the same issue because the main culprit now is an excessive call to python scripts.
