### ISSUE TITLE
Windows 10 Creator's Update Broke Docker for Windows

### ISSUE THREAD

**Issue by vikalyan** [docker/for-win#703] opened 2017-05-04 05:12 UTC
### Expected behavior
On Windows 10, after updating to the Creators Update, Docker can continue to start and run containers as before the update.

### Actual behavior
On Windows 10 Creators Update, container startup fails with the following error code: 0xc0370106

### Information
I am using Azure container registry. The image I am using is a custom image. I am using Windows containers. 

Docker Community Edition Version 17.03.1-ce-win5 (10743)
Channel: stable
b18e2a5

Windows 10 Enterprise Version 1703 (Build number 15063.0)

Output of docker info:-

D:\cdpx\pipeline-engine\output\bin\windows>docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.91 GiB
Name: vikalyan-hp
ID: 6U2M:2IFF:WJVW:GONX:GBCE:T4TY:G55T:YV4I:BTYQ:PUIW:GEAH:3MNH
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-05-03T22:07:54.2492939-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Azure Container registry is "cdpxtest.azurecr.io" and image name is "samples/wsmobile".

### Steps to reproduce the behavior

If I start the container with a simple invocation of docker run such as 

docker run -t -d --name FOO "cdpxtest.azurecr.io/samples/wsmobile"

the container starts up and runs fine. 

However, a more complex invocation that involves passing in volumes to map and resources to provision, fails. Example:-

docker run  -v "d:\mysource":"C:\source":rw      -v "c:\drop":"C:\temppriordrop":ro      -v "c:\credentials":"C:\tempcredentials":ro      -v "c:\scripts":"C:\tempscripts":ro      --memory 3000m      --cpu-count 1    --env-file "c:\credentials\environment.info"          -t -d --name "FOO"      "cdpxtest.azurecr.io/samples/wsmobile"
2d8c5f024893ba24974c26a70950374f2ab1388d2a04b95b57489db8dc71a37c
C:\Program Files\Docker\docker\resources\bin\docker.exe: Error response from daemon: container 2d8c5f024893ba24974c26a70950374f2ab1388d2a04b95b57489db8dc71a37c encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).

This exact same invocation used to work before the Creator's update several times for the past few weeks. 

After attempting to see which particular option was causing the container to not start, it looks like the bind mount of the source folder is causing the container startup to fail. Not sure why this happens. The source folder existed prior to installing the creators update as well.

**Comment by friism** [comment] 2017-05-04 14:31
@vikalyan can you reproduce this on a Windows Server 2016 system?

**Comment by vikalyan** [comment] 2017-05-04 19:30
@friism I don't think so. I will try, but the Windows 10 Creator's Update is Windows 10 specific. I will try out the same workflow on a Windows Server 2016 system after latest updates to see if it is an issue.

**Comment by friism** [comment] 2017-05-04 21:34
I can reproduce this (with a USB key for D-drive). I'm guessing that the d-drive thing is what causes the problem (please confirm).

```
> docker run -v "D:\test:C:\test" microsoft/nanoserver powershell -c dir C:\test
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 38a4c5fb01314070b22a6bb8d543e465dd4d362da51a1851c0494c0bb089ac36 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).
```

Daemon logs:

```
time="2017-05-04T14:29:23.891372300-07:00" level=debug msg="Calling POST /v1.29/containers/create"
time="2017-05-04T14:29:23.925935800-07:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"powershell\",\"-c\",\"dir\",\"C:\\\\test\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[\"D:\\\\test:C:\\\\test\"],\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[114,346],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"microsoft/nanoserver\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
time="2017-05-04T14:29:24.010914400-07:00" level=debug msg="hcsshim::GetLayerMountPath Flavour 1 ID 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:24.016407700-07:00" level=debug msg="Calling proc (1)"
time="2017-05-04T14:29:24.047859800-07:00" level=debug msg="Calling proc (2)"
time="2017-05-04T14:29:24.084730500-07:00" level=debug msg="hcsshim::GetLayerMountPath succeeded flavour=1 id=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6 path=C:\\ProgramData\\Docker\\windowsfilter\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:24.121551000-07:00" level=debug msg="hcsshim::CreateSandboxLayer layerId 60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 parentId C:\\ProgramData\\Docker\\windowsfilter\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:24.127548500-07:00" level=debug msg="hcsshim::NameToGuid Name 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:24.202573800-07:00" level=debug msg="hcsshim::NameToGuid Name 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.242971300-07:00" level=debug msg="hcsshim::CreateSandboxLayer - succeeded layerId=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 parentId=C:\\ProgramData\\Docker\\windowsfilter\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:24.308583900-07:00" level=debug msg="Calling POST /v1.29/containers/60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02/attach?stderr=1&stdout=1&stream=1"
time="2017-05-04T14:29:24.309527300-07:00" level=debug msg="attach: stdout: begin"
time="2017-05-04T14:29:24.309527300-07:00" level=debug msg="attach: stderr: begin"
time="2017-05-04T14:29:24.377329800-07:00" level=debug msg="Calling GET /v1.29/events?filters=%7B%22container%22%3A%7B%2260586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D"
time="2017-05-04T14:29:24.399219800-07:00" level=debug msg="Calling POST /v1.29/containers/60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02/start"
time="2017-05-04T14:29:24.470042100-07:00" level=debug msg="Assigning addresses for endpoint dreamy_sinoussi's interface on network nat"
time="2017-05-04T14:29:24.493428200-07:00" level=debug msg="RequestAddress(172.28.192.0/20, <nil>, map[])"
time="2017-05-04T14:29:24.537234600-07:00" level=debug msg="Network Response : { \"ComputedPolicies\" : [ { \"ACL\" : [ { \"Type\" : \"ACL\" } ] } ], \"CreateProcessingStartTime\" : 131384069645352368, \"DNSServerList\" : \"172.28.192.1,\", \"EnableInternalDNS\" : true, \"EnableLowMetric\" : true, \"GatewayAddress\" : \"172.28.192.1\", \"ID\" : \"f742124c-1ea8-49c4-9a56-23b9de216ca1\", \"IPAddress\" : \"172.28.201.52\", \"MacAddress\" : \"00-15-5D-DA-9A-0A\", \"Name\" : \"New HNS Endpoint\", \"Policies\" : [ { \"Type\" : \"ACL\" } ], \"PrefixLength\" : 20, \"Type\" : \"nat\", \"Version\" : 4294967297, \"VirtualNetwork\" : \"f32e4871-034a-4fad-b617-c6e6157fc494\", \"VirtualNetworkName\" : \"nat\" }"
time="2017-05-04T14:29:24.545246000-07:00" level=debug msg="Assigning addresses for endpoint dreamy_sinoussi's interface on network nat"
time="2017-05-04T14:29:24.628352400-07:00" level=debug msg="Programming external connectivity on endpoint dreamy_sinoussi (55ea0681cf0c891ce2431b0cb4862c5232b37fa70b14a749093c53544fe43c25)"
time="2017-05-04T14:29:24.638889900-07:00" level=debug msg="WindowsGraphDriver Get() id 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6 mountLabel "
time="2017-05-04T14:29:24.691267600-07:00" level=debug msg="hcsshim::ActivateLayer Flavour 1 ID 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.718533200-07:00" level=debug msg="hcsshim::ActivateLayer  - succeeded id=2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6 flavour=1"
time="2017-05-04T14:29:24.744133500-07:00" level=debug msg="hcsshim::PrepareLayer flavour 1 layerId 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.773133100-07:00" level=debug msg="hcsshim::PrepareLayer succeeded flavour=1 layerId=2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.801134600-07:00" level=debug msg="hcsshim::GetLayerMountPath Flavour 1 ID 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.809133800-07:00" level=debug msg="Calling proc (1)"
time="2017-05-04T14:29:24.828636100-07:00" level=debug msg="Calling proc (2)"
time="2017-05-04T14:29:24.891814700-07:00" level=debug msg="hcsshim::GetLayerMountPath succeeded flavour=1 id=2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6 path=C:\\ProgramData\\Docker\\windowsfilter\\2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.918679300-07:00" level=debug msg="WindowsGraphDriver Put() id 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.944675200-07:00" level=debug msg="hcsshim::UnprepareLayer flavour 1 layerId 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:24.976245300-07:00" level=debug msg="hcsshim::UnprepareLayer succeeded flavour 1 layerId=2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:25.003317300-07:00" level=debug msg="hcsshim::DeactivateLayer Flavour 1 ID 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:25.028967900-07:00" level=debug msg="hcsshim::DeactivateLayer succeeded flavour=1 id=2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:25.034953100-07:00" level=debug msg="WindowsGraphDriver Get() id 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6 mountLabel "
time="2017-05-04T14:29:25.058112400-07:00" level=debug msg="hcsshim::ActivateLayer Flavour 1 ID 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.121596900-07:00" level=debug msg="hcsshim::ActivateLayer  - succeeded id=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6 flavour=1"
time="2017-05-04T14:29:25.144484800-07:00" level=debug msg="hcsshim::PrepareLayer flavour 1 layerId 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.169380400-07:00" level=debug msg="hcsshim::NameToGuid Name 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:25.177872200-07:00" level=debug msg="hcsshim::PrepareLayer succeeded flavour=1 layerId=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.192922500-07:00" level=debug msg="hcsshim::GetLayerMountPath Flavour 1 ID 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.217970600-07:00" level=debug msg="Calling proc (1)"
time="2017-05-04T14:29:25.242387800-07:00" level=debug msg="Calling proc (2)"
time="2017-05-04T14:29:25.269687700-07:00" level=debug msg="hcsshim::GetLayerMountPath succeeded flavour=1 id=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6 path=C:\\ProgramData\\Docker\\windowsfilter\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.270188300-07:00" level=debug msg="WindowsGraphDriver Put() id 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.332437000-07:00" level=debug msg="hcsshim::UnprepareLayer flavour 1 layerId 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.393729600-07:00" level=debug msg="hcsshim::UnprepareLayer succeeded flavour 1 layerId=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.417810200-07:00" level=debug msg="hcsshim::DeactivateLayer Flavour 1 ID 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.441154400-07:00" level=debug msg="hcsshim::DeactivateLayer succeeded flavour=1 id=2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.468407700-07:00" level=debug msg="libcontainerd: client.Create() with spec {1.0.0-rc2-dev {windows amd64} {false {114 346} {0 0 [] } [powershell -c dir C:\\test] [] C:\\ [] [] false  } { false} 60586331ba62 [{c:\\test  d:\\test []}] {[] [] []} map[] <nil> <nil> 0xc042025918}"
time="2017-05-04T14:29:25.496404200-07:00" level=debug msg="hcsshim::NameToGuid Name 2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6"
time="2017-05-04T14:29:25.559403100-07:00" level=debug msg="hcsshim::NameToGuid Name 2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6"
time="2017-05-04T14:29:25.589220800-07:00" level=debug msg="HCSShim::CreateContainer id=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 config={\"SystemType\":\"Container\",\"Name\":\"60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02\",\"Owner\":\"docker\",\"IsDummy\":false,\"IgnoreFlushesDuringBoot\":true,\"LayerFolderPath\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02\",\"Layers\":[{\"ID\":\"87ec27a6-f5e9-50c8-9ae1-161c316c0eca\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6\"},{\"ID\":\"d170642d-fe0d-5fca-b04e-a3b1139b984f\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\2182f33c95a826e599846ac8963310870a225a52b733d3ea7ab2caa0148287e6\"}],\"HostName\":\"60586331ba62\",\"MappedDirectories\":[{\"HostPath\":\"d:\\\\test\",\"ContainerPath\":\"c:\\\\test\",\"ReadOnly\":false,\"BandwidthMaximum\":0,\"IOPSMaximum\":0}],\"SandboxPath\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\",\"HvPartition\":true,\"EndpointList\":[\"f742124c-1ea8-49c4-9a56-23b9de216ca1\"],\"HvRuntime\":{\"ImagePath\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\2b31f86e7aea1cee80d77af24b362171cb06985b155bf2ff103f0a2cbfd941f6\\\\UtilityVM\"},\"Servicing\":false,\"AllowUnqualifiedDNSQuery\":true}"
time="2017-05-04T14:29:25.964431000-07:00" level=debug msg="HCSShim::CreateContainer succeeded id=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 handle=72748896"
time="2017-05-04T14:29:25.964930400-07:00" level=debug msg="libcontainerd: Create() id=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02, Calling start()"
time="2017-05-04T14:29:25.973430900-07:00" level=debug msg="libcontainerd: starting container  60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02"
time="2017-05-04T14:29:26.035438600-07:00" level=debug msg="HCSShim::Container::Start id=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02"
time="2017-05-04T14:29:26.551431100-07:00" level=debug msg="Result: {\"Error\":-1070137082,\"ErrorMessage\":\"The compute system exited unexpectedly.\"}"
time="2017-05-04T14:29:26.551431100-07:00" level=error msg="libcontainerd: failed to start container: container 60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)"
time="2017-05-04T14:29:26.575015900-07:00" level=debug msg="HCSShim::Container::Terminate id=60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02"
time="2017-05-04T14:29:26.602108900-07:00" level=debug msg="libcontainerd: cleaned up after failed Start by calling Terminate"
time="2017-05-04T14:29:26.613132300-07:00" level=error msg="Create container failed with error: container 60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)"
time="2017-05-04T14:29:26.652636100-07:00" level=debug msg="attach: stdout: end"
time="2017-05-04T14:29:26.653122400-07:00" level=debug msg="attach: stderr: end"
time="2017-05-04T14:29:26.659618400-07:00" level=debug msg="Revoking external connectivity on endpoint dreamy_sinoussi (55ea0681cf0c891ce2431b0cb4862c5232b37fa70b14a749093c53544fe43c25)"
time="2017-05-04T14:29:26.756461100-07:00" level=debug msg="Releasing addresses for endpoint dreamy_sinoussi's interface on network nat"
time="2017-05-04T14:29:26.756921700-07:00" level=debug msg="ReleaseAddress(172.28.192.0/20, 172.28.201.52)"
time="2017-05-04T14:29:26.816249700-07:00" level=error msg="Handler for POST /v1.29/containers/60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02/start returned error: container 60586331ba626933027644d2c5b4b028cef13e81f3764c300235ccca3c001a02 encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)"
time="2017-05-04T14:29:26.825121600-07:00" level=debug msg="Client context cancelled, stop sending events"
```

I also have dmps in `C:\ProgramData\Microsoft\Windows\WER\ReportArchive\`.

@vikalyan this is most likely a problem that needs to be addressed in moby/moby. Please open an issue there and ping @jhowardmsft. Please link back to this issue.

**Comment by vikalyan** [comment] 2017-05-04 22:36
@friism That's what I thought too. I tried a few more debugging steps:

1. Copied the folder from D: to C:. No luck.
2. Created an empty folder in C: - That worked. A difference between the other folders and the source folder is that the ones in C: that did mount were not empty.
3. I also checked security permissions. Since the host is not a domain joined network, I thought maybe something to do with file ACLs? Not sure.
4. I am using Windows containers; not sure why this would be a moby/moby problem?

**Comment by friism** [comment] 2017-05-04 23:19
> Copied the folder from D: to C:. No luck.
> Created an empty folder in C: - That worked. A difference between the other folders and the source folder is that the ones in C: that did mount were not empty.

So you cannot mount _any_ non-empty c-drive directory? I can't reproduce that:

```
PS C:\test> dir


    Directory: C:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/4/2017   4:12 PM              7 file.txt


PS C:\test>

docker run -v "C:\test:C:\test" microsoft/nanoserver powershell -c dir C:\test


    Directory: C:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/4/2017   4:12 PM              7 file.txt
```

> I also checked security permissions. Since the host is not a domain joined network, I thought maybe something to do with file ACLs? Not sure.

That shouldn't matter for Windows to Windows mounts.

> I am using Windows containers; not sure why this would be a moby/moby problem?

The code in moby/moby is what powers both Docker Linux containers and Docker Windows containers (it was previously named `docker/docker`).

**Comment by vikalyan** [comment] 2017-05-05 04:59
@friism Makes sense. Non-empty folders was a hypotheses; looks like that wasn't it. Haven't yet tried on Windows Server 2016 yet.

**Comment by friism** [comment] 2017-05-05 15:17
@vikalyan also note that the destination folder (if on c-drive) has to be empty or non-existant: https://github.com/moby/moby/issues/20127

**Comment by vikalyan** [comment] 2017-05-05 22:44
@friism The container image doesn't have a C:\source at all. Also, this was working before. Same image, same invocation etc.

**Comment by friism** [comment] 2017-05-06 00:50
@vikalyan again, this is unlikely to be a problem with Docker for Windows. For that reason, I recommend opening an issue in moby/moby and pinging @jhowardmsft

**Comment by vikalyan** [comment] 2017-05-07 04:59
@friism  That's fair. Will do!

**Comment by friism** [comment] 2017-05-07 16:52
Closing here since it's now tracked on moby/moby.

**Closed by friism** 2017-05-07 16:52 UTC
Labels: area/wincon

**Comment by jtilander** [comment] 2018-02-21 22:12
On the moby issue, they said it's a windows issue so they closed it there. And this ticket is closed. 

So is this tracked anywhere for resolution? Or did everyone just close the tickets and Windows 10 is officially not supported for docker?

**Comment by cowlinator** [comment] 2018-03-16 22:56
@vikalyan ^
