### ISSUE TITLE
Unable to edit command line

### ISSUE THREAD

**Issue by heaths** [docker/for-win#148] opened 2016-10-16 16:16 UTC
### Expected behavior

Using the left arrow should allow me to edit the command line.

### Actual behavior

Left arrow acts like backspace. This is a regression from a couple beta builds ago.

### Information

* Windows 10 Anniversary Update, 10.014393.321
* Using Windows Containers with microsoft/windowsservercore:latest
* Diagnostics ID: 46038B3F-DEDA-4C40-9668-9A6DE7D46E18/2016-10-16_09-14-19

### Steps to reproduce the behavior

1. Type command line with mistake early on (or execute wrong command line, then use up arrow to recall)
2. Use left arrow to go back and correct mistake

**Comment by rneugeba** [comment] 2016-10-16 16:48
Thanks for reporting. I can't reproduce this. I can start a interactive container like `docker run -ti --rm alpine:latest /bin/sh` and command line editing works as expected. I'm using powershell to start the container.

Could you provide more details, like which shell you are using etc

**Comment by heaths** [comment] 2016-10-17 16:15
As noted, I was using Windows containers with "microsoft/windowsservercore:latest". The default shell is "cmd.exe", which is what I was using. But even if I switch to "powershell.exe" this happens (it's still based on "conhost", so that's not surprising).

**Comment by rneugeba** [comment] 2016-10-17 16:24
ah, sorry, I missed that. Thanks for the reply

**Comment by friism** [comment] 2016-10-17 18:37
@heaths hm, I can't reproduce - what's your `docker version`?

![working-navigation](https://cloud.githubusercontent.com/assets/126104/19450391/10e57b0e-945e-11e6-85cf-940e8743404c.gif)

**Comment by heaths** [comment] 2016-10-17 20:08
```
> docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

> docker run -t --rm microsoft/windowsservercore:latest hostname
e2fbd4e53297
```

**Comment by friism** [comment] 2016-10-17 20:22
@heaths and what's the command that you run where arrow navigation fails?

**Comment by heaths** [comment] 2016-10-17 20:36
Any command, really. For example:
```
> docker run -it --rm microsoft/windowsservercore:latest cmd
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

> echo Hello, world!
```
When I use the left arrow to, say, edit "world" to "friism", it actually deletes characters. After characters are removed, using the right arrow does not restore them (so it's not seemingly just a drawing issue).

**Comment by friism** [comment] 2016-10-17 20:48
ah, I get it too when running `cmd`. Pinging @jhowardmsft to see he remembers what the situation is.

**Comment by rneugeba** [comment] 2016-10-17 23:25
this seems specific to `cmd` (tested with running docker both from `cmd` and `powershell`). with:
```
docker run -it --rm microsoft/windowsservercore:latest powershell
```
command line editing seems to work

[I'm on build 14931]

**Comment by jhowardmsft** [comment] 2016-10-17 23:25
The left arrow functionality is only expected to work interactively when using PowerShell and WindowsServerCore images. Using nanoserver or cmd won't work due to functionality currently in the platform.

**Comment by friism** [comment] 2016-10-17 23:26
Thanks @jhowardmsft , closing issue since this is a Windows limitation.

**Closed by friism** 2016-10-17 23:26 UTC
Labels: area/wincon
