### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by oparoz** [docker/for-win#120] opened 2016-10-01 18:11 UTC
## Expected behavior

Docker should start in a minute or 2
### Actual behavior

Docker never starts and burns CPU cores doing nothing unless you exit Docker while booting it...
Happens with both stable and beta 27
### Information

```
[19:18:38.623][Program        ][Info   ] Version: 1.12.1-stable
[19:18:38.655][Program        ][Info   ] Starting on: 10/1/2016 7:18:38 PM
[19:18:38.655][Program        ][Info   ] OS: Windows 10 Pro
[19:18:38.655][Program        ][Info   ] Edition: Professional
[19:18:38.655][Program        ][Info   ] Id: 1607
...
[19:18:40.248][Updater        ][Info   ] Local build 7135 is as good as the remote 7135 on channel Stable
...
14 minutes later user is fed up and leaves
[19:32:55.594][App            ][Info   ] User clicked on exit
[19:32:55.600][Notifications  ][Info   ] Docker will shut down
...
3 minutes later Docker is finally alive, but starts instead of shutting down
[19:34:48.305][Firewall       ][Info   ] Ports are opened
[19:34:48.307][HyperV         ][Info   ] Create
...
[19:35:35.353][Notifications  ][Info   ] Docker is running
...
[19:35:35.365][NamedPipeClient][Info   ] Sending Stop()...
...
[19:35:44.401][NamedPipeClient][Info   ] Received response for Stop
[19:35:44.400][NamedPipeServer][Info   ] Stop done.
```

This seems like a networking issue. I'm not sure what it's waiting for though
### Steps to reproduce the behavior
1. Install
2. Launch

**Comment by oparoz** [comment] 2016-10-01 18:27
What makes things worse is that it becomes impossible to uninstall or upgrade Docker once someone has tried to start it. Processes just hang and need to be killed.

**Comment by rneugeba** [comment] 2016-10-02 10:39
@oparoz thanks for the report. Is the UI responsive enough to send us a diagnostics for us to take a look at?

**Comment by oparoz** [comment] 2016-10-02 18:24
@rneugeba - Sometimes it is, sometimes it isn't :). I managed to create one yesterday I think: `a49b2a4a-3ae9-42df-8788-66bc7e3272ff`

**Comment by oparoz** [comment] 2016-10-02 18:32
And the beta just started in 6 minutes. Better than ever before.

This part takes 5 minutes
```
[20:23:47.749][Updater        ][Info   ] Local build 7538 is as good as the remote 7538 on channel Beta
[20:28:43.804][Firewall       ][Warning] Firewall service is not running.
[20:28:43.808][HyperV         ][Info   ] Create
```

**Comment by rneugeba** [comment] 2016-10-05 06:45
@oparoz thanks for the ID above, but I could not find any diagnostics logs for it.

when you say that the latest Beta starts in 6minutes, this seems very very long and disabling the firewall should not be necessary. @dgageot any idea what happens between the two steps above which could take that long?

Also, once it starts, could you go to the diagnostics menu and manually update the diagnostics and post the ID it provides? The ID should be printed in the UI in the form of `<UUID>/<date>`. It gathers additional information which may help us to debug.

thanks

**Comment by oparoz** [comment] 2016-10-06 13:15
Here is a new ID generated after it had started:
D8F2CE2C-C114-49A2-B30D-49F9D84B97F3/2016-10-06_15-10-48

Cheers.

**Comment by dgageot** [comment] 2016-10-18 08:53
@oparoz Could you please give a try to Docker for Windows Beta28 and tell us if you still have the issue?

**Comment by oparoz** [comment] 2016-10-19 20:23
I've just tried and no luck. It took 20 minutes to open the ports.

```
[17:16:38.357][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[17:16:38.358][HyperVGuids    ][Info   ] Installing GUIDs...
[17:16:38.359][HyperVGuids    ][Info   ] GUIDs installed
[17:16:38.360][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[17:16:38.666][Updater        ][Info   ] Local build 7813 is as good as the remote 7813 on channel Beta
[17:37:22.314][Firewall       ][Info   ] Ports are opened
```

**Comment by dgageot** [comment] 2016-12-01 06:19
@oparoz Can you please take a look at Beta31 and provide an diagnostic id if the issue is still there?

**Comment by oparoz** [comment] 2016-12-01 11:31
Just tried beta 31 and it launched within a minute. I need to do another test with a different network config to see if that's the culprit, but it's looking good so far.
Thanks!

**Comment by rneugeba** [comment] 2016-12-02 15:44
@oparoz thanks for getting back to us and glad that Beta31 seems to work for you. We'll close this issue in a few days if we don't hear back but you can always re-open later if you still have the issue.

**Closed** 2016-12-04 17:01 UTC
Labels: kind/bug, status/1-acknowledged
