### ISSUE TITLE
Docker for windows: Network timed out while trying to connect to https://index.docker.io/

### ISSUE THREAD

**Issue by katygarner** [docker/for-win#55] opened 2016-08-24 12:57 UTC
### Expected behavior
Run:
 `docker run hello-world`
Expect no errors

### Actual behavior
Error returned
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.

### Information

Diagnostic ID: 8B05F453-80F1-4E18-95A3-6FF744157E1B/2016-08-24_11-00-27
Running on windows 10 
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

### Steps to reproduce the behavior

  1. Use windows powershell (also tried other terminals)
  2. Run `docker run hello-world`

**Comment by ebriney** [comment] 2016-08-25 10:44
Thanks for the report. That's seem to be a DNS problem, we are working on better detection of DNS addresses for the next version.
Can you try to set google DNS (8.8.8.8) in the settings windows (settings/Network/DNS Server -> click on fixed then apply)?

**Comment by katygarner** [comment] 2016-08-25 10:46
Thanks @ebriney I've already tried this (from reading other issues) and it didn't solve the problem.

**Comment by ebriney** [comment] 2016-08-25 10:48
And if you use 10.29.1.9 which is your other DNS address?

**Comment by katygarner** [comment] 2016-08-25 10:52
@ebriney I've just tried and it's the same issue.

**Comment by ebriney** [comment] 2016-08-25 11:04
Ok, sorry. I'll try to figure out how what is wrong!

**Comment by katygarner** [comment] 2016-08-25 11:05
@ebriney thank you, please let me know if you need any more information from me.

**Comment by ebriney** [comment] 2016-08-25 12:40
For sure

**Comment by jirapast** [comment] 2016-08-31 08:36
i got same problem and have no idea to moving on

**Comment by katygarner** [comment] 2016-09-02 15:38
@ebriney Do you have any more updates on what may be causing this problem?

**Comment by Toyinster** [comment] 2016-09-03 11:22
This is literally driving me insane - I have a fresh install of Windows 10 Professional and Docker 1.12.0. Hyper-V is installed and enabled. I have one instance of DockerNAT which appears to be healthy and I have changed the DNS to 8.8.8.8/8.8.4.4, Network DNS Server in Docker is set to Fixed 8.8.8.8

I don't have WIndows Insider running anymore after having to completely rebuild my system after the last update. Is this a requirement?

**Comment by friism** [comment] 2016-09-04 08:12
@Toyinster insider builds are not required - can you please run the diagnostics and post the ID here so we can help you debug?

**Comment by xckai** [comment] 2016-09-05 09:37
same issue , I could't use docker search and docker pull .I got-->  response from daemon: Get https://index.docker.io/v1/search?q=kafka&n=25: dial tcp: i/o timeout

**Comment by Toyinster** [comment] 2016-09-05 19:45
Thanks @friism : 266A07B2-7A2A-4835-86FA-240386A20EDD/2016-09-05_20-44-37

**Comment by manbearpigisreal** [comment] 2016-09-06 00:48
Same issue here

ID: 97125ACF-EA70-4F3A-9758-7B71FBBF18EA/2016-09-05_20-46-39

**Comment by cognition** [comment] 2016-09-06 15:33
Sending build context to Docker daemon 6.144 kB
Step 1 : FROM microsoft/windowsservercore
latest: Pulling from microsoft/windowsservercore
1239394e5a8a: Retrying in 15 seconds     <-- counted down several times
1239394e5a8a: Downloading
unknown blob

7E6A9CC6-B3A4-49B4-9CE7-2C1656D9D91E/2016-09-06_11-20-53

**Comment by Heliosare** [comment] 2016-09-07 12:30
Same here :,(
ADB9E8D7-58E2-4C9A-96E0-F2D2FCAF9FE6/2016-09-07_14-24-49

**Comment by cokacola1978** [comment] 2016-09-08 13:48
same here
 id: 7B3BFE8C-E485-46E2-8227-397D2372BB9E/2016-09-08_15-40-55

**Comment by dgageot** [comment] 2016-09-08 14:34
@katygarner @jirapast @Toyinster @manbearpigisreal @cognition @Heliosare @cokacola1978 A new version (Beta25) was released yesterday with fixes to the network/dns stack. Could you please give it a try and tell us if you see an improvement? Thanks a lot!

**Comment by jjhii** [comment] 2016-09-08 22:22
I was asked to put my log file here from another thread:
https://forums.docker.com/t/network-timed-out-on-pull/21449

Error:
PS C:\> docker pull nginx
Using default tag: latest
Pulling repository docker.io/library/nginx
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/nginx/images. You may want
to check your internet connection or if you are behind a proxy.

[log-2016-09-08_18-07-50.txt](https://github.com/docker/for-win/files/462818/log-2016-09-08_18-07-50.txt)

**Comment by TimMensch** [comment] 2016-09-09 05:19
I was actively using Docker from Windows as recently as four days ago (Sept 4). I tried updating a package tonight only to find a similar error to the ones described in this bug:

```
tim@copper12 MINGW64 /c/Users/tim/projects/games/steel
$ docker pull openresty/openresty:trusty
Pulling repository docker.io/openresty/openresty
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/openresty/openresty/images. You may want to check your internet connection or if you are behind a proxy.
```

I've installed nothing relevant since then. I checked for Windows updates, and none were installed after September 1st. There were a couple of Visual Studio updates installed on the 4th, but no other hints as to why things that were working four days ago are suddenly dead. Docker itself hasn't updated (that I can tell) in the past four days either. The docker bin folder was installed/last modified on August 11th and the exe files are dated July 28th.

I'm downloading the beta now. I'll update with results.

**Comment by TimMensch** [comment] 2016-09-09 05:38
OK, after upgrading to the beta, I can pull images again. Odd, but there you go.

**Comment by cokacola1978** [comment] 2016-09-09 06:34
it's OK for me with the last beta version
thanks @dgageot

**Comment by dgageot** [comment] 2016-09-09 06:48
@TimMensch @cokacola1978 Thanks a lot for the update!

@jjhii Which version of Docker for Windows are you using? If it's not Beta25, can you please give it a try?

@katygarner @jirapast @Toyinster @manbearpigisreal @cognition @Heliosare If I get good feedback from a couple of you or if I get no news at all, I'll tentatively close the issue.

**Comment by katygarner** [comment] 2016-09-09 08:38
@dgageot Where can I get Beta25 from?  (the website has changed and only offers me the latest version of windows for docker - which I've tried and has the same issues)  Thanks

**Comment by katygarner** [comment] 2016-09-09 08:58
@dgageot Beta25 has fixed this problem for me.  Thanks

**Comment by dgageot** [comment] 2016-09-09 09:00
\o/

**Comment by jjhii** [comment] 2016-09-09 14:21
@dgageot --- when I do check update, it says I have the latest version

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Comment by dgageot** [comment] 2016-09-09 16:37
@jjhii Can you please double check in the About box?

**Comment by jjhii** [comment] 2016-09-09 18:00
@dgageot - about box says Version 1.12.0-stable (build: 5968) 9cd1dc2

**Comment by dgageot** [comment] 2016-09-09 18:02
Then you won't see the fix. It's only on beta channel for now

**Comment by manbearpigisreal** [comment] 2016-09-09 18:19
@dgageot This may sound silly, but where can I get the Beta version?

**Comment by friism** [comment] 2016-09-09 18:21
@manbearpigisreal Download from here: https://docs.docker.com/docker-for-windows/

**Comment by manbearpigisreal** [comment] 2016-09-09 18:43
@dgageot @ebriney  awesome, beta works for me.

Thank you both.

**Comment by jjhii** [comment] 2016-09-09 19:08
@dgageot @manbearpigisreal  -- ok, installed version 1.12.1-beta25 (build: 6833) 158f2ee
Problem seems to be gone, thanks.

**Comment by dgageot** [comment] 2016-09-10 10:33
Looks like Beta25 fixes the issue for a lot of users and nobody complained that the issue is still here. So let's close this ticket!

**Closed by dgageot** 2016-09-10 10:33 UTC
Labels: area/network, kind/bug, version/1.12.0, version/beta24

**Comment by Toyinster** [comment] 2016-09-11 15:56
Thanks @dgageot - the update has fixed the issue! Great job.

**Comment by xckai** [comment] 2016-09-12 06:55
Using  ip:port instead of url:port as proxy , It will works fine

**Comment by lotrdocker** [comment] 2016-12-01 13:35
Last stable version 1.12.3 not working for me, got error "Network timed out while trying to connect to .... You may want to check your internet connection or if you are behind a proxy." where version 1.12.2 works perfectly.
