### ISSUE TITLE
Problens on open Docker v2.1.00

### ISSUE THREAD

**Issue by potreco** [docker/for-win#4430] opened 2019-08-05 19:28 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
- [X] I have uploaded Diagnostics
- Diagnostics ID: EAF1C51E-4168-4BD9-B2C7-E19B9D64E586/20190805192334

### Expected behavior
Open the Docker normally

### Actual behavior
Error crash on Docker init.

### Information
I tried to restore to default settings, but isn't work

- Windows Version: Windows 10 18362.267
- Docker Desktop Version: 2.1.0.0

### Steps to reproduce the behavior
  1. Open docker
  2. Crash error

**Comment by mikeparker** [comment] 2019-08-06 16:42
```
[16:23:16.566][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: O comando em execu��o parou porque a vari�vel preferencial "ErrorActionPreference" ou o par�metro comum est� definido como Stop: 'DockerDesktopVM' falhou ao inicializar.

Mem�ria insuficiente no sistema para iniciar a m�quina virtual DockerDesktopVM.

N�o foi poss�vel inicializar a mem�ria: Mem�ria esgotada (0x8007000E).

'DockerDesktopVM' falhou ao inicializar. (ID da m�quina virtual 86FAE889-6232-4750-9A3E-3D7313F56176)

Mem�ria insuficiente no sistema para iniciar a m�quina virtual DockerDesktopVM com tamanho de ram de 2048 megabytes. (ID da m�quina virtual 86FAE889-6232-4750-9A3E-3D7313F56176)

'DockerDesktopVM' n�o p�de inicializar a mem�ria: Mem�ria esgotada (0x8007000E). (ID da m�quina virtual 86FAE889-6232-4750-9A3E-3D7313F56176)
   em System.Management.Automation.Runspaces.AsyncResult.EndInvoke()

```
Duplicate of https://github.com/docker/for-win/issues/4348, https://github.com/docker/for-win/issues/4362, https://github.com/docker/for-win/issues/4368

**Closed by mikeparker** 2019-08-06 16:42 UTC
