### ISSUE TITLE
docker top fails.

### ISSUE THREAD

**Issue by jtnord** [docker/for-win#2124] opened 2018-06-19 20:55 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 51061EC2-9F3F-4302-A4BA-4D95A2305093/2018-06-19_21-46-18

### Expected behavior

docker top should always work.

### Actual behavior

sometimes a container gets iteself into a state where `docker top` fails.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?

Yes

  - Is the problem new?

No

  - Did the problem appear with an update?

No

  - A reproducible case if this is a bug, Dockerfiles FTW.
-->
  - Windows Version:

win 10, 1803

  - Docker for Windows Version:

```
C:\Users\jnord>docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: kubernetes

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
 Kubernetes:
  Version:     Unknown
  StackAPI:                   Unknown
```

### Steps to reproduce the behavior

1. `git clone https://github.com/jenkinsci/docker-fixtures.git`
2. `cd docker-fixtures\src\main\resources\org\jenkinsci\test\acceptance\docker\fixtures\SshdContainer`
3. `docker build --tag topissuecontainer .`
4. `docker run --detach --publish 22:22 --name topissue topissuecontainer`
5. `ssh -o StrictHostKeyChecking=no -i unsafe test@localhost /bin/bash -c 'for value in {1..99999} ; do /bin/echo $value ^> /dev/null; done'`
6. `ssh -o StrictHostKeyChecking=no -i unsafe test@localhost`     (leave this running)
7. (in a new window)   `docker top topissue`

```
C:\Users\jnord>docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      windows/amd64
 Experimental: true
 Orchestrator: kubernetes

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
 Kubernetes:
  Version:     Unknown
  StackAPI:                   Unknown

C:\Users\jnord>docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                            NAMES
6d38ee735886        jenkins/ssh-slave:14b48574e3b3             "/usr/sbin/sshd -D -e"   5 hours ago         Up 5 hours          127.0.0.1:32795->22/tcp                          silly_chandrasekhar
223cad22d5e3        selenium/standalone-firefox-debug:2.53.1   "/opt/bin/entry_poin…"   31 hours ago        Up 31 hours         0.0.0.0:4444->4444/tcp, 0.0.0.0:5900->5900/tcp   hopeful_hermann

C:\Users\jnord>docker top 6d38ee735886
Error response from daemon: Unexpected pid '111498root': strconv.Atoi: parsing "111498root": invalid syntax
```

It seems like there is some whitespace missing and the ps output is mis parsed.

```
C:\Users\jnord>docker exec -it 6d38ee735886 /bin/bash
root@6d38ee735886:/# ps auxwww
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  69944   632 ?        Ss   16:05   0:00 /usr/sbin/sshd -D -e
root         11  0.0  0.1  19952  3676 pts/0    Ss   20:51   0:00 /bin/bash
root         17  0.0  0.1  38380  3088 pts/0    R+   20:52   0:00 ps auxwww
```

looks like the ps command in the moby vm does not wrap properly...

```
C:\Users\jnord>docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
ff3a5c916c92: Pull complete
Digest: sha256:e1871801d30885a610511c867de0d6baca7ed4e6a2573d506bbec7fd3b03873f
Status: Downloaded newer image for alpine:latest
/ # ps aux
PID   USER     TIME   COMMAND
    1 root       0:05 /sbin/init text
    2 root       0:00 [kthreadd]
    3 root       0:31 [ksoftirqd/0]
    5 root       0:00 [kworker/0:0H]
    7 root       1:14 [rcu_sched]
    8 root       0:00 [rcu_bh]
    9 root       0:03 [migration/0]
   10 root       0:00 [lru-add-drain]
   11 root       0:00 [watchdog/0]
   12 root       0:00 [cpuhp/0]
   13 root       0:00 [cpuhp/1]
   14 root       0:00 [watchdog/1]
   15 root       0:03 [migration/1]
   16 root       0:07 [ksoftirqd/1]
   18 root       0:00 [kworker/1:0H]
   19 root       0:00 [kdevtmpfs]
   20 root       0:00 [netns]
   21 root       0:00 [khungtaskd]
   22 root       0:00 [oom_reaper]
   23 root       0:00 [writeback]
   24 root       0:00 [kcompactd0]
   26 root       0:00 [ksmd]
   27 root       0:05 [khugepaged]
   28 root       0:00 [crypto]
   29 root       0:00 [kintegrityd]
   30 root       0:00 [bioset]
   31 root       0:00 [kblockd]
   32 root       0:00 [ata_sff]
   33 root       0:00 [hv_vmbus_con]
   34 root       0:00 [devfreq_wq]
  154 root       0:16 [kswapd0]
  155 root       0:00 [vmstat]
  156 root       0:00 [cifsiod]
  157 root       0:00 [cifsoplockd]
  159 root       0:00 [bioset]
  160 root       0:00 [xfsalloc]
  161 root       0:00 [xfs_mru_cache]
  226 root       0:00 [kthrotld]
  228 root       0:00 [acpi_thermal_pm]
  230 root       0:00 [bioset]
  231 root       0:00 [bioset]
  232 root       0:00 [bioset]
  233 root       0:00 [bioset]
  234 root       0:00 [bioset]
  235 root       0:00 [bioset]
  236 root       0:00 [bioset]
  237 root       0:00 [bioset]
  238 root       0:00 [bioset]
  239 root       0:00 [bioset]
  240 root       0:00 [bioset]
  241 root       0:00 [bioset]
  242 root       0:00 [bioset]
  243 root       0:00 [bioset]
  244 root       0:00 [bioset]
  245 root       0:00 [bioset]
  246 root       0:00 [bioset]
  247 root       0:00 [bioset]
  248 root       0:00 [bioset]
  249 root       0:00 [bioset]
  250 root       0:00 [bioset]
  251 root       0:00 [bioset]
  252 root       0:00 [bioset]
  253 root       0:00 [bioset]
  254 root       0:00 [scsi_eh_0]
  255 root       0:00 [scsi_tmf_0]
  256 root       0:00 [bioset]
  257 root       0:00 [bioset]
  288 root       0:00 [scsi_eh_1]
  289 root       0:00 [scsi_tmf_1]
  292 root       0:00 [bioset]
  323 root       0:00 [nvme]
  324 root       0:00 [dm_bufio_cache]
  325 root       0:03 [hv_balloon]
  326 root       0:00 [ipv6_addrconf]
  681 root       0:00 {rungetty.sh} /bin/sh /usr/bin/rungetty.sh
  683 root       0:00 /bin/login -f root
  684 root       0:00 [kworker/1:1H]
  685 root       0:01 [kworker/0:1H]
  694 root       0:00 -sh
 1043 root       0:11 [jbd2/sda1-8]
 1044 root       0:00 [ext4-rsv-conver]
 1362 root       2:57 /usr/bin/containerd
 1390 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/acpid -address /run/containerd/containerd.sock -containerd-binary /usr/bin/co
 1409 root       0:00 /sbin/acpid -f -d
 1431 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/diagnose -address /run/containerd/containerd.sock -containerd-binary /usr/bin
 1449 root       0:00 /usr/local/bin/diagnosticsd -vsock -hvsock
 1477 root       1:02 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/docker-ce -address /run/containerd/containerd.sock -containerd-binary /usr/bi
 1498 root       0:04 /usr/local/bin/docker-init /usr/bin/entrypoint.sh
 1523 root       0:00 {entrypoint.sh} /bin/sh /usr/bin/entrypoint.sh
 1530 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/rngd -address /run/containerd/containerd.sock -containerd-binary /usr/bin/con
 1558 100        0:00 rpcbind
 1565 root       2:53 /sbin/rngd
 1570 root       0:00 rpc.statd
 1573 root       0:00 {start-docker.sh} /bin/sh /usr/bin/start-docker.sh
 1574 root      63:46 kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --cluster-dns=10.9
 1575 root       0:02 /usr/bin/lifecycle-server
 1608 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/trim-after-delete -address /run/containerd/containerd.sock -containerd-binary
 1617 root      41:03 /usr/local/bin/dockerd -H unix:///var/run/docker.sock --config-file /run/config/docker/daemon.json --swarm-default-advertise-addr=eth0 --userland-proxy-path /usr/bin/vpnkit-expose-port
 1629 root       0:00 /usr/bin/trim-after-delete -- /sbin/fstrim /var/lib/docker
 1673 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/vpnkit-forwarder -address /run/containerd/containerd.sock -containerd-binary
 1691 root      14:50 /vpnkit-forwarder -hvGuid 0B95756A-9985-48AD-9470-78E060895BE7
 1731 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/vpnkit-tap-vsockd -address /run/containerd/containerd.sock -containerd-binary
 1741 root       2:37 docker-containerd --config /var/run/docker/containerd/containerd.toml
 1751 root       0:00 {entrypoint.sh} /bin/sh /entrypoint.sh
 1788 root       0:00 /sbin/vpnkit-tap-vsockd --tap eth0 --message-size 8192 --buffer-size 262144 --listen --pidfile /tmp/pid
 1810 root       0:04 containerd-shim -namespace services.linuxkit -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/services.linuxkit/vsudd -address /run/containerd/containerd.sock -containerd-binary /usr/bin/co
 1835 root       0:02 /vsudd -inport 23a432c2-537a-4291-bcb5-d62504644739:unix:/var/run/docker.sock
 1868 root       1:01 /sbin/vpnkit-tap-vsockd --tap eth0 --message-size 8192 --buffer-size 262144 --listen --pidfile /tmp/pid
 3098 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/ac6d9b8845a55d6749dd32f848d924f603f7173c5e0c318a892bf63ca54772c7 -address /var/run
 3176 root       0:00 /pause
 3192 root       0:03 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/8d88d15d3dc8bd5b34d6db6879ff1cc22962efa02faf3237502b81f9e9227887 -address /var/run
 3241 root       0:00 /pause
 3292 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/01b94dcc7368eb21e0a4325c045dc20c8a8988a9f44ef7d42456c18f24706ab5 -address /var/run
 3319 root       0:00 /pause
 3412 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/70f61c6856ad9ef4598c512882c6b1a30c47e6450c083e5405170d2d5597feff -address /var/run
 3435 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/97e42055b896a46684abfe8b7d0e1d275c5a26c80c1a011399f834cb3a0ffbdb -address /var/run
 3454 root       0:00 /pause
 3461 root      28:13 kube-scheduler --address=127.0.0.1 --leader-elect=true --kubeconfig=/etc/kubernetes/scheduler.conf
 3466 root       0:19 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/cb869a11e56c3c1e61dddba4cff9b23d19a63f018d618db1b882a791bb11eeff -address /var/run
 3486 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/716897b6eda0537d1a2efe6ae3053eba0230a9efa6a4f51640ce449d620de604 -address /var/run
 3512 root     127:42 kube-apiserver --enable-bootstrap-token-auth=true --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --client-ca-
 3515 root      30:20 etcd --data-dir=/var/lib/etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379
 3709 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d7fa37871bf21e28dc1e5797e95c8416012b9e0cf6070401ee464eb33e1a492a -address /var/run
 3733 root     113:08 kube-controller-manager --service-account-private-key-file=/etc/kubernetes/pki/sa.key --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --add
 3851 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/253fa1ee5759aa0fa79bda9bf5aafb4a0d75135080bdcec9ec438379f44f5832 -address /var/run
 3878 root       0:00 /pause
 4059 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/023a525d08d955c2a604c1828edbd0a081952a32f92a2a3fa6cb3d5fb9190d6d -address /var/run
 4080 root       1:29 /kube-dns --domain=cluster.local. --dns-port=10053 --config-dir=/kube-dns-config --v=2
 4110 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/c119975264555795293dc1cbf8f8f467c2b091ea5f4e8697fb211394bde28466 -address /var/run
 4143 root       0:00 /pause
 4172 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/70eaf96e2901d9b8bc589acc8ffd9c97b78ccc911eb8cfe656874cd4b7a0728f -address /var/run
 4193 root       0:09 /dnsmasq-nanny -v=2 -logtostderr -configDir=/etc/k8s/dns/dnsmasq-nanny -restartDnsmasq=true -- -k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-
 4199 root       0:03 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/0b94caa3324669c933008e142df0d348df9d5f664c856c18a6fd5d486ad9e36c -address /var/run
 4216 root       0:00 /pause
 4286 root       0:03 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/b046e6046233f400a73d0e4b1e39344758fd0d7fc8295ce46fe144173f12f2b4 -address /var/run
 4310 nobody     3:34 /sidecar --v=2 --logtostderr --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
 4346 root       0:03 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/aa282e551f46a76856f55753a53e713289b979175e2a1711466dfc0edc36d29f -address /var/run
 4387 root       0:00 /pause
 4406 root       0:19 /usr/sbin/dnsmasq -k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053
 4431 root       0:03 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/65087dc9f670e9b7b27bfb4b0b4d43f88b648e82225698b0bc5dfdcbdee8a954 -address /var/run
 4450 root      10:53 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf
 4570 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/c333357388f88679a047cb8fa6a40fc994da4e72434d8574d2d7f7104b0d56be -address /var/run
 4589 root       0:10 /compose-controller --kubeconfig  --reconciliation-interval 30s
 4630 root       0:04 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/bcd3da88e6ee0cb10298254f660abfac97619ec1e5508b4b9331acb82ed872eb -address /var/run
 4651 root       1:40 /api-server --kubeconfig  --authentication-kubeconfig  --authorization-kubeconfig  --etcd-servers=http://127.0.0.1:2379 --secure-port=9443 --tls-ca-file=/etc/docker-compose/tls/ca.crt --tls-cert-file=
 4733 root       0:00 /usr/bin/vpnkit-expose-port -proto tcp -host-ip 0.0.0.0 -host-port 5900 -container-ip 172.17.0.2 -container-port 5900
 4768 root       0:00 /usr/bin/vpnkit-expose-port -proto tcp -host-ip 0.0.0.0 -host-port 4444 -container-ip 172.17.0.2 -container-port 4444
 4774 root       0:10 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/223cad22d5e3c09b57c0ac8d91e0833a1cabaaa36c7e39d928d03d29a4e9a362 -address /var/run
 4801 root       0:00 {entry_point.sh} /bin/bash /opt/bin/entry_point.sh
 4864 root       0:00 [kauditd]
 4866 root       0:00 sudo -E -i -u seluser DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_FRONTEND=noninteractive FIREFOX_VERSION=47.0.1 GECKODRIVER_VERSION=0.10.0 GEOMETRY=1680x1090x24 no_proxy=localhost SCREEN_DEPTH=24 SCREEN_
 4881 1000       0:00 {xvfb-run} /bin/sh /usr/bin/xvfb-run -n 99 --server-args=-screen 0 1680x1090x24 -ac +extension RANDR java -jar /opt/selenium/selenium-server-standalone.jar
 4893 1000      59:33 Xvfb :99 -screen 0 1680x1090x24 -ac +extension RANDR -nolisten tcp -auth /tmp/xvfb-run.N0xsUU/Xauthority
 4898 1000       4:23 java -jar /opt/selenium/selenium-server-standalone.jar
 4911 root       0:46 fluxbox -display :99.0
20843 root       0:00 [kworker/1:1]
22178 root       0:00 [kworker/1:2]
22200 root       0:00 [kworker/0:1]
22232 root       0:00 [kworker/u256:1]
23782 root       0:00 [kworker/1:0]
24071 root       0:00 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/25cf4e841d1407643907f4dd12287b40fd716b423a90eb687bd79fb6d8634d44 -address /var/run
24090 root       0:00 /bin/sh
24155 root       0:00 ps aux
1107451000      15:47 /usr/bin/firefox -foreground
111498root       0:00 /usr/bin/vpnkit-expose-port -proto tcp -host-ip 127.0.0.1 -host-port 32795 -container-ip 172.17.0.3 -container-port 22
111504root       0:00 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/6d38ee735886430deaf12401ad513ba12186521813c605a70f43517454aff06f -address /var/run
111525root       0:00 /usr/sbin/sshd -D -e
123363root       0:04 [kworker/0:0]
123435root       0:00 [kworker/u256:3]
```

**Comment by jasonbivins** [comment] 2018-06-21 17:57
@jtnord 
How often are you rebooting the machine? It actually looks like Docker is losing network connectivity, and is trying to reconnect but somehow ending halfway without making the connection or dropping completely.  What do you have setup for the DNS server under Settings > Network in docker?

```
[17:08:17.797][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 192.168.250.1:53 caught Lwt.Resolution_loop.Canceled returning Eof

[17:08:17.814][BootHelper     ][Info   ] Resume from hibernation
[17:08:18.080][DnsUpdater     ][Info   ] Network configuration change detected
[17:08:18.080][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[17:08:18.783][ApiProxy       ][Info   ] time="2018-06-19T17:08:18+01:00" msg="Node status error: Unauthorized"
```

**Comment by jtnord** [comment] 2018-06-22 10:58
@jasonbivins I don't restart that often (maybe once or twice a week), I tend to hibernate to move between places.  Also jumping between wired interfaces and different WiFi (and add in connecting / disconnected to the VPN to boot).  I don;t believe this is tied to networking - but trying to parse the output from ps in mobyvm which is not correct when the PIDs are higher than 100000

FWIW I do have sometime general issues with docker not being able to start new containers after a network change (that may be what you are seeing in the diagnostics bundle - but that's an issue I have yet to raise (as it doesn't block me as at the point it happens it is safe for me to restart docker, whereas with this issue it occurs when I am actively using docker)

Restarting Docker fixes this issue until it happens again.  I think this is just the amount of processes run via docker - I can reproduce this at will with our product testing framework in a 
  `while run-the-tests; do "echo ran tests"; done`  (because the tests start new docker containers and in each container it will likely run another 16 processes).  and IIRC the pids in linux (moby vm) will increase until they wrap at which point they will recycle, but they don't recycle by default.
That is I can reproduce this after a reboot.

DNS setting is "Automatic" in settings.

**Comment by jtnord** [comment] 2018-07-04 14:42
## steps to reproduce.

1. git clone https://github.com/jenkinsci/docker-fixtures.git 
2. cd docker-fixtures\src\main\resources\org\jenkinsci\test\acceptance\docker\fixtures\SshdContainer
3. docker build --tag topissuecontainer .
4. docker run --detach --publish 22:22 --name topissue topissuecontainer
5. ssh -o StrictHostKeyChecking=no -i unsafe test@localhost /bin/bash -c 'for value in {1..99999} ; do /bin/echo $value ^> /dev/null; done'
6. ssh -o StrictHostKeyChecking=no -i unsafe test@localhost     (leave this running)
7. (in a new window)   docker top topissue

**Comment by thaJeztah** [comment] 2018-07-04 19:38
This looks to be a duplicate of https://github.com/moby/moby/issues/34282, and being worked on in this PR https://github.com/moby/moby/pull/36621. The PR is stalling currently, because the contributor didn't currently have time to work on it

**Comment by rn** [comment] 2018-07-09 15:51
@thaJeztah thanks for the link to the upstream issue. Closing this here as it is tracked elsewhere.

**Closed by rn** 2018-07-09 15:51 UTC
Labels: version/18.05.0-ce-win67
