### ISSUE TITLE
first start on windows10 64bit

### ISSUE THREAD

**Issue by serge-max** [docker/for-win#6645] opened 2020-05-12 07:25 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-05-12 08:53
No info about what the problem is, closing this ticket.

**Closed by stephen-turner** 2020-05-12 08:53 UTC
