### ISSUE TITLE
Display error 

### ISSUE THREAD

**Issue by krishnakumar081020** [docker/for-win#12862] opened 2022-07-24 09:17 UTC
![image](https://user-images.githubusercontent.com/70047548/180640530-37988443-b81a-4288-a8ec-de7fc7c4d090.png)

**Comment by prathameshpise** [comment] 2022-07-24 12:11
what to do after this error?

**Comment by joe0BAB** [comment] 2022-07-25 07:53
Thanks for reporting this issue! For docker 4.10 the container log view isn't working if webgl isn't available on your machine. We have found the cause and fixed it already. The fix will be included in 4.11 which we hope to release this or next week.

**Comment by nicks** [comment] 2022-07-26 15:07
I'm going to de-dupe this against https://github.com/docker/for-win/issues/12825 to centralize communication there, thanks for filing!

**Closed by nicks** 2022-07-26 15:07 UTC
