### ISSUE TITLE
Docker Desktop win 3.3.0 Update failed

### ISSUE THREAD

**Issue by sztan** [docker/for-win#11294] opened 2021-05-25 08:05 UTC
Hello : Docker 3.3.0 (62916) / Windows 10 Entreprise version 10.0.18363. Same issue. An update is available but I cannot install it because I cannot kill system (critical process)
Same as (https://github.com/docker/for-win/issues/9459) but with higher version.

**Comment by stephen-turner** [comment] 2021-05-25 10:29
Closing as dupe of #9459.

**Closed by stephen-turner** 2021-05-25 10:29 UTC
