### ISSUE TITLE
Docker ignoring enable/disable setting on Manual proxy configuration

### ISSUE THREAD

**Issue by sobait** [docker/for-win#9773] opened 2020-12-11 13:31 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8E20CD83-717D-462E-B35D-E9A218DFC958/20201211131900

### Expected behavior
Normally sitting behind a corporate proxy, and have enabled the manual proxy configuration and filled in my proxy settings. When I'm at home, I don't have a proxy. I disable the manual proxy configuration by clicking the enable/disable button, but leaving my settings in the form.

Expected outcome is that Docker will not use a proxy anymore when e.g. using `docker run hello-world`.

### Actual behavior
When performing the above steps, Docker continues to use the proxy settings, effectively ignoring the enable/disable button.

### Information

  - Windows Version: W10 Enterprise 1803 Build 17134.1845
  - Docker Desktop Version: Tested on both 2.5.0.1 and 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I have also assured that the `http_proxy` and `https_proxy` environment variables are unset.

I cannot say if the problem occurred on earlier versions, I noticed this first on 2.5.0.1.

I have also checked the settings file in `C:\Users\<user>\AppData\Roaming\Docker\settings.json` and confirmed that the `proxyHttpMode` setting is switching true/false when enabling/disabling the manual configuration setting in Docker Desktop.

### Steps to reproduce the behavior

  1. Enable manual proxy configuration in Docker Desktop
  2. Fill in proxy settings
  3. Apply & Restart
  4. Open Git Bash
  5. `docker run hello-world`
  6. After pull and run, close Git Bash.
  7. Connect to network without proxy.
  8. Disable manual proxy configuration in Docker Desktop
  8. Apply & Restart
  9. Repeat 4-6.

`docker run` will now fail with message:

> docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup <proxy_url> on 192.168.65.1:53: no such host

**Comment by stephen-turner** [comment] 2020-12-11 14:16
Thanks for the report. In fact, we've already fixed it in our internal builds, so it will be in the next release. You can follow updates in #9357 (I'm going to close this ticket as a dupe of that one).

As a workaround you can blank out the values, though I realise that's less convenient if you want to restore them later.

**Closed by stephen-turner** 2020-12-11 14:16 UTC
