### ISSUE TITLE
Unable to set Docker for Windows Containers Daemon Settings

### ISSUE THREAD

**Issue by caleblloyd** [docker/for-win#473] opened 2017-02-07 21:22 UTC
Version: 1.13.1-rc2-beta41 (10019)
Channel: beta

**Expected Behavior**

Daemon configuration settings should get put into ` C:\ProgramData\Docker\config\daemon.json`

**Actual Behavior**

Even if I manually set `C:\ProgramData\Docker\config\daemon.json`, it is overwritten with `{}` every time I click "Switch to Windows Containers"

![image](https://cloud.githubusercontent.com/assets/2414837/22712051/6ba8a902-ed51-11e6-8bf9-ae4d763b6c3f.png)

**Comment by simonferquel** [comment] 2017-02-08 09:23
This is a UI issue: 
Daemon.json settings for Linux and Windows containers are separated. So, when you are switched to Linux containers, editing the daemon.json only applies to Linux. After switching to Windows containers, the Daemon tab should show you the Windows daemon.json content (and allow you to edit it as you want). Clicking "apply" will restart the Windows daemon with those settings.

Although please make sure you don't modify the file by hand. The UI will always rewrite it before start (this is by design, so that we can inspect / modify settings in the future to merge them with our own requirements).

**Comment by simonferquel** [comment] 2017-02-08 09:24
I'll wait for confirmation that this works for you and close the issue

**Comment by caleblloyd** [comment] 2017-02-08 11:28
The problem for me is that my network bridge is somehow messed up and now I can't start Docker for Windows without it, so my "Switch to Windows Containers" never completes successfully.. https://github.com/docker/docker/issues/30280

Also, what if someone puts invalid settings in the `daemon.json` and then can't get the windows daemon to start?  Then they will never be able to change them in the GUI.  Maybe the GUI should present tabs with Linux Daemon Settings and Windows Daemon Settings.

**Comment by simonferquel** [comment] 2017-02-08 12:14
Hmm, you are right.
As a temporary workaround, you can go to c:\users\<username>\AppData\Roaming\Docker and edit settings.json. Just add `"WindowsDaemonOptions":"{  \"bridge\": \"none\"}"` in the root json object.

**Comment by simonferquel** [comment] 2017-02-08 15:38
Please let me know if the workaround works. The UI part of the issue is now tracked internally.

**Comment by caleblloyd** [comment] 2017-02-08 15:48
Workaround works great - thanks!

**Closed** 2017-02-08 16:27 UTC
Labels: area/gui, status/1-acknowledged
