### ISSUE TITLE
Docker doesn't start after system restart

### ISSUE THREAD

**Issue by CatCode91** [docker/for-win#11018] opened 2021-04-23 15:26 UTC
Windows 10 Pro, 10.0.19042 Build 19042
AMD Ruzen 7 PRO 4750U

Docker was installed and worked well untill I installed Visual Studio C++ developer tools throught Visual studio 2019 installer.
After restart, fish whale in tray displays without boxes, And app looks like does not answer. When I click on whale icon using right button - i see only two points - "Dashboard" and "Settings" instead menu with many options what I saw early.

When i try to run getting-started command it writes:
 _docker: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect_

I found some issues - for first, I used dockerCli.exe -SwitchDaemon. It helps, docker starts. But all my previous installed images were disappeared and disappeares over and over after every system restarts. Could you help me please?

**Comment by kuhnboy** [comment] 2021-04-26 14:51
Odd, I am now experiencing the exact same issue.

**Comment by stephen-turner** [comment] 2021-05-14 09:44
I think this is a dupe of #11047, so I'm going to close this issue and you can follow there for updates. In particular please see my latest comment there (https://github.com/docker/for-win/issues/11047#issuecomment-841136100) for something to try.

**Closed by stephen-turner** 2021-05-14 09:44 UTC

**Comment by CatCode91** [comment] 2021-05-15 10:10
i just started use 2.5.X version. It is works fine
