### ISSUE TITLE
Allow to choose the version of Kubernetes to install

### ISSUE THREAD

**Issue by donatelloOo** [docker/for-win#10137] opened 2021-01-19 16:42 UTC
It would be nice to be able to choose the underlying Kubernetes version that is installed on Docker Desktop.

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [X] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

Docker Desktop is bound to a specific version of Kubernetes.
When enabling Kubernetes, the latest supported version is installed.
After upgrading Docker Desktop without resetting (or disabling/enabling kubernetes), we can keep the same version.
But during reset, there is no way to specify the version of Kubernetes we want to install.

### Expected behavior

We should be able to choose the version of Kubernetes in a subset of supported versions (especially to validate APIs are working with a specific version).

### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by stephen-turner** [comment] 2021-01-19 17:01
Thanks. This is a dupe of docker/roadmap#103, so I'm going to close this one. Feel free to upvote that one with a thumbs-up emoji.  (Unfortunately no-one else has shown any interest in it after eight months).

**Closed by stephen-turner** 2021-01-19 17:01 UTC
