### ISSUE TITLE
Wrong Date/Time

### ISSUE THREAD

**Issue by devlife** [docker/for-win#72] opened 2016-09-06 14:42 UTC
### Expected behavior

I would expect the container date and time would match host date and time
### Actual behavior

The container is a day+ behind my windows host
### Steps to reproduce the behavior
1. `docker run...` for ubuntu:latest
2. `date` from within the container
3. Note that the date/time is different than your windows host

**Comment by rneugeba** [comment] 2016-09-06 22:28
@devlife thanks for the report. We use the in kernel Hyper-V time synchronisation and it should work, but may only gradually adjust time. A couple of questions:
- did this happen after your computer was set to sleep?
- did you check the time soon after waking up after sleep?
- did the gap get less over time?

**Comment by antoniocanas** [comment] 2016-09-09 09:23
This is happening to me as well, since last update

**Comment by cvillerm** [comment] 2016-09-09 12:33
Same problem happening to me. The clock drift corresponded exactly to the time my laptop was in sleep mode. I didn't realize it immediately, but I started to see wrong behaviors in my Docker applications (ELK stack reporting logs with a time difference) just after resuming.

**Comment by devlife** [comment] 2016-09-09 12:58
@rneugeba My computer was not set to sleep. I'll set my computer to sleep and check the time and see if the gap has lessened.

**Comment by cvillerm** [comment] 2016-09-09 15:02
Disabling and then enabling again the **MobyLinuxVM > Settings > Integration Services > Time synchronization** service from **Hyper-V Manager** resyncs the clock of containers immediately.

**Comment by Matthias247** [comment] 2016-09-28 11:05
Unfortunately I have issues with this as well. I'm using docker for windows mainly as some build/cross-compilation tool, by running a build scripts inside linux containers. This problems e.g. leads to automake failing:
> checking whether build environment is sane... configure: error: newly created file is older than distributed files!

Always happens if the PC is going to sleep (e.g. during lunch time). Does not recover until I manually restart docker, so I think it's not really syncing during runtime but only at startup.

**Comment by rlpowell** [comment] 2016-09-29 15:17
My symptom was that on *every change* vim would say "WARNING File has changed since last read!".  Took me ages to figure out it was a time problem.

This *was not* happening 2 or 3 updates ago, even with regular laptop sleep/hibernation.

**Comment by schwamster** [comment] 2016-10-05 18:03
also ran into that problem while running terraform within a container to create an infrastructure on azure. 
creating a storage account failed with an authorization problem.  cvillerms Tipp helped

**Comment by cfstras** [comment] 2016-10-18 15:34
For me, resuming from hibernate leaves the docker clock at the same time it was hibernated at. Restarting docker fixes the timestamp, but also means restarting containers...

**Comment by entzik** [comment] 2016-10-20 10:11
same issue here, exactly as reported by @cfstras . Annoying thing for me is one of the containers is running keycloak and after the laptop sleeps, it  issues OIDC certificates with an outdated timstamp so all my authentication chain is broken.

I would rather have docker stop all my containers after a sleep, at least I would know I have to restart everything.

**Comment by rcarmo** [comment] 2016-10-24 14:08
Add me to the list. Using `make` inside Moby with time drift is impossible, so much so that I've resorted to building my containers on a remote box instead.

**Comment by zifik** [comment] 2016-10-25 15:00
@rneugeba 
- did this happen after your computer was set to sleep? **Yes**
- did you check the time soon after waking up after sleep? **Yes, correction is either not happening or not happening quickly enough. -- Needs to be immediate**
- did the gap get less over time? **Not sure, will look into this aspect**

Using Docker GUI to Restart Docker appears fix it immediately every time. Though there has got to be a more elegant solution.

**Comment by provegard** [comment] 2016-11-15 12:59
Any update/priority on this issue?

**Comment by dgageot** [comment] 2016-11-21 16:20
Hi everyone, a fix should ship in the Beta version, schedule next week.

**Comment by dgageot** [comment] 2016-11-30 09:44
@amalm @pmsousa Beta 31 was just released. It's expected to fix this issue. Please give it a try!

**Comment by dgageot** [comment] 2016-12-01 05:55
@devlife @cvillerm @Matthias247 @cfstras @provegard @zifik @rcarmo Beta 31 was just released. It's expected to fix this issue. Please give it a try!

**Comment by cfstras** [comment] 2016-12-01 10:03
Docker version 1.13.0-rc2-beta31 (9132) de6f6c2
- Working with docker, all good
- Hibernate PC in the evening
- Wake up
```
[inside container]
# date
Wed Nov 30 21:34:24 UTC 2016
## go to hyper-v manager, disable and enable Time Sync integration
# date
Thu Dec  1 09:56:05 UTC 2016
```

So the issue is still there. Do I maybe have to recreate my docker machine to get the fix in? Because I'd rather not go through the process of backing up development containers.

**Comment by dgageot** [comment] 2016-12-01 10:49
@cfstras The Disable/Enable should have be done automatically. Can you share your logs?

**Comment by cfstras** [comment] 2016-12-01 11:11
Sure.
before hibernate: (`log.1.txt`) http://pastebin.com/egk8bhzq
after hibernate: (`log.txt`) http://pastebin.com/ZUw2efY9

**Comment by Matthias247** [comment] 2016-12-01 12:13
@dgageot Thanks for working on it. Just tested with beta31 but still experience the same problem after PC went to sleep after the amount of time that was set in the windows power options (power plan) settings.

**Comment by rlpowell** [comment] 2016-12-01 16:49
Same here:

rlpowell@680e70564cca> date
Thu Dec  1 01:22:37 PST 2016
rlpowell@680e70564cca> date
Thu Dec  1 08:48:11 PST 2016

I'll note that the list of integration services looks different; "Data Exchange" and "Backup" are now unchecked.  Maybe your code is toggling the wrong thing depending on versions of hyper-v, or something like that?

**Comment by rlpowell** [comment] 2016-12-02 16:15
Oh, for the record: this is with a fresh docker VM after a reboot.

**Comment by dgageot** [comment] 2016-12-02 16:54
@Matthias247 @cfstras @rlpowell I'm working on a fix. A good way to test it would be for you to contact by at david dot gageot at docker.com. I'll send you a pre-release version for you to test.

**Comment by dgageot** [comment] 2016-12-08 21:53
Hi @Matthias247 @cfstras @rlpowell have you tried to install Beta32?

**Comment by Matthias247** [comment] 2016-12-09 22:19
@dgageot I could test it only very briefly since I'm working on something different at the moment. But apperently it works now. After an hour of standby I can still build the stuff without automake complaining about wrong time.  
Thanks for fixing it!

**Comment by dgageot** [comment] 2016-12-09 22:20
@Matthias247 Good to hear!

**Comment by cfstras** [comment] 2016-12-12 12:36
@dgageot I immediately got problems because I had deactivated Hyper-V to do a clean install -- and saw you pushed a hotfix because the installer did not remind me I still had it disabled :)

Since then, docker has been working like a charm for me! Thanks for all your efforts!

**Comment by dgageot** [comment] 2016-12-12 18:09
@cfstras Good to hear, I'm going to close the issue then!

**Closed by dgageot** 2016-12-12 18:09 UTC
Labels: area/hyper-v, kind/bug, status/0-more-info-needed, status/4-fix-released-beta, status/5-will-be-closed

**Comment by steve-heslouin** [comment] 2017-02-16 09:39
This error remains on Mac OS with latest beta docker version

Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by rneugeba** [comment] 2017-02-16 10:27
@steve-heslouin this is already tracked here https://github.com/docker/for-mac/issues/1260

**Comment by aron-truvian** [comment] 2019-08-13 22:05
Is this actually resolved?  I am experiencing this currently on my docker desktop for windows (v2.1.0.1)

If my computer has been put to sleep, and then awakens, my docker containers are all out of sync with my host's time.  This continues until I restart docker.

**Comment by davclark** [comment] 2019-08-13 23:33
I can confirm that this has re-emerged as a bug - also running Docker on Windows, Edge, v2.1.1.0

Maybe this is due to WSL2-related changes? I'm experiencing the issue with Hyper-V / Moby.

**Comment by giggio** [comment] 2019-11-06 16:31
This issue is still ocurring on the latest version:

````
▶ docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
````

Are there any plans to actually fix this? The problem happened after the PC hibernated.

The solution to disable and reenable time synchronization on HyperV works, but we shouldn't have to do this manually.

**Comment by LiamRoelsWA** [comment] 2019-11-13 08:33
I have the exact same issue and it messes up all sorts of things. I usually fix it by restarting docker but there really should be a better fix...

**Comment by twodrops** [comment] 2019-12-18 15:34
Is this issue still tracked somewhere else? The issue is reproducible with Docker Edge Version 2.1.7.0.
The clock drift happens after windows goes to sleep

**Comment by SiobhanBaynes** [comment] 2020-01-03 09:44
I'm also seeing this on V19.03.5.  This doesn't appear to be fixed.

**Comment by motish1111** [comment] 2020-01-07 08:39
Having the same problem. V19. Please Help

**Comment by ftrauernicht** [comment] 2020-01-07 09:03
I also have this Problem on docker V.19.0.3.5. Its very annoying to restart the service every morning :/

**Comment by borgez** [comment] 2020-01-09 11:52
I also have this Problem

**Comment by aron-truvian** [comment] 2020-01-15 22:06
Note: This issue still exists, and will cause certificate failures in a docker image when trying to do a dotnet restore.

See: [Dotnet Restore SSL Error](https://github.com/dotnet/dotnet-docker/issues/1341)

**Comment by TomasEkeli** [comment] 2020-01-22 13:15
I'm seeing this on Windows 10 running Docker version 19.03.2, build 6a30dfc

It stops an apt-get update on build as it thinks some security-updates are from the future. I'm currently over 16hours off.

**Comment by ahernandez-allegion** [comment] 2020-01-22 18:13
Same issue with Docker 19.03.5 on Windows but running Linux VMs on Windows Subsystem for Linux (WSL). Restarting Docker fixes the issue.

**Comment by truman303** [comment] 2020-01-22 19:35
Hi. Same issue running Docker Desktop Community 19.03.5 pn Windows 10. Using windows containers with microsoft/iis base image. Restarting Docker Desktop doesn't seem to help. Recreating the image doesn't seem to help either.

**Comment by MateusAmin** [comment] 2020-01-23 01:10
Time slip of 4 minutes after bringing the host up from sleep. Diagnostics ID:

1CE0BF2A-0D0C-4EA2-BECE-8C51FE289A95/20200123010621

**Comment by kamko** [comment] 2020-01-23 16:36
Definitely not fixed. Should we open a new issue?

**Comment by ftrauernicht** [comment] 2020-01-23 19:32
> Hi. Same issue running Docker Desktop Community 19.03.5 pn Windows 10. Using windows containers with microsoft/iis base image. Restarting Docker Desktop doesn't seem to help. Recreating the image doesn't seem to help either.

I also have this some times, I try to restart the service and sometimes it get fixed but not always.. In such cases i get a new error called "Error getting userland proxy(...)". As soon as I get this the only solution seems to be restarting the whole pc :/

**Comment by rensa** [comment] 2020-01-23 22:55
@ftrauernicht There's a new issue at https://github.com/docker/for-win/issues/4526 :)

**Comment by philippe-granet** [comment] 2020-03-06 08:02
**In release note:**
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2203
**Known issues:** 
_In some cases, Docker containers do not synchronize time with the host when the host machine is put to sleep._

**Comment by lucaalex87** [comment] 2020-03-26 14:29
Known issue means it's fixed, or if we know about it, we can just forget it? 😃

**Comment by davclark** [comment] 2020-03-27 23:31
@lucaalex87 as of 3 days ago, there's an installer linked here that appears to fix the issue. Still not stable / release, but a fix if you need it:

https://github.com/docker/for-win/issues/4526

**Comment by lucaalex87** [comment] 2020-03-30 09:40
@davclark Thank you for this comment - I'll give it a try! :) I wasn't aware of the other issue number.
