### ISSUE TITLE
could'nt load windows images : PRocessUtilityVMImage error. Symantec conflict ?

### ISSUE THREAD

**Issue by lechacha** [docker/for-win#597] opened 2017-03-20 21:25 UTC
Hi
I can't load any image with my W10 Docker in Windows mode (everything ok with linux images)

With Windows images, i always get an error  during ProcessUtilityVMImage

example below :
docker: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\c454ad7b9f9f07ee9391b29fde0c74bb90e1edba5dbce77e2c01c725497985ee\UtilityVM: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus..

I've tried to run images, pull images load images. Always the same error with my lapTop.
Everything is ok with another PC (but i use avast an not SEP !)

Any Idea ??

### Information
A diagnostic was uploaded with id: 3A4E16E1-BB10-4D6A-A829-05167D887E91/2017-03-20_22-16-56

**Comment by friism** [comment] 2017-03-21 06:55
Yes, symantec is know to cause problems, closing this as duplicate of https://github.com/docker/for-win/issues/463

Please re-open if you can't get it working.

**Closed by friism** 2017-03-21 06:55 UTC
