### ISSUE TITLE
can not start docker desktop ver 2.2.0.3(42716)

### ISSUE THREAD

**Issue by quyennguyenvan** [docker/for-win#5797] opened 2020-02-17 13:22 UTC
System.InvalidOperationException:
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.WPF.BackendClient.Version()
   at Docker.WPF.BackendClient.CheckVersion()
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by saboorgee** [comment] 2020-03-13 08:57
I am also receiving same issue. after windows update, Any solution??

**Comment by ruchikv** [comment] 2020-04-19 06:15
https://stackoverflow.com/questions/61289669/docker-desktop-not-starting-sequence-contains-no-matching-element

**Comment by mat007** [comment] 2020-06-05 04:30
Duplicate of #6007

**Closed by mat007** 2020-06-05 04:30 UTC
