### ISSUE TITLE
Crash on updating Docker

### ISSUE THREAD

**Issue by ManoMarks** [docker/for-win#264] opened 2016-11-30 01:53 UTC
### Expected behavior
Docker would start up after updating

### Actual behavior
Crash on updating

### Information
8933275A-5908-48B5-91BD-6EFD64746CE2/2016-11-29_17-49-09
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior
Update Docker

**Comment by dgageot** [comment] 2016-11-30 06:10
Closing. Duplicate of https://github.com/docker/for-win/issues/173

**Closed by dgageot** 2016-11-30 06:10 UTC
