### ISSUE TITLE
docker for windows ignores disk size

### ISSUE THREAD

**Issue by stefanloerwald** [docker/for-win#6594] opened 2020-05-08 16:06 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior

I have the disk image size set to 100GB, but I get errors in images saying that the disk is full. The disk uses 60GB, which seems to be the default size for docker-for-win, isn't it? I expect it to only fail when the disk is actually full (at which point I would increase the available space...)

### Actual behavior

The disk is "full" at 60GB, even though it's configured to go up to a hundred.

This is with version 2.2.0.5 (43884) (oh and please make things like version numbers copyable from the UI).

**Comment by mat007** [comment] 2020-05-11 05:53
Thanks for the report, it’s likely a duplicate of #5881 which has been fixed in Edge 2.2.3.0 and will be available in the next Stable (due imminently).

And yes the About box content should be selectable, I’m pretty sure it used to be so there must have been a regression there. I’ll create an internal ticket.

**Closed by mat007** 2020-05-11 05:53 UTC
