### ISSUE TITLE
Unable to mount directory using pwd or bash path

### ISSUE THREAD

**Issue by othercorey** [docker/for-win#6668] opened 2020-05-13 00:18 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B7E6258B-CBAA-42FE-BF7A-B96F626857AD/20200513001103

### Expected behavior
Directory mounted and able to list and access files in mounted directory.

### Actual behavior
Directory is not mounted or is mounted with no files.

### Information
  - Windows Version: Windows 10 1909 build 18363.778
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.
  - Using Hyper-V backend

This issue started after upgrading to version 2.3.02 through automated update.

### Steps to reproduce the behavior
- Run container with local directory mounted: `-v /$(pwd):/target`
- Navigate to target directory and list files

The directory is mounted if using the full windows path with windows drive prefix: `D:/directory`.

**Comment by guanzo** [comment] 2020-05-13 05:38
For me, this is the 2nd time docker desktop pushed out a broken version that forces me to downgrade. Of course, downgrading to the previous version didn't fix it, so now I have go version by version to find the one that actually works with `-v /$(pwd):/target`. Each attempt is a 1 gig download and 10 minutes of my time wasted. 

This is ridiculous, please test your software or something idk.

**Comment by SunboX** [comment] 2020-05-13 06:53
I re-installed v2.2.2.0 from here [1] and it works again. The v2.2.3.0 did also not work after re-install!

[1] https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by avalanchus** [comment] 2020-05-14 08:58
> This is ridiculous, please test your software before releasing. 

But what if this version of docker began to be used in production? So many mistakes can lead to large losses of reputation, leading to the refusing of this technology.

**Comment by nebuk89** [comment] 2020-05-14 10:55
Hey, we appreciate the frustration and understanding that Docker Desktop is a complex piece of software. We don’t have anything on our roadmap right now about allow people to import/export their current setup but it is something we have discussed.  Feel free to open this as a feature request on our roadmap https://github.com/docker/roadmap for adding the ability to export/import to make this bit easier. 

We have recently made some fundamental changes to the file system on Windows (https://www.docker.com/blog/deep-dive-into-new-docker-desktop-filesharing-implementation/) and this still sits in some of the tail of these bugs. This was pretty big change for us and we hope in the long run that it will be a better experience, we are still working through some of those original changes and some of the knock on effects of early fixes we did post this launch. 

Thank you for continuing to raise bugs :) without you trying the new versions and letting us know-> we wont get there 🙌

**Comment by stephen-turner** [comment] 2020-05-14 12:27
It's also worth mentioning that we don't just test the product in-house. We know that Docker Desktop is a platform that is being used in an infinite number of ways. So to try and cover as many of the long tail of use cases as possible, we release all changes to the Edge channel several weeks before they get released to Stable, and we have several thousand users on that channel (more always welcome!). Unfortunately none of them reported this particular issue, which means that it's rare, although we appreciate that it's no less frustrating if it happens to you.

**Comment by othercorey** [comment] 2020-05-14 16:11
@stephen-turner What is the recommended alternative then? I thought using a bash shell was fairly common.

**Comment by mat007** [comment] 2020-05-14 19:12
@othercorey we are working on providing a workaround and a proper long term fix.
Right now we have a quick fix that seems to be working, here is a link to a private build if you’d like to try: https://download-stage.docker.com/win/stable/45279/Docker%20Desktop%20Installer.exe
The only difference between Stable 2.3.0.2 and this build is that fix.

It seems this regression is due to the two `/` at the beginning of the path. Our code that rewrites the paths from Windows (the host) to Linux (the Hyper-V based VM) has been changed and we didn’t think of this as a possible use case.

Given that `$(pwd)` returns a path that starts with a `/` already, `/$(pwd)` then starts with two.
Is this intentional? Maybe you wanted to work around

> If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "/usr/bin/bash.exe" to "C:\Program Files\Git\usr\bin\bash.exe". When that is not desired -- e.g. "--upload-pack=/opt/git/bin/git-upload-pack" or "-L/regex/" -- you need to set the environment variable MSYS_NO_PATHCONV temporarily, like so:
>
>    MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc
>
> Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "//usr/bin/bash.exe".

(from https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues)
?

If you have scripts (especially if they need to work on Mac/Linux as well) it’s probably not worth changing them but if it’s from the command line you could perhaps:
1. use `MSYS_NO_PATHCONV=1` and remove the leading `/`
2. use `$(pwd -W)` and remove the leading `/` to use Windows paths

**Comment by othercorey** [comment] 2020-05-14 19:39
@mat007 

Thanks for the information. I was not aware of `$(pwd -W)` as the new best practice. I can confirm that works with the previous stable release and the custom 45279 build you provided. I did not have time to test with the vanilla 2.3.0.2 build, but I assume it's fine.

For background info, we avoid MSYS_NO_PATHCONV because it has caused several hard-to-debug issues when people leave it enabled in the wrong spot.

I have also tested normal `$(pwd)` with the custom 45279 build and can confirm it works.

**Comment by dbaxiell** [comment] 2020-05-15 10:02
Hi, I had the same problem (using unix style paths, for Git bash + Windows Hyper-V Docker) and the private build above solved the file sharing issue.

**Comment by stephen-turner** [comment] 2020-05-15 11:50
So I guess none of our Edge users are using this `/($pwd)` idiom with an extra leading slash. :-(

**Comment by othercorey** [comment] 2020-05-18 13:07
> So I guess none of our Edge users are using this `/($pwd)` idiom with an extra leading slash. :-(

There is no other way to use a bash path with git bash. It's not something we add randomly so it's going to be standard for those types of users.

**Comment by mat007** [comment] 2020-05-28 21:35
A fix has now been released in Docker Desktop Stable 3.2.0.3, I’ll go ahead and close this issue.
Thanks!

**Comment by guanzo** [comment] 2020-05-28 21:37
I apologize for my outburst, it was totally unnecessary. Thanks for the fix.

**Comment by stephen-turner** [comment] 2020-05-29 14:23
Thanks, @guanzo.

**Closed** 2020-05-29 14:23 UTC
Labels: status/1-acknowledged, version/2.3.0.2

**Comment by dbaxiell** [comment] 2020-05-29 14:26
> A fix has now been released in Docker Desktop Stable 3.2.0.3, I’ll go ahead and close this issue.
> Thanks!

2.3.0.3 🙂

**Comment by rfay** [comment] 2020-06-05 20:49
This seems to still be a problem in 2.3.0.3.  I'm not sure it made it.

It happens on the Windows side, and it wasn't happening before I upgraded test runners to Windows 2004 and turned on WSL mode. 

Did it get lost in WSL2 mode?

**Comment by mat007** [comment] 2020-06-06 06:59
> Did it get lost in WSL2 mode?

I don’t think we rewrite the paths in WSL 2 mode, @simonferquel ?

**Comment by rfay** [comment] 2020-06-06 14:14
It's possible that this is only an issue when using WSL2 mode with a volume mount (using -v). And it's possible that it's a somewhat different issue. But an example is 

```
 docker run -v "//c/Users/rfay:/junkhome"  --rm busybox sh -c "df /junkhome"
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay                2355376       376   2355000   0% /junkhome
```

Note that /junkhome is an overlay mount, not the right thing, and of course, it's empty.

If you use a Windows path in the mount, it works:

```
$ docker run -v "c:/Users/rfay/tmp:/junkhome"  --rm busybox sh -c "df /junkhome"
Filesystem           1K-blocks      Used Available Use% Mounted on
C:\134               267361040  45139336 222221704  17% /junkhome
```

If you use --mount, it works correctly:

```
docker run --rm --mount "type=bind,src=/c/Users/rfay/tmp,target=/junkhome" busybox sh -c "df /junkhome"
Filesystem           1K-blocks      Used Available Use% Mounted on
C:\134               267361040  45140792 222220248  17% /junkhome
```

On Windows 1909, with Docker 2.3.0.3 (obviously Hyper-V) you see it working perfectly fine. Note the difference of the filesystem type though (correct grpcfuse instead of "C:\134 " as shown in Windows 2004)
```
 docker run -v "//c/Users/rfay:/junkhome"  --rm busybox sh -c "df /junkhome"

Filesystem           1K-blocks      Used Available Use% Mounted on
grpcfuse             267418584  61587208 205831376  23% /junkhome
```

It's impossible to execute this example on Windows 2004 with 2.3.0.3 in Hyper-V mode because of https://github.com/docker/for-win/issues/5955, the "function not implemented" bug.

**Comment by simonferquel** [comment] 2020-06-08 10:05
Windows docker API proxy is the same on hyper-v and WSL 2. However, please note that the Linux CLI (used when running the CLI from your WSL 2 distro) uses a different proxy. This one handles mount sources as they exist within your wsl2 distro. So if you have your C drive mounted in /mnt/c (the defaults in WSL), mounting from there should be `-v /mnt/c:/c-drive`.

**Comment by rfay** [comment] 2020-06-08 12:35
The situation we're talking about here is using Docker-WSL2 with the Windows-side CLI. WSL2-in-distro works OK. As does Docker Hyper-V (pre-2004)

**Comment by mat007** [comment] 2020-06-09 05:12
@rfay I think we fixed this while addressing another issue a few days ago, it seems to be working properly with our latest master build:
```
$ docker run -v "//c/Users/mathi:/junkhome"  --rm busybox sh -c "df /junkhome"
Filesystem           1K-blocks      Used Available Use% Mounted on
drvfs                485856252 403488712  82367540  83% /junkhome
```
I can share a link to download a build if you want.

**Comment by rfay** [comment] 2020-06-09 13:07
@mat007 I'd be happy test it, but don't specifically need it, as I changed all tests to use --mount instead of -v.  That output does look loads better.
