### ISSUE TITLE
"ErrorActionPreference" or common parameter is set to Stop: Element not found.

### ISSUE THREAD

**Issue by neridonk** [docker/for-win#429] opened 2017-01-25 09:33 UTC
### Expected behavior
Docker should run

### Actual behavior
Docker fails

### Information
I can create the mobyLinuxvm with thte Hyperv gui (Generation 1)
https://github.com/docker/for-win/issues/67#issuecomment-245841516
BUT when i try to run the machine i get 
"Boot failed: not a bootable disk. No bootable device."

this tip here didnt helped me too...
https://github.com/docker/for-win/issues/402#issuecomment-273961060

Sideinfo -> I have ESET as firewall

```
Log
`Version: 1.13.0 (9795)
Channel: Stable
Sha1: 0c6d765c5482987c547f4b2b68f04167ebd3f352
Started on: 2017/01/25 10:11:52.044
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\me\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:11:52.163][GUI            ][Info   ] Starting...
[10:11:52.513][Tracking       ][Info   ] Crash report and usage statistics are enabled
[10:11:52.517][SegmentApi     ][Info   ] Usage statistic: appLaunched
[10:11:52.590][NamedPipeClient][Info   ] Sending Version()...
[10:11:52.592][NamedPipeClient][Info   ] Received response for Version
[10:11:52.593][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:11:52.592][NamedPipeServer][Info   ] Version done in 00:00:00.
[10:11:52.682][Updater        ][Info   ] Checking for updates on channel Stable...
[10:11:52.684][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[10:11:52.685][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[10:11:52.685][PowerMode      ][Info   ] Stop
[10:11:52.685][HyperV         ][Info   ] Stop
[10:11:52.685][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[10:11:52.690][HyperV         ][Info   ] Script started at 10:11:52.690
[10:11:52.703][HyperV         ][Info   ] Module loaded at 10:11:52.703
[10:11:52.711][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:11:52.711][HyperV         ][Debug  ] [stop] took 00:00:00.0260012 to run
[10:11:52.711][OptimizeDisk   ][Info   ] Optimize
[10:11:52.711][PowerShell     ][Info   ] Run script...
[10:11:52.718][Moby           ][Info   ] Stop
[10:11:52.722][HyperV         ][Info   ] Create
[10:11:52.722][HyperVGuids    ][Info   ] Installing GUIDs...
[10:11:52.722][PowerMode      ][Info   ] Start
[10:11:52.722][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[10:11:52.722][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\Users\me\docker\MobyLinuxVM.vhdx -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[10:11:52.723][HyperVGuids    ][Info   ] GUIDs installed
[10:11:52.728][HyperV         ][Info   ] Script started at 10:11:52.728
[10:11:52.740][HyperV         ][Info   ] Module loaded at 10:11:52.740
[10:11:52.794][HyperV         ][Info   ] Creating Switch: DockerNAT...
[10:11:53.021][Updater        ][Info   ] Local build 9795 is as good as the remote 9795 on channel Stable
[10:11:54.033][HyperV         ][Info   ] Switch created.
[10:11:54.357][Firewall       ][Info   ] Ports are opened
[10:11:54.357][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

. Let's retry
[10:11:54.357][PowerShell     ][Info   ] Run script...
[10:11:55.703][HyperV         ][Info   ] Hyper-V is running
[10:11:55.703][PowerMode      ][Info   ] Stop
[10:11:55.703][HyperV         ][Info   ] Stop
[10:11:55.704][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[10:11:55.709][HyperV         ][Info   ] Script started at 10:11:55.709
[10:11:55.724][HyperV         ][Info   ] Module loaded at 10:11:55.724
[10:11:55.733][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:11:55.733][HyperV         ][Debug  ] [stop] took 00:00:00.0289991 to run
[10:11:55.733][OptimizeDisk   ][Info   ] Optimize
[10:11:55.733][PowerShell     ][Info   ] Run script...
[10:11:55.740][Moby           ][Info   ] Stop
[10:11:55.744][HyperV         ][Info   ] Destroy
[10:11:55.745][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[10:11:55.750][HyperV         ][Info   ] Script started at 10:11:55.750
[10:11:55.761][HyperV         ][Info   ] Module loaded at 10:11:55.761
[10:11:55.769][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:11:55.770][HyperV         ][Info   ] Destroying Switch DockerNAT...
[10:11:56.062][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[10:11:56.069][HyperV         ][Debug  ] [destroy] took 00:00:00.3249975 to run
[10:11:56.069][Firewall       ][Info   ] Closing ports...
[10:11:57.619][Firewall       ][Info   ] Ports are closed
[10:11:57.619][HyperVGuids    ][Info   ] Removing GUIDs...
[10:11:57.620][HyperVGuids    ][Info   ] GUIDs removed
[10:11:57.620][HyperV         ][Info   ] Create
[10:11:57.620][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\Users\me\docker\MobyLinuxVM.vhdx -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[10:11:57.625][HyperV         ][Info   ] Script started at 10:11:57.625
[10:11:57.636][HyperV         ][Info   ] Module loaded at 10:11:57.635
[10:11:57.672][HyperV         ][Info   ] Creating Switch: DockerNAT...
[10:11:58.277][HyperV         ][Info   ] Switch created.
[10:11:58.333][PowerMode      ][Info   ] Stop
[10:11:58.333][HyperV         ][Info   ] Stop
[10:11:58.333][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[10:11:58.338][HyperV         ][Info   ] Script started at 10:11:58.338
[10:11:58.348][HyperV         ][Info   ] Module loaded at 10:11:58.348
[10:11:58.357][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:11:58.357][HyperV         ][Debug  ] [stop] took 00:00:00.0239980 to run
[10:11:58.357][OptimizeDisk   ][Info   ] Optimize
[10:11:58.357][PowerShell     ][Info   ] Run script...
[10:11:58.363][Moby           ][Info   ] Stop
[10:11:58.367][HyperV         ][Info   ] Destroy
[10:11:58.367][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[10:11:58.376][HyperV         ][Info   ] Script started at 10:11:58.376
[10:11:58.386][HyperV         ][Info   ] Module loaded at 10:11:58.386
[10:11:58.394][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:11:58.395][HyperV         ][Info   ] Destroying Switch DockerNAT...
[10:11:58.653][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[10:11:58.659][HyperV         ][Debug  ] [destroy] took 00:00:00.2919975 to run
[10:11:58.659][Firewall       ][Info   ] Closing ports...
[10:11:58.961][Firewall       ][Info   ] Ports are closed
[10:11:58.961][HyperVGuids    ][Info   ] Removing GUIDs...
[10:11:58.961][HyperVGuids    ][Info   ] GUIDs removed
[10:11:58.961][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[10:11:58.995][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.


[10:11:58.996][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.


`
```

### Steps to reproduce the behavior

Windows 10 pro  Version 10.0.14393

1. Installed Docker
2. Started and here we go

**Comment by dgageot** [comment] 2017-01-30 08:16
Closing as a duplicate of https://github.com/docker/for-win/issues/390

**Closed by dgageot** 2017-01-30 08:16 UTC

**Comment by ChocoSmith** [comment] 2017-05-18 02:31
thought i would add this to this thread (comments arnt locked) as a comment for the duplicate issue #390. had the same issue, tried to reinstall more than once. including different versions (docker used to work)

found under by running powershell  Get-NetAdapter that it looked like my virtual adapter was faulty

for me what worked was the virtual network was the issue. i issued a reset (in windows 10 similar to thread https://www.howtogeek.com/265870/how-to-reset-your-entire-network-in-windows-10-and-start-from-scratch/) 

upon fresh start (didnt even need to reinstall) the correct virtual adapter was created and everything started working again

**Comment by mukeshkagarwal** [comment] 2017-07-14 09:14
I was also facing the same issue but it was random in nature, I found it is due to some inaccessibility of  network card by the docker start script. This inaccessibility further blocks the start up process of docker. 

I found one hack and it is working fine on my windows machine 

Hack
-----
Open `C:\Program Files\Docker\Docker\resources\mobylinux.ps1` with any editor in admin mode. 
Find following code (around line 164)

```
 $networkAdapter | Remove-NetIPAddress -Confirm:$false -ea SilentlyContinue

$networkAdapter | Set-NetIPInterface -Dhcp Disabled -ea SilentlyContinue

$networkAdapter | New-NetIPAddress -AddressFamily IPv4 -IPAddress $switchAddress -PrefixLength ($SwitchSubnetMaskSize) -ea Stop | Out-Null
```

Add a `return` after line 165 in a new line like below and save the file. 


```
$networkAdapter | Remove-NetIPAddress -Confirm:$false -ea SilentlyContinue

$networkAdapter | Set-NetIPInterface -Dhcp Disabled -ea SilentlyContinue

return

$networkAdapter | New-NetIPAddress -AddressFamily IPv4 -IPAddress $switchAddress -PrefixLength ($SwitchSubnetMaskSize) -ea Stop | Out-Null
```

Now restart docker and after restart completion execute following commands in dos admin mode to setup the network card manually

`netsh interface ipv4 set address name="vEthernet (DockerNAT)" static 10.0.75.1 255.255.255.0 `

You have to run this command everytime whenever you are doing system restart and docker completes start process (due to any reason). 
TIP : create a batch file of this command and save somewhere handy. 

Note: The ps hack would get undone by any docker update. so be aware...

**Comment by gblue1223** [comment] 2017-08-17 10:19
In my case, I changed my computer name from 'AAA' to 'BBB' and rebooted but on Hyper-V Manager the computer name still appearing as 'AAA' and I couldn't change the name on Hyper-V Manager so I've reverted the name to 'AAA' and it works without any error. Hope it helps someone.

**Comment by peponeska** [comment] 2017-08-25 07:27
I also have an ESET Firewall (feature of ESET Endpoint Security 6.4) enabled on **vEthernet (DockerNAT)** interface by default. Each time Docker updates it would not start again in Linux containers mode. 

## Solution
I did manage to get it working by editing `c:\Program Files\Docker\Docker\resources\MobyLinux.ps1` by **inserting/adding** this one line of code

    # Make sure ESET Firewall is disabled
    $networkAdapter | Disable-NetAdapterBinding -ComponentID ESET_EpfwLWF -ea SilentlyContinue

around line 164 where you should find the following original. 

    # Make sure the Switch has the right IP address
    $networkAdapter = Get-NetAdapter | ? { $_.DeviceID -eq $vmNetAdapter.DeviceId }
    if ($networkAdapter | Get-NetIPAddress -IPAddress $switchAddress -ea SilentlyContinue) {
        $networkAdapter | Disable-NetAdapterBinding -ComponentID ms_server -ea SilentlyContinue
        $networkAdapter | Enable-NetAdapterBinding  -ComponentID ms_server -ea SilentlyContinue
        Write-Output "Using existing Switch IP address"
        return
    }

@dgageot Could you please update the original `MobyLinux.ps1` so that I (or anyone else with this problem) would no longer have to manually edit it after each Docker update?

**Comment by friism** [comment] 2017-08-25 14:26
cc @ebriney 

I'm worried that making this addition will just shift the problem to happen whenever ESET gets updated.

**Comment by sherryhw** [comment] 2017-09-07 18:13
I think the Network adapters got really messy after uninstall and reinstall docker. Today when I opened my network adapters I saw even 10 more Hyper-V Virtual Ethernet Adapters. 
Here is my solution:
1. Device manager --> Network Adapters --> delete all the Hyper-V Virtual Ethernet Adapters.
2. Restart the docker and it will automatically create an Hyper-V Virtual Ethernet Adapters. Keep an eyes on the device manager and make sure there is only one Hyper-V adapter.
After this I think it should be allset for this issue. Thought sometime I will end up with another issue like "Docker hv-sock proxy (vsudd) is not reachable".  However, each time when we uninstall and reinstall the docker, we should keep an eye on that Hyper-V adapters and make sure there is only one.
Thanks,
Sherry

**Comment by eimis05** [comment] 2017-09-08 20:11
@mukeshkagarwal - yes thank you that worked!

**Comment by okproject** [comment] 2017-09-25 00:14
@sherryhw  Thank you very much, removing hyperv network adapters and resetting docker worked for me.

**Comment by solo-man2015** [comment] 2018-03-23 07:07
Everyone seems to have a favorite for windows 10, my problem seemed to be that MobyLinuxVM was not getting created so I did,  
Option 1
Stop docker service
1. Create a MobyLinuxVM on hyper V yourself
2. Setup switch type to DockerNAT 
3. Setup IP Addr and Subnet mask for virutal interface (Copy config from MobyLinux.ps1)
Now try restarting it should work ... 
Or 
Option 2 
Find the line $ErrorActionPreference = "Stop" in MobyLinux.ps1 
change it to $ErrorActionPreference = "SilentlyContinue"
Should work

**Comment by MrsLaviniaG** [comment] 2018-08-02 05:01
In Services I selected Hyper V Management and restarted it (right click - restart), even though it said it was running, and success.

**Comment by kamiNaranjo** [comment] 2019-05-24 14:38
> In Services I selected Hyper V Management and restarted it (right click - restart), even though it said it was running, and success.

After tried a lot of things this solution work for me. 

Thank you

**Comment by niranjanasu** [comment] 2019-06-21 22:25
I am also having the same problem.  Here is the crash report - D9597C1B-84F5-4FD7-9E8F-32A2EC7F0DB8/20190621151333

Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/06/21 15:13:19.163
Resources: c:\program files\docker\docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748
File: C:\Users\vzxzp1\AppData\Local\Docker\log.txt
CommandLine: "c:\program files\docker\docker\docker for windows.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:13:19.301][GUI            ][Info   ] Starting...
[15:13:19.565][ComponentVersions][Info   ] Edition community
[15:13:20.523][Tracking       ][Info   ] Crash report and usage statistics are enabled
[15:13:20.523][SegmentApi     ][Info   ] Usage statistic: appLaunched
[15:13:20.570][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:13:20.570][SegmentApi     ][Info   ] Usage statistic: Identify
[15:13:21.845][SegmentApi     ][Info   ] Usage statistic: eventNotElectedForFeature
[15:13:21.845][SegmentApi     ][Info   ] Usage statistic: stateFeatureDisabled
[15:13:21.845][NamedPipeClient][Info   ] Sending Version()...
[15:13:21.860][NamedPipeClient][Info   ] Received response for Version
[15:13:21.860][NamedPipeClient][Info   ] Sending MigrateApp()...
[15:13:21.876][NamedPipeClient][Info   ] Received response for MigrateApp
[15:11:58.283][BackendServer  ][Info   ] Started
[15:13:21.860][NamedPipeServer][Info   ] Version()
[15:13:21.876][Notifications  ][Info   ] Docker Desktop is starting...
[15:13:21.860][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:13:21.860][NamedPipeServer][Info   ] MigrateApp()
[15:13:21.876][NamedPipeServer][Info   ] MigrateApp done in 00:00:00.0156881.
[15:13:21.898][NamedPipeClient][Info   ] Sending Version()...
[15:13:21.898][NamedPipeClient][Info   ] Received response for Version
[15:13:21.898][NamedPipeClient][Info   ] Sending RegisterFileAssociations(c:\program files\docker\docker\docker for windows.exe)...
[15:13:21.898][NamedPipeServer][Info   ] Version()
[15:13:21.898][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:13:21.898][NamedPipeServer][Info   ] RegisterFileAssociations(c:\program files\docker\docker\docker for windows.exe)
[15:13:21.898][NamedPipeClient][Info   ] Received response for RegisterFileAssociations
[15:13:21.898][FileTypeRegistrar][Info   ] Registering file association for extension .ddvp
[15:13:21.913][NamedPipeClient][Info   ] Sending Version()...
[15:13:21.898][NamedPipeServer][Info   ] RegisterFileAssociations done in 00:00:00.
[15:13:21.913][NamedPipeClient][Info   ] Received response for Version
[15:13:21.913][NamedPipeClient][Info   ] Sending EnableVersionPack(default, Docker.Core.Settings)...
[15:13:21.913][NamedPipeServer][Info   ] Version()
[15:13:21.913][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:13:21.913][NamedPipeServer][Info   ] EnableVersionPack(default, Docker.Core.Settings)
[15:13:21.929][NamedPipeClient][Info   ] Received response for EnableVersionPack
[15:13:21.929][NamedPipeServer][Info   ] EnableVersionPack done in 00:00:00.0156894.
[15:13:21.976][NamedPipeClient][Info   ] Sending Version()...
[15:13:21.976][NamedPipeClient][Info   ] Received response for Version
[15:13:21.976][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[15:13:21.976][NamedPipeServer][Info   ] Version()
[15:13:21.976][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:13:21.976][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[15:13:21.997][PowerMode      ][Info   ] Stop
[15:13:21.998][HyperV         ][Info   ] Stop
[15:13:22.030][PowerShell     ][Info   ] Run script with parameters: -Stop True
[15:13:22.030][PowerShell     ][Info   ] Creating a Runspace Pool...
[15:13:22.808][NPS            ][Info   ] NPS User id created
[15:13:23.188][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[15:13:23.235][NPS            ][Info   ] NPS user ceated on: 6/21/2019 3:13:22 PM -07:00, last survey:  1/1/0001 12:00:00 AM +00:00
[15:13:24.091][HyperV         ][Info   ] Script started at 15:13:24.027
[15:13:27.589][HyperV         ][Info   ] Modules loaded at 15:13:27.589
[15:13:28.028][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:13:28.044][HyperV         ][Debug  ] [stop] took 00:00:06.0455902 to run
[15:13:28.044][OptimizeDisk   ][Info   ] Optimize
[15:13:28.044][PowerShell     ][Info   ] Run script...
[15:13:28.060][Moby           ][Info   ] Stop
[15:13:28.075][HyperVGuids    ][Info   ] Installing GUIDs...
[15:13:28.075][PowerMode      ][Info   ] Start
[15:13:28.075][HyperVGuids    ][Info   ] GUIDs installed
[15:13:28.075][Firewall       ][Info   ] Removing all existing rules...
[15:13:28.110][HyperV         ][Info   ] Create
[15:13:28.129][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[15:13:28.176][HyperV         ][Info   ] Script started at 15:13:28.176
[15:13:28.224][HyperV         ][Info   ] Modules loaded at 15:13:28.224
[15:13:28.260][Firewall       ][Info   ] All existing rules are removed.
[15:13:28.261][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[15:13:28.273][Firewall       ][Info   ] Opening ports for SMB...
[15:13:28.317][Firewall       ][Info   ] Ports are opened
[15:13:28.433][HyperV         ][Info   ] Creating Switch: DockerNAT...
[15:13:31.545][HyperV         ][Info   ] Switch created.
[15:13:31.858][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 
. Let's retry
[15:13:31.951][HyperV         ][Info   ] Hyper-V is running
[15:13:31.951][PowerMode      ][Info   ] Stop
[15:13:31.951][HyperV         ][Info   ] Stop
[15:13:31.951][PowerShell     ][Info   ] Run script with parameters: -Stop True
[15:13:32.014][HyperV         ][Info   ] Script started at 15:13:32.014
[15:13:32.045][HyperV         ][Info   ] Modules loaded at 15:13:32.045
[15:13:32.076][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:13:32.076][HyperV         ][Debug  ] [stop] took 00:00:00.1250023 to run
[15:13:32.076][OptimizeDisk   ][Info   ] Optimize
[15:13:32.076][PowerShell     ][Info   ] Run script...
[15:13:32.123][Moby           ][Info   ] Stop
[15:13:32.139][HyperV         ][Info   ] Destroy
[15:13:32.139][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[15:13:32.170][HyperV         ][Info   ] Script started at 15:13:32.170
[15:13:32.201][HyperV         ][Info   ] Modules loaded at 15:13:32.201
[15:13:32.217][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:13:32.217][HyperV         ][Info   ] Destroying Switch DockerNAT...
[15:13:32.389][NamedPipeServer][Error  ] Unable to execute Start: Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 
    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.ContainerEngine.Linux.DoDestroy(Boolean keepVolume) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 364
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 116
[15:13:33.045][NamedPipeClient][Error  ] Unable to send Start: Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

[15:13:33.045][Notifications  ][Error  ] Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

[15:13:33.092][NamedPipeClient][Info   ] Sending Version()...
[15:13:33.092][NamedPipeClient][Info   ] Received response for Version
[15:13:33.092][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\vzxzp1\AppData\Local\Temp\ gather -id D9597C1B-84F5-4FD7-9E8F-32A2EC7F0DB8/20190621151333, C:\Users\vzxzp1\AppData\Local\Temp\D9597C1B-84F5-4FD7-9E8F-32A2EC7F0DB8/20190621151333.zip)...
[15:13:33.092][NamedPipeServer][Info   ] Version()
[15:13:33.092][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:13:33.108][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\vzxzp1\AppData\Local\Temp\ gather -id D9597C1B-84F5-4FD7-9E8F-32A2EC7F0DB8/20190621151333, C:\Users\vzxzp1\AppData\Local\Temp\D9597C1B-84F5-4FD7-9E8F-32A2EC7F0DB8/20190621151333.zip)
[15:13:57.165][ErrorReportWindow][Info   ] Open logs




I tried to uninstall and then reinstall - the same error.  When uninstalling, I was trying to remove docker from everywhere and made sure all the network adapters (DockerNat) was removed.

Please help me get back to having docker.

**Comment by Geckex** [comment] 2019-11-28 08:46
Windows update - caused network issues - go into adapters (for docker the vEthernet DockerNAT) - check if you have option "sk-ndis lightweight filter", if so untick this. Restart docker.
