### ISSUE TITLE
Files in host volume that have special characters filenames, have the filename translated to ?'s in Linux container

### ISSUE THREAD

**Issue by immanuelnoel** [docker/for-win#986] opened 2017-08-08 05:55 UTC
Files in host (Windows) volume that have special characters filenames, have the filename translated to ?'s in Linux container

Repro:
1. Run a Linux container, eg, ubuntu, and mount the volume in Windows host
2. Place filename with test-öäü.txt in mounted volume and try view the same on the Linux container

### Expected behavior
Filename converted to test-??????.txt

### Actual behavior
Filename must be test-öäü.txt 

### Information
Windows 10 Host

**Comment by jasonbivins** [comment] 2017-08-08 15:25
Hi @immanuelnoel   Can you please share the commands you were using, along with a diagnostic ID?
I'd like to make sure I'm reproducing this the same way you are.

**Comment by friism** [comment] 2017-08-08 16:42
This is most like a samba issue: https://serverfault.com/a/124630/275

Idk if we can tweak the SMB parameters

**Comment by jasonbivins** [comment] 2017-08-08 19:01
I played around with this a bit more - Windows just doesn't like those characters.
``` C:\Mount>echo text text including tt-öäüt-öäüt-öäüt-öäü > test.txt

C:\Mount>type test.txt
text text including tt-öäüt-öäüt-öäüt-öäü ```

Opening test.txt by double clicking gives me this: 

![image](https://user-images.githubusercontent.com/28021664/29089511-78f44462-7c4a-11e7-8e4c-3b9f4438122c.png)

**Comment by jasonbivins** [comment] 2017-08-08 19:04
I'm even struggling with those characters here in the webform - see the ``` above, along with the blank space?  When i double click test.txt it looks like this 
![image](https://user-images.githubusercontent.com/28021664/29089511-78f44462-7c4a-11e7-8e4c-3b9f4438122c.png)

**Comment by Milania1** [comment] 2017-08-21 15:29
I just wanted to confirm that I have exactly the same issue with docker on Windows 10.

Steps to reproduce:

- Create an empty text file with non-ASCII characters, e.g. the mentioned `test-öäü.txt` at `C:\docker_filename-issue`.
- Run a container with a shared drive mounted to `C:\docker_filename-issue` and execute `ls`. Output on my system:
```
PS C:\Users> docker run -it -v c:/docker_filename-issue:/docker_filename-issue ubuntu
root@346afa6dd6bc:/# cd docker_filename-issue/
root@346afa6dd6bc:/docker_filename-issue# ls
test-??????.txt
root@346afa6dd6bc:/docker_filename-issue# exit
exit
PS C:\Users> docker -v
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by rn** [comment] 2018-03-12 17:22
I cannot reproduce this with Version 18.03.0-ce-rc1-win54 (16164) on Windows 10 Pro RS3 (build number 16299):
```
PS C:\test> New-Item  -Path test-öäü.txt


    Directory: C:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/03/2018     17:19              0 test-öäü.txt


PS C:\test> docker run --rm -v  C:\test:/test alpine ls -al /test
total 4
drwxr-xr-x    2 root     root             0 Mar 12 17:19 .
drwxr-xr-x    1 root     root          4096 Mar 12 17:19 ..
-rwxr-xr-x    1 root     root             0 Mar 12 17:19 test-öäü.txt
PS C:\test>
```
Since this issue is quite old, I'm also closing it. Please re-open if it is not fixed for you

**Closed by rn** 2018-03-12 17:22 UTC
Labels: area/linux, area/mounts, area/windows 10, status/1-acknowledged

**Comment by Milania1** [comment] 2018-03-13 18:15
@rn Thanks for testing this. If I use your steps, I get the same output as you. However, executing my own steps from above, the issue still exists. I tested with `Docker version 18.03.0-ce-rc1, build c160c73` on Windows 10 version 1709 (build number 16299.248).

I think the difference is that in your approach you output the result of the container directly and in my approach I first bash inside the container and generate the output from there. But I don't know why this is a problem.
