### ISSUE TITLE
Unable to mount C drive

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/for-win#950] opened 2017-07-21 21:51 UTC
Hello,

All was well and i have reset factory defaults and now the shared drives generate an error : 
```
[23:45:19.295][SambaShare     ][Error  ] Unable to mount C drive: container_linux.go:262: starting container process caused "exec: \"/usr/bin/nsenter1\": stat /usr/bin/nsenter1: no such file or directory"
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/usr/bin/nsenter1\": stat /usr/bin/nsenter1: no such file or directory".

[23:45:19.296][SambaShare     ][Info   ] Removing share C
[23:45:19.335][NamedPipeClient][Info   ] Received response for Mount
```

Diagnostic id : 203F4A72-5133-4562-8FD4-C497D1702906/2017-07-21_23-47-38

**Comment by Dargmuesli** [comment] 2017-07-25 21:38
Try the newest Edge build. Version 17.06.1-ce-rc1-win20 (12818). The issue is fixed for me there.

**Comment by sylvainmouquet** [comment] 2017-07-26 19:43
I have the problem with this version 
```
Version 17.06.1-ce-rc1-win20 (12818)
Channel: edge
28a0bb2
```

**Comment by sylvainmouquet** [comment] 2017-07-26 20:04
I have uninstalled docker, reboot and install edge version and it's working
https://github.com/docker/for-win/issues/690

**Comment by jasonbivins** [comment] 2017-07-26 20:59
hi @sylvainmouquet 
I'll go ahead and close this issue, but please let us know if it pops back up again

**Closed by jasonbivins** 2017-07-26 20:59 UTC

**Comment by Kevinrob** [comment] 2018-03-12 12:16
I had the same issue. It seems that the hyper-v VM become corrupted when changing CPU/memory settings. After a "reset to factory", it's working again 👍 .

**Comment by romamajestik** [comment] 2018-06-22 12:51
@Kevinrob красава!

**Comment by speller** [comment] 2019-06-02 03:20
Only reset to factory defaults worked for me to fix this issue.
