### ISSUE TITLE
Windows 10: Docker for Windows: unable to share drive

### ISSUE THREAD

**Issue by carljmosca** [docker/for-win#2549] opened 2018-09-05 13:35 UTC
Opening new issue because #690 is being ignored.

https://github.com/docker/for-win/issues/690

**Comment by Smilebags** [comment] 2018-09-06 01:58
This certainly seems to be the case. I've had the same issue and no resolution in the previous issue. It needs another look at.

**Comment by e-gautier** [comment] 2018-09-06 17:44
yay! waiting since 2 years that Docker for Windows works properly.

**Comment by mak003** [comment] 2018-09-07 07:59
After update the docker for windows to latest version(Docker version 18.06.1-ce, build e68fc7a). I saw the same issue. what kind of account  and password is required, I can't use my windows account to deal with it. windows really XXXX !

**Comment by lucallero** [comment] 2018-09-09 03:56
+1, same issue here, the workaround of creating a new account didn't work. I'm really trying to work on a Windows box, but it's hard. This is the type of thing that annoys, no error, no log, no solution simply doesn't work, and this with a simple feature of mount a persistent volume.
Look like the same issue too https://github.com/docker/for-win/issues/1801 https://github.com/docker/for-win/issues/690

**Comment by TylerSmall19** [comment] 2018-09-11 18:51
I am suffering from the same issue, and it would appear that I can get around this issue by using Git Bash for Windows.

I [installed Git Bash](http://www.techoism.com/how-to-install-git-bash-on-windows/) and ensured Docker was present, then inside of Git Bash I went into the directory of the file I was attempting to share:

`cd [dir]`

Next, I provided the file I was attempting to share via an absolute path with my docker run command:

`docker run -d -p 9260:9200 -v elasticsearch.yml:[copyPath]/elasticsearch.yml [imagePath]/elasticsearch:empty`

This allowed me to start a local Docker container with the image and volume provided. Hopefully this will work for someone else out there too?

Proof (`docker ps` output): 
`569bc7073cc5   path/elasticsearch:empty   "/run/entrypoint.sh"   10 minutes ago      Up 3 seconds        9300/tcp, 0.0.0.0:9260->9200/tcp   [name]`

**Comment by dnsdhrj** [comment] 2018-09-21 04:02
@mak003 I did a factory reset, and it worked!

Hoping it might help to fix issue, here's my situation:
1. Updated to 18.06.1-ce-win73 (19507)
2. Switched to Linux container mode (didn't use Linux container nor shared drives before)
3. Shared drives didn't work
4. After doing factory reset and applying [this solution](https://github.com/docker/for-win/issues/690#issuecomment-373017897), shared drive works.

**Comment by willnil** [comment] 2018-10-23 15:13
did every suggested workarounds (includ. the factory reset, create a new user, uninstall and reinstall ...) but it still didn't work for me

**Comment by PsychoXIVI** [comment] 2018-11-29 15:22
Still not working :C

**Comment by nngo** [comment] 2019-02-21 14:57
I encountered a similar issues this morning running Docker Desktop Community on my Windows 10 Pro.
All of a sudden, my `C:` Drive was no longer shared. I went into Settings > Shared Drives and the `Shared` checkbox for my `C Drive` was unchecked, I checked it and clicked `Apply`, it prompted me for my password but the setting did NOT persist. I repeated the above steps a few more times and the shared setting would NOT take into effect. I then restarted Docker Desktop and repeated a few more times in frustration and the setting would not take into effect and I was not able to mount a volume for my Docker container. I rebooted. The shared setting was unchecked. I tried again and it failed and I was still unable to mount a volume. I restarted Docker Desktop again, this time, I gave it an extra few minutes after it said that it was done restarting. Then I went into settings and checked the box to share my `C:` drive, entered my password yet again... and it finally took the setting and I am able to mount the volume from my `C:` drive. Somehow, I got lucky.

I am currently running Docker Desktop CE
```
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

Engine: 18.09.2
Compose: 1.23.2
Machine: 0.16.1
```

**Comment by topikettunen** [comment] 2019-03-07 08:24
+1 Just encountered the same issue as @nngo  with the same versions. But I haven't been able to share my `C:` drive.

**Comment by HBouch** [comment] 2019-04-22 09:35
Making sure this issue is getting the attention it needs :

- Windows 10 Enterprise, I have admin privileges with my account.
- Docker version 18.09.3, build 774a1f4

It has been ages since I'm trying to fix it, but no luck ...

**Comment by LoicHa** [comment] 2019-04-24 10:12
Try this, worked for me 

![image](https://user-images.githubusercontent.com/28562111/56651840-46272000-668a-11e9-99d8-eaad3280d71d.png)

**Comment by djs55** [comment] 2019-05-03 10:15
To understand what's going on we need to have a look at the logs after the drive sharing failure has happened.

If you can reproduce the problem, it would be really helpful if you:
1. could reproduce it
2. then upload a diagnostic report (from the whale menu -> Diagnose and Feedback ... -> (wait for a while) -> Upload)
3. then quote the diagnostic id in a  comment.

Thanks for your help!

**Comment by hallen93** [comment] 2019-05-09 09:50
I'm having the same issue. Attached is the log from when I try to share the drive.

`[11:49:52.302][SambaShare     ][Info   ] Removing share "C"
[11:49:52.336][SambaShare     ][Info   ] Mount C
[11:49:52.460][Cmd            ][Info   ] Den delade resursen finns inte.
[11:49:52.460][Cmd            ][Info   ] Du kan f† mer hj„lp genom att skriva NET HELPMSG 2310.
[11:49:52.463][SambaShare     ][Info   ] "C" is not shared
[11:49:52.463][SambaShare     ][Info   ] Creating share "C:" as "C" with Full Control to "Administratör"
[11:49:52.532][Cmd            ][Info   ] C delades.
[11:49:52.573][Cmd            ][Info   ] Resursnamn              C
[11:49:52.573][Cmd            ][Info   ] S”kv„g                  C:\
[11:49:52.573][Cmd            ][Info   ] Kommentar               
[11:49:52.573][Cmd            ][Info   ] Max antal anv„ndare     Ingen begr„nsning
[11:49:52.573][Cmd            ][Info   ] Anv„ndare               
[11:49:52.573][Cmd            ][Info   ] Cachelagring            Cachelagring har inaktiverats
[11:49:52.574][Cmd            ][Info   ] Beh”righet              JHAL-ZBOOK\Administrat”r, FULL
[11:49:52.574][Cmd            ][Info   ] Kommandot har utf”rts.
[11:49:52.577][SambaShare     ][Info   ] "C" is shared
[11:49:52.578][SambaShare     ][Info   ] Username: Administratör
[11:49:52.578][SambaShare     ][Info   ] Host IP: 10.0.75.1
[11:49:52.578][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=JHAL-ZBOOK,sec=ntlmsspi
[11:49:52.634][SambaShare     ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: Ett eller flera fel har uppstått. ---> Newtonsoft.Json.JsonReaderException: Error parsing undefined value. Path '', line 1, position 2.
   vid Newtonsoft.Json.JsonTextReader.ParseUndefined()
   vid Newtonsoft.Json.JsonTextReader.ParseValue()
   vid Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   vid Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   vid Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   vid Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   vid Docker.HttpOverStream.HttpClientExtensions.<ParseResponseBody>d__4`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Docker.HttpOverStream.HttpClientExtensions.<Post>d__3`1.MoveNext()
   --- Slut på stackspårning för interna undantag ---
   vid System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   vid System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   vid Docker.Backend.LifecycleClient.Mount(MountRequest req)
   vid Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Internt undantag #0) Newtonsoft.Json.JsonReaderException: Error parsing undefined value. Path '', line 1, position 2.
   vid Newtonsoft.Json.JsonTextReader.ParseUndefined()
   vid Newtonsoft.Json.JsonTextReader.ParseValue()
   vid Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   vid Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   vid Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   vid Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   vid Docker.HttpOverStream.HttpClientExtensions.<ParseResponseBody>d__4`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Docker.HttpOverStream.HttpClientExtensions.<Post>d__3`1.MoveNext()<---

[11:49:52.634][SambaShare     ][Info   ] Removing share "C"
[11:49:52.666][NamedPipeClient][Info   ] Received response for filesharing/mount
[11:49:52.666][NamedPipeServer][Info   ] filesharing/mount done in 00:00:00.6528634.
[11:49:52.671][TrackingSettings][Info   ] Crash report and usage statistics are enabled
[11:49:52.674][NamedPipeClient][Info   ] Sending app/version()...
[11:49:52.674][NamedPipeClient][Info   ] Received response for app/version
[11:49:52.674][NamedPipeClient][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[11:49:52.674][NamedPipeServer][Info   ] app/version()
[11:49:52.674][NamedPipeServer][Info   ] app/version done in 00:00:00.
[11:49:52.675][NamedPipeServer][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[11:49:52.678][PowerShell     ][Info   ] Run script...
[11:49:52.717][NamedPipeClient][Info   ] Received response for disk/get-size
[11:49:52.718][NamedPipeClient][Info   ] Sending app/version()...
[11:49:52.718][NamedPipeClient][Info   ] Received response for app/version
[11:49:52.718][NamedPipeClient][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[11:49:52.717][NamedPipeServer][Info   ] disk/get-size done in 00:00:00.0420602.
[11:49:52.718][NamedPipeServer][Info   ] app/version()
[11:49:52.718][NamedPipeServer][Info   ] app/version done in 00:00:00.
[11:49:52.719][NamedPipeServer][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[11:49:52.719][PowerShell     ][Info   ] Run script...
[11:49:52.757][NamedPipeClient][Info   ] Received response for disk/get-size
[11:49:52.757][NamedPipeServer][Info   ] disk/get-size done in 00:00:00.0380601.
`

**Comment by pamoller** [comment] 2019-05-26 11:08
Rentered my changed windows password after "reset to factory defualuts" solved my problem.

**Comment by lucallero** [comment] 2019-05-26 14:28
I think the problem was related to the way windows deal with virtual networks, just a guess, I'm not sure. The point is that after reset/reinstall windows :( things worked.

**Comment by HBouch** [comment] 2019-05-26 15:32
> I think the problem was related to the way windows deal with virtual networks, just a guess, I'm not sure. The point is that after reset/reinstall windows :( things worked.

Are you on Windows 10 Enterprise ?

**Comment by lucallero** [comment] 2019-05-26 21:22
![image](https://user-images.githubusercontent.com/4185387/58387328-3da46b00-7fe3-11e9-93f1-a073dae6654d.png)

**Comment by lucallero** [comment] 2019-05-26 21:23
> > I think the problem was related to the way windows deal with virtual networks, just a guess, I'm not sure. The point is that after reset/reinstall windows :( things worked.
> 
> Are you on Windows 10 Enterprise ?

![image](https://user-images.githubusercontent.com/4185387/58387333-514fd180-7fe3-11e9-8d02-d9c8a74bd316.png)

**Comment by HBouch** [comment] 2019-05-26 21:35
> > > I think the problem was related to the way windows deal with virtual networks, just a guess, I'm not sure. The point is that after reset/reinstall windows :( things worked.
> > 
> > 
> > Are you on Windows 10 Enterprise ?
> 
> ![image](https://user-images.githubusercontent.com/4185387/58387333-514fd180-7fe3-11e9-8d02-d9c8a74bd316.png)

Yeah, I think my firm blocks some stuff using the group policy, even if firewall rules don't.
Docker on Win 10 Pro would work just fine.

**Comment by DawnBreather** [comment] 2019-05-28 19:06
> Rentered my changed windows password after "reset to factory defualuts" solved my problem.

Yup, had to do the same to make things **work**.
_re-entering the credentials on checking / unchecking the the drive didn't help_

**Comment by huberchrigu** [comment] 2019-06-12 08:44
I had the same log message as @hallen93. It looks like there is an issue with encoding, special characters in the computer/domain or user name (like "ü" in my case) are not encoded correctly. After renaming my computer to English characters only, it worked even without prompting me for the password.

**Comment by vladymyr-ca** [comment] 2019-07-04 16:31
"Reset to factory defaults" resolved this issue for me

**Comment by tomaziniale** [comment] 2019-07-05 19:57
I had this issue for the first time here, diagnostic ID:
DF561E4B-A943-4541-8000-E3AFE0B844FA/20190705125012

from the logs
```
[12:33:16.344][SambaShare     ][Error  ] Unable to mount D drive: 10.0.75.1 (10.0.75.1:445) open
rm: cannot remove '/d': Is a directory
rm: cannot remove '/D': No such file or directory
umount: /host_mnt/d: not mounted.
mount.cifs kernel mount options: ip=10.0.75.1,unc=\\10.0.75.1\D,noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,sec=ntlmsspi,user=myuseraccount,domain=DOMAIN,pass=***
ln: failed to create symbolic link '/d/d': File exists

[12:33:16.345][SambaShare     ][Info   ] Removing share D
[12:33:16.393][SambaShare     ][Info   ] Creating share "D:\" as "D" with Full Control to "DOMAIN\myuseraccount"
[12:33:16.467][Cmd            ][Info   ] D was shared successfully.
```

**Comment by ikarus-999** [comment] 2019-07-08 05:30
No answer if unset password windows10 pro...

**Comment by Wael3bbas** [comment] 2019-07-31 12:30
It works with me after clicking in `Reset Credentials ` under `Shared Drivers` and sharing the driver again  and enter username and password.

I think the issue was changing user password.

**Comment by kanpeki** [comment] 2019-08-05 15:05
Enabling Smb protocol fixed it for me. (run Set-SmbServerConfiguration -EnableSMB2Protocol $true in Powershell)

**Comment by HBouch** [comment] 2019-08-07 15:30
> Enabling Smb protocol fixed it for me. (run Set-SmbServerConfiguration -EnableSMB2Protocol $true in Powershell)

Using Windows 10 Enterprise Edition ?

**Comment by RaphaelSilva** [comment] 2019-08-08 20:15
I reset to factory defaults before share my drive D:

Running this command in a supervisord PowerShell

Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Public

Then, I shared my drive D and you run the command again:
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private

Done! Now the sharing is able to see the host folder

**Comment by JettJones** [comment] 2019-10-01 00:00
In my case the workaround was to make a local user, and use those credentials to share my drive. My main user is from an active directory domain, which I'm guessing is not supported.  Many logs follow...

A failed login with my domain account:
```
[16:30:39.062][SharedDrivesSettings][Info   ] Apply shared drive settings
[16:30:39.066][NamedPipeClient   ][Info   ] Sending app/version()...
[16:30:39.070][NamedPipeClient   ][Info   ] Received response for app/version
[16:30:39.070][NamedPipeClient   ][Info   ] Sending filesharing/mount(All, C, MYWORKDOMAIN\jettjones:**********, Docker.Core.Settings)...
[16:30:39.067][NamedPipeServer   ][Info   ] app/version()
[16:30:39.067][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[16:30:39.071][NamedPipeServer   ][Info   ] filesharing/mount(All, C, MYWORKDOMAIN\jettjones:**********, Docker.Core.Settings)
[16:30:39.071][SambaShare        ][Info   ] Mount C
[16:30:39.260][Cmd               ][Info   ] This shared resource does not exist.
[16:30:39.260][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:39.264][SambaShare        ][Info   ] "C" is not shared
[16:30:39.264][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "MYWORKDOMAIN\jettjones"
[16:30:39.383][Cmd               ][Info   ] C was shared successfully.
[16:30:39.461][Cmd               ][Info   ] Share name        C
[16:30:39.461][Cmd               ][Info   ] Path              C:\
[16:30:39.461][Cmd               ][Info   ] Remark            
[16:30:39.461][Cmd               ][Info   ] Maximum users     No limit
[16:30:39.462][Cmd               ][Info   ] Users             
[16:30:39.462][Cmd               ][Info   ] Caching           Caching disabled
[16:30:39.462][Cmd               ][Info   ] Permission        MYWORKDOMAIN\jettjones, FULL
[16:30:39.462][Cmd               ][Info   ] The command completed successfully.
[16:30:39.467][SambaShare        ][Info   ] "C" is shared
[16:30:39.528][SambaShare        ][Info   ] Username: jettjones
[16:30:39.528][SambaShare        ][Info   ] Host IP: 10.0.75.1
[16:30:39.528][SambaShare        ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=MYWORKDOMAIN,sec=ntlmsspi
[16:30:39.548][Moby              ][Info   ] [   91.571644] Status code returned 0xc000006d STATUS_LOGON_FAILURE
[16:30:39.553][Moby              ][Info   ] [   91.576957] CIFS VFS: Send error in SessSetup = -13
[16:30:39.559][Moby              ][Info   ] [   91.581935] CIFS VFS: cifs_mount failed w/return code = -13
[16:30:39.566][SambaShare        ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: One or more errors occurred. ---> Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Inner Exception #0) Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()<---

[16:30:39.566][SambaShare        ][Info   ] Removing share "C"
[16:30:39.639][SambaShare        ][Info   ] Mount C
[16:30:39.799][Cmd               ][Info   ] This shared resource does not exist.
[16:30:39.799][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:39.804][SambaShare        ][Info   ] "C" is not shared
[16:30:39.804][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "jettjones"
[16:30:39.872][Cmd               ][Info   ] System error 1332 has occurred.
[16:30:39.874][Cmd               ][Info   ] No mapping between account names and security IDs was done.
[16:30:39.878][SambaShare        ][Error  ] Failed to create share "C:" as "C" with Full Control to "jettjones" with code: 2
[16:30:39.933][Cmd               ][Info   ] This shared resource does not exist.
[16:30:39.933][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:39.938][NamedPipeClient   ][Info   ] Received response for filesharing/mount
[16:30:39.937][SambaShare        ][Info   ] "C" is not shared
[16:30:39.937][NamedPipeServer   ][Info   ] filesharing/mount done in 00:00:00.8659979.`
```

Here is the successful login with the local account:

```
[16:30:50.820][MountCredentialAsker][Info   ] Storing credentials: LOCALHOST\Jett:***********
[16:30:50.828][NamedPipeClient   ][Info   ] Sending app/version()...
[16:30:50.829][NamedPipeClient   ][Info   ] Received response for app/version
[16:30:50.829][NamedPipeServer   ][Info   ] app/version()
[16:30:50.832][NamedPipeClient   ][Info   ] Sending filesharing/mount(All, C, LOCALHOST\Jett:**********, Docker.Core.Settings)...
[16:30:50.829][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[16:30:50.834][NamedPipeServer   ][Info   ] filesharing/mount(All, C, LOCALHOST\Jett:**********, Docker.Core.Settings)
[16:30:50.834][SambaShare        ][Info   ] Mount C
[16:30:50.991][Cmd               ][Info   ] This shared resource does not exist.
[16:30:50.992][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:50.996][SambaShare        ][Info   ] "C" is not shared
[16:30:50.996][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "LOCALHOST\Jett"
[16:30:51.061][Cmd               ][Info   ] System error 1332 has occurred.
[16:30:51.061][Cmd               ][Info   ] No mapping between account names and security IDs was done.
[16:30:51.066][SambaShare        ][Error  ] Failed to create share "C:" as "C" with Full Control to "LOCALHOST\Jett" with code: 2
[16:30:51.125][Cmd               ][Info   ] This shared resource does not exist.
[16:30:51.125][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:51.129][SambaShare        ][Info   ] "C" is not shared
[16:30:51.129][SambaShare        ][Info   ] Mount C
[16:30:51.280][Cmd               ][Info   ] This shared resource does not exist.
[16:30:51.280][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:30:51.285][SambaShare        ][Info   ] "C" is not shared
[16:30:51.285][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "Jett"
[16:30:51.402][Cmd               ][Info   ] C was shared successfully.
[16:30:51.468][Cmd               ][Info   ] Share name        C
[16:30:51.468][Cmd               ][Info   ] Path              C:\
[16:30:51.468][Cmd               ][Info   ] Remark            
[16:30:51.468][Cmd               ][Info   ] Maximum users     No limit
[16:30:51.469][Cmd               ][Info   ] Users             
[16:30:51.469][Cmd               ][Info   ] Caching           Caching disabled
[16:30:51.469][Cmd               ][Info   ] Permission        JETT-LAPTOP\Jett, FULL
[16:30:51.469][Cmd               ][Info   ] The command completed successfully.
[16:30:51.474][SambaShare        ][Info   ] "C" is shared
[16:30:51.479][SambaShare        ][Info   ] Username: Jett
[16:30:51.479][SambaShare        ][Info   ] Host IP: 10.0.75.1
[16:30:51.479][SambaShare        ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=JETT-LAPTOP,sec=ntlmsspi
[16:30:51.508][NamedPipeClient   ][Info   ] Received response for filesharing/mount
[16:30:51.508][GoBackendProcess  ][Info   ] error CloseWrite to: The pipe is being closed.
[16:30:51.508][NamedPipeServer   ][Info   ] filesharing/mount done in 00:00:00.6746499.
```


In the windows event viewer (eventvwr.msc) during the failed login, I see this:

```
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/30/2019 4:29:51 PM
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      Jett-Laptop
Description:
An account failed to log on.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		jettjones
	Account Domain:		MYWORKDOMAIN

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC0000064

Process Information:
	Caller Process ID:	0x0
	Caller Process Name:	-

Network Information:
	Workstation Name:	-
	Source Network Address:	10.0.0.2
	Source Port:		53994

Detailed Authentication Information:
	Logon Process:		NtLmSsp 
	Authentication Package:	NTLM
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0
```
And if there are questions, I did reset docker-for-windows and restart my machine, before trying a second user.

The login failure event is not appearing in the docker UI, so there's one issue there. The failure itself may be caused by that missing security ID.  But that's guesswork, so just leaving this here in case it helps someone.

**Comment by bgever** [comment] 2019-10-04 03:27
All these didn't work:
 - Resetting to factory defaults.
 - Reset credentials.
 - `Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Public`

The only solution was to create a new local account with `mmc`:
 - `WinKey+R`, `msc`, OK
 - File | Add/Remove Snap-in...
 - Select _Local Users and Groups_ then **Add >**
 - _Local Computer_, then **Finish**, then **OK**
 - Open _Local Users and Groups (Local)_, then _Users_
 - Action | New User...
 - Enter _User name_ and passwords
 - Untick _User must change password at next logon_
 - Tick _User cannot change password_
 - Tick _Password never expires_
 - Double-click the created user
 - Tab _Member of_ and **Add...**
 - Enter `Administrators` and click **Check Names**
 - OK to save
 - In File explorer go to the folder you'd like to map as a volume, and add the user and give them full control

**Comment by RiskofStorm** [comment] 2019-10-21 04:59
I guess it's better to raise server on linux rather to mess up with win10. Idk why LinuxOnWindows is needed to EEE (because docker won't installs without headacke. I actually don't even bother to install docker via LoW. low chanse it would work)?

**Comment by cakelly** [comment] 2019-10-21 16:51
If your firewall is configured to allow traffic on the Hyper-V network, and your drive is shared in "Shared Drives", this does work.  There are lots of layers in Windows networking, as with ogres and onions. But with patience, it can be coaxed into working.  I didn't have to add users, but I did move the data I wanted to share into the Public user space.

**Comment by danielfeng7171** [comment] 2019-11-13 04:11
> All these didn't work:
> 
> * Resetting to factory defaults.
> * Reset credentials.
> * `Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Public`
> 
> The only solution was to create a new local account with `mmc`:
> 
> * `WinKey+R`, `msc`, OK
> * File | Add/Remove Snap-in...
> * Select _Local Users and Groups_ then **Add >**
> * _Local Computer_, then **Finish**, then **OK**
> * Open _Local Users and Groups (Local)_, then _Users_
> * Action | New User...
> * Enter _User name_ and passwords
> * Untick _User must change password at next logon_
> * Tick _User cannot change password_
> * Tick _Password never expires_
> * Double-click the created user
> * Tab _Member of_ and **Add...**
> * Enter `Administrators` and click **Check Names**
> * OK to save
> * In File explorer go to the folder you'd like to map as a volume, and add the user and give them full control

This solution worked for me! Thanks!

**Comment by paduchuriramesh** [comment] 2019-11-19 06:03
This one worked for me. 

https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/

**Comment by jjborie** [comment] 2019-12-10 13:41
Hello,

I found that adding your local user to Remote Desktop User group do the trick for me no need admin permission.

Best

**Comment by jlu1202** [comment] 2019-12-17 21:16
I had the same issue with my AD account after changing the password so I did a "Reset to factory default" and was able to re-share my C drive with my AD account again.

**Comment by stephen-turner** [comment] 2020-02-11 14:22
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.

**Closed by stephen-turner** 2020-02-11 14:22 UTC

**Comment by leonildojuniorzup** [comment] 2020-03-01 11:00
> After update the docker for windows to latest version(Docker version 18.06.1-ce, build e68fc7a). I have the same issue. when I want to share C disk, a window came out. ask for password. I can't use my windows account to deal with it. what kind of account and password is required?
> 
> Anyone who have the same issue, Please follow this way: Settings→Reset→Reset to factory default
> Maybe it can solves your problem, At least works for me.
> Anyway, choose Microsoft Windows is my biggest mistake!


Thank you very much mak003, your tip worked well for me!
