### ISSUE TITLE
Docker hv-sock proxy is not reachable - diag id = 14203433-9F27-432F-9AE2-629299ADF26A/2017-01-23_13-13-12

### ISSUE THREAD

**Issue by mikenhg5** [docker/for-win#415] opened 2017-01-23 13:21 UTC
### Expected behavior

Took latest version as at 23rd Jan 2017, having had Docker working fine previously

Latest version required a reboot, expected Docker to start OK

### Actual behavior

Docker fails to start
[Docker Error Log.txt](https://github.com/docker/for-win/files/723668/Docker.Error.Log.txt)

Error message

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

Diagnostic id = 14203433-9F27-432F-9AE2-629299ADF26A/2017-01-23_13-13-12
Uploaded this to Git Hub

### Steps to reproduce the behavior

  1. Downloaded version
Version 1.13.0 (9795)
Channel: Stable
0c6d765

  2. Rebooted Windows 10

nb: I had NO trouble previously when running Docker earlier version

I've used Kitematic to stop/start containers and they ran happily

Hyper-V is installed and running (as previous reqts)

**Comment by earlcherry** [comment] 2017-01-24 04:19
the same problem

**Comment by dgageot** [comment] 2017-01-25 05:53
Closing as it's a duplicate of #406

**Closed by dgageot** 2017-01-25 05:53 UTC
