### ISSUE TITLE
docker run hello-world "could not read CA certificate"

### ISSUE THREAD

**Issue by pilsytski** [docker/for-win#3999] opened 2019-05-28 19:27 UTC
After Installation steps from Docker site,Docker on Windows 10 Pro Education
 1.Installed Success.
 2.docker --version     
Docker version 18.09.2, build 6247962
3.docker-machine --version
docker-machine.exe version 0.16.1, build cce350d7
4.docker-compose --version
docker-compose version 1.23.2, build 1110ad01
5.But when i try start simple container: docker run hello-world
I got:
could not read CA certificate "C:\\Users\\User\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\User\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.

I check my path,and files doesn't exist there.
What i did wrong?Or give me advice how resolve this issue.
Sanx

**Comment by scarabetta** [comment] 2019-05-29 06:05
I had the same problem. The files are in a different path (`C:\Users\{user}\.docker\machine\certs`) but I don't know why. I created the `\machine\default` folder and copied the certs from there. In my case this solved the "could not read..." error, albeit I now have a connection refused error with `https://192.168.99.100:2376` that I'm still trying to fix. 

If you manage to make it work, let me know!

**Comment by mikeparker** [comment] 2019-05-29 15:25
Duplicate of https://github.com/docker/for-win/issues/3314

**Closed by mikeparker** 2019-05-29 15:25 UTC
