### ISSUE TITLE
Create and Download not working, if I pull the image manually then I can create.

### ISSUE THREAD

**Issue by rrsalas** [docker/for-win#6233] opened 2020-04-05 13:45 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonberger** [comment] 2020-04-05 14:11
I have the same problem. There is some more detail in a mac issue https://github.com/docker/for-mac/issues/3493
All with this problem have german vodafone cable internet with a Fritzbox router.

Here my diagnostic ID:
2C720C5D-E08D-4E09-9317-4FB9DA3F1162/20200405141024

**Comment by smarwei** [comment] 2020-04-06 07:00
Do you also have problems logging in from command line? I get the same error. If I switch to windows containers it works though. 

My provider is Unitymedia (which is now Vodafone) and I also use their FritzBox.

**Comment by simonberger** [comment] 2020-04-06 19:59
@smarwei Yes indeed docker login results in the same error message. Really strange. The login via docker desktop works without a problem.

**Comment by stephen-turner** [comment] 2020-04-07 14:05
If it's being blocked by the router, I don't see what we can do. It sounds like you need to consult the manufacturers of the FritzBox.

**Comment by simonberger** [comment] 2020-04-07 14:21
You do not follow the reports closely enough.
The Mac daemon works in the very same network. Also for example the login works in the docker client but not the console. This is a problem in the software. But it seems to be caused by a special network behavior.
One reason we thought about could be IPv4 / IPv6 handling. Vodafone cable seems to no longer use a native IPv4 address. But Iam no expert and do not know how that could effect docker.

**Comment by stephen-turner** [comment] 2020-04-08 09:23
This comment in the for-mac issue suggests that a FritzBox upgrade fixed it: https://github.com/docker/for-mac/issues/3493#issuecomment-610594332

**Comment by simonberger** [comment] 2020-04-08 09:48
Yes one of around four which reported the issue had fixed it. But we have not enough parameters. For example if he has a changed internet plan or other changes.
No matter if this is fixable by any router or provider setting. There seems to exist a worse network handling of the windows daemon compared to the mac one not handling all states.

**Comment by jonas-jonas** [comment] 2020-04-08 16:30
I have the Fritzbox 6591 from Vodafone using internet via TP-Link DLAN adapters (LAN). Same issue. Do you have a workaround? I'm on a PC, so I can't use WIFI.

**Comment by simonberger** [comment] 2020-04-08 16:47
I am also willing to provide any information or test anything that could help. Currently I can use my macbook but that should just be a temporary non optimal work around.

**Comment by BeatDirector** [comment] 2020-04-08 16:58
@jonas-jonas before I got my new Fritzbox, I couldn't pull any image from docker over LAN connection. My workaround was using a WIFI stick. Nothing else worked. I tried to disable IPv6, reset my Fritzbox, change LAN cable and lots of other thing but nothing worked. You could contact your ISP and replace your Fritzbox. But feel free and try a full reset first. Maybe it works for you. Good luck

**Comment by stephen-turner** [comment] 2020-04-08 17:15
If it broke since upgrading to 2.2.3.0, then this build might be worth trying: [win](https://download-stage.docker.com/win/edge/44007/Docker%20Desktop%20Installer.exe) and [mac](https://download-stage.docker.com/mac/edge/44007/Docker.dmg). Although IPv6 is not fully supported, this fixes it in some cases.

If you do try it, then please let us know whether it worked. Unfortunately, if it doesn't fix it, then I'm not sure there's any more we can do: it does look like it's something specific to the Fritzbox.

**Comment by jonas-jonas** [comment] 2020-04-08 19:52
@stephen-turner thanks for the suggestion. Unfortunately that doesn't solve the issue for me. For clarity, [1] is my `$ docker.exe version` output (maybe you could check if that's the latest version, but it looks like it).

@BeatDirector I might have some time to reset my FritzBox this weekend. So will see if that fixes it.

[1]
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true
```

**Comment by simonberger** [comment] 2020-04-09 07:45
It currently works for me. The newest version did not help, but I did a restart of the Fritzbox and since this time I can pull. No Firmware updates or similar.
You might try as well @jonas-jonas

**Comment by jonas-jonas** [comment] 2020-04-09 09:32
@simonberger wow. That worked for me too. Sometimes it's the simple "computer guy tricks" that help! Thanks.

**Comment by stephen-turner** [comment] 2020-04-09 10:07
Thanks for the reports, everyone. It looks like the problem is in the FritzBox not in Docker, and that a restart of the FritzBox fixes it, so I'm going to close this ticket.

**Closed by stephen-turner** 2020-04-09 10:07 UTC
