### ISSUE TITLE
Unable to connect MobyLinuxVm

### ISSUE THREAD

**Issue by sudipto92** [docker/for-win#1841] opened 2018-03-16 06:55 UTC
### Actual behavior
 It needs to connect and i should able to login VM

### Steps to reproduce the behavior

  1. Open Hyper-V Manager
  2. Right Click on MobyLinuxVM and then click Connect

**Comment by jasonbivins** [comment] 2018-03-20 01:55
Hi @sudipto92    We actually disable most of the integration services for the MobyLinuxVM - you shouldn't be able to connect to it by design.
What were you trying to accomplish?

**Comment by sudipto92** [comment] 2018-03-20 02:10
I want to start daemon in mobylinuxvm which will connect with portainer

**Comment by pgayvallet** [comment] 2018-03-20 08:04
You can enter the VM via `docker run -it --privileged --pid=host justincormack/nsenter1 /bin/sh`

**Comment by rn** [comment] 2018-03-20 10:37
Closing as this is by design and a workaround was suggested.

**Closed by rn** 2018-03-20 10:37 UTC
Labels: area/windows 10, kind/How-to, kind/feature, status/0-wont-fix

**Comment by sudipto92** [comment] 2018-03-22 05:12
@pgayvallet is it will connect with MobyLinuxVm??

**Comment by rustyx** [comment] 2019-06-15 12:58
@jasonbivins how do you disable it? (just curious)
