### ISSUE TITLE
Docker doesn't start up anymore in Windows 10.

### ISSUE THREAD

**Issue by cshift** [docker/for-win#200] opened 2016-11-03 17:36 UTC
### Expected behavior

Docker Daemon stopped starting up with Windows 10, or starts up when Reset is clicked in Daemon GUI

### Actual behavior

Docker doesn't start. Additionally when "Reset" is clicked in the Daemon Gui the following error comes up.  Diagnostic ID is below

> Unable to start: 'MobyLinuxVM' failed to change state.
>
>The operation is not supported.
>at <ScriptBlock>, <No file>: line 340
>at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
>at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>at Docker.Core.Backend.BackendClient.Start(Settings settings)
>at Docker.Actions.<>c__DisplayClass24_0.<RestartVm>b__0()
> at Docker.Core.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
> 

### Information

  - Diagnostic ID:  1C60540D-15CB-4254-A29C-895A08F4EC28/2016-11-03_13-30-12
### Steps to reproduce the behavior
Docker won't start

**Comment by rneugeba** [comment] 2016-11-04 10:17
Hi, thanks for your report. Could you try the latest Beta (https://download.docker.com/win/beta/InstallDocker.msi). It will have better diagnostics for us to take a look at.
Thanks

**Comment by WybrenKoelmans** [comment] 2016-11-04 20:11
Same error here, error report:

8771104C-C6E8-4E07-BA17-ED445FF38A02/2016-11-04_21-11-16

let me know how I can help

**Comment by geocine** [comment] 2016-11-09 16:51
please check my error report

B4D5EF30-0ACB-47BA-B4CF-717F132D355A/2016-11-10_00-49-56

**Comment by simonferquel** [comment] 2016-11-10 16:16
@WybrenKoelmans I see that you have a network device with 10.0.75.1 (which is the default IP of the network we setup between Windows and the Linux VM). Can you change the network settings in Docker for Windows to change the subnet address to a non conflicting one ?

**Comment by WybrenKoelmans** [comment] 2016-11-10 18:54
@simonferquel Thank you very much, it was indeed the issue. I had created a Virtual Switch in Hyper-V which apparently defaults to the same IP. Would it be a good idea to pick a different IP for as a default for Docker?

**Comment by rneugeba** [comment] 2016-11-11 16:55
Thanks for reporting back and glad that your issue is solved.

The IP address on your external switch is 10.0.75.1 and it would normally get this from a DHCP server or similar on your network. If I create an external switch on one of my systems I get a 172.16.x.x address which is what we use on the wireless. If I create I create an internal Switch it gets an address from the `169.254.0.0'/16` subnet which is "reserved" for self assigned IP addresses. So this would be the expected behaviour.

Since we can't really control which IP addresses are used we provide the override in the UI. Since this worked for you I'm closing this issue.

@geocine your issue seems different (different error message). Could you open a separate issue? Thanks

**Closed by rneugeba** 2016-11-11 16:55 UTC
Labels: area/network, status/0-triage
