### ISSUE TITLE
Resizing window is inconsistent - often requires two clicks

### ISSUE THREAD

**Issue by jl8n** [docker/for-win#12836] opened 2022-07-12 07:10 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2402027D-A164-4EC1-A3C0-B8C0968E8741/20220712065109

Windows 11 Desktop

### Actual behavior

Inconsistent behavior when trying to resize the desktop window from any of the four sides OR from the top-left, top-right, or bottom-left corner:

- shrinking the window is only possible every-other click
- growing the window is only possible by first shrinking the window

Resizing the window from the bottom-right corner always works correctly on the first try

https://user-images.githubusercontent.com/18693995/178430060-251a305c-b7c0-4fcc-ad40-e0e2d561c83c.mp4

### Expected behavior

Resizing the window is consistent regardless of the side/corner clicked

**Comment by nicks** [comment] 2022-07-12 14:08
Thanks for reporting! I'm going to de-dupe this against https://github.com/docker/for-win/issues/12816 to centralize the discussion there. (They're both a regression in the underlying window-management library we were using, and hopefully will be fixed in the next release.)

**Closed by nicks** 2022-07-12 14:08 UTC
