### ISSUE TITLE
Error “git cat-file: could not get object info” in docker container after Docker desktop update 2.2.0.4 on win 10

### ISSUE THREAD

**Issue by s-s-popov** [docker/for-win#6017] opened 2020-03-13 22:34 UTC
After update Docker desktop to 2.2.0.4 on win 10 I have had error "git cat-file: could not get object info" in container. Before update everething was ok.

Docker-compose.yml:
```
version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
```     

Dockerfile:
```
FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["flask", "run"]
```

git log:
```
root@97cb634b1d22:/usr/src/app# git ls-files --stage -- /usr/src/app/database/db.py
100644 e94b169ef5fc85022ac40b10a27646019230ae3f 0       database/db.py
root@97cb634b1d22:/usr/src/app# git cat-file -s e94b169ef5fc85022ac40b10a27646019230ae3f
fatal: git cat-file: could not get object info
```

**Comment by trajano** [comment] 2020-03-14 17:02
https://forums.docker.com/t/issues-after-upgrading-docker-desktop-to-2-2-0-4/90589/3

When you access the file using `cat` it would also show "Operation not permitted"

I tried mounting and accessing a short path and it works correctly so I am presuming it is because of the MAX FILE LENGTH of Windows.

**Comment by trajano** [comment] 2020-03-14 17:33
In the 2.2.0.4 release notes it discusses something about

> Fixed cache invalidation and event injection in shared volumes with host paths longer than 260 characters.
 
Could this have caused the issue?   Downgrading to 2.2.0.3 fixes the problem for me.

**Comment by mat007** [comment] 2020-03-16 06:44
Thanks for the report, we’re going to investigate it.

**Comment by omcandido** [comment] 2020-03-16 09:14
Is by any chance the file read-only? If so, it may be related to #6016

**Comment by djs55** [comment] 2020-03-16 09:19
@s-s-popov thanks for your report. Unfortunately the Dockerfile, docker-compose.yml isn't enough for me to build the project and reproduce the failure (e.g. missing `requirements.txt` and probably other things). Could you reproduce the failure, upload diagnostics and quote the id here? Thanks!

**Comment by i-kosh** [comment] 2020-03-16 10:31
I can reproduce it with git inside Debian container
This what i get then typing `git status` from windows
```powershell
PS C:\Users\ikosh> cd dev
PS C:\Users\ikosh\dev> git clone https://github.com/octocat/Hello-World.git
Cloning into 'Hello-World'...
remote: Enumerating objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), 1.53 KiB | 21.00 KiB/s, done.
PS C:\Users\ikosh\dev> cd .\Hello-World\
PS C:\Users\ikosh\dev\Hello-World> git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
PS C:\Users\ikosh\dev\Hello-World>
```

After i mount this directory in container
```powershell
PS C:\Users\ikosh> docker run --rm -it -v "~/dev/Hello-World:/test" debian
root@29048cbfb4d1:/#
```
install git in it
```bash
root@29048cbfb4d1:/# apt update
...
root@29048cbfb4d1:/# apt install -y git
...
done.
```
and get this error
```bash
root@29048cbfb4d1:/# cd test
root@29048cbfb4d1:/test# git status
fatal: failed to read object 7fd1a60b01f91b314f59955a4e4d4e80d8edf11d: Operation not permitted
root@29048cbfb4d1:/test#
````

**Comment by djs55** [comment] 2020-03-16 11:06
@i-kosh thanks for the repro instructions -- they worked for me too. Looking at the trace it seems like the same root cause as #6016: file is read-only but we try to open it with the wrong flags.

**Comment by stephen-turner** [comment] 2020-03-16 18:09
Thanks, let's close this one as a dupe then.

**Closed by stephen-turner** 2020-03-16 18:09 UTC
Labels: status/0-triage, version/2.2.0.4

**Comment by djs55** [comment] 2020-03-17 19:27
FYI I've got a prototype build (branched from stable 2.2.0.4) which has a fix for this problem. If you have the time to try it: https://download-stage.docker.com/win/stable/43531/Docker%20Desktop%20Installer.exe .  If it still doesn't work please let me know and also upload a fresh set of diagnostics. Thanks again!

**Comment by djs55** [comment] 2020-03-17 19:40
I deleted a comment about a prototype build because I just discovered it was incomplete - sorry for the confusion.

**Comment by djs55** [comment] 2020-03-17 20:38
I now have a more complete prototype build (based on top of the recent stable 2.2.0.4). If you have the time to try it let me know how it goes: https://download-stage.docker.com/win/stable/43542/Docker%20Desktop%20Installer.exe If it still doesn't work, please upload a fresh set of diagnostics and quote the id here.

**Comment by austriancoder** [comment] 2020-03-25 09:31
@djs55 Had the same problem and your prototype build fixes the problem.

**Comment by alex-pravdin-springernature** [comment] 2020-03-26 03:55
@djs55 Does this build contain the #4526 fix? I'm facing both issues.

**Comment by attilasg** [comment] 2020-03-30 12:52
I am having the same issues on Windows running 2.2.0.4(43472)

**Comment by djs55** [comment] 2020-03-30 13:28
@alex-pravdin-springernature sorry I missed this comment. We're about to make a release on edge which has all the fixes -- this will probably be the best build to use. I'll let you know when we have a release candidate.

**Comment by attilasg** [comment] 2020-03-30 13:42
Ok, I just started downloading the current edge, will stop now...
