### ISSUE TITLE
Not able to start Docker

### ISSUE THREAD

**Issue by Lovelesh1991** [docker/for-win#4446] opened 2019-08-06 13:42 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Lovelesh1991** [comment] 2019-08-06 13:44
7C61ADED-5BF8-4670-B5C1-AE058A26B3B5/20190806133611 is the diagnostic ID
Windows:10 Pro 64 bit
Facing error when trying to start Docker after fresh install. Have tried with run as Administrator mode as well same issue.

**Comment by mikeparker** [comment] 2019-08-06 16:49
```
[09:32:56.357][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Not enough memory in the system to start the virtual machine DockerDesktopVM.

Could not initialize memory: Ran out of memory (0x8007000E).

'DockerDesktopVM' failed to start. (Virtual machine ID 631223DC-64C1-4651-8393-F77A1598C447)

Not enough memory in the system to start the virtual machine DockerDesktopVM with ram size 2048 megabytes. (Virtual machine ID 631223DC-64C1-4651-8393-F77A1598C447)

'DockerDesktopVM' could not initialize memory: Ran 
```

Duplicate of https://github.com/docker/for-win/issues/4348, https://github.com/docker/for-win/issues/4362, https://github.com/docker/for-win/issues/4368

**Closed by mikeparker** 2019-08-06 16:49 UTC
