### ISSUE TITLE
Docker desktop installer fails on Windows if user name contains "."(dot)

### ISSUE THREAD

**Issue by sergey-derugo** [docker/for-win#11521] opened 2021-06-24 16:11 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics. 
  - Diagnostics ID: N/A, Reason: Docker was not installed successfully

### Actual behavior
 Docker desktop installer fails if OS user name contains "." dot such as **name.surname**
### Expected behavior
Docker installer should work

### Information
  - Windows Version: Microsoft Windows Server 2019 Datacenter, 10.0.17763 N/A Build 17763
  - Docker Desktop Version: 3.5.0 build 66024
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior
  1. Download Docker desktop installer version 3.5.0(product version 3.5.0.66024)
  2. Run the installer
  3. Actual result: installation fails due to the error:
  ```
Download failed: Could not find a part of the path 'C:\Users\namesurname\AppData\Local\Temp\nvbhzwmht5x'.
        at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```
 See the screenshot ![docker_error](https://user-images.githubusercontent.com/17096143/123297123-f40b0f00-d51f-11eb-8634-a6a2b66772fe.jpg)

### Known workarounds
Create a symlink, i.e. _C:\Users\namesurname_ which points to _C:\Users\name.surname_
```
mklink /d C:\Users\namesurname C:\Users\name.surname
```
Note, that you might need Admin permissions

**Comment by stephen-turner** [comment] 2021-06-24 16:49
Thanks for the report. Closing as dupe of #11514. We plan to have a patch later today.

**Closed by stephen-turner** 2021-06-24 16:49 UTC
