### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by Hinton** [docker/for-win#1866] opened 2018-03-21 12:58 UTC
### Expected behavior
Docker starts.

### Actual behavior

An error occurred

### Information

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

Diagnostic ID: E5D09B0C-1951-4398-93EE-7127C6343732/2018-03-21_13-53-48
Docker Version 17.12.0-ce-win47 (15139)

Windows Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.309

Reinstalling and/or resetting docker dosn't help. Reverting to an older version helped for a while but the error occurred again after a while.

### Steps to reproduce the behavior

  1. Install Docker
  2. Attempt to start Docker

**Comment by AnthonyMastrean** [comment] 2018-03-22 15:50
I have this same problem, repeatedly, day after day. It starts with `docker` or `docker-compose` commands hanging. I go to the Docker for Windows application, open Settings, and try Reset | Restart Docker. I have tried quitting the Docker for Windows app and killing processes/services. Usually, I have to restart my machine 😢 .

### Platform

I am completely updated.

Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.192

### Application

And I'm running stable Docker w/o experimental features.

Engine: 17.12.0-ce

### Information

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```   

### Diagnostic IDs

2018-03-19
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-19_10-10-35
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-19_10-14-20
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-19_10-17-29

2018-03-22
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-22_11-18-56
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-22_11-24-10
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-22_11-26-26
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-22_11-39-34
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-03-22_11-42-54

**Comment by AnthonyMastrean** [comment] 2018-03-22 16:05
C'mon, there are dozens of similar open [issues](https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Docker+hv-sock+proxy+%28vsudd%29+is+not+reachable) going back over a year! Most of these have no comments. The ones that do are from community members randomly changing settings.

What's happening here?

 * Duplicates: #1860, #1839, #1816, #1811, #1809, #1776, #1720, #1691, #1691, #1603, #1590, #1566, #1557, #1545, #1436, #1359, #1279, #1152, #1110, #1096, #1019, #1001, #971, #904, #900, #816, #792, #773, #701, #614, #606, #592
 * Related: https://github.com/docker/for-win/issues/1762#issuecomment-371523594, https://github.com/docker/for-win/issues/1592#issuecomment-370180347, https://github.com/docker/for-win/issues/1589#issuecomment-359779797, https://github.com/docker/for-win/issues/818#issuecomment-321688448, https://github.com/docker/for-win/issues/648#issuecomment-296379720, https://github.com/docker/for-win/issues/599#issuecomment-328917434

**Comment by tylerreece22** [comment] 2018-03-23 00:40
Yeah. I am having the same issue. Does anyone have the fix?

**Comment by tylerreece22** [comment] 2018-03-23 00:48
Two things. One problem I was having was when I was downloading an image I ran out of memory and the this issue actually went away because I turned off the experimental features and that seemed to do the trick XD

**Comment by jornj** [comment] 2018-03-26 05:58
One possible workaround: I was able to run docker on Windows 10 Enterprise with **Docker version 17.12.0.15139** 

I've tried 2-3 versions after that, including the latest one as of today (stable edition), but I'm getting the same "`Docker hv-sock proxy (vsudd) is not reachable`" error message every time. Resetting to factory defaults does not help.

**Comment by AnthonyMastrean** [comment] 2018-04-12 15:48
I got the latest Docker for Windows update and I'm having the same "Docker hv-sock proxy (vsudd) is not reachable", but with a different stack trace.

### Platform

I am completely up-to-date.

Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.309

### Application

I'm running stable Docker w/ experimental features.

Engine: 18.03.0-ce-win59 (16762)

### Information

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```   

### Diagnostic IDs

2018-04-12
 * EC10B2E4-09D2-4873-84AF-24452C6B5916/2018-04-12_11-34-10

**Comment by malawto** [comment] 2018-04-17 21:48
I also get the dreaded `Docker hv-sock proxy (vsudd) is not reachable` error message.  Docker for Windows was working until a Windows Update wrecked it.  **More, I think it has to do with being in a VM.  It works on a physical box and I took the exact same steps to isolate and prove it** (except I had to enable hypervisor applications for the VM inside of VMWare's settings.  And I've done this with known working instances of Docker in the VM, so it's correctly set for sure.)

Here are the steps I took to reproduce it:

1. I spun up a new Windows 10 Pro machine on a physical box:
**Starting OS level**
Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.125
2. Installed Docker CE for Windows Stable
Everything works correctly. 🥇 
3. Patch Windows... 
**Updated OS**
Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.371

Everything still works.  But... do the same steps on a new VM, built the exact same way?  **_It works after you install at OS Build: 16299.125, but somewhere in between that and getting to 16299.371... an update must break something._**  

It's clearly different running in a VM, but I've done it prior to the updates with no issue.  Has something changed with communicating with the Hyper-V alpine VM while virtualized?  Don't know, but I can isolate it to here.  I don't have time to find the specific patch that 's responsible... and I think undoing patches is suboptimal, so I don't really want to.

**Comment by hoegge** [comment] 2018-05-01 17:52
same as @AnthonyMastrean:
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Log: E9CBF190-66D5-420A-A5A8-9FA5D6D52443/2018-05-01_19-47-15

Stable Docker releases seems to be as likely as winning the lottery. When will I learn never to update

**Comment by Hinton** [comment] 2018-05-01 20:50
I forgot about this issue. Docker for Windows have been working reliably for me lately, using version `18.03.0-ce-win59 (16762)` on OS Build `16299.371`.

Unfortunately I can't give any advice other than this specific version seems to work reliably for my two Windows 10 machines. I haven't dared to upgrade to the latest version and probably won't bother as long as it continues working.

**Comment by rn** [comment] 2018-05-01 21:43
@hoegge in your case you actually run out of memory inside the Linux VM and the OOM killer starts killing processes. Try increasing the amount of memory allocated to the VM

**Comment by hoegge** [comment] 2018-05-02 05:01
Tried to increase memory allocation from the default 2GB to 8GB since one of my containers was suddenly using 1,9 GB. Seems to have fixed the problem. Would be nice if docker warned about low memory instead of cryptic messages. Thanks @rn

**Comment by rn** [comment] 2018-05-02 16:44
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.

**Closed by rn** 2018-05-02 16:44 UTC
Labels: area/network, area/startup, area/windows 10, version/17.12.0-ce-win47, version/18.03.0-ce-win59, version/18.05.0-ce-rc1-win63

**Comment by AnthonyMastrean** [comment] 2018-05-02 17:00
@rn Thank you for digging though the diagnostics and identifying these two sub-categories! I'm going to watch the new issues and take a closer look at my diagnostics when the problem occurs again.
