### ISSUE TITLE
Windows tray icon should toggle based on theme(light/dark) like other tray icons

### ISSUE THREAD

**Issue by vil-c** [docker/for-win#8083] opened 2020-08-15 13:46 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible?
Yes
  - Is the problem new?
The problem is not new
  - Did the problem appear with an update?
The problem has always been there

  - Windows Version: Version 20H2 (OS Build 19042.423)
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to check the behavior

  1. Can be seen in any windows 10 machine by toggling windows theme

  2. Attaching images to make the point clear

3. Dark mode is fine
![dark-docker](https://user-images.githubusercontent.com/26361661/90313513-caaa4b80-df2a-11ea-8309-da35ff8dfcbd.png)

4. But not consistent with light theme (other icons toggle color based on theme)
![light-docker](https://user-images.githubusercontent.com/26361661/90313524-deee4880-df2a-11ea-84fd-51e405370e0e.png)

**Comment by stephen-turner** [comment] 2020-08-17 14:52
Thanks for the report. Closing as dupe of #4113. (Also, it will be fixed RSN).

**Closed by stephen-turner** 2020-08-17 14:52 UTC
Labels: version/2.3.0.4
