### ISSUE TITLE
Container view keeps flashing/updating after upgrade to 4.28.0

### ISSUE THREAD

**Issue by ErikStrandhSR** [docker/for-win#13972] opened 2024-03-14 22:46 UTC
### Description

Since upgrading to 4.28.0 the container view updates and flashes every 1-2 seconds. It becomes hard to use it since any dialogues are closed with every update.
Tried to downgrade all the versions down to 4.27.0 but the issue remains in all of them now.

### Reproduce

1. Upgrade to 4.28.0
2. Open the container view

### Expected behavior

No flashing

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 3.827GiB
 Name: docker-desktop
 ID: 8f18ccb3-63e0-420f-a085-48bcd7285d53
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

6E5ADDAD-28C7-4111-A996-E6D466CACED8/20240314223348

**Comment by CaptainGooseFat** [comment] 2024-03-15 12:31
I have this exact same issue, and i also had it in the previous version of docker desktop. I have searched for a fix but have not found anyone asking about this until i found this.

**Comment by bsousaa** [comment] 2024-03-18 10:43
can you share a video capture with the issue?

**Comment by CaptainGooseFat** [comment] 2024-03-18 15:36
Sorry but i can't, my company blocks the installation of screen recording software.
Can i describe it better for you?
What happens is that the contents of the Containers view "reloads" approximately every 1-2 seconds.
Everything except for the text "Containers" and "Give feedback" at the top and the bar at the bottom that shows "Ram", "CPU" and "Signed in" flashes and reloads. The side menu (Containers, Images, Volumes etc) does not flash, only the contents to the right.

I hope that helps?
Thanks

**Comment by thkerkmann-rwe** [comment] 2024-03-21 09:11
I can confirm, this is happening on my machine also.
Interestingly, this is also happening on the Volumes view, but not on the images nor Builds view.

**Comment by CaptainGooseFat** [comment] 2024-03-21 09:49
I checked my Volumes view now after reading your comment, and i can confirm that this is the case for me too. Both the Containers view and Volumes view flashes for me too.

**Comment by fruttyh** [comment] 2024-03-26 11:50
I'm experiencing the same issue. 
Got the same docker version as @CaptainGooseFat

**Comment by CaptainGooseFat** [comment] 2024-03-27 07:54
Are anyone looking into this? It's driving me crazy

**Comment by CaptainGooseFat** [comment] 2024-04-30 10:50
Any news on this?

**Comment by CaptainGooseFat** [comment] 2024-04-30 12:21
Just to add: I updated to 4.29.0 just now and the problem persists.

**Comment by thkerkmann-rwe** [comment] 2024-04-30 12:28
Could be related to Windows (version / drivers / ...) as I have it on one machine, but not on another.
Might it be related to video driver?

**Comment by CaptainGooseFat** [comment] 2024-05-02 07:22
> Could be related to Windows (version / drivers / ...) as I have it on one machine, but not on another. Might it be related to video driver?

It's possible but i dont know. Several of my colleagues have the same version of docker but does not have this issue. We all have the exact same model of computer and updates are handled centrally.

**Comment by CaptainGooseFat** [comment] 2024-05-02 10:40
I have updated my video drivers, no luck unfortunately

**Comment by thkerkmann** [comment] 2024-05-07 07:52
I've created a video, maybe it helps to understand. This is the volumes view, but the same applies to the containers view.

https://github.com/docker/for-win/assets/15521035/b96922a4-2d9c-49c1-a603-ad01e589ae14

**Comment by CaptainGooseFat** [comment] 2024-05-07 11:31
> I've created a video, maybe it helps to understand. This is the volumes view, but the same applies to the containers view.
> 
>  20240506_163249.mp4

Yes, I have this exact same problem.

**Comment by BoschMihaiChezan** [comment] 2024-05-22 21:07
Same issue, Windows 11 - Docker Desktop containers view is constantly flickering, and flickering means also deselecting selected objects or closing dialogs.

**Comment by karman-docker** [comment] 2024-05-24 13:13
@thkerkmann @BoschMihaiChezan @CaptainGooseFat does this issue happen irrespective of whether containers are running or not ?

**Comment by CaptainGooseFat** [comment] 2024-05-24 13:15
> @thkerkmann @BoschMihaiChezan @CaptainGooseFat does this issue happen irrespective of whether containers are running or not ?

Yes it does.

**Comment by karman-docker** [comment] 2024-05-24 15:06
@CaptainGooseFat appreciate if you could share a diagnostics captured with all containers stopped and when the dashboard is flashing. Thank you.

**Comment by BoschMihaiChezan** [comment] 2024-05-27 05:13
@karman-docker 
The containers window is always flashing with no regards to the containers being running or stopped. It flashes even when there are no containers at all. To me it seems something like a "heartbeat mechanism" which should update the Containers view in the background but instead it does it in the front-end by resetting the Containers view to blank for half a second before updating the view. I would guess it's something related to the UI components rather than related to containers status.
What kind of diagnostics capture are you referring at?

**Comment by karman-docker** [comment] 2024-05-27 06:59
@BoschMihaiChezan thanks for the details.
When you see the issue even when there are no containers, could you run the below command, that will upload a diagnostics bundle.
Windows:
"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload

MacOS: 
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload

**Comment by BoschMihaiChezan** [comment] 2024-05-27 07:17
> @BoschMihaiChezan thanks for the details. When you see the issue even when there are no containers, could you run the below command, that will upload a diagnostics bundle. Windows: "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload
> 
> MacOS: /Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload

Here is the log for `"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload `
-- [com.docker.diagnose.txt](https://github.com/docker/for-win/files/15452201/com.docker.diagnose.txt)

**Comment by karman-docker** [comment] 2024-05-27 08:28
@BoschMihaiChezan unfortunately there was an error during upload, could you retry please and let us know the bundle Id (it gets displayed on the terminal when upload completes).

**Comment by BoschMihaiChezan** [comment] 2024-05-27 11:43
@karman-docker  I guess it's because of the company proxy or something. Anyway, what are you looking for is (according to the logs) in the diagnostics file/archive which was generated locally in C:\Users\CHM1LUD\AppData\Local\Temp\ED625D72-CAF0-487E-964B-8A17CBB08EFE: 
[20240527070657.zip](https://github.com/docker/for-win/files/15455349/20240527070657.zip)

**Comment by CaptainGooseFat** [comment] 2024-06-19 06:01
Any news on this issue?

**Comment by karman-docker** [comment] 2024-06-19 09:19
Apologies for the delay. Not being able to consistently reproduce the issue in our environment is causing the delay. But the issue is being actively investigated to identify a mitigation. Thank you.

**Comment by CaptainGooseFat** [comment] 2024-06-19 12:31
> Apologies for the delay. Not being able to consistently reproduce the issue in our environment is causing the delay. But the issue is being actively investigated to identify a mitigation. Thank you.

Okay, perfect. Thanks for your reply.

**Comment by HayateLaTech** [comment] 2024-06-25 18:34
I have the same problem :D just updated to 4.31.1 to see if it got fixed, but no dice ;w;

**Comment by HayateLaTech** [comment] 2024-07-07 04:39
I uploaded my Diagnostics Report too:

380A505A-7D08-4986-926E-4E77D556FD09/20240707041556

**Comment by susseau** [comment] 2024-07-09 19:41
After upgrading to 4.32.0, the same problem occurs. It has existed for several versions.

**Comment by kanehama** [comment] 2024-08-01 04:00
I updated Docker desktop to 4.33.0 (4.33.1) and this problem seems to be fixed.

**Comment by kanehama** [comment] 2024-08-01 04:01
I updated Docker desktop to 4.33.0 (4.33.1) and this problem seems to be fixed.

**Comment by susseau** [comment] 2024-08-01 07:42
In 4.33.0 the problem is gone. Thanks!

**Comment by BoschMihaiChezan** [comment] 2024-08-01 08:21
In Docker Desktop v4.33.1 the flashing Containers window issue/bug seems to be resolved. The Containers view is not flashing anymore, containers dots menus function properly.

**Closed as completed** 2024-08-06 11:40 UTC
Labels: area/gui, status/triage, version/4.28.0, version/4.31.1, version/4.32.0

**Comment by CaptainGooseFat** [comment] 2024-08-12 07:54
I updated docker today and the problem persists for me.

**Comment by lorenrh** [comment] 2024-08-30 09:08
4.34.0 has been released with a fix for this issue, more information o the [release notes](https://docs.docker.com/desktop/release-notes/).

**Comment by CaptainGooseFat** [comment] 2024-08-30 09:20
I just installed the new update and can confirm that it solves the problem for me. Thanks.

**Comment by quarky42** [comment] 2024-09-03 23:10
4.33.0 and 4.33.1 do not fix this issue for me.   For my particular instance of this issue, the whole Docker Desktop screen redraws when containers are running every 1-2 seconds.  When containers are not running, the screen is stable and does not blank out / redraw.

**Comment by quarky42** [comment] 2024-09-03 23:19
I misread the post from 5 days ago and have updated to 4.34.0 from within Docker Desktop itself.  Can confirm that this issue that has been plaguing me for 7 months or more is finally fixed.  Thank you!
