### ISSUE TITLE
Docker-compose commands are ignored

### ISSUE THREAD

**Issue by ArmandoAA** [docker/for-win#2858] opened 2018-11-07 11:48 UTC
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Run the docker-compose up -d command on my terminal which is in the directory of my docker file and it runs my dockerfile.

### Actual behavior
Currently, when running any docker-compose command my terminal just ignores and shows me the line again to put some command.

### Information
I'm using docker for Windows in the stable version.
Previously my docker-compose worked normally.
I already reinstalled docker.
I've already returned the docker to factory settings.
I'm not sure when this problem came up.
The docker commands are working normally.

### Steps to reproduce the behavior

  1. Run any docker-compose command

**Comment by patrix** [comment] 2018-11-07 18:51
+1

**Comment by patrix** [comment] 2018-11-07 19:18
Duplicate of docker/compose#6254

**Closed** 2018-11-15 22:33 UTC
