### ISSUE TITLE
Volume sync at random times

### ISSUE THREAD

**Issue by bitdevelopment** [docker/for-win#5569] opened 2020-01-23 13:34 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8461A581-BEF1-43E1-A3E0-E1646E0A7DC3/20200123092000

So as mentioned, mounted volume (windows directory) under docker, have random syncs, for example let's say I have text "kitten" inside `index.html`. Docker will run properly, and if i execute `docker exec -it webserver cat /var/www/html/index.html`, I will get "kitten", printed out. However, IF I edit `index.html` FROM the host, and replace let's say `kitten` with `kitty`, and right after I run `cat` on docker exec, I will get `kitten` most of the time, which means that mounted volume didn't sync with a host. After, 10 seconds, 30, one time even 30 minutes, `kitten` will turn into `kitty` and container will sync with a host. 

### Initial configuration
* Docker for windows has container defined in `docker-compose` with mounted Windows directory as volume.
* Mounted directory has index.html file with content `kitten`

### Expected behavior
Running `cat /var/www/html/index.html` before editing index.html file should print `kitten`
Running `cat /var/www/html/index.html` should IMMEDIATELY after editing index.html content into `kitty` print out the same content that exists on host.
### Actual behavior
`cat /var/www/html/index.html` after random amount of time matches content on host (turns `kitten` into `kitty`)
### Information
Because of simplification of the issue, I used index.html as a single file in this example. directory contains thousands of files (like any web project running around us). 
Mounted volume indeed has really random syncs, sometimes it's 10 seconds, sometimes it's 30 minutes. 
Succeeded to reproduce on 3 same laptops, using same timezones, and same hardware, however I was unable to reproduce same issue on different laptop in different timezone. 
Docker images report UTC+0 as default timezone, while host uses US ET time.  (If that matters)

  - Windows Version: 1909 (Windows 10 Pro)
  - Docker Desktop Version: latest stable (42247 v2.2.0)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

Did not succeed to reproduce in different environment.

**Comment by bitdevelopment** [comment] 2020-01-23 13:36
Any suggestion and workaround is appreciated!

**Comment by bitdevelopment** [comment] 2020-01-23 14:12
Confirmed as 2.2.0.0 grpc-fuse issue, on cifs we didn't encounter such issues. For that reason, we are reverting to previous version, until the problem is resolved.

**Comment by stephen-turner** [comment] 2020-01-23 16:08
Sounds like a dupe of #5530.

**Comment by bitdevelopment** [comment] 2020-01-23 16:17
> Sounds like a dupe of #5530.

Most probably is, just there is no information there for these random syncs.

**Comment by stephen-turner** [comment] 2020-02-11 13:39
We have just released 2.2.0.3, which fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

**Closed by stephen-turner** 2020-02-11 13:39 UTC
Labels: status/0-triage, version/1909, version/2.2.0.0
