### ISSUE TITLE
Images Page is Loading Forever (but it can be used normally)

### ISSUE THREAD

**Issue by Seasawher** [docker/for-win#12996] opened 2022-10-04 10:28 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0541F715-84D1-428E-ABF6-060C4D2CCB64/20221004100716

### Expected behavior

When you access Images page iside Docker Desktop Dashboad first time, there is no loading spinner. 

### Actual behavior

The spinner appears in the ”Images on disk" row and does not disappear after hours, even after uninstalling and reinstalling Docker.

![docker_loading](https://user-images.githubusercontent.com/47292598/193795239-223749ac-4588-4a44-a094-1420e6419fb7.jpg)

It does not mean that my input is not accepted. 

### Information

  - Windows Version: Windows 11 Home, 22H2, build 22621.608
  - Docker Desktop Version: 4.12.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ... Open Docker Desktop
  2. ...Create and remove Images
  3. ...Restart Docker Desktop
  4. ...Click "Images"

**Comment by nicks** [comment] 2022-10-05 02:51
thanks for the report! I'm going to mark this as a duplicate of https://github.com/docker/for-mac/issues/6502, to centralize the communication on it.

**Closed by nicks** 2022-10-05 02:51 UTC
