### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by Viacheslav-Romanov** [docker/for-win#2652] opened 2018-09-26 06:02 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment] 2018-09-26 06:05
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Closed by mat007** 2018-09-26 06:05 UTC

**Comment by marioanz** [comment] 2018-11-30 19:14
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:  22ED990D-4E0D-4381-9AEB-F430CAE1AFD3/20181130103807

### Expected behavior
Docker Start

### Actual behavior
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 
Edition:	Windows 10 Pro
Version:	1809
Installed on 	11/29/2018
OS build:	17763.134

  - Docker for Windows Version:  18.09.0

### Steps to reproduce the behavior


  1. Build Windows 10 VM.  Install Updates.
  2. Enable nested virtualization
  3. Turn on Features:  Containers, Hyper-V
  4. Download/Install Docker Desktop
