### ISSUE TITLE
Can't Open run.sh

### ISSUE THREAD

**Issue by aliens9889** [docker/for-win#103] opened 2016-09-26 15:25 UTC
Hi everybody!! I was checking what would be the reason of why I write this command `docker-compose run db sh` the only thing i got is this 

```
Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose run`.
```

After this I was checking what it's going on and when I type docker logs this is what I got.

`sh: can't open '/app/docker/run.sh`

So I don't have a clue I could how can fix it. Any suggetions!? 

And By the way Thanks for the Help!

**Comment by rneugeba** [comment] 2016-09-27 11:14
please provide details, such as docker version, sample docker files etc. without this we can't reproduce and therefore can't help
thanks

**Comment by rneugeba** [comment] 2016-10-05 06:47
I'm closing this issue as there is not enough information available. please re-open if this is still a issue and provide additional info.
thanks

**Closed by rneugeba** 2016-10-05 06:47 UTC
Labels: status/more-info-needed
