### ISSUE TITLE
Installer creates update log in wrong location, if the username contains a whitespace

### ISSUE THREAD

**Issue by IceOnly** [docker/for-win#8767] opened 2020-10-02 07:08 UTC
### Expected behavior
I am not sure there the correct path should be, I think somewhere in C:\Users\John Doe\....

### Actual behavior
If a Windows User contains a whitespace in his name (like John Doe), the install/update logfile will be written to: C:\Users\John with no file extension. This cause in some weird behaviour of the windows system. Like using Win-R and enter %appdata% will try to open the log file, instead of open the folder C:\Users\John Doe\AppData\Roaming.

### Information
  - Is it reproducible? Yes
  - Is the problem new? No, last 6 updates broke my system
  - Windows Version: Windows 10
  - Docker Desktop Version: 2.4.0.0 (48506)

### Steps to reproduce the behavior
 1. Setup a fresh windows installation and choose the Username "John Doe"
 2. Install an old Docker version
 3. Update to the latest version
 4. now a file without extension should be created at c:\Users\John

**Comment by LukasWestholt** [comment] 2020-10-02 07:59
same problem here:

    Started on: 2020.09.30 19:20:12.067
    File: C:\Users\Lukas
    CommandLine: "C:\Users\Lukas Westholt\AppData\Local\Temp\3elsdb13.3p1.exe" install --uninstall-info-file="C:\Users\Lukas Westholt\AppData\Local\Temp\uwmvmvbk.0fm" --confirm --append-logs --log-output-file=C:\Users\Lukas Westholt\AppData\Local\Docker\install-log.txt --relaunch-as-admin
    [19:20:12.084][InstallHandler] No installation found
    [19:20:12.316][InstallWorkflow] Using package: res:DockerDesktop
    [19:20:12.322][InstallWorkflow] Downloading
    [19:20:13.224][InstallWorkflow] Extracting manifest
    [19:20:13.833][InstallWorkflow] Checking prerequisites
    [19:20:14.260][InstallWorkflow] Unpacking artifacts
    [19:21:41.051][InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
    [19:21:52.475][InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
    [19:22:03.826][InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
    [19:22:04.398][InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
    [19:22:04.405][InstallWorkflow-ServiceAction] Removing service
    [19:22:04.411][InstallWorkflow-ServiceAction] Creating service
    [19:22:05.965][InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
    [19:22:05.986][InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
    [19:22:06.073][InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
    [19:22:06.078][InstallWorkflow-ShortcutAction] Ignore shortcut: C:\Users\Lukas Westholt\Desktop\Docker Desktop.lnk/Docker Desktop
    [19:22:06.083][InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
    [19:22:06.089][InstallWorkflow] Deploying component CommunityInstaller.PathAction
    [19:22:06.953][InstallWorkflow] Deploying component CommunityInstaller.PathAction
    [19:22:07.969][InstallWorkflow] Deploying component CommunityInstaller.ExecAction
    [19:22:09.444][InstallWorkflow] Registering product
    [19:22:09.455][InstallWorkflow] Installation succeeded

There are missing quotation marks for --log-output-file.

**Comment by stephen-turner** [comment] 2020-10-02 08:17
Closing as dupe of #7941. But thank you for the diagnosis @LukasWestholt. We'll double-check that this is fixed in 2.4.0.0 and is just a leftover bug from the uninstaller of the previous version.

**Closed by stephen-turner** 2020-10-02 08:17 UTC
Labels: version/2.4.0.0

**Comment by mat007** [comment] 2020-10-02 11:21
This has been fixed but it needs one more release to propagate to the installed application because the way it works upon update is that we first run the installed installer on uninstall mode to remove the bits from the old version, then run the new installer to install the new bits, and finally store the installer in the application installation folder for the next future update.
