### ISSUE TITLE
Docker Desktop Dashboard not showing running containers

### ISSUE THREAD

**Issue by skyd0me** [docker/for-win#10642] opened 2021-03-13 06:53 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When I open the settings, I can not click anything in the application. Tick some checkboxes, change proxy settings or anything as none of the UI elements are clickable.
I have multiple containers running but the dasbhoard is still empty.
Already reinstalled docker desktop for windows but nothing changed. The latest update made everything even worth as the complete UI freezes after some minutes and I have to manually kill the UI app via task manager.

### Expected behavior

UI is clickable and shows the running containers. So nothing fancy. Very basic requirements :-)

### Information

  - Windows Version: 2004
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: NO

### Steps to reproduce the behavior

  1. Open docker desktop
  2. Click on Settings
  3. Nothing is clickable at all. No settings can be changed.
  4. Go back to dashboard. No running containers are displayed. But docker ps shows three running containers.

**Comment by stephen-turner** [comment] 2021-03-15 10:23
This might be a dupe of #10563.

**Closed** 2021-04-01 05:56 UTC
