### ISSUE TITLE
Docker For Windows 2.1.0.0 wont start on W10 1903 

### ISSUE THREAD

**Issue by robert-niestroj** [docker/for-win#4421] opened 2019-08-05 07:15 UTC
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [  ] I have uploaded Diagnostics
  - Diagnostics ID: 6A40662B-B805-41DF-B8FA-A904C6430A8E/20190805070056

### Expected behavior

Docker should start normally, there should be a white icon in the taskbar.

### Actual behavior

I get an error:
Unable to stop
   w Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   w Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   w Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   w Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information
  - Is it reproducible?

Yes. On my laptop and on my colleagues laptop. Both Windows 10 1903. 

  - Is the problem new?

Yes

  - Did the problem appear with an update?

No. Fresh install.

  - Windows Version:

Windows 10 1903

  - Docker Desktop Version:

2.1.0.0

### Steps to reproduce the behavior
  1. Start computer, docker is set to autostart
  2. Error occurs while Docker tries to start

**Comment by wirdehall** [comment] 2019-08-05 12:17
This seams to be the same error as #4426.

**Comment by mikeparker** [comment] 2019-08-06 16:38
```
[09:00:53.883][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[09:00:55.935][PowerShell        ][Error  ] AuthorizationManager check failed.
```

Duplicate of https://github.com/docker/for-win/issues/4376

**Closed by mikeparker** 2019-08-06 16:38 UTC

**Comment by mikeparker** [comment] 2019-08-08 12:15
Docker Desktop 2.1.0.1 stable has been released with a fix for this now.
