### ISSUE TITLE
Issue with Docker Initialization

### ISSUE THREAD

**Issue by Higor-Matos** [docker/for-win#13674] opened 2023-09-09 18:30 UTC
### Description

Docker fails to start correctly. It takes approximately 20 minutes to "initialize," and when attempting to check volumes or execute any commands like Docker Compose, it throws an error indicating that the service is not running.

I have tried starting the service multiple times, but it always stops on its own.

### Reproduce

Download and install the latest version of Docker Desktop.

### Expected behavior

Docker is working properly.

### docker version

```bash
→ C:\Program Files\PowerShell\7› docker version
Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
→ C:\Program Files\PowerShell\7› docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: Cannot connect to the Docker daemon at npipe:////./pipe/docker_engine. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

2B2DC83C-998C-4949-82C5-B438E478F33D/20230909181301

### Additional Info

These reports are related to the same topic.
https://github.com/docker/for-win/issues/13662
https://github.com/docker/for-win/issues/13667
https://github.com/docker/for-win/issues/13673
https://github.com/docker/for-win/issues/13639

**Comment by Higor-Matos** [comment] 2023-09-09 18:50
After reverting to version 4.21.1, it started working normally again.

**Comment by lorenrh** [comment] 2023-09-11 16:27
Thanks for your report, I'll close this issue as a duplicate of #13662, any more information you want to share, please share it on that issue.

**Closed as completed by lorenrh** 2023-09-11 16:27 UTC
Labels: needs-triage, version/4.22.1
