### ISSUE TITLE
Docker 1.13.0-rc5 removed color from console

### ISSUE THREAD

**Issue by kobenauf** [docker/for-win#372] opened 2017-01-07 00:52 UTC
### Expected behavior
Docker content still appears in color

### Actual behavior
As of the Docker build that just occurred (Docker version 1.13.0-rc5, build 43cc971) the color that did appear in my console is now gone.  This is pretty important in helping me easily separate and manage the 6 containers running in the same docker-compose instance.

### Information
I use cygwin/bash on Windows 10.

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
372B18A7-9C30-427A-BE2A-C71AC6C6DC45/2017-01-06_16-48-5

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rneugeba** [comment] 2017-01-07 13:10
thanks for the report. Could you give an example command line which used to have colour and does not anymore?
thanks

**Comment by juliankolbe** [comment] 2017-01-22 14:30
Im having the same issue. I usually run my docker-compose up from the the git for windows gitbash terminal. It used to have colors and worked perfectly. So the container names had colors as well as some of their output. (Node.js container for example produced colored log outputs). Now however the logs all are all white and there is exactly zero color. I really need a fix for this. Help is appreciated.

**Comment by rneugeba** [comment] 2017-01-23 11:13
@juliankolbe could you provide a concrete sample command line?
thanks

**Comment by dgageot** [comment] 2017-01-30 11:39
@juliankolbe @kobenauf Did you have time to prepare a simple concrete sample command line?

**Comment by juliankolbe** [comment] 2017-01-30 12:26
@dgageot @rneugeba Hi, sorry it took a while. So i'm not exactly sure what you mean by sample command line, but i hope this is it. If it isn't let me know. So the one with colour is obviously cmder, which i have now adopted. The other is the gitbash for windows as supplied by git.

##### What it used to look like on gitbash more or less
![Image of Cmder](https://i.imgur.com/hRm51yq.png)

##### What it looks like after the update
![Image of Gitbash](https://i.imgur.com/tgj185c.png)

**Comment by rneugeba** [comment] 2017-02-15 14:21
This looks like an issue with compose and not with the Docker for Windows application, which ships compose. If the issue is still there with the latest Beta/Stable, which ships an updated version of compose, please open an issue on https://github.com/docker/compose
thanks for reporting

**Closed by rneugeba** 2017-02-15 14:21 UTC
Labels: status/1-acknowledged, version/beta35
