### ISSUE TITLE
Docker not opening

### ISSUE THREAD

**Issue by Sarahiruthh** [docker/for-win#13581] opened 2023-07-04 01:44 UTC
### Description

Every time I open Docker, it states "Docker Desktop is unable to detect a Hypervisor. Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/desktop/windows/troubleshoot/#virtualization" I've tried everything in the https://docs.docker.com/desktop/troubleshoot/overview/#virtualization has suggested, but I'm not sure what else to do. Please help! Diagnostics ID below.

Thanks!

Diagnostics ID:
CCE05404-8115-4949-84FF-337611C5DB06/20230704012813

### Reproduce

I just downloaded Docker a few minutes ago. There aren't really any steps to reproduce other than opening the desktop application. 

### docker version

```bash
Docker version 24.0.2, build cb74dfc
```

### docker info

```bash
N/A
```

### Diagnostics ID

CCE05404-8115-4949-84FF-337611C5DB06/20230704012813

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by landism** [comment] 2023-07-07 14:36
This looks like a dupe of #13575

**Closed as completed by landism** 2023-07-07 14:36 UTC
Labels: area/installer, area/startup, status/duplicate
