### ISSUE TITLE
Docker will not start on windows 10 - Unable to write to the database. Exit code: 1

### ISSUE THREAD

**Issue by Aviram** [docker/for-win#1201] opened 2017-10-11 11:37 UTC
Can someone help ?

Log is attached : 
[14:20:26.712][ErrorReportWindow][Info   ] Open logs
[14:22:15.590][SegmentApi     ][Info   ] Usage statistic: actionMenuSwitchLinuxDaemon
[14:22:15.594][Notifications  ][Info   ] Docker is switching...
[14:22:15.625][SegmentApi     ][Info   ] Usage statistic: actionSettingsChanged
[14:22:15.626][SegmentApi     ][Info   ] Usage statistic: Identify
[14:22:15.637][NamedPipeClient][Info   ] Sending Version()...
[14:22:15.639][NamedPipeClient][Info   ] Received response for Version
[14:22:15.639][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[14:22:15.639][NamedPipeServer][Info   ] Version()
[14:22:15.639][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:22:15.641][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[14:22:15.646][PowerMode      ][Info   ] Stop
[14:22:15.646][HyperV         ][Info   ] Stop
[14:22:15.666][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[14:22:16.014][HyperV         ][Info   ] Script started at 14:22:15.999
[14:22:18.229][HyperV         ][Info   ] Module loaded at 14:22:18.229
[14:22:18.306][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:22:18.308][HyperV         ][Debug  ] [stop] took 00:00:02.6603152 to run
[14:22:18.308][OptimizeDisk   ][Info   ] Optimize
[14:22:18.308][PowerShell     ][Info   ] Run script...
[14:22:18.328][Moby           ][Info   ] Stop
[14:22:18.354][PowerMode      ][Info   ] Start
[14:22:18.354][HyperVGuids    ][Info   ] Installing GUIDs...
[14:22:18.355][HyperV         ][Info   ] Create
[14:22:18.356][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[14:22:18.357][HyperVGuids    ][Info   ] GUIDs installed
[14:22:18.357][Firewall       ][Info   ] Removing all existing rules...
[14:22:18.368][HyperV         ][Info   ] Script started at 14:22:18.368
[14:22:18.383][HyperV         ][Info   ] Module loaded at 14:22:18.383
[14:22:18.620][HyperV         ][Info   ] Creating Switch: DockerNAT...
[14:22:18.667][Firewall       ][Info   ] All existing rules are removed.
[14:22:18.668][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:22:18.675][Firewall       ][Info   ] Opening ports for SMB...
[14:22:18.687][Firewall       ][Info   ] Ports are opened
[14:22:19.859][HyperV         ][Info   ] Switch created.
[14:22:21.106][HyperV         ][Info   ] Set IP address on switch
[14:22:22.287][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[14:22:23.124][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[14:22:23.431][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[14:22:23.929][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[14:22:24.066][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[14:22:24.673][HyperV         ][Info   ] Disabled Guest Service Interface
[14:22:24.705][HyperV         ][Info   ] Enabled Heartbeat
[14:22:24.734][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[14:22:24.753][HyperV         ][Info   ] Enabled Shutdown
[14:22:24.767][HyperV         ][Info   ] Enabled Time Synchronization
[14:22:24.780][HyperV         ][Info   ] Disabled VSS
[14:22:24.994][HyperV         ][Info   ] VM created.
[14:22:24.995][HyperV         ][Debug  ] [create] took 00:00:06.6398742 to run
[14:22:24.995][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[14:22:25.086][Database       ][Info   ] Generating CA Cert Bundle
[14:22:25.109][Database       ][Info   ] CA Cert Bundle Generated
[14:22:25.156][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[14:22:25.157][DataKit        ][Info   ] Thread 1 killed on uncaught exception Unix.Unix_error(40, "send_notification", "")

[14:22:25.157][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[14:22:25.157][DataKit        ][Info   ]                    Unix.Unix_error(Unix.ENOTSOCK, "select", "")

[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[14:22:25.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[14:22:25.426][DataKit        ][Error  ] Process died
[14:22:26.531][Database       ][Error  ] 2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/10/11 14:22:26 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

**Comment by rwarford** [comment] 2017-10-11 20:18
See also #1203

**Comment by chatchavan** [comment] 2017-10-17 10:33
See also #871

**Comment by djs55** [comment] 2017-11-30 17:12
I think
```
Thread 1 killed on uncaught exception Unix.Unix_error(40, "send_notification", "")
```
implies this is a duplicate of #498. There should be a fix in the edge branch shortly.

Thanks for your report and your patience.

**Closed by djs55** 2017-11-30 17:12 UTC
