### ISSUE TITLE
Issues with Teredo IPv6 Tunneling after installing

### ISSUE THREAD

**Issue by mablae** [docker/for-win#42] opened 2016-08-17 16:06 UTC
### Expected behavior
Xbox One App Chats should work. Maybe Skype is also affected as they use the same network stack.

### Actual behavior
When Docker is installed the Xbox App Chat (Party) is not able to connect anymore, none the less the 
teredo status shows that everything is fine: `type: qualified`

Disabling the `Hyper-V` network interfaces solved the issue for me.

### Information

Windows 10 Pro 1607

**Comment by rneugeba** [comment] 2016-09-01 18:24
@mablae I can happily run skype along with Docker for Windows, but I'm on a IPv4 network (not sure if that is significant). I don't have an Xbox One App chat client but I can't really see how the Hyper-V networking interferes with other application. We just create an iternal switch with a default IP address of `10.0.75.1/24`. If you are using this prefix elsewhere on your network, you can change the Docker for Windows prefix via the settings menu.

Could you also provide a diagnostics?
Thanks

**Comment by dgageot** [comment] 2016-09-14 06:57
Hi @mablae have you had time to upload a diagnostic so that we can help fix the issue? Or maybe your managed to fix the issue. In any case, please keep us posted. Without news, I will close the issue in a couple of days.

Thanks a lot!

**Comment by dgageot** [comment] 2016-09-16 16:57
@mablae I'm going to have to close this issue since we couldn't reproduce it and didn't get a more complete diagnostic. Thanks again for helping us and feel free to reopen the ticket if you still have the issue and can provide more information

**Closed by dgageot** 2016-09-16 16:57 UTC
Labels: area/network, status/more-info-needed

**Comment by djs415** [comment] 2019-04-11 15:37
I had the same issue, and it was as easy as disabling the extra network interfaces created (possibly at the time of installing docker?). Once I turned them off I instantly connected to my xbox party chat through the windows 10 xbox app.
