### ISSUE TITLE
Install Docker Desktop 3.0.0 (50684) on windows10 with wsl Failed

### ISSUE THREAD

**Issue by xiaohuifirst** [docker/for-win#9845] opened 2020-12-17 15:50 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Failed to register product: 检索 COM 类工厂中 CLSID 为 {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} 的组件失败，原因是出现以下错误: 80080005 服务器运行失败 (异常来自 HRESULT:0x80080005 (CO_E_SERVER_EXEC_FAILURE))。
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

### Information

  - Windows Version: Win10 pro 19042.685
  - Docker Desktop Version: 3.0.0 (50684)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by wangxulong** [comment] 2020-12-18 01:49
i meet the same issue

**Comment by tiborvass** [comment] 2020-12-20 02:04
Duplicate of #9825

**Closed by tiborvass** 2020-12-20 02:04 UTC
Labels: version/3.0.0
