### ISSUE TITLE
Can not pull images from private registry

### ISSUE THREAD

**Issue by Matthias247** [docker/for-win#87] opened 2016-09-16 11:51 UTC
### Expected behavior
We have set up an internal docker registry which we use for image sharing. It's located out `companyrepo:5000`. When I used the old boot2docker solution I could easily do `docker pull companyrepo:5000/myimage:1` to pull and use an image. I only had to add the server name to the insecure registry entries.

I want to be able to do the same thing with docker for windows.

### Actual behavior
I get the error:
> Error response from daemon: Get http://companyrepo:5000/v2/: dial tcp: lookup companyrepo on 192.168.65.1:53: no such host
    
However this IP address is not where our company repository is hosted, and I have no idea where it comes from. 

If I manually enter our companys DNS server address the error message changes to:
> Error while pulling image: Get http://companyrepo:5000/v1/repositories/myimage/images: dial tcp: lookup companyrepo on 192.168.65.9:53: server misbehaving

### Information

- tested with stable build of Docker for Windows as well es beta channel
- the behavior is also described here, but no solution: https://forums.docker.com/t/docker-for-windows-not-pulling-images-from-private-v2-api-registry/18851
- if it matters: Our internal IP addresses are all 10.10.x.y and are typcially assigned through DHCP.

### Steps to reproduce the behavior

  1. Execute `docker pull companyrepo:5000/myimage:1` from our internal network and observe the given error message

**Comment by Matthias247** [comment] 2016-09-16 13:19
In the meantime I got it running in 2ways:

1. Use the full qualified domain name of the server. E.g. `docker pull companyrepo.ourcompany.com:5000/myimage:1`. This is not as nice since the images then have a different name.
2. Set the DNS search option **inside** the docker for windows host. I'm doing this with:  
  docker run -it -v //:/host alpine //bin/sh  
  open /host/etc/resolv.conf and add "search ourcompany.com"  
  After that step pulling from the repository works. BUT I would need to do that after each docker restart.

Specifying `"dns-search": ["ourcompany.com"]` or `"dns-opt": ["search ourcompany.com"]` in the Docker daemon configuration section does not work for me. Should it do the same?

**Comment by dgageot** [comment] 2016-09-16 16:37
Hi @Matthias247 which version of Docker for Windows are you using? You might want to try a more recent version since we added some support for search domains in `beta26` and `1.12.1`

**Comment by Matthias247** [comment] 2016-09-16 16:41
@dgageot It's 1.12.1 and beta26. Installed it just today in order to try it out.

**Comment by jasonsoft** [comment] 2016-09-17 04:45
Hi @Matthias247  & @dgageot ,

I used to got the same problem as well.  After I installed 1.12.1 or beta26, it seems to me that the problem has been resolved.

**Comment by chakrim99** [comment] 2016-09-28 13:00
Hi,

I have docker 1.12.1 ver and when i run "docker run -it ubuntu bash" or "docker pull ubuntu" command I am getting the below error:

Unable to find image 'ubuntu:latest' locally
Pulling repository docker.io/library/ubuntu
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp: lookup index.docker.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable.
See 'docker run --help'.


Please suggest to fix the issue.

**Comment by Matthias247** [comment] 2016-09-30 11:08
@dgageot In Beta27 the problem no longer shows up. Although I didn't find anything related to this in the changelog.

**Comment by dgageot** [comment] 2016-09-30 12:59
@Matthias247 That's the magic of bug fixing I guess ;-) To be fair, beta27 contains quite a few fixes to VpnKit, the component in charge of the networking. We might have not listed all the fixes in the changelog.

@chakrim99 Could you try Beta27?

**Comment by chakrim99** [comment] 2016-10-05 12:28
@dgageot, Thank you, I tried by switching to beta version, and able run Ubuntu container. But one observation is, after the switch, lost the older containers created, not relevant to the current issue but wanted to let you as i am not sure if its expected behavior. 
Can you also please suggest me how to move the "Virtual hard disks" to D or E drive, I tried as specified from [https://forums.docker.com/t/where-are-images-stored/9794/6](https://forums.docker.com/t/where-are-images-stored/9794/6) but was not able run docker . Please let me know if I should create a new issue as its not relevant to the current issue.

**Comment by dgageot** [comment] 2016-10-18 08:45
I'm going to close this issue. Thanks a lot for your help!

@chakrim99 Please create separate tickets for those other issues. That really helps us to have separate tickets for separate issues.

**Closed by dgageot** 2016-10-18 08:45 UTC
Labels: kind/bug, version/beta26
