### ISSUE TITLE
restart needed after every resume from hibernate

### ISSUE THREAD

**Issue by chris-findlay** [docker/for-win#12969] opened 2022-09-18 21:08 UTC
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. Start DockerDesktop.
  2. Run containers via scripts - all good.
  3. Hibernate
  4. Resume
  5. Attempt to orchestrate containers using the same scripts - get timeouts.
  6. Restart docker.
  7. Retry 5 - everything works.

**Comment by chris-findlay** [comment] 2022-09-18 21:09
This is relatively recent - not more than a month old.  Used to work fine.

**Comment by tehaksbrid** [comment] 2022-09-22 08:30
Same, though I typically can't even restart Docker Desktop. Usually have to restart system.

**Comment by b2b-florent-quillien** [comment] 2022-09-23 14:15
Same thing here. I use hibernation a lot and so I now have to reboot my system several times a day

**Comment by tyornado** [comment] 2022-09-24 08:37
may be it is the same reason of issue i encountered   
[https://github.com/docker/for-win/issues/12979](url)

**Comment by tehaksbrid** [comment] 2022-09-24 08:49
@b2b-florent-quillien @chris-findlay I force-updated my WSL2 kernel yesterday morning. I've had two hibernates since then, and Docker Desktop has not shown this behavior again.

`wsl --update`

**Comment by b2b-florent-quillien** [comment] 2022-09-24 09:36
@tehaksbrid Thanks your advice, it seems to work! I just tried multiple hibernate. After the update, I had to reboot my system, not only wsl, to resolve the problem.

**Comment by chris-findlay** [comment] 2022-09-26 00:01
```
$ wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.102.1
```

**Comment by nicks** [comment] 2022-09-26 19:48
To help centralize the discussion on this, I'm going to mark it as a duplicate of https://github.com/docker/for-win/issues/12969

We currently believe that this is an upstream WSL bug but the WSL team is still looking for a repro case.

**Closed by nicks** 2022-09-26 19:48 UTC

**Comment by chris-findlay** [comment] 2022-09-26 19:58
@nicks You marked this as a duplicate of itself, so I can't go see the consolidated discussion..!

**Comment by nicks** [comment] 2022-09-26 20:10
LOL oops, fixed :laughing: https://github.com/docker/for-win/issues/12968
