### ISSUE TITLE
Docker unable to switch from linux to windows container

### ISSUE THREAD

**Issue by chiragkhanna28** [docker/for-win#11945] opened 2021-08-19 19:48 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 85D6BBD3-B7B9-467E-92B3-AF4359768F66/20210819193401

### Actual behavior

When trying to switch from linux container to windows container, docker is getting failed.

### Expected behavior

When trying to switch from linux container to windows container, docker should keep running.

### Information

  - Windows Version: 19043.1165
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  When trying to switch from linux container to windows container, docker is getting failed.

**Comment by StefanScherer** [comment] 2021-08-20 08:32
Thanks for the report. We're aware of this issue and are working on a fix. In the meantime follow the workaround described here: https://github.com/docker/for-win/issues/11899#issuecomment-900084477
I'll close this ticket as it's a duplicate of #11899.

**Closed by StefanScherer** 2021-08-20 08:32 UTC
