### ISSUE TITLE
Can't Run - Windows 10

### ISSUE THREAD

**Issue by richraid21** [docker/for-win#400] opened 2017-01-19 02:55 UTC
### Expected behavior
Docker Launches 
### Actual behavior
Error Thrown
### Information

3587B5AC-BB75-4F2A-9138-418F6747141C/2017-01-18_21-53-37

[log.txt](https://github.com/docker/for-win/files/715571/log.txt)

### Steps to reproduce the behavior

  1. Attempt to run
  2. Fail

**Comment by simonferquel** [comment] 2017-01-19 10:22
Can you verify if you can create a VM manually and launch it using Hyper-V manager ?

**Comment by richraid21** [comment] 2017-01-20 02:31
Hyper V seems to be having problems with Secure Boot (Or at least the MobyLinux.ps1 script is having trouble setting it properly). 

After looking into the problems and logs, and running the PowerScript scripts manually, I was able to find the issue. After googling for a bit, I found this [issue](https://github.com/docker/for-win/issues/216#issuecomment-260843209). Referenced in this linked comment is what solved my problem. 
I replaced line 250 in MobyLinux.ps1 with the two lines provided and reran -Delete and -Create.   

Docker seems to be functioning like normal now.

**Comment by simonferquel** [comment] 2017-01-20 09:17
Ok @richraid21 thanks for the details. We'll evaluate the risk to modify this for everybody in next beta !

**Comment by richraid21** [comment] 2017-01-20 13:41
Just a little bit more information:  

There seems to be a problem with my(alot of?) Hyper V installs. I can create a Gen1 VM instance with an ISO attached (all in one go), but I cannot setup a Gen2 VM with an iso attached (all in one go). 

In order to successfully create a Gen2 VM instance, I need to create it without an attached ISO. Then, after the VHDX is created, go in and attach the ISO manually, and remove secure boot. 

Unrelated to Docker, but it may help track down the problem.

**Comment by rneugeba** [comment] 2017-01-24 11:13
@jasonwzs reported [here](https://github.com/docker/for-win/issues/315#issuecomment-274633206) that the workaround poster [here](https://github.com/docker/for-win/issues/216#issuecomment-259855519) works, but needs to be redone after every update.

**Comment by rneugeba** [comment] 2017-01-30 15:35
we added the fix in master and it should hopefully make it into the next beta

**Comment by rneugeba** [comment] 2017-01-31 16:05
Beta40 is out, which should have a potential fix. Could you try it from here: https://download.docker.com/win/beta/InstallDocker.msi

**Comment by richraid21** [comment] 2017-01-31 16:17
Seems to be working in beta40. Will update on any changes.

**Comment by dgageot** [comment] 2017-01-31 16:35
Thanks @richraid21 I'm going to close the issue then. Feel free to reopen if the issue is back in the future.

**Closed by dgageot** 2017-01-31 16:35 UTC
Labels: area/hyper-v, status/0-more-info-needed, status/4-fix-released-beta
