### ISSUE TITLE
Docker desktop fails to run 

### ISSUE THREAD

**Issue by malembetirick** [docker/for-win#7062] opened 2020-06-04 20:47 UTC
I have an issue to run docker from my windows 10 professional since the new update. I uninstalled and reinstalled many times but i'm still facing this issue.
You will find below, the log of fail:
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/06/04 22:39:33.376
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\rmalembe\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[22:39:33.753][GUI               ][Info   ] Starting...
[22:39:33.827][ComponentVersions ][Info   ] Edition community
[22:39:33.835][ComponentVersions ][Info   ] Edition community
[22:39:34.393][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[22:39:34.433][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[22:39:34.441][SegmentApi        ][Info   ] Usage statistic: Identify
[22:39:35.010][SegmentApi        ][Info   ] Usage statistic: appLaunched
[22:39:44.445][ApplicationTemplatesTracking][Info   ] Cannot list templates
[22:39:44.446][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[22:39:44.448][SegmentApi        ][Info   ] Usage statistic: heartbeat
[22:39:44.576][LoggingMessageHandler][Info   ] [e7b4fe62] <BackendAPIClient start> GET http://backend/version
[22:39:45.543][LoggingMessageHandler][Info   ] [e7b4fe62] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 965ms)
[22:39:45.677][LoggingMessageHandler][Info   ] [8b7a0c46] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[22:39:45.849][LoggingMessageHandler][Info   ] [8b7a0c46] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 172ms)
[22:39:45.862][LoggingMessageHandler][Info   ] [693aad0c] <BackendAPIClient start> POST http://backend/migrate/app
[22:39:45.868][LoggingMessageHandler][Info   ] [693aad0c] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 6ms)
[22:39:45.877][Engines           ][Debug  ] Starting
[22:39:45.907][LoggingMessageHandler][Info   ] [b5bff228] <BackendAPIClient start> POST http://backend/versionpack/enable
[22:39:45.912][NpsStore          ][Error  ] Cannot read NPS ID: Le fichier 'C:\Users\rmalembe\AppData\Roaming\Docker\.npsid' est introuvable.
[22:39:46.154][LoggingMessageHandler][Info   ] [b5bff228] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 247ms)
[22:39:47.135][NPS               ][Info   ] NPS User id created
[22:39:47.335][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[22:39:47.881][GoBackendProcess  ][Info   ] Started
[22:39:47.886][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[22:39:47.915][MutagenProcess    ][Info   ] Started
[22:39:47.929][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[22:39:47.930][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[22:39:47.937][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[22:39:47.948][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1591303187}
[22:39:47.949][SystrayNotifications][Info   ] Docker is starting
[22:39:49.456][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[22:39:49.456][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[22:39:49.456][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[22:39:49.456][MutagenProcess    ][Info   ] [sync] Session manager initialized
[22:39:50.974][LoggingMessageHandler][Info   ] [1271f2ce] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[22:39:51.429][LoggingMessageHandler][Info   ] [1271f2ce] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 454ms)
[22:39:51.433][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[22:39:51.437][LoggingMessageHandler][Info   ] [f927e18a] <BackendAPIClient start> POST http://backend/hyperv/stop
[22:39:51.557][LoggingMessageHandler][Info   ] [f927e18a] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 119ms)
[22:39:51.594][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[22:39:51.919][VpnKitBridge      ][Info   ] Started
[22:39:51.991][LoggingMessageHandler][Info   ] [659f5cc3] <Server start> GET http://unix/versions
[22:39:52.188][LoggingMessageHandler][Info   ] [659f5cc3] <Server end> GET http://unix/versions -> 200 OK (took 196ms)
[22:39:52.940][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:39:52.940][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:39:53.942][IsoConfig         ][Info   ] Generating CA Cert Bundle
[22:39:53.998][IsoConfig         ][Info   ] CA Cert Bundle Generated
[22:39:54.008][GoBackendProcess  ][Info   ] â‡¨ http server started on \\.\pipe\dockerVpnKitControl
[22:39:54.072][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[22:39:54.074][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[22:39:54.081][GoBackendProcess  ][Info   ] enabling filesystem caching
[22:39:54.081][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[22:39:54.086][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[22:39:54.090][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[22:39:54.090][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[22:39:54.090][GoBackendProcess  ][Info   ] using mfsymlinks
[22:39:54.104][GoBackendProcess  ][Info   ] â‡¨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[22:39:54.114][GoBackendProcess  ][Info   ] â‡¨ http server started on \\.\pipe\dockerBackendApiServer
[22:39:54.983][LoggingMessageHandler][Info   ] [114d0fa3] <BackendAPIClient start> POST http://backend/hyperv/create
[22:39:55.217][LoggingMessageHandler][Info   ] [114d0fa3] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 234ms)
[22:39:55.233][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[22:39:55.233][LoggingMessageHandler][Info   ] [df9be478] <BackendAPIClient start> POST http://backend/hyperv/stop
[22:39:55.248][LoggingMessageHandler][Info   ] [df9be478] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 15ms)
[22:39:55.260][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 13724
[22:39:55.289][LoggingMessageHandler][Info   ] [fe18baa8] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[22:39:57.189][LoggingMessageHandler][Info   ] [fe18baa8] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1900ms)
[22:39:57.198][LoggingMessageHandler][Info   ] [e2b78685] <BackendAPIClient start> GET http://backend/hyperv/check-virtualization
[22:39:57.234][LoggingMessageHandler][Info   ] [e2b78685] <BackendAPIClient end> GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 36ms)
[22:39:57.235][LoggingMessageHandler][Info   ] [2d8b4d97] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[22:39:57.286][LoggingMessageHandler][Info   ] [2d8b4d97] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 51ms)
[22:39:57.286][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[22:39:57.286][LoggingMessageHandler][Info   ] [2b87595b] <BackendAPIClient start> POST http://backend/hyperv/stop
[22:39:57.302][LoggingMessageHandler][Info   ] [2b87595b] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 15ms)
[22:39:57.317][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[22:39:57.334][VpnKitBridge      ][Info   ] Started
[22:39:57.334][IsoConfig         ][Info   ] Generating CA Cert Bundle
[22:39:57.370][IsoConfig         ][Info   ] CA Cert Bundle Generated
[22:39:57.533][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:39:57.535][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:39:59.902][LoggingMessageHandler][Info   ] [c86db2c9] <BackendAPIClient start> POST http://backend/hyperv/create
[22:39:59.953][LoggingMessageHandler][Info   ] [c86db2c9] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 50ms)
[22:39:59.953][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[22:39:59.953][LoggingMessageHandler][Info   ] [c09eb4af] <BackendAPIClient start> POST http://backend/hyperv/stop
[22:39:59.972][LoggingMessageHandler][Info   ] [c09eb4af] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 18ms)
[22:39:59.979][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 12800
[22:39:59.993][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[22:39:59.993][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[22:39:59.993][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[22:39:59.993][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1591303199}
[22:39:59.994][SystrayNotifications][Error  ] Unhandled exception: La séquence ne contient aucun élément.
[22:40:00.050][GUI               ][Info   ] Sending Bugsnag report 2c04e7e8-2f6f-4470-9db9-fd70ddf8d2ad...
[22:40:00.184][GUI               ][Info   ] Bugsnag report 2c04e7e8-2f6f-4470-9db9-fd70ddf8d2ad sent
[22:40:00.185][SegmentApi        ][Info   ] Usage statistic: eventCrash
[22:40:00.190][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[22:40:00.386][Engines           ][Error  ] Start failed with Unhandled exception: La séquence ne contient aucun élément.
   à Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:ligne 17
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:ligne 37
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:ligne 93
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:ligne 57
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:ligne 29
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 67
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 36
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:ligne 72
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Docker.Engines.Engines.<StartAsync>d__24.MoveNext() dans C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:ligne 109)
[22:40:00.778][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[22:40:00.779][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[22:40:00.780][GoBackendProcess  ][Info   ] mutagen sync list --output json
[22:40:00.990][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[22:40:00.991][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\

**Comment by mat007** [comment] 2020-06-05 04:30
Duplicate of #6007

**Closed by mat007** 2020-06-05 04:30 UTC
Labels: version/2.3.0.3
