### ISSUE TITLE
Upgrade to 3.3.3 breaks WSL2 GPU - Nvidia-Container-CLI initialization error

### ISSUE THREAD

**Issue by bnapora** [docker/for-win#11309] opened 2021-05-26 17:18 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 2203EF72-C69C-4192-B9CE-62DAE2FD9774/20210526170227

### Actual behavior
Containers dependent on Nvidia GPU no longer start up.  Containers with no GPU dependency do start-up.  When starting containers using GPU get the following error:
OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown

On NVidia support forum, the solution seems to be to downgrade Docker for Desktop to version 3.3.0
I can't figure out how to downgrade Docker.

### Expected behavior
Run containers dependent on Nvidia GPU

### Information

  - Windows Version: Build 21382.co_release.210511-1416
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Install Docker Desktop for Windows 3.3.3
  2. ...

**Comment by stephen-turner** [comment] 2021-05-27 09:10
Thanks, I think this is a dupe of #11246.

**Closed by stephen-turner** 2021-05-27 09:10 UTC
