### ISSUE TITLE
"Restart docker..." button removes all images and volumes

### ISSUE THREAD

**Issue by fmasa** [docker/for-win#290] opened 2016-12-05 15:26 UTC
### Expected behavior
_"Restart docker..."_ button restarts VM without deleting everything. Every pre-beta31 version worked that way.
### Actual behavior
_"Restart docker..."_ button removes all images and volumes.

### Information
Diagnostic ID: 21BA5754-F71A-41EF-9AB8-5CBE69D11D11/2016-12-05_16-17-54

### Steps to reproduce the behavior

  1. Start container with data volume (e.g. https://hub.docker.com/_/mysql/)
  2. Fill your volume with precious development data
  3. Hit _"Restart docker..."_ and lose you precious work 😆

**Comment by rneugeba** [comment] 2016-12-05 16:49
@fmasa I can't reproduce this. When I restart Beta31 the images I had before are still present afterwards. So at least on my system the images are still there.

You also mention mentioned volumes...could you give a concrete example to reproduce?

thanks

**Comment by fmasa** [comment] 2016-12-05 16:51
Sure, I'll try provide more accurate Steps in a few hours.

**Comment by dgageot** [comment] 2016-12-05 23:43
@fmasa Could you have clicked in "Reset to Factory Default" by mistake?

**Comment by justgos** [comment] 2016-12-06 08:45
I have the same problem.
Two times in a row actually : / so I'm sure it was "Restart", not "Reset" )

After the first time I'd:
1. pulled jupyter/minimal-notebook
2. installed some staff on it
3. committed as a new version
4. pressed "Restart Docker"
5. got additional ~8 GB free space on hdd and only one Docker image - "d4w/nsenter

Diagnostic ID: 7804DFFB-7C12-4CD3-B6CA-A82AEEB28E40/2016-12-06_10-39-40

**Comment by dgageot** [comment] 2016-12-06 11:51
@fmasa @justgos You are right, this is actually a huge bug. When the VM fails to stop properly, we have to force kill it. We also added a piece of code that deletes the VM to be sure we didn't introduce some corruption when we killed the VM's process. This new piece of code introduced in Beta31 has a huge bug. It also deletes the data disk with the VM.
This is going to be fixed quickly in the Beta that should be out today or tomorrow.

**Comment by BDvirus** [comment] 2016-12-06 12:51
hi @dgageot 
I can also confirm that it's happens to me, also with Beta31.
It's unpleasant.. :( but this is what it is..
I realy hope it's is going to be fixed quickly in the next Beta.
And other interesting thing...
When I switch to "Windows Containers" all of the windows container where there :)
So half of comfort.. only the linux containers gone..

**Comment by simonferquel** [comment] 2016-12-06 13:27
A fix is on its way for the next beta (hopefully this week). Sorry for the inconvenience !

**Comment by rlpowell** [comment] 2016-12-06 16:29
Oh dear.  I routinely end up with stuck files, on probably an at-least-daily basis.  That is: files in a shared (-v volume mount) directory that cannot be deleted, on the docker or windows sides. (As I mentioned in another ticket: this is so common that I assumed you knew about it; let me know if I should open a ticket.)   I have to reboot to fix this.  I suspect that rebooting in that case *also* requires a force shutdown.  So this means that every time I get a stuck file, I'm going to lose my images, which take 2+ hours and a good network (which I often don't have on my laptop) to recreate.  That's ... unfortunate.   Let me know if I can help with testing or anything.

**Comment by rlpowell** [comment] 2016-12-06 16:33
Actually: can I *downgrade* to remove this behaviour?  That would be really really nice.  Actually, since all my images are gone, I suppose I could just uninstall and install an older beta.

**Comment by rlpowell** [comment] 2016-12-06 16:35
Hmm.  No way to get older betas.  Not sure if this is worth downgrading to stable if y'all are going to have it done in the next day or two.

**Comment by rneugeba** [comment] 2016-12-08 12:14
Beta32 shipped yesterday and it should fix this issue. Please re-open if you still have the same issue.

**Closed by rneugeba** 2016-12-08 12:14 UTC
Labels: area/hyper-v, status/3-fixed

**Comment by rlpowell** [comment] 2016-12-09 07:20
Well, the installation of Beta32 triggered this issue, so that was unpleasant (but not unexpected).  Time to rebuild everything again wee!
