### ISSUE TITLE
vpnkit huge memory consumption 

### ISSUE THREAD

**Issue by CdeMills** [docker/for-win#2015] opened 2018-05-08 14:17 UTC
Hello,
context: Windows 10 platform,
Version: 18.03.0-ce
API version: 1.37
Go version: go1.9.4
Git commit: 0520e24
Built: Wed Mar 21 23:06:28 2018
OS/Arch: windows/amd64
Experimental: false
Orchestrator: swarm

The docker container is based on fedora27, created as
docker create -t --name fedora --publish 2242:22 --publish 4732:3389 --init --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -cap-add=NET_ADMIN --device=/dev/net/tun fedora27 /usr/bin/systemctl

with systemctl coming from https://github.com/gdraheim/docker-systemctl-replacement

The only enabled service is sshd; once the container is started I launch a graphical session with x2go server and a get a full linux environment running on top of Windows10.

After around two hours, the hard disk start doing continuous noise, and vpnkit.exe (in Windows) start consuming all the disk bandwidth. At this time the x2go client becomes unresponsive and disconnects. The only option is to stop the container, kill vpnkit, stop docker. Sometimes the x2go client becomes unresponsive too, requiring a machine reboot.

This occured two times this week.

Is there some way to limit vpnkit memory consumption ?

Regards

Pascal

**Comment by rn** [comment] 2018-05-08 14:33
@CdeMills thanks for the report. This looks like a dup of https://github.com/docker/for-win/issues/1932 and is already tracked in the upstream vpnkit repository https://github.com/moby/vpnkit/issues/371 so I'm closing this here.

However, it would be great if you could provide as detailed as possible reproduction steps on the VPNKit issue linked above, ideally with a Dockerfile and exact commands so that we could reproduce the setup without too much guessing. Thanks

**Closed by rn** 2018-05-08 14:33 UTC

**Comment by apm963** [comment] 2018-05-08 18:58
@rn The minimum requirement to reproduce this issue is to add a Docker for Windows 18.03.* node to a swarm. I have confirmed the memory leak occurs even when there are no swarm containers running. At the beginning, the leak causes memory to climb by approx. 0.1 MB every 10 or so seconds. After a few hours it can get up to 1 MB per second or more. There are more details in the linked issue.

**Comment by hillyu** [comment] 2018-05-21 08:05
facing the same problem. Using docker CE 18.03 non-swam, vpnkit used up almost all the available
 memory.
