### ISSUE TITLE
Auto-Updated pre-requisite for 17.05.0-ce-rc1-win8 (11189) fails on Windows 10 

### ISSUE THREAD

**Issue by gleeds** [docker/for-win#640] opened 2017-04-13 22:26 UTC
### Expected behavior
Updater updates Docker for Windows to the new version.

### Actual behavior
The following error message is given:
![image](https://cloud.githubusercontent.com/assets/1095404/25026253/4e2b0986-206b-11e7-8637-ef7d6becf3a0.png)

### Information

  - Diagnostic ID: 0D3C54A3-3636-471C-8D1D-8AE541CFDADF/2017-04-13_17-24-17
  - Windows Version: Windows 10 Enterprise N Version 1607 (OS Build 14393.953)
![image](https://cloud.githubusercontent.com/assets/1095404/25026782/e2164d66-206d-11e7-9dc2-f5925ffa9ac6.png)

### Steps to reproduce the behavior

  1. Have 17.04.0-ce-win7 (10981) installed on Windows 10 Enterprise N Version 1607
  2. Accept prompt to update
  3. Click Yes when asked to elevate to Administrator privileges
  4. Get the above error after a few seconds

**Comment by mgw854** [comment] 2017-04-15 01:20
I can reproduce on Windows 10 Education build 16176 coming from the same Docker version (10981).

**Comment by MichaelSL** [comment] 2017-04-16 21:51
I have the same issue on Windows 10 Pro N v1703 Build 15063.138

**Comment by vriesmarcel** [comment] 2017-04-20 17:36
I am running on windows creators update, windows 10 pro and see also this error and am unable to run the edge channel :-( 
Is there any way I can pass in at command line to skip this version check, which seems to be flawed?
version number the os is:
ver: Microsoft Windows [Version 10.0.15063]

thanks!

**Comment by Patrock** [comment] 2017-05-03 09:21
I have the same problem with edge channel updates to 17.05.0-ce-rc1-win8 on Windows 10 Education build Version 1607 and now 1703 (Creators update)...

**Comment by vicenterusso** [comment] 2017-05-03 16:30
Same problem with Windows 10 Enterprise
Version 1607
Build 14393.1066

**Comment by simonferquel** [comment] 2017-05-04 07:49
Thanks for reporting the issue, we are actively tracking it and it should be fixed in an upcoming Edge build.

**Comment by rn** [comment] 2018-03-10 14:43
I think this is fixed so closing

**Closed by rn** 2018-03-10 14:43 UTC
Labels: area/installer, status/1-acknowledged
