### ISSUE TITLE
Docker desktop factory reset after reboot

### ISSUE THREAD

**Issue by FranciscoNabas** [docker/for-win#11284] opened 2021-05-24 01:11 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I perform a clean installation on my Windows 10 20H2 host, set up the containers and everything works like it should.
When i reboot the machine, docker daemon does not start and there is nothing on the console.
No images, no containers, no compose and all the settings went back to factory.
Tried reinstalling, even running a deep clean on Windows to remove any Docker trace.
When i right click on the taskbar icon, it appears only 'Dashboard' and 'Settings', after a fresh install and after the reboot.
### Expected behavior
To keep everything after reboot.
### Information

  - Windows Version: 10 Pro 20H2
  - Docker Desktop Version: Docker version 20.10.6, build 370c289
  - WSL2 or Hyper-V backend?  Tried on both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Create containers either through CLI or compose
  3. Reboot the machine

P.S.: Also tried to set up a shutdown script to gracefully stop the containers before shutting down.

**Comment by stephen-turner** [comment] 2021-05-24 09:20
Thanks for the report, I believe this is a dupe of https://github.com/docker/for-win/issues/11047. There is a test build on that ticket that you can try.

**Closed by stephen-turner** 2021-05-24 09:20 UTC

**Comment by FranciscoNabas** [comment] 2021-05-24 09:48
Thank you very much! Will try it
