### ISSUE TITLE
Unable to start Docker desktop in Windows 11 Home

### ISSUE THREAD

**Issue by aanburaj** [docker/for-win#14089] opened 2024-05-22 12:18 UTC
### Description

Hi Folks,

When I try tp run the Docker after installing, I get the below error. Please help

An unexpected error occurred
Docker Desktop was unable to gather information about the current error. This most likely means that the services supporting Docker Desktop have exited unexpectedly

connect ENOENT \\.\pipe\errorReporter

### Reproduce

Docker run

### docker version

```bash
Not sure
```

### docker info

```bash
Not sure
```

### Diagnostics ID

6958EF88-F0B8-4C3A-BA5C-C0C1D5D13B45/20240522120620

**Comment by karman-docker** [comment] 2024-05-22 12:22
duplicate of  https://github.com/docker/for-win/issues/14084.
You should be able to resolve it following the instructions here https://github.com/docker/for-win/issues/14084#issuecomment-2122353807

**Comment by aanburaj** [comment] 2024-05-22 13:00
Thanks a ton!!!! It worked!!

Regards,

Antony

**Comment by aanburaj** [comment] 2024-05-22 13:01
Closing this as the issue is resolved

**Closed as completed** 2024-05-22 13:01 UTC
Labels: needs-triage, version/4.30.0
