### ISSUE TITLE
Docker refuses to let the user decide image location!

### ISSUE THREAD

**Issue by Sil3ntStorm** [docker/for-win#13011] opened 2022-10-12 19:29 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker refuses to let the user have control of their system and its resource allocation.
It fails to start complaining about the user attempting to use brute force to make the software behave correctly, due to the software in question lacking features to let the user decide which resources are being used.

```
System.Exception:
Path contains symlink: C:\ProgramData\Docker
   at Docker.Core.PermissionUtils.CheckPath(String path, Boolean allowDockerAppData) in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 284
   at Docker.Backend.HttpAPI.WindowsContainersController.FixPermissions(String path) in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 109
   at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 77
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected behavior
The software starts and functions correctly while respecting the choice of the user as to which location is used to store billions of bytes of data.
In a non shady behaving software, the software would offer the user the **choice** of where billions of bytes of data are stored, instead of going out of their way to actively sabotage the user!

### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 4.12.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

1. symlink C:\ProgramData\Docker to somewhere else, since Docker in its eternal wisdom refuses to offer the user a choice of where billions of bytes are consumed.
2. Switch to using Windows Containers.

**Comment by nicks** [comment] 2022-10-12 20:13
Sorry that this is so frustrating. I'm going to mark this as a duplicate of the roadmap item here - https://github.com/docker/roadmap/issues/94.

Sadly, it's not quite as simple as creating a symlink to the location where you want to install, and I think the discussion there better expresses the behavior you want.

**Closed by nicks** 2022-10-12 20:13 UTC

**Comment by Sil3ntStorm** [comment] 2022-10-12 20:23
I am going to look forward to the explanation of what could possibly ever be so complicated about  **__not__ actively** working **against** the user, or providing a UI option. Not doing anything in the first place would've likely been perfectly fine and working.

**Comment by mat007** [comment] 2022-10-13 07:02
@nicks I believe [docker/readmap#94](https://github.com/docker/roadmap/issues/94) is about the installation folder, whereas this issue, if it mentions it, is more about the location of the data folder for WSL 2.
We have an option in the UI on Mac and on Windows with Hyper-V to customize this location, but for historical reasons there isn’t one for WSL 2. We do have an internal ticket to address this though.

@Sil3ntStorm we’re rejecting symlinks for security reasons, as it was raised in a security audit that this could be used by attackers to delete any file on disk.

**Comment by Sil3ntStorm** [comment] 2022-10-13 08:48
@mat007 that is correct, I care about where docker stores the downloaded images, which is about 90% of the data used by docker. Installation directory is fine to configure as well of course and should be in every application before it ever being released publicly as far as I am concerned.

As for the "security concerns": If the user symlinks their directories then yes just delete the stuff that's in there is an expected behavior? Just showing a warning "Hey there are symlinks, are you sure you want to do this?" would have been fine. But outright refusing to work is a total no go, especially for such a heavy hitter in terms of storage space as docker is. Infinitely more so when you don't offer an option to let the user choose.

As for the workaround: NO that does NOT solve anything (I already attempted that before reporting)! That merely frees you about one GB, which is only like 1% of the space consumption by docker. I literally spent a day messing around attempting to make docker behave properly. It completely killing itself more than once attempting to make it happen, and having to reinstall the application multiple times over does not help.

To be absolutely clear: The location for the downloaded images (`FROM foo` in a dockerfile) and all their dependencies as well as those locally created absolutely MUST be configurable and it MUST be allowed to store them on ANY location.

**Comment by mat007** [comment] 2022-10-24 09:31
Here is the correct roadmap issue actually: https://github.com/docker/roadmap/issues/239
