### ISSUE TITLE
Docker desktop for Windows isn't starting since lastest update (3.x)

### ISSUE THREAD

**Issue by Geekimo** [docker/for-win#9784] opened 2020-12-12 16:08 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 128DD0BA-7C48-4326-8B43-B4AE4A584D37/20201212155730

### Expected behavior
Docker Desktop is expected to start
### Actual behavior
Docker Desktop isn't starting
### Information

  - Windows Version: Windows 10 2004
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. From the latest 2.x version, update to 3.x with the integrated updater
  2. Then it wont start.

**Comment by Geekimo** [comment] 2020-12-12 16:18
In addition, after resetting to factory defaults, it works.

**Comment by adampwright** [comment] 2020-12-12 19:11
> In addition, after resetting to factory defaults, it works.

Same issue and same result.

**Comment by 3B9ACA00** [comment] 2020-12-13 03:31
Same issue
7959BDE6-4FB8-4C25-9954-C451DC366718/20201213032409

**Comment by b-hayes** [comment] 2020-12-13 08:47
I had the same thing https://github.com/docker/for-win/issues/9757

I had to reinstall docker and then it worked for a day. BUt today just booted my machine again and ALL my containers are gone and docker is crashing.

This is pretty bad. I'll have to rebuild 16 containers every day before I can do my job.

The most recent upload id:
A9921648-B713-4F74-8F3F-F67D175A8613/20201213083941

**Comment by grig0ry** [comment] 2020-12-14 06:45
Same issue. Downgrade to 2.5.0.0 temporary fixed this problem.

**Comment by myshon** [comment] 2020-12-14 08:42
How to download 2.5.0.0?

**Comment by grig0ry** [comment] 2020-12-14 08:52
@myshon https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2500

**Comment by b-hayes** [comment] 2020-12-15 21:04
Also, you have to get 2.5.0.0 as the 2.5.0.1 link gives you 3.0 lol. Docker is so reliable. 😒

**Comment by phickox** [comment] 2020-12-17 14:05
Mine will start (almost) every time. But then after about 20 minutes or 3-5 commands, it simply locks up. I run a command which has run dozens of times before and poof. Other times, it will lock up on another one.  Sometimes the Docker Desktop also gets lost and the dashboard will launch, but can't see any images.  Only thing working at the moment is quitting and relaunching.  It took 6 cycles to do my last push because it kept hanging in the middle.   
At the moment, I just did a factory reset and it locked up on a tag command but in another console I can run images and the dashboard can still see the image - which is new - normally once it hangs, everything hangs.
Guess I'm going to have to uninstall as well and downgrade.   Before the upgrade to 3.0, it would run for days or weeks with no problems.

**Comment by tiborvass** [comment] 2020-12-20 01:04
@Geekimo I verified your diagnostics ID, and it seems you are hitting #9755. Closing as dupe of #9755 which has a workaround at #9755 (comment)

**Closed by tiborvass** 2020-12-20 01:04 UTC
