### ISSUE TITLE
Shared Volumes Slow

### ISSUE THREAD

**Issue by coccyx** [docker/for-win#209] opened 2016-11-07 18:55 UTC
### Expected behavior
Running I/O intensive task (in this case, `govendor sync`) should be only marginally slower than running on a native filesystem.

### Actual behavior
In my case, running the I/O intensive task is slow enough to be almost unusable.

### Information

- Windows 10, Anniversary Update

### Steps to reproduce the behavior

Happy to run any benchmarks or look to see if there's any tunables I can set to try to better reproduce the behavior.  I didn't see any similar issues here, so I decided to start this as a placeholder we can fill in.

**Comment by friism** [comment] 2016-11-07 19:02
@coccyx I suspect this is a duplicate of https://github.com/docker/for-win/issues/150 - do you mind if I close this issue and track this on 150?

**Comment by coccyx** [comment] 2016-11-07 20:04
Sure, if we can isolate to networking, that makes sense, but that issue did not have anything specific to volumes.

**Comment by friism** [comment] 2016-11-07 21:24
@coccyx do you have a command we can use to reproduce, eg. using a piece of open source Go code or similar? Also, is this using a volume mount? In that case, the disk I/O will be going over the guest/host network.

**Comment by dimasnake** [comment] 2016-11-08 20:43
I think this is a duplicate of https://github.com/docker/for-win/issues/188

**Comment by whitecolor** [comment] 2016-11-27 13:26
This issue has is more appropriate name then #188

There is also alike issue in docker for mac: https://github.com/docker/for-mac/issues/77

I also experience this for example with `git`, when I attach as volume some folder and make `git` operations on it, with quite large code base speed of operation is significantly slower then on dev machine.

To reproduce it you may just take some image with GIT installed and attach some big repo and try do do `git status`.

**Comment by dgageot** [comment] 2016-12-03 14:37
I'm going to close this ticket as a duplicate of #188 (which was given a more appropriate title)

**Closed by dgageot** 2016-12-03 14:37 UTC
Labels: area/volumes, kind/performance, status/0-triage
