### ISSUE TITLE
Cannot change to Windows Containers

### ISSUE THREAD

**Issue by friism** [docker/for-win#356] opened 2016-12-26 16:01 UTC
Diagnostics: 0C170A20-248A-4C0B-B759-49C82718AA77/2016-12-26_10-55-12

![image](https://cloud.githubusercontent.com/assets/126104/21484053/8766d0c4-cb5a-11e6-9910-13f6c795b17c.png)

I think my Windows 10 might be in a weird state:

![image](https://cloud.githubusercontent.com/assets/126104/21484057/94665f06-cb5a-11e6-8152-e244ee6172c6.png)

**Comment by friism** [comment] 2016-12-26 16:16
A restart fixes the problem it seems. Leaving issue open for now in case this should be made more durable

**Comment by rneugeba** [comment] 2016-12-28 18:08
@friism thanks for the report. Your system indeed looks like in a weird state with no windows features listed at all. I see you are on insider build 14971 (which is not the latest, I'm on 14986) and I can't reproduce this, so I'm closing this as there is very little we can do in terms of debug (your reboot seem to have fixed whatever issue there was)

**Closed by rneugeba** 2016-12-28 18:08 UTC
Labels: area/wincon, area/windows
