### ISSUE TITLE
Unable to map container port to random host port

### ISSUE THREAD

**Issue by docknight** [docker/for-win#10673] opened 2021-03-16 15:04 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
With the latest version of Docker Desktop I'm unable to run containers with a container port mapped to random host port.
Example:
`docker run -p 1433 -e ACCEPT_EULA=Y -d $InternalDockerRegistryUrl/valu-database:local`

The command fails with the following message:
`91fa68a89f1df0607b696428687dc8481054ce400723e4d70ec311b039aa7657
docker: Error response from daemon: failed to create endpoint zealous_knuth on network nat: Windows does not support host IP addresses in NAT settings.`

### Expected behavior
The container should start with port mapped to a random port on the host machine.
No explicit host IP address should be assigned automatically.

### Information
The following command works as expected:
`PS C:\Users\**********> docker run -p 55000:1433 -e ACCEPT_EULA=Y -d $InternalDockerRegistryUrl/valu-database:local
f8988c4db0f77a825b9023c656a6a3106bc67188cc1d581f2282704837506d5e`
`PS C:\Users\**********> docker ps
CONTAINER ID   IMAGE                                              COMMAND                  CREATED         STATUS                            PORTS                     NAMES
f8988c4db0f7   *******************/valu-database:local   "powershell -Command…"   6 seconds ago   Up 3 seconds (health: starting)   0.0.0.0:55000->1433/tcp   jolly_kepler`

Also, if I don't provide the container port explicitly, random port mapping works as expected.
`PS C:\Users\**********> docker run -P -e ACCEPT_EULA=Y -d $InternalDockerRegistryUrl/valu-database:local
20de6015834fdb31b51a59429da4b8099c900da29676dcb341957a88a81cced2`
`PS C:\Users\**********> docker ps
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                    PORTS                     NAMES
20de6015834f   *******************/valu-database:local   "powershell -Command…"   41 seconds ago   Up 38 seconds (healthy)   0.0.0.0:58014->1433/tcp   sleepy_buck`

  - Docker Desktop Version: 3.2.2. (Engine: 20.10.5)
  - WSL2

**Comment by stephen-turner** [comment] 2021-03-16 18:46
Thanks for the report, but closing as a dupe of #10552.

**Closed by stephen-turner** 2021-03-16 18:46 UTC
Labels: version/3.2.2.
