### ISSUE TITLE
DockerDesktopVM Clock Drift

### ISSUE THREAD

**Issue by cocowalla** [docker/for-win#5131] opened 2019-11-13 20:30 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
I expect that the `DockerDesktopVM` Hyper-V VM's clock, and that of containers, will keep in sync with the host.

### Actual behavior
After sleeping and resuming the host, I can see the incorrect time in containers, and get errors running `apt-get` in containers because of this.

If I check the state of the Hyper-V time sync service, it says it's OK:
```powershell
Get-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization"
```

The only way I have found to fix this is to restart Docker Desktop - but is a time-consuming task.

### Information

  - Windows Version: Windows 10, 1903
  - Docker Desktop Version: 2.1.5.0 Edge (but this has been an issue forever)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Sleep the host for some hours
  3. Resume the host
  4. Run any container, and check the time in it - it's very wrong

**Comment by LaurentLesle** [comment] 2019-12-04 16:33
Same issue of time drift with the edge version 2.1.6.1 with wsl2 based engine. mainly due to hybernate

**Comment by twodrops** [comment] 2019-12-18 16:53
Also with Edge version 2.1.7.0

**Comment by aaronadamsTO** [comment] 2020-01-14 18:36
I am experiencing a similar, but slightly different, problem on 2.1.7.0.

My Debian VM's clock appeared to reset itself to midnight. I don't believe it was caused by hibernation; I was editing documents when suddenly I could no longer save, because I was trying to overwrite "newer" files:

```
$ date
Tue Jan 14 00:02:38 UTC 2020
$ ls -al --full-time
total 0
drwxrwxrwx 1 root root    0 2020-01-14 16:30:46.704288200 +0000 .
drwxrwxrwx 1 root root 4096 2020-01-14 16:30:42.693718300 +0000 ..
-rwxr-xr-x 1 root root   65 2020-01-14 16:31:26.803354900 +0000 footer.html
```

It's happened to me two or three times now.

The following commands in an elevated PowerShell immediately resolve the issue without restarting Docker Desktop (credit to @ThorstenHans for [the idea](https://thorsten-hans.com/docker-on-windows-fix-time-synchronization-issue):

```
Disable-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization"
Enable-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization"
```

**Comment by aaronadamsTO** [comment] 2020-02-03 16:55
I'm now on 2.2.0.0 (42247) stable, and I'm also experiencing time drift on sleep (in addition to the midnight reset).

The same elevated PowerShell commands work to restore the correct container time, but if I forget to run this script on resume, Git commits during that period have the wrong timestamp, which is very frustrating.

**Comment by mat007** [comment] 2020-02-03 17:09
Thanks for the report @aaronadamsTO , I believe for 2.2.0.0 this is tracked in #5593

**Comment by aaronadamsTO** [comment] 2020-02-18 16:44
I agree this can be tracked in https://github.com/docker/for-win/issues/5593 and this ticket can be closed - but I also think it's worth looking into why this bug made it into stable after so many users reported problems on Edge. Thanks.

**Comment by stephen-turner** [comment] 2020-03-25 17:59
Dupe of #5593 and #4526, closing.

**Closed by stephen-turner** 2020-03-25 17:59 UTC
Labels: version/2.1.5.0 Edge
