### ISSUE TITLE
iptables update issue

### ISSUE THREAD

**Issue by avanzarit-in** [docker/for-win#517] opened 2017-02-22 19:31 UTC
### Information
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by dgageot** [comment] 2017-02-23 09:29
@avanzarit-in This is not a Docker for Windows issue. `iptables` can't run in an unprivileged container. Your should run with `docker run --cap-add=NET ...`
Please close this issue if it works for you.

**Comment by rneugeba** [comment] 2017-02-27 01:40
could you please provide a full docker command line and reproduction ideally with a diagnostics ID.
thanks

**Comment by rneugeba** [comment] 2017-03-08 16:11
Closing due to inactivity. Please reopen if you have a command line and tried a priv container.

**Closed by rneugeba** 2017-03-08 16:11 UTC
Labels: status/0-more-info-needed, status/0-wont-fix

**Comment by roens** [comment] 2019-07-21 20:46
I'm seeing this too…

```
root@pine64:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
root@pine64:~# uname -a
Linux pine64 3.10.107-pine64 #2 SMP PREEMPT Wed Jul 17 05:36:01 UTC 2019 aarch64 GNU/Linux
```

From a freshly built Armbian image, described above, I've (as `root`):

```
apt install apparmor-utils apt-transport-https avahi-daemon ca-certificates curl dbus jq network-manager scout
apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository "deb https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt update
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/arm64/containerd.io_1.2.6-3_arm64.deb
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/arm64/docker-ce-cli_18.09.8~3-0~debian-buster_arm64.deb
wget https://download.docker.com/linux/debian/dists/buster/pool/stable/arm64/docker-ce_18.09.8~3-0~debian-buster_arm64.deb
dpkg -i *.deb
systemctl unmask docker.socket
systemctl unmask docker.service
```

Here's where things aren't starting well:
```
root@pine64:~# service docker status
* docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-07-21 20:13:34 UTC; 30min ago
     Docs: https://docs.docker.com
  Process: 8441 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 8441 (code=exited, status=1/FAILURE)

Jul 21 20:13:34 pine64 systemd[1]: docker.service: Service RestartSec=100ms expired, scheduling restart.
Jul 21 20:13:34 pine64 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Jul 21 20:13:34 pine64 systemd[1]: Stopped Docker Application Container Engine.
Jul 21 20:13:34 pine64 systemd[1]: docker.service: Start request repeated too quickly.
Jul 21 20:13:34 pine64 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 21 20:13:34 pine64 systemd[1]: Failed to start Docker Application Container Engine.
```

And so I've tried starting `dockerd` manually:
```
root@pine64:~# /usr/bin/dockerd -H unix:///lib/systemd/system/docker.socket
INFO[2019-07-21T20:45:02.416804461Z] libcontainerd: started new docker-containerd process  pid=9245
INFO[2019-07-21T20:45:02.417265764Z] parsed scheme: "unix"                         module=grpc
INFO[2019-07-21T20:45:02.417393142Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-07-21T20:45:02.417901988Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]  module=grpc
INFO[2019-07-21T20:45:02.418058533Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-07-21T20:45:02.418479835Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420070f00, CONNECTING  module=grpc
INFO[0000] starting containerd                           revision=468a545b9edcd5932818eb9de8e72413e616e86e version=v1.1.2
INFO[0000] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[0000] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.zfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[0000] could not use snapshotter zfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[0000] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd-debug.sock"
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd.sock"
INFO[0000] containerd successfully booted in 0.030181s  
INFO[2019-07-21T20:45:02.534379463Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420070f00, READY  module=grpc
INFO[2019-07-21T20:45:02.546506214Z] parsed scheme: "unix"                         module=grpc
INFO[2019-07-21T20:45:02.546670384Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-07-21T20:45:02.546965475Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]  module=grpc
INFO[2019-07-21T20:45:02.547046893Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-07-21T20:45:02.547285649Z] pickfirstBalancer: HandleSubConnStateChange: 0x442025a3b0, CONNECTING  module=grpc
INFO[2019-07-21T20:45:02.548172087Z] pickfirstBalancer: HandleSubConnStateChange: 0x442025a3b0, READY  module=grpc
INFO[2019-07-21T20:45:02.562190634Z] [graphdriver] using prior storage driver: aufs 
INFO[2019-07-21T20:45:02.594952007Z] Graph migration to content-addressability took 0.00 seconds 
WARN[2019-07-21T20:45:02.595784027Z] Your kernel does not support swap memory limit 
WARN[2019-07-21T20:45:02.596335374Z] mountpoint for pids not found                
INFO[2019-07-21T20:45:02.600054338Z] parsed scheme: "unix"                         module=grpc
INFO[2019-07-21T20:45:02.603716385Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-07-21T20:45:02.604698409Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]  module=grpc
INFO[2019-07-21T20:45:02.604857954Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-07-21T20:45:02.605096001Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420070230, CONNECTING  module=grpc
INFO[2019-07-21T20:45:02.605923730Z] pickfirstBalancer: HandleSubConnStateChange: 0x4420070230, READY  module=grpc
INFO[2019-07-21T20:45:02.606379991Z] Loading containers: start.                   
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.2 (nf_tables):  TABLE_ADD failed (Invalid argument): table nat
 (exit status 4)
```

But maybe this is all an issue with `iptables`?
```
root@pine64:~# iptables -L
iptables v1.8.2 (nf_tables):  TABLE_ADD failed (Invalid argument): table filter
```

**Comment by rgalbo** [comment] 2019-08-09 23:22
same issue as @roens
