### ISSUE TITLE
Run Jar on WindowServer2016 with JDK 11-docker Image

### ISSUE THREAD

**Issue by GauravSaxena205** [docker/for-win#3666] opened 2019-04-01 18:30 UTC
I am very new to Dockers and trying to run my jar file on WindowsServer2016 with JDK 11. 
I am using Operating system: Windows 10 and successfully installed Dockers to it.

The issue is I am not able to run jar file on this image .

My Docker File attached
[Dockerfile.txt](https://github.com/docker/for-win/files/3030803/Dockerfile.txt)

**Comment by ulrich** [comment] 2019-04-02 10:14
Hello @GauravSaxena205

Can you try with a simple test before using your Dockerfile? Like this:

`docker run hello-world`

**Comment by GauravSaxena205** [comment] 2019-04-02 14:16
Hello-world is running good

![image](https://user-images.githubusercontent.com/14364562/55409593-25e6c400-5517-11e9-8ff0-29e80a474558.png)

is my docker file correct?
are these line correct for running a jar in dockerfile?
ADD SimpleInterest2.jar SimpleInterest2.jar
EXPOSE 8080
CMD ["java", "-jar", "SimpleInterest2.jar"]

**Comment by GauravSaxena205** [comment] 2019-04-02 20:48
I deleted all the existing docker images and tried again and jar file ran good.
![image](https://user-images.githubusercontent.com/14364562/55435110-07e88600-554e-11e9-9268-277e3efe5d7f.png)

**Comment by ulrich** [comment] 2019-04-02 21:04
@GauravSaxena205 so, the problem is not your Docker Desktop installation. It's a good news to see your Dockerfile run correctly. Can we close this issue?

**Closed** 2019-04-02 21:08 UTC
