### ISSUE TITLE
How to move ext4.vhdx to a non system disk?

### ISSUE THREAD

**Issue by xiajingren** [docker/for-win#7348] opened 2020-06-21 10:32 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. How to move C:\Users\Administrator\AppData\Local\Docker\wsl\data\ext4.vhdx to a non system disk?

**Comment by efelippe** [comment] 2020-06-21 17:54
Assuming that you are using "Docker Desktop WSL 2 backend"

Duplicate of #5829

Solution by @thijsputman [#5829 (comment)](https://github.com/docker/for-win/issues/5829#issuecomment-622442186)

Using Powershell/cmd
```
wsl --shutdown
wsl --export docker-desktop-data docker-desktop-data.tar
wsl --unregister docker-desktop-data
wsl --import docker-desktop-data X:\path\to\docker-desktop-data.tar --version 2
```

Where "X:" is the disk you want to move .vhdx to. 

As @thijsputman said:
> It's sufficient to move the docker-desktop-data WSL-distro. The other one (docker-dekstop) gets restored to its original location when you update Docker Desktop – it's small and doesn't grow in size when using Docker.

**Comment by stephen-turner** [comment] 2020-06-22 09:00
Thanks, @efelippe, closing as dupe.

**Closed by stephen-turner** 2020-06-22 09:00 UTC

**Comment by wutzebaer** [comment] 2020-06-26 16:23
the example is missing the target dir, for me this worked:
wsl --import docker-desktop-data D:\docker D:\docker\docker-desktop-data.tar --version 2

**Comment by efelippe** [comment] 2020-07-03 16:49
> the example is missing the target dir, for me this worked:
> wsl --import docker-desktop-data D:\docker D:\docker\docker-desktop-data.tar --version 2

My bad, thanks for correction. Edited my answer. 👍
