### ISSUE TITLE
Docker inventing IPv6 AAAA records based on v4 addresses.

### ISSUE THREAD

**Issue by keifgwinn** [docker/for-win#13197] opened 2023-01-26 16:11 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

``` 
  {
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

  - [x] I have uploaded Diagnostics

  - Diagnostics ID: B81118D0-36D1-4C87-8FA6-5B6E804D052A/20230126161125

### Actual behaviour

```
❯ docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host www.google.com'
www.google.com has address 142.250.187.196
www.google.com has IPv6 address 2a00:1450:4009:81f::2004
www.google.com has IPv6 address ::ffff:142.250.187.196

(execute same command from windows host (bind dns host command compiled for windows)
❯ host www.google.com
www.google.com has address 142.250.187.196
www.google.com has IPv6 address 2a00:1450:4009:81f::2004
```

**www.google.com has IPv6 address ::ffff:142.250.187.196** < this address is invented, and based on the ipv4

### Expected behaviour
No invented records returned

### Information

  - Is it reproducible?

Yes

  - Is the problem new?

Yes

  - Did the problem appear with an update?

Probably, I recently upgraded my local docker to the latest, and this wasn't occurring in the past. It wasn't noticed before, but ran into it when testing latest version of our software.

  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

`docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host www.google.com'`

`docker run -it ubuntu:focal bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host time.microsoft.com'`

  - Windows Version:
  
 Windows 11 22H2 Build 22621.1192 

  - Docker Desktop Version: 

Docker version 20.10.22, build 3a2c30b

  - WSL2 or Hyper-V backend?  
  
WSL2

  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  
No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
❯ & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2023-01-26T16:05:10.869998900Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behaviour

1. `docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host www.google.com'`

**Comment by thaJeztah** [comment] 2023-01-26 17:33
Looks like an IPv4-mapped IPv6 address; https://www.rfc-editor.org/rfc/rfc4291#section-2.5.5.2

Do you see the same if you use host -4 ... ?

**Comment by keifgwinn** [comment] 2023-01-27 10:28
> Looks like an IPv4-mapped IPv6 address; https://www.rfc-editor.org/rfc/rfc4291#section-2.5.5.2
> 
> Do you see the same if you use host -4 ... ?

```
❯ docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host -4 www.google.com'
www.google.com has address 142.250.187.196
www.google.com has IPv6 address 2a00:1450:4009:81f::2004
www.google.com has IPv6 address ::ffff:142.250.187.196
```

I first encountered it with this error from our licensing library activation code. 

```
SocketException: An address incompatible with the requested protocol was used
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <aa976c2104104b7ca9e1785715722c9d>:0 
  at SKGL.SKM.GetNetworkTime () [0x0002f] in <f6299139c0bd4170b9c124cec5f6c27d>:0 
  at SKGL.SKM.TimeCheck () [0x00000] in <f6299139c0bd4170b9c124cec5f6c27d>:0 
  at SKM.V3.ExtensionMethods.HasNotExpired (SKM.V3.LicenseKey licenseKey, System.Boolean checkWithInternetTime, System.Boolean allowUsagOnExpirationDate) [0x00031] in <f6299139c0bd4170b9c124cec5f6c27d>:0 
```

It's this line https://github.com/Cryptolens/cryptolens-dotnet/blob/839d327557c4d22dc3983be35f4cab6460ec690e/Cryptolens.Licensing/SKM.cs#L111 where it's attempting to go to time.windows.com for an NTP time check. However,  the line is trying to use an IPv6 address on an IPv4 connection.

**Comment by keifgwinn** [comment] 2023-01-27 10:59
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/23369849/215070284-536a411e-e78a-491c-96c2-6252c2b8a27b.png">
I did a tcp dump inside the container for time.windows.com to try and trace why it's putting v6 in v4 answers

**Comment by keifgwinn** [comment] 2023-01-27 11:16
As the error was intermittent, I ran the trace through a successful and a failed activation. It appears to be linked to the order that the answers come back in. Asking for A record for time.windows.com in the request ( number 17) time.windows.com came back A first and the activation succeeded, and then in 37 it came back AAAA first, and the activation failed.

<img width="2128" alt="image" src="https://user-images.githubusercontent.com/23369849/215073379-90be6a4b-b6e3-4941-a084-0dc141816f74.png">

**Comment by keifgwinn** [comment] 2023-01-27 12:04
I ran the same test on an m1 mac with docker 4.12.0 (85629) installed

![image](https://user-images.githubusercontent.com/23369849/215082326-06efb62c-4157-4059-b3f9-f256e180baac.png)

and I don't get the v6 addresses back.

**Comment by keifgwinn** [comment] 2023-01-30 16:00
I saw 4.16.3 was out so I retested under that, still getting these phantom IPv6 dns results

```
❯ docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host -4 time.windows.com'
time.windows.com is an alias for twc.trafficmanager.net.
twc.trafficmanager.net has address 51.145.123.29
twc.trafficmanager.net has IPv6 address ::ffff:51.145.123.29
❯ docker run -it ubuntu bash -c 'apt-get update > /dev/null 2>&1 ; apt-get install -y bind9-dnsutils > /dev/null 2>&1  ; host -4 time.windows.com 8.8.8.8'
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

time.windows.com is an alias for twc.trafficmanager.net.
twc.trafficmanager.net has address 51.145.123.29
```

**Comment by keifgwinn** [comment] 2023-02-28 12:40
this is still occuring in Docker Desktop 4.17.0 (99724)

**Comment by thaJeztah** [comment] 2023-06-23 09:16
I marked this ticket as "frozen" to prevent it being automatically closed, and asked some colleagues that are more familiar with the networking stack to at least have a look (whether or not it's intentional, unexpected or otherwise)

**Comment by akerouanton** [comment] 2023-06-23 10:42
@keifgwinn I'm able to reproduce this issue with Docker Desktop v4.17.0, but not with the latest release (v4.20.1). Can you try to upgrade and check if you're still able to reproduce it?

**Comment by keifgwinn** [comment] 2023-06-23 15:07
@akerouanton Unfortunately the PC I was using for this previously has died, and it was a work computer for a company I'm no longer with so I don't have a PC to test this with at the moment.

**Comment by akerouanton** [comment] 2023-06-23 15:09
OK, in that case let's consider it's been fixed in the latest release. If anyone else come here and can reproduce the original issue with Docker Desktop v4.20.1 or newer, ping me and I'll reopen it.

**Closed by akerouanton** 2023-06-23 15:09 UTC
Labels: area/network, lifecycle/frozen

**Comment by keifgwinn** [comment] 2023-06-26 10:51
@charence can you test this out with the latest docker and the 3drepo local project?

**Comment by keifgwinn** [comment] 2023-06-26 13:27
it's not happening on mac v4.20.1 at this time on my same home network.

**Comment by akerouanton** [comment] 2023-06-26 13:48
@keifgwinn Thanks for double-checking!
