### ISSUE TITLE
Update from 2.3.0.3 to 2.3.0.4 failed

### ISSUE THREAD

**Issue by mrsombre** [docker/for-win#7880] opened 2020-07-29 09:15 UTC
```
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/07/29 15:50:25.161
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\dbarsukov\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -k -p
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:50:25.300][ComponentVersions ][Info   ] Edition community
[15:50:25.329][Installer         ][Info   ] Killing processes...
[15:50:25.355][Installer         ][Error  ] Access is denied
[15:50:25.463] [UninstallWorkflow] Action CommunityInstaller.ExecAction failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
[15:50:25.467] [InstallWorkflow] Installation failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
[15:50:25.469] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[15:50:25.470] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by DarkTraveler** [comment] 2020-07-29 12:15
I also cannot install the latest version of Docker. It doesn't matter stable or edje

**Comment by mrsombre** [comment] 2020-07-29 13:04
I even can't uninstall the current version ;) Seems it will be with me for ages.

**Comment by maxtechera** [comment] 2020-07-30 16:35
This is bad!!
The latest update broke my current setup with WSL 2. 
Now I can't install this or previous version.
I was able to install version 2.1.0.1, I think this one does not include WSL2 integration so that might have something to do.

**Comment by DarkTraveler** [comment] 2020-07-30 16:40
@maxtechera 
Are you a windows insider by any chance? In my case, the problem is with updates to build OS 20175 and higher

**Comment by maxtechera** [comment] 2020-07-30 16:43
I am yes, currently on 20175.1000! Tho I have pending update to 20180.1000 I'm thinking on updating as a last resort.


I'm getting this error when updating which doesnt really tell me what's going on:

```  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()```

**Comment by DarkTraveler** [comment] 2020-07-30 16:46
@maxtechera on version 20180.1000 the problem remains :/

https://github.com/docker/for-win/issues/7890

**Comment by mrsombre** [comment] 2020-07-30 16:50
I'm not, as you can see in the log provided above.

**Comment by DarkTraveler** [comment] 2020-07-30 16:55
@maxtechera 

By the way, I just was able to run.
After 10 unsuccessful attempts, I thought to do reinstall windows.
But at the very last moment I changed my mind ...

1) We completely remove the Docker script via PoweShell
https://stackoverflow.com/questions/42161471/how-to-uninstall-docker-machine-under-windows-10/51167323#51167323

2) Run the latest Docker installation, I took 2.3.4.0
3) When installing, DO NOT select support for WSL2

4) Docker is installed ... and a notification appears at startup, about the start of the WSL2 subsystem, I don't understand how, but the launch still occurs

5) Docker itself did not completely start for me

6) You need to get to the settings and run hard reset

7) He just started, but unfortunately past manipulations cleared it :/ Nevertheless, I have already launched my working project
P/s I was able to run only through powershall: / through WSL hangs on deployment

8) Also check that the marks about integration with wsl 2 distributions have not gone off (Resources / Wsl integration)

9) maybe he's pretending ... that he works through wsl2 :)

**Comment by magneticflux-** [comment] 2020-07-30 18:43
I was able to install 2.3.0.4 (Stable) on Windows Insider build 20180.1000 following the steps in https://github.com/docker/for-win/issues/7880#issuecomment-666523319. I didn't have to remove any registry keys, I just deleted the Docker and Docker Desktop folders in ProgramData, Program Files, and AppData.

**Comment by maxtechera** [comment] 2020-07-30 19:25
@DarkTraveler @magneticflux- 
I was able to install last stable version on 20150 as well. Deleting all record of Docker even from registry, no idea why that didn't work the first time.

**Comment by metcalfc** [comment] 2020-07-31 21:42
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```

Docker on the Windows side (powershell, cmd, etc) will behave normally.

**Comment by stephen-turner** [comment] 2020-08-03 13:44
Closing this ticket, as it is a Windows bug not a Docker bug. Please follow microsoft/WSL#5648 for updates.

**Closed by stephen-turner** 2020-08-03 13:44 UTC
Labels: version/2.3.0.3
