### ISSUE TITLE
Need to have Docker Containers (HyperVisor) enabled by default on a clean install of Docker for Windows 10.

### ISSUE THREAD

**Issue by slonghei** [docker/for-win#11426] opened 2021-06-10 16:40 UTC
Closed issues are locked after 30 days of inactivity.
This helps our team focus on active issues.

If you have found a problem that seems similar to this, please open a new issue.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle locked

_Originally posted by @docker-desktop-robot in https://github.com/docker/for-win/issues/10053#issuecomment-774581673_

**Comment by slonghei** [comment] 2021-06-10 16:50
Meant to leave open! :)

**Comment by stephen-turner** [comment] 2021-06-11 14:44
Thank you for the suggestion. This is a feature request not a bug, so the roadmap item you have already quoted is the correct place for it. I'll close this ticket as a duplicate of that one.

**Closed by stephen-turner** 2021-06-11 14:44 UTC
Labels: lifecycle/locked
