### ISSUE TITLE
Docker Containers list not showing

### ISSUE THREAD

**Issue by OqilovSherzod** [docker/for-win#12768] opened 2022-06-09 23:05 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When i want to see my running containers docker not showing nothing, just white screen
### Expected behavior
Show currently running containers list
### Information

  - Windows Version: Windows 11 Pro 21H2 build 22000.708
  - Docker Desktop Version: 4.9.0
  - WSL2 backend 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: on a standalone machine

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Install Docker desktop with version mentioned.
  2. Run mongo service or any
  3. Click to "Containers"
![photo_2022-06-10_03-55-09](https://user-images.githubusercontent.com/10669173/172959401-46281160-758d-4bb0-be1d-c8e4363b4ca6.jpg)

**Comment by majeeddl** [comment] 2022-06-12 11:59
I see this error

**Comment by trungutt** [comment] 2022-06-12 22:24
Thanks for reporting! I think this is likely a duplicate of https://github.com/docker/for-win/issues/12759, so closing this issue to centralize discussion of workarounds there.

**Closed by trungutt** 2022-06-12 22:24 UTC
