### ISSUE TITLE
Once stopped, service won't restart cleanly

### ISSUE THREAD

**Issue by Jaykul** [docker/for-win#41] opened 2016-08-17 08:01 UTC
When I stop the docker service for any reason and then restart it later, it doesn't restart cleanly, so I have to use the "Restart Docker..." button in the GUI

That is, here's my test case:
```posh
stop-service com.docker.service
start-service com.docker.service
docker version
```

### Expected behavior

I should be able to stop the docker service, and start it again later, and use it:

### Actual behavior
```
Client:                                                                                                                     
 Version:      1.12.0                                                                                                       
 API version:  1.24                                                                                                         
 Go version:   go1.6.3                                                                                                      
 Git commit:   8eab29e                                                                                                      
 Built:        Thu Jul 28 21:15:28 2016                                                                                     
 OS/Arch:      windows/amd64                                                                                                
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified. 
```

### Information

A diagnostic was uploaded with id: 26E1532F-8294-4698-98A9-E66F4EFA30EC/2016-08-17_03-44-09

Product version info:

```
Client:                                    
 Version:      1.12.0                      
 API version:  1.24                        
 Go version:   go1.6.3                     
 Git commit:   8eab29e                     
 Built:        Thu Jul 28 21:15:28 2016    
 OS/Arch:      windows/amd64               

Server:                                    
 Version:      1.12.0                      
 API version:  1.24                        
 Go version:   go1.6.3                     
 Git commit:   8eab29e                     
 Built:        Thu Jul 28 21:15:28 2016    
 OS/Arch:      linux/amd64                 
```

**NOTE:** When I try this with the latest [dev builds for Windows Containers](https://master.dockerproject.org/windows/amd64/docker-1.13.0-dev.zip), that service does start/stop and work, but obviously it only hosts Windows images (and for some reason, will only talk to me if I run docker elevated).

```
Server:                                    
 Version:      1.13.0-dev                  
 API version:  1.25                        
 Go version:   go1.6.3                     
 Git commit:   4105cff                     
 Built:        Mon Aug 15 18:37:46 2016    
 OS/Arch:      windows/amd64    
```

**Comment by rneugeba** [comment] 2016-08-17 11:15
Thanks for the report. Out of curiosity, why do you want to stop the service? When the app is not running it shouldn't consume many resources.

**Comment by Jaykul** [comment] 2016-08-17 18:47
That is a *great* question @rneugeba 😄 

I'm new, and I haven't figured out how to get _both_ the Linux Container Server service and the [Windows one](https://master.dockerproject.org/windows/amd64/dockerd.exe) to work simultaneously -- they both want to use the same pipe address for communication...

**Comment by rneugeba** [comment] 2016-08-17 19:21
@Jaykul making WIndows containers and Docker for Windows work easily together is definitely something we are working on. But before that is done you can run them side by side as described by @friism in this forum post: https://forums.docker.com/t/linux-and-windows-images-side-by-side/20518

It's a little pedestrian for now, but please let me know if this works for now.

**Comment by Jaykul** [comment] 2016-08-17 19:55
That's very helpful, thanks ... I was looking for that `-H` syntax, but got distracted reading about `runtimes` in the [configuration](https://docs.docker.com/engine/reference/commandline/dockerd/#/docker-runtime-execution-options) (which I now see aren't even available on Windows). 

Much to learn.

**Comment by rneugeba** [comment] 2016-08-18 09:33
FYI, you need to start `dockerd` from an elevated prompt, but you connected to it via `-H` from a normal user if you pass ` -G <your user name>` as the `dockerd` command line argument.

Closing this issue for now

**Closed by rneugeba** 2016-08-18 09:33 UTC

**Comment by Jaykul** [comment] 2016-08-18 15:09
I don't think you should close it. The problem is real, and ought to be
fixed. I shouldn't need to rely on the desktop app to restart docker (and
the fact that the desktop app has a button to do so is enough argument that
this functionality is needed).

**Comment by rneugeba** [comment] 2016-08-19 13:56
I guess, I don't understand what the issue is. When I stop the service and then start the app, it asks me to restart the service and if you select `Start` it starts the service and the app.
![screen shot 2016-08-19 at 14 54 20](https://cloud.githubusercontent.com/assets/3338098/17811984/0c400b60-661d-11e6-996d-354861781978.png)

**Comment by Jaykul** [comment] 2016-08-21 16:27
Yes. And if you *only start it that way* it works. But it *only works* if you start it with the systray app. If you follow the steps in the original post, and 

```posh
stop-service com.docker.service
start-service com.docker.service
```

When you look in the app, it will think everything is fine ... but if you try commands like `docker version`, you'll just get errors. You end up having to use the Systray app to `restart` it to get it working again.

**Comment by rneugeba** [comment] 2016-08-22 09:49
Then don't start the service from the command line :)
I can understand why you might want to stop the service, but the service is only useful in conjunction with the application, so let the app start it when it needs it.

**Comment by Jaykul** [comment] 2016-08-23 07:37
>  the service is only useful in conjunction with the application

Wait, what? Huh? Maybe this is what I'm not getting. *Why* is the service only useful in conjunction with the application?

I mean, we're using the docker cli or the PowerShell module to actually manage docker images and containers, the app basically just pops up and tells us we can do that. 

However, regardless, YOU CANNOT just let the app start the service, because **the app won't start it, ever**. If for _any_ reason, you have stopped the docker service, here's what happens:

1. You run a command and it fails with that `open //./pipe/docker_engine: The system cannot find the file specified.` error ....
2. Click the system tray expando thing, 
3. Find and *right*-click the docker icon
4, Choose "Settings..." or "Diagnose and feedback" from the pop-up menu
5. Switch to the Reset tab
6. Click "Restart Docker..."
7. POPUP WARNING. It's going to shut all containers down (*but they're already down, so*) click "Restart" again.
8, Wait.
9. Keep waiting.
10. Yep, you guessed it. Wait some more.
11. After a while --maybe up to three minutes, I haven't actually clocked it, because I keep missing the _pop-under_-- you notice the error dialog `Failed to connect to dockerBackend: time out`
12. Close the error dialog (possibly sending the crash report) and **reboot** or:
   13. (Hopefully) Realize the systray app is not clever enough to check for the service.
   14. Open task manager, or services, or powershell
   15. Restart the service by hand
   16. Try the docker cli or powershell commands and **still** get `An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.`
17. **Repeat Steps 2-8 again, _this time_ with success**
 
So you see, you have to **first** start the service by hand, and **then _restart it_** from the app.

**Comment by rneugeba** [comment] 2016-08-23 07:46
The application, ie the systray icon, will start the `com.docker.service` service when it starts and the service is not running (see the dialogue screenshot above). What you seem to be doing is to stop the service while the app is running and then manually restart the service while the app is *still* running. And yes, in that case the app (systray) will not be able to reconnect to the service.

If you want to stop the service (for whatever reason) you should also close the app because without the service running you don't really have a functioning app. If you then restart the app (systray) it will prompt you if you want to restart the service.

**Comment by Jaykul** [comment] 2016-08-24 01:20
So, is that the whole function of the app? Does it just start and fix the service? Or is it providing a bridge from a named pipe in the user space to the service, or what?

I mean, the other docker daemon (eg. from https://master.dockerproject.org/windows/amd64/docker-1.13.0-dev.zip) doesn't need the app, the service in that one stops and starts without problems.

**Comment by friism** [comment] 2016-08-24 01:29
@Jaykul the app:

 1. starts and stops the hyper-v VM
 2. starts and stops the on-host proxy which proxies the engine API from Linux unix socket to windows named pipe
 3. proxies networking to avoid problems with VPNs, etc.
 4. Manages volume sharing from host to containers.
