### ISSUE TITLE
Docker on Windows 10 - Keep having to reset credentials on shared drive

### ISSUE THREAD

**Issue by smithma01** [docker/for-win#547] opened 2017-03-02 13:59 UTC
Description

Docker on windows 10 doesn't keep shared drive/directory setting after reboot.

Steps to reproduce the issue:

1: Share a drive using the docker settings gui in windows 10 pro (x64)
2: Created a docker image that maps a directory to a windows directory on the shared drive.
3: Reboot the windows host and start the image if auto-start is not set
4: enter image and go to the shared folder/directory - it is not shared...

Describe the results you received:

Directory and folders mapped from host windows machine to Linux image no longer mapped after reboot. I then have to reset the shared drives credentials and re-setup the windows host shared drive. Once done starting the docker image works as expected and the directories are mapped as needed.

Describe the results you expected:

I expect for the shared drive to remain shared after a reboot of the host machine.

Additional information you deem important (e.g. issue happens only occasionally):

Seems to happen after every reboot

Output of docker version:

Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true```

Output of docker info:

Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 11.45 GiB
Name: moby
ID: 4LZ7:PMRV:JDGJ:UVXJ:CAC6:YG2O:JJK4:AA6V:QWMJ:5NUP:6IN6:NY3G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-03-02T11:57:15.7370858Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Additional environment details (AWS, VirtualBox, physical, etc.):

Windows 10 pro (x64) docker host is running on a physical HP Z600 workstation

**Comment by jasonterando** [comment] 2017-03-02 20:34
Are you using a local or domain account?  If domain, you might want to try a local account.

**Comment by smithma01** [comment] 2017-03-02 21:46
Thanks - I am using a local account and the machine has not been joined to a domain - it is a fresh installation of windows 10 pro with just windows updates installed...

**Comment by smithma01** [comment] 2017-03-03 13:04
Docker installed an update last night on my windows machine but the behavior in terms of having to reset the user credentials on the shared drive - I've posted the updated docker version and docker info output below:

**PS C:\Users\Mark> docker version**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true

**PS C:\Users\Mark> docker info**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 11.45 GiB
Name: moby
ID: FFGV:Z6AP:HGZJ:UGVX:5N2B:7UGR:3PKX:MNM7:6TCK:ZCBF:GZOY:TFPB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 34
 System Time: 2017-03-03T12:59:52.0205984Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by rneugeba** [comment] 2017-03-07 20:02
I'm closing this as a duplicate of #385 and will mention you there so you get updates.
thanks for reporting

**Closed by rneugeba** 2017-03-07 20:02 UTC

**Comment by danielleiszen** [comment] 2020-04-09 01:25
Reset credentials feature is missing from docker desktop 2.2.0.5 but I keep getting this error message. Am I missing something or this is really a feature cut?

**Comment by mat007** [comment] 2020-04-09 05:42
@danielleiszen credentials are not needed anymore for file sharing, you shouldn’t be getting a popup.
Please create a fresh issue with a diagnostics report if possible (Troubleshoot window in the systray menu).
Thanks.
