### ISSUE TITLE
Mapping volumes does not work after upgrade to version 1.12.3

### ISSUE THREAD

**Issue by amalm** [docker/for-win#252] opened 2016-11-24 14:37 UTC
### Expected behavior
docker run --rm -v c:/Users:/data alpine ls /data should list the contents in c:\Users.

### Actual behavior
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: C: drive is not shared. Please share it in Docker for Windows Settings.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
7106D23D-EE34-41A7-824C-E4CF23061BC3/2016-11-24_15-12-27

The mounting info looks ok:
   [15:09:49.842][NamedPipeClient][Info   ] Sending Mount(C, SDNET\maas:**********, Docker.Core.Settings)...
   [15:09:49.847][NamedPipeServer][Info   ] Mount(C, SDNET\maas:**********, Docker.Core.Settings)
   [15:09:49.853][SambaShare     ][Info   ] Mount C
   [15:09:49.926][Cmd            ][Info   ] Share name        C
   [15:09:49.930][Cmd            ][Info   ] Path              C:\
   [15:09:49.934][Cmd            ][Info   ] Remark            
   [15:09:49.938][Cmd            ][Info   ] Maximum users     No limit
   [15:09:49.943][Cmd            ][Info   ] Users             
   [15:09:49.946][Cmd            ][Info   ] Caching           Caching disabled
   [15:09:49.950][Cmd            ][Info   ] Permission        SDNET\maas, FULL
   [15:09:49.954][Cmd            ][Info   ] 
   [15:09:49.958][Cmd            ][Info   ] The command completed successfully.

a bit futher down
   [15:09:49.974][SambaShare     ][Info   ] "C" is shared

and finally
   [15:36:36.577][NamedPipeServer][Info   ] SharedDrives()
   [15:36:36.583][NamedPipeServer][Info   ] SharedDrives done.
   [15:36:36.629][ApiProxy       ][Info   ] C
   [15:36:36.645][ApiProxy       ][Info   ] C: drive is not shared. Please share it in Docker for Windows 

Settings
### Steps to reproduce the behavior

  1. Installed Docker for Windows w/ the msi installer downloaded.
  2. Enabled C as shared drive
  3. Worked happily
  4. Upgraded after being informed that a new information was available
  5. Volume mapping do not work
  6. Disabled the shared drive and restarted 
  7. Enabled the shared drive and restarted (also win)
  8. Still the same message
![2016-11-24 15_27_47-new issue docker_for-win](https://cloud.githubusercontent.com/assets/2129288/20601809/ba6a4488-b25a-11e6-8dd2-420c682cb5ef.png)

**Comment by rneugeba** [comment] 2016-11-24 16:53
@amalm thanks for your report and the diagnostics ID. I can confirm that the share is mounted in the Linux VM:
```
//10.0.75.1/C on /c type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=maas,domain=SDNET,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,actimeo=1)
//10.0.75.1/C on /C type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=maas,domain=SDNET,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,actimeo=1)
```
so this looks like an issue with the mechanism we detect if a drive is shared.  Could your try the following command in Powershell and provide the output:
```
& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SharedDrives
```

Also ping @dgageot

**Comment by amalm** [comment] 2016-11-25 08:01
@rneugeba thanks for reacting promptly.

The output

`PS C:\Users\maas> & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SharedDrives`
`[0x7FFDD75770E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)`
`C`

BTW: The ANOMALY message is something I get in all shells due to Trend Microoffice Scan as far as I could google it. I do not expect it to be part of the problem, but never say never.

I hope this will ping @dgageot....

**Comment by dgageot** [comment] 2016-11-25 08:10
@rneugeba I can see how the message shown by Trend Microoffice Scan can be an issue. The Api Proxy runs the command @rneugeba gave you (`C:\Program Files\Docker\Docker\DockerCli.exe -SharedDrives`) and then parses the output to find if `C` drive is shared.
The error message on the first line of the output makes it ignore the second line (C)

I'll create a ticket to have this fix quickly.

**Comment by amalm** [comment] 2016-11-25 08:55
@dgageot: the ANOMALY is on stdout(not stderr), as is the drive (C) that you are looking for. 
Thanks for quick response!

**Comment by dgageot** [comment] 2016-11-25 08:56
@amalm Thanks. Yes I guessed so while working on the fix...

**Comment by dgageot** [comment] 2016-11-26 08:36
@amalm The fix should ship with next beta version

**Comment by pmsousa** [comment] 2016-11-28 07:55
@dgageot When can we expect this build to be available?

**Comment by dgageot** [comment] 2016-11-30 09:40
@amalm @pmsousa Beta 31 was just released. It's expected to fix this issue. Please give it a try!

**Comment by pmsousa** [comment] 2016-11-30 17:13
@dgageot I've tried the new build and can confirm the problem is solved!!!! :D

**Comment by dgageot** [comment] 2016-12-01 05:50
@amalm I'm going to assume Beta 31 fixed it for you too an close this issue. Feel free to reopen if that's not the case!

**Closed by dgageot** 2016-12-01 05:50 UTC
Labels: area/mounts, status/2-in-progress, status/4-fix-released-beta, status/5-will-be-closed, version/1.12.3

**Comment by amalm** [comment] 2016-12-01 08:38
Would love to verify it, but am stuck upgrading to the Beta from Stable. The Installer script is stuck with "Preparing Docker VM upgrade' in the installer win. 

There are some issues like this, e.g. https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/13 but until now I have not succeeded to upgrade....

However I am convinced the issue is solved as it is verified by @pmsousa.

`Version: 1.12.3 (8488)
Channel: Stable
Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
Started on: 2016/12/01 09:24:56.252
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:24:56.217][Installer      ][Info   ] Killing processes...
[09:24:56.271][Installer      ][Info   ] Killing existing com.docker.service process with PID 3660
[09:24:56.479][Installer      ][Info   ] Killing existing Docker for Windows process with PID 6764
[09:24:56.694][Installer      ][Info   ] Preparing upgrade...
[09:24:56.699][HyperV         ][Info   ] Destroy
[09:24:56.707][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[09:24:58.808][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[09:25:05.910][HyperV         ][Info   ] Shutdown VM ...
[09:25:05.923][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:25:05.945][HyperV         ][Info   ] Destroying Switch DockerNAT...`
