### ISSUE TITLE
Unable to run Docker for Windows on Windows 10 Ent

### ISSUE THREAD

**Issue by nijel91** [docker/for-win#74] opened 2016-09-10 03:47 UTC
### Expected behavior

Ability to run Docker for Windows
### Actual behavior

Docker Daemon not starting
### Information
- Diagnostic ID: 0FE9B5A9-AEF2-4210-BE1E-FFEAAFAD5A37/2016-09-09_22-42-17
- host distribution and version: Windows 10 Enterprise 10.0.10586
### Steps to reproduce the behavior

 to reproduce, please follow installation instructions

**Comment by dgageot** [comment] 2016-09-16 16:53
Hi @nijel91 thank you for reporting this issue! Can you please update to `1.12.1-stable` or `beta26` and tell us if the issue is fixed for you now?

**Comment by danbeaulieu** [comment] 2016-09-16 17:53
I was also having issues on Windows 10 Enterprise on several different hosts. 

I just installed Docker for Windows Beta 26 and it was still not able to start, crash report:
0199DC35-2724-4E6E-B6BC-28BDF9573BF9/2016-09-16_13-52-02

```
Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by Gmanweb** [comment] 2016-09-25 16:13
same problem trying to start docker on windows, fresh install.
version 
```
C:\gman>docker --version
Docker version 1.12.1, build 23cf638
```
ERROR:
```
Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by AndyBerman** [comment] 2016-09-26 14:10
I'm having the same problem.  Have tried uninstalling & reinstalling both Docker and Hyper-V.

**Comment by cgatian** [comment] 2016-09-28 18:48
Any resolution to this?

**Comment by cgatian** [comment] 2016-09-28 19:34
So in my situation, I had Docker automatically install Hyper-V.  This completes without a hickup. However, if you uninstall Hyper-V and attempt to reinstall it you will see the installation is actually not allowed.  Verify your CPU supports virtualization by performing opening task manager and verifying that Virtualization is enabled.  If it's not shown, then it will not work.

![image](https://cloud.githubusercontent.com/assets/1752170/18929100/06eec866-8591-11e6-8b7f-269347989f38.png)

**Comment by AndyBerman** [comment] 2016-09-28 19:47
It shows Virtualization is Enabled.

**Comment by friism** [comment] 2016-09-29 02:45
@cgatian is the screenshot you posted from another system than then one where you experienced the problem?

**Comment by chrisella** [comment] 2016-09-29 07:53
Exactly the same problem here, it's particularly annoying as it happened for me once I just finished moving all of our build flow and tool-chain to containers, typical ha.
I don't know if it's relevant but I think it's failing coincided with a windows 10 update for me.

**Comment by dev2see** [comment] 2016-09-30 15:57
The same problem

**Comment by crutchfield** [comment] 2016-10-04 13:34
Appears to be same issue I am having as well.  Tried stable and beta versions and got the same results.  Errors appear in log right before attempting to read/write certificates.  Be happy to provide more info to help isolate. 


[09:12:41.534][DataKit        ][Info   ] +850368us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[09:12:41.670][Database       ][Info   ] Successfully removed 3 value(s)
[09:12:41.685][DataKit        ][Info   ] 
[09:12:41.685][DataKit        ][Info   ] +1001096us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[09:12:41.748][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\windows\TEMP\tmpE621.tmp
[09:12:47.400][Database       ][Error  ] 2016/10/04 09:12:41 fatal error reading msg: EOF

**Comment by friism** [comment] 2016-10-04 13:47
@chrisella @crutchfield thanks for reporting, a fix is in the works!

**Comment by chrisella** [comment] 2016-10-04 13:47
@friism Excellent great news! :) 
thanks

**Comment by husainaloos** [comment] 2016-10-04 14:21
There might be two different problems here, with the same error message:

`Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)`

The log

`
[09:19:24.157][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:19:25.162][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:19:25.169][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:19:25.178][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:19:25.185][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:19:25.190][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:19:25.193][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[09:19:25.196][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:19:25.200][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:19:25.204][Database       ][Info   ] Writing com.docker.driver.amd64-linux/proxy/exclude=
[09:19:25.208][Database       ][Info   ] Writing com.docker.driver.amd64-linux/proxy/http=http://autoproxy.gm.com/
[09:19:25.212][Database       ][Info   ] Writing com.docker.driver.amd64-linux/proxy/https=http://autoproxy.gm.com/
[09:19:26.256][Database       ][Error  ] 2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2016/10/04 09:19:26 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:19:26.266][NamedPipeServer][Error  ] Unable to execute Start: Unable to write to the database. Exit code: 1    at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[09:19:26.277][NamedPipeClient][Error  ] Unable to send Start: Unable to write to the database. Exit code: 1
[09:19:26.289][Notifications  ][Error  ] Unable to write to the database. Exit code: 1
[09:19:26.297][Program        ][Info   ] Sending Bugsnag report 68e2fdbf-8a4a-445f-be5f-bad11239dd73...
[09:19:27.157][Program        ][Info   ] Bugsnag report 68e2fdbf-8a4a-445f-be5f-bad11239dd73 sent
[09:19:27.188][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[09:19:27.195][NamedPipeServer][Info   ] DownloadVmLogs()
[09:19:27.199][PowerShell     ][Info   ] Run script...
[09:19:27.265][HyperV         ][Warning] Unable to download logs: 2016/10/04 09:19:27 Failed to Dial a04a4196-b656-4ddd-a01d-4666cb8409e4 445ba2cb-e69b-4912-8b42-d7f494d007ea : A socket operation encountered a dead network.

[09:19:27.272][NamedPipeServer][Info   ] DownloadVmLogs done.
[09:19:27.279][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[09:20:18.992][ErrorReportWindow][Info   ] Open logs`

**Comment by danbeaulieu** [comment] 2016-10-13 19:15
This doesn't appear to be fixed on 
```
Version: 1.12.2-beta28 (7813)
Channel: Beta
Sha1: b09fe3ddc04b65d8a6219f27132a10a7918b3a91
```

Current crash report 816C0048-9BC7-4861-9DF8-0BEC0FEDE44F/2016-10-13_15-11-07

**Comment by srinathanand** [comment] 2016-10-14 18:52
Same problem on Windows 10 Version 1607 (OS Build 14393.321).

Docker version returns - docker --version
Docker version 1.12.1, build 23cf638

Hyper-V is enabled with a pop-up that came up when installing Docker and on restart this is the error -

```
Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
Crash report diagnostic id - 41EAEBF4-5972-49F7-9CDB-36E06570325D/2016-10-14_14-29-22

**Comment by AndyBerman** [comment] 2016-10-14 19:00
Upgrading to the Beta Channel Version 1.12.2-beta28 (7813) resolved this problem for me.

**Comment by srinathanand** [comment] 2016-10-14 19:32
Thanks @AndyBerman. I'll try that and post my results.

**Comment by srinathanand** [comment] 2016-10-14 19:40
@AndyBerman -I downloaded the Beta installer and ran it but I am still seeing the same problem. Here is my Docker version - 
docker --version
Docker version 1.12.2, build bb80604, experimental

**Comment by chrisella** [comment] 2016-10-17 08:08
I've also installed the latest Beta version (1.12.2-beta28 (7813)) and am having the same issue persist with the failure to write to the database.
:(

**Comment by srinathanand** [comment] 2016-10-17 12:27
@chrisella - where did you get the 1.12.2-beta28 (7813) from ?

**Comment by chrisella** [comment] 2016-10-17 12:29
Downloaded the BETA channel here : [https://docs.docker.com/docker-for-windows/](https://docs.docker.com/docker-for-windows/)

**Comment by srinathanand** [comment] 2016-10-17 13:53
@chrisella - Thanks I downloaded the same version. When you say restart do you mean a Windows restart or Docker for Windows restart ?

**Comment by crutchfield** [comment] 2016-10-17 13:55
I just downloaded and installed beta and the issue is resolved. 

>docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by chrisella** [comment] 2016-10-17 14:10
@srinathanand I restarted windows ... which obviously also restarts Docker :) though I didn't do that directly.
I hope you have some luck, since installing that Beta I've gone all day so far and not had any issues

**Comment by srinathanand** [comment] 2016-10-17 14:24
@chrisella - Restarted both docker and windows with no luck so far. It takes a lot of time trying to start up but fails with the same message every time.

@friism - Do you know what else I can try to fix this problem ? I am on the latest beta (1.12.2-beta28(7813)).

My latest crash report id is -
24C0616A-C2A9-476B-8F52-DF26B11C72F5/2016-10-17_10-00-29

**Comment by srinathanand** [comment] 2016-10-17 14:37
Here is my Windows version information -

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393

**Comment by srinathanand** [comment] 2016-10-17 15:32
UPDATE: Looking back at @cgatian comments I tried to find out if Virtualization was enabled or not for my CPU. I am running a Intel Xeon CPU E5645 @ 2.40 GHz. I downloaded a program called SecurAble and found out that Hardware Virtualization is a No for my CPU and I don't see a Virtualization label when I run Task Manager as shown in the screenshot by cgatian.

I am assuming this is the cause for my Docker for Windows not running. Can someone confirm ?

**Comment by friism** [comment] 2016-10-17 16:46
@srinathanand yeah, it wouldn't work without that

**Comment by srinathanand** [comment] 2016-10-17 17:02
Thanks @friism for confirming. Should this be added as a pre-requisite for the Docker for Windows installation ? Just checking the Task Manager should help people if they should use Docker for Windows or the Docker Toolbox.

Current "Getting Started" says this -
```
Docker for Windows requires 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later) and Microsoft Hyper-V. Please see What to know before you install for a full list of prerequisites.
```

**Comment by friism** [comment] 2016-10-17 19:16
@srinathanand I don't think VirtualBox will work without this either, but adding it to the prerequisites is a good idea.

@londoncalling this is where to find it

![image](https://cloud.githubusercontent.com/assets/126104/19451900/8af8f9f2-9463-11e6-92d4-40df5d1967d1.png)

**Comment by guilhermecgs** [comment] 2016-11-10 13:10
same problem with me

**Comment by guilhermecgs** [comment] 2016-11-10 16:55
Virtual Box can't do nested virtualization..

So it is not possible to run Windows 10 Pro as guest OS and try to install docker for windows on top of it

**Comment by rneugeba** [comment] 2016-11-30 14:07
This issue is getting quite messy: some users reported this as fixed, others use a CPU where it won't fix etc. So I'm closing this issue. Should you still have an issue, please open a new issue with details such as diagnostics ID using a recent Beta release
Thanks

**Closed by rneugeba** 2016-11-30 14:07 UTC
Labels: area/hyper-v, kind/bug, status/0-triage, version/beta28

**Comment by devops2017** [comment] 2017-02-03 21:04
Task Manager showing virtualization is disabled under performance tab. How I can enable it?

**Comment by lisaiceland** [comment] 2017-02-16 16:12
This problem is NOT fixed. Plz don't close this and move on. Needs fixing please. Thnx

**Comment by rneugeba** [comment] 2017-02-16 16:15
@lisaiceland please read my reason for closing it and suggestion on what to do if you still have the issue [here](https://github.com/docker/for-win/issues/74#issuecomment-263881536)

**Comment by lisaiceland** [comment] 2017-02-16 16:19
really? we should expect better from a stable release of Docker. Pleas, we can do better really.

**Comment by lisaiceland** [comment] 2017-02-16 16:20
works fine on MacOS latest for 02/16/2017

**Comment by srinathanand** [comment] 2017-02-16 16:20
@lisaiceland -  have you made sure that Virtualization is enabled?

**Comment by rneugeba** [comment] 2017-02-16 16:28
@lisaiceland please open a new issue with a *diagnostics ID* so that we can take a look. This issue is way to messy with lots of different issues posted by users. It's not easy to triage such an issue with so much noise.

In almost all of the case where something like this happens it is actually *not* an issue with Docker for Windows but most likely an issue with a given Windows installation or interference with other software installed such as security software etc etc.

**Comment by lisaiceland** [comment] 2017-02-16 18:02
yes. all the recommendations...I have them enabled. Done.

Thank You.
Lis

Regards,
Happy Analyzing, Developing, Managing & Launching Dreams Daily!

Bless. Ciao!

Lisa Kristinardottir (Lis) | Lisaiceland.com | USAGains.com


   P
*Save a tree! Please consider your environmental responsibility before
printing. *
*Don't print this e-mail unless it's really necessary.*



*CONFIDENTIALITY NOTICE*



This e-mail is intended only for the addressee named above. It contains
information that is privileged, confidential or otherwise protected from
use and disclosure. If you are not the intended recipient, you are hereby
notified that any review, disclosure, copying, or dissemination of this
transmission or taking of any action in reliance on its contents, or other
use is strictly prohibited.


If you have received this transmission in error, please reply to the sender
listed above immediately and permanently delete this message from your
inbox. Thank You.
