### ISSUE TITLE
on windows 2016 server, after Docker for Windows Installer.exe install, docker ps return error--error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default d aemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by khangulab** [docker/for-win#1318] opened 2017-11-14 05:42 UTC
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jedmao** [comment] 2017-11-25 00:44
Duplicate of #1338

**Comment by thaJeztah** [comment] 2017-11-25 14:18
closing as duplicate of https://github.com/docker/for-win/issues/1338, and probably others as well

**Closed by thaJeztah** 2017-11-25 14:18 UTC
