### ISSUE TITLE
Both Stable & Beta fail to install properly, or run, on Win10

### ISSUE THREAD

**Issue by Ltek** [docker/for-win#518] opened 2017-02-23 01:20 UTC
### Expected behavior
Docker to start properly

### Actual behavior
Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoDestroy(Boolean keepVolume)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information
Win10 Pro version1607  build14393.693
Crash Report: 41D0C09E-1985-40D1-9DF6-8A3623AB67EA/2017-02-22_18-14-26

### Steps to reproduce the behavior

install any version of docker stable or beta posted in the last 2 months (I've tried several builds)

**Comment by dgageot** [comment] 2017-02-23 09:30
This is a duplicate of https://github.com/docker/for-win/issues/436

**Closed by dgageot** 2017-02-23 09:30 UTC
