### ISSUE TITLE
Docker Unable to start

### ISSUE THREAD

**Issue by WillCamelCase** [docker/for-win#4408] opened 2019-08-03 17:48 UTC
Please, help.** Docker does not start.**

**Diagnostic ID:** FB1CA4F0-BAA5-4E2E-95B3-26B7E9F67A06/20190803173545
**Log** [log.txt](https://github.com/docker/for-win/files/3464151/log.txt)
**Diagnostic** [diagnostics.log](https://github.com/docker/for-win/files/3468706/diagnostics.log)

Unable to start
   em Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   em Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   em Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   em Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mikeparker** [comment] 2019-08-06 16:23
Duplicate of https://github.com/docker/for-win/issues/4348, https://github.com/docker/for-win/issues/4362, https://github.com/docker/for-win/issues/4368

**Closed by mikeparker** 2019-08-06 16:23 UTC
