### ISSUE TITLE
Problems with docker-compose run db sh

### ISSUE THREAD

**Issue by aliens9889** [docker/for-win#102] opened 2016-09-26 14:26 UTC
Hello everybody, I'm new on docker and I'm working on a project that started before I get in. So my problem is with docker-compose build and docker-compose up -d Cuz I'm trying to run the project for the first time in Windows and I don't know what I missing around.

When I try to run the docker-compose build this is what I get:

```
C:\Users\alien\Documents\workspaces\ambit\ambit-pac-gateway>docker-compose build
redis uses an image, skipping
db uses an image, skipping
Building web
Step 1 : FROM python:3.5-alpine
 ---> d1128d077f32
Step 2 : MAINTAINER Sebasti├ín Magr├¡ <sebastian@uakami.com>
 ---> Using cache
 ---> 5ec26ff57103
Step 3 : ARG DJANGO_DEBUG
 ---> Using cache
 ---> 52087671134c
Step 4 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> e3703f121655
Step 5 : RUN apk update     && apk add          postgresql-dev          ca-certificates          openssl          gcc          libc-dev          libxml2-dev          libxslt-dev          libffi-dev          cairo-dev          pango-dev          jpeg-dev          zlib-dev          gdk-pixbuf          ttf-dejavu     && cp /lib/libz.so /usr/lib     && cp /lib/libz.a /usr/lib     && pip install -U pip setuptools     && rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 4898eb7e684d
Step 6 : ADD . /app
 ---> 4eb59a61f3ac
Removing intermediate container 99967a5deec1
Step 7 : WORKDIR /app
 ---> Running in d331eab4d0e0
 ---> 3cb4b0585d20
Removing intermediate container d331eab4d0e0
Step 8 : RUN sh /app/docker/prepare.sh
 ---> Running in 6f6b65fe0b78
: not found/prepare.sh: line 2:
/app/docker/prepare.sh: set: line 3: illegal option -
ERROR: Service 'web' failed to build: The command '/bin/sh -c sh /app/docker/prepare.sh' returned a non-zero code: 2
```

this my prepare.sh
```

> #!/bin/sh

> set -ex

> prepare () {
>     cp pac_gateway/settings/local_docker.py pac_gateway/settings/local.py

>     reqs="`[[ "$DJANGO_DEBUG" = "True" ]] && echo "requirements/development.txt" || echo "requirements/production.txt"`"

>     pip install -U pip setuptools -r $reqs
> }

> prepare
```

this is my run.sh

```
#!/bin/sh

cp pac_gateway/settings/local_docker.py pac_gateway/settings/local.py

pip install -U -r `[[ "$DJANGO_DEBUG" = "True" ]] && echo "requirements/development.txt" || echo "requirements/production.txt"`

exec gunicorn --config=/app/gunicorn.py pac_gateway.wsgi
```
this is Dockerfile

```
FROM python:3.5-alpine
MAINTAINER Sebastián Magrí <sebastian@uakami.com>

ARG DJANGO_DEBUG

ENV PYTHONUNBUFFERED 1

# Get PostgreSQL 9.5 and base development files for pip builds
# Update pip to its latest release
RUN apk update \
    && apk add \
         postgresql-dev \
         ca-certificates \
         openssl \
         gcc \
         libc-dev \
         libxml2-dev \
         libxslt-dev \
         libffi-dev \
         cairo-dev \
         pango-dev \
         jpeg-dev \
         zlib-dev \
         gdk-pixbuf \
         ttf-dejavu \
    && cp /lib/libz.so /usr/lib \
    && cp /lib/libz.a /usr/lib \
    && pip install -U pip setuptools \
    && rm -rf /var/cache/apk/*

ADD . /app

WORKDIR /app

RUN sh /app/docker/prepare.sh

EXPOSE 8000

CMD sh /app/docker/run.sh
```

And when I try to write this `docker-compose run db sh`

the answer that I got is this 
```

Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose run`.
```

this project is running on Ubuntu, but at work the put me to try on Windows
I don't know if this relevant for help, but this a Django project
I will appreciate all the help I'll receive. Thanks you

**Comment by rneugeba** [comment] 2016-09-27 11:13
I can reproduce your issue when I use Windows style line endings (CRLF) in `prepare.sh`. If I convert to Unix style line endings (LF) it works fine.  Since the shell scripts are executed in a Linux/Unix container the files must have Unix style line endings. See the Docker for Windows troubleshoot: https://docs.docker.com/docker-for-windows/troubleshoot/

closing

**Closed by rneugeba** 2016-09-27 11:13 UTC

**Comment by friism** [comment] 2016-09-27 14:25
If you're using Visual Studio Code, also check out this blog post for how to get correct line endings: https://blogs.msdn.microsoft.com/stevelasker/2016/09/22/running-scripts-in-a-docker-container-from-windows-cr-or-crlf/
