### ISSUE TITLE
hey guys , i need help , am tryingt o push my image to my docker hub..

### ISSUE THREAD

**Issue by SATKURISUNAND** [docker/for-win#12459] opened 2021-12-21 19:52 UTC
hey guys , i need help , am tryingt o push my image to my docker hub..

ubuntu@ip-172-31-46-165:~$ clear
ubuntu@ip-172-31-46-165:~$ docker push awsdocker
The push refers to repository [docker.io/library/awsdocker]
d6f5889c8a4b: Preparing
5eaeb0d8d830: Preparing
04aebfb4ce61: Preparing
16542a8fc3be: Preparing
6597da2e2e52: Preparing
977183d4e999: Waiting
c8be1b8f4d60: Waiting
denied: requested access to the resource is denied
ubuntu@ip-172-31-46-165:~$

_Originally posted by @PaulObalonye in https://github.com/docker/for-win/issues/808#issuecomment-617290485_

**Comment by SATKURISUNAND** [comment] 2021-12-21 19:52
please help me out

**Comment by thaJeztah** [comment] 2021-12-21 20:12
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug,

**Closed by thaJeztah** 2021-12-21 20:12 UTC
