### ISSUE TITLE
All versions after 4.15 contain a communication bug between the host and Docker

### ISSUE THREAD

**Issue by budarin** [docker/for-win#13209] opened 2023-02-01 14:41 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 374513F7-8009-484F-8C36-46187B87809E/20230201142522

### Actual behavior

I want everything to work as in version 4.15

### Expected behavior

I install new versions, launch my containers as before and try to access them as before - there is no connection

I delete new versions - I put 4.15 and everything works

### Information

  - Windows Version: Windows 10 Pro 22H2
  - Docker Desktop Version: 4.16.3
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: virtualized Windows

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

### Steps to reproduce the behavior

[docker-stack.zip](https://github.com/docker/for-win/files/10558095/docker-stack.zip)

I have to stay on version 4.15 for now

**Comment by jasondalycan** [comment] 2023-02-01 21:05
Same issue here: published ports within services in swarm mode on Windows 10 (WSL2) drop the connection immediately.

**Comment by YouveGotMeowxy** [comment] 2023-02-01 22:24
Most likely related: 

https://github.com/docker/for-win/issues/13187

**Comment by jruhe-adesso** [comment] 2023-02-03 09:08
Same here

Docker 4.16.3 from 4.15.0

Windows 10 21H2

WSL-Version: 1.0.3.0
Kernelversion: 5.15.79.1
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19044.2486

**Comment by burgoyn1** [comment] 2023-02-06 20:59
I had the same thing happen to me. Docker 4.16.3 from 4.15.0

Windows 11 22H2

Running in swarm mode. Downgrading back to 4.15.0 worked. For those wanting to downgrade the instructions are here #13207

**Comment by YouveGotMeowxy** [comment] 2023-02-09 00:14
With almost 600 employees, it'd be "_really super nice_" if they could assign at least **_one_** to monitor and respond to their own issues queue, and at least acknowledge them....

Is that too much to ask?

![image](https://user-images.githubusercontent.com/39491297/217681131-3a094328-6421-4330-a360-60b509b7319e.png)

**Comment by j0hnst0n** [comment] 2023-02-09 00:32
@YouveGotMeowxy FWIW the employee count is just over 300 (LinkedIn data is noisy...), but your point still stands; no, it's not too much to ask. Our product team reviews the public roadmap weekly, not sure how this slipped through the cracks but we'll address ASAP.

Thank you for being part of the Docker community!

**Comment by YouveGotMeowxy** [comment] 2023-02-09 00:44
> @YouveGotMeowxy FWIW the employee count is just over 300 (LinkedIn data is noisy...), but your point still stands; no, it's not too much to ask. Our product team reviews the public roadmap weekly, not sure how this slipped through the cracks but we'll address ASAP.
> 
> Thank you for being part of the Docker community!

Thank you, @j0hnst0n for the fast reply!

Ok, my apologies about the employee count. I just assumed LI had a simple count of how many users have "works at Docker" in their profile.

All I ask is that at least 1 employee to regularly monitor and respond to the issues here, so it's not a total mystery to us whether or not our reports are even being _heard_. I've been completely unable to even access a single container since this last update, for at least a week or so. "Downgrading" is more painful than it's worth. I've been praying for a new update every single day to address this, and it never comes.

Thanks again! :)

**Comment by christophermclellan** [comment] 2023-02-10 12:27
@budarin , @YouveGotMeowxy thank you for flagging. i've created a ticket for this internally and we'll pick it up asap. i'll provide an update shortly.

**Comment by christophermclellan** [comment] 2023-02-22 13:56
@budarin @YouveGotMeowxy just to say, we picked this up last week. Hoping to get back to you soon with a fix.

**Comment by markalanevans** [comment] 2023-02-22 21:50
Same here we are bricked

**Comment by markalanevans** [comment] 2023-02-23 06:07
I was able to use the CLI and the --disable-version-check to revert back to 4.15

```.\DockerDesktopInstaller.exe install --disable-version-check```

**Comment by markalanevans** [comment] 2023-02-23 06:08
We then unchecked all the auto update settings

**Comment by YouveGotMeowxy** [comment] 2023-02-28 23:03
I still cant connect to any containers in my swarm as of 4.17.0 (99724). But I see them all running "normally" in the list of containers.

**Comment by jens1000** [comment] 2023-03-01 08:06
I had a problem with Docker Desktop because there were expired certificates, but the docker self diagnose tool said everything was fine. I solved that by deleting the directory AppData/Local/Docker/pki and restarting Docker. Could this have been the case here? Did you check the Docker logs before?

**Comment by YouveGotMeowxy** [comment] 2023-03-02 02:13
> I had a problem with Docker Desktop because there were expired certificates, but the docker self diagnose tool said everything was fine. I solved that by deleting the directory AppData/Local/Docker/pki and restarting Docker. Could this have been the case here? Did you check the Docker logs before?

@jens1000 thank you for helping. I just tried and unfortunately no change. The interesting thing too is, after deleting it and restarting DD, DD is back up running but the pki folder wasn't recreated and refilled by Docker.

**Comment by burgoyn1** [comment] 2023-05-20 20:01
@christophermclellan @j0hnst0n This issue is still happening for me in the latest version v4.19.0. I had another problem and needed to upgrade and I figured I would see if it was resolved. Is this being worked on internally? Almost 4 months seems like a very long time.

**Comment by christophermclellan** [comment] 2023-05-22 09:41
Hey @burgoyn1 , sorry for delay. Team are currently working on this. We have planning today so will catch up on this and I'll provide more detailed timelines afterwards.

**Comment by ctalledo** [comment] 2023-05-24 18:04
Hi folks, Cesar Talledo from Docker here. I'll be helping debug this (and apologies again for the belated reply).

I tried with a very simple experiment where I created a couple of swarm services on an overlay network, and have one of them publish a port on the host. I tried with both DD 4.15 and DD 4.18. In both cases things worked properly, meaning that the services where able to talk to each other via the overlay network, and I was able to access the published service via port.

@burgoyn1: Could you share some more info on the setup that is failing for you? The simpler the better so I can reproduce in house and debug what's going on.

Thanks!

**Comment by ctalledo** [comment] 2023-05-24 18:09
> I tried with a very simple experiment

FYI here's what I did (on a Windows host with WSL)

1) Install DD 4.18
2) Start DD (configure it to use WSL backend)
3) Initialize the swarm node: `docker swarm init`
4) Setup the services:

```
docker network create --driver overlay my-network`
docker service create --publish published=8090,target=80 --name my_web2 --network=my-network nginx
docker service create --name client --network=my-network alpine tail -f /dev/null
```

5) Verified that the `alpine` container can access the nginx service
6) Verified that my browser can access the nginx service via `localhost:8090`.

**Comment by burgoyn1** [comment] 2023-05-24 23:37
@ctalledo This is the process I am doing:

1. Install DD 4.15.0
2. Start DD 4.15.0 configured for WSL backend. I have installed Ubuntu-22.04 from the windows marketplace and enabled the integration with that repo
3. Initialize the swarm with: `docker swarm init`
4. Create an overlay network `docker network create --driver=overlay --subnet=10.10.0.0/16 --ip-range=10.10.0.0/16 --gateway=10.10.0.1 application`
5. Create a portainer instance `docker service create --name portainer --publish mode=host,target=9000,published=9000 --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock --mount type=bind,src=/home/burgoyn1/portainer,dst=/data portainer/portainer` (Make sure you mount it to some kind of file system on your computer so it will load all the data when it restarts)
6. Once set up, create a stack in portainer called `test` with the following configuration:
```
version: '3.7'
services:
  main:
    image: nginx:latest
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
    ports:
      - target: 80
        published: 8090
        protocol: tcp
        mode: host
    networks:
    - application

networks:
  application:
    external: true
```

7. This will create a running container just fine at http://localhost:8090/
8. Upgrade DD to 4.19.0 (or later)
9. Wait for docker to finish setting up and install. Once booted, docker containers will run, but won't be reachable from localhost.

**Comment by ctalledo** [comment] 2023-05-25 18:10
Hi @burgoyn1, thanks for the detailed repro instructions. I was able to repro on my side, so next step is to debug what's going on.

FYI, I noticed that swarm services become unreachable after the update from 4.15 -> 4.19, but if I re-initialize the swarm, then things work as usual:

```
docker swarm leave --force
docker swarm init
``` 

It's not an ideal solution since you have to then recreate the stacks, but thought I would mention it in case it helps. 

I'll dig down to see why the swarm services become unavailable after the update.

**Comment by burgoyn1** [comment] 2023-05-25 18:59
@ctalledo Cool, leaving the swarm then re-building works perfectly. Ideal, no, but it did work for me.

If anyone else experiences this issue, following the step above worked for me. Hopefully this is only a one time thing and not with every update. I will let you know if it happens again.

**Comment by budarin** [comment] 2023-05-25 19:04
I tried to raise my stack to 4.19 - it didn't work - all the same problems as with 4.16
unable to access services from the browser

**Comment by burgoyn1** [comment] 2023-05-25 19:06
@budarin Have you tried backing up your stacks, leaving the swarm, then creating a new one and trying again?

**Comment by STaRDoGG** [comment] 2023-05-25 19:56
Just a small tip if anyone uses portainer and "loses" all their stacks in it, you can get them back by hand editing the portainer.db and swapping out the old swarm id with the new swarm id.

**Comment by ctalledo** [comment] 2023-05-25 20:41
Thanks everyone for chiming in.

@burgoyn1: glad to know the work-around worked. I'll continue debugging so we can fix this.

@budarin: Please try leaving the swarm and creating a new one; if this does not work for you please let me know the steps so I can reproduce on my end.

@STaRDoGG: thanks for the tip on recreating the portainer state on a new swarm, very helpful.

**Comment by ctalledo** [comment] 2023-05-26 04:35
Hi folks, I am not seeing the problem when upgrading from 4.18 -> 4.19, or 4.19 -> 4.20 (not yet released). In both cases, existing swarm stacks get recreated after the upgrade and are reachable from the host as expected. 

Therefore, I am going to close this issue as the problem is known to occur from 4.15->newer, but is fixed in later versions of Docker Desktop.

If someone disagrees, please re-open the issue with an explanation on why.

Thanks again for reporting this and sorry for the delay in addressing it.

**Closed by ctalledo** 2023-05-26 04:35 UTC

**Comment by burgoyn1** [comment] 2023-05-26 08:01
@ctalledo Maybe add it somewhere to documentation so that it is not just on this thread?

**Comment by ctalledo** [comment] 2023-05-26 16:30
> @ctalledo Maybe add it somewhere to documentation so that it is not just on this thread?

Hi @burgoyn1, in general we prefer to avoid documenting bugs as they can pollute the docs. I think this GH issue is the best place to document the problem and work-around.

Thanks.

**Comment by budarin** [comment] 2023-05-30 00:11
After removing v15 and installing v19 - services are accessible from web browser

**Comment by johnmanko** [comment] 2024-05-29 20:51
> Hi @burgoyn1, thanks for the detailed repro instructions. I was able to repro on my side. Next step is for me to debug what's going on.
> 
> FYI, I noticed that swarm services become unreachable after the update from 4.15 -> 4.19, but if I re-initialize the swarm, then things work as usual:
> 
> ```
> docker swarm leave --force
> docker swarm init
> ```
> 
> It's not an ideal solution since you have to then recreate the stacks, but thought I would mention it in case it helps.
> 
> I'll dig down to see why the swarm services become unavailable after the update.

This solved my problem.
