### ISSUE TITLE
engine linux/wsl failed to run

### ISSUE THREAD

**Issue by toanphan1302** [docker/for-win#14445] opened 2024-11-25 08:29 UTC
### Description

running engine: waiting for the Docker API: engine linux/wsl failed to run: starting WSL engine: error spotted in wslbootstrap log: "[2024-11-25T08:14:09.482596405Z][wsl-bootstrap][F] preparing block device /dev/sdd: detecting file system: detecting fs type: exec: \"blkid\": executable file not found in $PATH"

![Image](https://github.com/user-attachments/assets/8135b84c-a63d-4649-bcf6-55489eb015e9)

### Reproduce

1. Run docker desktop
2. The error occur 

### docker version

```bash
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
```

### docker info

```bash
Client:                                                                                                                  Version:    27.3.1                                                                                                      Context:    desktop-linux                                                                                               Debug Mode: false                                                                                                       Plugins:                                                                                                                 buildx: Docker Buildx (Docker Inc.)                                                                                       Version:  v0.17.1-desktop.1                                                                                             Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe                                                       compose: Docker Compose (Docker Inc.)                                                                                     Version:  v2.29.7-desktop.1                                                                                             Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe                                                      debug: Get a shell into any image or container (Docker Inc.)                                                              Version:  0.0.37                                                                                                        Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe                                                        desktop: Docker Desktop commands (Alpha) (Docker Inc.)                                                                    Version:  v0.0.15                                                                                                       Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe                                                      dev: Docker Dev Environments (Docker Inc.)                                                                                Version:  v0.1.2                                                                                                        Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe                                                          extension: Manages Docker extensions (Docker Inc.)                                                                        Version:  v0.2.27                                                                                                       Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe                                                    feedback: Provide feedback, right in your terminal! (Docker Inc.)                                                         Version:  v1.0.5                                                                                                        Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe                                                     init: Creates Docker-related starter files for your project (Docker Inc.)                                                 Version:  v1.3.0                                                                                                        Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe                                                         sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)                               Version:  0.6.0                                                                                                         Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe                                                         scout: Docker Scout (Docker Inc.)                                                                                         Version:  v1.14.0                                                                                                       Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
```

### Diagnostics ID

680879A2-1507-4D8B-B7F3-FF860FC8D8DC/20241125081519

**Comment by griesi007** [comment] 2024-11-29 08:46
@bsousaa  I suddenly noticed the same error. WSL itself is running without any issues

running engine: waiting for the Docker API: engine linux/wsl failed to run: starting WSL engine: error spotted in wslbootstrap log: "[2024-11-29T08:43:06.983715802Z][wsl-bootstrap][F] more than one sd* disk in /sys/block with wwid ending by 57de6aa93848de02790adcb4: /dev/sdc,/dev/sde"

DiagnosticsId: C8D509D5-368B-4030-BF82-B30E23F69E96/20241129084428

![Image](https://github.com/user-attachments/assets/4f42ae05-ffab-44d1-86fd-48ad87344c8c)

**Comment by griesi007** [comment] 2024-11-29 08:55
@toanphan1302 did you find a way to resolve the issue?

**Comment by toanphan1302** [comment] 2024-11-29 10:40
> [@toanphan1302](https://github.com/toanphan1302) did you find a way to resolve the issue?

Not yet.

**Comment by IAsDoubleYou** [comment] 2024-12-02 10:19
I had the same issue. Reset to factory defaults didn't solve it.
I ended up removing, rebooting and reinstalling and now it works again.

**Comment by henixnet** [comment] 2024-12-02 18:23
Im used this solution: 
https://github.com/docker/for-win/issues/14453#issuecomment-2507992110 

https://desktop-stage.docker.com/win/main/amd64/176956/Docker%20Desktop%20Installer.exe

Reinstal dd by new dev build and its worked.

**Comment by andrea-reale** [comment] 2024-12-02 19:17
Hey all,

Thank you for reporting the issue and for your patience. As noted above, this is a duplicate of #14453.

As discussed in that ticket, you can install the development build that is shared above. The same fix will be released in the upcoming 4.37 release.

I am closing this issue now because of duplication.

Please, keep reporting any other problem or feedback you may still have about this issue on #14453.

**Closed as not planned** 2024-12-02 19:17 UTC
Labels: status/triage, area/WSL2, status/duplicate, version/4.35.1, version/4.36.0

**Comment by zhtgeneral** [comment] 2025-05-31 18:42
Reinstalling and restarting worked for me

**Comment by toanphan1302** [comment] 2025-06-01 02:11
The error I encountered appears to be related to how my Windows `PATH` is interfering with the `PATH` in WSL.

**Comment by CharlesCNorton** [comment] 2025-06-06 11:53
only reinstalling fixed it
