### ISSUE TITLE
Docker fails to start with "Access is denied" error

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#10935] opened 2021-04-15 13:40 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4694BB44-2E66-43FA-86E0-3E80BBC1A2D8/20210415132820

### Actual behavior

Docker fails to start and shows the "An error occurred" dialog with the following exception:
```
System.ComponentModel.Win32Exception:
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.ManagedProcesses.ManagedProcess.StartProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, CancellationToken stopToken) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 122
   at Docker.ManagedProcesses.ManagedProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 50
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Expected behavior
Docker starts and runs happily

#### Is it reproducible?
 I've restarted Docker multiple times and get the same error every time
 Potentially helpful is that Windows ran updates last night, and Docker upgraded itself this morning. It would surprise me, but it's possible that the issue is related to the combination of Windows updates and Docker upgrade.
#### Is the problem new?
Yes
#### Did the problem appear with an update?
Yes, the update to 3.3.0 (62916)

  - Windows Version: 10.0.19042 Build 19042
  - Docker Desktop Version: 3.3.0 (62916)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Upgrade Docker to 3.3.0, attempt to start it.

**Comment by stephen-turner** [comment] 2021-04-15 15:30
Thanks for the report, but closing as a dupe of #10881.

**Closed by stephen-turner** 2021-04-15 15:30 UTC
Labels: version/3.3.0
