### ISSUE TITLE
Last update/release (October 3 or 4, 2017) set the Linux Docker VM to 2GB instead of honoring my current config

### ISSUE THREAD

**Issue by CESARDELATORRE** [docker/for-win#1169] opened 2017-10-04 21:53 UTC
### Expected behavior
Update Docker for Windows (stable release) and maintain the current configuration.settings

### Actual behavior
The assigned memory was set to 2GB instead of honoring my current config which was 5GB.

### Information

 I believe the last Docker for Windows update has a bug. It didn't respect the memory assigned I had (4GB) and it set the memory to 2GB and then, the SQL Server container was not starting. I thought it was related to the new SQL Container image released this week, but it was because of the memory that it was set to 2GB after updating Docker for Windows to the latest stable release.

### Steps to reproduce the behavior

  1. Set Docker host memory to 5GB or similar
  2. Update Docker for windows
  3. Check if the memory settings continues the same or changed. If it changed, that's a bug.

**Comment by friism** [comment] 2017-10-04 21:58
@jasonbivins do you have time to try and repro?

**Comment by jasonbivins** [comment] 2017-10-05 02:54
Hi @CESARDELATORRE
Can you share more details about how you were allocating the memory, as well as a diagnostic ID so that I can get more specifics on the versions?
I tested several upgrades stepping from 17.06 to 17.09 stable versions, but the only way I was able to get it to reset the memory settings was through the Reset menu. 

![image](https://user-images.githubusercontent.com/28021664/31208995-59591afe-a956-11e7-942b-09026d81b7d6.png)

**Comment by CESARDELATORRE** [comment] 2017-10-05 05:59
Hi! So I've had this PC with 5GB memory assigned to Docker for quite some time. It was originally set through the settings window. But yesterday/today, after installing the last stable Docker Update it was configured to 2GB.
I don't see any other way why it was reset to 2GB...

**Comment by BrizzleRocker** [comment] 2017-10-05 08:17
I can confirm I have seen this behavior too.

**Comment by jasonbivins** [comment] 2017-10-17 01:55
Hi @CESARDELATORRE @BrizzleRocker 
I still cannot reproduce this except by deliberately destroying settings.  I'll go ahead and close this for now, but please keep an eye out for it and let me know if you see it again.  Any details you can provide will help.

**Closed by jasonbivins** 2017-10-17 01:55 UTC
Labels: area/installer, area/windows, status/2-in-progress
