### ISSUE TITLE
Docker Desktop startup fails with message "wrong parameter"

### ISSUE THREAD

**Issue by terpentin81** [docker/for-win#4420] opened 2019-08-05 06:24 UTC
### Expected behavior
Docker Desktop should startup without any error messages

### Actual behavior
Docker Desktop fails to startup:
Falscher Parameter.

   bei System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   bei Docker.WPF.Credentials.MountCredentialAsker.DecryptPassword(Byte[] encrypted)
   bei Docker.WPF.Credentials.MountCredentialAsker.RetrieveCredential(String target)
   bei Docker.WPF.BackendClient.Restart(ContainerEngineMode mode)
   bei Docker.Actions.DoRestartVM(Settings previousSettings)
   bei Docker.Actions.<>c__DisplayClass31_0.<RestartVM>b__0()
   bei Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information
  - Windows Version: 10 (Version 1803 Build 17134.885)
  - Docker Desktop Version: 2.1.0.0 (368774)
  - Diagnostics ID: F95D0D84-2AA3-4085-B18D-BD06C801C261/20190805060657

### Steps to reproduce the behavior
Just start Docker Desktop, reproducible

**Comment by terpentin81** [comment] 2019-08-05 06:25
startup as admin doesn't help...

**Comment by mikeparker** [comment] 2019-08-06 16:37
duplicate of https://github.com/docker/for-win/issues/3560

**Closed by mikeparker** 2019-08-06 16:37 UTC
Labels: version/2.1.0.0
