### ISSUE TITLE
Just changed #CPU on my host machine

### ISSUE THREAD

**Issue by Bafff** [docker/for-win#4436] opened 2019-08-06 07:07 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 53070D11-C36F-4BA6-970F-1ED14449E73B/20190806064838

### Information

  - Windows Version:
get-ComputerInfo -Property Windows*
```
WindowsBuildLabEx              : 18362.1.amd64fre.19h1_release.190318-1202
WindowsCurrentVersion          : 6.3
WindowsEditionId               : Professional
WindowsInstallationType        : Client
WindowsInstallDateFromRegistry : 22.07.2019 10:37:56
WindowsProductId               : 00330-80192-00883-AA758
WindowsProductName             : Windows 10 Pro
WindowsSystemRoot              : C:\WINDOWS
WindowsVersion                 : 1903
```
  - Docker Desktop Version:
C:\Users\Baf>docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

(Engine is not starting at the moment so I can't provide all info)
### Steps to reproduce the behavior

  1. I tried to change № of CPU from 2 to 4 in the settings
  2. Reset to factory defaults does not help

**Comment by mikeparker** [comment] 2019-08-06 16:45
```
[09:48:38.809][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: ���������� ������� �����������, ��� ��� ����������������� ���������� "ErrorActionPreference" ��� ������ ��������� ��������� �������� Stop: "DockerDesktopVM": �� ������� ���������.

� ������� �� ������� ������ ��� ������� ����������� ������ "DockerDesktopVM".

�� ������� ���������������� ������: ������������ ������ (0x8007000E).

�� ������� ��������� "DockerDesktopVM" (������������� ����������� ������ 751D2F6F-97ED-489C-A336-0ADBD7D594DD).

� ������� �� ������� ������ ��� ������� ����������� ������ DockerDesktopVM � ������� ���, ������ 2048 ��. (�� ����������� ������ 751D2F6F-97ED-489C-A336-0ADBD7D594DD)

"DockerDesktopVM" �� ������� ���������������� ������: ������������ ������ (0x8007000E). (�� ����������� ������ 751D2F6F-97ED-489C-A336-0ADBD7D594DD)

```
Duplicate of https://github.com/docker/for-win/issues/4348, https://github.com/docker/for-win/issues/4362, https://github.com/docker/for-win/issues/4368

**Closed by mikeparker** 2019-08-06 16:45 UTC
