### ISSUE TITLE
Linux containers' system time is wrong

### ISSUE THREAD

**Issue by yehoshuadimarsky** [docker/for-win#5803] opened 2020-02-18 00:52 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
0BAC421C-A3AC-4CD5-9A2E-4C32B21BE853/20200218003129

### Expected behavior
The internal system time inside a container is correct

### Actual behavior
It is wrong, sometimes off by at least 90 minutes. This leads to a cascade of side effects, such as not being able to access updates with apt-get, and other tools that rely on the internal system time to be accurate for security purposes.

Note, this is with *Linux* containers, so it is not the same as #2280. Also, I don't notice this happening after sleep mode, so don't think it's related to #5781. 

Weird thing is, on another very similar computer (same OS, Docker version, both are company managed via AzureAD) - I have no problems.

### Information

  - Windows Version: 
Windows 10 Pro - 10.0.18362
  - Docker Desktop Version: 
2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: 
No, on a laptop

### Steps to reproduce the behavior

```powershell
(base) PS C:\Users\JoshDimarsky> Get-TimeZone                                                                                                                               

Id                         : Eastern Standard Time
DisplayName                : (UTC-05:00) Eastern Time (US & Canada)
StandardName               : Eastern Standard Time
DaylightName               : Eastern Daylight Time
BaseUtcOffset              : -05:00:00
SupportsDaylightSavingTime : True

(base) PS C:\Users\JoshDimarsky> Get-Date                                                                                                                                   
Monday, February 17, 2020 7:44:00 PM

(base) PS C:\Users\JoshDimarsky> docker run -it continuumio/miniconda3 /bin/bash 

(base) root@5d81f250eee9:/# date
Mon Feb 17 18:55:14 UTC 2020
```

![image](https://user-images.githubusercontent.com/24758845/74694417-08b5f500-51be-11ea-9ab1-a47316a4786c.png)

**Comment by yehoshuadimarsky** [comment] 2020-02-18 01:02
Although after reading through #4526, it does seem like this is related to the computer sleeping, maybe I just don't notice it. Restarting Docker for Windows seems to do the trick. Weird/annoying.

**Comment by jeffgriffith** [comment] 2020-02-27 22:49
I ran into the same thing. 2.2.0.3 (42716). The time was half a day in the past. After rage-deleting my container, turned out restarting Docker Desktop was the fix :-)

**Comment by trickreich** [comment] 2020-03-02 10:51
Is there a workaround or do I need to restart docker every time?

**Comment by mat007** [comment] 2020-03-03 13:25
We’re thinking we have now fixed this in our master branch, here is a link to a private Edge build which includes it: https://download-stage.docker.com/win/edge/43075/Docker%20Desktop%20Installer.exe
If you’re wanting to test it it should install on top of Stable 2.2.0.3 but understand this is an internal Edge build which purpose is only to validate the fix.

**Comment by rfay** [comment] 2020-03-10 13:27
Related workaround: https://thorsten-hans.com/docker-on-windows-fix-time-synchronization-issue - but I hope everybody will test the stage build instead.

**Comment by stephen-turner** [comment] 2020-03-25 18:06
I'm closing this as a dupe of #4526.

**Closed by stephen-turner** 2020-03-25 18:06 UTC
