### ISSUE TITLE
[NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

### ISSUE THREAD

**Issue by BruceGilham** [docker/for-win#390] opened 2017-01-14 01:16 UTC
### Expected behavior
Docker Creates VM and Runs
### Actual behavior
Docker returns error
### Information
Diagnostic ID: 
B0C7-37907FB04E2E/2017-01-13_17-12-11

Reproduce:
Install Docker

Version
Windows 10 Pro

### Steps to reproduce the behavior
Unknown

Log:
Version: 1.12.6 (9655)
Channel: Stable
Sha1: 258480fd147da7888a440ed7808d255c0fb15bb7
Started on: 2017/01/13 00:02:25.552
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:02:25.552][SegmentApi     ][Info   ] Usage statistic: heartbeat
[01:02:25.553][SegmentApi     ][Info   ] Usage statistic: heartbeat
[02:02:25.553][SegmentApi     ][Info   ] Usage statistic: heartbeat
[03:02:25.553][SegmentApi     ][Info   ] Usage statistic: heartbeat
[04:02:25.554][SegmentApi     ][Info   ] Usage statistic: heartbeat
[04:02:28.560][SegmentApi     ][Error  ] Failed to track event: A task was canceled.
[05:02:25.555][SegmentApi     ][Info   ] Usage statistic: heartbeat
[05:02:25.562][SegmentApi     ][Error  ] Failed to track event: An error occurred while sending the request.
[05:02:25.645][Updater        ][Info   ] Checking for updates on channel Stable...
[05:02:25.650][UpdateFeedDownloader][Error  ] The remote name could not be resolved: 'download.docker.com'
[05:02:25.653][Updater        ][Info   ] No update available
[06:02:25.567][SegmentApi     ][Info   ] Usage statistic: heartbeat
[07:02:25.567][SegmentApi     ][Info   ] Usage statistic: heartbeat
[08:02:25.568][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:02:25.569][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:02:25.570][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:02:25.571][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:02:25.646][Updater        ][Info   ] Checking for updates on channel Stable...
[11:02:25.786][Updater        ][Info   ] Local build 9655 is as good as the remote 9655 on channel Stable
[12:02:25.581][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:02:25.583][SegmentApi     ][Info   ] Usage statistic: heartbeat
[14:02:25.583][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:02:25.584][SegmentApi     ][Info   ] Usage statistic: heartbeat
[16:02:25.584][SegmentApi     ][Info   ] Usage statistic: heartbeat
[16:56:05.816][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[16:56:11.062][FeedbackSettings][Info   ] Open logs
[16:56:22.498][SegmentApi     ][Info   ] Usage statistic: actionRestart
[16:56:22.502][Notifications  ][Info   ] Docker is restarting...
[16:56:22.516][NamedPipeClient][Info   ] Sending Stop()...
[16:56:22.520][NamedPipeServer][Info   ] Stop()
[16:56:22.530][HyperV         ][Info   ] Stop
[16:56:22.538][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[16:56:22.580][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[16:56:22.597][NamedPipeClient][Info   ] Received response for Stop
[16:56:22.594][NamedPipeServer][Info   ] Stop done.
[16:56:22.601][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[16:56:22.609][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[16:56:22.612][HyperVGuids    ][Info   ] Installing GUIDs...
[16:56:22.616][HyperVGuids    ][Info   ] GUIDs installed
[16:56:22.619][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[16:56:24.604][Firewall       ][Info   ] Ports are opened
[16:56:24.607][HyperV         ][Info   ] Create
[16:56:24.610][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:56:24.886][HyperV         ][Info   ] Using existing Switch: DockerNAT
[16:56:25.031][PowerShell     ][Info   ] Run script 'Import-Module Dism; Get-WindowsOptionalFeature -Online | where FeatureName -like "*Hyper-V*" | where State -ne Enabled'...
[16:56:26.108][HyperV         ][Info   ] Hyper-V is running
[16:56:26.111][HyperV         ][Info   ] Create
[16:56:26.113][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:56:26.208][HyperV         ][Info   ] Using existing Switch: DockerNAT
[16:56:26.251][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[16:56:26.272][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

[16:56:26.276][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

[16:56:41.632][ErrorReportWindow][Info   ] Open logs
[17:02:25.596][SegmentApi     ][Info   ] Usage statistic: heartbeat
[17:02:25.657][Updater        ][Info   ] Checking for updates on channel Stable...
[17:02:25.863][Updater        ][Info   ] Local build 9655 is as good as the remote 9655 on channel Stable
[17:06:48.048][SegmentApi     ][Info   ] Usage statistic: actionMenuFeedback
[17:06:50.054][FeedbackSettings][Info   ] Open github issues
[17:11:47.384][FeedbackSettings][Info   ] Upload diagnostic
[17:11:47.391][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[17:11:47.395][NamedPipeServer][Info   ] GetDebugInfo()
[17:12:10.201][NamedPipeServer][Info   ] GetDebugInfo done.
[17:12:10.216][NamedPipeClient][Info   ] Received response for GetDebugInfo
[17:12:10.239][Program        ][Info   ] Sending Bugsnag report fade9a8e-caac-4ee4-84a2-ab05c4982838...
[17:12:11.672][Program        ][Info   ] Bugsnag report fade9a8e-caac-4ee4-84a2-ab05c4982838 sent
[17:12:11.685][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[17:12:11.689][NamedPipeServer][Info   ] DownloadVmLogs()
[17:12:11.693][PowerShell     ][Info   ] Run script...
[17:12:11.710][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[17:12:11.717][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[17:12:11.714][NamedPipeServer][Info   ] DownloadVmLogs done.
[17:16:01.357][FeedbackSettings][Info   ] Open logs

**Comment by rneugeba** [comment] 2017-01-14 13:55
Thanks for your report. Unfortunately, the diagnostics ID is truncated. The first part should be a full [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier). Could you repost?
Thanks

**Comment by hurricaneMitch** [comment] 2017-01-15 21:56
I am having the same issue and it repros on all of my Windows 10 devices. I have uninstall/reinstalled Docker and Run as Admin. I have launched VMs in Hyper-V with no issue.

Diagnostics ID is 0AFB8C5E-4B18-4C4B-BCD2-A1646425CFBB/2017-01-15_13-52-56

And the logs are 

Version: 1.12.6 (9655)
Channel: Stable
Sha1: 258480fd147da7888a440ed7808d255c0fb15bb7
Started on: 2017/01/15 13:51:51.417
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:51:51.390][Tracking       ][Info   ] Crash report and usage statistics are enabled
[13:51:51.429][SegmentApi     ][Info   ] Usage statistic: appLaunched
[13:51:51.491][NamedPipeClient][Info   ] Sending Version()...
[13:51:51.503][NamedPipeClient][Info   ] Received response for Version
[13:51:51.506][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:51:51.499][NamedPipeServer][Info   ] Version done.
[13:51:51.584][Updater        ][Info   ] Checking for updates on channel Stable...
[13:51:51.584][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[13:51:51.590][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[13:51:51.595][HyperVGuids    ][Info   ] Installing GUIDs...
[13:51:51.599][HyperVGuids    ][Info   ] GUIDs installed
[13:51:51.602][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[13:51:51.674][Updater        ][Info   ] Local build 9655 is as good as the remote 9655 on channel Stable
[13:51:54.730][Firewall       ][Info   ] Ports are opened
[13:51:54.736][HyperV         ][Info   ] Create
[13:51:54.742][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[13:51:55.035][HyperV         ][Info   ] Using existing Switch: DockerNAT
[13:51:55.158][HyperV         ][Info   ] Using existing Switch IP address
[13:51:55.196][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[13:51:56.553][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[13:51:56.843][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[13:51:57.345][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[13:51:57.502][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[13:51:58.219][HyperV         ][Info   ] VM created.
[13:51:58.225][PowerShell     ][Info   ] Run script...
[13:51:58.265][PowerShell     ][Info   ] Run script 'Import-Module Dism; Get-WindowsOptionalFeature -Online | where FeatureName -like "*Hyper-V*" | where State -ne Enabled'...
[13:51:59.464][HyperV         ][Info   ] Hyper-V is running
[13:51:59.468][HyperV         ][Info   ] Create
[13:51:59.472][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[13:51:59.566][HyperV         ][Info   ] Using existing Switch: DockerNAT
[13:51:59.603][HyperV         ][Info   ] Using existing Switch IP address
[13:51:59.642][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[13:52:00.795][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[13:52:01.051][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[13:52:01.536][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[13:52:01.823][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[13:52:02.419][HyperV         ][Info   ] VM created.
[13:52:02.423][HyperV         ][Info   ] Stop
[13:52:02.426][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[13:52:02.481][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[13:52:02.491][HyperVGuids    ][Info   ] Installing GUIDs...
[13:52:02.495][HyperVGuids    ][Info   ] GUIDs installed
[13:52:02.498][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[13:52:05.632][Firewall       ][Info   ] Ports are opened
[13:52:05.637][HyperV         ][Info   ] Create
[13:52:05.642][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[13:52:05.732][HyperV         ][Info   ] Using existing Switch: DockerNAT
[13:52:05.794][HyperV         ][Info   ] Using existing Switch IP address
[13:52:05.833][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[13:52:07.156][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[13:52:07.430][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[13:52:07.933][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[13:52:08.241][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[13:52:08.885][HyperV         ][Info   ] VM created.
[13:52:08.890][PowerShell     ][Info   ] Run script...
[13:52:08.937][NamedPipeServer][Error  ] Unable to execute Start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'FREYA' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Docker.Core.PowerShell.Output(String script)
   at Docker.Backend.Processes.DataKit.<Start>b__3_0()
   at Docker.Backend.Processes.ExternalProcess.StartProcess(String fileName, Func`1 argumentsSupplier)
   at Docker.Backend.Processes.ExternalProcess.Start(Func`1 arguments)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[13:52:08.956][NamedPipeClient][Error  ] Unable to send Start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'FREYA' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
[13:52:08.960][Notifications  ][Error  ] The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'FREYA' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
[13:52:37.729][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[13:52:37.733][NamedPipeServer][Info   ] GetDebugInfo()
[13:52:55.141][NamedPipeServer][Info   ] GetDebugInfo done.
[13:52:55.154][NamedPipeClient][Info   ] Received response for GetDebugInfo
[13:52:55.169][Program        ][Info   ] Sending Bugsnag report b9d86dfe-51a7-492e-b441-a01cd95f71f6...
[13:52:56.047][Program        ][Info   ] Bugsnag report b9d86dfe-51a7-492e-b441-a01cd95f71f6 sent
[13:52:56.065][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[13:52:56.069][NamedPipeServer][Info   ] DownloadVmLogs()
[13:52:56.073][PowerShell     ][Info   ] Run script...
[13:52:56.123][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'FREYA' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
[13:52:56.131][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[13:52:56.127][NamedPipeServer][Info   ] DownloadVmLogs done.
[13:53:15.267][ErrorReportWindow][Info   ] Open logs

**Comment by friism** [comment] 2017-01-15 23:34
@hurricaneMitch it looks like there's a problem with Hyper-V on your machine. Can you try creating any old Hyper-V VM to see if that's functional for you?

It would also be valuable to know whether this is running on hardware or in a VM.

**Comment by cristoforo** [comment] 2017-01-16 14:59
Same issue here.

Diagnostic ID is 27EF6D01-9D82-469E-8AC3-136444A69D4D/2017-01-16_15-57-42
Runnning on hardware

Log:
```
Version: 1.12.6 (9655)
Channel: Stable
Sha1: 258480fd147da7888a440ed7808d255c0fb15bb7
Started on: 2017/01/16 15:53:48.878
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:53:48.720][Tracking       ][Info   ] Crash report and usage statistics are enabled
[15:53:48.974][SegmentApi     ][Info   ] Usage statistic: appLaunched
[15:53:50.100][NamedPipeClient][Info   ] Sending Version()...
[15:53:50.260][NamedPipeClient][Info   ] Received response for Version
[15:53:50.270][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:50:25.106][BackendServer  ][Info   ] Started
[15:50:25.107][Moby           ][Info   ] Connecting...
[15:53:50.224][NamedPipeServer][Info   ] Version()
[15:53:50.241][NamedPipeServer][Info   ] Version done.
[15:53:51.897][Notifications  ][Info   ] Docker is starting...
[15:53:51.915][Updater        ][Info   ] Checking for updates on channel Stable...
[15:53:51.992][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[15:53:52.022][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[15:53:52.040][HyperVGuids    ][Info   ] Installing GUIDs...
[15:53:52.056][HyperVGuids    ][Info   ] GUIDs installed
[15:53:52.130][Updater        ][Info   ] Local build 9655 is as good as the remote 9655 on channel Stable
[15:53:52.164][Firewall       ][Info   ] Opening ports for c:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[15:54:21.394][Firewall       ][Info   ] Ports are opened
[15:54:21.406][HyperV         ][Info   ] Create
[15:54:21.494][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile c:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[15:55:18.639][HyperV         ][Info   ] Using existing Switch: DockerNAT
[15:55:29.327][PowerShell     ][Info   ] Run script 'Import-Module Dism; Get-WindowsOptionalFeature -Online | where FeatureName -like "*Hyper-V*" | where State -ne Enabled'...
[15:56:10.553][HyperV         ][Info   ] Hyper-V is running
[15:56:10.566][HyperV         ][Info   ] Create
[15:56:10.580][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile c:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[15:56:15.125][HyperV         ][Info   ] Using existing Switch: DockerNAT
[15:56:17.545][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[15:56:18.071][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[15:56:18.090][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[15:56:33.202][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[15:56:33.222][NamedPipeServer][Info   ] GetDebugInfo()
[15:57:41.119][NamedPipeServer][Info   ] GetDebugInfo done.
[15:57:41.164][NamedPipeClient][Info   ] Received response for GetDebugInfo
[15:57:41.271][Program        ][Info   ] Sending Bugsnag report 68f11a59-87cb-4390-b201-57bc53566df7...
[15:57:42.804][Program        ][Info   ] Bugsnag report 68f11a59-87cb-4390-b201-57bc53566df7 sent
[15:57:42.860][NamedPipeClient][Info   ] Sending DownloadVmLogs()...
[15:57:42.878][NamedPipeServer][Info   ] DownloadVmLogs()
[15:57:42.899][PowerShell     ][Info   ] Run script...
[15:57:43.012][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[15:57:43.050][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[15:57:43.031][NamedPipeServer][Info   ] DownloadVmLogs done.
[15:58:13.130][ErrorReportWindow][Info   ] Open logs
```

**Comment by cristoforo** [comment] 2017-01-16 19:48
Also tried the `MobyLinux.ps1' -destroy` and `create`:

```
PS C:\Program Files\Docker\Docker\resources> & 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1' -destroy
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
```
But `create` returns an error
```
PS C:\Program Files\Docker\Docker\resources> & 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1' -create
Creating Switch: DockerNAT...
Switch created.
New-NetIPAddress : The object already exists.
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:156 char:23
+ ... rkAdapter | New-NetIPAddress -AddressFamily IPv4 -IPAddress $switchAd ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_NetIPAddress:ROOT/StandardCimv2/MSFT_NetIPAddress) [New-NetIPAddress], CimException
    + FullyQualifiedErrorId : Windows System Error 5010,New-NetIPAddress
```

**Comment by hurricaneMitch** [comment] 2017-01-17 01:46
@friism I am running on hardware. Two different Desktops and a laptop. 
I booted up other VMs with no issue. When I was doing that I noticed that I had about 10 different MobyLinuxVMs. I deleted them all and everything works fine now. Docker drops a new VM on installation and running Docker. 

My suspicion is that, after update of Docker, the previous versions VM is the one failing. Not exactly sure of the code path but I assume an attempt is made to create a new VM. And then maybe it attempts to access the old one again? And repeat for each time this occurs.

I am still reproing the issue on my laptop and another desktop. Any way I can get someone better logs or investigate this theory? Or perhaps you have another theory? I have seen this bug here and in another thread so it would be good to figure out the root cause :)

**Comment by charany1** [comment] 2017-01-17 10:06
I'm facing the same issue .

**Comment by cristoforo** [comment] 2017-01-17 10:12
**[solved]**

Here's what worked for me: Windows 10 has a new "Reset network" command under Settings.
Just applied that, rebooted and Docker was working again.

How to Reset Network interface on Windows 10:
Select the Start  button, then select Settings  > Network & Internet > Status > Network reset.

**Comment by simonferquel** [comment] 2017-01-18 17:12
@cristoforo thanks for the workaround. Alternatively, latest beta should have fixed most of the startup related issues

**Comment by rneugeba** [comment] 2017-02-10 23:09
I'm closing this issue and locking it. The issue is quite old and we have released major updates on both the beta and stable channel. If you still have an issue, please open a new issue.
Thanks

**Closed by rneugeba** 2017-02-10 23:09 UTC
Labels: status/0-more-info-needed, version/1.12.6
