### ISSUE TITLE
Environment Variables not being saved. 

### ISSUE THREAD

**Issue by coryrichardkwikee** [docker/for-win#10660] opened 2021-03-15 22:43 UTC
environment variables are not being saved in Docker Desktop 3.2.2.
Same exact commands, directory structure, and docker-compose files work in previous version, Docker Desktop 3.2.1.
WSL2 backend. 
Solved by downgrading. 

**Directory Setup:** 

-Project_Root_Dir/
    -.env
    -deploy/
        -docker-compose.yml
        -docker-compose.pgadmin.yml

**Command & output:**

$ docker-compose -f deploy/docker-compose.yml -f deploy/docker-compose.pgadmin.yml up -d --build
The ADMIN_EMAIL variable is not set. Defaulting to a blank string.
The AES_KEY variable is not set. Defaulting to a blank string.
The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.

************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without a clear title, description, and diagnostics ID cannot be debugged,
and will be closed. See https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback
for how to generate a diagnostics ID either from inside the app or from the command
line.
************************************************************************************

-->

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-03-16 10:40
Thanks for the report, I'm closing it as a dupe of docker/compose#8192.

**Closed by stephen-turner** 2021-03-16 10:40 UTC
