### ISSUE TITLE
ERROR: Network timed out while trying to connect

### ISSUE THREAD

**Issue by mahnunchik** [docker/for-win#24] opened 2016-08-05 05:36 UTC
### Expected behavior

`docker pull` works

### Actual behavior

`docker pull` does not work

```
ERROR: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.
```

### Information

![error1](https://cloud.githubusercontent.com/assets/780935/17427227/29b64a5c-5b09-11e6-8339-995eb72e3c01.PNG)

![image_from_skype](https://cloud.githubusercontent.com/assets/780935/17427213/f5706318-5b08-11e6-89a9-9f8ac977461d.png)

### Steps to reproduce the behavior

  1. `docker pull any-image`

**Comment by dgageot** [comment] 2016-08-05 09:33
Hi @mahnunchik Could you share your logs or a diagnostic id? Thanks a lot!

**Comment by Icantthinkofanyname** [comment] 2016-08-05 10:00
I have the same issue. I tried it both on stable and beta version as well.

**Comment by dgageot** [comment] 2016-08-05 10:10
Hi @Icantthinkofanyname could you share your logs or a diagnostic id? Thanks a lot!

**Comment by mahnunchik** [comment] 2016-08-05 12:30
@dgageot logs http://pastebin.com/RYi6tY04

**Comment by dgageot** [comment] 2016-08-05 13:45
@Icantthinkofanyname @mahnunchik Can you try with a fixed DNS server?
Something like `8.8.8.8`

![settings-network](https://cloud.githubusercontent.com/assets/153495/17438527/9279a4a2-5b23-11e6-95be-aa1c8dab7fc9.png)

**Comment by mahnunchik** [comment] 2016-08-05 13:50
@dgageot I've tried, nothing has changed.

**Comment by glennsills** [comment] 2016-08-05 17:32
I had this problem. I had previously been using Docker Toolbox with VirtualBox which I had uninstalled before installing Docker for Windows. I tried many suggestions involving fiddling around with the virtual network. Then I noticed that the uninstalling Docker Toolbox had left some folder in my AppData folder and so had Virtual Box. I deleted all that stuff manually, reinstalled Docker for Windows and voila - working Docker. 

This could all be coincidental but you might want to give it a try. It only takes 5 minutes.

**Comment by changeisnormal** [comment] 2016-08-05 19:09
@dgageot I've also tried that and it didn't work for me either. 
@glennsills I had never install toolbox with VirtualBox before so I don't think that fits my situation.

**Comment by changeisnormal** [comment] 2016-08-05 19:24
@dgageot 

A diagnostic was uploaded with id: A4341136-0CD7-4779-AF29-A378002D0636/2016-08-05_15-23-48

**Comment by hineios** [comment] 2016-08-05 20:43
I had the same problem. But after changing to a fixed DNS server it fixed my problem!

**Comment by Senegura** [comment] 2016-08-09 16:29
Fixed DNS server don't solve my problem. I am always get Network timed out while trying to connect to ... You may want to check your internet connection or if you are behind a proxy.

**Comment by saule1508** [comment] 2016-08-12 13:46
I just installed docker, then I had this error. I switched to fixed DNS (8.8.8.8) and it solved the problem. Then I reverted the setting (removed the fixed DNS) and it keeps working.
I found the solution here: http://stackoverflow.com/questions/31990757/network-timed-out-while-trying-to-connect-to-https-index-docker-io

**Comment by Rhynier** [comment] 2016-08-18 16:03
None of the advice above worked for me either. I am running Windows 10 Enterprise version 1511, build 10586.545. Uploaded diagnostic with ID AFCCE8AA-DEFB-4046-93FD-68B40FF3D9D8/2016-08-18_08-55-33.

**Comment by khalidsalomao** [comment] 2016-08-23 14:22
+1
Same problem here with Windows 10 Pro version 1607 build 14393.51.
Diagnostic ID: B625FBF8-26D1-4A80-8F24-B93512DD68B9/2016-08-23_11-18-23

**Comment by zcl0621** [comment] 2016-08-24 01:34
+1 
I always got this issue

**Comment by dgageot** [comment] 2016-09-08 14:39
@mahnunchik @Icantthinkofanyname @changeisnormal @Senegura @Rhynier @khalidsalomao @zcl0621 A new version (Beta25) was released yesterday with fixes to the network/dns stack. Could you please give it a try and tell us if you see an improvement? Thanks a lot!

**Comment by saule1508** [comment] 2016-09-09 07:35
@dgageot : it solved the problem for me, thanks. (in a previous post I mentioned that switching to fixed DNS solved my issue but it was only temporarily fixed).

**Comment by dgageot** [comment] 2016-09-09 07:36
@saule1508 \0/

**Comment by dgageot** [comment] 2016-09-09 12:38
I believe this is a duplicate of #55 

When I get a bit more users saying that Beta25 fixes the issue, I'll close both tickets

**Comment by dgageot** [comment] 2016-09-10 10:33
Looks like Beta25 fixes the issue for a lot of users and nobody complained that the issue is still here. So let's close this ticket!

**Closed by dgageot** 2016-09-10 10:33 UTC
Labels: area/network, kind/bug, version/1.12.0, version/beta24

**Comment by mahnunchik** [comment] 2016-09-10 11:15
It solved my problem. Thanks!

**Comment by khalidsalomao** [comment] 2016-09-26 15:47
Problem solved!
