### ISSUE TITLE
Spelling error on update screen

### ISSUE THREAD

**Issue by naikrovek** [docker/for-win#12462] opened 2021-12-23 17:38 UTC
OK so this is a stupid spelling issue and not a technical issue.  I'm not going to go through the process of collecting all of this data, since it isn't applicable anyway.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1234_to_make_the_bot_happy

### Actual behavior
incorrect spelling in settings page.

### Expected behavior
correct spelling in settings page.

### Information
  - Windows Version:  Windows 11 22523.1000
  - Docker Desktop Version: 4.3.2 (72729)
  - WSL2 or Hyper-V backend?  WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical machine.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Not relevant.

### Steps to reproduce the behavior

  1. I can't test this on the latest version, because there is no update available, but:
  2. When an update is available, a button is shown in the Software Updates page of Settings that should say "Release Notes" but instead says "Release*s* Notes" (note the 2nd "s" in "Releases") and it's a stupid thing to file an issue for, but it drives me nuts.  "Release" should be singular, even if the button takes you to a list of release notes.

**Comment by stephen-turner** [comment] 2022-01-06 13:48
Thanks for reporting this. It will be fixed in the next version.

**Comment by naikrovek** [comment] 2022-01-26 12:45
I think this was fixed in 4.4.2, and in 4.4.3 it returned.  if it wasn't fixed in 4.4.1 or 4.4.2, then never mind.  If it was, then it got re-broken.

**Comment by stephen-turner** [comment] 2022-01-26 14:45
Thanks. I know it was fixed because I fixed it myself. It must have got reverted.

**Comment by stephen-turner** [comment] 2022-01-26 14:49
Strange, it looks OK in the source. Unless there's another instance I missed.

**Comment by stephen-turner** [comment] 2022-01-26 18:14
@naikrovek I can't reproduce this. I just tried 4.4.3 and the button says "Release notes" as it should. Can you reproduce it and send a screenshot in case we're looking in a different place?

**Comment by naikrovek** [comment] 2022-01-26 18:22
I updated from 4.3.3 to 4.4.4 on THREE machines this morning and it said "Releases notes" on all three, and I did not take a screenshot.  :(  Go ahead and close this again, and if I see it again, I'll comment WITH a screenshot :)

**Comment by stephen-turner** [comment] 2022-01-26 18:23
OK, shall do, thanks.

**Closed by stephen-turner** 2022-01-26 18:23 UTC
Labels: version/4.3.2
