### ISSUE TITLE
vpnkit.exe increases up to all physical memory

### ISSUE THREAD

**Issue by doctorpepper608** [docker/for-win#2021] opened 2018-05-10 13:06 UTC
Crazy extending memory size of vpnkit.exe

### Expected behavior
-
### Information
diagnostic link C028AA6E-8408-4344-93DF-A19EAA986A07/2018-05-10_16-02-43
### Steps to reproduce the behavior

.1. Docker run.

**Comment by rn** [comment] 2018-05-10 13:12
thanks for the report. This looks like a dup of #1932 and is already tracked in the upstream vpnkit repository moby/vpnkit#371 so I'm closing this here. If you have a specific reproduction, please add them to the VPNKit ticket. Thanks

**Closed by rn** 2018-05-10 13:12 UTC
