### ISSUE TITLE
manual proxy configuration switch does not disable proxy settings

### ISSUE THREAD

**Issue by SGrunder** [docker/for-win#9687] opened 2020-12-03 13:41 UTC
when proxy settings are entered in the resources/proxy screen and the manual proxy configuration switch is disabled,
The proxy settings (that are disabled in the screen) are still active.
This can be easily checked by running "docker info"

IMy guess was that is hould be easy to turn proxy settings on and off by using the switch.
This is not possible, the proxy fields have to be emptied when you don't want to use any proxy.
The switch is therefore useless.

**Comment by stephen-turner** [comment] 2020-12-03 15:57
Thanks for the report. This is a dupe of #9357.

**Closed by stephen-turner** 2020-12-03 15:57 UTC
