### ISSUE TITLE
Docker desktop - Switching to windows contianer resulting in error

### ISSUE THREAD

**Issue by dinilvenugopal** [docker/for-win#6811] opened 2020-05-20 15:36 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by dinilvenugopal** [comment] 2020-05-20 15:38
•Diagnostics ID: EF664E5B-6035-485E-A68D-5DD193187FCD/20200520151918

**Comment by stephen-turner** [comment] 2020-05-20 16:33
Closing as dupe of #6812.

**Closed by stephen-turner** 2020-05-20 16:33 UTC
