### ISSUE TITLE
Cannot install Docker Desktop to external drive or non-system drive

### ISSUE THREAD

**Issue by MichaelNZ85** [docker/for-win#12933] opened 2022-08-26 01:26 UTC
The Windows version of Docker Desktop has no option to install the program (or store the containers) on a drive other than the system drive (normally C:). My system drive is a small SSD and I install the majority of my programs to an additional HDD with much more space. 

I can do this with Docker Desktop for Mac on my other computer, but currently this is not an option for Windows.

**Comment by nicks** [comment] 2022-08-30 17:15
Thanks for reporting! I'm going to mark this as a duplicate of https://github.com/docker/roadmap/issues/94, please subscribe to that issue.

**Closed by nicks** 2022-08-30 17:15 UTC
