### ISSUE TITLE
Docker occasionally not starting up

### ISSUE THREAD

**Issue by SetTrend** [docker/for-win#11175] opened 2021-05-11 16:40 UTC
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: `F9C61679-70F2-4888-B1A0-BB9182F5AFBD/20210511163051`

#### Every once or twice in a week Docker for Windows won't start when I'm launching my VM:

![Docker daemon won't start](https://user-images.githubusercontent.com/9283914/117852676-dfccc480-b287-11eb-9402-c3dc5e61cfea.gif)

### Expected behavior

Everything should run flawlessly.

### Information
  - Windows Version: Windows 10x64, v20H2
  - Docker Desktop Version:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:26:56 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```
  - WSL2 or Hyper-V backend? WSL2 (running on Windows containers though)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Yes, VMware Workstation VM (latest).

**Comment by stephen-turner** [comment] 2021-05-14 09:45
I think this is a dupe of #11047, so I'm going to close this issue and you can follow there for updates. In particular please see my latest comment there (https://github.com/docker/for-win/issues/11047#issuecomment-841136100) for something to try.

**Closed by stephen-turner** 2021-05-14 09:45 UTC
