### ISSUE TITLE
Docker crashing after Windows update

### ISSUE THREAD

**Issue by zphinxify** [docker/for-win#11987] opened 2021-08-24 14:13 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B5CCFE8A-BCAA-48EF-B217-0E0E081D80E6/20210824140712

### Actual behavior:
Upon installing the latest windows update as of 24/8-21, docker no longer works.
My co-worker had the same issue, but he somehow solved it after 5-6h.

### Expected behavior
Docker should work, I guess.

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes, you only have to install the latest windows update.
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes, windows related issue
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version:
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2 I guess (windows back-end)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: ?

### Steps to reproduce the behavior
Install windows update and the issue arises. Have been the same for my boss and co-workers.
A reproducible case, Dockerfiles with reproduction inside is best.

I have seen similar issues being voiced here, but none of the proposed solutions work for me.
I've tried to re-install docker several times, enabled Hyper-V for windows. Nothing works.

Quite frustrating, since this is a reoccuring issue with every update in regards to windows

**Comment by zphinxify** [comment] 2021-08-24 14:23
Ok so I seem to have found the issue as to why this won't work...

I genuinly hope this works for you aswell:

Go to C:\ProgramData\Docker
Right click on panic.txt → Properties
Uncheck ‘Read-Only’

**Comment by elliottmatt** [comment] 2021-08-24 22:55
I agree with above. Worked for me.

**Comment by zphinxify** [comment] 2021-08-25 06:09
So I just came in to work, and the same issue arises. Instead of having to unmark the panic.txt file every time, I'll simply downgrade to Docker v 3.5.2, since this worked the last time.

**Comment by stephen-turner** [comment] 2021-08-25 11:29
This is a dupe of https://github.com/docker/for-win/issues/11899: there is a test build there that we believe fixes the issue.

**Closed by stephen-turner** 2021-08-25 11:29 UTC
