### ISSUE TITLE
Error While Switching to windows

### ISSUE THREAD

**Issue by tabbu-syeda** [docker/for-win#11933] opened 2021-08-19 05:18 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6FD2BC3E-C180-4177-8618-5E37CA036697/20210819050828

### Actual behavior
Docker.Core.DockerException:
Could not save daemon configuration to C:\ProgramData\Docker\config\daemon.json: Access to the path 'C:\ProgramData\Docker\config' is denied.
   at Docker.ApiServices.DaemonOpts.DaemonOptionsLoader.Get(ContainerEngineMode mode) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\DaemonOpts\DaemonOptionsLoader.cs:line 63
   at Docker.ApiServices.DaemonOpts.DaemonOptionsLoader.GetAsJson(ContainerEngineMode mode) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\DaemonOpts\DaemonOptionsLoader.cs:line 75
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WindowsContainersEngine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WindowsContainersEngine.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

  System.UnauthorizedAccessException:
  Access to the path 'C:\ProgramData\Docker\config' is denied.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
     at Docker.Core.Paths.EnsureParentDirectoryIsCreated(String path) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:line 120
     at Docker.ApiServices.DaemonOpts.DaemonOptionsLoader.Save(ContainerEngineMode mode, DaemonOptions options) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\DaemonOpts\DaemonOptionsLoader.cs:line 80
     at Docker.ApiServices.DaemonOpts.DaemonOptionsLoader.Get(ContainerEngineMode mode) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\DaemonOpts\DaemonOptionsLoader.cs:line 59
  
### Expected behavior
Successfully switched to Windows container.
### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ..
  2. ...
[log.txt](https://github.com/docker/for-win/files/7011909/log.txt)

**Comment by StefanScherer** [comment] 2021-08-19 07:54
Thanks for reporting. It's a duplicate of #11899 where you can find a workaround (make the panic.log writable).

**Closed by StefanScherer** 2021-08-19 07:54 UTC
