### ISSUE TITLE
Unable to start docker on windows 10

### ISSUE THREAD

**Issue by kishutvn** [docker/for-win#82] opened 2016-09-15 13:50 UTC
### Expected behavior
Docker service should start successfully
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...install docker on windows 10 vm
  2. ... After install got the attached log report
[log-2016-09-15_19-00-44.txt](https://github.com/docker/for-win/files/474790/log-2016-09-15_19-00-44.txt)

**Comment by dgageot** [comment] 2016-09-16 16:39
Hi @kishutvn Could you please try version beta26? If the problem is still here, could you upload a full diagnostic and paste the diag id here? That would be really helpful!

**Comment by dgageot** [comment] 2016-09-21 14:46
Hi @kishutvn Did a more recent version fix the issue for you?

**Comment by kishutvn** [comment] 2016-09-22 11:16
Hi @dgageot,
Stuck up with other issues, sorry for coming late on this thread.
-----------------------
More details----, Attached log, version info 
------
crash id:2AA78F72-7B74-4BB8-9E3D-134C8538E37C/2016-09-22_16-35-30
Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[docker_version_info.txt](https://github.com/docker/for-win/files/487094/docker_version_info.txt)
[log.txt](https://github.com/docker/for-win/files/487096/log.txt)

Installed URi: https://download.docker.com/win/beta/InstallDocker.msi

**Comment by rneugeba** [comment] 2016-09-23 14:07
@kishutvn you seem to be running windows 10 Pro in a VMware VM. Docker for windows also makes use of Hardware virtualisation (which VMware also uses).  In your case Hyper-V fails to start because the VM does not support the hardware virtualisation it needs:
```
9/22/2016 3:05:59 PM            41 Error            Hypervisor launch failed;
                                                    Either VMX not present or
                                                    not enabled in BIOS.
```
This *may* work if you enable nested virtualisation for your Windows VM, but in general this is a configuration we do not support, so I'm closing the issue.

**Closed by rneugeba** 2016-09-23 14:07 UTC
Labels: kind/bug, version/beta26
