### ISSUE TITLE
Docker Windows will not start: Cancellation token triggered before we finished reading from the stream.

### ISSUE THREAD

**Issue by voycey** [docker/for-win#11601] opened 2021-07-06 05:36 UTC
I have read through what seems like every iteration on this error but nothing suggested has solved it.

This is a brand new XPS 9700 - fresh install.

I have disabled all antivirus and firewalls, I have reinstalled WSL2 and even tried multiple distros.

I have factory reset several times, rebooted more times, deleted app data and reinstalled. Nothing works at all :(

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: D602511F-9E77-40F4-BD2A-4BE9508C800E/20210706052449

 Windows Version:
  - Docker Desktop Version: 
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

Error message:

`Error invoking remote method 'desktop-backend': Error: {"error":true,"type":0,"reason":"Cancellation token triggered before we finished reading from the stream.","details":"System.Threading.Tasks.TaskCanceledException: Cancellation token triggered before we finished reading from the stream.\r\n at HttpOverStream.ByLineReader.<ReadLineAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.Core.IPC.Client.<SendAsync>d__4.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Core\\IPC\\Client.cs:line 41\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.LifecycleClient.<DockerStartAsync>d__4.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\LifecycleClient.cs:line 84\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Desktop\\LinuxkitDaemonStartup.cs:line 30\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Desktop\\Engines\\WSL2\\LinuxWSL2Engine.cs:line 178\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\StateMachines\\TaskExtensions.cs:line 20\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\StateMachines\\StartTransition.cs:line 29\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\StateMachines\\StartTransition.cs:line 38\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\StateMachines\\EngineStateMachine.cs:line 69\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Desktop\\Engines\\Engines.cs:line 114\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.Services.SettingsService.<SetInternalAsync>d__16.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Services\\SettingsService.cs:line 147\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.ApiServices.Services.SettingsService.<SetAsync>d__15.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Services\\SettingsService.cs:line 95\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Docker.HttpApi.Controllers.SettingsController.<Post>d__8.MoveNext() in C:\\workspaces\\PR-16024\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\SettingsController.cs:line 67","url":null,"settings":{"cli":{"useComposeV2":false},"desktop":{"disableUpdate":false,"analyticsEnabled":true,"autoStart":false,"backupData":false,"disableTips":false,"tipLastViewedTime":0,"tipLastId":0,"updateAvailableTime":0,"updatePopupAppearanceTime":0,"exportInsecureDaemon":true,"useCredentialHelper":true,"wslEngineEnabled":true,"wslPreconditionMessage":null,"openUIOnStartupDisabled":false,"displayedTutorial":false},"vm":{"daemon":"{\r\n \"registry-mirrors\": [],\r\n \"insecure-registries\": [],\r\n \"debug\": false,\r\n \"experimental\": false,\r\n \"features\": {\r\n \"buildkit\": true\r\n },\r\n \"builder\": {\r\n \"gc\": {\r\n \"enabled\": true,\r\n \"defaultKeepStorage\": \"20GB\"\r\n }\r\n }\r\n}","fileSharing":[],"kubernetes":{"enabled":false,"showSystemContainers":false},"network":{"automaticDNS":true,"dns":"8.8.8.8","socksProxyPort":0,"vpnkitCIDR":"192.168.65.0/24"},"proxy":{"mode":"system","http":"","https":"","exclude":""},"resources":{"cpus":{"value":8,"min":1,"max":16},"memoryMiB":{"value":2048,"min":1024,"max":30464},"swapMiB":{"value":1024,"min":512,"max":4096},"diskSizeMiB":{"value":65536,"used":0},"dataFolder":"C:\\ProgramData\\DockerDesktop\\vm-data"}},"wslIntegration":{"distros":[],"enableIntegrationWithDefaultWslDistro":true}}}`

**Comment by voycey** [comment] 2021-07-06 23:58
Downgrading to 3.4.0 solved this - 3.5.1 is very broken by the looks of it
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-340

**Comment by llslim** [comment] 2021-07-08 02:59
I too had to downgrade to 3.4.0 for the same error on both xps 13 laptop and desktop running the latest windows 21H1 update

**Comment by lorenrh** [comment] 2021-07-09 09:57
Thanks for the report! We are investigating this issue.

**Comment by djs55** [comment] 2021-07-09 09:59
@voycey looking through the diagnostics I see:
```
[15:24:37.784][ApiProxy          ][Fatal  ] msg="ensuring desktop context: querying desktop-linux docker context: invalid character '\\x00' looking for beginning of value"
```
There may be something wrong with the database of docker contexts. Could you run `docker context ls` and paste the output?

**Comment by djs55** [comment] 2021-07-09 13:04
@voycey I've got a developer build which should work around this problem: https://desktop-stage.docker.com/win/stable/amd64/66555/Docker%20Desktop%20Installer.exe In this build the "invalid character" error is logged but isn't fatal, so hopefully the app should start. This build will also add some `docker context inspect` commands to the diagnostics.

If you get a chance to try it, let me know if it helps! If you still have problems, please upload a fresh set of diagnostics and quote the ID here. It might also help as a workaround to take a backup of `.docker` in your home directory and then delete it, in case there are some corrupt files in there.

**Comment by daffodilistic** [comment] 2021-07-10 12:48
> @voycey I've got a developer build which should work around this problem: https://desktop-stage.docker.com/win/stable/amd64/66555/Docker%20Desktop%20Installer.exe In this build the "invalid character" error is logged but isn't fatal, so hopefully the app should start. This build will also add some `docker context inspect` commands to the diagnostics.
> 
> If you get a chance to try it, let me know if it helps! If you still have problems, please upload a fresh set of diagnostics and quote the ID here. It might also help as a workaround to take a backup of `.docker` in your home directory and then delete it, in case there are some corrupt files in there.

Finally, the developer build of Docker runs on my W10 21H1 machine...Docker broke after v3.2.2...

**Comment by daffodilistic** [comment] 2021-07-12 04:41
An update - after installing the preview build, it failed to start again, but after some tinkering around, it seems that Folding@Home on Medium setting affects the startup and shutdown of Docker Engine. Not sure if this helps but it might work for others who have the same problem as me.

**Comment by voycey** [comment] 2021-07-12 04:49
> @voycey looking through the diagnostics I see:
> 
> ```
> [15:24:37.784][ApiProxy          ][Fatal  ] msg="ensuring desktop context: querying desktop-linux docker context: invalid character '\\x00' looking for beginning of value"
> ```
> 
> There may be something wrong with the database of docker contexts. Could you run `docker context ls` and paste the output?

Hey sorry I have had to uninstall it and go back a version, I can say that I completely cleared out Docker (Registry and Deleting APPDATA folders) after each uninstall to no avail

**Comment by hepter** [comment] 2021-07-12 09:39
> @voycey I've got a developer build which should work around this problem: https://desktop-stage.docker.com/win/stable/amd64/66555/Docker%20Desktop%20Installer.exe In this build the "invalid character" error is logged but isn't fatal, so hopefully the app should start. This build will also add some `docker context inspect` commands to the diagnostics.
> 
> If you get a chance to try it, let me know if it helps! If you still have problems, please upload a fresh set of diagnostics and quote the ID here. It might also help as a workaround to take a backup of `.docker` in your home directory and then delete it, in case there are some corrupt files in there.

This build version works fine. Thanks. I haven't had any issues with this version but I can share the Diagnostics ID again if it helps you investigate more.

**Comment by djs55** [comment] 2021-07-13 08:16
@hepter I'm glad this build is working better. Sharing another diagnostics ID is a good idea -- if you have time to do that then I'll look through the logs and check that everything looks ok. Thanks!

**Comment by hepter** [comment] 2021-07-13 08:32
@djs55 Sure. You can check this Diagnostic ID: 71E9D3A7-2400-46B1-924C-1B270C2467B6/20210713082219

**Comment by djs55** [comment] 2021-07-13 15:04
@daffodilistic I'm glad you solved your problem. Next time you have a problem (presumably a timeout) starting Docker could you upload diagnostics and quote the ID? I'd like us to cope better with busy machines. There is probably a timeout somewhere which should be removed / made much larger.

**Comment by sozercan** [comment] 2021-07-13 23:12
@djs55 another diagnostic ID for error:
`"ensuring desktop context: querying desktop-linux docker context: invalid character '\\x00' looking for beginning of value"`

0D5AB2C2-745F-4437-A046-4CC268CB866D/20210713230812

**Comment by edwardtew** [comment] 2021-07-21 23:19
With the developer build 3.6.0 (linked above)
I can get docker started but changing settings and interaction with the `Docker Desktop` app seems to be broken/limited.

![image](https://user-images.githubusercontent.com/19808346/126571506-3aead4e5-012c-46d8-be4a-8044908f7626.png)

Clicking Apply/Restart and I get this 
![image](https://user-images.githubusercontent.com/19808346/126571553-d44258bc-9472-4a1f-a567-04a659bcdafc.png)

Under WSL2 I also notes that the `.docker/contexts` dir is a symlink/junction back to itself.
```
#:~/.docker$ ls -la
-rwxr--r-- 1 edward.tew edward.tew   83 Jul 22 10:53 config.json
lrwxrwxrwx 1 edward.tew edward.tew   36 Jul 21 11:20 contexts -> /c/Users/edward.tew/.docker/contexts
-rwxr--r-- 1 edward.tew edward.tew  252 Jul 19 18:53 daemon.json
drwxr-xr-x 1 edward.tew edward.tew 4096 Jul  7 15:00 devenvironments
-rw-r--r-- 1 edward.tew edward.tew    0 Jul  8 16:30 features.json
drwxr-xr-x 1 edward.tew edward.tew 4096 Jul 22 10:53 run
drwxr-xr-x 1 edward.tew edward.tew 4096 Jul  7 14:41 scan
```

Diagnostics uploaded here:
`44079AE5-0EFB-42CB-B39A-64D810FACE74/20210721230917`

**Comment by voycey** [comment] 2021-08-06 07:25
Just to confirm - I installed this one today and the preview build above works for me too!

**Comment by camicase82** [comment] 2021-08-09 02:29
Hi there, confirming the issue here, I got these 2 report numbers, 0719236E-BEFC-4D87-B0C6-26C59DB18E4D/20210808211621
0719236E-BEFC-4D87-B0C6-26C59DB18E4D/20210808211701 tested the suggested build and my containers are up and running again

**Comment by ulyssessouza** [comment] 2021-08-11 16:56
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.

**Closed by ulyssessouza** 2021-08-11 16:56 UTC

**Comment by goostleek** [comment] 2021-08-12 07:22
I can confirm the problem was related to https://github.com/docker/for-win/issues/11601 and upgrading to 3.6.0 resolved the issue for me 🎉.
