### ISSUE TITLE
Docker in WSL 2 hanging and never accomplish the command

### ISSUE THREAD

**Issue by moreirayokoyama** [docker/for-win#7904] opened 2020-07-30 17:22 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I want to pull a new image and be able to run containers from WSL 2.

### Actual behavior

docker build, docker run, docker pull... none of these commands work on WSL 2. Unless I already have the image pulled, I can't start a new container.

### Information
I can still pull images or build new ones from windows terminal. And only then go back to linux and use them.

  - Windows Version: Windows 10 Pro Insider Preview Build 20180.rs_prerelease.200725-1714
  - Docker Desktop Version: 19.03.12
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
From WSL 2, run any command that make Docker create a new image... docker build, docker run, docker pull.
  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-07-30 17:26
It's a Windows bug, dupe of #7808.

**Closed by stephen-turner** 2020-07-30 17:26 UTC
