### ISSUE TITLE
Docker pulling failed on Server 2016 Standard

### ISSUE THREAD

**Issue by viscropst** [docker/for-win#452] opened 2017-01-31 16:26 UTC
Hi there,
I am a beginner for Windows Container on Windows Server 2016 with docker.
I tried to docker push microsoft/sample-dotnet
### Expected behavior
Pulling successful and Running well. 
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/16207250/22473785/ee563ea6-e814-11e6-933e-c915042eb781.png)

### Information
I am using CMD with Administrator mode.
  
![image](https://cloud.githubusercontent.com/assets/16207250/22471721/2c5f6a58-e80e-11e6-89c5-9a5cd4fd5a23.png)

![image](https://cloud.githubusercontent.com/assets/16207250/22471746/3e7af180-e80e-11e6-8620-93cd90a2b363.png)

### Steps to reproduce the behavior

  1. Start the cmd with Administrator mode.
  2. docker run microsoft/sample-dotnet
  
![image](https://cloud.githubusercontent.com/assets/16207250/22473776/e8f7c97a-e814-11e6-86ee-49317fdcdfe5.png)

**Comment by friism** [comment] 2017-01-31 16:31
Thanks for reporting!

Please see this issue for possible fixes and more details: https://github.com/Microsoft/Virtualization-Documentation/issues/355

The problem is not related to the Docker for Windows product, so I'll close this issue - feel free to reopen or follow up if you have questions.

**Closed by friism** 2017-01-31 16:31 UTC

**Comment by viscropst** [comment] 2017-02-01 02:32
And I found a new problem,I can not login the docker hub in docker.
![image](https://cloud.githubusercontent.com/assets/16207250/22493202/a01f838c-e869-11e6-90e9-fd3b58f992a2.png)

**Comment by friism** [comment] 2017-02-01 02:40
@viscropst have you created an account?

**Comment by viscropst** [comment] 2017-02-01 03:23
I created the account and type the correct password.
