### ISSUE TITLE
Exception when pulling an image

### ISSUE THREAD

**Issue by johnvanloon** [docker/for-win#363] opened 2016-12-29 08:13 UTC
After getting the anniversary update of Windows 10 (Winver: 1607, build 14393.576) I followed the steps on this page: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10

However when trying to pull any image (tried several from docker-hub, both based on nano-server and server-core), I get an exception when the first layer is at 100% extracting:

failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e\UtilityVM: winapi error #3489661090

At the same time a find an error in the Windows Event viewer from hpdskflt. EventId is 1001 and there is no 
description. After some searching I found that hpdskflt relates to the 'HP Mobile Data Protection Sensor'. This sensor should stall the head of a harddisk when falling. However this laptop contains an SSD, so this does not really make sense. Therefore I tried to disable it, but did not succeed. I cannot disable it in device manager and also not from the BIOS.

Diagnostic ID from "Diagnose & Feedback" in the menu: 5FD2D3E0-F72B-486F-A8E4-26BC33063E9D/2016-12-29_09-03-07

Extract from logfile:
[08:18:41.475][ApiProxy       ][Info   ] Successfully dialed name pipe \\.\pipe\docker_engine_windows
[08:18:41.476][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:41.476959000+01:00" level=debug msg="Calling POST /v1.25/images/create?fromImage=microsoft%2Fnanoserver&tag=latest" 
[08:18:41.479][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:41.479958000+01:00" level=debug msg="Trying to pull microsoft/nanoserver from https://registry-1.docker.io v2" 
[08:18:42.944][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:42.944968900+01:00" level=debug msg="Pulling ref from V2 registry: microsoft/nanoserver:latest" 
[08:18:43.443][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:43.443974600+01:00" level=debug msg="pulling blob \"sha256:10bf725c5388a1909f7184467b5ec75dbad3ece68508aa5fa4074baa0b20cc6f\"" 
[08:18:43.443][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:43.443974600+01:00" level=debug msg="pulling blob \"sha256:bce2fbc256ea437a87dadac2f69aabd25bed4f56255549090056c1131fad0277\"" 
[08:18:43.444][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:43.443974600+01:00" level=debug msg="Pulling sha256:bce2fbc256ea437a87dadac2f69aabd25bed4f56255549090056c1131fad0277 from foreign URL https://go.microsoft.com/fwlink/?linkid=837858" 
[08:18:43.444][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:43.444973200+01:00" level=debug msg="Pulling sha256:10bf725c5388a1909f7184467b5ec75dbad3ece68508aa5fa4074baa0b20cc6f from foreign URL https://go.microsoft.com/fwlink/?linkid=837895" 
[08:18:55.319][WindowsDockerDaemon][Info   ] time="2016-12-29T08:18:55.319455200+01:00" level=debug msg="Downloaded 10bf725c5388 to tempfile C:\\WINDOWS\\TEMP\\GetImageBlob161398455" 
[08:19:13.106][WindowsDockerDaemon][Info   ] time="2016-12-29T08:19:13.105265400+01:00" level=debug msg="Downloaded bce2fbc256ea to tempfile C:\\WINDOWS\\TEMP\\GetImageBlob112381610" 
[08:19:13.108][WindowsDockerDaemon][Info   ] time="2016-12-29T08:19:13.108286100+01:00" level=debug msg="hcsshim::CreateLayer Flavour 1 ID cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e parent " 
[08:19:13.109][WindowsDockerDaemon][Info   ] time="2016-12-29T08:19:13.109263300+01:00" level=debug msg="hcsshim::CreateLayer  - succeeded id=cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e parent= flavour=1" 
[08:20:59.260][WindowsDockerDaemon][Info   ] time="2016-12-29T08:20:59.260649400+01:00" level=debug msg="Cleaning up layer cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\\ProgramData\\Docker\\windowsfilter\\cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e\\UtilityVM: winapi error #3489661090" 
[08:20:59.261][WindowsDockerDaemon][Info   ] time="2016-12-29T08:20:59.261650500+01:00" level=debug msg="HCSShim::GetContainers query={}" 
[08:20:59.262][WindowsDockerDaemon][Info   ] time="2016-12-29T08:20:59.262651500+01:00" level=debug msg="HCSShim::GetContainers succeeded" 
[08:20:59.274][WindowsDockerDaemon][Info   ] time="2016-12-29T08:20:59.274650300+01:00" level=debug msg="hcsshim::DestroyLayer Flavour 1 ID cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e-removing" 
[08:21:05.621][WindowsDockerDaemon][Info   ] time="2016-12-29T08:21:05.621429400+01:00" level=debug msg="hcsshim::DestroyLayer succeeded flavour=1 id=cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e-removing" 
[08:21:05.632][WindowsDockerDaemon][Info   ] time="2016-12-29T08:21:05.632424300+01:00" level=error msg="Error trying v2 registry: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\\ProgramData\\Docker\\windowsfilter\\cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e\\UtilityVM: winapi error #3489661090" 
[08:21:05.632][WindowsDockerDaemon][Info   ] time="2016-12-29T08:21:05.632424300+01:00" level=error msg="Attempting next endpoint for pull after error: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\\ProgramData\\Docker\\windowsfilter\\cbfdb4917ee9a193389883595309771c9a60e8bf71faa922261be2e60cb26a4e\\UtilityVM: winapi error #3489661090"

**Comment by rneugeba** [comment] 2016-12-29 10:22
@johnvanloon thanks for your report. Could you try the `Debug-ContainerHost.ps1` script from: https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost and see if that shows up anything?

Also, could your provide a diagnostics ID? This uploads additional information which might be useful for debugging this issue
Thanks

**Comment by johnvanloon** [comment] 2016-12-29 11:57
Diagnostics ID = 5FD2D3E0-F72B-486F-A8E4-26BC33063E9D/2016-12-29_09-03-07

Output from Debug-ContainerHost.ps1 is below.
The fact that the base-image is not installed, makes sense as I'm not able to pull any.
Looking at the network  message right now, but I think that's not related, right?


Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 64ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 26ms
 [+] Is not a build with blocking issues 25ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  42ms
 [+] Service is running 22ms
 [+] Docker.exe is in path 2.05s
 [+] Docker is registered in the EventLog service 26ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 33ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 39ms
 [+] Do not have zz values set 28ms
Describing The right container base images are installed
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 89ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\Users\jovanloon\Downloads\Debug-ContainerHost.ps1: line 99
Describing Container network is created
 [+] At least one local container network is available 1.48s
 [+] At least one NAT, Transparent, or L2Bridge Network exists 22ms
 [+] NAT Network's vSwitch is internal 23ms
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 57ms
   Expected: {True}
   But was:  {False}
   209:       $vmNicGatewayIPExists | Should Be $true
   at <ScriptBlock>, C:\Users\jovanloon\Downloads\Debug-ContainerHost.ps1: line 209
 [+] NAT Network's internal prefix does not overlap with external IP' 44ms
Showing output from: docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88 GiB
Name: NLLT106817
ID: A7IW:3XHD:O7Y2:JOBR:RAXM:E2ZQ:RIXO:N4AG:AYZ5:YUAH:GAL7:FA6T
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Showing output from: docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64
 Experimental: false

Showing output from: docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
b2d707139ddc        nat                 nat                 local
c3bd6f287e77        none                null                local

Warnings & errors from the last 24 hours


   ProviderName: docker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
29-12-2016 11:55:09              1 Error            Attempting next endpoint for pull after error: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\... 29-12-2016 11:55:09              1 Error            Error trying v2 registry: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\... 29-12-2016 11:53:42              1 Error            Resolver Setup/Start failed for container nat, "error in opening name server socket listen udp 172.23.16.1:53: bind: The requested address is not va... 29-12-2016 11:53:41              1 Error            Resolver Setup/Start failed for container nat, "error in opening name server socket listen udp 172.23.16.1:53: bind: The requested address is not va... 29-12-2016 11:53:40              1 Error            Resolver Setup/Start failed for container nat, "error in opening name server socket listen udp 172.23.16.1:53: bind: The requested address is not va...

**Comment by johnvanloon** [comment] 2016-12-29 12:06
FYI: Fixed the NAT issue in the debug-output. However, as expected, this does not resolve the issue of not being able to pull an image.

**Comment by simonferquel** [comment] 2017-01-02 14:14
@friism it seems not to be a docker for desktop bug but more a Windows container issue. Can you bring someone to help diagnose it ?

**Comment by friism** [comment] 2017-01-02 18:23
@johnvanloon I think this might be a dupe of https://github.com/Microsoft/Virtualization-Documentation/issues/355

In addition to the HP stuff, do you have any antivirus software that might cause trouble?

**Comment by johnvanloon** [comment] 2017-01-03 08:03
It indeed seems to be a duplicate of that issue.
We are using Windows Defender for anti-malware and I am not able to disable that or that exclude any files or folders.

**Comment by rneugeba** [comment] 2017-01-03 10:55
@johnvanloon thanks for checking and commenting on  Microsoft/Virtualization-Documentation#355. The issue is probably better tracked there as this seems to be a more generic Windows issue rather than a Docker for Windows issue, so I'm closing this here. If you prefer tracking here, please re-open.
Thanks

**Closed by rneugeba** 2017-01-03 10:55 UTC
Labels: area/wincon, status/0-more-info-needed

**Comment by marvinvperez** [comment] 2017-01-07 12:39
@johnvanloon 
Hi, can you share how did you fix the NAT issue? I'm also getting this error. Thanks

[-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 57ms
Expected: {True}
But was: {False}
209: $vmNicGatewayIPExists | Should Be $true
at , C:\Users\jovanloon\Downloads\Debug-ContainerHost.ps1: line 209

**Comment by rneugeba** [comment] 2017-01-07 13:09
@marvinvperez could you try:
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking

This is supposed to diagnose and fix up networking issues with Windows Containers
Thanks

**Comment by marvinvperez** [comment] 2017-01-07 14:18
@rneugeba 
Hi, thanks for reply. I did as suggested on the link but not luck. The --ForceCleanup says completed but when I ran ./Debug-ContainerHost.ps1 again I still the same issue.

Basically, I just spin-up a new Azure VM from template Windows Server 2016 Datacenter with Docker Container so I assume networking should be working already.
Thanks.

**Comment by rneugeba** [comment] 2017-01-07 14:43
@marvinvperez I would suggest opening an issue on https://github.com/Microsoft/Virtualization-Documentation

**Comment by marvinvperez** [comment] 2017-01-07 14:45
@rneugeba , thanks! yeah will do.
