### ISSUE TITLE
[4.9.0] Container view is show empty.

### ISSUE THREAD

**Issue by chuoke** [docker/for-win#12765] opened 2022-06-09 03:03 UTC
Today I updated to the newest version which is:
```
Version: Docker Desktop 4.9.0 (80466) is currently the newest version available.
```

### Actual behavior

The default view after starting is Extensions Marketplace, but before is not.
When I switch to containers view, is empty like this:

![image](https://user-images.githubusercontent.com/17611457/172754514-72609c60-cabd-4c3e-a4c3-0e13c212c5ce.png)

I tried to quit and restart the docker-desktop, but did not recover.

And I find my container can be running normally, I think this is a UI bug.

### Expected behavior

show normally.

### Information

  - Windows Version: Windows 10 professional  21H1 19043.1706
  - Docker Desktop Version: 4.9.0 (80466) 
  - WSL2 or Hyper-V backend?  Use the WSL 2 based engine

**Comment by chef88val** [comment] 2022-06-09 07:17
Thanks to open this issue because i have the same problem
**JUST when click over cointainers options**. If i'm at Images, i can see the list of images
![image](https://user-images.githubusercontent.com/7094117/172787683-6fcff57d-f76c-4030-8a52-3bfd3ad90fb2.png)
![image](https://user-images.githubusercontent.com/7094117/172787695-3adc4322-7af1-45f0-9094-28b56f4bf8e6.png)
![image](https://user-images.githubusercontent.com/7094117/172787719-bc63d4f4-5a1b-4698-b56f-f82fe8048b13.png)

**Comment by nicks** [comment] 2022-06-09 11:30
Thanks for the report! I'm going to close this as a duplicate of https://github.com/docker/for-win/issues/12759 to centralize discussion.

**Closed by nicks** 2022-06-09 11:30 UTC
Labels: version/4.9.0
