### ISSUE TITLE
MobyLinux has aio-max-nr set by default to 65536 instead of 1048576

### ISSUE THREAD

**Issue by borgdrone7** [docker/for-win#92] opened 2016-09-19 22:28 UTC
### Expected behavior
Recommended value for aio-max-nr is 1048576

### Actual behavior
Actual default value is 65536

### Information
This is impossible to change from within container and apply it to all other containers (sysctl: setting key "fs.aio-max-nr": Read-only file system) because well, you know :). Problem arises when trying to run 5+ MySQL instances, MySQL fails because aio-max-nr is set too low by default (io_setup() failed with EAGAIN). As there is no way to access host MobyLinux (at least last time I checked, btw it is something I cannot comprehend) on Docker for Windows, there is no way to change this easily. Native AIO in mysql can be disabled altogether but I would rather not use hacks like that. Solution to all problems similar to this is to let us access and use MobyLinux host and do whatever we want with our virtual machine. Not sure if this is specific to Hyper-V + Docker for windows or am I missing something obvious but couldn't find solution anywhere else.
 
### Steps to reproduce the behavior
cat /proc/sys/fs/aio-max-nr

**Comment by justincormack** [comment] 2016-09-19 22:40
Hi, sorry about that. There is planned to be an interface to set the default `sysctl` values but it is not there yet. I have increased the default, and this should be in the next beta, which is currently scheduled for early next week.

**Comment by borgdrone7** [comment] 2016-09-19 22:57
Thanks, will wait for the next beta 👍. Also decision by the team to prevent us to access the host directly is very hard to grasp.

**Comment by justincormack** [comment] 2016-09-19 23:07
You can set the value temporarily with `docker run --privileged alpine sh -c 'echo 1048576 > /proc/sys/fs/aio-max-nr'` - this will last until the next restart. You can use the automatic restart features in Docker to set this to run always.

You can access the host directly, but we cannot support the product if you do so, and we do not document it, as the interfaces are subject to change.

**Comment by rneugeba** [comment] 2016-09-19 23:12
@borgdrone7 we are trying to strike a balance. Sensible default values, tight integration and ease of use works for a lot of people. If we provide a generic interface to things like sysctl, people can accidentally break things either quite badly or, worse, in a subtle way, making it quite hard to support. Please let us know if you have any suggestions.
Thanks
Rolf

**Comment by borgdrone7** [comment] 2016-09-19 23:37
Thanks @justincormack that fixes it until interface is done. 
@rneugeba, in my case I am testing locally on my Windows machine and production will be Linux anyway which I will have access to at the end of the day anyway. Generally I don't think anyone will run production code on Windows for docker as per se. For example even if I wanted to run it on Windows in production I would create bare Linux VM there, install docker and then run it from there instead of installing docker for Windows and be limited by one VM and other limitations imposed. So end result is that many people who are using docker on windows (as in Docker for Windows product) will sooner or later deploy it somewhere and then will have full access to host anyway. So I really don't see a point in making our dev and production environments different by disabling us from modifying host as we wish. 
As for support, if Docker for Windows cannot be supported because of "don't shoot yourself in the foot" policy then how can docker for Linux be supported? It is always installed on host on which 3rd party has access. Unless there is plan to completely disable installing docker even on Linux and offer it only as some standalone project I don't get it. Maybe Windows users are considered "less advanced" to use very nice term :). 
Btw how can I access the host on Windows?

**Comment by rneugeba** [comment] 2016-09-28 22:36
we shipped Beta27 today. so I'm closing this. please re-open if the issue is not resolved.
thanks for the report!

**Closed by rneugeba** 2016-09-28 22:36 UTC
Labels: fixed-in/beta27, kind/enhancement
