### ISSUE TITLE
Windows docker force input a password while change shared drives 

### ISSUE THREAD

**Issue by eromoe** [docker/for-win#545] opened 2017-03-02 01:36 UTC
My home computer doesn't have a password, so I can't set change shared drives.

![image](https://cloud.githubusercontent.com/assets/3938751/23462604/6f5f07ec-fec9-11e6-9729-3cec7f1f9f37.png)

**Comment by rneugeba** [comment] 2017-03-03 16:40
@eromoe Thanks for the report. This is a duplicate of #449, #366, #352 and we commented on there that we rely on Authenticated Samba mounts, so this won't fix.

**Closed by rneugeba** 2017-03-03 16:40 UTC
