### ISSUE TITLE
Volume mounting fails for MSSQL-Server Container after update to Docker Desktop 2.3.0.2.

### ISSUE THREAD

**Issue by AlphaRage** [docker/for-win#6660] opened 2020-05-12 17:00 UTC
### Expected behavior

The files inside my MSSQL-Server Docker Container should appear at the volume destination and the Container should start normally.

### Actual behavior

The Container logs always show errors for some of the files, leading to crashes and restarts until killed. Only some files are copied.

### Information

  - Is it reproducible? Yes.
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes.

  - Windows Version: Win 10 Pro, all updates
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Tested inside VM and native, both with same behavior.

### Steps to reproduce the behavior

  1. Install Docker Desktop 2.3.0.2 
  2. Run example command `docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>' -p 1453:1433 -v C:/Users/user/AppData/Roaming/DOCKERTEST/MSSQL/data:/var/opt/mssql/data -d mcr.microsoft.com/mssql/server:2017-latest`
 3. The Container will fail to copy the files and crash.

With Docker Desktop 2.2.0.5 it works just fine.

**Comment by martyt** [comment] 2020-05-12 19:53
Duplicate of #6656

**Comment by AlphaRage** [comment] 2020-05-12 19:57
Correct, it is the exact same issue. It's better explained in the duplicate though, I think.

**Comment by stephen-turner** [comment] 2020-05-13 07:55
Closing as dupe.

**Closed by stephen-turner** 2020-05-13 07:55 UTC
