### ISSUE TITLE
The "Stick to Bottom" option is broken, making logs impossible to read.

### ISSUE THREAD

**Issue by BrainSlugs83** [docker/for-win#10371] opened 2021-02-12 19:54 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BC56976D-645A-497A-A40D-2278AF595902/20210212193405

### Actual behavior
The logging window is completely non-functional, as it just grows in size and you can never see the latest log messages without manually scrolling.

Additionally, items that should remain docked (like the container options at the top or the search panel at the bottom) do not remain docked, and are not visible unless you scroll to them (meaning that the on/off slider at the bottom is basically inaccessible, and the container options at the top are gone if you're not looking at the very first page of logs).

I believe what's happening is that the parent UI control is growing in size instead of the log control -- and so the slider bar is happening at the wrong level of the UI control.  So the snap to bottom might be "working" but is essentially useless because it's not executed on the control where the sliding is actually happening.

### Expected behavior
- Docked UI controls remain docked -- regardless of scroll level (i.e. the top container options and bottom search panel should remain stationary, and not scroll off the top or bottom of the window).

- The "Stick to Bottom" option is honored, so that when it's on, we can see the latest logs without having to constantly scroll down manually.

### Information

  - Windows Version: Windows 10 Pro (2004 / 19041.804)
  - Docker Desktop Version: 3.1.0 (51484)
  - WSL2 or Hyper-V backend?  This is a UI issue, but I believe I'm using Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, I'm using Docker Desktop on a desktop machine.

### Steps to reproduce the behavior

1. Run a containerized docker app that logs to the console every second or so, and just leave it running.
2. Notice that as it logs, that the "Stick to Bottom" slider has no effect (on or off is the same behavior), and that you have to manually scroll the window if you want to see the latest logs, in addition, the option itself slides off the bottom, so it makes it really hard to toggle it if you're doing lots of active logging.

**Comment by StefanScherer** [comment] 2021-02-13 09:10
Thanks for reporting. We're already on it and will have a fix in the next release.

**Comment by stephen-turner** [comment] 2021-02-15 10:29
Closing as dupe of #10160.

**Closed by stephen-turner** 2021-02-15 10:29 UTC
Labels: version/3.1.0
