### ISSUE TITLE
terminal in container garbles the text and gets wonky (powershell host, powershell in container)

### ISSUE THREAD

**Issue by cons0l3** [docker/for-win#198] opened 2016-11-03 11:21 UTC
when 
1) running `docker run --rm -it microsoft/windowsservercore powershell` in host powershell
2) in the container powershell repeat to execute `dir` until the bottom of the terminal window is reached
3) produce an error e.g. enter "ddddddd"

result: the screen contents is all messed up.

![image](https://cloud.githubusercontent.com/assets/1457252/19964086/0e55cb72-a1c0-11e6-9b81-acd68fa84533.png)

when
1) resizing the terminal window, the contents gets all messy.

expected:
the terminal to the container works like if it is a powershell on the host.

**Comment by rneugeba** [comment] 2016-11-03 17:28
I can't reproduce this with build 14393 with all updates installed as well as freshly pulled nanoserver and windows server core images.
It may also depend on your terminal settings, but I tried line wrapping and the output is not garbled when I resize.
![screen shot 2016-11-03 at 17 15 44](https://cloud.githubusercontent.com/assets/3338098/19977224/ce74571e-a1ea-11e6-86f2-7c9485ee466c.png)

**Comment by cons0l3** [comment] 2016-11-04 08:12
more screenshot of weirdness.

usually my powershell has a blue background, that gets all all black when garbling starts. resizing the window increases the probability of the garbling.

![image](https://cloud.githubusercontent.com/assets/1457252/19998399/e47ab1fc-a26c-11e6-8e5e-6bc2711f5ce5.png)

![image](https://cloud.githubusercontent.com/assets/1457252/19998703/8f0dceb4-a26e-11e6-94d5-4584c1723721.png)

In the second image I have drawn a blue circle around where the cursor currently awaits input. It basically jumped up and is now right in the middle of the previous output. Maybe a bug of powershell itself? (I have never before experienced it with powershell though)

I have an NVIDIA 580 graphics-card. 

[NVIDIA System Information 11-04-2016 09-03-27.txt](https://github.com/docker/for-win/files/570903/NVIDIA.System.Information.11-04-2016.09-03-27.txt)

The powershell is running in "normal" (*not* like `powershell -version 2.0`)

## PowerShell Version
```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## WinVer
Version 1607 (Build 14393.351)

## Docker Info
´´´
C:\Users\carst>docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 11.99 GiB
Name: BLAUBEERE10
ID: E2WR:C7YS:2BZ5:TNFX:NCJL:FZPY:6U6F:3MFC:CBX4:DJCP:LZFO:RZS3
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
´´´
## Docker Version
´´´
C:\Users\carst>docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
´´´

**Comment by rneugeba** [comment] 2016-11-04 10:38
One of my machines is on the same version as you:
```
PS C:\Users\docker> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
I also see the different background colour (see below) but I don't see the garbled text. Same on a recent insider build (5.1.14955.1000).

@jhowardmsft any idea what could cause this?


![screen shot 2016-11-04 at 10 25 36](https://cloud.githubusercontent.com/assets/3338098/20002617/a0f7d4ca-a279-11e6-9816-b5ab81f12128.png)

**Comment by rneugeba** [comment] 2016-11-25 10:21
I'm closing this issue as we can only part reproduce it and because it's not an issue with the Docker for Windows application itself, but seems to be an issue in the windows terminal emulation. If the issue is still there, you could try filing an issue here: https://github.com/Microsoft/Virtualization-Documentation/issues

**Closed by rneugeba** 2016-11-25 10:21 UTC
Labels: area/wincon, status/0-more-info-needed

**Comment by masaeedu** [comment] 2017-09-20 03:09
@rn Are you still interested in repro-ing this? I have a console application that deletes and rewrites lines to show progress, and the terminal output consistently becomes totally garbled in interactive mode.
