### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by kec2** [docker/for-win#3942] opened 2019-05-21 14:13 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4BB10EA0-15E1-4C32-AF40-9151C46AC4A9/20190521154617

### Expected behavior
Docker starts without error

### Actual behavior
Docker failed to start

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 4F46DD10-E322-4E66-A597-CEED1FC4FC0D)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 4F46DD10-E322-4E66-A597-CEED1FC4FC0D).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 10 inside a VMWare
  - Docker for Windows Version: 
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Double click the desktop shoutcut.
  3. Error message box is presented.

**Comment by joesixpack** [comment] 2019-05-26 18:32
See #1221

**Comment by mikeparker** [comment] 2019-05-30 14:35
Duplicate of https://github.com/docker/for-win/issues/1221
* Your Hyper-V configuration is broken. This may be caused by a windows update.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 14:35 UTC

**Comment by joesixpack** [comment] 2019-05-30 19:38
That fix doesn't work, BTW.
