### ISSUE TITLE
403 Error Codes for random css, images and js files on load, Pages of Web Application not loading properly after Docker for Windows Update.

### ISSUE THREAD

**Issue by mantaBracket** [docker/for-win#5876] opened 2020-02-25 14:57 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0B8565F9-6A68-4E66-A4D9-737AA020E2C9/20200225144738

### Expected behavior

Pages loading correctly every page load.

### Actual behavior

Every few page loads random css, js or pictures are not loaded and it throws an 403 error in the browser console. This started occurring with existing setups after the update.

### Information

Since updating to the new Docker Version 2.2.0.3 (Build 42716), every 2nd-4th load, random css styling, images and js scripts are missing. When checking the browser console the errors for the inaccessible files read net::ERR_ABORTED 403 (Forbidden) and 403 Forbidden. The Files that are missing change around every incorrect page load.

  - Windows Version: 1809
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Not possible remotely.

**Comment by stephen-turner** [comment] 2020-02-25 14:59
Closing as a dupe of #5793

**Closed by stephen-turner** 2020-02-25 14:59 UTC
