### ISSUE TITLE
I'm not able to start docker using linux container in Windows machine

### ISSUE THREAD

**Issue by olcavi** [docker/for-win#3936] opened 2019-05-20 16:56 UTC
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 5C43E907-2EE1-424F-9982-7F2EB7E78630/20190520182115

### Expected behavior
  Docker run without Error.
   I already use docker on my machine but since a windows update, it doesn't start. 
### Actual behavior
   Error when docker start:
à <ScriptBlock>, <Aucun fichier> : ligne 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 10 pro
  - Docker for Windows Version: 2.0.0.3

### Steps to reproduce the behavior

  1.  only start docker

**Comment by olcavi** [comment] 2019-05-20 16:58
[log.txt](https://github.com/docker/for-win/files/3198945/log.txt)

**Comment by olcavi** [comment] 2019-05-20 17:00
I tried to run the following command in a cmd window: 
MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
but it doesn't work. I read that you have to run this command on the Hyper-V host, but I don't know how to do....

**Comment by mikeparker** [comment] 2019-05-30 14:38
Duplicate of https://github.com/docker/for-win/issues/1221
* Your Hyper-V configuration is broken. This may be caused by a windows update.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 14:38 UTC
