### ISSUE TITLE
Persistent container data at first not present after VM restart

### ISSUE THREAD

**Issue by imgdat** [docker/for-win#218] opened 2016-11-11 08:34 UTC
### Expected behavior
After exiting Docker then running it again containers should have their persistent data.

### Actual behavior
After exiting Docker then running it again containers have data set to their image defaults. However restarting the containers then has the persistent data.

### Information
  - Diagnostic ID: 0FAD67F1-D5B0-4EC2-9342-7D8A139E2736/2016-11-10_23-40-19

docker-compose.yml:
```
version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - "./.data/wp:/var/www/html"
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
```
Same as https://docs.docker.com/compose/wordpress/ with volume added for wordpress container.

Docker Version 1.12.3 (8488) Stable
Windows 10 Pro Version 1607 OS Build 14393.447

### Steps to reproduce the behavior
  1. docker-compose up -d with above yaml file
  2. Go to http://localhost:8000 and complete WP install
  3. Exit Docker.
  4. Run Docker.
  5. Go to http://localhost:8000 but now the install is asked for again (don't complete it)
  6. Restart mysql and wordpress containers
  7. Go to http://localhost:8000 and now WP loads normally

I'm new to Docker so maybe there's something I'm missing about volumes or data persistence. Also this only happens with "restart: always" and starting the containers manually does have the persistent data.

**Comment by dgageot** [comment] 2016-12-03 14:16
Hi @imgdat, I believe this is a duplicate of https://github.com/docker/for-win/issues/71. Can you confirm?

**Comment by imgdat** [comment] 2016-12-03 18:56
@dgageot Yes it's a duplicate.

**Comment by dgageot** [comment] 2016-12-03 19:13
@imgdat Thanks a lot! Closing as a duplicate of #71 then

**Closed by dgageot** 2016-12-03 19:13 UTC
Labels: area/compose, status/0-more-info-needed
