### ISSUE TITLE
Docker for windows not prompting user selection when sharing c drive

### ISSUE THREAD

**Issue by maarten-wachters** [docker/for-win#5653] opened 2020-01-30 18:51 UTC
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker prompts me to enter a user name and password and shares the drive

### Actual behavior
without restarting the checkbox is ticked, and the drive is shared under an azureAd account
### Information

  - Windows Version: 10.0.18363 build 18363 
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Boot up docker
  2. Go to shared files and select the drive to share

**Comment by mat007** [comment] 2020-01-31 05:25
I believe this is a duplicate of #5567

**Closed by mat007** 2020-01-31 05:25 UTC
