### ISSUE TITLE
Docker does not start on Windows 10

### ISSUE THREAD

**Issue by seyedsepehr** [docker/for-win#1338] opened 2017-11-19 08:57 UTC
### Expected behavior
After installation, docker must be able to start
### Actual behavior
Docker throws error on startup and fails to start.
### Information

[NamedPipeClient][Error  ] Unable to send Start: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

When trying to start or create VM using docker-machine, following error:

PS C:\WINDOWS\system32> docker-machine create --driver "hyperv" default
dial-http tcp 127.0.0.1:30896: read tcp 127.0.0.1:30897->127.0.0.1:30896: wsarecv: An existing connection was forcibly closed by the remote host.

PS C:\WINDOWS\system32> docker-machine start default
Host does not exist: "default"

winver
Windows 10
Version 1607 (OS Build 14393.1884)

PS C:\WINDOWS\system32> docker-machine --version
docker-machine.exe version 0.12.2, build 9371605

Hyper-v is installed and other VMs are running on it.

### Steps to reproduce the behavior

  1. Install docker on Windows 10
  2. Try to start docker

**Comment by jsappme** [comment] 2017-11-19 16:44
```
Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/11/19 10:38:31.485
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Home
Edition: Core
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\herve\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:38:31.593][GUI            ][Info   ] Starting...
[10:38:33.362][Tracking       ][Info   ] Crash report and usage statistics are enabled
[10:38:33.365][SegmentApi     ][Info   ] Usage statistic: appLaunched
[10:38:34.470][NPS            ][Info   ] NPS User id created
[10:38:36.614][NPS            ][Info   ] NPS user ceated on :11/19/2017 8:38:33 AM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[10:38:36.614][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:38:36.616][SegmentApi     ][Info   ] Usage statistic: Identify
[10:38:36.693][Notifications  ][Info   ] Docker is starting...
[10:38:36.729][NamedPipeClient][Info   ] Sending Version()...
[10:38:36.742][NamedPipeClient][Info   ] Received response for Version
[10:38:36.743][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[10:29:45.247][BackendServer  ][Info   ] Started
[10:38:36.740][NamedPipeServer][Info   ] Version()
[10:38:36.741][NamedPipeServer][Info   ] Version done in 00:00:00.0004974.
[10:38:36.744][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[10:38:36.749][PowerMode      ][Info   ] Stop
[10:38:36.751][HyperV         ][Info   ] Stop
[10:38:36.758][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[10:38:36.760][PowerShell     ][Info   ] Creating a Runspace Pool...
[10:38:36.906][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[10:38:37.026][HyperV         ][Info   ] Script started at 10:38:37.020
[10:38:37.036][Moby           ][Info   ] Stop
[10:38:37.043][Linux          ][Error  ] Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79. Let's retry
[10:38:37.046][PowerShell     ][Info   ] Run script...
[10:38:38.441][PowerMode      ][Info   ] Stop
[10:38:38.441][HyperV         ][Info   ] Stop
[10:38:38.441][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[10:38:38.460][HyperV         ][Info   ] Script started at 10:38:38.460
[10:38:38.462][Moby           ][Info   ] Stop
[10:38:38.473][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[10:38:38.513][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
[10:38:38.514][Notifications  ][Error  ] Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
```

**Comment by cwdobbins** [comment] 2017-11-20 01:22
Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by cwdobbins** [comment] 2017-11-20 01:28
Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/11/19 20:28:07.545
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Home
Edition: Core
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\Christopher Dobbins\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:28:07.630][GUI            ][Info   ] Starting...
[20:28:08.262][Tracking       ][Info   ] Crash report and usage statistics are enabled
[20:28:08.262][SegmentApi     ][Info   ] Usage statistic: appLaunched
[20:28:08.862][NPS            ][Info   ] NPS user ceated on :11/17/2017 7:06:06 PM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[20:28:08.862][SegmentApi     ][Info   ] Usage statistic: heartbeat
[20:28:08.862][SegmentApi     ][Info   ] Usage statistic: Identify
[20:28:08.946][Notifications  ][Info   ] Docker is starting...
[20:28:08.997][NamedPipeClient][Info   ] Sending Version()...
[20:28:09.000][NamedPipeClient][Info   ] Received response for Version
[20:28:09.000][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[20:26:13.156][BackendServer  ][Info   ] Started
[20:28:09.000][NamedPipeServer][Info   ] Version()
[20:28:09.000][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:28:09.015][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[20:28:09.015][PowerMode      ][Info   ] Stop
[20:28:09.015][HyperV         ][Info   ] Stop
[20:28:09.031][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:28:09.031][PowerShell     ][Info   ] Creating a Runspace Pool...
[20:28:09.742][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[20:28:10.414][HyperV         ][Info   ] Script started at 20:28:10.353
[20:28:10.497][Moby           ][Info   ] Stop
[20:28:10.506][Linux          ][Error  ] Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79. Let's retry
[20:28:10.509][PowerShell     ][Info   ] Run script...
[20:28:12.057][PowerMode      ][Info   ] Stop
[20:28:12.057][HyperV         ][Info   ] Stop
[20:28:12.057][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:28:12.072][HyperV         ][Info   ] Script started at 20:28:12.072
[20:28:12.088][Moby           ][Info   ] Stop
[20:28:12.088][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[20:28:12.367][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
[20:28:12.368][Notifications  ][Error  ] Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
[20:28:20.890][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[20:28:20.893][NamedPipeClient][Info   ] Sending Version()...
[20:28:20.893][NamedPipeClient][Info   ] Sending Version()...
[20:28:20.894][NamedPipeClient][Info   ] Sending Version()...
[20:28:20.895][NamedPipeClient][Info   ] Sending Version()...
[20:28:20.896][NamedPipeClient][Info   ] Received response for Version
[20:28:20.896][NamedPipeClient][Info   ] Received response for Version
[20:28:20.896][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\Christopher Dobbins\AppData\Roaming\Docker\features-overrides.json'.
[20:28:20.896][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[20:28:20.896][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\mobyLogs.tar)...
[20:28:20.896][NamedPipeClient][Info   ] Received response for Version
[20:28:20.896][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\pcap.tar)...
[20:28:20.896][NamedPipeClient][Info   ] Received response for Version
[20:28:20.896][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\win_containers)...
[20:28:20.896][NamedPipeServer][Info   ] Version()
[20:28:20.912][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[20:28:20.896][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:28:20.896][NamedPipeServer][Info   ] Version()
[20:28:20.896][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:28:20.896][NamedPipeServer][Info   ] Version()
[20:28:20.896][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:28:20.896][NamedPipeServer][Info   ] GetDebugInfo()
[20:28:20.896][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\mobyLogs.tar)
[20:28:20.896][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\pcap.tar)
[20:28:20.896][NamedPipeServer][Info   ] Version()
[20:28:20.896][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:28:20.896][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Christopher Dobbins\AppData\Local\Temp\2m2cnmrl.oik\win_containers)
[20:28:20.912][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[20:28:20.912][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0156310.
[20:28:20.927][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[20:28:20.959][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[20:28:20.959][HyperV         ][Warning] Unable to download logs: The term 'Hyper-V\Get-VM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[20:28:20.959][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0625168.
[20:28:24.850][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[20:28:24.850][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:03.9536510.
[20:28:29.200][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:08.3034046.
[20:28:29.200][NamedPipeClient][Info   ] Received response for GetDebugInfo
[20:28:29.322][CrashReport    ][Info   ] Uploading diagnostics...
[20:28:30.623][CrashReport    ][Info   ] Diagnostics successfully uploaded (2023BBE2-2F84-407F-9D46-F1646A0BF303/2017-11-19_20-28-20)
[20:28:30.639][GUI            ][Info   ] Sending Bugsnag report 41b591fc-5cb1-42c0-8b7b-a99a84f0095a...
[20:28:31.140][GUI            ][Info   ] Bugsnag report 41b591fc-5cb1-42c0-8b7b-a99a84f0095a sent
[20:28:31.440][ErrorReportWindow][Info   ] Open logs

**Comment by garethterrace** [comment] 2017-11-20 11:02
I think this is because you're using Windows 10 Home.  Docker requires Hyper-V which is only available in Pro and upwards:

- https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install 
- https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements

**Comment by seyedsepehr** [comment] 2017-11-20 20:55
No. I'm using Windows 10 Enterprise. Hyper-V is installed and I have a number of VMs created and running in Hyper-V. However, docker-machine or anything related to that does not exist in Hyper-V, which I suppose has to be created as part of installing docker. Even docker-machine create command doesn't work.

Exception 0xc000001d 0xffffc90a5dce8800 0xffffc90a5dce8800 0x18000b8bc
PC=0x18000b8bc

syscall.Syscall(0x7ffc82ffdc40, 0x2, 0x238, 0x3, 0x0, 0x0, 0x0, 0x318)
	/usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x238, 0x303, 0x0, 0xffffffff)
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:114 +0x6f
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.makeWin32File(0x238, 0xc0420a58f0, 0x0, 0x0)
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:102 +0xb7
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.DialPipe(0xc04225b568, 0x16, 0xc0420a59b8, 0x0, 0x17d0920, 0xc04244a112, 0xc0420a5a30)
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/pipe.go:187 +0x51a
github.com/docker/cli/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc04225b568, 0x16, 0x773594000, 0x41081c, 0x149f2d0, 0xc0420a5a58, 0x0)
	/go/src/github.com/docker/cli/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/cli/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xf0875f, 0x3, 0xc04243bd60, 0x19, 0xc0420a5a58, 0x149f2d0, 0xc0420a5a60, 0x6baac4)
	/go/src/github.com/docker/cli/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0421ca870, 0x14168c0, 0xc0420401a8, 0xf0875f, 0x3, 0xc04243bd60, 0x19, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:852 +0x82
net/http.(*Transport).dialConn(0xc0421ca870, 0x14168c0, 0xc0420401a8, 0x0, 0xf08f84, 0x4, 0xc04243bd60, 0x19, 0x5c0a2c, 0x1, ...)
	/usr/local/go/src/net/http/transport.go:1008 +0x1c53
net/http.(*Transport).getConn.func4(0xc0421ca870, 0x14168c0, 0xc0420401a8, 0xc0424463c0, 0xc0424408a0)
	/usr/local/go/src/net/http/transport.go:908 +0x7f
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:910 +0x3aa

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc0421ca870, 0xc04243bd40, 0x0, 0xf08f84, 0x4, 0xc04243bd60, 0x19, 0x0, 0x0, 0x300000002)
	/usr/local/go/src/net/http/transport.go:913 +0xb99
net/http.(*Transport).RoundTrip(0xc0421ca870, 0xc0422e5b00, 0xc0421ca870, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:378 +0x593
net/http.send(0xc0422e5b00, 0x14073c0, 0xc0421ca870, 0x0, 0xc000000000, 0x0, 0x0, 0x8, 0xc042004598, 0x40fcaf)
	/usr/local/go/src/net/http/client.go:249 +0x169
net/http.(*Client).send(0xc042446300, 0xc0422e5b00, 0x0, 0x0, 0x0, 0xc042004598, 0x0, 0x1, 0x10)
	/usr/local/go/src/net/http/client.go:173 +0x10f
net/http.(*Client).Do(0xc042446300, 0xc0422e5b00, 0xc0420401a8, 0xc0422e5b00, 0xc0420401a8)
	/usr/local/go/src/net/http/client.go:595 +0x25b
github.com/docker/cli/vendor/golang.org/x/net/context/ctxhttp.Do(0x2560000, 0xc0420401a8, 0xc042446300, 0xc0422e5a00, 0xc04242df50, 0xc0424267e0, 0xc0424267e0)
	/go/src/github.com/docker/cli/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:30 +0x99
github.com/docker/cli/vendor/github.com/docker/docker/client.(*Client).doRequest(0xc042384a00, 0x2560000, 0xc0420401a8, 0xc0422e5a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/vendor/github.com/docker/docker/client/request.go:135 +0x102
github.com/docker/cli/vendor/github.com/docker/docker/client.(*Client).Ping(0xc042384a00, 0x2560000, 0xc0420401a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/cli/vendor/github.com/docker/docker/client/ping.go:17 +0x1bc
github.com/docker/cli/cli/command.(*DockerCli).Initialize(0xc0421fd5c0, 0xc042354fa0, 0x2, 0x149f2d0)
	/go/src/github.com/docker/cli/cli/command/cli.go:139 +0x1a2
main.newDockerCommand.func2(0xc042438d80, 0x149f2d0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:49 +0xdd
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc042438d80, 0xc0420463f0, 0x0, 0x0, 0xc042438d80, 0xc0420463f0)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:628 +0x573
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042396480, 0xc042396900, 0xc0423673c0, 0xc042004450)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:742 +0x350
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042396480, 0xc042396480, 0x1407980)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:168 +0xe0

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x10b
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 33 [syscall, locked to thread]:
syscall.Syscall6(0x7ffc82ff6bf0, 0x5, 0x318, 0xc0420a3f9c, 0xc0420a3fa0, 0xc0420a3fa8, 0xffffffff, 0x0, 0x7ffc7eab3040, 0x1, ...)
	/usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x318, 0xc0420a3f9c, 0xc0420a3fa0, 0xc0420a3fa8, 0xffffffff, 0xc0420a3fc0, 0x5c0a2c)
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:102 +0xc6
github.com/docker/cli/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x318)
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:154 +0x82
created by github.com/docker/cli/vendor/github.com/Microsoft/go-winio.initIo
	/go/src/github.com/docker/cli/vendor/github.com/Microsoft/go-winio/file.go:73 +0x87
rax     0x0
rbx     0xc04202cf68
rcx     0x238
rdi     0x276000
rsi     0xc0420a5800
rbp     0xc0420a57b0
rsp     0x255fd98
r8      0x0
r9      0x1
r10     0x238
r11     0x18d7610
r12     0x0
r13     0x4
r14     0x0
r15     0xd3
rip     0x18000b8bc
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 200
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 78
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by seyedsepehr** [comment] 2017-11-20 20:56
Notice that I have got the same issue on two separate Windows 10 machines. Basically it never worked for me.

**Comment by cwdobbins** [comment] 2017-11-21 01:15
This is not specific to Windows 10 Home-  I upgraded to Windows 10 Pro and have the same issue with the latest distro:

Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/11/20 20:15:14.057
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\Christopher Dobbins\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:15:14.150][GUI            ][Info   ] Starting...
[20:15:14.662][Tracking       ][Info   ] Crash report and usage statistics are enabled
[20:15:14.662][SegmentApi     ][Info   ] Usage statistic: appLaunched
[20:15:15.334][NPS            ][Info   ] NPS user ceated on :11/17/2017 7:06:06 PM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[20:15:15.334][SegmentApi     ][Info   ] Usage statistic: heartbeat
[20:15:15.334][SegmentApi     ][Info   ] Usage statistic: Identify
[20:15:15.397][Notifications  ][Info   ] Docker is starting...
[20:15:15.428][NamedPipeClient][Info   ] Sending Version()...
[20:15:15.444][NamedPipeClient][Info   ] Received response for Version
[20:15:15.444][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[20:15:01.159][BackendServer  ][Info   ] Started
[20:15:15.444][NamedPipeServer][Info   ] Version()
[20:15:15.444][NamedPipeServer][Info   ] Version done in 00:00:00.
[20:15:15.459][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[20:15:15.459][PowerMode      ][Info   ] Stop
[20:15:15.459][HyperV         ][Info   ] Stop
[20:15:15.459][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:15:15.475][PowerShell     ][Info   ] Creating a Runspace Pool...
[20:15:15.569][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[20:15:15.647][HyperV         ][Info   ] Script started at 20:15:15.631
[20:15:15.662][Moby           ][Info   ] Stop
[20:15:15.662][Linux          ][Error  ] Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79. Let's retry
[20:15:15.662][PowerShell     ][Info   ] Run script...
[20:15:17.242][PowerMode      ][Info   ] Stop
[20:15:17.242][HyperV         ][Info   ] Stop
[20:15:17.242][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:15:17.247][HyperV         ][Info   ] Script started at 20:15:17.247
[20:15:17.254][Moby           ][Info   ] Stop
[20:15:17.261][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[20:15:17.293][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
[20:15:17.295][Notifications  ][Error  ] Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79

**Comment by jedmao** [comment] 2017-11-25 00:42
Similar issue here. Tried both stable and edge versions. I'm running Windows 10 Pro with Hyper-V installed and virtualization running. Also, the daemon is running. Restarting the daemon doesn't fix this issue.
```
PS C:\WINDOWS\system32> docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:30:11 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.34/version: open 
//./pipe/docker_engine: The system cannot find the file specified. In the default daemon
configuration on Windows, the docker client must be run elevated to connect. This error
may also indicate that the docker daemon is not running.
```
![image](https://user-images.githubusercontent.com/1058243/33225949-cb1de556-d13e-11e7-9500-8d39a69bb6fa.png)
![image](https://user-images.githubusercontent.com/1058243/33225945-bdf0254c-d13e-11e7-82ea-36dd42ee0079.png)

**Comment by labradore** [comment] 2017-12-19 20:12
I had the same problem.  Running on Windows 10 Pro Version 1709 Build 16299.125
Fixed by:
1. `docker-machine create --driver hyperv vm`
2. Wait for step one to complete.  It took about 5 minutes on a fast machine with SSD and 32GB ram.
2. Kill process "Docker for Windows.exe" (because it was unresponsive)
3. Restart "Docker for Windows"

I'm not that familiar with Docker, but it appears that you need a VM running called MobyLinuxVM.  The command above builds it and for some reason fails silently during the normal install or 1st start-up.

I've experienced other silent failures as well; had a tough time installing DfW on a fresh Windows 2016 server and have been unable to install at all on a windows 7 machine (trying to use with Virtualbox as the VM driver), the installer just silently crashes.  I suspect that the developers need to take a good look at default behaviors for the installers and start alerting users to errors rather than letting them just get dumped in logs.

**Comment by rn** [comment] 2018-03-20 11:45
@seyedsepehr Tour exception looks identical to https://github.com/docker/for-win/issues/140 and subsequently https://github.com/moby/moby/issues/27423. The root cause was Lavasoft Web Companion.

I'm closing this issue (it's also quite old) but if you still have the same issue after disabling any AV, please let us know.

**Closed by rn** 2018-03-20 11:45 UTC

**Comment by fcarpentier** [comment] 2020-03-30 09:33
On Windows 10 pro (version 18363), i had the same problem resolved by installing Docker with "Run as administrator"

**Comment by tuf22191** [comment] 2020-05-21 03:22
I hate windows!

**Comment by ningacoding** [comment] 2020-06-11 22:10
Problem exists in latest version.
