### ISSUE TITLE
Windows 11 WSL Docker fails to shutdown which causes Windows shutdown to fail

### ISSUE THREAD

**Issue by Taskle** [docker/for-win#13760] opened 2023-10-26 02:19 UTC
### Description

Starting about a month ago, on Windows 11 with the latest version of Docker WSL fails to shut down when terminated. This is most noticeable because shutting down the machine entirely fails due to this. Uninstalling Docker fixes the problem, and reinstalling Docker causes the problem to return.

### Reproduce

On a Windows 11 machine:
1. Uninstall Docker entirely.
2. Shut down and observe the computer shuts down fine.
3. Install the latest Docker Windows.
4. Shut down the computer and observe that it fails to shut down, citing Docker not terminating.
5. Log back into the machine and try to start Docker. Observe the "Docker failed to initialize" dialog (with body text, "Docker Desktop is shutting down.")

Docker must be hard-terminated from the Task Manager for it to be restartable.

### Expected behavior

Shutting down windows will shut down successfully as Docker will shut down successfully.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe


Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 39
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 31.29GiB
 Name: docker-desktop
 ID: e08e4ade-134d-4c4f-87f1-0f52b4dee02e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

D2180E54-5215-4BAF-8D55-EE5982729664/20231026021728

### Additional Info

I hypothesized that antivirus could have something to do with it so I uninstalled it completely, but the issue persists. For context, I've spent several hours trying to find a solution, but I hypothesize that it affects a subset of users. I don't have any unusual software or other unique plugins installed; my OS is pretty clean.

**Comment by bsousaa** [comment] 2023-10-26 10:21
Is this a duplicate of https://github.com/docker/for-win/issues/13697?

**Comment by Taskle** [comment] 2023-10-26 15:45
Ah, yes it is (I looked hard but didn't find it as my experience isn't that it crashes, per se, but that it hangs). But the description in the comments and the image at the top is exactly what I'm seeing so I believe it is a duplicate, yes.

**Comment by bsousaa** [comment] 2023-10-27 08:46
ok, closing in favour of #13697 then to keep the conversation in one single place.

**Closed as not planned by bsousaa** 2023-10-27 08:46 UTC
Labels: status/triage, status/duplicate, version/4.24.2
