### ISSUE TITLE
Win 10: Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

### ISSUE THREAD

**Issue by Ltek** [docker/for-win#462] opened 2017-02-03 05:21 UTC
### Expected behavior
Docker does not error when starting

### Actual behavior
Docker is fubar'd and will not run not matter what I try

Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoDestroy(Boolean keepVolume)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information
Diagnostic ID : 41D0C09E-1985-40D1-9DF6-8A3623AB67EA/2017-02-02_22-13-47

Tried... uninstall docker, ran 2 different system cleaners, multiple times. Deleted all VMs (in Hyper-V manager and in the file system), deleted all virtual switches, and rebooted clean... nothing works. I have tried doing this 3 times now.

### Steps to reproduce the behavior
install stable or latest beta, make no difference... Docker must be broken on Win 10 pro!?

**Comment by dgageot** [comment] 2017-02-03 07:52
Duplicate of #436

**Closed by dgageot** 2017-02-03 07:52 UTC
