### ISSUE TITLE
Unable to start docker daemon after upgrade to 2.1.0.0

### ISSUE THREAD

**Issue by ilnar20** [docker/for-win#4359] opened 2019-08-01 06:11 UTC
- [x] I have uploaded Diagnostics
  - Diagnostics ID: 24BF0F5B-E6D8-4471-8287-112879E0287E/20190801054855

### Expected behavior
After upgrade docker daemon starts without any problems

### Actual behavior

Docker throws error on startup and fails to start.

![55](https://user-images.githubusercontent.com/32128096/62269017-74ab5880-b43a-11e9-8e68-6420a8d02367.PNG)

### Information

  - Windows Version: 10 Pro N 1903
  - Docker Desktop Version: 2.1.0.0

daemon.json content is as follows:
` {
  "registry-mirrors": [],
  "debug": true,
  "experimental": true,
  "data-root": "d:\\docker"
} `

### Steps to reproduce the behavior

  1. Upgrade Docker Desktop to version 2.1.0.0
  2. Start Docker Desktop

**Comment by ilnar20** [comment] 2019-08-01 06:21
After reseting to factory defaults the error has gone

**Comment by Dale4** [comment] 2019-08-01 13:33
I upgraded and have the same issue.

**Comment by zappy-shu** [comment] 2019-08-02 15:05
Hi, , this appears to be a duplicate of https://github.com/docker/for-win/issues/3375 so i'm closing, but we are fixing the root cause. Please see https://github.com/docker/for-win/issues/3375#issuecomment-515808417 for a workaround.

**Closed by zappy-shu** 2019-08-02 15:05 UTC

**Comment by simonmatt** [comment] 2020-05-28 13:53
If you're using `Linux Container` of Docker Desktop, please quit your Docker, then comment or remove the option **data-root** in your `daemon.json`, and then start your Docker Desktop.
Because the option `data-root: D:\docker\images` can only work under **Windows Container**, you can also update `data-root: D:\docker` to `/var/local/docker` that is recognized by **Linux**
