### ISSUE TITLE
In the case of WSL 2, this is managed by Windows not us. But our documentation points to this page from Microsoft: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk

### ISSUE THREAD

**Issue by ms-vamp** [docker/for-win#13028] opened 2022-10-23 18:31 UTC
In the case of WSL 2, this is managed by Windows not us. But our documentation points to this page from Microsoft: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk

_Originally posted by @stephen-turner in https://github.com/docker/for-win/issues/9672#issuecomment-737153587_

this thread was buried but held the only solution to my problem. please update the link you referenced to this one https://learn.microsoft.com/en-us/windows/wsl/vhd-size

**Comment by nicks** [comment] 2022-10-24 04:06
Looks like this issue was opened by accident and was intended as a comment. Closing...

**Closed by nicks** 2022-10-24 04:06 UTC

**Comment by ms-vamp** [comment] 2022-10-24 13:43
it was intentional. the original thread does not allow new comments. only asking that the link be updated to the new microsoft link so others in the future can find the solution.

also, if you dont mind, i am curious if you can expand on which distro needs to have its partition / VHD expanded:

- host distro (ubuntu example in thread)
- docker-desktop
- docker-desktop-data

 it is unclear in that thread but would be very helpful to add in the windows FAQs for anyone else running into this issue. my situation was similar to OP where i had containers operating on large files mounted from the host distro and despite having ample space on disk the 251G limit was hit.
