### ISSUE TITLE
Docker Desktop is unable to detect a Hypervisor. Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

### ISSUE THREAD

**Issue by Kanishkasingla** [docker/for-win#13590] opened 2023-07-08 12:00 UTC
### Description

Docker Desktop is unable to detect a Hypervisor. Hardware assisted virtualization and data execution protection must be enabled in the BIOS.

### Reproduce

try running docker

### docker version

```bash
4.21.1
```

### docker info

```bash
info
```

### Diagnostics ID

6021B1F9-EA4A-4552-8BBC-E52372B406B7/20230708113851

**Comment by Priyanshu88** [comment] 2023-07-09 14:08
I am also facing Same error and below pops-up. I tried stackoverflow solutions but issue did not resolve and do not have options of Hyper -V components in my windows features on or off. I am using Windows 11 Home currently.
![image](https://github.com/docker/for-win/assets/86107841/563e4f1d-2799-416c-bb25-9aec4d3ce739)

**Comment by lorenrh** [comment] 2023-07-10 09:37
seems like a duplicate of https://github.com/docker/for-win/issues/13575

**Closed as completed** 2023-07-10 09:37 UTC
Labels: needs-triage

**Comment by Priyanshu88** [comment] 2023-07-10 13:58
Issue https://github.com/docker/for-win/issues/13575 is not solved yet.

**Comment by Priyanshu88** [comment] 2023-07-15 09:28
Hey @Kanishkasingla, Try the approach which I mentioned here: https://github.com/docker/for-win/issues/13575#issuecomment-1636668544
