### ISSUE TITLE
long time to start

### ISSUE THREAD

**Issue by kamkie** [docker/for-win#283] opened 2016-12-03 23:20 UTC
### Expected behavior
docker for windows is ready in 1 minute

### Actual behavior
docker for windows is ready after hour

### Information

  - Diagnostic ID 27CA4E77-3441-4D83-9240-B52F69F2EF03/2016-12-03_20-29-11
  - windows 10 insider preview 14971
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. start docker for windows

**Comment by sitex** [comment] 2016-12-04 06:50
Same problem is here.
Docker is taking a very long time to start.

### Expected behavior

docker for windows is ready after **_few seconds_** (as it said in a tool-tip)

### Actual behavior

docker for windows is ready after hour

### Information

- Diagnostic ID B28AE6BC-5E88-43F5-9C24-82D5F775D899/2016-12-04_14-49-38
- windows 10 pro. version 1607. build 14393.447

### Steps to reproduce the behavior

1. install docker for windows
2. start docker for windows

**Comment by rneugeba** [comment] 2016-12-04 15:33
@sitex looking at the Logs, your issue is completely different to @kamkie. Could you please open a separate issue? Your delay is caused here:
```
[14:30:33.843][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:30:34.239][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[14:45:18.003][Firewall       ][Info   ] Ports are opened
```
Thanks

**Comment by kamkie** [comment] 2016-12-04 15:44
i had this same situation on older version of docker for windows
`
[14:30:33.843][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:30:34.239][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[14:45:18.003][Firewall       ][Info   ] Ports are opened
`

**Comment by sitex** [comment] 2016-12-04 17:01
#286 Created @rneugeba

**Comment by rneugeba** [comment] 2016-12-06 10:25
@kamkie @sitex apologies. On closer inspection of the logs, it looks like you have the same issues. In both cases it seems to take a long time to open firewall ports. So, I'm closing this in favour of #286 which has more comments. Apologies for the confusion

**Closed by rneugeba** 2016-12-06 10:25 UTC
Labels: status/0-triage, version/beta31
