### ISSUE TITLE
Just updated docker and ALL my containers are gone!

### ISSUE THREAD

**Issue by b-hayes** [docker/for-win#9757] opened 2020-12-10 23:03 UTC
Just clicked update this morning and now I am going to have to spend all day rebuilding all my containers and setting up my dev environment.
😒
But first I have to stop docker itself from crashing before I can do anything.
😡

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A9921648-B713-4F74-8F3F-F67D175A8613/20201210224950
And here is the crash report upload id: A9921648-B713-4F74-8F3F-F67D175A8613/20201210225624

### Expected behavior
I run my scripts to start docker containers and see a bunch of green "done"s

### Actual behavior
`The command 'docker' could not be found in this WSL 2 distro.`
I then open docker on windows to see if it needs adding integrating with my WSL2 disto again and see that EVERYTHING IS GONE!
I restart docker and it crashes!
I am unable to do my job today. 👏👏👏

### Information

  - Windows Version: 10 PRO version 2004 build 19041.685
  - Docker Desktop Version: 3.0.0 I think? released today.
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
1. From a cold boot, when prompted say yes to updating docker.
2. Watch the dumpster fire burn all your containers 🤣😅😭
3. 🚪🚶‍♂️
4. 🤯🔫

Reinstalling docker from scratch seems or resetting to factory defaults will stop it crashing but then the very next time I boot all my containers are gone and its crashing again.

Every morning have to rebuild 20 containers from nothing.

### Steps used to resolve the problem
- cant.

**Comment by b-hayes** [comment] 2020-12-13 08:44
Rebooting my computer causees docker to destroy all my containers again. I cant use docker at all.

**Comment by b-hayes** [comment] 2020-12-15 21:06
See related issue: https://github.com/docker/for-win/issues/9784

**Comment by tiborvass** [comment] 2020-12-20 00:43
I verified your diagnostic ID, and it seems you are hitting #9755. Closing as dupe of #9755 which has a workaround at https://github.com/docker/for-win/issues/9755#issuecomment-748539590

**Closed by tiborvass** 2020-12-20 00:43 UTC
