### ISSUE TITLE
win11 版本 21H2， docekr desktop 启动报错 An unexpected error occurred. Restart Docker Desktop.

### ISSUE THREAD

**Issue by six1203** [docker/for-win#13519] opened 2023-05-31 16:03 UTC
dylan@dylan:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

C:\Users\Windows11>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2023-05-31T15:58:27.664164200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.vpnkit.exe is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[SKIP] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[WARN] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.32.1

Please note the following 1 warning:

1 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.32.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.vpnkit.exe is not running

Not all of the backend processes are running.

C:\Users\Windows11>wsl.exe -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2

**Comment by gjycn** [comment] 2023-05-31 16:26
I'm also having this issue with Windows 11 (22631.1825)

**Comment by ctalledo** [comment] 2023-05-31 19:02
Hi @six1203, please upload a [Docker Desktop diagnostics bundle](https://docs.docker.com/desktop/troubleshoot/overview/) as otherwise it's impossible for us to debug the issue.

Thanks.

**Comment by chenyRain** [comment] 2023-06-01 09:45
I'm also having this issue with Windows 11.

**Comment by six1203** [comment] 2023-06-01 14:46
>

**Comment by six1203** [comment] 2023-06-01 14:47
> Hi @six1203, please upload a [Docker Desktop diagnostics bundle](https://docs.docker.com/desktop/troubleshoot/overview/) as otherwise it's impossible for us to debug the issue.
> 
> Thanks.

This is the docker diagnostic id I have uploaded

7B07B43E-C797-4B34-964E-E4D4F1D8898D/202306011445187B07B43E-C797-4B34-964E-E4D4F1D8898D/20230601144518

**Comment by ctalledo** [comment] 2023-06-01 16:38
> 7B07B43E-C797-4B34-964E-E4D4F1D8898D/202306011445187B07B43E-C797-4B34-964E-E4D4F1D8898D/20230601144518

Small correction, should be: 7B07B43E-C797-4B34-964E-E4D4F1D8898D/20230601144518

**Comment by ctalledo** [comment] 2023-06-01 16:45
Thanks @six1203 for uploading the diagnostics bundle and apologies again for the issue.

The problem is caused by Docker Desktop failing to get the WSL version from the host; it's a duplicate of #13518. Please see [here](https://github.com/docker/for-win/issues/13518#issuecomment-1572373105) for an explanation.

Could you please provide the output of `wsl --version` on your host?

Thanks!

**Comment by ctalledo** [comment] 2023-06-01 16:45
Closing a duplicate of #13518. Let's track it there.

**Closed by ctalledo** 2023-06-01 16:45 UTC
Labels: status/triage, area/WSL2
