### ISSUE TITLE
Docker for Desktop 2.1.0.5 fails to install due to McAfee AutoRun Prevention

### ISSUE THREAD

**Issue by jischebeck** [docker/for-win#5179] opened 2019-11-19 20:49 UTC
### Expected behavior
Docker Desktop can be installed without issues.
### Actual behavior
Docker Desktop 2.1.0.5 fails to install. 

The error message explains, that a error due to a non authorized execution occurs.
The same error appears in the McAfee protocol.

### Information

The problem can be reproduced. 
  - Windows Version: Windows 10 - 201909
  - Docker Desktop Version: 2.1.0.5

**Error message Docker:**
```
Es wurde versucht, einen nicht autorisierten Vorgang auszuführen.
   bei Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   bei Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   bei CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   bei CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

**Error Message in McAfee Protocoll:**
```
18.11.2019 15:13:33   mfeesp(8560.11344) <SYSTEM> ApBl.AP.Activity: NT-AUTORITÄT\SYSTEM hat C:\Program Files\Docker\Docker\com.docker.service ausgeführt. Dieser Prozess hat versucht, auf HKCU\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\DOCKER DESKTOP zuzugreifen, hat damit die Regel "Registrieren von Programmen für Autorun" verletzt und wurde daher blockiert. In KB85494 wird erläutert, wie Sie auf dieses Ereignis reagieren können.
```

**Comment by caneiro** [comment] 2020-02-13 17:07
Same problem over here.

**Comment by mat007** [comment] 2020-02-13 17:14
Thanks for the report, closing as a duplicate of #5087

**Closed by mat007** 2020-02-13 17:14 UTC
