### ISSUE TITLE
Docker Desktop 4.21.0 does not embed the k8s version as claimed in release notes 

### ISSUE THREAD

**Issue by paulchambers** [docker/for-win#13578] opened 2023-07-03 11:46 UTC
### Description

Same issue as #13457, the release notes claim that 4.21.0 bundles kubernetes 1.27.2 but it uses 1.25.9

### Reproduce

install docker desktop and enable kubernetes
run kubectl version

output: Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

### Expected behavior

kubernetes server version should match version in release notes

### docker version

```bash
Server: Docker Desktop 4.21.0 (113844)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
N/A
```

### Diagnostics ID

N/A

**Comment by lorenrh** [comment] 2023-07-03 11:52
Hi thanks for your report. Do you happen to have local installation of kubectl? I just did a fresh install, and I see 1.27.2 :(

**Comment by nicks** [comment] 2023-07-03 13:50
thanks for the report! I'm going to mark this as a duplicate of https://github.com/docker/for-win/issues/12963, which has more details.

**Closed as completed by nicks** 2023-07-03 13:50 UTC
Labels: status/triage, area/Kube, status/duplicate, version/4.21.0
