### ISSUE TITLE
Docker container stats zero disk read/write

### ISSUE THREAD

**Issue by DouglasDRF** [docker/for-win#10432] opened 2021-02-20 14:35 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
In the Docker UI, all the containers like Redis, Postgres in the Stats section the Disk Read/Write Section is always zeroe
### Expected behavior
Show the real stats of Disk 

### Information

  - Is it reproducible?
  Yes
  - Is the problem new?
  I don't think so, at least with WSL2
  - Did the problem appear with an update?
  No. It's happening since some versions earlier
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  I used official images of Redis and Postgres

  - Windows Version:
   20H2
  - Docker Desktop Version:
   3.1.0
  - WSL2 or Hyper-V backend?  
  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  No

### Steps to reproduce the behavior

  1. Create a container like Postgre, MySQL, Redis and fill some table/key/collection with some data
  2. Check the container Stats in Docker Desktop UI

**Comment by stephen-turner** [comment] 2021-02-22 09:26
Thanks for the report, @DouglasDRF. Looking into it.

**Comment by stephen-turner** [comment] 2021-02-26 09:08
@DouglasDRF Apologies for the slow reply. What does `docker stats` on the command line show? Is it the same?

**Comment by DouglasDRF** [comment] 2021-02-27 15:29
Yes. In the test below I ran a stored procedure that inserts 1 milion of lines of fake data in a table. Both the UI and the `docker stats` it's zero

![image](https://user-images.githubusercontent.com/17039306/109391712-3cf6e200-78f7-11eb-8161-36200e6a62dd.png)

**Comment by thaJeztah** [comment] 2021-03-01 10:51
Are you seeing this for any container, or only for containers that use volumes in which the data is written? (wondering if it's related to that).

There are some existing issues in the moby repository, which may help debugging; https://github.com/moby/moby/issues/28114, and https://github.com/moby/moby/issues/21317 / https://github.com/moby/moby/issues/38588, and slightly related https://github.com/moby/moby/issues/16173

**Comment by DouglasDRF** [comment] 2021-03-05 17:52
Sorry the slow time anwser. I think there's no relation with volumes. I tested running a mongo container with no voulume and inserted severeal fake test data and de Disk I/O keeps in zero.

I think that me be something related with Windows Version... In my laptop from the company I work, it has the same docker version, but the Windows is the 1909 release and it works

**Comment by stephen-turner** [comment] 2021-03-05 18:02
Interesting, maybe something has changed in Windows.

I wonder if at this stage I could ask you to copy this ticket into the https://github.com/moby/moby repo instead? If the problem is shown by `docker stats` too, then it must be in the Engine, which is only an upstream to us. Apologies, I would just move the ticket myself, but it's not possible because the Engine is not part of the docker org.

**Comment by DouglasDRF** [comment] 2021-03-08 17:17
The issue copy is done.

**Comment by stephen-turner** [comment] 2021-03-12 11:41
OK, thanks, I'll close this copy.

**Closed by stephen-turner** 2021-03-12 11:41 UTC
