### ISSUE TITLE
docker command line mount points dont resolve relative paths correctly

### ISSUE THREAD

**Issue by chadmccune** [docker/for-win#5735] opened 2020-02-11 16:54 UTC
https://hub.docker.com/editions/community/docker-ce-desktop-windows -->
  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When passing a mount path like `c:\somedirectory\someotherdirectory\..\upone\tohere` previous versions followed the `..\` correctly.  Docker Desktop update 2.20.3 (42716) installed today no longer has this behavior
### Actual behavior
It now fails with: "Error response from daemon: file does not exist."

### Information

  - Windows Version: 1903 (18362.535)
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:no

### Steps to reproduce the behavior

1. mkdir \mysub
2. mkdir \mysub\sub1
3. mkdir \mysub\sub2
4. docker run -it --mount=type=bind,source=c:\mysub\sub2\..\sub1,target=/sub1 ubuntu bash

I use this functionality in some powershell scripts that mount to a subfolder above where the script is ran so i'll do something like 
$myroot = $PSScriptRoot
$mountpath = "$($myroot)\..\myfolder" and then use $mountpath in my command line.

I've worked around the issue by adding another line to my script, but it requires me to change all my scripts.

$mountpath = Resolve-Path $mountpath

**Comment by mg-christian-axelsson** [comment] 2020-02-12 09:50
I noticed this issue in 2.2.0.2. As Docker a long time started to enforce absolute paths I figured this is by design and that it only worked by accident before but I might be wrong on that note. I did end up fixing all my scripts to resolve all relative paths (admittedly a bit of a pain with old batch scripts).

**Comment by liayn** [comment] 2020-02-14 11:01
dumb question, but shouldn't this
`docker run -it --mount=type=bind,source=c:\mysub\sub2..\sub1,target=/sub1 ubuntu bash`
rather be
`docker run -it --mount=type=bind,source=c:\mysub\sub2\..\sub1,target=/sub1 ubuntu bash`

**Comment by chadmccune** [comment] 2020-02-14 14:42
@liayn Yes, and that's how its typed in the description, and when I edit it, it shows correctly, but when it displays, its showing ..\ instead for some reason..

**Comment by mdgilene** [comment] 2020-02-26 20:21
Can confirm this issue. I use a python script to build the docker run commands for me. Making sure to resolve all relative paths to absolute paths before executing the command fixes the issue.

`cmd += f'-v {os.path.abspath(os.path.join(os.getcwd(), "..", "path", "to", "data"))}:/mnt '`

**Comment by STotev** [comment] 2020-04-21 15:23
I have the same issue. The thing is, our scripts used to resolve the paths to `C:\\Users\\...` (double backslashes, absolute path) and it worked before.
Now it only works when the paths are `C:/Users/...`.

We use git bash to run shell scripts that runs everything. 

I have updated my docker to 2.2.0.4 and since then I have this issue.

Is this issue going to be resolved?

**Comment by arobert3434** [comment] 2020-04-23 06:21
I can confirm this on Windows WSL / 2.2.0.5 sharing C drive as worked in 2.1.0.5:

    docker run ... -v /c/dir/subdir/../anotherdir:/somewhere

fails with "docker: Error response from daemon: file does not exist."

    docker run ... -v /c/dir/anotherdir:/somewhere

succeeds.

This should be fixed even though it can be worked around since scripts will often generate paths with the "..".

**Comment by mat007** [comment] 2020-04-23 10:19
@STotev I tested with Edge 2.3.0.0 and it seems to be working properly e.g.
```
→ mathi Thu Apr 23 12:13:15 ~/tmp
$ ls
ok

→ mathi Thu Apr 23 12:15:17 ~/tmp                                                        
$ MSYS_NO_PATHCONV=1 docker run --rm -v "C:\Users\mathi\tmp":/ok alpine ls /ok           
ok                                                                                       
                                                                                         
→ mathi Thu Apr 23 12:17:19 ~/tmp                                                        
$ MSYS_NO_PATHCONV=1 docker run --rm -v "C:\\Users\\mathi\\tmp":/ok alpine ls /ok        
ok                                                                                       
                                                                                         
→ mathi Thu Apr 23 12:17:28 ~/tmp                                                        
$ MSYS_NO_PATHCONV=1 docker run --rm -v C:\\Users\\mathi\\tmp:/ok alpine ls /ok          
ok                                                                                       
```

Or am I missing something?

**Comment by mat007** [comment] 2020-04-23 10:21
@arobert3434 I can confirm I’m able to reproduce it and we’ll be looking into it, thanks!

```
? mathi Thu Apr 23 12:13:15 ~/tmp
$ ls
ok

? mathi Thu Apr 23 12:13:28 ~/tmp
$ MSYS_NO_PATHCONV=1 docker run --rm -v "C:\Users\mathi\tmp":/ok alpine ls /ok
ok

? mathi Thu Apr 23 12:15:03 ~/tmp
$ MSYS_NO_PATHCONV=1 docker run --rm -v "C:\Users\mathi\tmp\..\tmp":/ok alpine ls /ok
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: file does not exist.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
```

**Comment by STotev** [comment] 2020-04-23 14:42
@mat007 I tested the same as you've tested on my machine(with 2.2.0.4) and this seems to work for me, too. I guess something else is causing the issue. I am trying to break down everything that happens for me in order to create something replicable.

Is there a way to see any logs from the daemon to see for which file it is complaining that it cannot find?

I've tried to manually run the same command that our script does, providing all the paths to be absolute, with no wrapping quotes and backslashes, and it seems to be working fine.

The thing is, when I debug all of the paths that are provided as volumes and env files, they seem to be absolute. 

To give more information: the command is in a shell script, all of the paths are provided as variables `${SOME_PATH}` to the docker command.
I had output the command to the console to see what's actually ran and it appear to run the same command I manually ran. I even copied the output and ran it myself again. Everything works.

I guess docker can't resolve the paths given through variables.

I'll try later to test directly in the console by creating variables and pass them to the docker command.

**Comment by mat007** [comment] 2020-04-24 07:39
@arobert3434 actually yours is likely a duplicate of #5735

**Comment by mat007** [comment] 2020-04-24 08:24
Thanks @STotev @arobert3434 @chadmccune and everyone, this has now been fixed in our master branch and will be available in the upcoming Edge and Stable releases.

**Comment by mat007** [comment] 2020-06-08 09:55
Closing as this has now been released on both channels, thanks!

**Closed by mat007** 2020-06-08 09:55 UTC
Labels: status/1-acknowledged, version/2.2.0.3
