### ISSUE TITLE
Mapped Data Folder is not accesbile from MsSqlServer on Docker

### ISSUE THREAD

**Issue by hgmamaci** [docker/for-win#6755] opened 2020-05-16 21:16 UTC
The docker command is
`docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=XXX@35*" -p 2544:1433 -v D:\MsSqlDataRoot\Data:/var/opt/mssql/data2 --name mssql2019 -d mcr.microsoft.com/mssql/server:2019-latest `

I cannot attach database files from this mapped folder on the host.

When I try to test to create a new database I get the error:

CREATE FILE encountered operating system error 31(A device attached to the system is not functioning.) while attempting to open or create the physical file '/var/opt/mssql/data2/test.mdf'.

Version: 2.3.0.2 (45183)
Channel: stable
Sha1: e9b671cd3cb844cb63ad6fd7c79a4d15424233c4
Started on: 2020/05/16 17:19:51.622
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\gokha\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe"

**Comment by mat007** [comment] 2020-05-17 07:52
Thanks for the report, this is a duplicate of #6646.

**Closed by mat007** 2020-05-17 07:52 UTC
Labels: version/2.3.0.2
