### ISSUE TITLE
Docker for Windows 2.1.0.0 - Not Running

### ISSUE THREAD

**Issue by willianfrs** [docker/for-win#4453] opened 2019-08-06 16:57 UTC
Hello, I would like some help. When installing Docker for Windows version 2.1.0.0, it displays an error message and does not start.

Message:
Unable to stop
    in Docker.Core.Pipe.NamedPipeClient. <TrySendAsync> d__5.MoveNext ()
--- End of stack trace from previous location where exception was thrown ---
    in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
    in Docker.Core.Pipe.NamedPipeClient.Send (String action, Object [] parameters)
    in Docker.Actions.DoStart (SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
    in Docker.Actions. <String> c__DisplayClass24_0. <Start> b__0 ()
    in Docker.ApiServices.TaskQueuing.TaskQueue. <String> c__DisplayClass17_0. <. ctor> b__1 ()

Diagnostic ID: A4EB7718-C1AC-4F61-BFA7-427FA539C981/20190806164324

Thanks.

**Comment by mikeparker** [comment] 2019-08-06 17:40
```
O Windows PowerShell atualizou sua pol�tica de execu��o com �xito, mas a configura��o foi substitu�da por uma pol�tica definida em um escopo mais espec�fico. Devido � substitui��o, o shell manter� sua pol�tica de execu��o efetiva atual de AllSigned. Digite "Get-ExecutionPolicy -List" para exibir suas configura��es de pol�tica de execu��o. Para obter mais informa��es, consulte "Get-Help Set-ExecutionPolicy".
[13:43:24.314][PowerShell        ][Error  ] O Windows PowerShell atualizou sua pol�tica de execu��o com �xito, mas a configura��o foi substitu�da por uma pol�tica definida em um escopo mais espec�fico. Devido � substitui��o, o shell manter� sua pol�tica de execu��o efetiva atual de AllSigned. Digite "Get-ExecutionPolicy -List" para exibir suas configura��es de pol�tica de execu��o. Para obter mais informa��es, consulte "Get-Help Set-ExecutionPolicy".
[13:43:24.330][PowerShell        ][Error  ] Falha na verifica��o do AuthorizationManager.
[13:43:24.372][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CommandNotFoundException: O termo 'Stop-MobyLinuxVM' n�o � reconhecido como nome de cmdlet, fun��o, arquivo de script ou programa oper�vel. Verifique a grafia do nome ou, se um caminho tiver sido inclu�do, veja se o caminho est� correto e tente novamente.
```
Duplicate of https://github.com/docker/for-win/issues/4376 we have fixed it and will be releasing a new version shortly

**Closed by mikeparker** 2019-08-06 17:40 UTC

**Comment by mikeparker** [comment] 2019-08-08 12:16
Docker Desktop 2.1.0.1 stable has been released with a fix for this now.

**Comment by willianfrs** [comment] 2019-08-08 14:13
Thank you very much, this version is working perfectly.
