### ISSUE TITLE
Docker for Windows requires installing Hyper-V even though it's not needed for WSL 2

### ISSUE THREAD

**Issue by aelij** [docker/for-win#4934] opened 2019-10-15 07:44 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Prompt for Hyper-V installation only when running Docker in the default (non-WSL2) mode.

Additionally, under some conditions I've seen the Docker installer automatically enable Hyper-V, which should also be avoided.

### Actual behavior
D4W prompts to install Hyper-V. Clicking Cancel shuts down Docker. However, right clicking the Docker icon and activating WSL 2 works just fine without Hyper-V installed (while the dialog remains open). 

### Information
  - Windows Version: 10.0.18990.1
  - Docker Desktop Version: 2.1.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Make sure Hyper-V isn't installed
2. Install WSL 2
3. Install Docker for Windows preview
4. Start Docker for Windows

**Comment by stephen-turner** [comment] 2019-10-15 10:16
Dupe of #4700.

**Closed by stephen-turner** 2019-10-15 10:16 UTC

**Comment by aelij** [comment] 2019-10-15 10:41
@stephen-turner the issues are not exactly the same. This one is specifically about the Hyper-V prerequisite check which should be simple to resolve even during the preview.

Also, if you're intending on addressing this issue, why close both of them?

**Comment by aelij** [comment] 2019-10-15 10:48
This is how I'd change the UX (less intrusive and better regardless of WSL2, IMHO):

When detecting Hyper-V isn't installed, instead of showing the dialog, add a warning icon to the docker tray icon, and add a context menu option to install it.
