### ISSUE TITLE
How make docker host respond on port 2375

### ISSUE THREAD

**Issue by eliassal** [docker/for-win#314] opened 2016-12-12 20:07 UTC
### Actual behavior
I am trying to access my docker from a 2nd machine using tcp://mydockerhost:2375 but not able to reach it. After doing a netstat, I noticed that the IP 127.0.0. listening is listening on the is port
as follows

> TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING

I am trying to access my docker from a 2nd machine using tcp://mydockerhost:2375 but not able to reach it. After doing a netstat, I noticed that the IP 127.0.0. listening is listening on the is port

I tried the following:
1 - In the Docker for windows settings > Daemon, I pasted 

> {
>     "hosts": ["tcp://192.168.1.51:2375"]
> }

It crashed, then changed it to 

> {
>     "hosts": ["tcp://192.168.1.51:2375"]
> }

So I reverted back and put the 2 lines by defaut which allowed Docker to start.

2 - I created a Daemon.json file, placed it in "C:\ProgramData\Docker\config", pasting in this file again
{
    "hosts": ["tcp://192.168.1.51:2375"]
}
I restarted docker successfuly but still see doing netstat

> TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING

I read some articles indiciating to start dockerd with -H.....but it seems that Docker for Windows does not allow this.

Can you please let me know how this can be done so I can acces docker remotely
### Information

  - Server version  = 1.13.0-rc3.
  - win 10
 

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by eliassal** [comment] 2016-12-12 20:10
Sorry; there is a mistake while I was typing
Changed to 
"hosts": ["tcp://0.0.0.0:2375"]
it crashed also

**Comment by rneugeba** [comment] 2016-12-12 22:29
are you trying to reach windows containers or Linux containers?

**Comment by eliassal** [comment] 2016-12-12 22:41
Linux containers

**Comment by friism** [comment] 2016-12-12 22:43
@eliassal I think this might be a duplicate of this question: https://github.com/docker/for-win/issues/225#issuecomment-266576967

**Comment by eliassal** [comment] 2016-12-12 23:23
Michael, in your our response to question 225, you recommend to play with the docker-machine. 1st, I have Docker for windows on the win10, wouldn't this create some issues.
I understand that Docker for windows cann't be configured and reached from outside, is this something that will be fixed in later versions or it is just by design and it will be always like this

**Comment by friism** [comment] 2016-12-12 23:37
@eliassal you can use Docker Machine with Docker for Windows to create more local hosts by using the hyper-v Docker Machine driver. Details here:

 * https://github.com/docker/labs/tree/master/swarm-mode/beginner-tutorial
 * https://github.com/docker/labs/blob/master/swarm-mode/beginner-tutorial/swarm-node-hyperv-setup.ps1

Or you can simple use any cloud host supported by docker-machine (which is most of them).

We may investigate opening this up later, but I don't think it's a priority right now.

Do you have more details on the user case that you're trying to unlock?

**Comment by eliassal** [comment] 2016-12-12 23:45
Thanks Michael, I have a couple of linux machines and hosting docker but I am doing a POC for a customer who is full MS stack. I managed to convince technical director to start Dockerisation of their Dev machines as a start point. Later, Also, they need to integrate a release workflow between Jenkins and Docker for windows. It will be difficult to convince them to switch activities to any linux environment.

**Comment by justincormack** [comment] 2016-12-12 23:47
You can run a small proxy container that accepts connections on 2375 and connects to the docker daemon socket (bind mounted in), and then publish the port on that so it is available on the host.

**Comment by eliassal** [comment] 2016-12-13 08:58
justin, wait wait , hold a moment, i am not expert yet in docker, is theres any doc or tutorial for the steps to follow, I am in the learning stage :-)

**Comment by xblanc33** [comment] 2016-12-22 22:37
Dear all,

I am also trying to reach my docker host on port 2375 from one of it container.

@friism, the use case I want too unlock is this one : https://engineering.riotgames.com/news/jenkins-ephemeral-docker-tutorial

It appears that I cannot reach it but I don't understand why. Is it a question of credential ?

Thanks a lot.

**Comment by friism** [comment] 2017-03-10 21:05
I think this is duplicate of https://github.com/docker/for-win/issues/225 closing this.

**Closed by friism** 2017-03-10 21:05 UTC
Labels: area/network, status/0-triage

**Comment by atomaras** [comment] 2018-07-18 22:30
I run `netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<public interface ip> protocol=tcp` to proxy from the outside world and it worked like a charm

**Comment by Tires** [comment] 2018-08-03 19:30
I created my Docker machine with "docker-machine create [...]" with virtual switch, so the docker machine is exposed to my local network and I can connect from other machines also

**Comment by TWhidden** [comment] 2018-09-18 05:58
> I run `netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<public interface ip> protocol=tcp` to proxy from the outside world and it worked like a charm

I hate this -- but it worked great. Thanks. Now I can get back to dev!

**Comment by tahuy** [comment] 2020-04-13 13:55
> I run `netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<public interface ip> protocol=tcp` to proxy from the outside world and it worked like a charm

really beautifull man
