### ISSUE TITLE
docker-init executable file not found in $PATH

### ISSUE THREAD

**Issue by hampt** [docker/for-win#695] opened 2017-05-02 11:42 UTC
### Expected behavior
After successfully installing Docker for Windows, the following hello-world invocation should work even with the --init parameter:
docker run --init hello-world

### Actual behavior
The above command fails with:
docker: Error response from daemon: exec: "docker-init": executable file not found in $PATH.

The same error has also been observed in Docker for Mac.

### Information
  - Diagnostic ID: 00739202-5BBB-4490-B244-970AF69926FB/2017-05-02_12-28-54
  - Windows 10 Enterprise Version 1607 Build 14393.1066

### Steps to reproduce the behavior
1. Install Docker for Windows
2. docker run --init hello-world

**Comment by friism** [comment] 2017-05-02 23:07
What's your use-case for `--init`?

**Comment by friism** [comment] 2017-05-02 23:12
@hampt can you try installing the Edge variant of Docker for Windows. That's what I'm using, and I can't reproduce.

**Comment by hampt** [comment] 2017-05-03 10:24
Indeed, the Edge version does not have the bug. This is limited to the current stable version, then. 
Use case is R-studio/Jupyter kind of software that spawns arbitrary/uncontrolled subprocesses.

**Comment by friism** [comment] 2017-05-03 14:59
OK, closing - I recommend using edge for now, the fix will be in stable in 17.06.

**Closed by friism** 2017-05-03 14:59 UTC
