### ISSUE TITLE
Cannot Share drives Windows10

### ISSUE THREAD

**Issue by ronce96** [docker/for-win#1801] opened 2018-03-07 12:59 UTC
### Expected behavior
Drive is shared

### Actual behavior
The checkbox is unchecked after I click on apply

### Information
I'm using windows 10 and Docker version 17.12.0-ce, build c97c6d6

### Steps to reproduce the behavior
  1. Run docker
  2. Go to docker settings > Shared Drives
  3. Select the drive to share
  4. Click apply

**Comment by jasonbivins** [comment] 2018-03-07 16:08
Hi @ronce96 
Do you get any errors or warnings when the box is unchecked?

**Comment by ronce96** [comment] 2018-03-07 16:53
@jasonbivins No, the common error of the firewall doesn't appear this time.

**Comment by crramirez** [comment] 2018-04-02 20:07
Hello @ronce96 

I have the same problem and I found a workaround. My windows account is a corporate one using Azure AD. Probably the problem is regarding how the account was created. As a work around create a new account, tell Windows that you don't have the email address for the new account and ultimately you won't login using a Microsoft account. Put a username "docker" for example, a good password, and create the account. Then edit the account to change the type to Administrator. In docker share the drive using the credential created putting your computer name before the username. Ex: DESKTOPXYZ\docker

This worked for me and the drive remains checked.

Hope it helps

Regards

**Comment by Ron-Burg** [comment] 2018-06-14 07:36
@crramirez Thanks!
I had the same exact issue (checkbox is unchecked after apply), this workaround fixed it.

**Comment by lucallero** [comment] 2018-09-09 03:51
Same issue here, the workaround of creating a new account didn't work. I'm really trying to work on a Windows box, but it's hard. This is the type of thing that annoys, no error, no log, no solution simply doesn't work, and this is with a simple feature of mount a persistent volume.

**Comment by brona90** [comment] 2018-11-22 07:14
+1
I am having the same issue.

**Comment by PsychoXIVI** [comment] 2018-11-29 15:21
Same issure :C

**Comment by syedhassaanahmed** [comment] 2018-12-02 22:52
Same issue. Any ETA on this?

**Comment by andalerom** [comment] 2018-12-05 17:29
My work around was to remove C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks folder...

**Comment by jmcgrory** [comment] 2019-01-10 13:59
Several of my team and I are experiencing this exact issue. It means we are unable to mount volumes/run containers.

My current workaround is to:

1. Turn off my computer
2. Pull my MacBook out of my bag
3. Pretend that Docker for windows exists

This is obviously not ideal. No quoted steps here have helped.

**Comment by vaceslav** [comment] 2019-02-12 21:19
workaround from @andalerom worked for me

**Comment by nea** [comment] 2019-02-13 09:48
Hi

I just want to promote what helped me thanks to @crramirez: I created a totally local user "docker", made it "Administrator" and used that user to login and share now.

Maybe thats an even cleaner solution ^^


Thanks a lot

**Comment by sprevrha** [comment] 2019-02-27 00:47
nngo's reset solution worked for me
https://github.com/docker/for-win/issues/2549#issuecomment-466030418

**Comment by perringqvist** [comment] 2019-02-27 12:52
@nea :s (@crramirez) solution worked for me as well. Many thanks

**Comment by jl-cs** [comment] 2019-03-06 10:45
Workaround from @andalerom also worked for me, thanks!

**Comment by danielmorlock** [comment] 2019-03-06 15:11
You should check ´ C:\Users\<user>\AppData\Local\Docker\log.txt´ for errors. 

In my case, I found the following:

´´´
[16:00:39.130][ApiProxy       ][Info   ] time="2019-03-06T16:00:39+01:00" msg="proxy << POST /v1.39/containers/dff37012ad4a61bb3234939c60fbcb10d3ebf6744268522539c3ca5a6892ed72/start (1.3915871s)\n"
[16:00:39.135][SambaShare     ][Error  ] Unable to mount C drive: C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/usr/bin/nsenter1\": stat /usr/bin/nsenter1: no such file or directory": unknown.
[16:00:39.135][SambaShare     ][Info   ] Removing share "C"
[16:00:39.188][NamedPipeClient][Info   ] Received response for filesharing/mount
´´´

Obviously the container (to test the SMB mount) is falsely missing ´/usr/bin/nsenter1` and crashes which results in a Docker Windows GUI doing nothing.

In my case this "test"-Docker-container seemed to be in a bad state. Since I cannot access the Hyper-V Machine for further debugging, removing the Hyper-V Disk Folder as @andalerom suggested was an appropriate solution that actually worked for me.

**Comment by cswgr** [comment] 2019-03-22 10:28
I had the same error message in the log.
For me it worked after I simply deleted the image `docker4w/nsenter-dockerd`.

**Comment by naeemmuhammad** [comment] 2019-04-17 10:42
In my case i was trying to create share by using a user account that was not in 'docker-users' group. Either add your account to that user group or use user account that already exists in that group. User groups can be accessed by 'lusrmgr.msc'

**Comment by CamDHall** [comment] 2019-06-15 01:24
Adding both my AzureAD account and a local account to the user group doesn't change anything for me.

**Comment by sithu951** [comment] 2019-06-24 04:21
I solved this problem by just deleting an image, as mentioned by @cswgr. Thank you so much.

**Comment by KindYAK** [comment] 2019-07-12 11:44
Hope this might have some people:
I was having the same issue. I had the following line in my logs:
`Unable to mount C drive: 10.0.75.1 (10.0.75.1:445) open`
Along with other lines related to IpV6, SambaShare and IPVS

Long story short:
The issue is related to how poorly network folder sharing is implemented in Windows. And Docker is using the folder sharing mechanism, so that might be the reason why the issue is coming up for so many people and there doesn't seem to be a fix.
What fixed it for me (I am not sure if it's a complete recipe, or that all of the steps are needer, but that what seemed to make it work for me):
1) Enabling IpV6 in all network devices. It was disabled
2) Enabling SMB 2/3 (I've also enable SMB 1, but seems like Docker is using SMB 3) - it's a network folder sharing protocols which were disabled in my system by default
3) Enabling network sharing and disabling password protection in "Network and Internet settings" -> "Sharing options"
4) I've uninstalled VmWare Player, which also removed VmWare virtual network devices.
5)* I am not sure if it's necessary, but at the moment it is working with a separate user without Micorosoft Account, as other advices mentioned - not sure if it's a must, but I am not going to touch it while it works

Six hours of my life - and I have it working :)

**Comment by kcorlidy** [comment] 2019-08-02 12:57
I tried cswgr's and andalerom's solution, but unfortunately it does not work for me. I even closed all firewall. What i did same as OP described *The checkbox is unchecked after I click on apply*, but if i ran `docker run --rm -v c:/Users:/data alpine ls /data` will return 

    C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Drive sharing failed for an unknown reason.
    See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.`

**Comment by kanpeki** [comment] 2019-08-05 15:04
Enabling Smb protocol fixed it for me. (run `Set-SmbServerConfiguration -EnableSMB2Protocol $true` in Powershell)

**Comment by patpicos** [comment] 2019-08-05 21:51
> Enabling Smb protocol fixed it for me. (run `Set-SmbServerConfiguration -EnableSMB2Protocol $true` in Powershell)

did you have to reboot?

**Comment by hatxor** [comment] 2019-08-22 22:42
> Enabling Smb protocol fixed it for me. (run `Set-SmbServerConfiguration -EnableSMB2Protocol $true` in Powershell)

I did it and worked! (Without reboot @patpicos)

**Comment by zubair1024** [comment] 2019-10-29 15:48
thanks @crramirez your solution worked!

**Comment by averri** [comment] 2019-11-18 12:13
> My workaround was to remove C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks folder...

What are the consequences of doing that?!

**Comment by andalerom** [comment] 2019-11-18 19:45
@averri, removing `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks` folder removes all your containers.

**Comment by bjornna** [comment] 2019-11-24 17:28
@andalerom  - removing `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks` worked for me as well. Of course I had to build up all containers and images. But it was worth it. 

Thanks!

**Comment by jjborie** [comment] 2019-12-10 13:41
Hello,

I found that adding your local user to Remote Desktop User group do the trick for me no need admin permission.

Best

**Comment by mattbell87** [comment] 2019-12-12 02:12
Try the latest [edge build](https://docs.docker.com/docker-for-windows/edge-release-notes/). It worked for me. No workarounds needed and didn't ask for my creds at all.

In the release notes:

> File sharing: The new gRPC FUSE system is no longer experimental and is enabled by default even when experimental features are turned off.

![image](https://user-images.githubusercontent.com/2722612/70676582-ca451b00-1ce0-11ea-9213-abb8f984dd71.png)

**Comment by stephen-turner** [comment] 2020-02-11 14:23
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.

**Closed by stephen-turner** 2020-02-11 14:23 UTC
Labels: area/mounts, area/windows 10, status/0-triage

**Comment by jmcgrory** [comment] 2020-02-11 14:41
> This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.

In the interim my entire office has switched to Linux 🤷‍♂

**Comment by coderzheng** [comment] 2020-04-16 07:16
It works for me when I delete a image,  as mentioned by @cswgr, thank you very much!
