### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop

### ISSUE THREAD

**Issue by bruparel** [docker/for-win#3624] opened 2019-03-26 03:23 UTC
Docker Daemon fails to start with the following error message (wrapped for readability):

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:

Generic failure  at New-Switch, <No file>: line 121 at <ScriptBlock>, <No file>: line 411
    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
    at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0()
in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()
in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by bruparel** [comment] 2019-03-26 03:25
Here is the entire stack trace:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by Tijaques** [comment] 2019-03-26 18:58
Approximatelly same thing for me with this stack, when starting Docker from new install on Win10 Pro.
Getting this with stable and edge : 

```
Unable to check availability for Windows feature *Hyper-V*: Le Registre de configuration est endommagé.

   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 92
   à Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 74
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59
```

**Comment by TravisEz13** [comment] 2019-04-11 20:45
Where is this code `C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs`.  I have a bug report to my team and I need to understand what this is doing.

**Comment by bruparel** [comment] 2019-04-11 22:01
You are a few days too late.  I re-imaged my machine and reinstalled Windows for Docker which is running fine now.  If you had reached out a couple of days sooner, I would have been able to give you more specific information.  Mostly, I found that my Hyper-V install had been corrupted somehow and it was not even able to create a Virtual Switch.

**Comment by TravisEz13** [comment] 2019-04-11 22:53
My issue wasn't exactly the same just the same stack.  I'm more curious where in the PowerShell execution occurs. I work on PowerShell.

**Comment by thaJeztah** [comment] 2019-04-12 00:17
That code is in a private repository; @simonferquel @chris-crone ^^ do you know if there's a way to give limited access to that code?

**Comment by simonferquel** [comment] 2019-04-12 08:00
I think the powershell script is actually distributed with docker desktop (check MobyLinux.ps1 in the docker desktop resources directory)

**Comment by thaJeztah** [comment] 2019-04-12 08:52
Thanks @simonferquel! 

@TravisEz13 if you need more information, feel free to reach out 🤗

**Comment by mikeparker** [comment] 2019-05-30 13:56
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 13:56 UTC

**Comment by fakabbir** [comment] 2020-01-08 07:33
Tried uncheck and check back after restart worked for me:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
