### ISSUE TITLE
Can't start any two docker-compose environments after update to Windows 20H2

### ISSUE THREAD

**Issue by marcusschroeder** [docker/for-win#9999] opened 2021-01-04 14:41 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
On my computer I use a couple of docker-compose environments with windows containers in parallel. Before the windows update to 2004 or 20H2 it was no problem to start several environments with 
```docker-compose up``` either manually or programmatically. It didn't matter if it was the same env with a different name or a completely different one.

### Actual behavior
Now, when starting any two docker compose environments, the second one gets stuck in start up until the first is stopped.

### Information

  - Is it reproducible? Yes, even on another computer.
  - Is the problem new? Yes, it appeared after windows update 1903 to 20H2
  - Did the problem appear with an update? Yes
  - Windows Version: Windows 10 Pro 20H2
  - Docker Desktop Version: 2.5.0.1 / 2.4.0.0 / 2.3.0.4 / 2.5.1.0 (experimental) / 3.0.0.0

docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)
Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 4
 Server Version: 20.10.0
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19042.685)
 OSType: windows
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.87GiB
 Name: <filtered>
 ID: <filtered>
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 51
  System Time: 2021-01-04T15:34:42.8968077+01:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Live Restore Enabled: false
 Product License: Community Engine
```

The problem appeared after a Windows update from 1903 to 2004 or 20H2 respectively.

I have tried:
- different Docker Desktop versions (see above) to no avail.
- WSL2 and LCOW

### Steps to reproduce the behavior

Use the following docker-compose.yml:
```
version: "2.4"


services:
  service_a:
    image: mcr.microsoft.com/windows/servercore/iis
    ports:
      - 80


  service_b:
    image: mcr.microsoft.com/windows/servercore/iis
    ports:
      - 80
```
1. Use Docker Desktop with Windows Container Backend
2. Start first environment with above docker-compose.yml: ```docker-compose -p first up -d```
3. Wait until environment is up (5-10 seconds)
4. Start second environment: ```docker-compose -p second up -d```
    At this point docker-compose appears to be stuck and one of the services show status "created" in ```docker ps -a```
6. Stop first environment in separate terminal ```docker-compose -p first down```
7. Now, the command from 5. continues and the environment becomes healthy and the service status is "running"

Furthermore:
- if I remove the "ports" from the docker-compose.yml this issue does not occur.
- rolling back to windows 1903 also fixed the issue for now until the windows update is applied again

Thank you in advance for your support.

**Comment by neumannj777** [comment] 2021-04-29 08:12
Can someone fix this, please?

**Comment by marcusschroeder** [comment] 2021-05-08 12:40
This issue still exists in Docker Desktop 3.3.3

**Comment by stephen-turner** [comment] 2021-05-18 09:46
We have escalated this to Microsoft.

**Comment by marcusschroeder** [comment] 2021-05-20 12:57
Thank you!

**Comment by marcusschroeder** [comment] 2021-07-09 10:35
The issue still exists in Docker Desktop 3.5.2

**Comment by stephen-turner** [comment] 2021-07-09 10:43
Yes, still waiting for an answer from Microsoft. I'll ping them again.

**Comment by stephen-turner** [comment] 2021-07-22 10:26
And I've pinged them again today. Given that it's caused by a Windows update, it's likely that it will have to be fixed by a Windows update too. The other possibility is that it may be fixable in the Windows container code in the upstream container engine (https://github.com/moby/moby) but that would still be the same team at Microsoft.

**Comment by stephen-turner** [comment] 2021-07-28 14:09
I've transferred this ticket to microsoft/Windows-Containers#140, and I'll close this copy now.

**Closed by stephen-turner** 2021-07-28 14:09 UTC
Labels: lifecycle/frozen, version/10.0 19042
