### ISSUE TITLE
Windows 10 after upgrade Windows and docker versions can't login, pull, run

### ISSUE THREAD

**Issue by clininalascondes** [docker/for-win#13667] opened 2023-09-01 17:20 UTC
### Description

Hello all,

After my windows upgrades to last version of windows 10 22H2 (before the windows version was Win10 19H1) and upgrade Docker Desktop to last version. I have regretted, I can't pull any image of docker hub. The error are:

1. I can't login in docker environment
2. I can't pull any image
3. I can't run any images

The error is:

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting
 for connection (Client.Timeout exceeded while awaiting headers)

I have read a lot of reports in internet:

I modified c:\windows\system32\drivers\hosts and and address:
# localhost name resolution is handled within DNS itself.
127.0.0.1       localhost
::1             localhost

34.228.211.243  registry-1.docker.io
#44.205.64.79    registry-1.docker.io

#34.228.211.243  registry-1.docker.io/v2/
#34.205.14.154   auth.docker.io
34.205.88.205   auth.docker.io
104.18.121.25   production.cloudflare.docker.com
# Added by Docker Desktop
172.19.66.19 host.docker.internal
172.19.66.19 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

I resinstall:
-  wsl 
-  docker

### Reproduce

1. docker login -u auribei 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting
 for connection (Client.Timeout exceeded while awaiting headers)
2.  docker pull hello-world
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting
 for connection (Client.Timeout exceeded while awaiting headers)
3. 
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while
 waiting for connection (Client.Timeout exceeded while awaiting headers).

### Expected behavior

docker run apache/nifi:latest run good.

### docker version

```bash
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.22.1 (118664)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.627GiB
 Name: docker-desktop
 ID: b15fd41a-f1e3-4da8-9eaa-c2e25fde43a8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

27FFC2C2-ABE6-48F2-9643-386F017D0224/20230901162735

### Additional Info

wsl -v 
Versi¾n de WSL: 1.2.5.0
Versi¾n de kernel: 5.15.90.1
Versi¾n de WSLg: 1.0.51
Versi¾n de MSRDC: 1.2.3770
Versi¾n de Direct3D: 1.608.2-61064218
Versi¾n DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versi¾n de Windows: 10.0.19045.3086

wsl -l
Distribuciones de subsistema de Windows para Linux:
docker-desktop (predeterminado)
docker-desktop-data

Windows System
Edition	Windows 10 Pro
Version	22H2
Installed on	‎04-‎01-‎2022
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by lorenrh** [comment] 2023-09-11 16:28
Thanks for your report, I'll close this issue as a duplicate of https://github.com/docker/for-win/issues/13662, any more information you want to share, please share it on that issue.

**Closed as completed by lorenrh** 2023-09-11 16:28 UTC
Labels: needs-triage, version/4.22.1
