### ISSUE TITLE
Unable to switch to Linux Containers in Windows 10

### ISSUE THREAD

**Issue by chinns06** [docker/for-win#3029] opened 2018-12-04 18:56 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ngie-eign** [comment] 2018-12-07 19:21
This issue is probably a duplicate of #1348.

**Closed** 2019-01-15 15:06 UTC
