### ISSUE TITLE
Unable to attach container to NAT network

### ISSUE THREAD

**Issue by delmania** [docker/for-win#1755] opened 2018-02-27 12:13 UTC
I've been working on migrating an ASP.NET application to Docker for months, and everything has been going fine.  It's a fairly simple setup, with SQL server running in one container and ASP.NET running on a second container, connected to each other using the nat network.  However, just a few days ago, I started receiving this error message when starting the application:

 `meazureweb_meazure-db_1 is up-to-date
Starting meazureweb_meazure-web_1 ... error

ERROR: for meazureweb_meazure-web_1  Cannot start service meazure-web: failed to create endpoint meazureweb_meazure-web_1 on network nat: HNS failed with error : The process cannot access the file because it is being used by another process.

ERROR: for meazure-web  Cannot start service meazure-web: failed to create endpoint meazureweb_meazure-web_1 on network nat: HNS failed with error : The process cannot access the file because it is being used by another process.
ERROR: Encountered errors while bringing up the project.`

I'm  at a loss.  I've reinstalled Docker, rebuilt the containers, all with no luck.  I've read this issue might be related to AV Software and bitlocker, but this has been working just fine for months.  Looking for some help here.

**Comment by jasonbivins** [comment] 2018-02-27 22:20
@delmania   We're working with Microsoft on some very similar issues, there seems to be a stuck vSwitch
Try these steps in powershell to see if it clears out the blockage
```
Stop-Service docker
stop-service hns
Get-ContainerNetwork | Remove-ContainerNetwork
Delete your HNS.data file
• C:\ProgramData\Microsoft\Windows\HNS\HNS.data
Start-service hns
Start-Service docker
```

**Comment by buzzfrog** [comment] 2018-02-28 09:29
I have the same problem when using Windows Containers.

**Comment by delmania** [comment] 2018-03-01 10:56
@jasonbivins Thanks for help, I probably should have mentioned this is on Windows 10!  Where is the Get-ContainerNetwork cmdlet?  Is that only on nano-server?  The github repository hasn't been updated in 2 years.

**Comment by Kaimonos** [comment] 2018-03-01 10:58
I picked up my docker project yesterday, and I'm seeing the same issue.

docker: Error response from daemon: failed to create endpoint priceless_golick on network nat: HNS failed with error : The process cannot access the file because it is being used by another process.

I hadn't worked on the project for 2 months.

This is indeed a windows container on win 10.

**Comment by natemcmaster** [comment] 2018-03-02 19:38
We ran into this bug recently too on the ASP.NET Core team. What we discovered is that the issue may be caused by port conflict. Changing a container to attach to an unused port makes the error go away.

What we found is that this started failing when the machine received the KB4074590 update. https://support.microsoft.com/en-us/help/4074590/windows-10-update-kb4074590. It appears that before this update, there was a false-positive return when attempting to bind to an already reserved port. In our CI test, we had always been trying to attach a Docker container to a reserved port. Docker thought everything was ok. Windows fixed something in the network stack and now binding to a reserved/in-use port is failing correctly as it should have all a long...thus the appearance of a regression.

If this is the only reason the error appears, it would be nice to produce a better error message to indicate that port conflict is the issue.

**Comment by dazinator** [comment] 2018-04-24 20:00
Thanks @natemcmaster - that does seem to be the cause in my case, and helped me resolve this issue.

**Comment by stephen-turner** [comment] 2018-05-02 15:58
I think this is the same as #1745, so closing as a dupe.

**Closed by stephen-turner** 2018-05-02 15:58 UTC
Labels: Kind/OS, area/network, area/wincon, kind/bug, status/0-triage

**Comment by SQLHorizons** [comment] 2018-07-21 14:42
@sisimogangg, Not sure about the rest of the comments here, but this is what worked for me.  Would be nice if the error actually told you that the port was already in use.

**Comment by ravikr-dev** [comment] 2019-06-28 07:44
This did not work for me, I tried a new port still the same error.
PS C:\WINDOWS\system32> docker run -d -p 1401:1433 --name SqlLocal2 -e sa_password=pwd -e ACCEPT_EULA=y microsoft/mssql-server-windows-developer:2017-latest
9120b55b918ad5cf1f6fbc55ec8884ba6bcce00beb11f924c05e842370cc3ac4
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: failed to create endpoint SqlLocal2 on network nat: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20).

**Comment by kolexinfos** [comment] 2019-07-30 08:34
The issue for me was also the port conflict issue, changing the container to run a port that was not in use fixed the error message which was misleading. it would be nice if the error message is more descriptive.

**Comment by johndkane** [comment] 2019-11-07 03:31
I'm providing additional troubleshooting information for this issue. My problem was also port numbers manually chosen, however I had a hard time tracking down which were available ...

In Windows, `netstat -a -b ` did not show the port numbers as being in use that I was trying, as I kept incrementing and guessing at more. These "ghost port mappings" (as I call them) tended to happen when my laptop was connected to a work VPN; maybe some funky networking things I don't understand. Regardless ... 

It was solved by using the docker run `-P` (uppercase) unary flag to tell docker to choose random available port numbers, and I removed the `-p=?` (lowercase) binary flag specifying explicit mappings of my guesses.   Docker successfully picked some high port numbers that were available and ran the container on them.
