### ISSUE TITLE
"Open Docker Desktop dashboard at startup" setting not applying

### ISSUE THREAD

**Issue by CeyFun** [docker/for-win#10769] opened 2021-03-28 12:26 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7A450A84-92E8-4DB4-8150-A04281D40440/20210328115352

### Actual behavior
Having the `Start Docker when you log in` setting checked and the `Open Docker Desktop dashboard at startup` setting unchecked makes the Docker dashboard appear every time I log in. The `Open Docker Desktop dashboard at startup` setting does not seem to change this behavior.

### Expected behavior
The Docker Desktop dashboard should not appear when login in when the `Open Docker Desktop dashboard at startup` setting is checked.

### Information

  - Windows Version: 20H2 - 19042.867
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Open Docker Desktop settings.
  2. Check the `Start Docker when you log in` setting and uncheck the `Open Docker Desktop dashboard at startup` setting.
  3. Click the `Apply & Restart` button.
  4. Restart the computer and log in.
  5. The Docker Desktop dashboard shows up.

**Comment by stephen-turner** [comment] 2021-03-30 13:19
Thanks for the report, we'll have a look.

**Comment by stephen-turner** [comment] 2021-04-07 13:48
Thanks again, CeyFun, but I was unable to reproduce this. With those settings, Docker started up when I logged in but the dashboard wasn't opened.

**Comment by CeyFun** [comment] 2021-04-07 13:59
It is weird. 🤔 I think I will install Docker on another Windows computer to see if the dashboard appears. If I cannot reproduce this, I will try to compare the two Docker installations to see what causes it. Thanks for looking into this anyway !

**Comment by CeyFun** [comment] 2021-04-07 23:37
I took an old PC that I have and installed Windows then Docker on it. I was not able to reproduce this bug. So I guess that something is wrong with my computer.
If I figure what is causing it I will post it here for future reference.

**Comment by stephen-turner** [comment] 2021-04-08 07:55
OK, thanks. I'll close this ticket for now, but please reopen it if you have more info later.

**Closed by stephen-turner** 2021-04-08 07:55 UTC
Labels: version/3.2.2
