### ISSUE TITLE
The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by Hwailaluta** [docker/for-win#177] opened 2016-10-28 05:32 UTC
### Expected behavior
Docker starts.

### Actual behavior
Docker doesn't start.

### Information

  - Diagnostic ID: FC334598-58BF-4DC0-892B-B5BCAE3DD79A/2016-10-28_00-27-35
  - Windows 10 Education edition. Latest version of Docker for Windows

### Steps to reproduce the behavior

  1. Run Docker for Windows on Windows 10 Education edition.

I had also tried Docker Toolbox with Windows 10 Home edition before this but upgraded to Education due to it not working.

**Comment by timotei** [comment] 2016-10-28 10:47
What HyperV switches do you have? I have the same issue in a VM

**Comment by rneugeba** [comment] 2016-10-28 11:58
@Hwailaluta thanks for your report. Could you try the latest Beta from https://download.docker.com/win/beta/InstallDocker.msi and if it also doesn't work provide the new diagnostics ID. The new logs will tell me if this is a duplicate of #54 or a different issue.
Thanks

**Comment by Hwailaluta** [comment] 2016-10-28 18:23
Hi, just tried it. It failed to give me a diagnostics ID, probably because my computer fell offline during the process. Maybe it's just me, but there seems to be a correlation between my crashing Docker and falling offline. I'm not falling offline during other processes. Here's the crash report:

Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

A friend suggested I try running it in Linux. I guess that's worth a shot?

**Comment by rneugeba** [comment] 2016-10-28 18:39
you mentioned you had toolbox installed..is it fully un-installed?

**Comment by Hwailaluta** [comment] 2016-10-28 18:48
Hm...I uninstalled it, Kitematic, and Virtualbox through Control Panel. Maybe it left something behind? Also, I did try running Docker for Windows before uninstalling those. However, I only just tried the Beta version with them both uninstalled along with the stable Docker for Windows.

**Comment by chadtipton** [comment] 2016-10-29 02:41
I'm getting the same error. Here's my diagnostic ID: 9D3EF1EF-78FF-4B8C-89D8-F431B5EC468C/2016-10-28_22-30-24

**Comment by chadtipton** [comment] 2016-10-29 22:03
Okay I got the stable version to work briefly after reinstalling windows.
1. Made Windows 10 Pro Installation Media with USB Flash Drive.
2. Downloaded and Copied InstallDocker.msi (Stable) to Windows 10 Installation Media (Flash drive).
3. Unplugged Network Cable.
4. Rebooted and performed clean install of Windows 10 Pro.
5. Win+R to run 'winver'. It says 'Version 1607 (OS Build 14393.0)'
6. Installed docker from InstallDocker.msi on Windows 10 Installation Media.
7. After automatic restart from installing Hyper-V services, Docker is running, and has IP address in Hyper-V manager.
8. Plugged in network cable.
9. Installed updates: KB3201860, KB3199986, KB3197954, KB890830
10. Computer Restarts.
11. Docker no longer runs.
Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
12. Reset to Factory Defaults. It doesn't run.
13. Uninstalled KB3197954 (Cumulative Update). It doesn't run.
14. Disabled Windows Defender and reset to factory defaults. It doesn't run.
15. Turned off Firewall and reset to factory defaults. It doesn't run.

**Comment by rneugeba** [comment] 2016-10-30 11:40
Thanks for the info. I had a look at the diagnostic and unfortunately, you are experiencing the same issue as described on #54. I'm closing this as a duplicate and add your info to #54.

**Closed by rneugeba** 2016-10-30 11:40 UTC
Labels: status/0-more-info-needed
