### ISSUE TITLE
Share drive under user with no password

### ISSUE THREAD

**Issue by SG5** [docker/for-win#449] opened 2017-01-31 08:26 UTC
### Expected behavior
Click `ok` with empty password

### Actual behavior
`ok` button disabled and took enable state only with not empty  password field

### Steps to reproduce the behavior

  1. Share drive C:

**Comment by rneugeba** [comment] 2017-01-31 09:43
@SG5 Thanks for the report. This is a duplicate of #366, #352 and we commented on there that we rely on Authenticated Samba mounts, so this won't fix.

**Closed by rneugeba** 2017-01-31 09:43 UTC
