### ISSUE TITLE
WSL integration not working

### ISSUE THREAD

**Issue by HANDZCZ** [docker/for-win#8207] opened 2020-08-24 13:46 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD71A767-8C31-41A5-9D5F-41080C8F9190/20200824134235

### Expected behavior
WSL integration starts working
### Actual behavior
WSL distro proxy fails to start

Log:
```
[15:30:57.367][WslIntegrationAgent-Arch][Info   ] 2020/08/24 15:30:57 Starting distro cli api server on /home/handz/.docker/run/docker-cli-api.sock
[15:30:57.368][WslIntegrationAgent-Arch][Info   ] 2020/08/24 15:30:57 Starting WSL Distro proxy
[15:30:57.528][WslIntegrationAgent-Arch][Info   ] fatal error: unexpected signal during runtime execution
[15:30:57.530][WslIntegrationAgent-Arch][Info   ] [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f254a2fae84]
[15:30:57.530][WslIntegrationAgent-Arch][Info   ] runtime stack:
[15:30:57.530][WslIntegrationAgent-Arch][Info   ] runtime.throw(0xad26d4, 0x2a)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/panic.go:1116 +0x74
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] runtime.sigpanic()
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/signal_unix.go:679 +0x46e
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] goroutine 1 [syscall]:
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] runtime.cgocall(0xa133f0, 0xc0002efad0, 0xc0001aa810)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/cgocall.go:133 +0x5d fp=0xc0002efaa0 sp=0xc0002efa68 pc=0x404fed
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user._Cfunc_mygetgrnam_r(0xc0004d4037, 0xc000470280, 0x29cb080, 0x400, 0xc0001aa810, 0x0)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	_cgo_gotypes.go:123 +0x4f fp=0xc0002efad0 sp=0xc0002efaa0 pc=0x51c27f
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1.1(0xc0004d4037, 0x7, 0x7, 0xc000470280, 0xc000404ba0, 0xc0001aa810, 0x7f25731f0e98)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0xf5 fp=0xc0002efb20 sp=0xc0002efad0 pc=0x51e425
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1(0xccc3a0)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0x59 fp=0xc0002efb68 sp=0xc0002efb20 pc=0x51e4a9
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user.retryWithBuffer(0xc000404ba0, 0xc0002efc58, 0x6, 0xc0004d4037)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3d fp=0xc0002efbc0 sp=0xc0002efb68 pc=0x51d87d
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup(0xab91fa, 0x6, 0x0, 0x0, 0x0)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:141 +0x1a1 fp=0xc0002efcb0 sp=0xc0002efbc0 pc=0x51cf61
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] os/user.LookupGroup(...)
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/lookup.go:51
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] main.main()
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/go/src/github.com/docker/pinata/docker-desktop-proxy/main.go:92 +0x65e fp=0xc0002eff88 sp=0xc0002efcb0 pc=0xa109be
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] runtime.main()
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/proc.go:203 +0x202 fp=0xc0002effe0 sp=0xc0002eff88 pc=0x4379b2
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] runtime.goexit()
[15:30:57.531][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002effe8 sp=0xc0002effe0 pc=0x464d11
[15:30:57.579][WslIntegrationAgent-Arch][Info   ] 2020/08/24 15:30:57 Proxy error: exit status 2
```

### Information

  - Windows Version: 20H2 (19042.450)
  - Docker Desktop Version: 2.3.5.0 (47357)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. run ```sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Arch --docker-desktop-root /mnt/wsl/docker-desktop```

return same error:
```
[handz@HANDZ ~]$ sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Arch --docker-desktop-root /mnt/wsl/docker-desktop
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f617d0b4e84]

runtime stack:
runtime.throw(0xad26d4, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x74
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:679 +0x46e

goroutine 1 [syscall]:
runtime.cgocall(0xa133f0, 0xc00025fad0, 0xc0001180a8)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5d fp=0xc00025faa0 sp=0xc00025fa68 pc=0x404fed
os/user._Cfunc_mygetgrnam_r(0xc00010e3b7, 0xc0001242a0, 0x2dd3080, 0x400, 0xc0001180a8, 0x0)
        _cgo_gotypes.go:123 +0x4f fp=0xc00025fad0 sp=0xc00025faa0 pc=0x51c27f
os/user.lookupGroup.func1.1(0xc00010e3b7, 0x7, 0x7, 0xc0001242a0, 0xc00040e000, 0xc0001180a8, 0x7f61a5faa7d0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0xf5 fp=0xc00025fb20 sp=0xc00025fad0 pc=0x51e425
os/user.lookupGroup.func1(0xccc3a0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0x59 fp=0xc00025fb68 sp=0xc00025fb20 pc=0x51e4a9
os/user.retryWithBuffer(0xc00040e000, 0xc00025fc58, 0x6, 0xc00010e3b7)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3d fp=0xc00025fbc0 sp=0xc00025fb68 pc=0x51d87d
os/user.lookupGroup(0xab91fa, 0x6, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:141 +0x1a1 fp=0xc00025fcb0 sp=0xc00025fbc0 pc=0x51cf61
os/user.LookupGroup(...)
        /usr/local/go/src/os/user/lookup.go:51
main.main()
        /go/src/github.com/docker/pinata/docker-desktop-proxy/main.go:92 +0x65e fp=0xc00025ff88 sp=0xc00025fcb0 pc=0xa109be
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x202 fp=0xc00025ffe0 sp=0xc00025ff88 pc=0x4379b2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00025ffe8 sp=0xc00025ffe0 pc=0x464d11
```

  2. ...

**Comment by oleg-andreyev** [comment] 2020-08-24 15:42
Same. Diagnostic ID EE127EF8-44F2-4D2C-852D-31471231FA42/20200824153902

**Comment by grthr** [comment] 2020-08-24 15:46
Duplicate of #8183 ?

**Comment by oleg-andreyev** [comment] 2020-08-24 17:47
Looks like yes

**Comment by stephen-turner** [comment] 2020-09-08 08:03
Closing as dupe of #8183

**Closed by stephen-turner** 2020-09-08 08:03 UTC
Labels: version/2.3.5.0
