### ISSUE TITLE
Host route table is not correctly updated for linux containers.

### ISSUE THREAD

**Issue by glonnon** [docker/for-win#341] opened 2016-12-20 00:00 UTC
### Expected behavior
The docker for windows beta linux networking isn't working correctly.  There isn't a route entry to correctly route requests from the host to the container.
 
### Actual behavior

The routing table on the host is not correctly updated after starting up the Linux VM container.  Network requests to the container are unable to be routed correctly.  This works correctly for docker windows containers.

### Information
**How to reproduce:**
1.  Use docker-compose to start the nginx:latest container.  The docker-compose.yml is inlined below.
`docker-compose up`
2. ` curl <host ip address>:10080 ` # this works
3. Use "docker inspect" to find the 172 based IP address.  # this does not work
`curl 172.20.0.2:80`

Note: For windows, the call is correctly routed (172.21.236.243 ip address).  The route table has the correct route, while for the linux containers, the route table entry is missing, thus it's unable to route the 172 address to the linux container.

`docker version`
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true

Here's the route print output 

```
===========================================================================
Interface List
 11...00 15 5d 24 18 8f ......Hyper-V Virtual Ethernet Adapter
 37...00 15 5d 01 2a 06 ......Hyper-V Virtual Ethernet Adapter #2
  2...0a 00 27 00 00 02 ......VirtualBox Host-Only Ethernet Adapter
 13...d0 50 99 0c 12 af ......Intel(R) Ethernet Connection I217-V
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1     192.168.1.42     35
        10.0.75.0    255.255.255.0         On-link         10.0.75.1    271
        10.0.75.1  255.255.255.255         On-link         10.0.75.1    271
      10.0.75.255  255.255.255.255         On-link         10.0.75.1    271
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      169.254.0.0      255.255.0.0         On-link     169.254.96.14    281
    169.254.96.14  255.255.255.255         On-link     169.254.96.14    281
  169.254.255.255  255.255.255.255         On-link     169.254.96.14    281
     172.21.224.0    255.255.240.0         On-link      172.21.224.1    271
     172.21.224.1  255.255.255.255         On-link      172.21.224.1    271
   172.21.239.255  255.255.255.255         On-link      172.21.224.1    271
      192.168.1.0    255.255.255.0         On-link      192.168.1.42    291
     192.168.1.42  255.255.255.255         On-link      192.168.1.42    291
    192.168.1.255  255.255.255.255         On-link      192.168.1.42    291
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link     169.254.96.14    281
        224.0.0.0        240.0.0.0         On-link      172.21.224.1    271
        224.0.0.0        240.0.0.0         On-link      192.168.1.42    291
        224.0.0.0        240.0.0.0         On-link         10.0.75.1    271
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link     169.254.96.14    281
  255.255.255.255  255.255.255.255         On-link      172.21.224.1    271
  255.255.255.255  255.255.255.255         On-link      192.168.1.42    291
  255.255.255.255  255.255.255.255         On-link         10.0.75.1    271
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
  1    331 ::1/128                  On-link
  2    281 fe80::/64                On-link
 11    271 fe80::/64                On-link
 13    291 fe80::/64                On-link
 13    291 fe80::146:23cc:831a:5a7a/128
                                    On-link
  2    281 fe80::116e:7515:6b28:600e/128
                                    On-link
 11    271 fe80::317d:4675:5ff1:a15c/128
                                    On-link
  1    331 ff00::/8                 On-link
  2    281 ff00::/8                 On-link
 11    271 ff00::/8                 On-link
 13    291 ff00::/8                 On-link
 37    271 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None
```

--- docker-compose.yml file--
```
version: "2.1"
services:
    nginx:
        image: nginx:latest
        ports:
        - "10080:80"
```
--

**Comment by rneugeba** [comment] 2016-12-28 18:51
@glonnon what's your use case? Docker for Windows does not really provide the ability to access the internal network, but we do, as you describe, provide a mechanism to access the exposed container ports on localhost.

**Comment by rneugeba** [comment] 2016-12-29 17:01
Closing this issue as a duplicate of #221. Please see in particular the comments [here](https://github.com/docker/for-win/issues/221#issuecomment-269632645) and [here](https://github.com/docker/for-win/issues/221#issuecomment-269659422)

**Closed by rneugeba** 2016-12-29 17:01 UTC
Labels: area/network, status/0-more-info-needed
