### ISSUE TITLE
Docker Desktop for Windows does not prompt for credentials when sharing a drive

### ISSUE THREAD

**Issue by lerickson-control4** [docker/for-win#5703] opened 2020-02-05 12:47 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2517DD28-AB78-430C-AFBD-31F851DBF30D/20200205121537

### Expected behavior
I am attempting to share drive C so that I can mount volumes in a container from folders under my home directory.  I expect that when I check the box for sharing drive C in the File Sharing section fo the Settings view in DDfW that it should prompt me for my domain credentials.

### Actual behavior
I am not prompted for my domain credentials.   After clicking Apply & Restart, the box remains checked, but when I try to mount a volume using either docker-compose or docker run the volume is reported as being empty (e.g., files that exist in the host folder are not found inside the container.  

When I click Apply & Restart, it does not appear restart the docker runtime, if that is what is supposed to happen.  The DDfW screen flashes briefly, but the docker runtime does not report that it is restarting.

No credentials are stored for docker in the Windows Credential Manager.  I do not get prompted to share the folder on demand either.  My drive is encrypted, if that makes a difference. 

### Information

  - Windows Version: Windows 10 Pro (1903)
  - Docker Desktop Version: 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

On a Windows PC with an encrypted drive;
  1. Access Settings for DDfW
  2. Select File Sharing
  3. Check the box for drive C
  4. Click Apply & Restart 
  5. Observe that the docker runtime does not restart
  6. Observe that mounted volumes from folders on drive C appear empty

**Comment by mat007** [comment] 2020-02-05 13:13
This looks like a duplicate of #5567 so I’ll go ahead and close this one.
Feel free to re-open it if you think it’s a different issue.
Thanks!

**Closed by mat007** 2020-02-05 13:13 UTC
Labels: version/2.2.0.0

**Comment by lerickson-control4** [comment] 2020-02-05 15:54
This is not a duplicate of that issue.  In that case the user reported that all but one drive could be shared.  In my case I only have one drive and it cannot be shared. It never even asks for domain credentials.

**Comment by mat007** [comment] 2020-02-05 16:03
Starting with 2.2.0.0 there is no need for credentials for sharing a drive anymore.

We’re about to advertise a private release build which fixes a number of issues related to file sharing, which you may want to try.
I’ll post the link in this issue when it’s ready.

**Comment by lerickson-control4** [comment] 2020-02-05 17:06
i will look forward to it.  So you don't think drive encryption would be an issue?  I'm banging my head here.  Even the simplest volume mount attempt fails. I just assumed it was related to not getting prompted for creds.

**Comment by lerickson-control4** [comment] 2020-02-06 12:53
For the benefit of anyone who finds this. I found the reason the volumes could not be mounted.  I was running `docker-compose up` in a WSL shell.  Just guessing here, but I'd say the user in the shell is unknown to Windows so the request to mount the volume is silently rejected.  Switched to running `docker-compose up` in powershell and the app stood right up.  Obvious in hindsight.  Live and learn.
