### ISSUE TITLE
unknown shorthand flag: 'w' in -w

### ISSUE THREAD

**Issue by bpacJoseph** [docker/for-win#5553] opened 2020-01-22 21:06 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 00172240-0EDE-43B7-94E1-C30E33189464/20200122202638

### Expected behavior
able to specify working directory
-w exists

### Actual behavior
unable to specify working directory
-w does not exist

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible?
     - every time
  - Is the problem new?
     - since most recent update
  - Did the problem appear with an update?
     - yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
     - Using vscode containers
  - Windows Version:
     - 1903
  - Docker Desktop Version:
     - 2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
     - no

### Steps to reproduce the behavior

Use vscode dev container
https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-public-git-repository-in-an-isolated-container-volume will reproduce the issue

**Comment by trungutt** [comment] 2020-01-23 12:55
Could you be more specific about steps to reproduce the behavior please?

**Comment by Xachman** [comment] 2020-01-23 13:42
@trungutt  run `docker exec -w`  It dosen't work and it breaks vscodes remote container feature totally.

**Comment by mat007** [comment] 2020-01-23 14:32
I followed the link to the tutorial and started from the beginning until `You can now work with the repository source code in this isolated environment as you would if you had cloned the code locally.`

After it completed starting the containers I did:
```
PS C:\Users\mathi> docker ps -a
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED              STATUS              PORTS                      NAMES
84b5699079a0        vsc-vscode-remote-try-node-913ae3dfa049c7f1857ef72f98442bba   "/bin/sh -c 'echo Co…"   About a minute ago   Up About a minute   127.0.0.1:3000->3000/tcp   upbeat_dewdney
PS C:\Users\mathi> docker exec -w /var -it upbeat_dewdney sh
# pwd
/var
#
```

What are we missing?

**Comment by Xachman** [comment] 2020-01-23 14:44
@mat007  Well thats neat.  I was getting `unknown shorthand flag: 'w' in -w` in vscodes remote container.  Ok so its probably not related directly to 2.2.0.0.  I just installed 2.1.0.5 and I'm still getting that error.

**Comment by mat007** [comment] 2020-01-23 14:59
What does `docker version` tell you?

**Comment by Xachman** [comment] 2020-01-23 14:59
@mat007 
this is what im getting after the 2.2.0.0
Docker version 17.10.0-ce, build f4ffd25
```
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED              STATUS              PORTS                      NAMES
2f615d1d51b8        vsc-vscode-remote-try-node-9b31b2278d29960cb91d3103aae8546e   "/bin/sh -c 'echo ..."   About a minute ago   Up About a minute   127.0.0.1:3000->3000/tcp   silly_darwin
PS C:\vscode-remote-try-node> docker exec -w /var -it silly_darwin sh
unknown shorthand flag: 'w' in -w
See 'docker exec --help'.
PS C:\vscode-remote-try-node>
```

**Comment by mat007** [comment] 2020-01-23 15:03
17.10 means Oct 2017, mine shows:
```
PS C:\Users\mathi> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false
```
There is something odd with your path maybe?
Can you try
```
PS>  &'C:\Program Files\Docker\Docker\resources\bin\docker' version
```
?
That’s the one that comes with Docker Desktop.

**Comment by Xachman** [comment] 2020-01-23 15:05
@mat007  well looks like we have found our issue.

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false
```

when I run

`PS>  &'C:\Program Files\Docker\Docker\resources\bin\docker' version`

How did this happen?

**Comment by mat007** [comment] 2020-01-23 15:07
Hmm what does your path environment variable look like?
I remember us fixing a bug where we used to append our path to the front of the system paths list and as people (rightly) complained we moved it to the end of the paths list.
I don’t remember when this was but I could find out.

Out of curiosity, do you remember which Docker Desktop version you upgraded to 2.2.0.0 from?

**Comment by Xachman** [comment] 2020-01-23 15:13
User:

```
`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\tools\mysql\current\bin;C:\tools\go\bin;C:\MinGW\bin;C:\wxWidgets\github\lib\gcc_dll;C:\Program Files\SSHFS-Win\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\CMake\bin;C:\Users\ziron\AppData\Roaming\npm;C:\Program Files\nodejs;C:\tools\Cmder;;C:\Users\ziron\AppData\Local\hyper\app-3.0.2\resources\bin`

System:

C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\OpenSSH-Win64;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\vim\vim80;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\tools\go\bin;C:\tools\php72;C:\Program Files\Java\jdk1.8.0_152\bin;C:\Go\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\ZeroTier\One\
```

**Comment by mat007** [comment] 2020-01-23 15:15
Right, so it’s still at the front of the paths, maybe I just remember a ticket we in the end decided not to fix 😬 
Do you happen to have a `docker.exe` in `C:\ProgramData\DockerDesktop\version-bin`?

**Comment by mat007** [comment] 2020-01-23 15:16
Well, actually that’ll be quicker:
```
PS > where.exe docker
C:\Program Files\Docker\Docker\Resources\bin\docker.exe
```

**Comment by Xachman** [comment] 2020-01-23 15:19
`C:\ProgramData\chocolatey\bin\docker.exe`

cant even think of why it would be in there

**Comment by Xachman** [comment] 2020-01-23 15:20
Oh I'm sure what I did was installed with chocolatey then did all the updates with the gui popups.

**Comment by Xachman** [comment] 2020-01-23 15:25
moving the docker exe out of `C:\ProgramData\chocolatey\bin\` fixed the issue for me

**Comment by mat007** [comment] 2020-01-23 15:57
@Xachman good to know! That might be worth reporting to Chocolatey, maybe?
@bpacJoseph would issue have the same root cause by any chance?

**Comment by bpacJoseph** [comment] 2020-01-23 19:44
> @mat007 Well thats neat. I was getting `unknown shorthand flag: 'w' in -w` in vscodes remote container. Ok so its probably not related directly to 2.2.0.0. I just installed 2.1.0.5 and I'm still getting that error.

I went back to docker 2.1.0.5, restarted my computer and everything worked.

> @Xachman good to know! That might be worth reporting to Chocolatey, maybe?
> @bpacJoseph would issue have the same root cause by any chance?

I did not install docker using Chocolatey

```
PS C:\WINDOWS\system32> .\where.exe docker
C:\Program Files\Docker\Docker\Resources\bin\docker.exe
```

Additional version information

Previous version before error was 2.1.0.5

```
PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


-----------------------------------------------------------

PS C:\WINDOWS\system32> &'C:\Program Files\Docker\Docker\resources\bin\docker' version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by mat007** [comment] 2020-01-24 05:40
@bpacJoseph the two outputs are identical.

Can you tell us exactly the command line you’re typing and the error you get?

**Comment by bpacJoseph** [comment] 2020-01-26 19:57
Command generated by vscode (same one as was failing before)
`docker exec -w /root/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0 -u root -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 57b27ee7b8265c9106c038eb357782ed5ef737d9dc392d942bae1e01b8622f4b /root/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/server.sh --disable-user-env-probe --port 0`

I redownloaded and installed docker desktop 2.2.0.0 10 minutes ago.
2.2.0.0 (42247) was installed.
-w works now.

It might have been a bad installation the first time.

**Comment by stephen-turner** [comment] 2020-02-11 13:36
It looks like this is now sorted, so closing the ticket.

**Closed by stephen-turner** 2020-02-11 13:36 UTC
Labels: status/0-triage, version/2.2.0.0
