### ISSUE TITLE
Docker auto updated and now nothing works

### ISSUE THREAD

**Issue by Oylex** [docker/for-win#10607] opened 2021-03-10 16:27 UTC
When I try docker-compose build, it returns:

failed to get console mode for stdout: The handle is invalid.

and it seems to work, but I don't feel progress: [+] Building 460.6s (9/22)   (the seconds increase forever...)

I also get errors about all my environment variables not being found.

and ports must be number or objects, but they worked all fine yesterday.

**Comment by stephen-turner** [comment] 2021-03-10 18:24
Closing as dupe of docker/compose#8186

**Closed by stephen-turner** 2021-03-10 18:24 UTC
