### ISSUE TITLE
Moby memory won't exceed 6570MB

### ISSUE THREAD

**Issue by smrau** [docker/for-win#384] opened 2017-01-13 11:15 UTC
### Expected behavior

I want to allocate 8GB or more memory to run a large container.

### Actual behavior

Any setting above 6570MB is ignored by Hyper-V. There is more than 4GB of RAM still available after Docker starts.

### Information

  - Diagnostic ID: 59172D14-6E15-4C6E-AAB0-9F43ECD1DE17/2017-01-13_21-50-14
  - Windows 10 Enterprise, version 1607, 16GB RAM.

Looking at the Docker logs, the correct CPU and memory parameters are being sent to Hyper-V.

### Steps to reproduce the behavior

  1. Set memory to a value such as 4096MB. Apply. Hyper-V manager shows correct amount of memory.
  2. Set memory to a value above 6570MB (eg, 7424MB). Apply. Hyper-V shows 6570MB.

I hope this is enough information ... I'm new at this. Thanks.

**Comment by rneugeba** [comment] 2017-01-13 13:10
Thanks for your report. Unfortunately, I can't reproduce this (see attached screen shot and also:
```
PS > (get-vm mobylinuxvm).MemoryAssigned
12348030976
```
If I then reduce the memory and start another VM (with 8GB) and try to increase the memory of the DockerForWindows VM I get and error (screenshot also attached). All this is pretty much as expected...I'm doing this on Windows 10 Pro (not Enterprise) but that shouldn't matter.

Looking at your logs I see a VM is successfully created and booted with 12800MB several times, though we don't seem to collect . The last boot in the logs suggest it was configured with 7424MB and if I look at the diagnostics I see `MemoryAssigned : 6889144320` which is odd.

In the logs i see several:
```
MobyLinuxVM' failed to modify device 'Memory'. (Virtual machine ID 51254DB8-9203-4050-A33D-942CBC828CF3)
[...]
Changing memory size of running virtual machine 'MobyLinuxVM' failed. Please make sure the guest operating system has fully booted and try again.
```
but not as manat as there where restarts with different memory settings in the logs.

@simonferquel any idea of what might be going on?

![screen shot 2017-01-13 at 11 36 23](https://cloud.githubusercontent.com/assets/3338098/21928899/5f16ed50-d985-11e6-8bf7-b7cd293a6017.png)

![screen shot 2017-01-13 at 13 01 14](https://cloud.githubusercontent.com/assets/3338098/21930949/aa4eec86-d990-11e6-8edf-44fa3c099075.png)

**Comment by simonferquel** [comment] 2017-01-13 13:30
The error seem to indicate that the VM was manually started from Hyper-V manager and that Docker for Windows did not see that (and tried to change memory settings thinking that the VM was stopped). For the reported allocated memory clamped at 6GB I have unfortunately no clue. Can you try to stop docker for windows and manually create an HyperV VM with 12GB (statically allocated) and see if you get the same result ?

**Comment by smrau** [comment] 2017-01-13 22:08
HI guys

 

Thanks for your feedback.

 

Each time I restart Docker, the VM restarts.

 

Other experiments I’ve done:

 

-          Shut down Docker, change the memory setting in Hyper-V, manually restart the VM, and it started fine. I then restarted Docker, which restarted the VM with the clamped setting.

-          Start Docker, manually shutdown the VM, increase the memory, restart, which worked. Except the client could not communicate with the daemon.

-          Restart Docker, then try to resize the memory on the running VM. Failed with “memory device” error.

 

Thanks for any help you are able to provide.

 

Cheers,

Steve.

**Comment by rneugeba** [comment] 2017-01-13 22:43
The VM stops by design when you quit the app.

You should not need to mess with the VM in Hyper-V manager (it's best if you don't at all). Starting the VM in Hyper-V manager when the app is not running does not work as the VM depends on some services running on the host. So, if the app starts it will restart the VM.

So it's best to try to focus on why setting the memory via the Docker for Windows Settings panel is not working for you

**Comment by smrau** [comment] 2017-01-15 06:11
Thanks Rolf. I agree. The issue was a show-stopper for me, so I’ve rolled back to the latest stable version and all works well. (I don’t need Windows container support for now.)

**Comment by rneugeba** [comment] 2017-01-15 12:08
@smrau glad it is working for you on stable. Very odd that it works with stable but not with the beta. Since we can't reproduce it and I haven't seen any other users reporting it, I'm closing this issue for now.

Please note that we are going to update the stable channel to the Beta code base once docker 1.13 is released. You may want to keep the 1.12.6 stable installer around just in case the update breaks things for you

**Closed by rneugeba** 2017-01-15 12:08 UTC
Labels: area/hyper-v, status/0-triage

**Comment by smrau** [comment] 2017-01-16 09:20
Hi Rolf. Thanks for the heads-up on the next release.

 

One thought that may explain my symptoms: I started with the (previous) stable release, then decided to try the beta. I missed the advice that I should uninstall the existing installation, and installed the beta on top of stable. Probably a coincidence.

 

Thanks again for your help.

 

Steve.
