### ISSUE TITLE
Access Apache installed inside Ubuntu 14.04 container.

### ISSUE THREAD

**Issue by adrpor** [docker/for-win#519] opened 2017-02-23 08:55 UTC
### Expected behavior
Access Apache installed inside Ubuntu 14.04 container (installed on MobyLinuxVM - with o IP) on Windows 10

### Actual behavior
Can't access default Apache on Ubuntu container on 127.0.0.1

### Information
A diagnostic was uploaded with id: CD9DB034-FCCB-4C25-9502-C6F276E0F13E/2017-02-23_09-31-09
I'm using Docker (stable version) for Windows 
Get-NetNat doesn't return any values

### Steps to reproduce the behavior

  1. docker run -it ubuntu:trusty /bin/bash
  2. docker exec -it <container> bash
  3. Install apache  -------------  
     sudo apt-get update
     sudo apt-get install apache2

      http://your_server_IP_address (127.0.0.1) is not available.

I tried with to add route route add 172.17.0.0 mask 255.255.0.0 127.0.0.1 -p

http://www.dotnetcatch.com/2016/11/11/access-a-docker-container-from-the-docker-for-windows-host/

I'm trying to use my  localhost, because this in the only way I can mount volumes for ununtu.

I tried to create new docker-machine with new ip (using external switch), buy even volume the was mounted the files were not sync - no errors with this command:
docker run -v //c/data:/var/www ubuntucontainer

Syncronisation works using on main MobyLinuxVM machine only.

PS I had no issues with Drupal container on MobyLinuxVM before. The installation was completed on 127.0.0.1 without issues. I have turned off Drupal container to run new one with ubuntu.

```
docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "4ee4e6546498bd5d72b4ad467d382649c4c2830c495c3bf9518626b4fe1c2756",
        "Created": "2017-02-23T07:06:42.8995629Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "44ecf7bdc00ac833c9f0863c41ad8b70e7a5f99a77596d6dc3a51cc30f060c59": {
                "Name": "serene_jones",
                "EndpointID": "c26b2f8edf8ac2bd1b375639f74b02278ec26083509e3f9ddbc12f9bf95a0139",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

```

Is it normal that MobyLinuxVM has no IP in HyperV? 
Should I bother with adding routes in Windows 10?
What the reason why only -volumes for files works on MobyLinuxVM . The other machines do not sync files, even there are no errors.

**Comment by dgageot** [comment] 2017-02-23 09:35
@adrpor if you want to access the apache that's in a container, from the host, you have to publish port 80. eg. `docker run -it ubuntu:trusty -p 80:80 /bin/bash`
I'm going to close this issue as it's not a Docker for Windows issue

**Comment by adrpor** [comment] 2017-02-23 10:04
> PS C:\Windows\system32> docker run -it ubuntu:trusty -p 8080:80 /bin/bash
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "e
xec: \"-p\": executable file not found in $PATH".

**Comment by adrpor** [comment] 2017-02-23 10:06
I'm not able to run -p 80:80  due to Error starting userland proxy: Bind for 0.0.0.0:80 failed: port is already allocated.

port 8080:80 is returning the error above

**Comment by dgageot** [comment] 2017-02-23 10:15
@adrpor Sorry My command is in the wrong order. It should be `docker run -it -p 80:80 ubuntu:trusty /bin/bash`. If port `80` is already used, it means another container is already publishing this port or something is using this port on the host. What's the result of `docker run -it -p 8888:80 ubuntu:trusty /bin/bash`?

**Comment by adrpor** [comment] 2017-02-23 11:10
Thank you, no issues as below 👍 :

![localhost](https://cloud.githubusercontent.com/assets/25367080/23256256/025e66c4-f9bf-11e6-8ea0-38ac88da5da2.png)

However http://127.0.0.1/ is returns completely empty html doc. (not apache)

`<head><link rel="alternate stylesheet" type="text/css" href="resource://gre-resources/plaintext.css" title="Zawijaj długie wiersze"></head><body><pre></pre></body>`

I'm wonder if need "fix" the Apache (add port there), or is there something else I need to do in Windows.

**Comment by adrpor** [comment] 2017-02-23 12:51
I'm glad that the problem is fixed.  

PS. Can we find out why port 80 was already allocated when when running ubuntu container?

**Comment by dgageot** [comment] 2017-02-23 14:28
@adrpor It looks like Skype is using port 80 on your machine. I'm glad the issue is fixed for you. I'm closing the issue

**Closed by dgageot** 2017-02-23 14:28 UTC
Labels: status/0-wont-fix
