### ISSUE TITLE
Docker Desktop - Windows Hypervisor is not present

### ISSUE THREAD

**Issue by gigi-beridze** [docker/for-win#13706] opened 2023-09-27 14:11 UTC
### Description

I have problem about "Docker-Desktop". you can see problem in the image. I am not good with windows, or if i can install docker cli in windows help me this way. Thanks For Helping!
![image](https://github.com/docker/for-win/assets/82542634/091bc8ca-8c34-4067-bc69-3a885b5194d2)

### Reproduce

1. i am trying just open docker and i have this err

### docker version

```bash
new
```

### docker info

```bash
info
```

### Diagnostics ID

1

**Comment by afshaarahmed** [comment] 2023-09-27 22:51
latest version of docker its not running on aws windows server core 2022 gives repeatedly error wsl --shutdown, from cmd trying again and again but not working. docker engine stopped.

**Comment by lorenrh** [comment] 2023-09-29 09:02
Hello!

This seems to be a problem with your configuration, not Docker Desktop per se. You can follow the guides in https://docs.docker.com/desktop/troubleshoot/topics/#virtualization. 

If after this the issue persists, please open a fresh ticket, and steps on how to reproduce it. For now I'm closing this ticket.

**Closed as completed by lorenrh** 2023-09-29 09:02 UTC
Labels: area/hyper-v, status/triage

**Comment by AldoSan666** [comment] 2024-08-14 15:34
From Docker Forums:

"Run bcdedit /set hypervisorlaunchtype auto as Administrator in cmd.

This worked for me, ensure the hyper-v is enabled in your BIOS aswell."

This worked for me, you need to reboot after the bcdedit set up.
