### ISSUE TITLE
Cannot bind to port 53

### ISSUE THREAD

**Issue by andersnordh** [docker/for-win#10605] opened 2021-03-10 13:59 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After installing Docker Desktop 3.1.0 and also after upgrading to 3.2.1, when starting it binds to 0.0.0.0:53 making it impossible to start at DNS in Docker since it reports that :53 is already bound to interface. 

### Expected behavior
Should not bind to 0.0.0.0:53.

### Information

  - Windows Version: Windows 10, OS build 19042.844.
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-03-10 14:28
Closing as dupe of #10601.

**Closed by stephen-turner** 2021-03-10 14:28 UTC
