### ISSUE TITLE
Cannot use .. inside path for mounting volumes

### ISSUE THREAD

**Issue by ksawerykarwacki** [docker/for-win#5750] opened 2020-02-12 15:57 UTC
Docker Desktop 2.2.0.3

When mounting volumes my team uses .. to mount directory above current directory. Paths for volumes are built based on current directory inside script. Output of this script looks like this:

`docker run -d -v  C:\Users\ksawery.karwacki\svn\rre\..:/home/test alpine sleep infinite
`
Since upgrade to 2.2.0.3 this call results in error:

`C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: file does not exist.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.`

**Comment by stephen-turner** [comment] 2020-02-12 17:14
Closing as dupe of #5735

**Closed by stephen-turner** 2020-02-12 17:14 UTC
