### ISSUE TITLE
Hyper-V Initialisation Fault - Binary stream '0' does not contain a valid BinaryHeader

### ISSUE THREAD

**Issue by julienb243** [docker/for-win#2269] opened 2018-07-25 21:25 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 413D537B-12AB-441F-AF26-0E8B4AA26BF8/20180726071617

### Expected behavior
Docker for Win app starts either with Windows or Linux container mode.
### Actual behavior
When prompted and confirmed to activate Hyper-V shortly after It fails with the error:
```
Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.InstallFeatures(Feature[] features) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 111
   at Docker.Notifications.BackendInstallFeatureExceptionReplier.<>c__DisplayClass10_0.<AskToUser>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Notifications\BackendInstallFeatureExceptionReplier.cs:line 103
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
### Information

  - Windows Version:  Win 10 Ent v1703 build 15063.1155
  - Docker for Windows Version: 18.06.0-ce-win70 (19075)

### Steps to reproduce the behavior

  1. Install DFW version (as above) and attempt to start

**Comment by gtardif** [comment] 2018-07-25 21:35
Closing as a duplicate of https://github.com/docker/for-win/issues/2262.
As a workaround, you can enable "Hyper-V" and "containers" features in "Windows Features" (search for "Turn Windows features on"), that will need a computer restart, then start Docker for Windows

**Closed by gtardif** 2018-07-25 21:35 UTC
