### ISSUE TITLE
Crash at startup if WSL `$HOME` = Windows `%USERPROFILE%`

### ISSUE THREAD

**Issue by jeritiana** [docker/for-win#11668] opened 2021-07-13 14:46 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 011FF991-2BF0-470C-B32F-969A36D91622/20210713121758

### Actual behavior

Stumbled upon this issue when upgraded (and subsequently uninstalled and reinstalled) versions 3.5.1 then 3.5.2.

On my machine, WSL2 home directory is the same as the Windows 10 user's profile folder i.e.
* Windows 10 host: `%USERPROFILE%=C:\Users\<username>`
* Ubuntu WSL2: `$HOME=/mnt/c/Users/<username>`

#### TL;DR

Docker Desktop wont start and complains `.docker\contexts\meta\fe9c6...\meta.json` cannot be accessed.
`%USERPROFILE%\.docker\contexts` is actually a symlink to itself i.e. `contexts -> /mnt/c/Users/<username>/.docker/contexts`: no `meta.json` would ever be accessed that way.

#### Workaround 1
Manually remove `%USERPROFILE%\.docker\contexts` every time before starting Docker Desktop.

#### Workaround 2
Set `USERPROFILE` to a differenet value in the context starting Docker Desktop. 
E.g.
```
@echo off
SET USERPROFILE=C:\Users\<username>\.docker\HOME
"C:\Program Files\Docker\Docker\Docker Desktop.exe"
```

The directory `C:\Users\<username>\.docker\HOME\.docker\contexts` would then be created and the symlink `/home/<username>/.docker/contexts -> /mnt/c/Users/<username>/.docker/HOME/.docker/contexts` would be valid.

#### More details

It begins from the UI. Docker Desktop wont start and issues *"It looks like there is an error with Docker Desktop, restart it to fix it"*. 

If I wait a couple of minutes, Docker Desktop automatically stops, then another error appears in a pop-up window:
```
System.Threading.Tasks.TaskCanceledException:
Cancellation token triggered before we finished reading from the stream.
```

Restarting Docker Desktop leads to the same behavior.

When looking at the log, the most suspicious messages are:
```
[21:43:17.220][IPCClient         ][Info   ] (84bb0c71) b16f0a49-GoBackendClient-CSharp C->S GET /ping
[21:43:17.223][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
... and later...
[21:43:35.049][ApiProxy          ][Error  ] Auto restarting process
[21:43:35.049][ApiProxy          ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.proxy.exe -windowsPipe=\\.\pipe\docker_engine_windows -wsl-distro docker-desktop  -dockerExe "C:\Program Files\Docker\Docker\resources\bin\docker.exe"  -inject-hosts=true
...
[21:43:35.127][ApiProxy          ][Error  ] Process died
```

It appears that there is a specific log file for the `ApiProxy` in `%APPDATA%\Docker\log\host\com.docker.proxy.exe.log`.  Inside, there was:
```
time="2021-07-13T16:09:36+03:00" level=fatal msg="ensuring desktop context: querying desktop-linux docker context: open C:\\Users\\user\\.docker\\contexts\\meta\\fe9c6...\\meta.json: The file cannot be accessed by the system."
main.main()
	win/backend/cmd/com.docker.proxy/main.go:65 +0x545
```

Indeed the `.docker` directory (in the HOME directory) looks like this:
```
~/.docker$ ls -l
total 0
drwxrwxrwx 1 user user 512 Apr 14 08:51 application-template
-rwxrwxrwx 1 user user  34 Jul 13 16:37 config.json
lrwxrwxrwx 1 user user  35 Jul 13 16:37 contexts -> /mnt/c/Users/user/.docker/contexts
-rwxrwxrwx 1 user user 252 Jul 13 16:05 daemon.json
drwxrwxrwx 1 user user 512 Jun 27 21:52 devenvironments
lrwxrwxrwx 1 user user  40 Jun 27 21:52 features.json -> /mnt/c/Users/user/.docker/features.json
drwxrwxrwx 1 user user 512 Apr  8 16:52 run
drwxrwxrwx 1 user user 512 Feb  4 12:28 scan
```

`contexts` and `features.json` are symlinks to themselves.

Now, I removed `contexts` especially and the following happens:
* Docker Desktop starts successfully \o/ but...
* I can see briefly in the Windows Explorer that a directory named `contexts` is created: this would presumably contain the required `meta.json` file
* This directory is then somehow removed and the symlink `contexts` is created.

Thus, manually removing the `.docker\contexts` symlink before starting Docker Desktop allows this latter to start, but, meh, this is weird.

I did a little more digging and it appears that a symlink is always created at Docker Desktop startup: "`$HOME/.docker/contexts`" `->` "where is `%USERPROFILE%` mounted`/.docker/contexts`". Whichever `contexts` file is overridden (actual directory, symlink to another directory, junction point to another directory) with this symlink, unless it is already an actual symlink to the required target.

Altering the `USERPROFILE` value before starting Docker Desktop also allows it to start.

For `.docker\features.json`, it alters some Docker Compose commands (e.g.: `docker-compose --version`) if it is an empty file. If the symlink does not resolve or is an empty actual JSON file `{}`, no apparent effects in my tests.

####

### Expected behavior

Docker Desktop starts normally.

### Information

  - Windows Version: 20H2 (Build 19042. 1083) Windows 10 Pro
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Nope

### Steps to reproduce the behavior

  1. Have a WSL2 distribution and enable integration within this distribution
  2. Inside WSL2: edit `/etc/passwd` and set the user's `HOME` directory to the Windows `%USERPROFILE%` value
     E.g.
```diff
-<wsl_user>:x:1000:1000:,,,:/home/<wsl_user>:/bin/bash
+<wsl_user>:x:1000:1000:,,,:/mnt/c/Users/<windows_user>:/bin/bash
```
  3. Exit and restart WSL
  4. Launch Docker Desktop: fails and issues *"It looks like there is an error with Docker Desktop, restart it to fix it"*
    If it succeeds the first time, stop and restart Docker Desktop again.
  5. Stop Docker Desktop
  6. Manually remove `%USERPROFILE%\.docker\contexts`
  7. Launch Docker Desktop again: succeeds

**Comment by jeritiana** [comment] 2021-07-13 14:49
This could be related to #7041.

**Comment by joel-schaal** [comment] 2021-07-19 16:30
Hey, thanks for opening this detailed issue and providing workarounds.

I have tried both and while Docker seems to work well, it seems Docker Compose has trouble to keep up (tested with both workarounds) :
```
C:\Users\me>docker-compose
Failed to load docker configuration: open C:\Users\me\.docker\features.json: The file cannot be accessed by the system.
```
I tried to restart `LxssManager`, but it was in vain.

Do you know by any chance how I can update where Docker Compose looks for its data, so that it rather checks in `C:\Users\me\.docker\HOME\.docker`  ?

**Comment by Koriit** [comment] 2021-07-19 16:40
Hello, today I faced the same issue with:
```
System.Threading.Tasks.TaskCanceledException:
Cancellation token triggered before we finished reading from the stream.
```
I confirm that the Workaround 1 with removing `.docker\contexts` does indeed work. Thank you!

**Comment by jeritiana** [comment] 2021-07-19 17:38
@joel-schaal have you just tried creating an empty JSON file in `C:\Users\me\.docker\features.json`?
i.e.
```
{}
```

**Comment by joel-schaal** [comment] 2021-07-19 20:57
Duh... 🤦 
Indeed, I removed the unreadable file and created an empty one and everything now works just fine.

Thanks again !

**Comment by hiepxanh** [comment] 2021-07-31 07:40
look like it have serious problem with context, I can enable open the new context file after remove the old one:
![image](https://user-images.githubusercontent.com/16970990/127732735-bdafc671-e327-406d-8dd9-6beac58d12ce.png)

but unable open the old one, it must be the cause of problem?
![image](https://user-images.githubusercontent.com/16970990/127732761-b2a7f840-1cab-4d1e-8116-4d9ec2221ce0.png)

**Comment by djs55** [comment] 2021-08-01 17:39
@jeritiana thanks for the detailed report. I have an experimental build which should help with this problem: https://desktop-stage.docker.com/win/stable/amd64/67109/Docker%20Desktop%20Installer.exe . Let me know if you get a chance to try it. If it doesn't work, could you upload a fresh set of diagnostics and quote the ID here? Thanks!

**Comment by ymesika** [comment] 2021-08-03 08:13
@djs55 I had the same WSL custom home directory configuration reported by this issue and the experimental build fixed it for me. Thanks.

**Comment by maldago** [comment] 2021-08-03 21:06
@djs55 not sure if it is related but since using the above release I am seeing an error with the docker desktop dashboard and cannot update settings 

```
[21:58:38.931][IPCServer         ][Info   ] (23073165) 21560a93-CSharpAPI S<-C axios/0.21.1 GET /settings
[21:58:38.931][IPCServer         ][Error  ] (23073165) 21560a93-CSharpAPI S->C axios/0.21.1 GET /settings (0ms): Internal Server Error
```

**Comment by ulyssessouza** [comment] 2021-08-11 16:56
Hello. Docker Desktop 3.6.0 has been released containing a fix for this issue.
So I'm closing the ticket. Please feel free to reopen if the problem persists.

**Closed by ulyssessouza** 2021-08-11 16:56 UTC
Labels: version/3.5.1, version/3.5.2

**Comment by joel-schaal** [comment] 2021-08-11 18:40
Thanks a lot, I can now use Docker Desktop again !

**Comment by jeritiana** [comment] 2021-08-17 13:20
Thank you all. Both experimental build from @djs55 and release 3.6.0 fixed the issue after a full reinstall + removing the `.docker` directory.
