### ISSUE TITLE
docker doesn't start after Windows 10 build : 20175

### ISSUE THREAD

**Issue by survivant** [docker/for-win#7847] opened 2020-07-27 20:28 UTC
Version: 2.3.3.2 (46784)
Channel: edge
Sha1: a03f51183ae5c3a98a5c8f2bb48f4a881e803158
Started on: 2020/07/27 16:18:06.396
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 20175
BuildLabName: 20175.1000.amd64fre.rs_prerelease.200717-1349
File: C:\Users\patate\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:18:06.507][GUI               ][Info   ] Starting...
[16:18:06.651][ComponentVersions ][Info   ] Edition community
[16:18:06.657][ComponentVersions ][Info   ] Edition community
[16:18:08.468][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[16:18:08.547][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[16:18:08.550][SegmentApi        ][Info   ] Usage statistic: Identify
[16:18:08.857][SegmentApi        ][Info   ] Usage statistic: appLaunched
[16:18:09.408][ApplicationTemplatesTracking][Info   ] Cannot list templates
[16:18:09.409][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[16:18:09.410][SegmentApi        ][Info   ] Usage statistic: heartbeat
[16:18:10.025][LoggingMessageHandler][Info   ] [8cb506e1] <BackendAPIClient start> GET http://backend/version
[16:18:10.074][LoggingMessageHandler][Info   ] [8cb506e1] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 47ms)
[16:18:10.220][LoggingMessageHandler][Info   ] [e3b38d7e] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[16:18:10.231][LoggingMessageHandler][Info   ] [e3b38d7e] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 10ms)
[16:18:10.237][LoggingMessageHandler][Info   ] [fe341b57] <BackendAPIClient start> POST http://backend/migrate/app
[16:18:10.246][LoggingMessageHandler][Info   ] [fe341b57] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 8ms)
[16:18:10.251][Engines           ][Debug  ] Starting
[16:18:10.287][LoggingMessageHandler][Info   ] [7c6113bb] <BackendAPIClient start> POST http://backend/versionpack/enable
[16:18:10.333][LoggingMessageHandler][Info   ] [7c6113bb] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 45ms)
[16:18:10.435][LoggingMessageHandler][Info   ] [e1928b28] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[16:18:10.447][LoggingMessageHandler][Info   ] [e1928b28] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 11ms)
[16:18:10.471][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[16:18:10.477][GoBackendProcess  ][Info   ] Started
[16:18:10.486][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[16:18:10.486][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[16:18:10.492][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[16:18:10.498][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1595881090}
[16:18:10.499][SystrayNotifications][Info   ] Docker is starting
[16:18:10.502][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[16:18:10.507][LoggingMessageHandler][Info   ] [331ccf7c] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:18:10.701][WSL2Provisioning  ][Info   ] Checking docker-desktop
[16:18:10.706][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro
[16:18:10.710][LoggingMessageHandler][Info   ] [331ccf7c] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 203ms)
[16:18:11.531][LoggingMessageHandler][Info   ] [efd89acd] <Server start> GET http://unix/versions
[16:18:11.670][LoggingMessageHandler][Info   ] [efd89acd] <Server end> GET http://unix/versions -> 200 OK (took 139ms)
[16:18:11.726][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[16:18:11.745][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[16:18:11.745][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[16:18:11.745][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[16:18:11.772][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[16:18:11.772][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[16:18:11.772][GoBackendProcess  ][Info   ] enabling filesystem caching
[16:18:11.772][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[16:18:11.772][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[16:18:11.772][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[16:18:11.772][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[16:18:11.772][GoBackendProcess  ][Info   ] using mfsymlinks
[16:18:13.547][Updater           ][Info   ] Check for update process exited with 4294967295
[16:19:10.976][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le d鬡i de lop鲡tion a expir鬠car aucune r鰯nse na 鴩 re絥 de lordinateur virtuel ou du conteneur.

 stderr: 
[16:19:10.981][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[16:19:11.080][LinuxWSL2Engine   ][Info   ] Stopping engine
[16:19:11.164][LoggingMessageHandler][Info   ] [48871f28] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[16:19:11.818][LoggingMessageHandler][Info   ] [48871f28] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 654ms)
[16:19:12.404][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[16:19:12.404][LoggingMessageHandler][Info   ] [1fe0dd5b] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:19:12.567][WSL2Provisioning  ][Info   ] Checking docker-desktop
[16:19:12.567][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro
[16:19:12.568][LoggingMessageHandler][Info   ] [1fe0dd5b] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 164ms)
[16:20:12.852][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le d鬡i de lop鲡tion a expir鬠car aucune r鰯nse na 鴩 re絥 de lordinateur virtuel ou du conteneur.

 stderr: 
[16:20:12.853][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[16:20:12.955][LinuxWSL2Engine   ][Info   ] Stopping engine
[16:20:13.030][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[16:20:13.030][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[16:20:13.030][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[16:20:13.031][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1595881213}
[16:20:13.038][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le d鬡i de lop鲡tion a expir鬠car aucune r鰯nse na 鴩 re絥 de lordinateur virtuel ou du conteneur.

 stderr: 
   ࠄocker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:ligne 142
   ࠄocker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:ligne 169
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:ligne 78
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:ligne 99
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:ligne 29
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 67
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠄocker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 92
[16:20:13.056][GUI               ][Info   ] Sending Bugsnag report 5ef4cbf1-da7d-4749-857f-8620ad06fcd4...
[16:20:13.203][GUI               ][Info   ] Bugsnag report 5ef4cbf1-da7d-4749-857f-8620ad06fcd4 sent
[16:20:13.204][SegmentApi        ][Info   ] Usage statistic: eventCrash
[16:20:13.208][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[16:20:13.361][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[16:20:13.362][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[16:20:14.616][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\patate\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Le d鬡i de lop鲡tion a expir鬠car aucune r鰯nse na 鴩 re絥 de lordinateur virtuel ou du conteneur.

 stderr: 
   ࠄocker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:ligne 142
   ࠄocker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:ligne 169
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:ligne 78
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:ligne 99
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:ligne 29
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 67
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠄocker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:ligne 92
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:ligne 69
--- Fin de la trace de la pile ࠰artir de l'emplacement pr飩dent au niveau duquel l'exception a 鴩 lev饠---
   ࠓystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ࠓystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ࠄocker.Engines.Engines.<StartAsync>d__23.MoveNext() dans C:\workspaces\edge-2.3.3.2\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:ligne 108)
[16:23:28.974][Diagnostics       ][Info   ] Uploading diagnostics DBEA6031-040B-4FB3-87CA-41EBCC5B2321/20200727202013
[16:23:30.187][Diagnostics       ][Info   ] Uploaded succesfully diagnostics DBEA6031-040B-4FB3-87CA-41EBCC5B2321/20200727202013
[16:24:12.181][ErrorReportWindow ][Info   ] Open logs

**Comment by zyazhb** [comment] 2020-07-28 02:19
**Same issue**

**Comment by stephen-turner** [comment] 2020-07-28 07:56
Probably a dupe of #7808.

**Closed by stephen-turner** 2020-07-28 07:56 UTC
Labels: version/2.3.3.2

**Comment by metcalfc** [comment] 2020-07-31 21:44
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
