### ISSUE TITLE
Volume is empty after computer restart

### ISSUE THREAD

**Issue by sazuna** [docker/for-win#938] opened 2017-07-19 21:47 UTC
### Expected behavior
Volume contains data after computer restart.

### Actual behavior
After restart, the volume is empty. After manually restarting the container, the volume contains the data as expected.

### Information

  - Diagnostic ID:  ED0FA56B-BF8D-4477-AAE2-15D50F4BBFDF/2017-07-19_18-40-42.
  -  Windows 10 Version 1703, Build 15063.483

### Steps to reproduce the behavior

First, I create the directory F:\test with a folder named "folder" and a file named "file.txt".

Using the following compose file:

```yml
version: '3'
services:
  test-service:
    container_name: test-container
    image: nginx:1.13
    volumes:
      - F:\test:/test
    restart: always
```

I bring it up with `docker-compose up`. In another console I count the number of files on the volume:

```
λ docker-compose exec test-service ls /test -1 | wc -l     
2
```

Which is expected and working properly. Then I gracefully stop the container and restart the computer.

```
λ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                NAMES
bab6e5aab15e        nginx:1.13              "nginx -g 'daemon ..."   5 minutes ago       Up About a minute   80/tcp           test-container
```

The container restarted with docker as expected, but then I again count the files in the volume:

```
λ docker-compose exec test-service ls /test -1 | wc -l     
0
```
The volume is empty after the restart! Restarting the container with `docker-compose restart`, fixes the problem, and the 2 results show up as expected.
I used nginx as image because it's a easy example, but it also happens with python:3.

Is this some expected behavior that I'm overlooking?

**Comment by jasonterando** [comment] 2017-07-27 15:47
If you have Docker auto-starting (Settings, General, Start Docker when you log in) you might try turning that off and starting off Docker manually.  I've ran into similar issues with Docker having issues mounting volumes too quickly - I think it's something they are addressing on Edge channel

**Comment by sazuna** [comment] 2017-07-27 17:57
Just tried it. Disabled start on login, reboot and manually started docker. The volume appears empty and it's fixed after manual container restart.
So it's not related to computer restarting, but with docker first run.
I can reproduce the issue with alpine, so if I find the time I'll try to make a even simpler reproduction case later, dropping the docker-compose.

**Comment by sazuna** [comment] 2017-07-28 02:12
Much simpler reproduction case:

Dockerfile:
```
FROM alpine:3.6
CMD ["tail", "-f", "/dev/null"] #Keep alive
```

```
docker build . -t for-win-938
```
Make sure to replace F:\test in the following for any non-empty directory that docker can read.
```
docker run --name for-win-938-cont -v F:\test:/test --restart=always -d for-win-938
```
File count works properly.
```
λ docker exec for-win-938-cont ls /test -1 | wc -l
2
```
Restart docker. The built-in "Restart docker" GUI is enough. No restart needed (thanks @jasonterando).
```
λ docker exec for-win-938-cont ls /test -1 | wc -l
0
```
File counter shows 0.
Manually restart the container:
```
docker restart for-win-938-cont
```

```
λ docker exec for-win-938-cont ls /test -1 | wc -l
2
```
Volume is properly mounted again.

So the issue has nothing to do with restart, but with Docker first run.

**Comment by martinsefcik** [comment] 2017-08-23 21:06
This bug is in Docker for Win I guess from the beginning (first beta versions) and it is pretty annoying that it was still not resolved yet :-(

**Comment by friism** [comment] 2017-08-26 17:46
I think this probably a dupe of this issue: https://github.com/docker/for-win/issues/584#issuecomment-286792858

Please comment if you don't think that's the case.

**Closed by friism** 2017-08-26 17:46 UTC

**Comment by sazuna** [comment] 2017-08-26 17:57
Not sure if applies. As I mentioned 2 comments up, I can reproduce this independently of docker-compose, and I think that's a important distinction.
I could edit the opening post of this issue with reproduction case without docker-compose, in which case this issue should be open, or I could add a comment on the other issue that I can reproduce the issue without docker-compose - I'm not sure if this would be clear enough because that issue's title specifically mentions docker-compose, but in this case this issue should be closed.
What do you think?

**Comment by friism** [comment] 2017-08-26 18:24
You're correct that it's not related to compose. It's a limitation in Docker for Windows itself: You can not count on host bind mounts working _right_ after Docker for Windows starts, as is the case when you use `--restart=always -d`

**Comment by unlocomqx** [comment] 2018-01-25 01:27
I can reproduce by restarting docker instead of restarting windows
Docker settings > reset > Restart Docker

**Comment by Coolius70** [comment] 2018-11-13 09:59
The problem still exists. After restart of windows or more precise docker itself, the volume does not mount, repsectilvy is empty. I have to restart the container which is quit annoying.
Docker takes already quit a long time. Wouldn't it be enough wo wait with starting containers unitl it is up completly?

**Comment by judos** [comment] 2019-02-13 18:48
Also got the issue. Very annoying.

Version 2.0.0.2 (30215)
Channel: stable
Build: 0b030e1
Engine: 18.09.1

**Comment by unlocomqx** [comment] 2019-02-13 18:51
@judos I switched to linux because of this :rofl:

**Comment by judos** [comment] 2019-02-13 18:53
@unlocomqx still just a workaround. That helps some but not all of us ;)

**Comment by sjdvda** [comment] 2019-02-20 10:22
I have the same issue. Seems like a pretty major problem. It's strange that this has been known for nearly two years at this point and there's still no fix. For now, I'm using Task Scheduler to start a few containers with volumes 5 minutes after booting, but it's far from an ideal solution. Still a problem if I'm restarting Docker instead of Windows.

**Comment by Y2zz** [comment] 2019-02-21 05:24
This problem has been around for two years! ! !

**Comment by BenoitRanque** [comment] 2019-04-18 07:30
Could my issue [here](https://github.com/docker/compose/issues/6653) be related?

**Comment by Coolius70** [comment] 2019-04-18 08:52
If you read above you will see that it is definitly the same annoying problem. Just restart all container when windows docker is restarted or move container to linux.

**Comment by dwernerinformatica** [comment] 2019-10-11 11:31
Looks as if this similar problem also occurs on Linux (Docker version 19.03.2, build 6a30dfc on CentOS Linux release 7.6.1810 ). Some of the bind mounts shown as empty, even if the container was started manually after other containers which were autostarted  (using the  the same share but not having the same problem?!?). On contaiiner restart also the faulty container works ok
