### ISSUE TITLE
VM not created in Hyper-V

### ISSUE THREAD

**Issue by PetaPetaPeta** [docker/for-win#28] opened 2016-08-06 12:54 UTC
### Expected behavior

When the Docker for Windows application is started a VM should be created in Hyper-V.

### Actual behavior

Upon starting the application nothing seemingly happens. This is confirmed by the log file seen here: http://pastebin.com/keXwv0r0.
I have let the application run for 10 minutes without any changes to the log file. From the task manager I can confirm that both Docker.Service and Docker for Windows are running. In the Hyper-V manager I can also see that no VM and no virtual switch is created. This indicates to me that the powershell script(docker/resources/MobyLinux.ps1) that is supposed to run when starting up the program is not initiated. 
I've attempted to both disable and enable Hyper-V. I've also reinstalled Docker (both stable and beta) several times.

### Information

**Diagnostic ID:** 9F8E4BB9-3CAA-4F23-AB78-DDEC90843FD8
**Docker version:** 1.12.0
**Log file:** http://pastebin.com/keXwv0r0
**OS:** Windows 10 Pro 1511
**OS Build:** 10586.494

### Steps to reproduce the behavior

1. Enable Hyper-V
2. Install Docker
3. Start Docker

**Comment by PetaPetaPeta** [comment] 2016-08-07 13:43
# Network debug

From starting the resource monitor(resmon.exe) I have the following things:
![image](https://cloud.githubusercontent.com/assets/2445709/17462664/ba2d99d0-5cb4-11e6-9bd0-f6b864912cad.png)
![image](https://cloud.githubusercontent.com/assets/2445709/17462665/c273a3a0-5cb4-11e6-8a80-7de3e14739af.png)
![image](https://cloud.githubusercontent.com/assets/2445709/17462666/d471df04-5cb4-11e6-879e-70c81965bf94.png)

From the last image it looks as though Docker is attempting to connect to some remote address and failing.

**Comment by PetaPetaPeta** [comment] 2016-08-07 21:36
(X-post from https://forums.docker.com/t/docker-for-windows-does-not-start-after-reinstall)
I have tried to keep it running for 8 hours since last start. It seems like this is due to some timeout error. The updated log can be seen here: http://pastebin.com/qkK9tefv. Note that there is an 8 hour delay between getting a diagnostic ID and the next event. The thing that I am seeing as the possible culprit is this message  `Failed to upload an event and will retry later`. This corresponds with the network activity I am reporting in the Github issue. Maybe a firewall issue?
The current status is that the Docker for Windows client shows up in the tray. It is however stuck with status "Docker is starting" and no updates to the log. With regards to network activity I am seeing the same activity as earlier reported. The biggest change is that I have established contact to the docker service with `docker ps` and that I can start a container with `docker run busybox`. I will try to see if I can reproduce this behaviour tomorrow.

**Comment by PetaPetaPeta** [comment] 2016-08-09 09:26
I have found that the following makes Docker start:

1.  Start Docker for Windows
2. Put computer to sleep for about 8 hours
3. Start computer again
4. Docker will now start up and it is possible to connect to the service, but the tray  says Docker is runnig
5. Put computer to sleep for about 8 hours
6. Start computer again
7. Docker now runs as expected

This heavily indicates some timeout issue.

**Comment by rneugeba** [comment] 2016-08-09 10:47
I'm a little confused about what the issue is here: The initial report is about Windows 10 pro build 10586 (or 1511 release) and the logs form the third comment suggest this is for Windows 10 Pro build 14393 (or 1607 release). Furthermore, the logs in the third comment suggest that the application started fine.

Also, if you have an issue, could you please use the `Upload diagnostic...` in the `Diagnose and Feedback`  and quote the ID reported. That way we get additional diagnostics which may help finding the issue.

**Comment by PetaPetaPeta** [comment] 2016-08-09 15:15
I updated the Windows version between the first and the second comment in order to see if that solved the issue. It did not.
With regards to the log in the third comment. Look at the difference in time between line 12 and 13. The As I mentioned in comment number 4 Docker only starts after a number of hours. During those hours the application attempts to send the seemingly same request to the same address without getting a response.

I am unable to use the "Upload diagnostic"-option  in the application as part of the problem is that the application does not appear in the tray.

**Comment by dsperling** [comment] 2016-08-09 17:11
I have an easy workaround for this problem so users seeing this issue can run Docker 'stable' on Windows 1607.

1.  Install Docker 'stable'
2. Ensure the checkbox on the last screen is checked so that Docker is launched after the install.
3.  You will not see the Docker tray, but if you look at Task Manager, "Docker for Windows.exe" is running.
4.  Pull out your network cable
5.  Docker tray appears and initializes.  You will see the Docker welcome screen.
6.  Plug your network cable back in.

This appears to be an issue in Mixpanel Analytics running hanging for a long period of time on Windows 1607.

**Comment by PetaPetaPeta** [comment] 2016-08-09 18:51
I can confirm that fix proposed by dsperling works with a wireless adapter as well. All you have to do is go into your adapters and enable/disable a couple of times.

@dsperling: The issue is also present in an earlier version of Windows, namely the one mentioned in the original comment.

**Comment by myfriend12** [comment] 2016-08-10 03:24
I am having the same issue with a fresh install of docker and I am completely lost. I keep getting the following error. I have tried to re-install docker, remove everything, but nothing works.

> Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.
> 
> 'MobyLinuxVM' failed to initialize.
> 
> 'MobyLinuxVM' failed to start. (Virtual machine ID 817661C8-62FA-4E75-9C79-79F4AF06CA50)
> 
> 'MobyLinuxVM' failed to initialize. (Virtual machine ID 817661C8-62FA-4E75-9C79-79F4AF06CA50)
>    at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Core.Backend.BackendClient.Start(Settings settings)
>    at Docker.Actions.<>c__DisplayClass26_0.<RestartVm>b__0()
>    at Docker.Core.TaskQueue.<.ctor>b__16_0()

Attached are the log files. Anyone have any idea because I am lost. Below are the versions I am running:

> PS C:\Users\Steven> docker --version
> Docker version 1.12.0, build 8eab29e
> PS C:\Users\Steven> docker-compose --version
> docker-compose version 1.8.0, build d988a55
> PS C:\Users\Steven> docker-machine --version
> docker-machine.exe version 0.8.0, build b85aac1
> PS C:\Users\Steven> docker version
> Client:
>  Version:      1.12.0
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   8eab29e
>  Built:        Thu Jul 28 21:15:28 2016
>  OS/Arch:      windows/amd64
> Error response from daemon: An invalid argument was supplied
> PS C:\Users\Steven> [System.Environment]::OSVersion.Version
> 
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 10     0      10586  0
> 

[logs.txt](https://github.com/docker/for-win/files/410264/logs.txt)

**Comment by rneugeba** [comment] 2016-08-11 13:35
@PetaPetaPeta @dsperling thanks for the update/details. We will release a Beta22 on the beta channel shortly (hopefully sometime today) and it has some improvements to the mixpanel code. Since we can easily reproduce the issue you are seeing it would be great if you could give the new Beta a try once it is out and report back. If the issue is still there we'll look into it more.

Thanks

**Comment by dsperling** [comment] 2016-08-11 17:35
@rneugeba  looks like Beta 22 fixes this issue on my PC.

Note:  This was tested with 1607 + the Cumulative Update for 1607 (KB3176495) which was released August 10.

**Comment by rneugeba** [comment] 2016-08-17 11:23
Closing as the Beta22 seems to fix the issue. Note that Beat23 is out, but, unfortunately, due to a bug in the autoupdater, requires manual installation from https://download.docker.com/win/beta/InstallDocker.msi

**Closed by rneugeba** 2016-08-17 11:23 UTC
Labels: area/gui, kind/bug

**Comment by PetaPetaPeta** [comment] 2016-08-19 08:09
I just installed the latest beta and it solves my issue as well. Thank you very much for fixing this.
