### ISSUE TITLE
The container get wrong timestamp

### ISSUE THREAD

**Issue by strengthening** [docker/for-win#183] opened 2016-10-31 05:38 UTC
### expect results
The container show same timestamp with my win10

### results in fact
 The container ‘s timestamp smaller than my win10's timestamp

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. open docker in win10 and do nothing ,let win10 auto sleep for a while.
  2. active win10 , all the container in the docker has a wrong timestamp.

**Comment by rneugeba** [comment] 2016-10-31 10:03
@strengthening thanks for your report. This looks like a duplicate of #72 and we are tracking time related issue after sleep there, so I'm closing this.

**Closed by rneugeba** 2016-10-31 10:03 UTC
