### ISSUE TITLE
Installation fails when lanmanserver is disabled

### ISSUE THREAD

**Issue by mryserb** [docker/for-win#5772] opened 2020-02-14 08:57 UTC
**Expected behavior**
Install Docker Desktop successfully even with lanmanserver disabled. Why? In the release notes there is this section about moving away from samba

**Actual behavior**
Docker Desktop installation failed.

(sorry got only the german translation for exception message)

Der Serverdienst wurde nicht gestartet.
![grafik](https://user-images.githubusercontent.com/19263347/74514821-aa62eb00-4f0d-11ea-913b-66c9b62f9b03.png)

But when enabling the lanmanserver server, the installation goes without a hitch. Even after disabling lanmanserver after the installation Docker runs without a problem.

Steps to reproduce:
- Download & Install Docker Desktop Community Stable Version 2.2.0.0 or 2.2.0.3 (doesn't matter)

Running Windows 10 Pro 1909

**Comment by mat007** [comment] 2020-02-14 09:30
Thank you for the report, closing as a duplicate of #5150.

**Closed by mat007** 2020-02-14 09:30 UTC
