### ISSUE TITLE
docker desktop with wsl2 and nvidia cuda dose not work on latest version 

### ISSUE THREAD

**Issue by Orielhalvani** [docker/for-win#11409] opened 2021-06-09 06:51 UTC
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual behavior
docker on ubuntu 20.04 does not start with nvidia driver 
### Information
this has smothing to do with the changes because it works with version 3.3.0 but not with 3.3.3

**Comment by stephen-turner** [comment] 2021-06-09 07:33
Thanks for the report, this is a dupe of #11246.

**Closed by stephen-turner** 2021-06-09 07:33 UTC
