### ISSUE TITLE
Dead containers went away magically

### ISSUE THREAD

**Issue by Jonesie** [docker/for-win#553] opened 2017-03-05 19:21 UTC
### Expected behavior
Should be able to rm stopped containers

### Actual behavior
Status of containers was 'Dead', could not rm them.  Got error :

Error response from daemon: Unable to remove filesystem for 80d67f24eaefcf364f763985abce9117561ecef7b0f60a1f0737f0da92eb5f60: remove /var/lib/docker/containers/80d67f24eaefcf364f763985abce9117561ecef7b0f60a1f0737f0da92eb5f60/resolv.conf.hash: read-only file system

I ran the settings/diagnose and feedback option and the containers magically went away.

So, this is good 👍 

### Information
Docker for windows - Version 17.03.0-ce-win1 (10296)
99DAD0DC-EDB0-4172-B313-500FD9631936/2017-03-06_08-14-45

### Steps to reproduce the behavior
No idea.. sorry :)

**Comment by Jonesie** [comment] 2017-03-05 19:36
Actually, I kept getting read-only errors when I tried to delete all my images.  A restart of docker fixed this.

**Comment by friism** [comment] 2017-03-11 00:07
I'm going to close this issue since it's unclear how to reproduce the problem. Please re-open if you find a series of steps that consistently reproduce the issue.

**Closed by friism** 2017-03-11 00:07 UTC
