### ISSUE TITLE
docker build process does not allow NVIDIA Kernel Driver / CUDA to appear to PyTorch

### ISSUE THREAD

**Issue by samhodge-aiml** [docker/for-win#12903] opened 2022-08-18 04:21 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
During build process PyTorch is not detecting CUDA, during the `docker-compose up --build`

```
RUN NVIDIA_VISIBLE_DEVICES=all CUDA_HOME=/usr/local/cuda conda run python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
```
prints 
`We got cuda in PyTorch!!: false`

### Expected behavior
During build process PyTorch *DOES* detect CUDA, during the `docker-compose up --build`

```
RUN NVIDIA_VISIBLE_DEVICES=all CUDA_HOME=/usr/local/cuda conda run python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
```
prints 
`We got cuda in PyTorch!!: true`
### Information
  - Is it reproducible? Yes
  - Is the problem new? No
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
 
  - Windows Version: Edition	Windows 10 Pro
Version	21H2
Installed on	‎16/‎08/‎2022
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

  - Docker Desktop Version: v4.11.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Local machine both windows and Ubuntu

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
C:\Users\Sam\Documents\synthetic-data-main\synthetic-data-main\demonstrator> "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-08-18T03:58:41.762736000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running


[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running



Not all of the backend processes are running.
```

### Steps to reproduce the behavior

Dockerfile

```
FROM nvidia/cuda:11.3.1-devel-ubi8

ENV BASE_PATH=/app
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

ENV PATH=$PATH:/usr/local/conda/bin

RUN yum -y update \
    && yum -y install curl wget bzip2 perl --nobest --skip-broken\
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local/conda \
    && rm -rf /tmp/miniconda.sh \
    && /usr/local/conda/bin/conda install -y python=3.8 --freeze-installed \
    && /usr/local/conda/bin/conda clean --all --yes \
    && find "/usr/local/conda" -follow -type f \
    \( -iname '*.a' -o -iname '*.pyc' -o -iname '*.js.map' \) -delete

RUN rpm -e --nodeps curl bzip2

RUN yes | conda install git

RUN yum autoremove -y && yum clean all


RUN mkdir -p ${BASE_PATH}

COPY *.txt ${BASE_PATH}/

RUN yum install mesa-libGL -y

RUN pip install --upgrade pip && \
    pip install --ignore-installed --no-cache-dir --use-deprecated=legacy-resolver\
     -r ${BASE_PATH}/requirements.txt \
      --extra-index-url https://download.pytorch.org/whl/cu113

RUN yum -y install openssh-clients

RUN NVIDIA_VISIBLE_DEVICES=all CUDA_HOME=/usr/local/cuda conda run python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
CMD python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
```

docker-compose.yml

```
version: "3"

x-demo-config:
  &demo-config
  runtime: io.containerd.runc.v2

  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      version: "${VERSION}"
  tty: true
  mem_limit: 48GB
  environment:
    CUDA_HOME: /usr/local/cuda
    CUDA_VISIBLE_DEVICES: 0
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: all
  shm_size: '2gb'

services:
  demo:
    << : *demo-config
    ports:
      - 8000:8000
```

requirements.txt

```
numpy==1.19.2
torch==1.11.0+cu113
torchvision==0.12.0+cu113
torchaudio===0.11.0

```

  0. save files above in a folder which can be accessed from WSL2 Ubuntu, see: https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl
  1. docker-compose up --build

  2. docker build --progess=plain -t simple .
```
Step 14/15 : RUN NVIDIA_VISIBLE_DEVICES=all CUDA_HOME=/usr/local/cuda conda run python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
 ---> Running in f03976d6d050
We got cuda in PyTorch!!: False

Removing intermediate container f03976d6d050
 ---> 46f80c1cf386
Step 15/15 : CMD python3 -c "import torch; print(f'We got cuda in PyTorch!!: {torch.cuda.is_available()}')"
 ---> Running in 0b3d9ec2dbcb
Removing intermediate container 0b3d9ec2dbcb
 ---> 4fe0ca21bfb5
Successfully built 4fe0ca21bfb5
Successfully tagged simple:latest
```

Note no GPU is present during build

  3. docker run --gpus=all simple:latest

```
We got cuda in PyTorch!!: True
```

GPU is present during runtime.,

**Comment by samhodge-aiml** [comment] 2022-09-06 07:36
Tumbleweeds?

**Comment by nicks** [comment] 2022-09-06 18:53
Thanks for reporting! I think you're basically asking for https://github.com/moby/buildkit/issues/1436 -- i.e., we need some sort of `RUN --gpus=all` so that the image builder has access to GPUs. I'm going to mark this as a duplicate of that issue so that there's one place to communicate progress on this.

**Closed by nicks** 2022-09-06 18:53 UTC

**Comment by kognat-docs** [comment] 2022-09-06 19:35
If I can build via Docker compose with GPUs present I am gold!

**Comment by gregruthenbeck** [comment] 2022-09-12 05:37
Found that it wants the libs from the win-side:

```
LD_LIBRARY_PATH=/usr/lib/wsl/lib/ python3 -c "import torch; print(torch.cuda.is_available())"
```
