### ISSUE TITLE
Docker fails to start with "Docker hv-sock proxy (vsudd) is not reachable" error

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#1557] opened 2018-01-15 16:01 UTC
### Expected behavior

Docker starts!

### Actual behavior

Docker fails to start, providing the following error:
```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

This has affected me on both 17.12.0 builds. I've tried the basic troubleshooting including resetting Docker to factory defaults, restarting, and rebooting, each various times and in various orders, and I've still been unable to get Docker to start. I've uninstalled and reinstalled 17.09.1, and am back to work.

### Information

  - **Diagnostic ID**
    5335669B-983C-4A00-A704-208023A88C15/2018-01-15_07-24-18
  - **Windows version**
    Windows 10 Pro Version 1709 (OS Build 16299.192)
  - **Log**
    [log.txt](https://github.com/docker/for-win/files/1632262/log.txt)

### Steps to reproduce the behavior

  1. Install either of the 17.12.0 Docker updates
  2. Restart the machine (since Docker doesn't restart itself after an update - boo!)
  3. Wait for Docker to fail

**Comment by jeffpapp** [comment] 2018-01-15 16:41
I started getting the same error this morning. 

I'm running version 17.12.0-ce-win47 (15139)

I seem to remember updating to the latest Docker version late last week, but then all of a sudden this morning it stopped working.

**Comment by Addisco** [comment] 2018-01-15 16:49
Me, too! Here is another issue with the exact same problem: #1532
@shawmanz32na where did you get the old version? Maybe I'm missing something but I can only find the download for the latest version.

**Comment by shawmanz32na** [comment] 2018-01-15 18:13
@Addisco I've opened another issue, #1559, in hopes that the team will include download links in the [Release Notes](https://docs.docker.com/docker-for-windows/release-notes/). In the meantime, Docker For Windows Version 17.09.1-ce-win42 (14687) (which was the most recent working version for me) can be downloaded from `https://download.docker.com/win/stable/14687/Docker for Windows Installer.exe`

**Comment by Addisco** [comment] 2018-01-15 18:19
@shawmanz32na Thanks a lot!
In the meantime I figured that it's possible to install old version using chocolatey, e.g.: https://chocolatey.org/packages/docker-for-windows/17.09.1.14687

**Comment by mborra** [comment] 2018-01-16 09:19
I have the same issue, but if I launch the Docker for Windows Installer.exe I receive the message that says : ... installation is up to date.

**Comment by weissjoh** [comment] 2018-01-16 14:38
I am facing the same issue since upgrading to 17.12.
Interestingly there will be a stop command to the Moby VM so the VM is gracefully shutdown. Of course it isn't accessible any more. I was not able to figure out where the stop event comes from (in the log I can see "PowerMode", "HyperV" and "Moby").

**Comment by Oziomajnr** [comment] 2018-01-20 05:00
I have had this issue for the past 2 weeks and recent updates have not fixed it.

**Comment by jahewett** [comment] 2018-01-20 15:45
Have had this issue, found this in the following thread.

**Comment by SaintFenix** [comment] 2018-01-21 17:19
Installing version: "Docker CE for Windows 17.11.0.14328-edge" through chocolatey got me around this error. Though I'd much prefer to be on a newer release, at least I can work now.

**Comment by khanhvu161188** [comment] 2018-01-24 03:47
I cannot believe that the issue is not solved for a long time. Still get this issue after giving up 3 months ago

**Comment by richstep** [comment] 2018-01-24 17:25
Same issue here. Uploaded diagnostics. Bugsnag report 16961c3d-8477-4d48-8fc3-60bc857ad62b sent

**Comment by beantownace** [comment] 2018-01-25 03:24
Hey gents, I have been stuck on this now as well for a few weeks on a Win 10 VM I cannot switch to linux containers with the same error.  Hopefully if someone gets a resolve please let us all know.

**Comment by ashokgrg** [comment] 2018-01-25 06:08
Stop docker service
    Stop docker (kill process if needed)
    Run docker as administrator

**Comment by beantownace** [comment] 2018-01-26 02:17
ashokgrg how do I complete those commands?   I stopped docker then right clicked docker for windows and selected Run as Administrator but that made no difference same error.

**Comment by DavidBrower** [comment] 2018-01-28 02:53
@Addisco That was the one thing that helped me. Thank you.

**Comment by bhatt40** [comment] 2018-02-02 19:35
@Addisco This is the only solution that has worked for me.  Thanks.

**Comment by captainhook99999** [comment] 2018-02-09 15:58
Right-click on the Docker tray icon and run "Switch to Windows Containers...".
This will work for you.

**Comment by mrdomiciano** [comment] 2018-02-09 16:08
@captainhook99999 - I think it should work as Linux container as before!

**Comment by arthurdn** [comment] 2018-02-19 11:30
**Removing or changing** of priority for third party software with **high CPU consumption** fixed everything.

**Comment by lacroixca** [comment] 2018-03-03 14:37
Running the following script worked for me! As recommended on the [Docker website](https://docs.docker.com/docker-for-windows/troubleshoot/#networking-and-wifi-problems-upon-docker-for-windows-install)

[SCRIPT: CleanupContainerHostNetworking](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/master/windows-server-container-tools/CleanupContainerHostNetworking/README.md)

**Comment by richard-edwards** [comment] 2018-03-04 19:10
Thanks @lacroixca. That script worked for me. Needed to run that in powershell as administrator and then a reboot and docker is now running fine.

**Comment by sergio-domingues** [comment] 2018-03-06 14:47
I changed the path to another disk (D://) on _Docker > Settings > Advanced > Images and Volumes VHD Location_ and it solved it for me. It's a really casuistic solution but it's Windows...

**Comment by ctmcisco** [comment] 2018-03-06 19:34
This works for STABLE and EDGE and doesn't require a clean up networking or reinstall of docker for windows

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by awidjaja** [comment] 2018-03-09 00:37
I got this issue in Sep last year, and this today (Mar) there is no an inch of progress.  Amazing, no one from docker seem to care.  This makes docker for windows completely useless for months. 
I found the only solution for this issue is to stop using docker.

**Comment by khanhvu161188** [comment] 2018-03-09 01:01
same with me. I end up using docker from last year

Khanh Vu
________________________________

**Comment by rn** [comment] 2018-03-09 20:47
@awidjaja we do care but this is very likely an issue with the local windows installation or third party software. We do run CI on multiple windows machines/builds on every PR and do not hit this issue and also run DfW on our laptops without hitting it. I've personally see probably about 10-15 causes of this issue on user's machines, none of which can be attributed to Docker for Windows itself. We simply do not have the resources to debug all of these in detail

**Comment by shawmanz32na** [comment] 2018-03-09 21:03
@rn I, for one, do very much appreciate the automated tests and the hard work that goes into preventing errors like these. That said, however, I've been on an old version of Docker for months now due to this issue, and clearly I'm not the only one.

Since you've "personally seen about 10-15 causes" of this issue, could you document those resolutions somewhere, perhaps at https://docs.docker.com/docker-for-windows/troubleshoot/#troubleshooting ? That way, you don't have to debug all our problems, but we can benefit from your experience.

**Comment by toddlucas** [comment] 2018-03-09 21:11
@rm, thanks for clarifying some of your QA process related to this. This issue started for me a few months ago. As I mentioned in #1532, about three weeks ago, I wiped my machine and did a clean install of Windows 10 Pro Version 1709 (OS Build 16299.248). I installed the latest DfW (at the time) and experienced this issue. Only by uninstalling and reinstalling an older build would it work. Something has changed.

**Comment by awidjaja** [comment] 2018-03-10 13:06
@rn, thanks for the response. 
I understand this is likely caused by some problem with the local PC, I don't expect docker team to debug all the individual issues. 

What I would like to ask is for docker team to enhance the error handling for "Docker hv-sock proxy (vsudd) is not reachable" to output more detail of variables causing the error so there is a way for us to fiind the root cause of the issue.  

If this error message is a generic message for a variety of errors, then it will help if docker team can make the error message more specific.

Hope this is not asking too much.

**Comment by trevorsandy** [comment] 2018-03-11 13:54
@toddlucas
I have the same situation as you. Can you share the version (and link if possible) of the older version of Docker you were able to get running successfully? Thanks.

**Comment by toddlucas** [comment] 2018-03-11 20:58
@trevorsandy, that's great. It may be that DfW now requires being run as admin due to a recent change and their setup needs to be modified to take this into account. It would be good if the root cause was identified and documented.

I've had success with 17.09.0-ce-win33 2017-10-06 (13620) Stable. It's what I'm running now. You can find many of the older downloads via the [release notes](https://docs.docker.com/docker-for-windows/release-notes/), now. My guess is that anything before January should work without admin elevation. That's when people started filing issues. I'm not sure why their QA process hasn't detected the issue that we're experiencing.

This type of solution will only work for so long. Running older builds is obviously not sustainable. Hopefully the Docker folks will resolve this soon and we will all be able to move forward, running updates without fear.

**Comment by rfrerebe** [comment] 2018-03-30 19:53
Hello,

Upgrading to Docker Community Edition 18.03.0-ce-win59 2018-03-26 solved the issue for me.

**Comment by shawmanz32na** [comment] 2018-03-30 21:57
I also successfully upgraded to 18.03.0.

Before upgrading, I made sure to prune all unused images, stop all containers, stop all docker-compose stacks, and do any other cleanup I could think of. I can't say for sure if that helped, or if 18.03.0 accidentally (or purposefully) fixed the problem.

I'll vote to close, since this is no longer an issue for me. If others still struggle with this, their votes may outweigh mine.

**Comment by Oziomajnr** [comment] 2018-03-31 03:12
Docker started working for me, I don't know if it auto updated or anything else happened, it just started working. I have since upgraded to version 18.03.0-ce-win59 (16762) and it still works. I think updating it should work.

**Comment by rn** [comment] 2018-05-01 13:40
@shawmanz32na you are running Windows 10 on VMWare. While it looks like your VMware VM is correctly configured for nested virtualisation, the boot of the Linux VM inside your Windows VM is *very* slow, causing a timeout to be hit.

Because we have no control over (nor visibility of) your Windows VM configuration, we can't support this scenario (see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios), so I'm closing this issue.

I know that others have commented here, having the same issue, but no diagnostics IDs were supplied. The only issue where there is a diagnostics ID is a non-supported configuration

**Closed by rn** 2018-05-01 13:40 UTC

**Comment by shawmanz32na** [comment] 2018-05-01 14:02
@rn Thanks for looking into it

**Comment by jcoconnor** [comment] 2018-05-03 12:33
I've just come new to docker to setup a dev/test environment.
At the moment, the only option available to us to use ESX 6.5.
So not impressed with the response by @rn above.

It is proving to be an extremely unstable system for us at the moment.

**Comment by rn** [comment] 2018-05-03 13:14
@jcoconnor we used to run the Docker for Windows CI on ESX server spinning up very carefully configured windows VMs (3 per PR), and very beefy machines and had probably a 20%-30% failure rate either during startup or during test runs. We have since moved to bare-metal and the failures we have seen with nested virt are mostly gone. I probably also have looked at 50-100 issues with parallels and desktop virt, misconfigured VMs, underprovisioned VMs etc. We simply can't diagnose or help with these issue,

**Comment by jcoconnor** [comment] 2018-05-03 13:17
Understood @rn and thanks for the reply.
I'm coming to the conclusion myself on this.
Unfortunately the VM infra that we have here is very heavily used, so that could well be the issue and a good indicator that we really need a native Hyper-V platform to support our testing.

**Comment by rn** [comment] 2018-05-03 13:26
If you can, I'd try pinning the Windows 10 VM to cores, not schedule other VMs on the same core, give it ample of reserved memory (e.g. 16G). I've seen tremendous slowdowns of Hyper-V VMs when booting if there is a load on the system.

**Comment by jcoconnor** [comment] 2018-05-03 14:52
@nr I checked with our Infra-Team and thats going to be a non-starter (significant workloads already on the boxes).

However, you've given me some extremely useful data points as to why we need either bare-metal Hyper-V or possibly a hosted solution.

Tx much.

**Comment by jcoconnor** [comment] 2018-05-04 08:03
@nr - thanks for your help to date - one (hopefully) last question.

Since I have an Azure account I have quickly tried to spin up docker [on a suitable provisioned machine](https://azure.microsoft.com/en-gb/blog/nested-virtualization-in-azure/)

Docker (LCOW) appears to work and I've successfully spun up a ubtunu image among others.
Is this likely to be a useful temporary environment until such time as I can get bare-metal servers provisioned ?

Please direct me to a better forum if this thread isn't the appropriate place for further discussion.

**Comment by rn** [comment] 2018-05-07 15:34
@jcoconnor LCOW currently is quite experimental. Some operations, such as building or pulling images with lots of layers can take considerably longer. I've also seen stability issues with random errors. Also, some of the host volume stuff, currently has even less functionality than the SMB/CIFS based implementation we use with the Linux VM. Having said all that, it depends on your apps and LCOW may be suitable option.

**Comment by jcoconnor** [comment] 2018-05-08 15:42
Thanks @rn We have been able to successfully get our application up using LCOW so it might be workable solution until we get some bare metal.

**Comment by PavelSosin** [comment] 2019-05-12 08:03
I had this issue with CE edition. Now I have this issue with enterprise 2.1 Is it "Enterprise" quality?

**Comment by PavelSosin** [comment] 2019-05-13 06:59
Which kind of Socket do you use, TCP/IP socket or Winsock ? If you use WinSock you can find many tricks how to make WinSock working in Windows 10 using single Google search. Proposed script can't be used in the real  production environment due to all its pre-cautions
[logs.zip](https://github.com/docker/for-win/files/3171456/logs.zip)
Packed logs file from the diagnostic zip is attached

cautions.

**Comment by PavelSosin** [comment] 2019-05-19 13:13
On the bare metal I can install Ubuntu and Microk8s with native management tools and use our own development  environment with no headache. Chrome runs everywhere.
