### ISSUE TITLE
Cannot access NodePort K8S service

### ISSUE THREAD

**Issue by evilmonster18** [docker/for-win#10391] opened 2021-02-15 15:09 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
I cannot access K8S Node Port services or pods from outside the cluster (neither from WSL or Windows).

### Expected behavior
I should be able to access a K8S Node Port service or pod from outside the cluster (both from WSL and Windows).

### Information
This problem can be easily and quickly reproduced by following the steps below. I just set up my Docker Desktop and respective K8S cluster for the first time a couple of days ago, and this has been a problem since the beginning.

  - Windows Version: **Windows 10 Pro: Version 20H2, Build 19042.804**
  - Docker Desktop Version: **3.1.0 (51484)**
  - WSL2 or Hyper-V backend? **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

### Steps to reproduce the behavior
  1. Run the 2 following commands to deploy a generic HTTP echo server and expose it to outside the cluster through a Node Port service:
```
kubectl create deployment echoserver --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment echoserver --type=NodePort --port=8080
```
  2. Open `NODE_IP:EXPOSED_PORT` in the browser or run the netcat command `nc NODE_IP EXPOSED_PORT` and try to send a message (from either WSL or Windows).
    - `NODE_IP` is the internal IP of the Docker Desktop K8S node (obtained by seeing the `INTERNAL-IP` column on the command `kubectl get nodes -o wide`)
    - `EXPOSED_PORT` is the node port exposed by the service (obtained by seeing the field `NodePort` on command `kubectl describe service echoserver`)

Opening the URL on the browser should be met with [this](https://imgur.com/a/9FyogbH) page. However, you will get a generic error response saying the browser couldn't reach the URL. 
Sending a message with the netcat command should be met with a 400 Bad Request response, as it will not be a properly formatted HTTP request. However, you will not get any response at all or the TCP connection may not even be made in the 1st place.

### Other success scenarios

- Trying to communicate with the service and/or the pod from inside the cluster, for example, through another pod, works perfectly.
- Using the command `kubectl port-forward deployment/echoserver 2311:8080` to port forward the deployment locally and then either accessing `localhost:2311` in the browser or through netcat also work perfectly (in both WSL and Windows).

#### EDIT:

Forgot to mention that issue #5406, posted more than a year ago, describes basically the same problem I am experiencing. Since no one really helped out on that issue, I decided to post this new one with more easily reproducible steps.

**Comment by stephen-turner** [comment] 2021-02-15 15:18
Sorry, but I'm going to close this as a duplicate of #5406. We don't want two tickets for the same issue. But it would be helpful if you could copy all the information across into that ticket.

**Closed by stephen-turner** 2021-02-15 15:18 UTC
