### ISSUE TITLE
Windows 11 WSL 2 Docker Desktop v4.23.0 Everything is Stuck

### ISSUE THREAD

**Issue by kicut** [docker/for-win#13677] opened 2023-09-12 05:33 UTC
### Description

I have tried all the suggestions of being in the wilderness and restarting the PC many times, none of them work.

![image](https://github.com/docker/for-win/assets/25601335/23610812-2012-4473-b229-ebdf4bac41f8)

Sometimes I can get in all the way here. I had to wait a long time to get this screen.

![image](https://github.com/docker/for-win/assets/25601335/e00971bd-1cfb-4fb8-8335-efe978e7f8a8)

![image](https://github.com/docker/for-win/assets/25601335/af488e71-d1dc-426f-876e-2abc59a3acdd)

![image](https://github.com/docker/for-win/assets/25601335/7b667273-d466-4851-ac6c-19addc62f3e4)

**`docker version`: _stuck_**

![image](https://github.com/docker/for-win/assets/25601335/51d3b838-af91-456d-8d75-8b309621a7ec)

`docker info`: _stuck_

![image](https://github.com/docker/for-win/assets/25601335/ded3a80b-bff8-4214-93ed-252a5d0cb33d)

### Reproduce

Open Docker Desktop and you will be stuck at "Starting the Docker Engine"

### Expected behavior

Don't get stuck there.

### docker version

```bash
stuck
```

### docker info

```bash
stuck
```

### Diagnostics ID

CA4DB01D-067C-49B5-8161-D37913784AA2/20230912051817

**Comment by kicut** [comment] 2023-09-12 09:15
I tried downgrading Docker Desktop one by one, it worked again on version v4.20.1, versions above had the same problem.

**Comment by ctalledo** [comment] 2023-09-12 19:29
Hi @kicut,

Thanks for filing the issue and apologies for the error. 

I can see in the diagnostics bundle that Docker Desktop 4.23 fails to boot on WSL with this error:

```
ESC[93m[2023-09-12T05:16:09.687478340Z][02-docker][I] [2023-09-12T05:16:09.687219240Z][lifecycle-server][W] still waiting for the HTTP proxy after 23.391990114s. Last error was Get "http://http.docker.internal:3128": EOF
```

We are investigating. It's a duplicate of #13662, so marking it as such. Let's track it on that other issue please. Thanks.

**Closed as completed** 2023-09-12 19:30 UTC
Labels: area/startup, area/WSL2, status/duplicate, version/4.23.0
