### ISSUE TITLE
Vmmem eating up CPU after last update even without running any docker image

### ISSUE THREAD

**Issue by Bleki** [docker/for-win#8742] opened 2020-10-01 09:32 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E550E750-34CD-4202-8F8A-A1A0D5C97B9C/20201001091450

### Expected behavior
No Vmmem high CPU usage

### Actual behavior
High CPU usage for Vmmem

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, it's a desktop Windows.

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Watch CPU usage in Task Manager for Vmmem

**Comment by johanseland** [comment] 2020-10-07 07:06
I can confirm that I am also experiencing this problem. I am running Windows 10 Pro and using Docker Desktop 2.4.0.0 (48506)

For me, the high Vmmem CPU usage seems to be tied to running compilation of a large C++ code base using parallel make/ninja.

**Comment by johanseland** [comment] 2020-10-08 07:15
I did some more digging into this and I have come up with an acceptable workaround. I wonder if the root causes it that Docker Desktop 2.4.0 uses slightly more memory than before, causing the system to start paging to this earlier than it did for 2.3.

These are my observations:
- The problem goes away for some time if I drop the Linux caches (e.g. echo 1 > /proc/sys/vm/drop_cache inside a wsl2 session)
- The vmmem process seems to be hogging all CPU, I suspect it is busy waiting when waiting for memory that has been swapped to disk.
- If I reduce the amount of memory available to wsl2 by editing .wslconfig I am not running into this problem. 

According to https://docs.microsoft.com/en-us/windows/wsl/wsl-config the default available memory to wsl2 is 80% of physical RAM. On my 16 GB machine this amounts to 12GB, which was enough for the system to start swapping with quite light usage of application on the host system (e.g. Visual Studio Code, Edge, some terminal windows). Limiting the amount to 10GB removed the problem for me altogether yesterday. I could successfully run the large compilation mentioned above without vmmem using all CPU.

**Comment by inhumantsar** [comment] 2020-11-15 18:11
Can confirm that editing wsl-config to enforce global resource limits helped stabilise memory and CPU usage.

Worth keeping in mind just how much memory all this stuff takes up though. On my system, after a fresh reboot and starting up Docker Desktop, vmmem usage sits around 1.5GB. +1GB for K8S. +1GB if I open up a new distro (Ubuntu 20.04). If the limits are set too low, the VM will start swapping again.

**Comment by ERGeorgiev** [comment] 2021-01-06 12:36
Some CPU and all of my ram, nothing running. Happened after a build, it's been 30 minutes and its still sitting there. Shutting down docker does not help.
![Docker_Desktop_B47KC5fcCL](https://user-images.githubusercontent.com/32902048/103769177-b3741380-501b-11eb-83ff-46d11d1aa9ac.png)

**Comment by cactysman** [comment] 2021-01-07 20:15
This started happening to me too over the past few days
<img width="549" alt="Taskmgr_2021-01-06_16-43-12" src="https://user-images.githubusercontent.com/5056880/103940319-6b451600-512d-11eb-939d-5a88c9876191.png">

**Comment by cactysman** [comment] 2021-01-13 22:37
Disabling the Kubernetes cluster fixed this for me btw, so there gotta be an issue with that part(?).

**Comment by mediplex** [comment] 2021-01-19 20:35
Same issue here.
vmmem takes 2gb+ after a reboot and no container running yet!
Once I run my dev container it eats up all the remaining memory.

Config: windows 10 20H2 (latest) and docker 3.1 (latest)

**Comment by sergey-derugo** [comment] 2021-01-26 14:56
> Same issue here.
> vmmem takes 2gb+ after a reboot and no container running yet!
> Once I run my dev container it eats up all the remaining memory.
> 
> Config: windows 10 20H2 (latest) and docker 3.1 (latest)

https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37 helped me

**Comment by ivanrodriguezfernandez** [comment] 2021-03-12 09:12
In the past we could configure limits with .wslconfig but now my computer ignore this seetings.

**Comment by liny01-nbsa** [comment] 2021-03-13 15:15
Same issue.

Windows Version: 20H2 (OS Build 19042.804)
Docker for Desktop: 3.2.1

**Comment by DeveloperPad** [comment] 2021-04-17 18:19
Same issue here. WSL already consumes like 12 out of my 16 GB RAM after startup, although not a single container is running.
Currently mitigated by above workaround with limiting the memory, but this is surely not a suitable fix.

Windows Version: 20H2 (OS Build 19042.928)
Docker for Desktop: 3.3.1

**Comment by Marcin-TA** [comment] 2021-04-22 06:42
I have the same issue. 100% CPUT and 80% RAM is used by Vmmem.

**Comment by acurvers** [comment] 2021-04-22 16:43
for me it is suddenly fixed, I am not sure why. I think it might be because
I updated ubuntu running in WSL which was not updated for a long time.
Maybe it helps

**Comment by Gabriellavoura** [comment] 2021-04-25 19:38
Same here (98% RAM ( 15.4GB) and 100%CPU).
Win pro build: 19042
WSL2
Docker v20.10.5

**Comment by onomatopellan** [comment] 2021-04-25 19:47
@Gabriellavoura You can specify the max RAM Docker WSL2 can use thanks to the [.wslconfig file](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig).

**Comment by Gabriellavoura** [comment] 2021-04-25 19:55
> 
> 
> @Gabriellavoura You can specify the max RAM Docker WSL2 can use thanks to the [.wslconfig file](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig).
> 
> ```
> [wsl2]
> memory=8Gb
> ```
Thanks, I have already done that, just posted here to say that this problem isn't fixed yet.

**Comment by rnemeth90** [comment] 2021-05-13 11:42
Same issue here. VMMem process is using 2-3 GB of RAM, despite no running containers. Kubernetes is not enabled. 

Docker Desktop: 3.3.3 (64133)
Windows 10 Enterprise 21H1 (19043.964)

**Comment by kamerat** [comment] 2021-06-03 15:03
Same for me. Even after quitting docker-desktop (Right click - quit docker desktop) vmmem does not exit.

Also, even tho Docker is not in boot, vmmem still spins up.

**Comment by vanquang9387** [comment] 2021-06-04 07:07
Same for me.
vmmem takes ~ 2GB memory without running any images.

Edition	Windows 10 Pro
Version	21H1
OS build	19043.985
WSL2
Docker Desktop verion 3.3.3

**Comment by Matsemann** [comment] 2021-06-04 11:37
```
$ wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Stopped         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2

$ docker ps
<nothing>
```

even with this, vmmem sometimes uses ~50%+ cpu and a couple of gigs of ram. `wsl --shutdown` and restarting docker engine works, but only temporarily.

**Comment by konradgadecki** [comment] 2021-06-25 23:32
```
C:\ > wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
C:\ > docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
<nothing>
```

I noticed this issue happens right after I create a docker image with ``` docker build ``` command locally on my pc. Memory utilization by vmmem process grows rapidly and never goes down, even if Docker Desktop (the latest version) is restarted. Only pc restart helps in this case for me so it all of this makes a local development difficult. Is there any solution? 

![image](https://user-images.githubusercontent.com/26045582/123493623-57c73200-d61d-11eb-88b1-2e49d83749f4.png)

**Comment by duemti** [comment] 2021-07-05 13:09
"docker will simplify the development" ... they said. Now my pc sounds like a jet engine. Also, spent ton of time figuring why that happens, to also find that i can't stop it (not at least without much overhead).

**Comment by paulmiller3000** [comment] 2021-07-06 13:15
> > Same issue here.
> > vmmem takes 2gb+ after a reboot and no container running yet!
> > Once I run my dev container it eats up all the remaining memory.
> > Config: windows 10 20H2 (latest) and docker 3.1 (latest)
> 
> https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37 helped me

This work-around fixed it for me as well. Would be nice if we could get a fix for this.

**Comment by danmaina** [comment] 2021-07-19 22:12
An alternative workaround that worked for me was to disable WSL 2 and use Hyper V. Docker may not be as fast but at least resources are much more reasonable.

Disable WSL 2 use in docker under settings

![image](https://user-images.githubusercontent.com/12138004/126233706-c8fbe83d-4f49-47b5-8e65-009fa041dada.png)

Disable WSL in windows features

![image](https://user-images.githubusercontent.com/12138004/126233786-b9b99dd1-2f3b-4a44-84e9-c9e543a03e8d.png)

![image](https://user-images.githubusercontent.com/12138004/126233911-7ff7522f-4d80-4c13-b016-d3d47c45be0b.png)

If you are using WSL for other tasks or want the extra docker perfomance, this may not be the solution you are looking for. It works only as a workaround.

**Comment by canardaaydin** [comment] 2021-08-12 16:41
Same issue, even though non of the containers are working, vmmem eats 16.5gb of ram.

**Comment by UltraWelfare** [comment] 2021-08-20 09:21
Same issue here. Not a single container ever created, it wukk still eat all of the RAM.
The .wslconfig isn't a fix as VMmem will still eat up to the limited amount specified on the file...

**Comment by kamerat** [comment] 2021-08-20 09:41
@danmaina 

You can use the HTML tag [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in the markdown to collapse your images.

```html
<details>
<summary>Some title - click me</summary>

![](https://user-images.githubusercontent.com/12138004/126233911-7ff7522f-4d80-4c13-b016-d3d47c45be0b.png)
</details>
```
Renders this:
<details>
<summary>Some title - click me</summary>

![](https://user-images.githubusercontent.com/12138004/126233911-7ff7522f-4d80-4c13-b016-d3d47c45be0b.png)
</details>

Really usefull for anwers like yours above with a lot of loong images.

**Comment by UltraWelfare** [comment] 2021-08-20 10:02
> 
> 
> An alternative workaround that worked for me was to disable WSL 2 and use Hyper V. Docker may not be as fast but at least resources are much more reasonable.

This is a good solution but unfortunately not available to users with Windows 10 Home.
Hyper-V is only available for "Windows 10 Enterprise, Pro, or Education" ([source](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v))

**Comment by therealdandecker** [comment] 2021-08-25 09:20
@danmaina the Hyper-V solution is the only one that worked for me as well (tried wslconfig and all that.) It is really maddening that this issue seems to get largely ignored.

**Comment by Matsemann** [comment] 2021-08-31 19:41
Relevant (but maybe not exactly the same) issue over at wsl https://github.com/microsoft/WSL/issues/6982#issuecomment-847598501

**Comment by philippeantonietti** [comment] 2021-09-14 04:01
same problem, docker is consuming a tremendous amount of CPU =(

**Comment by rcyost** [comment] 2021-09-27 00:49
same :(

**Comment by Marcin-TA** [comment] 2021-09-27 05:26
I noticed that version 4 of docker is super slower on win10 :(

**Comment by DarioLopes** [comment] 2021-11-16 14:04
Hi same here, Docker is pretty useless in Windows (run fine on Ubuntu though)

**Comment by kasvith** [comment] 2021-12-28 14:34
Hi Im having the same high CPU usage problem.

**Comment by LaBlazer** [comment] 2022-01-23 17:19
Any update on this? I'm experiencing the same issue...

**Comment by brunosalvino** [comment] 2022-02-07 23:12
Same here: after Windows startup, I start Docker Desktop, "Vmmem" memory usage goes to 2GB without any container running. I'm sitting here looking at Task Manager and "Vmmem" memory usage keeps going up all by itself. It has to be a memory leak.

Windows 10 Pro 21H2 build 19044.1466
Docker Desktop 4.4.4 (73704), Docker Engine v20.10.12

.wslconfig
[wsl2]
memory=4000MB
processors=4

**Comment by lojell** [comment] 2022-02-09 18:48
Same issue for me, high memory consumptions even when no containers are running

**Comment by Steven73041** [comment] 2022-03-06 10:07
Same here in windows 11. Docker not running at all but CPU 100% + RAM consuming. I opened docker and closed it and fixed.

**Comment by luxalpa** [comment] 2022-03-06 17:54
I have the same problem. I don't have WSL set up but instead use the Hyper-V version. Docker Desktop is not running. Launching it shuts down the Hyper-V machine and then starts it again, resolving the issue. There's also tons of error messages in the console but I wasn't able to capture those yet. I only remember that it was something about `vpnkit` (I don't use a VPN).

**Comment by jimmycd** [comment] 2022-03-11 13:05
+1
Win 11 
![image](https://user-images.githubusercontent.com/9625872/157870149-16095cfd-727a-4c82-896a-909be10b3cbb.png)
.wslconfig is 

```
[automount]
root = /

[wsl2]
memory=4GB   # Limits VM memory in WSL 2 up to 3GB
processors=2 # Makes the WSL 2 VM use two virtual processors

[user]
default = root

```

![image](https://user-images.githubusercontent.com/9625872/157870697-11613ca8-40e5-40fd-8916-8c136edc288f.png)



after fresh reboot (docker desktop autostarting, kubernetes active, nothing else active on the machine) -> CPU Fan goes wild 
![image](https://user-images.githubusercontent.com/9625872/157870233-929f1387-da4d-448c-9542-1d6630644e86.png)

try #1: stopping Kuberntes, docker desktop still active -> no change
try #2: disabling wsl distro integration -> no change
try #3: stop wsl: wsl -- shutdown --> vmmem dispappears (no wonder)
try #4: bash (starts wsl default distri) -> normal behaviour (only default distri is up)
try #5: restart docker desktop: now all 3 distris are up and NORMAL BEHAVIOUR!

--> wsl -- shutdown and restarting docker-desktop is a workaround (and only this).

**Comment by NebraskaCoder** [comment] 2022-08-08 02:03
Sad to see this issue go 'stale' with no resolution.

**Comment by Dherlou** [comment] 2022-08-08 07:06
/remove-lifecycle stale
Far from stale, unfortunately...

**Comment by lucaspottersky** [comment] 2022-08-15 20:28
> Sad to see this issue go 'stale' with no resolution.

i guess now they are only focused on making money instead 😞

**Comment by flophype** [comment] 2022-08-19 16:49
Still very much an issue!

**Comment by Steven73041** [comment] 2022-08-19 17:24
For me, after updates it is ok.

**Comment by nicks** [comment] 2022-08-22 17:22
Hi all! sorry to hear you're having problems.

From the history of this thread, it sounds like there are several different issues related to CPU/RAM usage being reported here -- some are fixed and some might not be. The original issue has a workaround that is described further up-thread (editing the wsl-config - https://github.com/docker/for-win/issues/8742#issuecomment-705380799). Some of the issues are tracked elsewhere in this issue tracker.

Because the original issue has a workaround, I'm going to close this. It's hard for us to inform people when your individual issue is fixed if we're lumping all resource utilization problems into a single issue.

If you believe your problem is still there, please file a new issue with specific repro steps and a diagnostic ID.

**Closed by nicks** 2022-08-22 17:22 UTC
Labels: version/2.4.0.0, version/20H2
