### ISSUE TITLE
docker docker-compose broken after run "install.sh" comes from harbor

### ISSUE THREAD

**Issue by mike-boost** [docker/for-win#8053] opened 2020-08-13 10:57 UTC
windows version:  2004 19041.450
windows docker desktop version:  19.03.12
WSL2 distro: Ubuntu 18.04
Harbor version at [v1.10.4](https://github.com/goharbor/harbor/releases)

1. download harbor offline installation tar, and untar to folder harbor
2. run "install.sh" in the "harbor"
script stop  at 81 of install.sh

and command docker and docker-compose can't not found anymore!!

@stephen-turner  please refer to the link
[install.sh](https://github.com/goharbor/harbor/blob/v1.10.4/make/install.sh)  depends on:
 [common](https://github.com/goharbor/harbor/blob/v1.10.4/make/common.sh),
[prepare](https://github.com/goharbor/harbor/blob/v1.10.4/make/prepare)

**Comment by stephen-turner** [comment] 2020-08-13 11:01
I don't know what's in this install.sh file, but I suspect this might be a dupe of #7836.

**Comment by stephen-turner** [comment] 2020-08-13 14:04
Thanks for the link to the scripts. I can confirm that this is a dupe of #7836: it's having a container that mounts the whole of your host filesystem inside the container (`-v /:/host_mnt`) that is the trigger. When that container is removed, the docker command gets accidentally removed too.

**Comment by stephen-turner** [comment] 2020-08-13 14:05
I will close this ticket as a dupe, please follow #7836 for updates.

**Closed** 2020-08-13 14:15 UTC
