### ISSUE TITLE
My docker doesn't start Unhandled exception: Sequence contains no elements

### ISSUE THREAD

**Issue by felefant** [docker/for-win#6686] opened 2020-05-13 14:37 UTC
Hi all,
i've a problem starting docker daemon on my windows 10 laptop.
I receive an Unhandled exception: Sequence contains no elements

Version: 2.3.0.2 (45183)
Channel: stable
Sha1: e9b671cd3cb844cb63ad6fd7c79a4d15424233c4
Started on: 2020/05/13 16:28:45.184
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\felefant\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:28:45.282][GUI               ][Info   ] Starting...
[16:28:45.301][ComponentVersions ][Info   ] Edition community
[16:28:45.305][ComponentVersions ][Info   ] Edition community
[16:28:45.505][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[16:28:45.524][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[16:28:45.529][SegmentApi        ][Info   ] Usage statistic: Identify
[16:28:45.697][SegmentApi        ][Info   ] Usage statistic: appLaunched
[16:28:56.781][ApplicationTemplatesTracking][Info   ] Cannot list templates
[16:28:56.782][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[16:28:56.784][SegmentApi        ][Info   ] Usage statistic: heartbeat
[16:28:56.879][LoggingMessageHandler][Info   ] [955511ac] <BackendAPIClient start> GET http://backend/version
[16:28:56.921][LoggingMessageHandler][Info   ] [955511ac] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 41ms)
[16:28:57.441][LoggingMessageHandler][Info   ] [53740479] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[16:28:57.449][LoggingMessageHandler][Info   ] [53740479] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 7ms)
[16:28:57.461][LoggingMessageHandler][Info   ] [8dd447da] <BackendAPIClient start> POST http://backend/migrate/app
[16:28:57.464][LoggingMessageHandler][Info   ] [8dd447da] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 2ms)
[16:28:57.471][Engines           ][Debug  ] Starting
[16:28:57.491][LoggingMessageHandler][Info   ] [8579cd76] <BackendAPIClient start> POST http://backend/versionpack/enable
[16:28:57.540][LoggingMessageHandler][Info   ] [8579cd76] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 48ms)
[16:28:57.671][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[16:28:57.699][GoBackendProcess  ][Info   ] Started
[16:28:57.703][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[16:28:57.730][MutagenProcess    ][Info   ] Started
[16:28:57.741][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[16:28:57.742][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[16:28:57.750][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[16:28:57.759][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1589380137}
[16:28:57.760][SystrayNotifications][Info   ] Docker is starting
[16:28:57.774][LoggingMessageHandler][Info   ] [57df99e3] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:28:57.976][LoggingMessageHandler][Info   ] [57df99e3] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 201ms)
[16:28:57.979][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[16:28:57.984][LoggingMessageHandler][Info   ] [38a56c3c] <BackendAPIClient start> POST http://backend/hyperv/stop
[16:28:58.028][LoggingMessageHandler][Info   ] [38a56c3c] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 43ms)
[16:28:58.065][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[16:28:58.106][VpnKitBridge      ][Info   ] Started
[16:28:58.110][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[16:28:58.110][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[16:28:58.110][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[16:28:58.110][MutagenProcess    ][Info   ] [sync] Session manager initialized
[16:28:58.607][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[16:28:58.607][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[16:28:59.197][IsoConfig         ][Info   ] Generating CA Cert Bundle
[16:28:59.232][IsoConfig         ][Info   ] CA Cert Bundle Generated
[16:28:59.505][LoggingMessageHandler][Info   ] [be03ceb1] <BackendAPIClient start> POST http://backend/hyperv/create
[16:28:59.560][LoggingMessageHandler][Info   ] [be03ceb1] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 54ms)
[16:28:59.579][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[16:28:59.579][LoggingMessageHandler][Info   ] [c6ea475d] <BackendAPIClient start> POST http://backend/hyperv/stop
[16:28:59.598][LoggingMessageHandler][Info   ] [c6ea475d] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 18ms)
[16:28:59.608][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 16064
[16:28:59.633][LoggingMessageHandler][Info   ] [7303a629] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[16:28:59.765][LoggingMessageHandler][Info   ] [e1320d67] <Server start> GET http://unix/versions
[16:28:59.863][LoggingMessageHandler][Info   ] [e1320d67] <Server end> GET http://unix/versions -> 200 OK (took 97ms)
[16:28:59.912][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[16:28:59.913][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[16:28:59.915][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[16:28:59.920][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[16:28:59.921][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[16:28:59.922][GoBackendProcess  ][Info   ] enabling filesystem caching
[16:28:59.922][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[16:28:59.923][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[16:28:59.926][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[16:28:59.926][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[16:28:59.926][GoBackendProcess  ][Info   ] using mfsymlinks
[16:29:00.173][LoggingMessageHandler][Info   ] [7303a629] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 539ms)
[16:29:00.180][LoggingMessageHandler][Info   ] [97bbcb81] <BackendAPIClient start> GET http://backend/hyperv/check-virtualization
[16:29:00.201][LoggingMessageHandler][Info   ] [97bbcb81] <BackendAPIClient end> GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 21ms)
[16:29:00.202][LoggingMessageHandler][Info   ] [dbe78d47] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:29:00.264][LoggingMessageHandler][Info   ] [dbe78d47] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 61ms)
[16:29:00.264][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[16:29:00.264][LoggingMessageHandler][Info   ] [b8aac025] <BackendAPIClient start> POST http://backend/hyperv/stop
[16:29:00.282][LoggingMessageHandler][Info   ] [b8aac025] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 17ms)
[16:29:00.302][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[16:29:00.320][VpnKitBridge      ][Info   ] Started
[16:29:00.320][IsoConfig         ][Info   ] Generating CA Cert Bundle
[16:29:00.353][IsoConfig         ][Info   ] CA Cert Bundle Generated
[16:29:00.511][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[16:29:00.514][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[16:29:00.585][LoggingMessageHandler][Info   ] [5eb92036] <BackendAPIClient start> POST http://backend/hyperv/create
[16:29:00.627][LoggingMessageHandler][Info   ] [5eb92036] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 41ms)
[16:29:00.628][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[16:29:00.628][LoggingMessageHandler][Info   ] [86cb509e] <BackendAPIClient start> POST http://backend/hyperv/stop
[16:29:00.643][LoggingMessageHandler][Info   ] [86cb509e] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 15ms)
[16:29:00.652][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 10684
[16:29:00.665][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[16:29:00.666][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[16:29:00.666][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[16:29:00.667][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1589380140}
[16:29:00.667][SystrayNotifications][Error  ] Unhandled exception: Sequence contains no elements
[16:29:00.691][GUI               ][Info   ] Sending Bugsnag report a7c3f046-f7b8-422f-84b7-b895cb328f6c...
[16:29:00.789][GUI               ][Info   ] Bugsnag report a7c3f046-f7b8-422f-84b7-b895cb328f6c sent
[16:29:00.790][SegmentApi        ][Info   ] Usage statistic: eventCrash
[16:29:00.793][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[16:29:00.993][Engines           ][Error  ] Start failed with Unhandled exception: Sequence contains no elements
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[16:29:01.228][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[16:29:01.229][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[16:29:01.230][GoBackendProcess  ][Info   ] mutagen sync list --output json
[16:29:01.400][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[16:29:01.400][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[16:29:10.502][SegmentApi        ][Info   ] Usage statistic: actionMenuFeedback
[16:29:11.802][LoggingMessageHandler][Info   ] [a6587011] <Server start> POST http://localhost/notifications/subscriptions
[16:29:11.880][LoggingMessageHandler][Info   ] [a0a6aa3e] <NotificationsClient start> GET http://localhost/ping
[16:29:12.011][LoggingMessageHandler][Info   ] [a0a6aa3e] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 131ms)
[16:29:12.014][LoggingMessageHandler][Info   ] [a6587011] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 211ms)
[16:29:15.192][LoggingMessageHandler][Info   ] [a39662ff] <Server start> GET http://localhost/kubernetes
[16:29:15.195][LoggingMessageHandler][Info   ] [248eae3d] <Server start> GET http://localhost/license/details
[16:29:15.211][LoggingMessageHandler][Info   ] [267188ca] <Server start> GET http://localhost/versions
[16:29:15.213][LoggingMessageHandler][Info   ] [248eae3d] <Server end> GET http://localhost/license/details -> 200 OK (took 17ms)
[16:29:15.217][LoggingMessageHandler][Info   ] [267188ca] <Server end> GET http://localhost/versions -> 200 OK (took 5ms)
[16:29:15.225][LoggingMessageHandler][Info   ] [ce7db7c5] <Server start> GET http://localhost/docker
[16:29:15.228][LoggingMessageHandler][Info   ] [ce7db7c5] <Server end> GET http://localhost/docker -> 200 OK (took 3ms)
[16:29:15.243][LoggingMessageHandler][Info   ] [a39662ff] <Server end> GET http://localhost/kubernetes -> 200 OK (took 51ms)
[16:29:15.361][LoggingMessageHandler][Info   ] [18128aad] <Server start> GET http://localhost/registry/user
[16:29:15.364][LoggingMessageHandler][Info   ] [18128aad] <Server end> GET http://localhost/registry/user -> 404 NotFound (took 2ms)
[16:29:15.679][GoBackendProcess  ][Info   ] external: GET /system/editor 200 \"axios/0.19.0\" \"\
[16:30:30.328][LoggingMessageHandler][Info   ] [c9126bea] <Server start> GET http://localhost/desktop/diagnose
[16:30:30.413][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[16:30:30.416][LoggingMessageHandler][Info   ] [c9126bea] <Server end> GET http://localhost/desktop/diagnose -> 204 NoContent (took 87ms)
[16:30:30.626][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[16:30:30.627][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[16:30:30.629][GoBackendProcess  ][Info   ] mutagen sync list --output json
[16:30:36.250][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[16:30:36.250][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[16:32:28.396][FeedbackWindow    ][Info   ] Uploading diagnostics...
[16:32:28.398][Diagnostics       ][Info   ] Uploading diagnostics 7CAB732C-4FC8-4B62-A480-A1A519BE4144/20200513142901
[16:32:29.827][Diagnostics       ][Info   ] Uploaded succesfully diagnostics 7CAB732C-4FC8-4B62-A480-A1A519BE4144/20200513142901

**Comment by mat007** [comment] 2020-05-13 14:48
Thanks for the report, I believe it’s a duplicate of #6651

**Closed by mat007** 2020-05-13 14:48 UTC
Labels: version/2.3.0.2
