### ISSUE TITLE
Docker Desktop 2.2.0.0 breaks file sharing of nested volumes

### ISSUE THREAD

**Issue by johnmreynolds** [docker/for-win#5574] opened 2020-01-23 16:32 UTC
Diagnostics ID: AB6364B2-C8B0-4F60-99AB-7024A7732124/20200123161601

We have docker-compose.yml files which contain nested volume definitions. Probably not the best practice, but convenient and works on previous versions. For example:

        volumes:
            - .:/mavens/work
            - ../../libs/aws/mklibs/aws:/mavens/work/mklibs/aws

which maps the current directory to /mavens/work and another directory to a sub-directory of /mavens/work

### Expected behavior

The filesystem as appearing in the container is the union of the files in the sub-directory and the parent directory. This worked in previous versions.

### Actual behavior

The parent directory files are shared correctly, but the folders below are empty.

Also, in the host filesystem, empty directories are created for the sub-directories.

### Information

  - Is it reproducible?

Seems to always occur. Ordering of the volume mapping doesn't seem to matter - either way around only the parent directory is visible.

  - Is the problem new?

Yes, seems to be new with the current docker desktop (which seems to have a new implementation of file sharing).

  - Did the problem appear with an update?

Yes, when updating to the latest Docker Desktop.

  - Windows Version: 

Windows 10 1909 18363.535

  - Docker Desktop Version:

2.2.0.0 (42247)

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

No.

### Steps to reproduce the behavior

Make a docker compose file for an image with nested volumes as given in an example above.

run the container with -entrypoint bash, and note that the volume mapping doesn't work.

**Comment by johnmreynolds** [comment] 2020-01-23 16:36
I forgot to mention that I did confirm that the other shares do work if the parent directory is not shared.

i.e. removing the parent share from the initial example:

        volumes:
            - ../../libs/aws/mklibs/aws:/mavens/work/mklibs/aws

does indeed populate /mavens/work/mklibs/aws with the expected files. But the original example:

        volumes:
            - .:/mavens/work
            - ../../libs/aws/mklibs/aws:/mavens/work/mklibs/aws

leaves /mavens/work/mklibs/aws as an empty directory.

**Comment by mat007** [comment] 2020-01-23 16:44
Thanks for the report, this looks like a duplicate of ##5540 isn’t it?

**Comment by stephen-turner** [comment] 2020-01-23 16:53
Closing as dupe

**Closed by stephen-turner** 2020-01-23 16:53 UTC

**Comment by johnmreynolds** [comment] 2020-01-23 17:05
It is a dupe, yes. I failed to see that other issue when I searched.
