### ISSUE TITLE
Quotes unexpectedly stripped from RUN instruction

### ISSUE THREAD

**Issue by FFLSH** [docker/for-win#1031] opened 2017-08-23 07:52 UTC
**Repro steps:**
1. Create Dockerfile with the contents

```
FROM microsoft/nanoserver
RUN powershell new-item -path "C:/Program Files/mydir" -type "Directory"
```

2. Build via `docker build .`

The command which in the Dockerfile is `new-item -path "C:/Program Files/mydir"` ends up running as `new-item -path C:/Program Files/mydir` (without the quotes) causing the command to fail.

The workaround for this is to modify the command to `new-item -path \"C:/Program Files/mydir\"` (escaping the quotes) but this is ugly and ruins syntax highlighting in some editors.

For those not wanting to manually reproduce, here is the error:

```
New-Item : A positional parameter cannot be found that accepts argument
'Files/mydir'.
At line:1 char:1
+ new-item -path C:/Program Files/mydir -itemtype Directory;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindin
   gException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell
   .Commands.NewItemCommand
```

**Comment by friism** [comment] 2017-08-23 13:39
Can you use single-quote instead? Also see: https://docs.docker.com/engine/reference/builder/#shell

**Comment by FFLSH** [comment] 2017-08-25 08:06
@friism 
That does work for the original case, but consider this one:

```
FROM microsoft/nanoserver

ENV DIRNAME=MYDIR

RUN powershell mkdir 'C:/Program Files/$ENV:DIRNAME'
```

Results in an error because powershell interprets `$ENV:DIRNAME` as a literal string due to single quotes. Changing it to double quotes as such:

```
FROM microsoft/nanoserver

ENV DIRNAME=MYDIR

RUN powershell mkdir 'C:/Program Files/$ENV:DIRNAME'
```

Results in `$ENV:DIRNAME` being successfully expanded by powershell, but the original issue recurs and the command fails as it sees `C:/Program` and `Files/MYDIR` as two arguments to `mkdir`

**Comment by friism** [comment] 2017-08-25 14:30
Can you use `$Env:ProgramFiles`? I think that's more correct anyway.

@jhowardmsft may have more insight.

**Comment by FFLSH** [comment] 2017-08-25 14:49
Maybe, but this was just a basic example. The actual use case has many different permutations.

**Comment by jhowardmsft** [comment] 2017-08-25 15:03
https://docs.docker.com/engine/reference/builder/#escape I think you're running afoul of this in the dockerfile docs: 'Note that regardless of whether the escape parser directive is included in a Dockerfile, escaping is not performed in a RUN command, except at the end of a line.'  That, and the way in which PS trays single and double quotes differently for variable expansion. One alternate is to use the JSON form. 

An alternate (not tested as typing on phone), just RUN mkdir %variable%. May need double quotes around %s there. This uses cmd as the shell. 

Pretty sure another alternate is to use the SHELL command to change the shell to PS then you won't have double escaping from cmd (default shell) invoking PS like you currently have.

**Comment by FFLSH** [comment] 2017-08-26 07:19
The quoted part of the docs brings more confusion.. I wasn't doing any sort of escaping in the problematic `RUN` instruction, but in the workaround I am doing escaping.

This seems incredibly complex for such a simple instruction. Why do we not just take the `RUN` instruction (e.g. `mkdir "C:/Program Files/mydir"`), prepend the `SHELL`, expand any build arguments, and run it in the container?

**Comment by NickDarvey** [comment] 2018-05-04 00:51
Variable expansion in strings in PowerShell is pretty common.
I haven't been able to find a good way to do this, other people seem to ditch variable expansion and just [use string formatting instead](https://github.com/StefanScherer/dockerfiles-windows/blob/5095fdcebbb4663d20d515d903d95828c3756a2d/python/Dockerfile#L10).

Idk if I can do this, but...
/remove-lifecycle stale

**Comment by NickDarvey** [comment] 2018-05-04 00:58
Okay, this helps: [Understanding quotes](
https://github.com/StefanScherer/dockerfiles-windows/tree/789fa0b54c0d0263fa9464025cfe12ec2fe0cd6c/quotes)

**Comment by rn** [comment] 2018-05-07 12:26
Closing this as this is not directly related to the Docker for Windows application (more a general Windows container question) and looks like this is resolved as well.

**Closed by rn** 2018-05-07 12:26 UTC

**Comment by MagicShoebox** [comment] 2019-02-14 18:07
@rn 

I believe this is still a legitimate issue.

To illustrate, I'm using powershell's Set-PSDebug command which lets us see the raw text received by powershell, before it parses the quotes. (e.g. >>>> echo "hello").

Host (Expected Behavior):
```
PS C:\> Set-PSDebug -Trace 1; echo "hello"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo "hello"
hello
```

Container:
```
Step 1/3 : FROM mcr.microsoft.com/windows/servercore:1803
Step 2/3 : SHELL ["powershell", "-Command"]
```

Experiment 1 (Actual Behavior):
```
Step 3/3 : RUN Set-PSDebug -Trace 1; echo "hello"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo hello
hello
```

Experiment 2 (Workaround - escaped with backslash):
```
Step 3/3 : RUN Set-PSDebug -Trace 1; echo \"hello\"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo "hello"
hello
```

Experiment 3 (#escape=` has no affect):
```
Step 3/3 : RUN Set-PSDebug -Trace 1; echo "hello"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo hello
hello
```

Experiment 4 (#escape=` has no affect):
```
Step 3/3 : RUN Set-PSDebug -Trace 1; echo \"hello\"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo "hello"
hello
```

Experiment 5 (#escape=` has no affect):
```
Step 3/3 : RUN Set-PSDebug -Trace 1; echo `"hello`"
DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> echo `hello`
hello`
```

Version info:
```
Version 1803 (OS Build 17134.523)

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:50:10 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by jhowardmsft** [comment] 2019-02-14 18:37
FWIW, I've been doing a lot of work around this recently, and hopefully all these hacks should be a thing of the past soon. See https://github.com/moby/moby/pull/38541, and specifically the commit in that PR "Generate OCI spec that remote runtime...". The PR isn't yet ready for full submission to moby and that commit is just a piece of the larger thing I'm working on. @StefanScherer would be interesting if you have time to put that PR through it's paces for quoting on the RUN statement in the builder, but skip the containerd part.

**Comment by StefanScherer** [comment] 2019-02-14 22:02
Thanks @jhowardmsft for that hint. Do you mean cherry-picking https://github.com/moby/moby/pull/38541/commits/73963adda7878acc70d12ed47738e3344f667f37 and make a valid PR out of it?
Would love to help here as I struggled last week to find a workaround for some PowerShell commands in a Dockerfile.

**Comment by jhowardmsft** [comment] 2019-02-14 22:16
@StefanScherer Can just build docker out of that branch in 38541. I'm not sure that one cherry-pick will be sufficient as it builds on the first commit and would also need the updated runtime-spec from yet another commit. I'll be submitting that open WIP PR including the fix in the next week or two once I've got more wrinkles resolved.

**Comment by StefanScherer** [comment] 2019-02-14 22:18
@jhowardmsft Ah ok. Sure I can help testing it. 👍
