### ISSUE TITLE
Cannot share drive if windows account has no password

### ISSUE THREAD

**Issue by Mikaka27** [docker/for-win#352] opened 2016-12-23 14:04 UTC
### Expected behavior
Don't ask for credentials if local windows user doesn't have any password.

### Actual behavior
Impossible to click ok while leaving the password field empty.

### Information

  - Diagnostic ID: B77F5BF3-DCFB-4AB3-BEC4-762CBCE8E736/2016-12-23_15-00-47
  - Windows 10 anniverssary

### Steps to reproduce the behavior

  1. Install docker for windows
  2. Make sure local user (admin type) has no password set
  3. Try to share C drive
  4. Try to click ok while leaving password field empty

**Comment by Arlington1985** [comment] 2017-01-07 14:32
Same problem. After setting password was possible to share

**Comment by wiktorn** [comment] 2017-01-11 15:27
Also - if you set a password, share, and then change back the user settings to no password, the settings menu will show that sharing is enabled but once you reboot the OS, actual volume mounts will silently fail.

**Comment by rneugeba** [comment] 2017-01-11 20:26
Thanks for the report. This is a duplicate of #366 and we commented on there that we rely on Authenticated Samba mounts, so this won't fix.

**Closed by rneugeba** 2017-01-11 20:26 UTC
Labels: area/mounts, status/0-triage
