### ISSUE TITLE
Docker cannot be started with an error on failed contact to the database on \\.\pipe\dockerdatabase:... 

### ISSUE THREAD

**Issue by connorzhao-infotrack** [docker/for-win#1108] opened 2017-09-20 00:04 UTC
### Expected behavior
Docker successfully run
### Actual behavior
Docker did not run
### Information

  Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145)

### Part of the error log

Version: 17.06.2-ce-win27 (13194)
Channel: stable
Sha1: 428bd6ceae2994bd2fc2a72ec122507abe2cf526
Started on: 2017/09/20 09:58:20.367
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\Connor.zhao\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:58:20.459][GUI            ][Info   ] Starting...
[09:58:21.119][Tracking       ][Info   ] Crash report and usage statistics are enabled
[09:58:21.121][SegmentApi     ][Info   ] Usage statistic: appLaunched
[09:58:21.169][NamedPipeClient][Info   ] Sending Version()...
[09:58:21.173][NamedPipeClient][Info   ] Received response for Version
[09:58:21.174][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:58:21.173][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:58:21.227][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[09:58:21.228][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[09:58:21.228][PowerMode      ][Info   ] Stop
[09:58:21.228][HyperV         ][Info   ] Stop
[09:58:21.229][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:58:21.234][HyperV         ][Info   ] Script started at 09:58:21.234
[09:58:21.246][HyperV         ][Info   ] Module loaded at 09:58:21.245
[09:58:21.254][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[09:58:21.254][HyperV         ][Debug  ] [stop] took 00:00:00.0259880 to run
[09:58:21.254][OptimizeDisk   ][Info   ] Optimize
[09:58:21.254][PowerShell     ][Info   ] Run script...
[09:58:21.261][Moby           ][Info   ] Stop
[09:58:21.267][HyperVGuids    ][Info   ] Installing GUIDs...
[09:58:21.267][PowerMode      ][Info   ] Start
[09:58:21.267][HyperV         ][Info   ] Create
[09:58:21.267][Firewall       ][Info   ] Removing all existing rules...
[09:58:21.267][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:58:21.269][HyperVGuids    ][Info   ] GUIDs installed
[09:58:21.273][HyperV         ][Info   ] Script started at 09:58:21.273
[09:58:21.285][HyperV         ][Info   ] Module loaded at 09:58:21.285
[09:58:21.334][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:58:21.402][Firewall       ][Info   ] All existing rules are removed.
[09:58:21.402][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:58:21.404][Firewall       ][Info   ] Opening ports for SMB...
[09:58:21.413][Firewall       ][Info   ] Ports are opened
[09:58:21.926][HyperV         ][Info   ] Switch created.
[09:58:22.306][HyperV         ][Info   ] Set IP address on switch
[09:58:22.319][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[09:58:22.813][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:58:22.964][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[09:58:23.226][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:58:23.329][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[09:58:23.684][HyperV         ][Info   ] Disabled Guest Service Interface
[09:58:23.694][HyperV         ][Info   ] Enabled Heartbeat
[09:58:23.717][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:58:23.728][HyperV         ][Info   ] Enabled Shutdown
[09:58:23.738][HyperV         ][Info   ] Enabled Time Synchronization
[09:58:23.757][HyperV         ][Info   ] Disabled VSS
[09:58:23.991][HyperV         ][Info   ] VM created.
[09:58:23.991][HyperV         ][Debug  ] [create] took 00:00:02.7238635 to run
[09:58:23.991][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[09:58:24.030][Database       ][Info   ] Generating CA Cert Bundle
[09:58:24.055][Database       ][Info   ] CA Cert Bundle Generated
[09:58:24.084][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[09:58:24.085][DataKit        ][Info   ] Thread 1 killed on uncaught exception Unix.Unix_error(40, "send_notification", "")

[09:58:24.085][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[09:58:24.085][DataKit        ][Info   ]                    Unix.Unix_error(Unix.ENOTSOCK, "select", "")

[09:58:24.085][DataKit        ][Info   ]                    

[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true}
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:58:24.093][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:58:25.439][Database       ][Error  ] 2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:24 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:25 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:25 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:58:25.439][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true}
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:58:26.439][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:58:27.687][Database       ][Error  ] 2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:26 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:27 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:27 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:27 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:27 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/20 09:58:27 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:58:27.687][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
### things I have tried
1. reinstall the OS will solve the problem, but i occurred again after one month, and I dont want to reinstall it again
2.following the step provided by @jasonbivins in #1066  did not solve my problem

**Comment by jasonbivins** [comment] 2017-09-20 18:12
Hi @connorzhao-infotrack 
Can you post a diagnostic ID?  From what I see here, it looks like the Docker.for.Windows service isn't connecting properly.

**Comment by connorzhao-infotrack** [comment] 2017-09-21 06:01
thx for reply, My diagnostic ID is: 90D99FC7-2188-4F0A-B352-09AEE9B6B8F0/2017-09-21_16-00-32 @jasonbivins

**Comment by Vetje** [comment] 2017-09-22 13:40
I'm having this same problem, however when I 'Switch to Windows container...' Docker works. Then, when I switch back to Linux containers the same error appears.

**Comment by jasonbivins** [comment] 2017-09-28 15:48
Hi @connorzhao-infotrack    It looks like the Docker for Windows service isn't connecting.  Can you try using the latest build ? We have been working on a lot of bugfixes around the connectivity.

**Comment by endersonmaia** [comment] 2017-10-06 18:05
I get the same problem here.

My diagnostic id : AA21F51C-59B8-4E2D-8F8E-E251CDFFDDBA/2017-10-06_15-02-27

**Comment by djs55** [comment] 2017-11-30 17:12
I think
```
Thread 1 killed on uncaught exception Unix.Unix_error(40, "send_notification", "")
```
implies this is a duplicate of #498. There should be a fix in the edge branch shortly.

Thanks for your report and your patience.

**Closed by djs55** 2017-11-30 17:12 UTC
Labels: area/network, area/windows 10, status/0-triage
