### ISSUE TITLE
Access denied when starting a process under non-admin account (Windows 10 20H2)

### ISSUE THREAD

**Issue by rwasef1830** [docker/for-win#10903] opened 2021-04-12 13:22 UTC
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 29F68CC6-5731-4A9B-BD70-FAF97091F99C/20210412131443

### Actual behavior
1. Update Docker for Windows Desktop.
2. Launch it.
3. Crash

### Expected behavior
It works

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

100% reproducible. Windows 10 20H2. Old docker install in WSL2 mode upgraded to latest. I am trying to find the name of the process it is launching. It maybe an antivirus false positive by Windows Defender denying access to the process, however there is no notification from it. Turning off Windows Defender realtime protection does not solve it.

**Comment by stephen-turner** [comment] 2021-04-12 13:29
Thanks for the report, I think this is a dupe of #10881. Workaround is in that ticket.

**Closed by stephen-turner** 2021-04-12 13:29 UTC
