### ISSUE TITLE
WSL2 kills file performance

### ISSUE THREAD

**Issue by kellytrinh** [docker/for-win#7086] opened 2020-06-06 14:28 UTC
Just got the May 2020 Windows update that includes support for WSL2.  Said yes to Docker migration to WSL2 backend and found that the new approach really kills file performance.  My file-operation-heavy workload went from 2 minutes to completion to 20 minutes.

It is wonderful to have the lowered CPU/Mem usage of WSL2 but this file performance is unusable.

**Comment by mat007** [comment] 2020-06-07 04:49
Duplicate of #6742

**Closed by mat007** 2020-06-07 04:49 UTC
