### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ybeloued** [docker/for-win#11519] opened 2021-06-24 15:05 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: n/a

### Actual behavior

After downloading "Docker Desktop Installer.exe", but once I tried to execute it, I'm getting the following error:

![image](https://user-images.githubusercontent.com/70377124/123284908-86051e80-d504-11eb-8fc4-b9d457cfa8ec.png)

from the screenshot I could say that there is a misconfiguration since my user directory is *Yassine.Beloued*

Because of the installation failed, I cannot generate Diagnostic ID

### Information

  - Windows Version: Windows 10 Entreprise
  - Docker Desktop Version: 3.5.0
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Set your user directory with dots, the installer will remove dots from your user's directory.
  2. Seems like I have the same [issue](https://github.com/docker/for-win/issues/11448).

**Comment by Henrique-Alvares** [comment] 2021-06-24 16:06
Just had the same problem, had a dot on my username, ended up having to create the path without the dot manually to verify that it would work.

**Comment by ybeloued** [comment] 2021-06-24 16:10
Yes, but in my case I cannot do it, because of the windows domain.

Could someone help to figure out this bug please?

**Comment by stephen-turner** [comment] 2021-06-24 16:48
Thanks for the report. Closing as dupe of #11514. We plan to have a patch later today.

**Closed by stephen-turner** 2021-06-24 16:48 UTC
