### ISSUE TITLE
Docker doesn't start up anymore in Windows 10

### ISSUE THREAD

**Issue by Vatvat99** [docker/for-win#495] opened 2017-02-13 14:20 UTC
### Expected behavior

Start Docker for Windows.

### Actual behavior

After installing Virtualbox, Docker for Windows doesn't start on Windows 10, and display this error : 
La référence d'objet n'est pas définie à une instance d'un objet.
   à Docker.Program.Run(IReadOnlyCollection`1 args)

I have uninstalled Virtualbox but Docker still doesn't start.

### Information

  - Diagnostic ID : A18A9802-F2F7-4010-B2D4-D1996717C708/2017-02-13_15-11-18

### Steps to reproduce the behavior

  1. Install Virtualbox 
  2. Now, Docker doesn't start
  3. Uninstall Virtualbox
  4. Docker does'nt start

**Comment by rneugeba** [comment] 2017-02-13 15:06
Thanks for your report. It looks like this error happens during an upgrade?

Have you tried to un-install the application, download the new installer from https://docs.docker.com/docker-for-windows/ and install it from fresh?

Thanks

**Comment by Vatvat99** [comment] 2017-02-13 15:36
Well, I tried to un-install and install again from the new installer, just to give it a try because I already did that a couple of times last friday, and also this morning, and guess what, Docker is now running ! So you solved the problem, thx so much ! 🥇 

I thought it came from the install of Virtualbox, as it is not compatible with docker, but I also did an upgrade to docker v1.13.1 on friday. Do you think it came from this installer ? Is the installer has been changed since friday ?

**Comment by rneugeba** [comment] 2017-02-13 15:52
@Vatvat99 thanks for getting back. weird. I don't think we changed anything with the installer (or much else) apart from a docker update since the previous beta. The changelog doesn't show anything relevant. Weird...I suspect it might be related to your system, maybe some remnants of virtualbox. Since this will be almost impossible to root cause and since it's now all working for you, I'm closing the issue.

**Closed by rneugeba** 2017-02-13 15:52 UTC
Labels: status/0-more-info-needed, version/1.13.0

**Comment by jrmclau** [comment] 2017-07-21 00:34
My solution was to set the Docker for Windows Service to "Manual" from "Disabled" in the Windows Services Management Console (services.msc). Is there a reason this service is defaulted to disabled, or could we just have it default to manual upon installation?
