### ISSUE TITLE
Can we run solaris/smartos on docker for-win?

### ISSUE THREAD

**Issue by kasper3** [docker/for-win#1781] opened 2018-03-03 23:37 UTC
When I switch to Linux Containers, I can run Linux containers. However, if i try something like `docker run -it docker pull humantrust/solaris_ci_baseimage`, it throws:

```
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

will it require to configure solaris VM in Hyper-V and somehow integrate it with docker to be able to run this `solaris_ci_baseimage`? I ultimately want to try out SmartOS, is it possible on Windows+Hyper-V+Docker?

**Comment by rn** [comment] 2018-03-08 16:52
the problem is that you are trying to run the `docker` image (which you specify after the `-it`. This requires the docker socket to be available in the container.

If you drop the extra `docker pull` from your command line, like this:
```
docker run -it humantrust/solaris_ci_baseimage
```
it should work.

closing

**Closed by rn** 2018-03-08 16:52 UTC

**Comment by kasper3** [comment] 2018-03-08 17:21
It turned out it's not a solaris image after all

root@d41d597b9592:/# uname -a
Linux d41d597b9592 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
