### ISSUE TITLE
Huge Amounts of Utilized Memory on Windows 10

### ISSUE THREAD

**Issue by nostrebor** [docker/for-win#144] opened 2016-10-12 17:27 UTC
### Expected behavior
When I docker-compose down, containers should have their resources freed. 

### Actual behavior
After removing and killing containers, their RAM is still utilized, and not visible in Windows Task Manager.

### Information

  - Diagnostic ID: 8784047B-D986-4DFE-847B-921694A3CEF6/2016-10-12_10-22-32
  - Running an ELK stack that is utilizing ~20gb of RAM when active.

### Steps to reproduce the behavior

  1. Start a set of containers that use a large amount of RAM using docker-compose up -d
  2. docker-compose down

**Comment by rneugeba** [comment] 2016-10-14 12:20
@nostrebor thanks for reporting the issue.

You seem to have set the memory for the VM to 20GB. We currently do not configure dynamic memory for the VM because that may cause other issues, like, for example, intermittent failures when your containers require more memory, but there is non available on the host.

So, since you configured Docker for Windows to use 20G of memory, this is expected behaviour and I'm closing this issue.

Your case is somewhat extreme, so you may want to change the default setting in Hyper-V manager, MobyLinuxVM -> Settings -> Memory and switch to dynamic memory with appropriate ranges.

**Closed by rneugeba** 2016-10-14 12:20 UTC
Labels: area/hyper-v
