### ISSUE TITLE
Docker volumes stop working unexpectedly

### ISSUE THREAD

**Issue by mauro-dellachiesa** [docker/for-win#157] opened 2016-10-19 15:39 UTC
### Expected behavior

Docker volumes continue to work, as long as the corresponding settings for Docker are not modified/updated.
### Actual behavior

Docker volumes stop working unexpectedly
### Information
- Diagnostic ID: 7EBFAC4B-2E44-489E-8838-9F0B9CC9F88E/2016-10-19_11-46-54
- page URL if this is a docs issue or the name of a man page
- Windows 10 Pro 1607, 14393.321
### Steps to reproduce the behavior
1. Reboot the PC
2. Work with different containers that use volumes. Lately I've been using the docker-compose found here: https://github.com/deviantony/docker-elk, but once I notice they stop working I test with:
   **docker run --rm -v c:/Users:/data alpine ls /data** 
3. After some undetermined time and "downing" and "upping" the docker compose, volumes stop working.

I initially thought it was caused because I left the containers running and hibernated my PC. But today I noticed that volumes stopped working without doing that.
Only rebooting the PC makes the volumes work again. Resetting the shared drives credentials nor restarting docker makes the volumes work again.

**Comment by sskorol** [comment] 2016-10-19 20:01
Noticed something similar with beta. After rebooting, shared volumes stopped working. I've been playing with `net share` and `resetting creds` to make it work again.

**Comment by simonferquel** [comment] 2016-10-20 07:52
@mauro-dellachiesa @sskorol do you have a VPN connection or a connection profile change (private, public or domain) when this happen ?

**Comment by sskorol** [comment] 2016-10-20 09:04
@simonferquel I'm using Docker on my local PC, which is not a part of any domain or VPN. Not sure if it'd help, but my network configuration uses automatic IP / DNS resolution (which is required by internet provider).

**Comment by simonferquel** [comment] 2016-10-20 09:36
@mauro-dellachiesa I see from the logs that your machine is a member of a domain. It seems possible that Windows is switching from private to public or domain network profile, and that the Windows Firewall blocks file sharing when it happens. Can you look at your inbound firewall rules (Control Panel / System and Security / Windows Firewall / Advanced Settings / Inbound Rules) and enable all rules named "File and Printer Sharing (SMB-In)" ?
We have a fix for that internally that should make it in a future beta (hopefully beta 30)

**Comment by simonferquel** [comment] 2016-10-20 09:37
@sskorol Can you try the same operation ?

**Comment by sskorol** [comment] 2016-10-20 10:07
@simonferquel just tried. This rule was disabled for `domain` and enabled for `private / public`. However, Windows Firewall is fully managed by `Kaspersky Total Security` on my PC. So not sure if these rules are applied when KTS is enabled. Anyway, just tried to run `docker run --rm -v c:/Grid/uploads:/data alpine ls /data` and it lists all files / subfolders correctly (assuming that I tried it after nightly power off).

**Comment by simonferquel** [comment] 2016-10-20 12:09
@sskorol We have a known issue related with 3rd party firewall interfering with samba share. In beta 30, we'll try to detect these cases, and provide guidance how to configure your firewall. 
The main thing is that we need to be able to connect to samba shares from our Linux VM to the Windows host. For that we need a rule allowing inbound TCP traffic on 10.0.75.1:445 from 10.0.75.2:* for whatever network profile is active. If you can create this rule in Kaspersky, you should be good !

**Comment by mauro-dellachiesa** [comment] 2016-10-20 13:02
Thanks @simonferquel. I'll give it a try and update my findings here.

**Comment by mauro-dellachiesa** [comment] 2016-10-21 14:29
Guys,
Today after starting my PC from hibernation I found that Docker was not working correctly. Tried this:
`C:\Users\Usuario>docker run --rm -v c:/Users:/data alpine ls /data`
And got the error:

> docker: Error response from daemon: mkdir /c: file exists.

After restarting Docker and re running the same command the error disappeared, but volumes do not work.
Here is another diagnostic I uploaded: 7EBFAC4B-2E44-489E-8838-9F0B9CC9F88E/2016-10-21_11-23-42

BTW, I do have a VPN set up. Let me know if you need some additional information.

Thanks!

**Comment by casperdcl** [comment] 2016-10-22 12:30
I get this every time I resume from sleep. Solve it by going to docker settings and un-sharing then re-sharing `C`.

**Comment by friism** [comment] 2016-10-22 15:34
@casperdcl can you run a diagnostic trace when sharing is not working and post the id here?

**Comment by simonferquel** [comment] 2016-10-24 10:49
@mauro-dellachiesa, @casperdcl Should be related to the "Network profile change" bug we have. Next beta should fix it.

**Comment by casperdcl** [comment] 2016-10-24 14:45
@friism I replied to your message 2 days ago via email but it isn't showing up here:

> Could do on Monday. The specific case I have is Win10+hyperV+docker+sharing C.
> 
> As far as I remember, base case reproducible:
> 
> 1. docker run --it -v "C:\\Users:/windows" ubuntu:16.04
> 2. cd /windows && ls # no prob
> 3. standby then resume
> 4. ls # error fs not accessible
> 5. Docker setting -> Shared Drives -> disable then enable C.
> 6. ls # works again 

Do you still want a trace?

**Comment by friism** [comment] 2016-10-24 15:04
@casperdcl let's hang back and see if the fix that @simonferquel mentioned works (should be coming in a couple days)

**Comment by casperdcl** [comment] 2016-10-25 18:21
Could do on Monday. The specific case I have is Win10+hyperV+docker+sharing
C.

As far as I remember, base case reproducible:

1. docker run --it -v "C:\\Users:/windows" ubuntu:16.04
2. cd /windows && ls # no prob
3. standby then resume
4. ls # error fs not accessible
5. Docker setting -> Shared Drives -> disable then enable C.
6. ls # works again

**Comment by cfstras** [comment] 2016-11-10 12:49
Same issue here. Sometimes Standby/Hibernate triggers it, sometimes it only happens after ~20 containers with mounts created&destroyed.

Windows 10.0.14393, Docker 1.12.3-beta29.3 (8418). Can't update further because #54 also affects me and I can't recreate images right now.

**Comment by scmrus** [comment] 2016-11-18 08:46
Same issue. Standby/Hibernate triggers it.

Windows 10, Docker 1.12.3-beta30.1 (8711).

**Comment by pmsousa** [comment] 2016-11-23 10:13
@scmrus Can you detail the steps you've took to make error disappear? I've got the exact same build - Windows 10, Docker 1.12.3-beta30.1 (8711) - but I can't manage to make it work again...

**Comment by scmrus** [comment] 2016-11-25 05:42
Hi, @pmsousa.
Unfortunately, re-sharing drive C not working now for me. But docker full restart works.

**Comment by scmrus** [comment] 2016-12-23 03:34
btw, looks like bug was fixed. I don't have any problems last days.

**Comment by rneugeba** [comment] 2016-12-29 10:28
@scmrus glad to hear it's working now. @pmsousa @cfstras @casperdcl do you still have the issue with the latest Beta?

**Comment by pmsousa** [comment] 2016-12-29 12:43
@rneugeba Nope, problem solved!

**Comment by rneugeba** [comment] 2017-01-07 16:29
thanks for getting back. Closing issue.

**Closed by rneugeba** 2017-01-07 16:29 UTC
Labels: status/2-in-progress, status/5-will-be-closed

**Comment by SG5** [comment] 2017-01-28 10:48
Have same issue with stable docker 1.12.6 (9655), re-sharing solved problem
