### ISSUE TITLE
File sharing credentials loop

### ISSUE THREAD

**Issue by radovanobal** [docker/for-win#5691] opened 2020-02-04 22:47 UTC
- [✓] I have tried with the latest version of my channel (Stable or Edge)
  - [✓] I have uploaded Diagnostics
  - Diagnostics ID: 94D80FB4-300E-457A-9CD3-456554C92768/20200204224950

### Expected behavior
Accept the credentials once and complete the file share enable for the drive

### Actual behavior
The file share does not complete and docker gets stuck in a credentials popup loop

### Information

  - Windows Version: 10.0.18363 Build 18363 / Windows 10 Pro
  - Docker Desktop Version: 2.2.0 42247 / Stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No VM

### Steps to reproduce the behavior

  1. open settings 
  2. add drive to be shared under resources
  3. enter password

Power shell:
> net share C=C:\ /grant:#####,FULL /CACHE:None
C was shared successfully.

> net use \\########\c /user:##### ######
The command completed successfully.

> net use \\########\c /delete
\\#######\c was deleted successfully.

**Comment by joesaunderson** [comment] 2020-02-04 23:06
I also have this issue, downgraded to 2.1.0.5 until fixed

**Comment by radovanobal** [comment] 2020-02-05 00:22
Downgraded to 2.1.0.5 
Similar error: 
docker.exe: Error response from daemon: Drive sharing failed for an unknown reason.

**Comment by mat007** [comment] 2020-02-05 05:33
This looks like a duplicate of #5567

**Closed by mat007** 2020-02-05 05:33 UTC
