### ISSUE TITLE
Please stop leaving your installation log file in my C:\Users directory!!!

### ISSUE THREAD

**Issue by OOPMan** [docker/for-win#6909] opened 2020-05-27 23:05 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When Docker For Windows installs or updates, it cleans up its logfile when its done.

### Actual behavior
When Docker For Windows installers or updates, it leaves a extensionless logfile in my `C:\Users` directory. Every time I start Windows there is an attempt to open this file which fails, popping up an error message. I was only able to work out what was going on by checking my Recent Files list and noting the file in question:

![image](https://user-images.githubusercontent.com/248980/83080563-8c4c7100-a04c-11ea-8390-35bdba6e8d85.png)

![image](https://user-images.githubusercontent.com/248980/83080590-a2f2c800-a04c-11ea-8c50-919d315b38dd.png)

I suspect the issue may be related to something around handling paths with spaces in them? 

### Information

  - Windows Version: Windows 10 Pro (1909 18363.836)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Restart Windows
  3. Observe Windows attempt to open extension-less log file and throw an error

**Comment by mat007** [comment] 2020-05-28 05:11
Thanks for the report, I believe this a duplicate of #6552

**Closed** 2020-05-29 13:16 UTC
Labels: version/2.3.0.3
