### ISSUE TITLE
Filesystem Events (fsevents) not propagated in ubuntu on windows 10

### ISSUE THREAD

**Issue by aeos** [docker/for-win#1115] opened 2017-09-21 22:27 UTC
### Expected behavior
When mounting a directory into a container, editing a file should trigger a file event which allows tools like webpack dev to hot reload.
### Actual behavior
no file events are propagated to the container.

**Comment by friism** [comment] 2017-09-21 23:41
This is a duplicate of https://github.com/docker/for-win/issues/56

Closing

**Closed by friism** 2017-09-21 23:41 UTC
