### ISSUE TITLE
Installing a fresh new docker CE for Windows and cant enable Hyper-V.

### ISSUE THREAD

**Issue by victor-frag** [docker/for-win#2255] opened 2018-07-25 14:01 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Downloaded docker CE for windows on docker storage website.
  2. Installed the docker application.
  3. Logged out as the docker asked to do.
  4. Docker application asks for enable Hyper-V and restart the machine.
  5. The step 4 fails.

Exception occured:

Fluxo binário não contém um BinaryHeader válido, '0'. Possíveis causas: fluxo inválido ou alteração da versão do objeto entre a serialização e a desserialização.
   em Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) na C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:linha 36
   em Docker.WPF.BackendClient.InstallFeatures(Feature[] features) na C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:linha 111
   em Docker.Notifications.BackendInstallFeatureExceptionReplier.<>c__DisplayClass10_0.<AskToUser>b__0() na C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Notifications\BackendInstallFeatureExceptionReplier.cs:linha 103
   em Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() na C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:linha 59

**Comment by gtardif** [comment] 2018-07-25 14:37
Pleas provide the diagnsotic ID in the issue (you can re-run diagnostics if you don't have your previous diagnosticID, and copy/paste it here once diagnostics are uploaded)

**Comment by DogFive** [comment] 2018-07-25 20:19
@victor-frag 
What version of windows are you using?

**Comment by gtardif** [comment] 2018-07-25 21:37
Closing as a duplicate of https://github.com/docker/for-win/issues/2262.
As a workaround if Hyper-V is available on your machine, you can enable "Hyper-V" and "containers" features in "Windows Features" (search for "Turn Windows features on"), that will need a computer restart, then start Docker for Windows

**Closed by gtardif** 2018-07-25 21:37 UTC
