### ISSUE TITLE
Proxy settings changed through UI are not applied

### ISSUE THREAD

**Issue by Burgito** [docker/for-win#5606] opened 2020-01-27 09:05 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: AEC6841C-1680-4FB0-BAB3-D81B2909FA18/20200127084947

### Expected behavior
Changing proxy settings through UI should be effective with docker cli

### Actual behavior
When proxy settings are changed through the UI, the "Apply & restart" doesn't make the changes effectives, initial is still visible with docker info command and is still used with different docker network accesses (docker login for example).

Restarting docker with the "Restart" button of the troubleshoot menu or with the "Restart" entry of the context menu on the docker icon in the taskbar doesn't make the changes effectives neither.

### Information
- Issue was not present in 2.1.0.5
- To make the changes effective, I've had to manually edit the files http_proxy.json and settings.json in C:\Users\*****\AppData\Roaming\Docker to make the change effective.
- Proxy was already set when I was using 2.1.0.5 (setting is imported)
- My docker version is 2.2.0, updated from 2.1.0.5
- Windows Version: Windows 10 Pro 1909 (18363.592)
- Docker Desktop Version: 2.2.0

### Steps to reproduce the behavior
1. Open docker desktop WebUi
2. Change you proxy settings
3. Apply & restart
4. Check your "docker info" command
New proxy settings should not be applied.

Please inform me if issue is not new.

**Comment by mat007** [comment] 2020-01-27 10:26
Thanks for the report, this looks like a duplicate of #5548

**Comment by mat007** [comment] 2020-01-27 10:28
Sorry, closed it too hastily, I meant to put a question mark as in «is it similar to #5548?».

**Comment by Burgito** [comment] 2020-01-27 15:59
No worries, 
I think it is actually very similar to #5548 except that I do not receive the "EOF" error and my proxy doesn't require any authentication.

The "reset to factory default" allowed me to have a normal behaviour.
So I think that there is indeed a problem with proxy settings and update from 2.1.0.5 to 2.2.0, but reset the app to factory default resolves it.

Thank you for your help and good luck to find what's happening ;)

**Comment by mat007** [comment] 2020-02-04 12:21
We have found and fixed an issue with the proxy settings not being properly migrated when upgrading from 2.1.0.5 to 2.2.0.0, thanks for your help!

**Comment by stephen-turner** [comment] 2020-02-11 13:45
We have just released 2.2.0.3, which fixes this issue, so closing this ticket. In case any Edge users are watching this ticket, it will be on the Edge channel tomorrow too.

**Closed by stephen-turner** 2020-02-11 13:45 UTC
Labels: status/0-triage, version/2.2.0.0
