### ISSUE TITLE
Enable time sync for MobyLinuxVM

### ISSUE THREAD

**Issue by copitz** [docker/for-win#409] opened 2017-01-21 13:50 UTC
### Expected behavior

The time within docker containers should be the same as on the host.

### Actual behavior

The time within docker containers drifts by some seconds (interestingly mostly ahead). The problem can be solved by enabling **Integration Services > Time synchronization** in MobyLinuxVM settings - but after docker is restarted, its disabled again.

### Information

  - Diagnostic ID: 67F6E95C-33B0-4D03-A875-104DE60F3AEB/2017-01-21_14-45-43
  - Windows 10 Pro x64, Version 1607, Build 14393.693

### Steps to reproduce the behavior

  1. Start a docker container and run `date` - time drifts
  2. Tick `MobyLinuxVM > Settings > Integration Services > Time synchronization` in Hyper-V manager
  3. Start a docker container and run `date` - time is in sync
  4. Restart docker
  5. Start a docker container and run `date` - time drifts again
  6. `MobyLinuxVM > Settings > Integration Services > Time synchronization` is disabled

**Comment by justincormack** [comment] 2017-01-21 13:58
There are some bugs in the time integration service kernel modules for Linux against different Windows versions, which may well be related to this. cc @rneugeba

**Comment by copitz** [comment] 2017-01-21 16:16
@rneugeba Yes, this was after I enabled the TimeSync manually

**Comment by rneugeba** [comment] 2017-01-31 10:41
@mattmeye and @michaelva observed the same issue over on #418.

The next beta (beta40) has updated linux kernel patches which are supposed to handle the negotiation of the TimeSync protocol between the Linux VM and the Windows host correctly. I'll ping you here once it is released.

**Comment by rneugeba** [comment] 2017-01-31 16:03
We have just released Beta40 with the updated kernel. You can download it here: https://download.docker.com/win/beta/InstallDocker.msi. Could you try and see if it fixes your issue? If not, I'd be interested in seeing the diagnostics upload from it.
Thanks

**Comment by amrael** [comment] 2017-02-01 03:21
I too have the issue but my case is more critical.
The localtime of host, `Wed Feb   1 12:11:25 JST 2017` is fast-forwarded to `Web Feb   1 12:11:25 UTC 2017` on docker container that means the time on the container has +9 hours of time difference. So I'm required to enable Time Sync from Hyper-V manager every time I launch it.

Here's diagnostics,
AC405871-1670-4236-B7F4-5059EFCBD50E/2017-02-01_12-12-05

**Comment by amrael** [comment] 2017-02-01 03:25
I forgot to mention that Beta40 didn't help at all.

**Comment by tobias-kuendig** [comment] 2017-02-07 14:31
I am experiencing the problems reported in #72. If I shut down my host and reboot it after 5 minutes the time of all containers runs 5 minutes behind. Enabling time sync fixes this problem until the next reboot since the MobyLinuxVM gets recreated and the time sync setting gets disabled again.

I am running beta 40.

**Comment by rneugeba** [comment] 2017-02-10 14:43
I'm curious as to why the Time synchronisation service is not running. Is it not enabled by default or does it get disabled. We can't reproduce it here.

Could someone try the following:

- Exit the application
- In an elevated powershell: `& 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1' -destroy`. *Note* this will remove all your container images.
- in an elevated powershell: ` while ($true) { $ts = Get-VMIntegrationService mobylinuxvm -name "Time Synchronization"; Write-Output "$($ts.Enabled) $($ts.StatusDescription)"; Start-Sleep -s 1 }`
- Start the Docker for Windows application

The endless loop should start by printing errors (as the VM does not exists). Once the app is starting it will recreate the VM and the script should print the TimeSync VM integration service status.

It be interested in the output from the script.

thanks

**Comment by Crack** [comment] 2017-02-13 11:44
It errors with:
```powershell
Get-VMIntegrationService : No integration component with the given name could be found.
At line:1 char:23
+ ... ue) { $ts = Get-VMIntegrationService mobylinuxvm -name "Time Synchron ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-VMIntegrationService], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMIntegrationService
```

Names are localized:
```powershell
PS C:\WINDOWS\system32> Get-VMIntegrationService mobylinuxvm

VMName      Name                      Enabled PrimaryStatusDescription SecondaryStatusDescription
------      ----                      ------- ------------------------ --------------------------
MobyLinuxVM Interfejs usługi gościa   False   OK
MobyLinuxVM Puls                      False   OK
MobyLinuxVM Wymiana par klucz-wartość False   OK
MobyLinuxVM Zamykanie                 False   OK
MobyLinuxVM Synchronizacja czasu      False   OK
MobyLinuxVM VSS                       False   OK
```
("Time Synchronization" is "Synchronizacja czasu", and it's disabled)

MobyLinux.ps1 uses localized names instead of IDs, which fails on non-English systems:
```powershell
    $vm | Get-VMIntegrationService | ForEach-Object {
        if ($_.Name -eq "Heartbeat" -or $_.Name -eq "Shutdown" -or $_.Name -eq "Time Synchronization") {
            Enable-VMIntegrationService $_
        } else {
            Disable-VMIntegrationService $_
        }
    }
```

**Comment by rneugeba** [comment] 2017-02-13 13:45
@Crack Thanks for your report, but I can't repro it. I switched my computer to German and re-installed and get this:
```
PS C:\WINDOWS\system32> Get-VMIntegrationService mobylinuxvm

VMName      Name                               Enabled PrimaryStatusDescription SecondaryStatusDescription
------      ----                               ------- ------------------------ --------------------------
MobyLinuxVM Gastdienstschnittstelle            False   OK
MobyLinuxVM Takt                               True    OK
MobyLinuxVM Austausch von Schlüsselwertepaaren False   OK
MobyLinuxVM Herunterfahren                     True    OK
MobyLinuxVM Zeitsynchronisierung               True    OK
MobyLinuxVM VSS                                False   OK
```
So the service names are in German and TimeSync (Zeitsynchronisierung) is enabled as expected...I do have english as a language pack installed as well  so that might be a difference...

For completeness:
```
PS C:\WINDOWS\system32> get-vm mobylinuxvm | Get-VMIntegrationService | ForEach-Object { if ($_.Name -eq "Heartbeat") { Write
-Output "Hello $_.Name" } else {Write-output $_.Name} }
Gastdienstschnittstelle
Takt
Austausch von Schlüsselwertepaaren
Herunterfahren
Zeitsynchronisierung
VSS
PS C:\WINDOWS\system32> get-vm mobylinuxvm | Get-VMIntegrationService | ForEach-Object { if ($_.Name -eq "Takt") { Write-Outp
ut "Hello $_.Name" } else {Write-output $_.Name} }
Gastdienstschnittstelle
Hello VMIntegrationComponent (Name = 'Takt', VMName = 'MobyLinuxVM') [Id = 'Microsoft:927B9577-12CB-4733-9D46-F64AFAC911F9\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47', VMId = '927b9577-12cb-4733-9d46-f64afac911f9'].Name
Austausch von Schlüsselwertepaaren
Herunterfahren
Zeitsynchronisierung
VSS
```
Here the match did not work. Which is kinda weird

**Comment by Crack** [comment] 2017-02-13 23:27
I have a pure Polish system: one from Win 7 -> 10 upgrade and one with Win 10 OEM, no language packs.

I just changed this line to
```powershell
    $vm | Get-VMIntegrationService | ForEach-Object {
        if ($_.Name -eq "Heartbeat" -or $_.Name -eq "Shutdown" -or $_.Name -eq "Synchronizacja czasu") {
            Enable-VMIntegrationService $_
        } else {
            Disable-VMIntegrationService $_
        }
    }
```
and recreated my VM. Now I have:
```powershell
PS C:\WINDOWS\system32> Get-VMIntegrationService mobylinuxvm

VMName      Name                      Enabled PrimaryStatusDescription SecondaryStatusDescription
------      ----                      ------- ------------------------ --------------------------
MobyLinuxVM Interfejs usługi gościa   False   OK
MobyLinuxVM Puls                      False   OK
MobyLinuxVM Wymiana par klucz-wartość False   OK
MobyLinuxVM Zamykanie                 False   OK
MobyLinuxVM Synchronizacja czasu      True    OK
MobyLinuxVM VSS                       False   OK
```
So time sync enabled, but Shutdown and Heartbeat still disabled. Which makes sense, because the script asks for Get-VMIntegrationService and filters results by Name, which is localized. It should use ID.

**Comment by rneugeba** [comment] 2017-02-14 10:26
Thanks for the help/debug. Could you try the attached script? Instead of matching on Names it matches on Service ID. 

To test the script:
- exit Docker for Windows
- Open an elevated powershell in  `C:\Program Files\Docker\Docker\resources`
- Execute `.\MobyLinux.ps1 -destroy`
- Copy the new script (attached below) over the existing one
- Execute `.\MobyLinux.ps1 -create`
- Check output
- Start the application

Use it for a while and check if the time sync service is running with `Get-VMIntegrationService MobyLinuxVM`

[MobyLinux.ps1.zip](https://github.com/docker/for-win/files/773750/MobyLinux.ps1.zip)

**Comment by Crack** [comment] 2017-02-14 22:40
It works, now VM has proper services:
```powershell
...
Disabled Interfejs usługi gościa
Enabled Puls
Disabled Wymiana par klucz-wartość
Enabled Zamykanie
Enabled Synchronizacja czasu
Disabled VSS
VM created.
PS C:\Program Files\Docker\Docker\resources> Get-VMIntegrationService MobyLinuxVM

VMName      Name                      Enabled PrimaryStatusDescription SecondaryStatusDescription
------      ----                      ------- ------------------------ --------------------------
MobyLinuxVM Interfejs usługi gościa   False
MobyLinuxVM Puls                      True
MobyLinuxVM Wymiana par klucz-wartość False
MobyLinuxVM Zamykanie                 True
MobyLinuxVM Synchronizacja czasu      True
MobyLinuxVM VSS                       False
```

**Comment by rneugeba** [comment] 2017-02-14 23:19
@Crack Thanks for testing. I'll make a PR and see that it makes it into the next release

**Comment by rneugeba** [comment] 2017-02-15 14:11
The fix is now in master and hopefully will go out with the next Beta

**Comment by dgageot** [comment] 2017-02-22 18:35
@copitz @amrael @Crack We just release version `17.03.0-rc1` of Docker for Windows. Please give it a try and tell us if it's better now.

**Comment by amrael** [comment] 2017-02-23 13:55
I've confirmed that the latest version fixed the problem!

**Comment by rneugeba** [comment] 2017-02-23 14:19
Thanks for confirming and Thanks to @Crack for the figuring out that the language settings were the cause. I'm closing this issue as there is a released Beta available with a fix

**Closed by rneugeba** 2017-02-23 14:19 UTC
Labels: area/hyper-v, status/0-triage, status/4-fix-released-beta, version/1.13.0

**Comment by tmarinov** [comment] 2019-01-02 18:21
I started having similar error when try to access CosmosDB from an api, contained in a Docker container on my windows 10 (used to work before):
"The authorization token is not valid at the current time. Please create another token and retry"

I see a few hours time difference between the docker container and my windows 10 laptop.
Here is my "anonymized" docker file:

`FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY Services/**********/.API.csproj Services/*******.API/
COPY Services/*******.csproj Services/***********/
RUN dotnet restore Services/********.API.csproj 
COPY . .
WORKDIR /src/Services/*********** 
RUN dotnet build *****.csproj -c Release -o /app
FROM build AS publish
RUN dotnet publish ****.API.csproj -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "****.API.dll"]
`

Started having this with image for 2.1 dotnet core. Since then:
- restarted Docker for Windows
- recreated the images/containers 
- Re-set Docker for Windows
- Upgraded whole solution to dotnet core 2.2.

Without any success - still getting the same error.

Any ideas?
(The solution contains 4 containers in total, all of them are with the same time, but it is different from the host machine (my windows laptop. Same solution was working 1 month ago - before Docker and  Windows upgrade)
