### ISSUE TITLE
docker in win 10 with hyper-v crashed

### ISSUE THREAD

**Issue by roman-vi** [docker/for-win#4407] opened 2019-08-03 16:20 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 008A1351-88EF-42A9-8AED-DDF4BADB5824/20190803155343

### Expected behavior
docker desktop app is started
 
### Actual behavior
and error occured
Der Wert darf nicht NULL sein.
Parametername: path1
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information
  - Windows Version: Win 10 Pro 1803 build 17134.829
  - Docker Desktop Version: 2.1.0.0

### Steps to reproduce the behavior

  1. docker installed
  2. enable hyper v
3. restart
4. start docker

**Comment by mikeparker** [comment] 2019-08-06 16:23
Duplicate of https://github.com/docker/for-win/issues/3375

**Closed by mikeparker** 2019-08-06 16:23 UTC
