### ISSUE TITLE
Missing command arguments on windows system restart

### ISSUE THREAD

**Issue by junhwong** [docker/for-win#524] opened 2017-02-23 16:34 UTC
### Expected behavior
When Windows system starts, it is possible to start docker  container correctly(e.g: docker run ....command arguments)
### Actual behavior
Missing command arguments on windows system restart
### Information
```
Version: 1.13.1 (10072)
Channel: Stable
Sha1: 94675c5a765e2c51fba6c10b87e0a1a4ed3dde51
Started on: 2017/02/23 23:48:12.979
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\username\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
```

### Steps to reproduce the behavior
  0. use this images: https://hub.docker.com/_/mysql/
  1. docker run --name some-mysql -v /my/own/datadir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
  2.  mysql create databases and tables
  3. stop container and start container ,  to this step is correct .
  4. restart windows system,  container is started yet, but not use command arguments, its losed!!!, it is a new container!!!

**Comment by junhwong** [comment] 2017-02-24 04:50
FIXED:
1. No miss command arguments anyone
2. But --restart=on-failure   is invalid, and started is incorrect container on system restarted， not expected
3. Try stop & start this container, It is back to normal, is correct!

**Comment by dgageot** [comment] 2017-02-24 05:52
@junhwong Are you ok if I close the issue then?

**Comment by junhwong** [comment] 2017-02-25 04:46
@dgageot  Why? This problem really occurred。

Is not my writing clear? What information is needed?

**Comment by rneugeba** [comment] 2017-02-27 01:38
It's a bit unclear what the issue is. Could you try rephrasing. Also, could your issue be the same as reported here: https://github.com/docker/for-win/issues/71

**Comment by junhwong** [comment] 2017-03-03 21:06
Yes, they look the same。but it seems no solution

**Comment by rneugeba** [comment] 2017-03-03 21:13
thanks for getting back. I'm closing this as a duplicate of #71 then as it is already tracked there. You are right that there is no solution yet. Doing a proper solution is not straight forward since we need to pass the credentials from the host to the Linux VM (via the docker daemon) so with the current implementation there will always be a race

**Closed by rneugeba** 2017-03-03 21:13 UTC
Labels: status/0-more-info-needed, status/0-wont-fix
