### ISSUE TITLE
Enabling Hyper-V feature turns my wi-fi off

### ISSUE THREAD

**Issue by londoncalling** [docker/for-win#139] opened 2016-10-10 21:07 UTC
@rneugeba @friism I'm adding this issue per feedback we got through the docs, [docs issue #100 "Feedback for: docker-for-windows/index.md"](https://github.com/docker/docker.github.io/issues/100#issuecomment-252415791) from https://github.com/shazChaudhry

### Expected behavior
Install Docker for Windows (which enables Hyper-V), or enable Hyper-V manually, and all works, with Wi-Fi enabled.

### Actual behavior
I am using Docker v1.12.1 on a Windows 10 laptop. Enabling Hyper-V feature turns my wi-fi off. How do I ensure that my wi-fi stays on while using Hyper-V features?

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rneugeba** [comment] 2016-10-10 22:33
@shazChaudhry the issue you reported on https://github.com/docker/docker.github.io/issues/100 has been moved here.

We enable Hyper-V on installation if it is not enabled. This should not interfere with your networking setup and the rest of the installation does not touch the network interface either.

Could you describe in a bit more details what's happening and how to reproduce it, what the version of Windows is, you are using etc. Could you please upload diagnostics and provide the ID?

Thanks

**Comment by simonferquel** [comment] 2016-10-11 07:46
There are known issues with some old wireless device drivers and Hyper-V. Can you try to update your wifi drivers ?

**Comment by tommiehansen** [comment] 2016-10-20 12:54
Try running a `repair` on your default connection, if that fails try it on `dockerNAT`.

If all fail uninstall Docker and run a `repair` on your default connection. Then re-install Docker.

**Comment by shazChaudhry** [comment] 2016-10-20 15:02
I have done windows updates, uninstalled and installed Docker several time. However, my wi-fi is still turned off every time hyper-v feature is enabled. wi-fi drivers are also up to date.

I have just done:
1. Got docker for windows (beta) from https://docs.docker.com/docker-for-windows/
2. Installed Docker (1.12.2, build bb80604, experimental), enabled Hyper-V feature, double checked that Virtualization was enabled and waited for Docker to start. As expected, wi-fi was automatically turned off. 
3. To turn wi-fi back on and to connect to internet, I have disabled "vEthernet (DockerNAT)"
4. Uploaded diagnostic and feedback: 4F7DC077-55A5-43DC-974E-2A86B75AB998/2016-10-20_15-06-18
5. Host info: Windows 10 Enterprise; Version = 1511; OS Build = 10586.633, Dell Latitude E5250

Please let me know if there is any other info you need.

**Comment by yongshin** [comment] 2016-10-27 22:38
It looks like many people have experienced the issue of losing wifi and hyperv before. In recent builds of Windows 10 (build 14295 or later) there is a new option.  This is currently a bit hidden (no GUI, and some rather finicky PowerShell) but you can now setup virtual switches for virtual machines that use NAT.

This means that your virtual machines can use a private IP address and still access Internet resources. More importantly – this is approach is very compatible with wireless network adapters: https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/setup_nat_network

**Comment by londoncalling** [comment] 2016-10-28 00:21
@yongshin thanks, I'll figure out a place to include this in the troubleshooting docs and link to it from other relevant topics

**Comment by rneugeba** [comment] 2016-10-28 11:56
@shazChaudhry it looks like you had VirtualBox installed and it didn't install cleanly. There are still some VirtualBox network adapters lingering on the system.  I'm closing this issue, for now. Please re-open if, after un-installing VirtualBox the issue persists.
Thanks

**Closed by rneugeba** 2016-10-28 11:56 UTC
Labels: area/hyper-v, area/network, kind/bug, status/0-more-info-needed

**Comment by ladvishal1985** [comment] 2017-02-20 14:07
I am facing the same issue. I downloaded Docker(stable windows) from https://docs.docker.com/docker-for-windows/install/. Post installation Hypervisor is enabled which leads to Windows restart. Then the wifi never starts. I tried uninstalling the Docker and disabled the Hyper-V which leads to Windows restart and again the wifi works normally. I tried this twice.
I have Windows 10 Enterprise. Again post installation I am unable to start docker I get an error message that asks me to enable Virtual Technolgy from BIOS(I am not sure if this is expected behavior)

Thanks

**Comment by londoncalling** [comment] 2017-02-21 04:58
@ladvishal1985 Disabling Hyper-V would cause problems, as it must be enabled.

Can you read through these topics and make sure you are following the protocols?

[What to know before you install](https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled

[Hyper-V (in Troubleshooting)](https://docs.docker.com/docker-for-windows/troubleshoot/#hyper-v) (includes a link to how to enable Hyper-V manually if this is necessary

[Virtualization must be enabled (in Troubleshooting)](https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled)

Also, make sure you do not have Virtual Box installed or enabled.

@rneugeba @friism can you help? This issue seems to be re-surfacing.

**Comment by friism** [comment] 2017-02-21 16:02
The networking clean-up scripts from Microsoft are another good resource: https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking

**Comment by kenchilada** [comment] 2017-02-22 02:19
I had the same problem.  I had a "External Virtual Switch" that functioned, and my docker host got an IP from DHCP on the LAN.  When WIFI is enabled, it all breaks.  Seems a problem with bridging?  I read elsewhere that I needed to remove external switch and create a NAT virtual switch with "New-NetNat".  This actually worked fine until the next time I rebooted.

Hyper-V feels so fragile, I feel like VirtualBox was a better option.  We were just wanting to find a stable environment for developers to work in.

**Comment by kenchilada** [comment] 2017-02-22 02:43
Followup to previous... if I reboot it starts working again.

In case it helps anyone, I followed this guide to setup the NAT switch...
http://www.thomasmaurer.ch/2016/05/set-up-a-hyper-v-virtual-switch-using-a-nat-network/

Then I stood up a dhcp server on that network to assign ipv4 addresses.

**Comment by gkorndorffer** [comment] 2017-06-04 18:08
I'm experiencing the same issues, Windows 10, no Virtualbox drivers... Virtualization is enabled, hyper-v is enabled...but when I install Docker, all network adapters get disabled

**Comment by evra** [comment] 2017-09-02 19:56
I solved this issue by enabling "Shared Usage" of the WiFi adapter (Docker restart is required).

**Comment by dkouzhel** [comment] 2017-09-27 12:45
Try to disable "LAN / VLAN Switch" in BIOS. The laptop automatically switch off WLAN with other online connection (ethernet or vlan or vpn)

**Comment by sukumarsk** [comment] 2017-10-20 08:37
I faced the same issue and tried all the above suggestions.

Finally , I disabled the DocketNAT adapter (Control Panel\Network and Internet\Network Connections)
Connected  back WiFI and at command prompt, issued below commands
ipconfig /release
ipconfig /renew

Enabled DockerNAT.

Now I am able to connect WiFi and also DockerNAT,

**Comment by sukumarsk** [comment] 2017-10-24 04:54
Further to my previous comment, I researched little more and found solution at

https://superuser.com/questions/1100336/issue-with-wifi-adapter-with-docker-windows-native-hyper-v


I have chosen option #2 and it resolved my issue.

Hope this helps.

**Comment by olivierlevy** [comment] 2018-09-14 10:32
Disable the vEthernet (default Switch)
Open Hyper-V Manager, select your computer on the left, you should have the possibilities to create the virtual network switch, but if you already have DockerNAT change from Internal to External network and select your wifi adapter

**Comment by jerrychong25** [comment] 2019-08-27 15:58
> Disable the vEthernet (default Switch)
> Open Hyper-V Manager, select your computer on the left, you should have the possibilities to create the virtual network switch, but if you already have DockerNAT change from Internal to External network and select your wifi adapter

For this solution, I need to always "Disable the vEthernet (default Switch)" after reboot laptop every time.

Is there any ways no need to disable the settings after reboot?

**Comment by jerrychong25** [comment] 2019-08-28 00:40
> Disable the vEthernet (default Switch)
> Open Hyper-V Manager, select your computer on the left, you should have the possibilities to create the virtual network switch, but if you already have DockerNAT change from Internal to External network and select your wifi adapter

Hi @olivierlevy,

After follows your settings, I could connect to my WIFI.

However, after reboot, I need to configure same steps every time I reboot my laptop.

Is there any ways to permanently fixes this issue?

Thanks.

**Comment by olivierlevy** [comment] 2019-08-28 07:31
Hi @jerrychong25 , unfortunatally, yes, you shall add a shortcut in you desktop to quickly go to your adapter ; or create or find a software that does the changes for you. My company made this kind of software that solved the issue, but I cannot share this :(

**Comment by jerrychong25** [comment] 2019-08-28 08:37
> Hi @jerrychong25 , unfortunately, yes, you shall add a shortcut in you desktop to quickly go to your adapter ; or create or find a software that does the changes for you. My company made this kind of software that solved the issue, but I cannot share this :(

Hi @olivierlevy, it is pretty annoying to turn off everytime after reboot.

Hope anyone that can share this software.
