### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'SKASULKA-L' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running. at New-Switch, <No file>: line 121

### ISSUE THREAD

**Issue by ShawnKasulka** [docker/for-win#3929] opened 2019-05-17 17:34 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 143A8D40-325F-4E44-A216-7DB26EE8491B/20190517132524

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment] 2019-05-30 14:47
Duplicate of https://github.com/docker/for-win/issues/1221
* Your Hyper-V configuration is broken. This may be caused by a windows update.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 14:47 UTC
