### ISSUE TITLE
After Docker update this afternoon program does not build anymore on Visual Studio 

### ISSUE THREAD

**Issue by bortot-systems** [docker/for-win#10609] opened 2021-03-10 17:33 UTC
### Actual behavior
Error to start application with docker composer
DT1001	ERROR: for gim.webui  Cannot start service gim.webui: failed to create endpoint web-59015-Empty-issue-status-in-priority-list on network dockercompose4185379768228670846_default: **Windows does not support host IP addresses in NAT settings**
**If the error persists, try restarting Docker Desktop**.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	394	

### Expected behavior
No errors

### Information

Docker composer.yml

version: '3.4'

services:
  gim.webui:
    image: web-image
    build:
      context: .\Presentation Layer\Gim.WebUI
      dockerfile: Dockerfile
    container_name: web-${BRANCH}
    depends_on:
     - "database"
  database:
    image: database-image
    build:
      context: .\Database Layer
      dockerfile: Dockerfile
    container_name: database
    environment:
      - attach_dbs=[{"dbName":"GIM","dbFiles":["C:\\sqldata\\GIM.mdf","C:\\sqldata\\GIM_log.ldf"]}]
    ports:
     - "5434:1433"   
    volumes:
      - database-data:C:\sqldata
volumes:
    database-data:
        name: volume-${BRANCH}

  - Windows Version: 10
  - Docker Desktop Version: 3.2.1 (61626)
  - WSL2 or Hyper-V backend?  Yes

**Comment by stephen-turner** [comment] 2021-03-10 18:13
Closing as dupe of #10552.

**Closed by stephen-turner** 2021-03-10 18:13 UTC
Labels: version/3.2.1
