### ISSUE TITLE
Cannot open read-only files in bind-mounted volume

### ISSUE THREAD

**Issue by ricmzn** [docker/for-win#6016] opened 2020-03-13 18:25 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 17DF2026-6081-4C91-B251-658F4666D41C/20200313180148

### Expected behavior
Read-only files shared between the Windows host and a Docker container should still be readable from the container.

### Actual behavior
Anything that tries to open the file gets a "File not found" or "Operation not permitted" error.

### Information
This happened after a recent Docker Desktop update, although I can't remember which version was installed before (it was a few months old). I first noticed this when a project failed its test run because it was built in a Docker container, and one of the build tools tried to read files in the project's .git directory, some of which are made read-only by default.

  - Windows Version: Windows 10 Pro 1909 (Build 18363.720)
  - Docker Desktop Version: 2.2.0.4 (Stable)
  - Virtualized Windows: No, it's installed directly on the machine

### Steps to reproduce the behavior
  - Create a text file on the desktop with some content
  - Run a container from cmd with the command line: `docker run -it -v "C:\Users\{yourname}\Desktop\{filename}:/test" ubuntu`
  - Check the permissions of the file with `ls -l` and try to read its contents with `cat`:
![01](https://user-images.githubusercontent.com/6194377/76648407-69c2b580-653d-11ea-9983-941bb99e3262.png)
  - Right click the file on Windows, open properties, check the "read-only" box, and confirm
  - Run the Ubuntu container with the same parameters as above
  - Output of `ls -l` and `cat` after the change (note that ls can read the new permissions correctly):
![02](https://user-images.githubusercontent.com/6194377/76648423-6fb89680-653d-11ea-99c7-e0640b6c05a7.png)

**Comment by omcandido** [comment] 2020-03-13 18:31
I was about to open the same issue.
Drupal installations crash with the latest update, as the settings.php file (which has 444 permissions) cannot be read.
The previous release (Docker Desktop Community 2.2.0.3) works fine.

**Comment by stephen-turner** [comment] 2020-03-13 18:36
@djs55 Did we change something in this area between 2.2.0.3 and 2.2.0.4?

**Comment by theryansmith** [comment] 2020-03-13 22:21
I wonder if this is also related to the fact that windows mounted volumes are also now case-sensitive?     https://github.com/docker/for-win/issues/6013

**Comment by djs55** [comment] 2020-03-16 10:11
@ricmzn thanks for the report and the very clear repro steps. I could reproduce this locally and identified the problem: unfortunately we mis-parse the Linux file open flags and attempt to open the file read/write instead of read-only. This was a regression caused by the fix to relax the file locking by adjusting the file open flags (`FILE_SHARE_` etc). I've got a proposed fix and a test case to cover it.

**Comment by djs55** [comment] 2020-03-17 19:27
I've got a prototype build (branched from stable 2.2.0.4) which has a fix for this problem. If you have the time to try it: https://download-stage.docker.com/win/stable/43531/Docker%20Desktop%20Installer.exe .  If it still doesn't work please let me know and also upload a fresh set of diagnostics. Thanks again!

**Comment by djs55** [comment] 2020-03-17 19:40
I deleted a comment about a prototype build because I just discovered it was incomplete - sorry for the confusion.

**Comment by djs55** [comment] 2020-03-17 20:38
I now have a more complete prototype build (based on top of the recent stable 2.2.0.4). If you have the time to try it let me know how it goes: https://download-stage.docker.com/win/stable/43542/Docker%20Desktop%20Installer.exe If it still doesn't work, please upload a fresh set of diagnostics and quote the id here.

**Comment by cleathley** [comment] 2020-03-18 08:39
@djs55 Can also confirm this also fixes a lot of composer install issues people were having (though the file system wasn't RO in mycase). Thanks

**Comment by m-h-k** [comment] 2020-03-18 10:23
I had the same issue using git inside a VSCode remote container, and your prototype build fixes it. Thank you very much!

**Comment by cakoops** [comment] 2020-03-18 11:09
I had in the recent stable 2.2.0.4 the following issue:
I could not read a file from C# code. Got permission denied error.

@djs55 
Your prototype fixed the issue.

**Comment by ricmzn** [comment] 2020-03-18 18:01
@djs55 I can also confirm that the linked prototype fixes the issue, with no visible regressions in the project I used for the initial diagnosis. Thanks a lot!

**Comment by hastarin** [comment] 2020-03-19 01:14
And just another confirmation that this worked for an issue I had with VS Code and a Remote Container.

**Comment by rfay** [comment] 2020-03-19 17:23
I hit this, just with a git fetch/checkout inside the container. The build in https://github.com/docker/for-win/issues/6016#issuecomment-600285551 fixed it for me @djs55 

A good automated test to add while fixing this would probably be just the "git checkout in container"

**Comment by minusdavid** [comment] 2020-03-25 04:44
Yikes...

**Comment by rfay** [comment] 2020-03-25 05:13
@djs55 any projection about a release to fix this? More Windows folk stumble on it every day. The natives are getting restless :)

**Comment by mat007** [comment] 2020-03-25 06:09
@rfay the current plan is to release an Edge version at the end of the month (March) then a Stable based on it mid-April.

**Comment by rfay** [comment] 2020-03-25 13:35
Yay for releasing things on edge before stable! Thanks, looking forward to both.

**Comment by tai-yi** [comment] 2020-04-01 03:40
My issue is resolved with `Enable the experimental WSL 2 based engine`

**Comment by stephen-turner** [comment] 2020-04-02 18:00
This is now fixed in 2.2.0.5 stable and 2.2.3.0 edge, so closing this ticket.

**Closed by stephen-turner** 2020-04-02 18:00 UTC
Labels: version/2.2.0.4

**Comment by bbqrob** [comment] 2020-06-09 15:24
Hi @stephen-turner , can you point to the commit, which fixes the problem. Got a similar problem, running docker-ee 19.03.8 on a MS Windows Server 2019 host (virtualized in VMWare ESXi) which serves as an Teamcity build agent.

**Comment by stephen-turner** [comment] 2020-06-10 11:17
@bbqrob I can't point to the commit because the product is not open source. But in any case, your problem must be different, as you're running the EE Engine on Windows Server, and the bug was in the Docker Desktop code. I suggest you open a ticket in the moby/moby repository instead.
