### ISSUE TITLE
moby VM loses track of time and doesn't synchronize to hostsystem

### ISSUE THREAD

**Issue by KekSfabrik** [docker/for-win#293] opened 2016-12-06 10:25 UTC
### Expected behavior

Time in a container is the same as the time of the hostsystem (+/- drift between syncs)

### Actual behavior

moby is paused and not shut down during hostsystem reboot and therefor maintains the time it was initially started, ignoring the that the time has changed

### Information

  - Version 1.12.3 (8488) from the Stable channel (d63ec34)
  - Win 10 Pro 1607 (Build 14393.447)

### Steps to reproduce the behavior

  1. Start any container on a friday
  2. Shut your win-box down
  3. Come back to work on monday and
  4. wonder why the container thinks it's still friday

### other than that...

i'm guessing the pause has been selected as default because people who aren't using restart-policies would be unhappy if all their containers were stopped after a reboot but we're running a sort-of timing-sensitive application where the developers on the event-generating side send timestamped events to the rest of the system running in containers (which doesn't know what to do with events coming from the future by several days)... right now people would have to manually restart the moby vm if they have the [start docker when you log in] box checked -- i'd really much rather not run my own ntpd container and link the time to all the other containers (which is the only other workaround i can come up with)

### possible solutions?

i really only see 2 possible solutions 
  - Synchronize time to hostsystem at boot or regularly (if that's to hard on a linux-vm on hyper-v then maybe using ntpd?)
  - actually reboot the moby VM

**Comment by rneugeba** [comment] 2016-12-06 10:45
@KekSfabrik Thanks for reporting. This looks like a duplicate of #72 so I'm closing it. If you look at #72 we released a partial fix with Beta31 and working on an improved fix for Beta32.

**Closed by rneugeba** 2016-12-06 10:45 UTC

**Comment by KekSfabrik** [comment] 2016-12-06 11:07
okay, sorry about that -- looked around but didn't see the issue for some reason

thank you :)
