### ISSUE TITLE
Git (any operaton) in bind mounted directory fails with fatal permission denied error.

### ISSUE THREAD

**Issue by ro-kue** [docker/for-win#6041] opened 2020-03-16 12:57 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2626AB4F-C286-49B5-B528-0B86C06FADDA/20200316124658

### Expected behavior

When mounting a directory with a git revpository, I expect to use git as usual.

### Actual behavior

Git fails with a permission denied error:

user@121119bfceee:/workspace$ git status
fatal: failed to read object 5f889e117b352cc134a2c1345b1cf6dfb43e2fe0: Operation not permitted

### Information

  - Windows Version: 10 Pro 1909 build 18363.720
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: nope
  - I'm using Hyper-V. Not the WSL2 backend.

This problem started with 2.2.0.4. It was fine before.

I'm mounting the source code as a bind mount into a python (debian) container. Usually, I could use git as normal but since the last update, it stopped. We're running 3 container mounting that source code but it makes no difference if I run all of them or one of them.

Log files also contain a lot of errors like "[13:45:20.222][VpnKitBridge      ][Info   ] time="2020-03-16T13:45:20+01:00" msg="error CloseWrite to: Die Pipe wird gerade geschlossen."

That's "pipe is being closed" in English.

### Steps to reproduce the behavior

1. Take a directory on the host with a git repository.
2. Bind mount in any container that offers a git executable.
3. Run git status or something else 

This should throw the error.

**Comment by mat007** [comment] 2020-03-16 13:04
Thanks for the report, this looks like a duplicate of #6016?

**Comment by ro-kue** [comment] 2020-03-16 13:30
@mat007 Honestly I'm not sure. Sure, the underlying issue can be that some files in the .git directory are actually read only. I'll investigate and report back. At first glance, it does not seem like this is a duplicate. At best two symptoms of the same issue. Give me half an our or so

**Comment by ro-kue** [comment] 2020-03-16 13:34
@mat007 omg you're right! Once I removed write protection from source directory, it worked. No restart no nothing. So yes, it's a duplicate.

**Comment by mat007** [comment] 2020-03-16 15:33
Thanks for confirming this @ro-kue, we have fixed this bug in our master branch now but it might take a couple of weeks before it’s released.
I’ll go ahead and close this ticket as a duplicate.
Thanks again!

**Closed by mat007** 2020-03-16 15:33 UTC
