### ISSUE TITLE
Installer v2.3.4.0 Fails to Install

### ISSUE THREAD

**Issue by groboclown** [docker/for-win#7890] opened 2020-07-29 18:31 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (unavailable through installer)

### Expected behavior

I expect the installer to install.

### Actual behavior

The installer fails on the final stages of the installation:

```
Removing files...

Removing files
Rollbacking component:
Rollbacking component: Create docker-users group
Rollbacking component: Add user to docker-users group
Deploying component: Enable WSL 2 Windows Features
Deploying component: Add user to docker-users group
Deploying component: Create docker-users group
Installing components
...
```

The installation wizard reports, "Installation failed" with the stack:

```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
```

### Information

I first attempted this after upgrading from Docker Edge (previous release version) using the Docker Edge installer downloaded by the auto-upgrade.  It failed during the install.  I then downloaded the stable release build from the website, and it, too, failed.  I then downloaded the Docker Edge installer from the website, and tried to install with that, but it, too, failed.  I rebooted then tried to install again, which also failed.  The stack above is from this last attempt at installing.

  - Windows Version: Windows 10 Pro Insider Preview, build 20175.1000
  - Docker Desktop Version: edge 2.3.4.0 (46980), edge 2.3.3.2 (46784), and stable 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to Reproduce

For myself, I consistently see this when attempting to run the installer.

The logs seems to indicate that it was an issue with WSL 2.  `wsl --list --all` still listed the `docker-desktop-data` distribution.  I deleted it, and shutdown wsl for good measure, then tried the install again, and it still failed at the same place.

**Comment by groboclown** [comment] 2020-07-29 21:36
I was able to get the install to work after the Windows upgrade to build 20180.1000

**Comment by magneticflux-** [comment] 2020-07-30 10:25
I'm using build 20180.1000 and the install doesn't work. @groboclown did you do something special before installing it?

**Comment by Comeza** [comment] 2020-07-30 10:37
I installed 20180.1000 yesterday and have the same problem.
Used 20175.1000 before where the installation also crashed.

Here is my log
```
[00:13:03.224] [InstallHandler] No installation found
[00:13:04.564] [InstallWorkflow] Using package: res:DockerDesktop
[00:13:04.584] [InstallWorkflow] Downloading
[00:13:21.596] [InstallWorkflow] Extracting manifest
[00:13:24.248] [InstallWorkflow] Checking prerequisites
[00:13:24.694] [InstallWorkflow] Unpacking artifacts
[00:15:12.178] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[00:15:16.923] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[00:15:28.822] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[00:15:38.818] [InstallWorkflow] Component CommunityInstaller.EnableFeaturesAction failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   bei System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   bei CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   bei CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
[00:15:38.826] [InstallWorkflow] Installation failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   bei System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   bei CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   bei CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
[00:15:38.839] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[00:15:38.842] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[00:15:38.843] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[00:15:38.852] [FileSystem] Killing existing CompatTelRunner process with PID 8084
[00:15:38.880] [FileSystem] Killing existing CompatTelRunner process with PID 3692
[00:15:38.881] [FileSystem] Deleting C:\Program Files\Docker\Docker
[00:15:39.206] [FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[00:15:39.213] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[00:15:39.214] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by magneticflux-** [comment] 2020-07-30 10:48
I also am unable to add or remove features the normal way (through "Turn Windows features on or off"). It seems like this is an issue with insider build 20180.1000; the only question is how @groboclown managed to get it working.

**Comment by ventayol** [comment] 2020-07-30 11:26
I'm also having problems with 20180.
Does anyone know if any docker version works in it?

**Comment by DarkTraveler** [comment] 2020-07-30 12:57
@ventayol 
Hey.
I already tried the 4th version: /
I noticed that now I also have hyper-v and windows sandbox dead!

**Comment by DarkTraveler** [comment] 2020-07-30 13:00
also in github wsl / wsl2 panic about docker started too

**Comment by ventayol** [comment] 2020-07-30 13:06
FYI, I went back to Windows `Build 20175.rs_prerelease.200717-1349` and now I can install and use Docker 2.3.4.0 perfectly, so it seems the problem is with last windows insider version 20180.1000.

**Comment by DarkTraveler** [comment] 2020-07-30 13:09
@ventayol 
but it didn't help me: / And for many, the problem began just in 20175. But I'm glad that everything is ok now.

**Comment by ventayol** [comment] 2020-07-30 13:15
@DarkTraveler I had to remove docker and then install it again. It also required to remove an entry on the windows registry and the uninstall didn't work well.

**Comment by stephen-turner** [comment] 2020-07-30 13:25
Microsoft bug, dupe of #7808.

**Closed by stephen-turner** 2020-07-30 13:25 UTC

**Comment by metcalfc** [comment] 2020-07-31 21:43
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
