### ISSUE TITLE
Persistent volumes are not created in 2.3.0.2

### ISSUE THREAD

**Issue by avalanchus** [docker/for-win#6692] opened 2020-05-13 17:37 UTC
- [x] I have uploaded Diagnostics
  - Diagnostics ID:
D46131A8-4FCB-4F0C-A015-F4DA403B5E61/20200513172729

### Expected behavior
The docker create persitent folder linked with host's folder
### Actual behavior
Folder not created

### Information
I double-checked several times, I downloaded several previous versions  - everything is ok there
But version 2.3.0.2 just refuses to work with persistent volumes. 

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.3.0.2

### Steps to reproduce the behavior
Please try this (docker with mysql server):
docker run -v //d/Data:/data -v //d/MySqlDockerData:/var/lib/mysql -p 9999:3306 -e MYSQL_ROOT_PASSWORD=111111 -d mysql:8.0 
After this you can chek host folders and docker folder 
- dockers folder /data is missing
- mysql folders have different contents in host and docker

**Comment by othercorey** [comment] 2020-05-13 19:57
Same as https://github.com/docker/for-win/issues/6668 ?

**Comment by avalanchus** [comment] 2020-05-14 08:40
> Same as #6668 ?
Indeed it looks like it. Previous version 2205 is correct

**Comment by djg2002** [comment] 2020-05-15 00:38
Try D:/  instead of //D/   But note its only a partial fix.  See https://github.com/docker/for-win/issues/6700

**Comment by mat007** [comment] 2020-05-15 06:16
Closing as a duplicate of #6668, thanks!

**Closed by mat007** 2020-05-15 06:16 UTC
