### ISSUE TITLE
Docker Desktop WSL distro stopped

### ISSUE THREAD

**Issue by kaladasan** [docker/for-win#10376] opened 2021-02-13 11:01 UTC
[log.txt](https://github.com/docker/for-win/files/5975522/log.txt)

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-02-15 10:33
Probably a dupe of #10374.

**Closed by stephen-turner** 2021-02-15 10:33 UTC
