### ISSUE TITLE
DD doesn't open/start after updating to 4.19.0

### ISSUE THREAD

**Issue by jamiematrix** [docker/for-win#13480] opened 2023-05-11 09:21 UTC
Updated to 4.19 yesterday and just noticed DD is no longer running.

I usually start it from the start menu, but DD is no longer listed or searchable. 
Next I went to C:\Programs\Docker\Docker and tried the .exe there, but nothing happens when double clicking. No error, no icon in the sys tray, nothing.
Restarted Windows and still nothing.
Tried the `Docker Desktop Installer.exe` file and get the following error:
```
empty package
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext() in C:\workspaces\PR-21718\src\github.com\docker\pinata\win\src\Docker.Installer\InstallWorkflow.cs:line 169
```
DD had been working fine before the update.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop doesn't start, there are no Docker related errors

### Expected behavior
Docker Desktop to start/show

### Information

  - Windows Version: 10
  - Docker Desktop Version: 4.19.0
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
[PASS] DD0027: is there available disk space on the host?
[FAIL] DD0028: is there available VM disk space? failed to retrieve the size information from ''
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[FAIL] DD0001: is the application running? Docker is not running
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[FAIL] DD0035: is the VM time synchronized? exit status 0xffffffff
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-05-11T09:11:16.425205200Z][com.docker.diagnose.exe][I] ipc.NewClient: 35633034-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-05-11T09:11:16.425289900Z][com.docker.diagnose.exe][I] (f991f5c5) 35633034-diagnose C->S diagnosticsd GET /ping
[2023-05-11T09:11:16.425797400Z][com.docker.diagnose.exe][W] (f991f5c5) 35633034-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:16.426790200Z][com.docker.diagnose.exe][I] ipc.NewClient: 23085f14-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-05-11T09:11:16.426790200Z][com.docker.diagnose.exe][I] (f91031ff) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-05-11T09:11:16.427359900Z][com.docker.diagnose.exe][W] (f91031ff) 23085f14-com.docker.diagnose C<-S NoResponse GET /docker (569.7µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:16.427359900Z][com.docker.diagnose.exe][I] (f91031ff-1) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:16.427915900Z][com.docker.diagnose.exe][W] (f91031ff-1) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (556µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:17.435360200Z][com.docker.diagnose.exe][I] (f91031ff-2) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:17.436182000Z][com.docker.diagnose.exe][W] (f91031ff-2) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (821.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:18.438299700Z][com.docker.diagnose.exe][I] (f91031ff-3) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:18.439384400Z][com.docker.diagnose.exe][W] (f91031ff-3) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (1.0847ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:19.443155800Z][com.docker.diagnose.exe][I] (f91031ff-4) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:19.443155800Z][com.docker.diagnose.exe][W] (f91031ff-4) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:20.447380200Z][com.docker.diagnose.exe][I] (f91031ff-5) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:20.447380200Z][com.docker.diagnose.exe][W] (f91031ff-5) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (208.1µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:21.451469900Z][com.docker.diagnose.exe][I] (f91031ff-6) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:21.451613100Z][com.docker.diagnose.exe][W] (f91031ff-6) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (143.2µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:22.457118000Z][com.docker.diagnose.exe][I] (f91031ff-7) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:22.457350600Z][com.docker.diagnose.exe][W] (f91031ff-7) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (232.6µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-11T09:11:23.460199100Z][com.docker.diagnose.exe][I] (f91031ff-8) 23085f14-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-11T09:11:23.460199100Z][com.docker.diagnose.exe][W] (f91031ff-8) 23085f14-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[FAIL] DD0005: is the user in the docker-users group? The user name could not be found.
[FAIL] DD0038: is the connection to Docker working? HTTP GET https://login.docker.com: Get "https://login.docker.com": proxyconnect tcp: open \\.\pipe\dockerHTTPProxy: The system cannot find the file specified.
[FAIL] DD0014: are the backend processes running? 4 errors occurred:
        * com.docker.backend.exe is not running
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running
        * com.docker.wsl-distro-proxy.exe is not running


[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.
[2023-05-11T09:11:23.705933100Z][com.docker.diagnose.exe][I] ipc.NewClient: ec5ad648-diagnose -> \\.\pipe\dockerBackendApiServer BackendAPI
```

**Comment by jamiematrix** [comment] 2023-05-11 12:57
I've managed to download and re-install Docker Desktop 4.19.0. So far the only site I've tried has started OK and is responding.

**Comment by ctalledo** [comment] 2023-05-11 16:21
Hi @jamiematrix, thanks for opening up the issue. On a first look, it appears to be a problem in the Docker Desktop installation. 

> I've managed to download and re-install Docker Desktop 4.19.0. So far the only site I've tried has started OK and is responding.

Does this mean that the problem is now resolved after re-installing? If so, I think we can close this issue. 

Thanks.

**Comment by oliveirafernandaz** [comment] 2023-05-13 14:24
I'm trying to solve this problem for a couple of days. unfortunately, re-installing didn't work for me. DD stops lauching again when I logout or restart my pc.

**Comment by ctalledo** [comment] 2023-05-15 17:20
Thanks @jamiematrix, glad to know the re-install solved the problem for you 👍 .

**Comment by ctalledo** [comment] 2023-05-15 17:22
> I'm trying to solve this problem for a couple of days. unfortunately, re-installing didn't work for me. DD stops lauching again when I logout or restart my pc.

Hi @oliveirafernandaz, please open a separate issue for this and if possible [upload the diagnostics bundle](https://docs.docker.com/desktop/troubleshoot/overview/). There are different reasons why DD may not start on WSL, so this way we can track your particular issue and see if it's related to a know issue or not. 

Thanks!

**Comment by ctalledo** [comment] 2023-05-15 17:23
Resolved via re-install of Docker Desktop.

**Closed by ctalledo** 2023-05-15 17:23 UTC
