### ISSUE TITLE
VPNkit using up all free memory

### ISSUE THREAD

**Issue by RonRadtke** [docker/for-win#6588] opened 2020-05-07 20:24 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D373AB3C-6015-4F29-8155-DD4BFD13B9F5/20200507200006

### Actual behavior
vpnkit-bridge.exe will consume all available memory. Restartig docker is freeing the memory for some hours till it is full again (takes up to 8GB of memory).
Seems like vpnkit-bridge.exe is allocating additional 50mb every around 20-30sec, but never freeing anything again.
Can't run diagnostics when memory is at 100% because of the vpnkit.
### Information

  - Windows Version: 1909 KB4550945 Pro Edition
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
Just happens by itself

**Comment by mat007** [comment] 2020-05-08 08:18
Thanks for the report, this is actually a duplicate of #5841 and has been fixed in Edge 2.3.0.0.
It will reach Stable most likely on Monday.

**Closed by mat007** 2020-05-08 08:18 UTC
Labels: version/2.2.0.5
