### ISSUE TITLE
Unable to disable Docker Desktop auto-updates

### ISSUE THREAD

**Issue by wilem82** [docker/for-win#10035] opened 2021-01-07 13:05 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

All of a sudden Docker Desktop says it will apply an update on the next restart.

### Expected behavior

Auto-updates should be disable-able in the settings and not update anything without the user's approval.

### Information
  - Windows Version: `20H2 (OS Build 19042.630)`
  - Docker Desktop Version: `3.0.4 (51218)`
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: `nope`

### Steps to reproduce the behavior

1. Install Docker Desktop
2. Sometimes in the future observe Docker Desktop deciding it wants to apply a self-update

### Notes

Is there some workaround please, perhaps in a json settings file? Or maybe block some IP addresses, to stop the auto-update check? Thank you.

PS. There is no auto-update option in the General settings, as multiple people mentioned: https://snipboard.io/xw1Iui.jpg

**Comment by stephen-turner** [comment] 2021-01-07 14:27
Dupe of docker/roadmap#183

**Closed by stephen-turner** 2021-01-07 14:27 UTC
