### ISSUE TITLE
Windows does not support host IP addresses in NAT settings

### ISSUE THREAD

**Issue by bortot-systems** [docker/for-win#10688] opened 2021-03-17 11:19 UTC
Actual behavior
Error to start docker container
(HTTP code 500) server error - failed to create endpoint web-59057-When-issue-is-yellow-very-difficult-to-see-White-text-on-Yellow-bg on network dockercompose4185379768228670846_default: Windows does not support host IP addresses in NAT settings
https://ibb.co/jbfTt4x

Expected behavior
Can you please explain what should we do to make it start? After the release of version 3.2.1 and 3.2.2 it's no longer working,
Thank you.

Windows Version: 10
Docker Desktop Version: 3.2.2 
WSL2 or Hyper-V backend? Yes

**Comment by stephen-turner** [comment] 2021-03-17 12:10
Closing as dupe of #10552.

**Closed by stephen-turner** 2021-03-17 12:10 UTC

**Comment by bortot-systems** [comment] 2021-03-17 12:16
Closing as dupe does not solve the problem when in the link provided people agreed that the solution is to downgrade to version 3.1 and prevent docker update.
Really? Is that even a solution?
As a developer my understand is that you guys have no idea of the bug you created and are not willing to solve it

**Comment by stephen-turner** [comment] 2021-03-17 13:42
Closing as a dupe just means that we already have a ticket for that item. We like to concentrate the discussion on one ticket. We are working on the bug.

**Comment by bortot-systems** [comment] 2021-03-17 14:15
OK thank you.
