### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure at New-Switch

### ISSUE THREAD

**Issue by JCWolf** [docker/for-win#3303] opened 2019-01-29 08:54 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F9A12E9E-585A-4707-8A80-B522AE5A3792/20190129102039

### Expected behavior
Docker should start successfully
### Actual behavior
Docker throws:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
### Information

  - Windows Version: Windows 10 Version 1803 Build 17134.523
  - Docker for Windows Version: 2.0.0.2(20215) Build 0b030e1

### Steps to reproduce the behavior

I don't know how to reproduce this but I can say what happened. 
I had docker installed on my laptop for a few months now and it was working great until a few weeks ago i tried to start a project with Java's Spring Boot, Maven and a Mysql Database. 
I have two computers. The one with Linux had no problems with the app but this Windows machine had. It started the containers fine but I couldn't access the IP of the app so I was thinking is a problem with Windows and so I uninstalled Docker. 

Today I installed it again and gave me this error. I did [this](https://github.com/docker/for-win/issues/863#issuecomment-312165754) but with no success.
I also uninstalled the Cisco AnyConnect VPN (some people mentioned that VPN software can be a casue) but with no success.
What can be the cause of this?
  1. ...
  2. ...

**Comment by THEjoezack** [comment] 2019-02-04 20:02
Having the same problem here. I noticed it last week, but it's been a while since I've tried to run docker before that. I can see that Virtual Machine Management Service is running, I did update to the latest stable version, I did uninstall/reinstall Docker for Windows. I too followed the advice here: https://github.com/docker/for-win/issues/863#issuecomment-312165754

**Comment by martinsubash** [comment] 2019-02-12 09:35
I also face the same problem.

**Comment by agungsus** [comment] 2019-02-18 02:34
Same here, did someone already found the workaround?

**Comment by sniderjoshua** [comment] 2019-03-18 15:39
I'm at this issue as well.

**Comment by mikeparker** [comment] 2019-05-30 13:59
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 13:59 UTC

**Comment by KimiaBaba** [comment] 2020-03-29 13:51
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Project 'MyCms' is not found.

I Have This Problem in asp.net core 3.1 project.

**Comment by KimiaBaba** [comment] 2020-03-29 13:52
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Project 'MyCms' is not found.

**I Have This Problem in asp.net core 3.1 project.**
