### ISSUE TITLE
failed to start the docker engine

### ISSUE THREAD

**Issue by VAISH2806** [docker/for-win#13497] opened 2023-05-19 16:54 UTC
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: C26A1672-0438-40D4-8C7D-D8D563F1F3AC/20230519164624

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ctalledo** [comment] 2023-05-23 19:36
Thanks @VAISH2806 for reporting.

Diagnostic bundle logs show DD 4.19 fails to get the WSL version from the host:

```
log/host/com.docker.backend.exe.log: 2023-05-19T 16:46:05.753029900Z [com.docker.backend.exe][E] getting WSL version: exit status 0xffffffff
```

It's a duplicate of issue #13445 (will mark this issue as such).

To work around it, try upgrading to the latest WSL version on your host please:

1) In your windows host, go to `settings -> windows update -> advanced` options and enable "receive updates for other microsoft products".

2) Open a command prompt or powershell and type `wsl --update`.

3) Verify the WSL version via `wsl --version`. It should show something like this:

```
C:\> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22624.1755
```

If `wsl --version` returns an error, please post the output here. Thanks!

**Closed** 2023-05-23 19:36 UTC
Labels: area/WSL2, duplicate, version/4.19.0
