### ISSUE TITLE
unknown blob when downloading nanoserver image

### ISSUE THREAD

**Issue by fegonfe** [docker/for-win#131] opened 2016-10-05 20:58 UTC
docker pull microsoft/nanoserver:latest
latest: Pulling from microsoft/nanoserver

### Expected behavior
image downloaded 

### Actual behavior
5496abde368a: Downloading (retries a few times and then abort)
unknown blob

other images downloads additional files but not the base image
docker pull microsoft/dotnet:1.0.1-nanoserver-core
5496abde368a: Downloading
68c8748424c9: Download complete
255fd0bbdec4: Download complete
4a8f25264872: Download complete
9d8cae9ccd82: Download complete
unknown blob
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
90DA9120-CF7C-4641-AA08-EFD3BDD7CE8E/2016-10-05_17-49-47

 I've tried with latest version and with beta 27. Same issue.

**Comment by artisticcheese** [comment] 2016-10-07 22:07
Same for WindowsServerCore. Solution is to use 1.13 client from here (https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10) but this shall be documented somewhere on docker website since anybody who would want to use windows containers with official RC client from docker website would fail to do so.

**Comment by fegonfe** [comment] 2016-10-07 23:03
Thanks. I was able to download it. 
Now the problem is that it hangs on docker run. It seems very likely a deadlock because docker and dockerd are just waiting

**Comment by fegonfe** [comment] 2016-10-10 20:14
I had to install version 1.13 AND KB3194496. Now, it is working.

**Comment by artisticcheese** [comment] 2016-10-10 20:16
Why did you close this? This is really a workaround for public issue. Anybody who will try out right now Docker on Windows will fail to do so since the only Beta version which is available through Docker website is 1.12

**Comment by fegonfe** [comment] 2016-10-10 21:40
The hang problem seems duplicate to issue #115.

**Comment by friism** [comment] 2016-10-17 18:39
@artisticcheese @fegonfe The latest beta ships with 1.12-cs2 which has a fix for this. Please upgrade, and feel free to re-open if you find that the problem is not solved.

**Closed by friism** 2016-10-17 18:39 UTC
Labels: area/wincon

**Comment by ateimoo** [comment] 2017-01-12 15:03
You can't pull any windows images using Docker Toolbox!!!
The daemon is Linux running on virtualbox. No mention of this in Docker docs :(
