### ISSUE TITLE
Dashboard completely unresponsive to user interaction without active network connection

### ISSUE THREAD

**Issue by epixian** [docker/for-win#10647] opened 2021-03-14 13:36 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics 
  - Diagnostics ID: (unable to generate diagnostics as the software is unresponsive)

### Actual behavior
When there is no active network connection, Docker Desktop hangs on start and is completely unresponsive to user interaction.  This is after a fresh restart and WSL2 not running when Docker Desktop starts.  When a network connection is established, Docker Desktop works as normal.  I thought this may have had something to do with the "Show weekly tips" or "Send usage data" preferences but the problem persists with both settings unchecked.

### Expected behavior
Docker Desktop should load and respond to user interaction regardless of network connection status.  If a connection is not available, a message or other indication in the status bar should indicate degraded conditions.  The localhost containers should still work regardless.  

Working without an active network connection should not render the application usable and should be an expected use case scenario (e.g. on an airplane).

### Information

  - Windows Version: Windows 10 1909 build 18363
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Quit Docker Desktop and run `wsl --shutdown`
  2. Disable network connection (e.g. disconnect, disable wifi, enable airplane mode, etc)
  3. Start Docker Desktop
  4. Open the dashboard

**Comment by stephen-turner** [comment] 2021-03-15 10:26
Thanks for the report, closing as a dupe of #10563.

**Closed by stephen-turner** 2021-03-15 10:26 UTC
