### ISSUE TITLE
Docker Desktop WSL2 fails to launch when ~/.bashrc contains interactive commands

### ISSUE THREAD

**Issue by Apreche** [docker/for-win#12787] opened 2022-06-17 14:01 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C7017BE1-14B7-4D0E-93DE-C5B54C5DF7B1/20220617135346

### Actual behavior
Docker Desktop executes the `~/.bashrc` file when it launches.
Because my bashrc file contains commands which interactively prompt the user, Docker Desktop fails to start.

### Expected behavior
I expect Docker Desktop to always launch successfully regardless of the contents of the bashrc file.
Alternatively, Docker Desktop could export an environment variable that could be checked for in the bashrc file so that the interactive commands could be conditionally skipped.

### Information
I am running Ubuntu 20.04.4 LTS with Windows 11 and the latest Docker Desktop for Windows with WSL2 integration.

My personal `~/.bashrc` file in the WSL distro contains commands which interactively prompt the user for input. Docker Desktop attempts to execute my personal bashrc file when it starts. The presence of commands with interactive prompts prevents Docker Desktop from starting. If I remove the line from the bashrc file, Docker Desktop launches and runs perfectly. 

It is not a new problem. It has been around for quite awhile. I just finally got around to reporting it.

  - Windows Version: 11 Pro 21H2 22000.739
  - Docker Desktop Version: 4.8.2 (79419)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
segment 2022/06/17 09:49:35 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io: getaddrinfow: The requested name is valid, but no data of the requested type was found.
segment 2022/06/17 09:49:35 ERROR: 1 messages dropped because they failed to be sent and the client was closed
No fatal errors detected.
```

Note: You can ignore the error about segment.io. That is happening because I have a Pi-hole which blocked the segement.io domain.

### Steps to reproduce the behavior
1. Install Ubuntu 20.04.4 LTS as the default WSL2 distro.
1. Install Docker Desktop for Windows.
2. Launch Docker Desktop. It should work normally.
3. In Docker Desktop settings enable "Use the WSL 2 based engine"
4. In Docker Desktop settings enable WSL Integration with the Ubuntu distro.
5. Quit Docker Desktop so that it is no longer running.
6. Open a WSL terminal for the installed Ubuntu distribution.
7. Edit the current user's `~/.bashrc` file in a text editor.
8. Add a line to the file that interactively prompts for input such as `read -p "Hello: "`, and save the changes.
9. Attempt to launch Docker Desktop. It will fail to launch.
10. Remove the line from the bashrc file and save the changes.
11. Attempt to launch Docker Desktop. It will launch as normal.

**Comment by StefanScherer** [comment] 2022-06-29 19:35
Thanks for the report. This is a duplicate of #12622 and it is fixed in 4.9.0 and above.

**Closed by StefanScherer** 2022-06-29 19:35 UTC
Labels: version/4.8.2
