### ISSUE TITLE
Time in container gets desychronized after wake up 

### ISSUE THREAD

**Issue by snekcz** [docker/for-win#5593] opened 2020-01-25 08:55 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 23379FB9-A5CD-4FE6-9206-CBF82284EFB0/20200125083318

### Expected behavior
Time in containers is always synchonized with the host time.
### Actual behavior
Time in container gets desynronized when host put to sleep and then woke up. Actually when host is put to sleep, the time is paused and after wake up it continues from that moment. 
Actual example:
Real time: Sat Jan 25 09:46:07 CET 2020
Time in container: Fri Jan 24 21:25:45 CET 2020
### Information

  - Is it reproducible? yes
  - Is the problem new? yes 
  - Did the problem appear with an update? yes, just after update to 2.2.0.0

  - Windows Version: Win 10 Pro1903
  - Docker Desktop Version: 2.2.0.0 (42247)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Run Docker Desktop
  2. Put host to sleep
  3. Wake up the host after some time
  4. The time is not synchonized
  5. When you restart Docker Desktop, the time is synchronized again

**Comment by snekcz** [comment] 2020-01-26 10:24
It is probably the same issue as https://github.com/docker/for-win/issues/4526

**Comment by Mikk36** [comment] 2020-01-27 22:00
Possibly also #3168

**Comment by coip** [comment] 2020-01-27 22:14
hadnt even considered sleep as contributing to timing discrepancy between Win/Docker off HyperV.

explains the ~inconsistent deviation I was observing... few hours off one day, none the next.

**Comment by korvin2000** [comment] 2020-01-28 09:16
Since version 2.2.0.0 at least 4 developers in our team have same issues with docker desktop for windows. It's really annoying such goofy  bugs in docker.

**Comment by samerdokas** [comment] 2020-01-29 14:25
I can confirm this.

```
> date < nul
The current date is: 2020-01-29
> time < nul
The current time is: 15:23:07,65
> docker run --rm -it ubuntu:18.04 /bin/bash
root@c903b00c3da2:/# date
Tue Jan 28 22:47:43 UTC 2020
```

**Comment by MartinSoto** [comment] 2020-01-31 14:35
I can confirm this as well; time drifts every time I put the machine to sleep. My current workaround is something like this
```
docker run --rm --privileged ubuntu hwclock -s
```
This may or may not work well depending on whether your Windows machine's hardware clock is set to UTC or to local time, but you may manage to vary this in an appropriate way. See [hwclock's documentation](https://linux.die.net/man/8/hwclock) for details.

**Comment by aaronadamsTO** [comment] 2020-02-03 17:50
Another workaround is to restart the Time Synchronization service (credit @ThorstenHans):

1. Run PowerShell as administrator
2. Run command:
    ```
    Disable-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization"
    Enable-VMIntegrationService -VMName DockerDesktopVM -Name "Time Synchronization"
    ```

This should restart the time synchronization service and immediately restore the correct time inside your containers.

**Comment by WolfspiritM** [comment] 2020-02-05 09:46
Same issue here. I'm using docker for desktop since it was released and never had this issue but since 2-3 days I experienced issues cause "apt-get update failed in the container with:

```
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 2h 29min 4s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 15h 27min 25s). Updates for this repository will not be applied.
```

I'm putting my computer to sleep regularily. Seems to be a bug in Hyper-V?!

**Comment by iTaybb** [comment] 2020-02-05 12:40
can confirm as well. v2.2.0.

**Comment by stephen-turner** [comment] 2020-02-10 13:22
Thanks for the reports. We're looking into this. We're not doing anything different here from previously, but we think something has changed in Hyper-V and/or the Linux kernel that we will need to work around.

**Comment by liayn** [comment] 2020-02-17 13:19
@stephen-turner This problem is not new and exists at least 1 year now, if not even longer. I got used to it restarting docker from time to time.

**Comment by snekcz** [comment] 2020-02-17 13:31
> @stephen-turner This problem is not new and exists at least 1 year now, if not even longer. I got used to it restarting docker from time to time.

I cannot fully agree with you, @liayn. First time I have experienced this issue was when I upgraded to 2.2.0.0. I'm now back on 2.1.0.5 beacuse of other issues and time is perfectly in sync all the time. So, it seem to be at least somehow connected to the upgrade.

**Comment by liayn** [comment] 2020-02-17 13:37
@snekcz Good for you. But as I wrote, I have this problem for a much longer time, and colleagues are having them too. (I was always on Dell XPS 9570, latest Win 10 Pro, latest BIOS, and so on)

**Comment by pep4eto1211** [comment] 2020-02-17 13:38
I can confirm I also experience the issue on 2.2.0.3 (42716). A workaround is to restart Docker. However, I believe that it might have something to do with Hyper-V. I noticed the issue when my auth for gsutil failed inside a running container. I had the exact same issue, when trying to authenticate gsutil on a linux VM running on Hyper-V.

**Comment by hvolmer** [comment] 2020-02-20 03:25
I can confirm as well, 2.2.1.0 edge.  

Very annoying with AWS not liking the timestamps on API requests. @aaronadamsTO's powershell steps gets things back in line.

**Comment by philippe-granet** [comment] 2020-03-06 08:02
**In release note:**
https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2203
**Known issues:** 
_In some cases, Docker containers do not synchronize time with the host when the host machine is put to sleep._

**Comment by cluetjen** [comment] 2020-03-12 11:00
Had the same problem with 2.2, then I've updated Windows to use insider preview version (slow) and it seems to work now.

**Comment by rpatrick00** [comment] 2020-03-23 14:12
I am seeing this issue with Docker Desktop 2.2.0.4.  The issue goes away if I downgrade to Docker Desktop 2.1.0.5.

**Comment by stephen-turner** [comment] 2020-03-23 14:25
This is a dupe of #4526, so I'm going to close this copy. @rpatrick00 There is a new build at https://github.com/docker/for-win/issues/4526#issuecomment-600688253 that you can try.

**Closed by stephen-turner** 2020-03-23 14:25 UTC
Labels: status/0-triage, version/2.2.0.0

**Comment by rpatrick00** [comment] 2020-03-24 13:58
@stephen-turner Thanks, the new build resolves my issue.

**Comment by sumantan** [comment] 2020-04-16 13:14
Seeing this issue in 2.2.3.0 edge running on WSL2

`sudo hwclock -s`
unblocks docker builds
