### ISSUE TITLE
MSSQL 2019 Fails To Start after Docker Upgrade

### ISSUE THREAD

**Issue by martyt** [docker/for-win#6656] opened 2020-05-12 14:07 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C3CC884A-106D-42E6-9542-153DDE7CE8F5/20200512141442

### Expected behavior
Normal MSSQL startup. Worked just fine before the upgrade
### Actual behavior

MSSQL docker container fails to start, with the following logs. Note that the referenced folder `C:\templatedata\....` does not exist on my machine and has never existed on my machine, nor is it part of my installation - I'm guessing something else has gone wrong, triggering some kind of "recovery" mode in MSSQL that wasn't converted properly for Docker use. 

```
SQL Server 2019 will run as non-root by default.

This container is running as user mssql.

Your master database file is owned by root.

To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.

2020-05-12 13:41:15.05 Server Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.

2020-05-12 13:41:15.12 Server ERROR: Setup FAILED copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf': 1(Incorrect function.)

ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)

SQL Server 2019 will run as non-root by default.

2020-05-12 13:41:17.95 Server Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.

2020-05-12 13:41:18.01 Server ERROR: Setup FAILED copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf': 1(Incorrect function.)

2020-05-12 13:41:21.13 Server Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.

2020-05-12 13:41:21.20 Server ERROR: Setup FAILED copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf': 1(Incorrect function.)
```
### Information

  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: Community v2.3.0.2 Engine v19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Upgraded  to Docker v19.03.8
Prior installation was working fine with no issues.

C:\ drive was shared with Docker

MSSQL 2019 latest version was installed via 

```
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=45$rfGGgt!" --restart unless-stopped -p 1433:1433 --network=qes_default --name omniusdevsql -h omniusdevsql -v c:/omniusdevsql/data:/var/opt/mssql/data -v c:/omniusdevsql/log:/var/opt/mssql/log -v c:/omniusdevsql/secrets:/var/opt/mssql/secrets -v c:/omniusdevsql/backup:/var/opt/mssql/backup -v c:/omniusdevsql/scripts:/var/opt/mssql/scripts -d mcr.microsoft.com/mssql/server:2019-latest
```

I have tried explicitly sharing `c:\omniusdevsql` instead of just `c:\` but no change.

**Comment by waynesi** [comment] 2020-05-12 15:00
Same issues here. Working all right after rolling back (uninstall and reinstall) to the earlier v2.2.0.5.

Seriously please include running mcr.microsoft.com/mssql/server:latest with host folder binding in your pre-release tests. Many times either a docker update or an image update crashed each other.

**Comment by abbatepabloo** [comment] 2020-05-12 15:23
Same problem here... How can I make a downgrade to the prior version in Windows 10?

**Comment by waynesi** [comment] 2020-05-12 15:24
> Same problem here... How can I make a downgrade to the prior version in Windows 10?

Uninstall and reinstall. Bear in mind, uninstall will remove all your local images and containers.

**Comment by abbatepabloo** [comment] 2020-05-12 15:33
Thanks @waynesi!
Is there any way to get the prior windows installer? When I downloaded the current one, I cut see it has the version (2.3.0.2). So, it's not going to install the prior version..

**Comment by waynesi** [comment] 2020-05-12 15:46
> Thanks @waynesi!
> Is there any way to get the prior windows installer? When I downloaded the current one, I cut see it has the version (2.3.0.2). So, it's not going to install the prior version..

Here you are - https://docs.docker.com/docker-for-windows/release-notes/ A download link under each version's section.

**Comment by mat007** [comment] 2020-05-13 06:25
Does it look like the same as #6646?

**Comment by waynesi** [comment] 2020-05-13 07:31
> Does it look like the same as #6646?

Yes. Although I'm using SQL 2019 and docker run; thus followed up on this post, I'm certain the host volume binding is the cause and two issues are essentially the same.

**Comment by stephen-turner** [comment] 2020-05-13 07:40
OK, let's close this one as a dupe and continue the discussion in #6646.

**Closed by stephen-turner** 2020-05-13 07:40 UTC
