### ISSUE TITLE
Cant switch to Windows containers in Windows 10

### ISSUE THREAD

**Issue by NuxYoung** [docker/for-win#11935] opened 2021-08-19 08:45 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:8DDC9EAA-31DF-462E-9B19-FCA0CBFE45E1/20210819082923

### Actual behavior
Cant switch to Windows containers
### Expected behavior
Change to Windows containers
### Information

  - Windows Version: windows 10 20H2 19402.1165
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  my PC

### Steps to reproduce the behavior

  1. start docker
  2. switch to Windows containers

**Comment by StefanScherer** [comment] 2021-08-20 08:32
Thanks for the report. We're aware of this issue and are working on a fix. In the meantime follow the workaround described here: https://github.com/docker/for-win/issues/11899#issuecomment-900084477
I'll close this ticket as it's a duplicate of #11899.

**Closed by StefanScherer** 2021-08-20 08:32 UTC
