### ISSUE TITLE
Crash while switching from Linux to Windows containers

### ISSUE THREAD

**Issue by arcesso** [docker/for-win#11899] opened 2021-08-15 02:41 UTC
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 833F8C2E-C875-4CFF-8675-948C94E96548/20210815023100

### Actual behavior

Application crash

System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary\`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

### Expected behavior
Switch from Linux to Windows containers.

### Information

  - Windows Version: Win 10 Pro 21H1
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

While Docker Desktop Service and Hyper-V Virtual Machine Management services are started:
  1. Attempt to switch to windows containers

**Comment by StefanScherer** [comment] 2021-08-17 08:05
Thanks @arcesso for the diagnostics. It looks like there's a permission problem as I can see this error in service.txt
```
[19:29:54.634][WindowsDaemon     ][Error  ] fatal: open C:\ProgramData\Docker\panic.log: Access is denied.
```
Please remove or rename the file `C:\ProgramData\Docker\panic.log` and try again. We have an internal ticket to look into it why this happens sometimes.

**Comment by freddydk** [comment] 2021-08-17 08:20
After the upgrade - panic.log on my machine was Read/Only - changing it to Read/Write solved the problem.

**Comment by fshaikhversapay** [comment] 2021-08-17 13:24
Yes, this solution worked for me. I unchecked the ‘Read-Only’ on the panic.txt file and then did the switch to windows containers, and it switched successfully.

**Comment by wrightIT-dev** [comment] 2021-08-17 14:40
had same problem after updating docker. This solution worked for me as well, thanks!

**Comment by stu85010** [comment] 2021-08-17 15:24
> Thanks @arcesso for the diagnostics. It looks like there's a permission problem as I can see this error in service.txt
> 
> ```
> [19:29:54.634][WindowsDaemon     ][Error  ] fatal: open C:\ProgramData\Docker\panic.log: Access is denied.
> ```
> 
> Please remove or rename the file `C:\ProgramData\Docker\panic.log` and try again. We have an internal ticket to look into it why this happens sometimes.

Thanks y’all, you saved my week😂😂😂

**Comment by arcesso** [comment] 2021-08-17 17:11
That worked perfectly! Thank you for your help.

**Comment by RaKuNbg** [comment] 2021-08-18 04:56
Works for me, too.
Was that some kind of joke of the developer to create a file called "panic.log" that prevents people from working?

**Comment by Marcuzz** [comment] 2021-08-20 08:16
This seems to happen after every single Windows update (I'm on Windows 11, so this happens every week) 😅

**Comment by NuxYoung** [comment] 2021-08-23 00:31
It do work when I delete the panic.log.  But everytime I restart my machine, I need to do it again (all for everyone authority)
is there any good ways to solve this problem?

**Comment by freddydk** [comment] 2021-08-23 06:59
Same here - every reboot - panic.log needs to be removed manually.
Seems like a good idea to add some resilience to the startup process in docker - and just remove the file if it is there (not considering so much why it wasn't removed by somebody else).

**Comment by slonopotamus** [comment] 2021-08-23 07:40
> is there any good ways to solve this problem?

Revert to Docker Desktop 3.5.2?

**Comment by RaKuNbg** [comment] 2021-08-23 07:43
Revert to Docker 3.5.2 didn't solve the problem for me.

**Comment by ebriney** [comment] 2021-08-25 10:52
Hello, can someone test this build with a patch that removes the ReadOnly attribute before launching dockerd and confirm me it fixes the issue?
cc @RaKuNbg @slonopotamus @arcesso @NuxYoung @Marcuzz @stu85010

**Comment by freddydk** [comment] 2021-08-25 11:04
@ebriney - what build?

**Comment by freddydk** [comment] 2021-08-25 11:25
I created a file called nopanic.bat with this content:
```
attrib c:\programdata\docker\panic.log -r
```
and placed it in shell:startup (C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)

Now I can reboot without docker crashing.
When I rename the .bat file to .bat.txt - then docker crashes again (and notepad opens with my bat.txt file:-))

so yes, @ebriney - it works for me.

**Comment by ebriney** [comment] 2021-08-25 11:29
Sorry build is there: https://desktop-stage.docker.com/win/main/amd64/67682/Docker%20Desktop%20Installer.exe

**Comment by bjornlyngwa** [comment] 2021-08-25 12:00
Hi @ebriney,
It's still crashing for me on startup. I am using Windows containers.

The C:\ProgramData\Docker\panic.log file is still marked as read only.

**Comment by Marcuzz** [comment] 2021-08-25 12:20
Can confirm `panic.log` still has the read only attribute, even after deleting it and having Docker re-create it with the provided build.

**Comment by StefanScherer** [comment] 2021-08-25 12:45
@Marcuzz @bjornlyngwa Sorry, we got the wrong link. I've updated the comment above and a step how you can "downgrade" to install the build 67678.

**Comment by lorenrh** [comment] 2021-08-31 15:19
Hello,

Docker Desktop 4.0.0 has been released containing a fix for this issue, so I'm closing this issue. Feel free to open a new ticket if the problem persists.

**Closed by lorenrh** 2021-08-31 15:19 UTC

**Comment by travnick** [comment] 2021-09-03 13:35
@lorenrh so there will be no fix for 3.6.0 release?

I'm asking since you've changed the licensing rules at version 4.0.0

**Comment by gitvadim** [comment] 2021-09-10 09:10
I can confirm that this issue still exists (at least for me) in Docker 4.0.0 and it started appearing after I had upgraded to 4.0.0.

**Comment by trungutt** [comment] 2021-09-30 15:37
The official 4.1.0 release is out with the fix included

**Comment by Sven-Niehus** [comment] 2021-11-04 13:23
I'm having the same issue as @AlphaKintari. Every time I reboot my machine the "C:\ProgramData\docker\panic.log" file is read only and I have to either delete it or change it manually to read/write again. 

@lorenrh can you maybe reopen this issue?

I'm on Windows Server 2022 Standard with the latest updates:
![image](https://user-images.githubusercontent.com/9822857/140320169-69bf3b11-d764-46f4-add6-2ff9a4ec34c5.png)


Docker Info output:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.10
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Standard Evaluation Version 2009 (OS Build 20348.288)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 4.999GiB
 Name: SVNITEST
 ID: 5RZC:MAIY:4VTX:E67I:WSUO:HMCC:4CMV:JENG:AKMG:35V2:6LZD:XEE6
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
