### ISSUE TITLE
Docker Unable to Start Docker

### ISSUE THREAD

**Issue by samgegr8** [docker/for-win#3842] opened 2019-05-02 14:23 UTC
Hi Team,

**Facing the below error** 
while we start the Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74

Tried All the steps mentioned in 

https://github.com/docker/for-win/issues/863 but still facing the issue. 

Help is needed.

One more Pointer. When I open Hyper-V Manager . I see below error

![image](https://user-images.githubusercontent.com/33149835/57082210-9e6cba80-6d39-11e9-84ab-99377ec9dcd3.png)

**Comment by mikeparker** [comment] 2019-05-30 13:53
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 13:53 UTC
