### ISSUE TITLE
Adding hosts for windows containers (--add-host, extra_hosts) does not work

### ISSUE THREAD

**Issue by Dresel** [docker/for-win#1455] opened 2017-12-22 11:12 UTC
### Expected behavior

Either docker run `--add-host` argument or docker compose `extra_hosts` option should add host entry to etc/host for windows containers.

### Actual behavior

Neither docker run `--add-host` argument nor docker compose `extra_hosts` option does add host entry to etc/host for windows containers.

### Information

  - Windows: Windows 10, 1709
  - Docker: 17.12.0-ce-rc4
  - Compose: 1.18.0

#### Not working example for windows container

  1. Run `docker run -it --add-host me:127.0.0.1 microsoft/nanoserver`
  2. Run `ping me`

#### Additional working example for linux container

  1. Run `docker run -it --add-host me:127.0.0.1 ubuntu`
  2. Run `apt-get update`
  3. Run `apt-get install iputils-ping`
  4. Run `ping me`

**Comment by hamid-riahi** [comment] 2018-01-12 02:49
I also have the same problem

**Comment by pasiorovuo** [comment] 2018-01-27 20:07
Same behavior confirmed.

**Comment by artisticcheese** [comment] 2018-02-06 21:12
Is not this supposed to be filed under moby/moby?

**Comment by icenold** [comment] 2018-02-09 12:28
anyone has a workaround for this?

**Comment by cnickel** [comment] 2018-02-09 13:15
@icenold, I did the following within the Dockerfile, it has worked for my needs.

```
RUN $file = $Env:windir+'\System32\drivers\etc\hosts'; `
'10.0.0.1 some.host.com' | Add-Content -PassThru $file;
```
note that i use the back tick as my escape character.

**Comment by artisticcheese** [comment] 2018-02-09 14:40
Probably much easier just
```
 "10.0.0.1 some.host.com" | Out-File -Append "$($Env:windir)\drivers\etc\hosts"
```

**Comment by icenold** [comment] 2018-02-09 16:04
is there no way to do this via compose?

**Comment by artisticcheese** [comment] 2018-02-09 16:12
It's bugged out as you can see on this thread. It does not do what is expected. I beleive this shall be filed under moby/mody not docker for win.

**Comment by icenold** [comment] 2018-03-30 16:18
any update/s?

**Comment by ToMaHaWk** [comment] 2018-04-24 20:58
I have the same issue. Any updates?

**Comment by cod7alex** [comment] 2018-05-20 08:31
any updates on this ?

**Comment by jtaylor100** [comment] 2018-06-19 16:36
It's a real pain this isn't supported. It would be really helpful to dynamically add hosts from the command line for development and staging purposes where real host names are not practical to add.

**Comment by tkoestler** [comment] 2018-08-02 00:15
I've run into the same issue.  I need to add some host entries purely for development. Works great on linux containers but we have cases where we must be able to run on Window containers as well. This seems fairly fundamental...

**Comment by starcraft66** [comment] 2018-08-28 14:36
I have run into this issue as well and it is a platfrom-breaking feature in my opinion. The only option to work around this seems to be manually adding entries to the hosts file in a "RUN" directive (but this only works when building on windows!!). If I build a linux image on a linux how, any modifications I make to the hosts file inside the image using a RUN directive are ignored, which means I won't be able to use it properly when pushing and pulling it to a windows LCOW host.

**Comment by poliez** [comment] 2018-11-20 09:34
> I have run into this issue as well and it is a platform-breaking feature in my opinion. The only option to work around this seems to be manually adding entries to the hosts file in a "RUN" directive (but this only works when building on windows!!). If I build a linux image on a linux how, any modifications I make to the hosts file inside the image using a RUN directive are ignored, which means I won't be able to use it properly when pushing and pulling it to a windows LCOW host.
> 
> EDIT: Just to be clear, I am encountering this problem both on Windows and Linux containers, I tried the reproducer @Dresel posted above with ubuntu and it doesn't work, when I try to `ping me`, I get `ping: me: No address associated with hostname` and the `/etc/hosts` file is completely empty.
> 
> I am running Docker CE Stable 18.06.0-ce-win72 (19098) with experimental features enabled on Windows 10 Professional.

I'm reporting the same exact issue. Any updates?

**Comment by Arash-Sabet** [comment] 2019-01-02 16:01
Same issue here. I think it makes sense to expedite addressing this problem.

**Comment by icenold** [comment] 2019-01-11 14:53
still no update?

**Comment by imphasing** [comment] 2019-03-04 23:50
This is kind of annoying because you end up using an ENTRYPOINT script if you want to do it in a generic way.. for my use-case I need to get some network level configuration which is not available during image time, so the ENTRYPOINT ends up running a script to update hosts then start a process

This is janky as hell, it would be really nice to do it from another layer up in the stack, like a compose file or command line option. Any update on this issue?

**Comment by kamavarapu** [comment] 2019-04-21 13:36
Please update.

**Comment by Iristyle** [comment] 2019-05-03 21:47
I think that this probably needs to be filed in https://github.com/docker/cli/issues to get visibility

**Comment by Cloudmersive** [comment] 2019-05-12 05:04
This is a huge problem!  Any updates on this?

**Comment by duki994** [comment] 2019-05-16 08:47
For me, extra_hosts work in compose in Windows 10 latest update.

Docker version: 18.09.2
Compose:  1.23.2

**Comment by icenold** [comment] 2019-05-16 13:52
> For me, extra_hosts work in compose in Windows 10 latest update.
> 
> Docker version: 18.09.2
> Compose: 1.23.2

you mean linux containers on windows10 host or windows containers on windows10 host?

**Comment by duki994** [comment] 2019-05-17 07:18
@icenold 
Linux containers on windows 10 (latest update -> from a day or two ago) host.

**Comment by bormm** [comment] 2019-05-21 08:53
> For me, extra_hosts work in compose in Windows 10 latest update.
> 
> Docker version: 18.09.2
> Compose: 1.23.2
This issue is about windows containers not about linux containers. Linux on Windows is working completely differently.
Just to be clear: The mentioned version is still not working.

**Comment by TCGV** [comment] 2019-08-19 20:32
Same issue here, docker desktop version 2.1.0.1 (37199)

**Comment by sobriant74** [comment] 2019-11-06 19:47
+1 same problem on dockers for windows.

**Comment by mikol4j** [comment] 2019-11-08 14:53
any news?

**Comment by norcis** [comment] 2020-01-20 08:06
Still not working :(

**Comment by mat007** [comment] 2020-01-20 17:26
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby and/or https://github.com/docker/compose instead as that is the more appropriate place.

**Closed by mat007** 2020-01-20 17:26 UTC

**Comment by Roemer** [comment] 2020-04-29 07:30
As this still does not work, adding the values to the hosts file during the build of the Docker image is still a good workaround.
I had quite a few issues getting it to work correctly when using the `SHELL ["powershell"...]` and then adding lines to the hosts file as then every character had an added space. Probably due to encodings.
Using `Add-Content` always gave an error `Stream was not readable` so I was stuck with `echo`.
The way I got it working with multiple entries is as follows:
```
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN cmd /c \"echo 1.2.3.4 host1 >> C:\Windows\System32\drivers\etc\hosts\"; `
    cmd /c \"echo 5.6.7.8 host2 >> C:\Windows\System32\drivers\etc\hosts\";
```
