### ISSUE TITLE
Crash on start after upgrading to 1.12.1-stable on Windows 10

### ISSUE THREAD

**Issue by alvesman** [docker/for-win#111] opened 2016-09-29 09:25 UTC
### Information

log file
[log.txt](https://github.com/docker/for-win/files/500249/log.txt)

**Comment by dgageot** [comment] 2016-09-29 11:28
Hi @alvesman Could you try to reset to factory defaults and see if it fixes the issue?

**Comment by dgageot** [comment] 2016-09-29 11:29
In fact, I'm going to close this as a duplicate of https://github.com/docker/for-win/issues/81

**Closed by dgageot** 2016-09-29 11:29 UTC
Labels: kind/bug

**Comment by alvesman** [comment] 2016-09-29 11:37
Yes, I've reseted to factory defaults. Same behavior.
Thanks, I'll keep watching [https://github.com/docker/for-win/issues/81](url)
