### ISSUE TITLE
From PITLORD

### ISSUE THREAD

**Issue by pitlordsuper** [docker/for-win#7352] opened 2020-06-21 15:55 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pitlordsuper** [comment] 2020-06-21 15:56
Thanks

**Comment by stephen-turner** [comment] 2020-06-22 09:03
No information on what the problem is, closing this ticket.

**Closed by stephen-turner** 2020-06-22 09:03 UTC
