### ISSUE TITLE
Updating Docker to 3.3 crashes because it forgets to trigger UAC admin rights

### ISSUE THREAD

**Issue by Pomax** [docker/for-win#10891] opened 2021-04-11 16:56 UTC
- [ ] ~I have tried with the latest version of Docker Desktop~
  - [ ] ~I have tried disabling enabled experimental features~
  - [ ] ~I have uploaded Diagnostics~

This is a problem with how the Windows version of Docker tries to install and run itself, not with what Docker does once it _is_ running.

### Actual behavior

Updating works, until the new 3.3 tries to start up, at which point it crashes with:
```
System.ComponentModel.Win32Exception:
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.ManagedProcesses.ManagedProcess.StartProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, CancellationToken stopToken) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 122
   at Docker.ManagedProcesses.ManagedProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 50
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Expected behavior

When the updater finishes and Docker restarts, it pops up a UAC dialog going "I need admin rights" and then finalizes the update installation with elevated permissions and without crashing.

### Steps to reproduce the behavior

Not entirely sure how you'd explicitly set up a guaranteed failing setup, but it would probably be:

  1. Use a Windows installation with a standard user account. **THIS IS NOT THE WINDOWS DEFAULT**, instead the first user is an admin by default (this is insane, and the first step is to always downgrade that account to a standard user): run "Change account type", pick your user account, click "change the account type", and make sure that it is set to "standard user". 
  1. Have Windows set to present the user with UAC confirmation dialog when applications need admin rights
    1. run `UserAccountControlSettings.exe`, have the slider all the way at the top.
  1. have Docker "just-before-3.3" installed
  1. Tell Docker to update to 3.3 (I used right-click on the systray icon, "Check for Updates", then started the updated that way)
  1. Run through the update process and observe that Docker crashes once it starts up with that "access error" because it's running as a standard user, so it absolutely doesn't get to mess with the filesystem without explicit permission?

### Workaround that backs up the suspected cause

Quit Docker for Desktop, then manually run it "as administrator" (right click on shortcut, "run as administrator"). All is well, no crashes happen. Quit it again, manually run as yourself (just click it). Watch it crash again.

(Note that "run as admin" runs it under the Admin profile, **not the current user's profile with elevated permission** so that's not actually a solution, it's _only_  a workaround to verify that Docker forgetting to ask windows for elevated permissions via UAC seems to be the problem here)

**Comment by algra4** [comment] 2021-04-12 06:26
I have the same issue

**Comment by StefanScherer** [comment] 2021-04-12 07:18
Thanks @Pomax for the report. We're investigating.

**Comment by algra4** [comment] 2021-04-12 07:20
@StefanScherer  maybe a duplicate with the #10881 ?

**Comment by gottschd** [comment] 2021-04-12 10:17
Hello,

I'm facing the same problem. Uninstalling 3.3.0 and installing again 3.2.2 fixed the problem (temporarily).
However, Docker Desktop will download and install the update 3.3.0 again automatically.

I appreciate the work you are doing, sure. However, with 3.3.0, i'm not able to do my work anymore. To be more exact, i'm blocked because of the update.

How about revoking the version 3.3.0 for now, so users can at least uninstall 3.3.0 and install 3.2.2?
It would help to be able to work again until a fix is available.

Thank you.

**Comment by stephen-turner** [comment] 2021-04-12 10:24
Yes, it's a dupe of #10881. I'm going to close this copy, but thanks for the detailed steps, @Pomax.

**Closed by stephen-turner** 2021-04-12 10:24 UTC
