### ISSUE TITLE
Docker stopped unexpectedly after updating to Windows 10 Insider Preview Build 20175

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#7824] opened 2020-07-25 20:44 UTC
Docker stopped unexpectedly after updating to Windows 10 Insider Preview Build 20175 

Diagnostics uploaded : 5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20200725203104

How do I figure out why this happened, is this a known issue with this build, any suggestions on how to fix

**Comment by stephen-turner** [comment] 2020-07-27 17:00
Docker isn't working well with this Windows build. We've reported it to Microsoft.

**Comment by stephen-turner** [comment] 2020-07-28 07:53
Probably a dupe of #7808.

**Closed by stephen-turner** 2020-07-28 07:53 UTC

**Comment by metcalfc** [comment] 2020-07-31 21:44
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
