### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by oscarpicasso-intact** [docker/for-win#23] opened 2016-08-04 18:23 UTC
### Expected behavior
Run hello-world image

### Actual behavior
C:\Apps>docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority.
See 'docker run --help'.
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  19836E58-CDE9-4E0B-99A2-79D2A3798817/2016-08-04_14-06-22

### Steps to reproduce the behavior
The behavior seems related with the interaction between docker and our corporate proxy.
  1. Install Docker 1.12 on Windows
  2. Configure corporate proxy
  3. Restart docker
  4. docker run hello-world

**Comment by abuechler** [comment] 2016-08-10 11:08
Same here reproduced with:

* Windows 10
* Proxy CA certificate configured on Windows
* Proxy (with user and password) configured in Docker Settings

````
docker version: Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

```

```
docker-machine version 0.8.0, build b85aac1
```

**Comment by dgageot** [comment] 2016-09-09 12:30
@oscarpicasso-intact @abuechler I believe this is a duplicate of #48, so I'm going to close the issue. Feel free to reopen if you don't agree. Thank you for submitting those bug reports!

**Closed by dgageot** 2016-09-09 12:30 UTC
Labels: kind/bug
