### ISSUE TITLE
Network timeout

### ISSUE THREAD

**Issue by rafiq-ahmed** [docker/for-win#57] opened 2016-08-24 16:34 UTC
### Expected behavior
Should connet to server and pull the image

### Actual behavior
docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.

### Information
Done changes in DockerNAT DNS to 8.8.8.8 but did not resolve the issue

  - Diagnostic ID: 6B9CC4F4-C1D2-4753-A945-3BDFB2653777/2016-08-24_21-59-02
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Start docker, try to pull hello-world it give error
  2. change the DockerNAT DNS to 8.8.8.8, still give same issue.

**Comment by ebriney** [comment] 2016-08-25 12:43
Thanks for the report (duplicate of #55).

**Comment by rneugeba** [comment] 2016-08-25 16:14
@rafiq-ahmed as @ebriney said, this seems to be a duplicate of #55. So closing this in favour of #55. Please keep an eye on #55, or post updates there. Thanks again for reporting

**Closed by rneugeba** 2016-08-25 16:14 UTC
Labels: area/network, kind/bug
