### ISSUE TITLE
Error Install Docker

### ISSUE THREAD

**Issue by jerryalfs** [docker/for-win#3991] opened 2019-05-28 03:22 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jerryalfs** [comment] 2019-05-28 03:23
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'EMERIO-USER' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by mikeparker** [comment] 2019-05-30 09:31
Dupe of https://github.com/docker/for-win/issues/1221
Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

**Closed by mikeparker** 2019-05-30 09:31 UTC
