### ISSUE TITLE
75119264-35E0-4E21-9988-D6CF7CD901D4/20190801084325

### ISSUE THREAD

**Issue by kmdyc** [docker/for-win#4366] opened 2019-08-01 08:48 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment] 2019-08-02 15:57
```
[16:43:19.220][IsoConfig         ][Warning] Error while migrating PKI from C:\Users\D37KADM002\AppData\Roaming\Docker\pki : ֵ����Ϊ null��
������: path1
[16:43:19.220][IsoConfig         ][Warning] PKI not migrated, will reissue new cluster certificates
[16:43:19.223][Linux             ][Info   ] Setting container engine status to FailedToStart
[16:43:19.266][NamedPipeServer   ][Error  ] Unable to execute engine/start: ֵ����Ϊ null��
������: path1    �� Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
   �� Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[16:43:19.305][NamedPipeClient   ][Error  ] Unable to send engine/start: ֵ����Ϊ null��
```

**Comment by mikeparker** [comment] 2019-08-02 15:58
Dupe of https://github.com/docker/for-win/issues/3375#issuecomment-515808417

**Closed by mikeparker** 2019-08-02 15:58 UTC
