### ISSUE TITLE
docker push fails on slow internet connection with larger image

### ISSUE THREAD

**Issue by braveness23** [docker/for-win#203] opened 2016-11-04 13:38 UTC
docker push fails with larger image on slow internet connection.  Other versions of dockerd have support to limit concurrent uploads but Docker for Windows does not and will fail to push as sessions time out.  Also internet connection becomes completely unusable during push.
 
--max-concurrent-uploads=5             Set the max concurrent uploads for each push

### Expected behavior

docker login -u [userID] -p [password]
Login Succeeded

docker push [userID]/[image]
The push refers to a repository [docker.io/[userID]/[image]]
81c04cd03377: Pushed
91a380f7f646: Pushed
7bbea1624f36: Pushed
666efc6c06ad: Layer already exists
fc477cce1fc1: Pushed
3eb060b15124: Layer already exists
3152df2b9456: Layer already exists
91b2f3fd06e9: Pushed
cc6b0a07c696: Skipped foreign layer
3fd27ecef6a3: Skipped foreign layer
latest: digest: sha256:b20...fd4c2 size: [size]

### Actual behavior

docker login -u [userID] -p [password]
Login Succeeded

docker push [userID]/[image]
The push refers to a repository [docker.io/[userID]/[image]]
81c04cd03377: Retrying in 1 second
91a380f7f646: Layer already exists
7bbea1624f36: Retrying in 1 second
666efc6c06ad: Layer already exists
fc477cce1fc1: Pushing [===============>                                   ] 84.69 MB/268.1 MB
3eb060b15124: Layer already exists
3152df2b9456: Layer already exists
91b2f3fd06e9: Pushing [=============>                                     ] 75.71 MB/288 MB
cc6b0a07c696: Skipped foreign layer
3fd27ecef6a3: Skipped foreign layer
dial tcp: lookup auth.docker.io: getaddrinfow: No such host is known.

### Information

docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
"There are no setting for Windows containers. Yet!"
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Version 1607 (OS Build 14393.351)

### Steps to reproduce the behavior

  1. Use an internet connection with a slow up speed (in my case 1.19 Mbps)
  2. Push a "large" image (in my case several hundred MB)

**Comment by dgageot** [comment] 2016-12-02 17:10
@braveness23 Could you please give a try to Docker for Windows Beta 31. It contains an updated version of dockerd for Windows Containers.

**Comment by dgageot** [comment] 2016-12-08 21:53
@braveness23 any news?

**Comment by dgageot** [comment] 2016-12-12 18:21
@braveness23 I'm going to assume the issue is fixed and close this issue. Feel free to reopen if it's not the case.

**Closed by dgageot** 2016-12-12 18:21 UTC
Labels: area/network, area/wincon, kind/performance, status/0-more-info-needed
