### ISSUE TITLE
Docker fails to start "A timeout occured while waiting for a WSL integration agent to become ready"

### ISSUE THREAD

**Issue by marvel-code** [docker/for-win#13496] opened 2023-05-19 09:48 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0106EB61-D03C-4997-B61E-191462B09B8A/20230519092735

### Actual behavior
Docker fails starting with error "A timeout occured while waiting for a WSL integration agent to become ready.".

### Expected behavior
Docker starts correctly so I can start containers.

### Information
I tried to shutdown WSL. I restarted pc, reinstalled docker with deleting Docker folders from local and roaming appdata, checked wsl version (it's 2). I was working fine on 8 may on previous version of Docker, but tried to start it today and got that error. I think it is related to forced windows update KB5026372 that was on 9 may.
  - Windows Version: Windows 11, version 22H2
  - Docker Desktop Version: 4.19.0.0
  - WSL2
  - I run Docker Desktop on my PC
 
### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
.\com.docker.diagnose.exe check
[2023-05-19T09:38:49.001209800Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[FAIL] DD0001: is the application running? Docker is not running
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? [ 1970.520407] EXT4-fs error (device sde): ext4_wait_block_bitmap:531: comm docker: Cannot read block bitmap - block_group = 3080, block_bitmap = 4233
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-05-19T09:39:00.415175500Z][com.docker.diagnose.exe][I] ipc.NewClient: 17f27ba6-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-05-19T09:39:00.416730200Z][com.docker.diagnose.exe][I] (cdf9587d) 17f27ba6-diagnose C->S diagnosticsd GET /ping
[2023-05-19T09:39:00.418748700Z][com.docker.diagnose.exe][W] (cdf9587d) 17f27ba6-diagnose C<-S NoResponse GET /ping (2.0185ms): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:00.424773600Z][com.docker.diagnose.exe][I] ipc.NewClient: 2ef700a5-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-05-19T09:39:00.426212000Z][com.docker.diagnose.exe][I] (25721841) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-05-19T09:39:00.427412600Z][com.docker.diagnose.exe][W] (25721841) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /docker (1.2006ms): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:00.429277100Z][com.docker.diagnose.exe][I] (25721841-1) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:00.430980000Z][com.docker.diagnose.exe][W] (25721841-1) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (1.4031ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:01.438561000Z][com.docker.diagnose.exe][I] (25721841-2) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:01.449571100Z][com.docker.diagnose.exe][W] (25721841-2) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (10.4375ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:02.456438400Z][com.docker.diagnose.exe][I] (25721841-3) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:02.457825800Z][com.docker.diagnose.exe][W] (25721841-3) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (1.3874ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:03.461461400Z][com.docker.diagnose.exe][I] (25721841-4) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:03.461978900Z][com.docker.diagnose.exe][W] (25721841-4) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (517.5µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:04.474924900Z][com.docker.diagnose.exe][I] (25721841-5) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:04.477677500Z][com.docker.diagnose.exe][W] (25721841-5) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (3.2746ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:05.481581900Z][com.docker.diagnose.exe][I] (25721841-6) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:05.483343700Z][com.docker.diagnose.exe][W] (25721841-6) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (1.7618ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:06.483810500Z][com.docker.diagnose.exe][I] (25721841-7) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:06.485982900Z][com.docker.diagnose.exe][W] (25721841-7) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (2.1724ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-05-19T09:39:07.491454800Z][com.docker.diagnose.exe][I] (25721841-8) 2ef700a5-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-05-19T09:39:07.493481900Z][com.docker.diagnose.exe][W] (25721841-8) 2ef700a5-com.docker.diagnose C<-S NoResponse GET /ping (2.0271ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[FAIL] DD0038: is the connection to Docker working? HTTP GET https://login.docker.com: Get "https://login.docker.com": proxyconnect tcp: open \\.\pipe\dockerHTTPProxy: The system cannot find the file specified.
[FAIL] DD0014: are the backend processes running? 4 errors occurred:
        * com.docker.wsl-distro-proxy.exe is not running
        * com.docker.backend.exe is not running
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running


[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.
[2023-05-19T09:39:08.694193700Z][com.docker.diagnose.exe][I] ipc.NewClient: 700f1684-diagnose -> \\.\pipe\dockerBackendApiServer BackendAPI
```

**Comment by ctalledo** [comment] 2023-05-19 16:44
Hi @marvel-code, thanks for filing the report and sorry to hear about this issue.

What version of WSL2 does you machine have? (i.e., on a command prompt or Powershell, type `wsl --version`). Please post the output here. In some older version of WSL, the `wsl --version` command does not exist so will report an error. If so, please post that output here too.

Thanks!

**Comment by ctalledo** [comment] 2023-05-19 18:25
> What version of WSL2 does you machine have? (i.e., on a command prompt or Powershell, type wsl --version). 

No worries, I can see from the diagnostic logs that it's WSL2 version 1.2.5.0 which is fine.

I can also see the problem: Docker Desktop's WSL integration service (i.e., a small service that gets installed in your WSL distro(s) to allow you to run `docker run` in them) has failed to start:

```
[2023-05-19T09:21:41.718236800Z][com.docker.backend.exe][E] WSLIntegrationService: start failed: starting added distros: 1 error occurred:
        * waiting for WSL integration for Ubuntu-18.04: waiting for WSL distro integration to become ready
```

It's not clear why this happens though. 

While we root-cause, as a possible work-around please try the [steps here](https://github.com/docker/for-win/issues/13472#issuecomment-1538814083).

**Comment by ctalledo** [comment] 2023-05-19 18:26
Marking as duplicate of #13472.

**Closed by ctalledo** 2023-05-19 18:26 UTC
Labels: area/WSL2, version/4.19.0
