### ISSUE TITLE
Unable to connect to docker host from within a container

### ISSUE THREAD

**Issue by toddlucas** [docker/for-win#37] opened 2016-08-13 18:51 UTC
### Expected behavior

I would like to connect my dockerized app to ports on my local host, to use development databases, etc.
### Actual behavior

I am unable to make any connection to the docker host, either using the container's IP or the gateway IP (e.g. 172.17.0.1).
### Information

Docker version 1.12.0, build 8eab29e

I also attempted to create a dedicated bridge subnet using `docker network` so that I could assign an IP to the container, but I experienced the same results.

I tested using an HTTP server on my host (ASP.NET Core Kestrel server), on the wildcard IP 0.0.0.0 at port 5000, attempting connection with curl. I also tested with Postgres, updating pg_hba.conf with both the wildcard IP and the DockerNAT IP (10.0.75.1 in my case).

Any workarounds would be appreciated.
### Steps to reproduce the behavior
1. Create a containerized app (I tried several, but ended up doing most testing with a vanilla Ubuntu image).
2. Expose a service on the host at a specific port (like Postgres on port 5432), ensuring that the listener is listening on the correct IP.
3. Attempt to connect to the port using the container's IP or gateway IP.
4. Should see connection refused

Thanks!

**Comment by dgageot** [comment] 2016-09-01 09:21
Hi @toddlucas thank you for reporting this issue. Your use case is common to a lot of users and we are currently trying to find the best way to solve it. However I don't know if/when this will happen yet.

**Comment by ecsousa** [comment] 2016-09-11 09:53
Hi,

I've was able to connect doing a working arround with ngix by starting it with the following config

```
stream {
    server {
        listen 10.0.75.1:2375;
        proxy_pass 127.0.0.1:2375;
    }
}
```

Then, on container I just set `DOCKER_HOST` variable to `10.0.75.1`.

_NOTE: My Docker toolbox internal virtual switch subnet address is set to 10.0.75.0 (default), that's why I've used 10.0.75.1 IP address_

**Comment by vandammeb** [comment] 2016-09-22 08:54
Any update on this issue?
@ecsousa : I tried the workaround with the nginx proxy, but could not get that working (nginx would not bind to the specified ip). Is it possible to post your complete nginx config and your docker(-compose) file?

**Comment by ecsousa** [comment] 2016-09-22 13:04
@vandammeb Here's my nginx config file.

[nginx.conf.txt](https://github.com/docker/for-win/files/487283/nginx.conf.txt)

Note that, if you have changed the subnet address on network config, you will have to change the listen address on nginx config.

Also, remember to specify ```-e DOCKER_HOST=10.0.75.1``` (or your host IP) when you are creating your container, to make sure docker client will try to connect to correct server

I am using the following PowerShell command to find out the correct IP address when creating my container. It should return you the right IP address you should use to replace 10.0.75.1 (on both container creation command line, and nginx file):

    (Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex (Get-NetAdapter | ? {$_.Name -like '*(DockerNAT)*' }).InterfaceIndex).IPAddress

**Comment by vandammeb** [comment] 2016-10-11 08:37
@ecsousa Still no luck with the workaround you suggested. The same nginx bind issue persists:

nginx_1      | 2016/10/10 16:41:17 [emerg] 1#1: bind() to 10.0.75.1:9003 failed (99: Cannot assign requested address)

Would you mind having a look at my stackoverflow question?
My docker-compose file and network info are available there.

**Comment by vandammeb** [comment] 2016-10-11 08:42
@dgageot Any chance this issues has been addressed in the current beta? (i'm using the stable version)

**Comment by bradyemerson** [comment] 2017-01-31 22:13
This can be closed. It is definitely something related to our corporate Win 10 settings, but I have been unable to narrow it to a specific setting or conflicting software. It works fine on my non-corporate Win 10 machine.

I have worked around this by using Docker Toolbox + VirtualBox.

**Comment by jasonbivins** [comment] 2017-06-05 17:03
closing this one - it has been resolved in https://github.com/docker/pinata/issues/4026

**Comment by toddlucas** [comment] 2017-06-05 17:24
Hi @jasonbivins , I'm not able to see this repo or issue. Can you give us more details on when and where we might see this fix? Thanks!

**Comment by jasonbivins** [comment] 2017-06-05 18:04
Hi @toddlucas   Apologies, but that is actually our internal repo

The issue is listed as fixed in 17.06  but I don't see a specific item for it in the release notes.  I'll reopen this issue until I can confirm for sure that this was included.

**Comment by jasonbivins** [comment] 2017-06-07 13:46
Hi @toddlucas    I was able to confirm that this feature  has been added in the latest Edge channel build.
Two DNS entries were created - each for their respective OS
docker.for.mac.localhost
docker.for.win.localhost

I ran a few quick tests and was able to telnet to docker.for.win.localhost from inside a container.

Thanks!
Jason

**Comment by toddlucas** [comment] 2017-06-07 15:56
Hi @jasonbivins , thanks for following up. That's great news. Feel free to close.

**Closed** 2017-06-09 15:18 UTC
Labels: area/network, kind/enhancement, status/5-will-be-closed
