### ISSUE TITLE
Deleting a sub-set of a stack deletes entire stack

### ISSUE THREAD

**Issue by sechel** [docker/for-win#13005] opened 2022-10-09 10:34 UTC
### Actual behavior

* From the Container list select the checkbox for an entire stack to selected all container of that stack.
* Then, check off a few container from that stack.
* Press the delete button.
* All container of that stack will be deleted including those that were not selected (and running for that matter 😉)

### Expected behavior

Not deleting the (running) unselected containers.

**Comment by nicks** [comment] 2022-10-12 13:59
Thanks for reporting! I was not able to reproduce this problem. Here are the commands I ran:
- Checked out https://github.com/docker/awesome-compose/tree/master/flask-redis
- Ran `docker compose up`
- Navigated to the UI and deleted the 'flask' container
- Confirmed that the `redis` container was still running successfully

Clarification questions:
- What version of Docker Desktop you're using?
- Do the above steps also reproduce the issue for you? that will help confirm if it's something specific to your stack or if it's an environment problem.

**Comment by ebriney** [comment] 2022-11-10 16:14
Closing this issue because a fix has been released in Docker Desktop 4.14.0. See release notes for more details.

**Closed by ebriney** 2022-11-10 16:14 UTC
Labels: status/1-acknowledged
