### ISSUE TITLE
How can I move MobyLinux Hyper-V virtual disk?

### ISSUE THREAD

**Issue by SaschaNaz** [docker/for-win#261] opened 2016-11-29 04:13 UTC
## Expected behavior

I should be able to move the disk anywhere

### Actual behavior

Direct change on Hyper-V VM settings is ignored and overwritten by Docker. (The same happens for CPU/Memory settings change but there at least are UI for them in Docker executable.)

My use: I want to move my virtual disk to SSD from traditional HDD to fix my performance issue.

### Information

  - Windows 10

### Steps to reproduce the behavior

1. Open Hyper-V manager and move MobyLinuxVM to anywhere you want
2. Check your virtual disk is correctly moved
3. Restart Docker
3. Check your virtual disk path is now overwritten and restored by Docker

**Comment by rneugeba** [comment] 2016-11-29 08:57
Thanks for the report. I'm closing this as a duplicate of #163 and see if I can post a workaround there later today

**Closed by rneugeba** 2016-11-29 08:57 UTC
