### ISSUE TITLE
WSL distro stopped while waiting for Lifecycle server.

### ISSUE THREAD

**Issue by Ma3yTa** [docker/for-win#7844] opened 2020-07-27 16:55 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B86BE646-CD2B-41B4-805C-18BA99974958/20200727164203

### Information

  - Windows Version: 2004 (OS Build  20175.1000)
  - Docker Desktop Version: 2.3.3.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: WSL2

**Comment by stephen-turner** [comment] 2020-07-27 16:59
Docker isn't working well with this Windows build. We've reported it to Microsoft.

**Comment by stephen-turner** [comment] 2020-07-28 07:54
Probably a dupe of #7808.

**Closed by stephen-turner** 2020-07-28 07:54 UTC
Labels: version/2004

**Comment by metcalfc** [comment] 2020-07-31 21:44
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.
