### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ManoMarks** [docker/for-win#1316] opened 2017-11-13 02:45 UTC
### Expected behavior
When I start my machine, I expect Docker to start-up.

### Actual behavior
I got a crash screen. This happens every time I reboot this machine, even under multiple updates to Docker. Once it has crashed, it won't fully stop, I have to force quit. Then I restart and it works fine.

### Information
57B12A34-05FD-45BA-9BD9-97AB99C04DE7/2017-11-12_18-38-39
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by philippfreyer** [comment] 2017-11-15 08:28
Similar behavior for me. The docker service should start on system startup. Instead, it crashes with always the same error message and I have to go to settings -> restart to let docker start up successfully:

`Docker command did not complete within the allowed timeout. Output: 
   bei Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:Zeile 152.
   bei Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:Zeile 49.
   bei Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:Zeile 197.
   bei Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:Zeile 168.
   bei Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:Zeile 65.
   bei Docker.Backend.BackendServer.<Run>b__6_10(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:Zeile 52.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.`

I use Docker with Hyper-V. 

Diagnostic ID:
C423A5F3-51A5-490E-93B2-1A8039EDEABB/2017-11-15_08-06-49

After restarting docker using the restart option in the settings menu, it starts up fine. However, it recreates the docker network. This usually means that I have to go to my firewall (Kaspersky) and mark it as a trusted network again.

**Comment by philippfreyer** [comment] 2017-11-17 08:23
Just in case multiple diagnostics help, here is the next one of today:
C423A5F3-51A5-490E-93B2-1A8039EDEABB/2017-11-17_09-22-34

**Comment by ManoMarks** [comment] 2017-11-18 23:25
Interestingly, Fall Creator Update just ran and it's working now

**Comment by philippfreyer** [comment] 2017-11-28 07:10
I ran the Fall Creators Update yesterday and for me, the startup process still does not work properly.
Collecting the Diagnostic IDs after the Fall Creators update here:
C423A5F3-51A5-490E-93B2-1A8039EDEABB/2017-11-28_08-07-00

**Comment by philippfreyer** [comment] 2017-12-13 07:07
I updated to Version 17.09.1-ce-win42 (14687) yesterday, hoping that this issue has been fixed. I am sad to report that this is not the case. Diagnostic IDs below here are uploaded using the mentioned Docker for Windows version:
C423A5F3-51A5-490E-93B2-1A8039EDEABB/2017-12-13_08-04-55

**Comment by philippfreyer** [comment] 2018-01-16 07:06
I updated to Version 17.12.0-ce-win47 (15139) a few days ago. Since then, Docker for Windows is starting up reliably each time and I did not experience any more crashes. For me, the issue is solved.

**Comment by rn** [comment] 2018-03-20 11:25
Since this seems fixed by a magic Fall Creators Update for @ManoMarks and for a version update for @philippfreyer I'm closing this issue. @philippfreyer I may be that you had an issue with `fast boot` as described in https://github.com/docker/for-win/issues/1741 so it might be worth keeping an eye out for that

**Closed by rn** 2018-03-20 11:25 UTC
