### ISSUE TITLE
Docker Engine failed to start after upgraded Docker Desktop to 3.6.0

### ISSUE THREAD

**Issue by Nutharat** [docker/for-win#11912] opened 2021-08-16 23:22 UTC
I have upgraded Docker Desktop from 3.5.2 to 3.6.0 and then experiencing issue that Docker Engine failed to start when I start or restart machine. Tried uninstall and reinstall the Docker Desktop but no difference.

### Environment:
- Windows 10 Pro (21H1) OS build 19043.1165.
- Docker Desktop 3.6.0.
- Docker settings "Start Docker Desktop when you log in" is selected.
- Docker Engine configuration "experimental" is true.

### Steps to Reproduce Behavior:
1. Install or upgrade Docker Desktop to 3.6.0.
2. Restart machine.

### Actual Behavior:
Docker Engine failed to start.

```
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

![DockerError-1](https://user-images.githubusercontent.com/69130490/129639742-62840c2c-3717-421e-81a0-e466691a98c5.png)
![DockerError-2](https://user-images.githubusercontent.com/69130490/129639744-5fbc22ca-4d90-44d0-8bac-6bfa8bb7b3d0.png)
![DockerError-3](https://user-images.githubusercontent.com/69130490/129639745-1bd9d48c-a85b-4477-901f-b1f3d8f96f6b.png)

### Expected Behavior:
Docker Engine is running.

### Workaround:
Error can be found in event viewer that there was an access denied on file "C:\ProgramData\Docker\panic.log". Delete that file and Docker Engine can start.
![DockerError-EventViewer](https://user-images.githubusercontent.com/69130490/129640899-888b2461-e127-4634-a118-eb3e93a7aebc.png)

Note that once Docker Engine is running I can restart without the issue. But if I restart machine I get the error again.

**Comment by StefanScherer** [comment] 2021-08-17 08:07
Thanks @Nutharat for the excellent analysis. Indeed we see sporadic problems with the file `C:\ProgramData\Docker\panic.log` that has to be removed or renamed manually when starting in Windows container mode.

I'll close this issue as it's a duplicate of #11899.

**Closed by StefanScherer** 2021-08-17 08:07 UTC
