### ISSUE TITLE
All containers and images gone  after reboot / update.

### ISSUE THREAD

**Issue by kjlhgfds** [docker/for-win#4344] opened 2019-07-31 18:23 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 35294F2F-A6E5-4068-B776-5912C6357EC9/20190731173127

### Expected behavior
I install an update / reboot and everything run as usual.

### Actual behavior
I installed an update an rebooted and when I run `docker container ls` or `docker images ls` the list is empty.

### Information
  - Is it reproducible ?
At least for me, I just need to install Docker, run a container, and after a restart of Docker, I can't see the container anymore.

  - Is the problem new ?
Yes, and that's the first time I update.

  - Did the problem appear with an update?
Yes, and / or with a reboot.

  - Windows Version: Windows 10 Pro Version 10.0.18362 Build 18362
  - Docker Desktop Version: 2.1.0.0 (36874) stable

I'm pretty new to docker so I don't really know what informations you could need but the ones I gave.
If you need anything more, tell me.
Thanks

**Comment by kjlhgfds** [comment] 2019-07-31 20:27
Actually, I found something.
After a fresh start of windows and docker, everything is working great.
But if I restart (just) docker, the only container that I can start is lets_encrypt. All the others just start and stop immediatly.

**Comment by trung674** [comment] 2019-08-01 09:31
Just updated to version 2.1.0.0, I experienced the same issue

**Comment by kjlhgfds** [comment] 2019-08-01 09:56
This is the version and build I have :
> Docker Desktop Version: 2.1.0.0 (36874) stable

And this is after doing the update to this version that I had the problem.

**Comment by kjlhgfds** [comment] 2019-08-17 09:54
The problem is still here with version 2.1.0.1 (37199).

**Comment by jlack1987** [comment] 2019-11-18 19:15
/remove-lifecycle stale

Having the same problem here `Docker version 19.03.1, build 74b1e89e8a`

**Comment by egorpavlikhin** [comment] 2019-11-22 06:06
Same here, all images, containers and configuration just gone. The fact that this issue exists and hasn't been fixed in 3 months is very troubling.

**Comment by pikkelnut** [comment] 2019-12-22 20:55
I've experience the same issue losing all of my images/containers after upgrading to Stable 2.1.0.5 - Stable.

**Comment by mipe** [comment] 2020-01-09 12:49
I just experienced the same problem with 2.1.0.5 stable.

Had 2 containers running (disk image size 12 GB) and changed Memory from 2048 to 4096 MB and clicked Apply.

Docker restarted immediately and all images were gone (disk image size 60 MB)...

This only happened once so far and I could not reproduce it again.

**Comment by pravynandas** [comment] 2020-01-14 02:16
Unfortunately hit the docker restart command now all the images/containers/volumes gone :(. This is very bad experience indeed.

Docker version 19.03.5, build 633a0ea838

**Comment by SchatzmanGPS** [comment] 2020-01-28 22:44
The same thing here powered down VM to snapshot and rebooted to no docker containers. Four weeks into a Jenkins project and it is all gone.

**Comment by pravynandas** [comment] 2020-01-29 04:44
Can you try restarting the docker service and see? In my case, surprisingly all the containers and volumes are intact after a successful service restart. Prior to that docker commands were running with blank results.

`service docker stop`
`service docker start`

**Comment by SchatzmanGPS** [comment] 2020-01-29 16:22
> Can you try restarting the docker service and see? In my case, surprisingly all the containers and volumes are intact after a successful service restart. Prior to that docker commands were running with blank results.
> 
> `service docker stop`
> `service docker start`

I tried that and the containers didn't start right away. I recognized I had set the flag -rm in my container command. I discovered the folder which holds all of the containers, but it only provides their serialized names. I then ran the command I used to create the containers (removing the -rm flag) and my Jenkins server came back up. It was restored to its previous conditions with all of my user data and projects. This restored the containers back to operation.

**Comment by Noahnut** [comment] 2020-02-12 13:11
I also got the same problem, where I update docker desktop for mac from 2.2.0.0 to newer version the container all gone ...

**Comment by alkampfergit** [comment] 2020-02-23 09:45
Same here, I have a physical machine with Windows 2019, I had some test images, usually it is powered down (is a test server).
Today I've started the server, no images, I needed to doker system clear -a to remove everyting.

The clear command actually found and removed images, but it is annoying

In that instance I've enabled experimental feature to run linux and windows container in the same machine.

**Comment by mat007** [comment] 2020-02-24 16:11
Closing in favor of #5278

**Closed by mat007** 2020-02-24 16:11 UTC
Labels: status/0-triage, version/2.1.0.0

**Comment by maildavc** [comment] 2020-05-10 20:07
your containers did not start automatically.

u need "sudo docker ps -a" to list them and then start all of them manually.

**Comment by query1280** [comment] 2020-05-19 13:35
I have same experience too. 
I'm using ubuntu 20.04 LTS 
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false


I have no idea why this happened. All I've done were erased..

**Comment by heinemannmarkus** [comment] 2020-06-03 06:55
For me restarting the docker service solved the problem. I run in the same issue after updating docker on windows.

**Comment by JIBSIL** [comment] 2020-06-04 18:24
Restart the docker service, worked for me!

**Comment by bkstha** [comment] 2020-06-17 13:39
I have the same problem but restart docker works for me. 
The strange thing is that when I use the hard drive the problem doesn't occur, but when I use SSD I have to restart docker after every reboot of my server.
What may be the cause? Any solution for this?
Components:
raspberrypi 4
rasbian os 32bit
openmediavault

**Comment by flufy3d** [comment] 2020-07-05 12:01
I have the same problem 
Docker version 19.03.8, build afacb8b7f0
Linux kenshin 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

the current workaround is 
sudo systemctl restart docker

**Comment by zetxx** [comment] 2020-07-16 07:00
same here

**Comment by lezli01** [comment] 2020-07-24 04:45
Problem occurs for me as well.
I have a fresh Ubuntu Server 20.04 LTS, installed latest docker.ce package and everything stated on official docker installation guide.

After a reboot the lists of `docker image ls` or `docker container ls` are empty but my containers that are configured to autostart are running. The only solution for me currently is to restart the service using `sudo service docker restart` but that restarts the containers and that is not really a good approach for example for my jenkins server.

**Comment by lezli01** [comment] 2020-07-24 05:56
I finally solved this issue, in my case it was a snap docker package which was installed by ubuntu server installer. I remember ticking the checkbox when it asked me do I want docker to be installed, it seems it installs a snap package and that version has issues. After removing snap `sudo snap remove docker` version everything worked fine.

**Comment by p5a0u9l** [comment] 2020-07-27 21:45
Same exact issue as @lezli01. Can confirm that `sudo snap remove docker` + reboot and re-issuing `docker-compose up -d` resolved the issue such that rebooting does _not_ require `sudo systemctl restart docker`
