### ISSUE TITLE
Have problem to use docker pull mcr.microsoft.com/dotnet/core/samples:aspnetapp

### ISSUE THREAD

**Issue by agrossma2** [docker/for-win#6247] opened 2020-04-06 13:50 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2020-04-06 13:59
I'm closing this issue because there is no information that would allow us to diagnose it. However, from the title, it sounds like the problem is more likely in the Windows engine, so it should probably be filed in the moby/moby project not in docker/for-win.

**Closed by stephen-turner** 2020-04-06 13:59 UTC

**Comment by agrossma2** [comment] 2020-04-06 14:01
Hello together
I use windows 10 enterprise Version1803 OS build 17134.1304
Docker Windows 2.2.0.5 (43884) stable

**Comment by agrossma2** [comment] 2020-04-06 14:01
I run it directly on the notebook!
