### ISSUE TITLE
Docker takes forever to startup, with errors on reading /etc/resolv.conf

### ISSUE THREAD

**Issue by bigeyex** [docker/for-win#13] opened 2016-07-31 05:13 UTC
### Expected behavior
Docker for windows startup normally

### Actual behavior
the try icon keeps saying "Docker is starting...".

Errors in the log includes 
[12:57:34.985][DataKit        ][Info   ] +1993786us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[12:57:47.562][VpnKit         ][Error  ] com.docker.slirp.exe: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENOENT, "uv_fs_open", "/etc/resolv.conf")

and it seems taking too long in this step:
[12:57:51.889][ApiProxy       ][Info   ] Dial Hyper-V socket a35d2eb3-5dbe-4c92-90e5-91d612a777eb:23a432c2-537a-4291-bcb5-d62504644739

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 
F9A9FED6-041F-40EF-A2AD-5D2EA52437A8/2016-07-31_13-01-09

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro 10.0.10586
Docker version : 1.12.0-beta21 build 5671 
(also tried the non-beta released version, the same phenomenon)

### Steps to reproduce the behavior

  1. finish installation;
  2. start docker

**Comment by btbxbob** [comment] 2016-08-01 03:39
Same problem here，Diagnostic ID:
9910108D-50EC-40E2-AA03-91C99D5C15AB/2016-08-01_11-38-26

**Comment by dgageot** [comment] 2016-08-01 06:11
@bigeyex @btbxbob Thanks for the report!. The `etc/resolv.conf` error message can be safely ignored. The rest is a real issue!

**Comment by rneugeba** [comment] 2016-08-01 11:09
I had a look at the two diagnostics and the cause is entirely different.

@bigeyex I noticed an un-natural long delay (22s) early in the application startup. I've filed an internal issue to investigate. Unfortunately, the diagnosis uploaded then is truncated. Did you maybe hit the "Upload diagnostics" link too early? Could you retry and wait for longer or check if if the whale icon in the try becomes red?

@btbxbob In your case there was an issue with the VM starting. It also seems that you have some portions of VMWare running your system. I'm not sure how well that will interact with Hyper-V

**Comment by bigeyex** [comment] 2016-08-01 13:42
Hi, I re-installed docker and recorded another diagnostic:
B8135B95-E027-4F0C-8271-65F697ECDC90/2016-08-01_21-39-07

btw, here's the log file:
[log-2016-08-01_21-34-53.txt](https://github.com/docker/for-win/files/393901/log-2016-08-01_21-34-53.txt)

Hope these will help.

**Comment by rneugeba** [comment] 2016-08-01 15:24
@bigeyex it looks like on your system it fails to connect to the docker daemon. Could you try a factory reset via `Settings->Reset->Reset to factory defaults...`

**Comment by sujunxuan** [comment] 2016-08-08 06:34
Some problem.
Diagnostic ID:
503C3EEF-783A-40C8-9D81-D6EE4F1F257E/2016-08-08_14-32-13
[log-2016-08-08_13-24-49.txt](https://github.com/docker/for-win/files/406194/log-2016-08-08_13-24-49.txt)

**Comment by rneugeba** [comment] 2016-08-17 13:04
For those experiencing long delays during start, could you check out Beta23 from here: https://download.docker.com/win/beta/InstallDocker.msi

We made some changes to the Mixpanel integration and hopefully it shouldn't delay startup anymore.

We'd be interested to hear if Beta23 fixes the issue.

Thanks
Rolf

**Comment by rneugeba** [comment] 2016-09-01 22:18
No update/activity in 15 days. Closing for now. If you still have the same issue with Beta23/24 please re-open

**Closed by rneugeba** 2016-09-01 22:18 UTC
Labels: kind/bug, status/more-info-needed
