### ISSUE TITLE
"Function not implemented" during create long path on mounted volume

### ISSUE THREAD

**Issue by swojdyga** [docker/for-win#6337] opened 2020-04-15 15:34 UTC
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Creating a long path (e.g. nested directories) on mounted volume works without errors.

### Actual behavior
Creating a long path throws error "Function not implemented".

### Information
Steps to receive error:
1. Run container: `docker run -v  ${pwd}:/app -it alpine`.
2. Go inside container: `docker exec -it <container_id> /bin/sh`
3. Try create nested directories: `mkdir /app/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/example-directory/ -p`

Everything works great on Docker for Windows 2.1.x. Beginning from 2.2.x I have these issue.

Windows Version: 10 (1903)
Docker Desktop Version: 2.2.0.5

**Comment by mat007** [comment] 2020-04-15 16:09
Thanks for the report.
I Believe it’s either a duplicate of #5955 or #5572, what do you think?

**Comment by swojdyga** [comment] 2020-04-15 18:14
Hmmm...

In [https://github.com/docker/for-win/issues/5955](#5955) temporary soluction is restart Docker - in my case it doesn't help.

Issue [https://github.com/docker/for-win/issues/5572](#5572) probably describe the same case, but... is closed :/

I think we'll know the truth when all these problems are fixed ;)

**Comment by djs55** [comment] 2020-04-16 07:26
@swojdyga thanks for the report and the reproduction steps. I managed to reproduce a bug and have a candidate fix here: https://download-stage.docker.com/win/edge/44390/Docker%20Desktop%20Installer.exe . If you have time to test, could you let me know if it's any better? If not, could you upload a fresh set of diagnostics? Thanks!

**Comment by swojdyga** [comment] 2020-04-16 18:27
Looks like it works :)

I have no idea what is your conception is to close the issue - should it be close now or when version with this fix will be published?

**Comment by ashersilver** [comment] 2020-04-28 15:31
Restarting worked for me ... its can be very confusing I was editing in with two editors, VS Code on Windows and Eclipse on Docker Image running Linux.  Copying code between Windows and Docker Linux seemed to be what "broke" Docker session.  Was thinking it could be CR/LF vs LF issues not getting translated in the clipboard, or by the target editor, but I cant be sure...

**Comment by stephen-turner** [comment] 2020-05-11 16:18
Fixed in 2.3, closing this ticket.

**Closed by stephen-turner** 2020-05-11 16:18 UTC
Labels: version/10
