### ISSUE TITLE
Windows does not support host IP addresses in NAT settings.

### ISSUE THREAD

**Issue by davidathompson** [docker/for-win#10552] opened 2021-03-05 02:54 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Dynamic host port assignment on windows stopped working with the latest docker for desktop.

It gives the following message: failed to create endpoint xxxx on network nat: Windows does not support host IP addresses in NAT settings.

### Expected behavior
When using the -p 80 flag for example, it is expected the host to find an available port to publish to. This is the behavior on linux containers and it was working fine on the prior version. 

### Information

Docker Desktop Version: 3.2.0 (61504)

Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:28:25 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:40:06 2021
  OS/Arch:          windows/amd64
  Experimental:     false

### Steps to reproduce the behavior

Run (from windows containers mode)
```
docker run -it --rm -p 80 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp
```

I get:
docker: Error response from daemon: failed to create endpoint aspnetcore_sample on network nat: Windows does not support host IP addresses in NAT settings.

Specifically assigning ports does still work:
```
docker run -it --rm -p 8854:80 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp
```

Also strangely this syntax does work and will pick a random available port. 
```
docker run -it --rm -P --expose 80 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp
```

Why don't I just use this? Because my actual core problem is when using docker-compose, it doesn't have a -publish-all. I have a business need for host routable unique ports at run time. Hopefully there is a fix? 

Thank you!

**Comment by stephen-turner** [comment] 2021-03-05 13:53
Thanks for the report, @davidathompson, but could I ask you to open it at https://github.com/moby/moby instead? This error message is from the daemon, which is only an upstream for us. Sorry, I would move it myself, but it's not possible as that repository is not in the docker org.

I do notice that moby/moby#26980 seems like a feature request for the same thing, but that ticket is over four years old, and you say this problem is new?

**Comment by davidathompson** [comment] 2021-03-05 14:37
Yes it just started after the Docker Desktop Version: 3.2.0 (61504) upgrade

**Comment by mskorb** [comment] 2021-03-12 12:05
@stephen-turner  in my case it stoped working after update from 3.1.0 to 3.2.1? You have mention that this issue could be related to[ moby/moby#26980](https://github.com/moby/moby/issues/26980)  from 2016, but on 3.1.0 it works properly, so I guess it is problably not the reason of this issue.

**Comment by stephen-turner** [comment] 2021-03-12 17:06
Yes, I'm going to reopen this ticket as we've had two more reports of it. Although the error message comes from the daemon, I think Desktop has broken the command line parsing somehow.

**Comment by Denis-Tek** [comment] 2021-03-14 20:43
I have the same problem after update from 3.1.0 to 3.2.1

**Comment by ukdiverboi** [comment] 2021-03-15 16:14
I also have the same problem after update from 3.1.0 to 3.2.1 - I have rolled back for now, but the warnings to upgrade are quite annoying! 

Any timeline for when a fix might be put in place??

**Comment by stephen-turner** [comment] 2021-03-15 17:28
Sorry, no timeline yet as we haven't identified the root cause.

**Comment by jdenny-ce** [comment] 2021-03-16 18:48
I'm having the same problem when I try to run a docker compose via Visual Studio 2019. I have about 10 repos that are all doing this and I've spent the day trying to figure out what's going on. Error: Cannot start service xxxx: failed to create endpoint xxxx on network dockercomposexxxxxxxx_default: Windows does not support host IP addresses in NAT settings. Everything worked fine before I decided to download/install 3.2.

The only work-around is uninstall 3.2, manually install 3.1, but I can't stop docker from updating so every time I restart docker or restart my machine it automatically updates. Is there a way to prevent docker from auto-updating? I can't find any settings to manage this.

**Comment by ukdiverboi** [comment] 2021-03-16 20:19
To stop it updating, just click no when it asks if you want to update, then click to start docker desktop again and this time it does not ask you. It will ask everytime you restart your computer though, which is annoying but just follow the same steps above. Hopefully they will find the root cause and get a fix out soon.

**Comment by mat007** [comment] 2021-03-23 10:05
We have now identified the root cause and a fix will be available in the next release of Docker Desktop.

**Comment by stephen-turner** [comment] 2021-04-09 07:54
This is now fixed in Docker Desktop 3.3.0.

**Closed by stephen-turner** 2021-04-09 07:54 UTC
Labels: version/3.2.0

**Comment by felithium** [comment] 2021-04-26 12:59
I have Docker Desktop 3.3.1 and am still having this issue.

**Comment by GrimHacker** [comment] 2021-05-19 11:01
Encountered this issue in 3.3.3 (64133) (engine 20.10.6) when running with Windows containers.
Worked around by replacing `- "127.0.0.1:8080:80"` in my docker-compose file with `-"8080:80"`
