### ISSUE TITLE
Hardware assisted Virtualization and execution...in the BIOS

### ISSUE THREAD

**Issue by bsguillot1** [docker/for-win#10972] opened 2021-04-20 03:53 UTC
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization

Diagnostics ID   150A29B8-E772-452A-B149-892142A0F718/20210420033958

************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without a clear title, description, and diagnostics ID cannot be debugged,
and will be closed. See https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback
for how to generate a diagnostics ID either from inside the app or from the command
line.
************************************************************************************

-->

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-04-20 07:54
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Closed by stephen-turner** 2021-04-20 07:54 UTC

**Comment by bsguillot1** [comment] 2021-04-20 13:16
I'm nor sure what you mean.  I downloaded the dockers from the Pi wallet node app.  I pasted the in screen message driven and then pasted the diagnostic ID given to me after the dockers ran its own diagnostic. The dockers had a link to follow to report the diagnostic ID....and it lead me to you. What else do you need?Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Stephen Turner ***@***.***> Date: 4/20/21  2:54 AM  (GMT-06:00) To: docker/for-win ***@***.***> Cc: bsguillot1 ***@***.***>, Author ***@***.***> Subject: Re: [docker/for-win] Hardware assisted Virtualization and execution...in the BIOS (#10972) 
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by stephen-turner** [comment] 2021-04-20 13:35
You could fill in these sections from the template:

Actual behavior
Expected behavior
Information
Steps to reproduce the behavior
