### ISSUE TITLE
Docker failed to initalize Windows 10

### ISSUE THREAD

**Issue by Wector** [docker/for-win#8911] opened 2020-10-08 14:03 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 20201008140600

### Expected behavior

Docker should just start.

### Actual behavior

I got this error:

System.NullReferenceException:
The object reference is not set to any object instance.
   in Docker.Core.Cli.CliOptionsLoader.Get () in C: \ workspaces \ edge-2.4.1.x \ src \ github.com \ docker \ pinata \ win \ src \ Docker.Core \ cli \ CliOptionsLoader.cs, line 33
   in Docker.Program.Run (IReadOnlyCollection`1 args) in C: \ workspaces \ edge-2.4.1.x \ src \ github.com \ docker \ pinata \ win \ src \ Docker.Desktop \ Program. cs, line: 340

### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.4.10 -  2.4.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or a mac VM: No

**Comment by stephen-turner** [comment] 2020-10-08 14:17
Thanks for the report. Closing as a dupe of #8757 and #8823.

**Closed by stephen-turner** 2020-10-08 14:17 UTC
