### ISSUE TITLE
No external internet when connected to Cisco AnyConnect VPN

### ISSUE THREAD

**Issue by DannyMeister** [docker/for-win#7179] opened 2020-06-11 07:25 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 188E647A-A209-4CDC-848D-D559D3BBDE97/20200611062413

### Expected behavior

I would expect internet connection from within my containers to work the same whether host is connected to the VPN or not.

### Actual behavior

Though internet connection works fine when host is not connected to the VPN, as soon as Cisco AnyConnect VPN client connects to my corporate network, internet connectivity within windows containers dies.

### Information
  - Windows Version: Windows 10 Enterprise version 1909 (colleague has reproduced on 1809)
  - Docker Desktop Version: 2.3.0.3 (most recent stable release)
  - Docker is running directly on Dell Precision 3540 in Hyper-V mode.

This happens only on Windows containers.  Switching to Linux containers I have internet access when connected to the VPN.

I do not know for sure whether this is a new issue (I have struggled with it for 3 months now) as due to current events I am now working from home and previously did not have to use the corporate VPN.  One colleague who is also experiencing this issue claims it was not a problem in an older version of Docker (not sure the version, but it was prior to the removal of DockerNAT).  I see similar unresolved reports from before that time.  Of course there may have also been recent changes to our corporate VPN client, but I wouldn't have a way of knowing that.

The VPN client seems configured aggressively, with no unsecured routes.  
![image](https://user-images.githubusercontent.com/7937829/84356000-2e11a900-ab89-11ea-9de4-1329a1dead54.png)

We also seem to have DNS issues as it doesn't pick up on the DNS used by the VPN either, but to not obscure this issue report, I can work around by manually setting a public DNS via daemon config or command line.

I have changed InterfaceMetric priorities, disabled unused network adapters, removed and reinstalled Hyper-V and Docker multiple times, and many other commonly suggested workarounds to no avail.  

Creating a new external hyperv network tied to my WiFi connection almost works.  Technically I seem to get an internet connection in the container, however internet speeds on the host and client drop to 0.1mbps and enough operations time out that it is useless.

```
PS C:\> docker run --dns 8.8.8.8 mcr.microsoft.com/windows/servercore:ltsc2019 ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : 2066234e4ee2
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : redacted

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : redacted
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter
   Physical Address. . . . . . . . . : 00-15-5D-E0-3B-93
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::b909:e074:933b:b28d%4(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.251.168(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.29.240.1
   DHCPv6 IAID . . . . . . . . . . . : 67114333
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-73-8F-43-00-15-5D-E0-3B-93
   DNS Servers . . . . . . . . . . . : 172.29.240.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

On host OS
```
PS C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : BOL-3PYR3Z2
   Primary Dns Suffix  . . . . . . . : redacted
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : redacted

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : redacted
   Description . . . . . . . . . . . : Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
   Physical Address. . . . . . . . . : redacted
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::9072:2912:9b50:6645%20(Preferred)
   Link-local IPv6 Address . . . . . : fe80::9c67:6951:c21a:9cfd%20(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.250.44.10(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : ::
                                       10.250.0.1
   DHCPv6 IAID . . . . . . . . . . . : 184550810
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-5F-18-B6-98-E7-43-A6-0A-4B
   DNS Servers . . . . . . . . . . . : 10.80.58.101
                                       10.80.58.102
   NetBIOS over Tcpip. . . . . . . . : Enabled

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wireless-AC 9560 160MHz
   Physical Address. . . . . . . . . : redacted
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.1.29(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Thursday, June 11, 2020 12:33:48 AM
   Lease Expires . . . . . . . . . . : Friday, June 12, 2020 12:33:47 AM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DNS Servers . . . . . . . . . . . : 192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter Ethernet 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : redacted
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (6) I219-LM
   Physical Address. . . . . . . . . : redacted
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 9:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : 60-F2-62-03-72-09
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 10:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : 62-F2-62-03-72-08
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : 60-F2-62-03-72-0C
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : 00-15-5D-39-70-C3
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::3daf:d10d:2fe0:ff68%24(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.29.97(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 402658653
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-5F-18-B6-98-E7-43-A6-0A-4B
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-E0-3E-4D
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::529:377e:2411:512f%31(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.240.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 520099165
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-26-5F-18-B6-98-E7-43-A6-0A-4B
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
```
PS C:\> Get-NetIPInterface -AddressFamily IPv4 | Sort-Object -Property InterfaceMetric -Descending

ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
24      vEthernet (Default Switch)      IPv4                  1500            5000 Disabled Connected       ActiveStore
31      vEthernet (nat)                 IPv4                  1500            5000 Disabled Connected       ActiveStore
1       Loopback Pseudo-Interface 1     IPv4            4294967295              75 Disabled Connected       ActiveStore
13      Bluetooth Network Connection    IPv4                  1500              65 Enabled  Disconnected    ActiveStore
6       Local Area Connection* 9        IPv4                  1500              25 Enabled  Disconnected    ActiveStore
2       Local Area Connection* 10       IPv4                  1500              25 Enabled  Disconnected    ActiveStore
22      Ethernet 2                      IPv4                  1500               5 Enabled  Disconnected    ActiveStore
15      Wi-Fi                           IPv4                  1500               3 Enabled  Connected       ActiveStore
20      Ethernet                        IPv4                  1390               1 Disabled Connected       ActiveStore
```
```
PS C:\> Get-NetRoute -AddressFamily IPv4

ifIndex DestinationPrefix                              NextHop                                  RouteMetric ifMetric PolicyStore
------- -----------------                              -------                                  ----------- -------- -----------
24      255.255.255.255/32                             0.0.0.0                                          256 5000     ActiveStore
20      255.255.255.255/32                             0.0.0.0                                          256 1        ActiveStore
2       255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
31      255.255.255.255/32                             0.0.0.0                                          256 5000     ActiveStore
6       255.255.255.255/32                             0.0.0.0                                          256 25       ActiveStore
15      255.255.255.255/32                             0.0.0.0                                          256 3        ActiveStore
13      255.255.255.255/32                             0.0.0.0                                          256 65       ActiveStore
22      255.255.255.255/32                             0.0.0.0                                          256 5        ActiveStore
1       255.255.255.255/32                             0.0.0.0                                          256 75       ActiveStore
24      224.0.0.0/4                                    0.0.0.0                                          256 5000     ActiveStore
20      224.0.0.0/4                                    0.0.0.0                                          256 1        ActiveStore
2       224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
31      224.0.0.0/4                                    0.0.0.0                                          256 5000     ActiveStore
6       224.0.0.0/4                                    0.0.0.0                                          256 25       ActiveStore
15      224.0.0.0/4                                    0.0.0.0                                          256 3        ActiveStore
13      224.0.0.0/4                                    0.0.0.0                                          256 65       ActiveStore
22      224.0.0.0/4                                    0.0.0.0                                          256 5        ActiveStore
1       224.0.0.0/4                                    0.0.0.0                                          256 75       ActiveStore
24      192.168.29.97/32                               0.0.0.0                                          256 5000     ActiveStore
15      192.168.1.255/32                               0.0.0.0                                          256 3        ActiveStore
15      192.168.1.29/32                                0.0.0.0                                          256 3        ActiveStore
15      192.168.1.1/32                                 0.0.0.0                                            1 3        ActiveStore
20      192.168.1.0/24                                 10.250.0.1                                         1 1        ActiveStore
15      192.168.1.0/24                                 0.0.0.0                                          256 3        ActiveStore
31      172.29.255.255/32                              0.0.0.0                                          256 5000     ActiveStore
31      172.29.240.1/32                                0.0.0.0                                          256 5000     ActiveStore
20      172.29.240.0/20                                10.250.0.1                                         1 1        ActiveStore
31      172.29.240.0/20                                0.0.0.0                                          256 5000     ActiveStore
1       127.255.255.255/32                             0.0.0.0                                          256 75       ActiveStore
1       127.0.0.1/32                                   0.0.0.0                                          256 75       ActiveStore
1       127.0.0.0/8                                    0.0.0.0                                          256 75       ActiveStore
15      64.22.251.206/32                               192.168.1.1                                        1 3        ActiveStore
20      10.250.255.255/32                              0.0.0.0                                          256 1        ActiveStore
20      10.250.44.10/32                                0.0.0.0                                          256 1        ActiveStore
20      10.250.0.0/16                                  0.0.0.0                                          256 1        ActiveStore
20      0.0.0.0/0                                      10.250.0.1                                         1 1        ActiveStore
15      0.0.0.0/0                                      192.168.1.1                                        3 3        ActiveStore
```

### Steps to reproduce the behavior

```
PS C:\> docker run --dns 8.8.8.8 mcr.microsoft.com/windows/servercore:ltsc2019 ping google.com
Ping request could not find host google.com. Please check the name and try again.
```

**Comment by stephen-turner** [comment] 2020-06-11 08:35
Dupe of #2050. Unfortunately out of our control.

**Closed by stephen-turner** 2020-06-11 08:35 UTC
Labels: version/2.3.0.3
