### ISSUE TITLE
Unable to view Logs - Error: WebGL2 not supported null

### ISSUE THREAD

**Issue by cacharrin** [docker/for-win#12825] opened 2022-07-07 20:20 UTC
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop runs correctly, I can create images and run containers, but when I try to click a container to view the logs, there is a big message saying:

Display Error

We have already reported this to our error tracker.

Error: WebGL2 not supported null

(Report issue on GitHub) <-- Button

NOTE: I can also inspect the container and view his stats, just the "logs" tab isn't working.

### Expected behavior

Docker desktop should display logs correctly.

### Information

  - Windows Version: Windows 10 Pro 21H2
  - Docker Desktop Version: 4.10.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[2022-07-07T12:30:32.321414300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * vpnkit.exe is not running

[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * vpnkit.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior
Create a container, and click on it to see his logs.

I search through internet and always WebGL2 is related to browsers.

How can I enable WebGL2 for Docker Desktop?

I don't know if it is related with my hardware. I have a NVIDIA GeForce 9800 GT with the latest drivers.

Previous versions of Docker Desktop worked properly, I just installed the latest this week and this problem appears.

In case my hardware is the problem, Is there a way to run Docker Desktop without needing WebGL2 for logs view?

**Comment by nicks** [comment] 2022-07-08 04:19
Thanks for reporting! Yes, we changed how we do log rendering. But we haven't seen this particular error and I'm not able to reproduce it. We'll investigate a bit.

**Comment by trungutt** [comment] 2022-07-08 08:18
Hi @cacharrin could you try out this custom build to see if this problem still persists?

https://desktop-stage.docker.com/win/main/amd64/82727/Docker%20Desktop%20Installer.exe

**Comment by sparck75** [comment] 2022-07-08 11:54
Same error here on all my container running a NodeJS images.  Logs are no longer working since 4.10.1.  No issues prior.

**Comment by cacharrin** [comment] 2022-07-08 14:53
@trungutt Yes, that version worked! :)

**Comment by trungutt** [comment] 2022-07-10 05:42
@sparck75 could you try out the above custom build?

**Comment by nicks** [comment] 2022-07-14 23:22
this will be fixed in the next release

**Comment by gavin-timbrell** [comment] 2022-07-28 16:24
We've just released [Docker Desktop 4.11.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4110) which includes a fix for this.

**Closed by gavin-timbrell** 2022-07-28 16:24 UTC
Labels: status/3-fixed
