### ISSUE TITLE
docker for wsl stopped working

### ISSUE THREAD

**Issue by zallarak** [docker/for-win#9824] opened 2020-12-15 19:10 UTC
[diagnostics.log](https://github.com/docker/for-win/files/5698012/diagnostics.log)

Windows version: 19041.685
Docker from WSL2 itself
Docker Desktop on Windows v20.10.0

In WSL2:
```
$ which docker-compose
/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose
$ which docker
/mnt/c/ProgramData/DockerDesktop/version-bin/docker
```

In WSL2 (continued)
```
$ docker --help

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

See https://docs.docker.com/docker-for-windows/wsl/ for details.
```

In powershell:
```
docker --help -> expected output
```

windows docker desktop settings:

![image](https://user-images.githubusercontent.com/806155/102261096-0dbf0000-3ec6-11eb-8c48-9481534da544.png)

**Comment by simonferquel** [comment] 2020-12-16 10:33
Can you give the diagnostic ID that has been uploaded (or re-generate a diagnostic file and give me the generated ID) ?

**Comment by zallarak** [comment] 2020-12-16 16:48
@simonferquel this is the folder name generated for that log file: `20201215175024` - do you need anything else?

**Comment by simonferquel** [comment] 2020-12-16 16:51
yes when you generate a diagnostic file, a big archive is uploaded somewhere on our servers, and you get a diagnostic ID (that shows up in the diagnostic UI). I need that ID to access the whole set of logs and config files required to debug the issue.

**Comment by zallarak** [comment] 2020-12-16 16:54
Is that the folder name? I don't see any "diagnostic UI"

![image](https://user-images.githubusercontent.com/806155/102380011-4b7e6000-3f7c-11eb-94fb-6f736943980c.png)

Please confirm if you need anything else from me.

**Comment by simonferquel** [comment] 2020-12-16 16:57
You need to click the "upload" button so I can access it. It will give you the diagnostic ID

**Comment by zallarak** [comment] 2020-12-16 17:00
Diagnostic ID: `D44F3937-7A12-48CC-A5E6-891D078B1EDD/20201216165931`

**Comment by simonferquel** [comment] 2020-12-17 07:42
Sorry, I just figured I answered on the wrong ticket... my bad!

So symlinks to the CLI tools seem ok. From ubuntu, what does `/usr/bin/docker info` gives you ? Also, can you check `/usr/bin` is in your PATH ?

**Comment by zallarak** [comment] 2020-12-17 15:54
Looks like `/usr/bin` is on the path but the docker command is not there @simonferquel 

```
$ /usr/bin/docker --info
bash: /usr/bin/docker: No such file or directory

$ echo $PATH | grep /usr/bin
/home/zain/miniconda3/bin:/home/zain/go/bin:/home/zain/miniconda3/bin:/home/zain/go/bin:/home/zain/.nvm/versions/node/v12.18.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Go/bin:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/zalla/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/zalla/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/zalla/go/bin:/mnt/c/Users/zalla/AppData/Local/Keybase/:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
```

**Comment by simonferquel** [comment] 2020-12-17 16:08
Hmm, that is very strange, as in the logs, we can see `[00:09:01.427][WslIntegrationAgent-Ubuntu][Info   ] msg="creating symlink for /usr/bin/docker"`. So the integration agent running in Ubuntu seem to have created the symlink correctly.

No such file or directory can actually mean multiple things in this context:
- /usr/bin/docker does not exists (somehow, the integration service did not create the link after all)
- the file pointed by /usr/bin/docker does not exists (you can check with `ls -al` or using `lstat` the target of the symlink and check this)
- the `docker` executable tries to load a library that is not found - which is a bit strange if you have a normal Ubuntu installation, but could happen. 

Can you have a look at this ?

**Comment by simonferquel** [comment] 2020-12-17 16:15
Ah no, ok, actually I thought docker was running fine but you just could not run the CLI. Looking further into the logs, the backend actually failed to start with the same kind of logs as https://github.com/docker/for-win/issues/9798.
If you don't have sensitive information in you containers / volumes, could you please export your docker-desktop-data distro and send it to me at simon.ferquel@docker.com ? (we are trying to reproduce the issue very hard without luck yet).

To create the export, you can run `wsl.exe --export docker-desktop-data some-file.tar`.

**Comment by zallarak** [comment] 2020-12-17 17:30
Please refer to the initial issue - docker isn't running in the WSL2 environment at all. It just crashes immediately.

I made the export, its 4GB. I can upload it to a cloud provider, will email you when its done, it will take a while.

**Comment by simonferquel** [comment] 2020-12-17 17:32
That is super-helpful, thanks!

**Comment by zallarak** [comment] 2020-12-17 20:45
@simonferquel I shared the file with you via Google Drive.

**Comment by simonferquel** [comment] 2020-12-18 09:41
Thanks a lot, I was able to reproduce locally, identify the root cause, and we have a fix inbound: https://github.com/moby/moby/pull/41817

**Comment by zallarak** [comment] 2020-12-18 17:07
You have kept me on win-docker my friend. Eagerly awaiting the merge @simonferquel - in the meantime, let me know if there's a workaround you're aware of. Really appreciate it.

**Comment by tiborvass** [comment] 2020-12-19 23:33
There is a fix incoming at moby/moby#41817 thanks to @simonferquel and @cpuguy83, in the meanwhile this is the workaround, I've tested myself.

# 🚧  WORKAROUND 🚧 

```
wsl.exe -d docker-desktop
$ nsenter -a -t $(pgrep lifecycle-server) find /var/lib/docker/containers -name config.v2.json -exec sed -i'' -E 's/"Running":true(,.*"Restarting":true)/"Running":false\1/' {} \;
```

Then Quit Docker Desktop, and start it gain. (Maybe Restart works too, I didn't try that)

**Comment by tiborvass** [comment] 2020-12-19 23:48
I'm closing this in favor of #9755 which was opened before. If you still have issues after the workaround, let us know below and we'll investigate.

**Closed by tiborvass** 2020-12-19 23:48 UTC

**Comment by zallarak** [comment] 2021-01-04 22:12
Guys - the workaround doesn't run on WSL2 or Powershell - still utterly broken.

![image](https://user-images.githubusercontent.com/806155/103584811-e4770b80-4e96-11eb-90b2-5bd977f1aff6.png)

![image](https://user-images.githubusercontent.com/806155/103584820-eb058300-4e96-11eb-80a7-6f5f631caec2.png)

**Comment by rloutrel** [comment] 2021-01-05 13:47
@zallarak : you should post in #9755 (every thing is centralized there)
