### ISSUE TITLE
v20.10.5 crashes previously fine containers.

### ISSUE THREAD

**Issue by jeacott1** [docker/for-win#10632] opened 2021-03-12 01:34 UTC
docker updated today to 3.2.1 (61626) v20.10.5
now containers that have run perfectly in the past crash - details below.

  - [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 61E44266-2D2C-41FD-A3D8-EF1089A12376/20210312012740

### Actual behavior

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xee057431, pid=165, tid=0xad4ffb40
#
# JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
# Java VM: OpenJDK Server VM (25.275-b01 mixed mode linux-x86 )
# Problematic frame:
# J 128 C2 java.lang.ThreadLocal$ThreadLocalMap.getEntry(Ljava/lang/ThreadLocal;)Ljava/lang/ThreadLocal$ThreadLocalMap$Entry; (42 bytes) @ 0xee057431 [0xee057400+0x31]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid165.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
qemu: uncaught target signal 6 (Aborted) - core dumped
```

### Expected behavior
no crash - clean run.

### Information

  - Windows Version: 10.0.18363 N/A Build 18363
  - Docker Desktop Version: 3.2.1 (61626) v20.10.5
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior
no clue.
this is a 32 bit application running in an ubuntu container. worked flawlessly until this update.

**Comment by StefanScherer** [comment] 2021-03-12 06:25
Thanks @jeacott1 for your report. We are working on a fix for this.
In the meantime you could use the command described in this ticket https://github.com/docker/for-win/issues/10594#issuecomment-794359992 to disable 32bit emulation.

**Comment by stephen-turner** [comment] 2021-03-12 09:08
Closing as dupe of #10594.

**Closed by stephen-turner** 2021-03-12 09:08 UTC
Labels: version/3.2.1
