### ISSUE TITLE
Erro docker id : A8B47BEB-2C4E-4947-9EE2-6351E99F02F0/20210608014410

### ISSUE THREAD

**Issue by kellenThaisaLima** [docker/for-win#11400] opened 2021-06-08 02:00 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A8B47BEB-2C4E-4947-9EE2-6351E99F02F0/20210608014410

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment] 2021-06-08 08:20
Dupe of #11398.

**Closed by stephen-turner** 2021-06-08 08:20 UTC
