### ISSUE TITLE
HTML file added to startup when updating

### ISSUE THREAD

**Issue by rogerfar** [docker/for-win#6955] opened 2020-05-29 13:01 UTC
Every time I update docker it creates a file in C:\Users with just the first name of my profile:

![image](https://user-images.githubusercontent.com/1142915/83262341-0af2fc80-a17a-11ea-8e48-e5f5c702349a.png)
This file looks like an upgrade log:
```
[13:08:51.329] [InstallHandler] No installation found
[13:08:51.337] [InstallHandler] Using embedded package
[13:08:51.505] [InstallWorkflow] Using package: res:CommunityInstaller.DockerDesktop.d4w
[13:08:51.510] [InstallWorkflow] Downloading
[13:08:52.512] [InstallWorkflow] Extracting manifest
[13:08:53.072] [InstallWorkflow] Checking prerequisites
[13:08:53.498] [InstallWorkflow] Unpacking artifacts
[13:10:10.326] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[13:10:14.870] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[13:10:19.387] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[13:10:19.862] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[13:10:19.868] [InstallWorkflow-ServiceAction] Removing service
[13:10:19.872] [InstallWorkflow-ServiceAction] Creating service
[13:10:21.227] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[13:10:21.243] [InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[13:10:21.308] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[13:10:21.312] [InstallWorkflow-ShortcutAction] Ignore shortcut: C:\Users\Roger Versluis\Desktop\Docker Desktop.lnk/Docker Desktop
[13:10:21.316] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[13:10:21.321] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:10:21.423] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:10:21.702] [InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[13:10:22.605] [InstallWorkflow] Registering product
[13:10:22.793] [InstallWorkflow] Installation succeeded

```

But what is really annoying, it also creates a startup entry:
![image](https://user-images.githubusercontent.com/1142915/83262422-31b13300-a17a-11ea-804f-39dd8a1aff1c.png)
Now every time windows starts this file gets opened, I have to remove this file by hand for it to stop.

Why is it doing this?

**Comment by mat007** [comment] 2020-05-29 13:16
Thanks for the report, I believe this a duplicate of #6552

**Closed by mat007** 2020-05-29 13:16 UTC
