### ISSUE TITLE
"unexpected error occurred" when starting Docker Desktop on Windows 11 Home

### ISSUE THREAD

**Issue by rc5hack** [docker/for-win#13524] opened 2023-06-01 15:42 UTC
### Description

I'm trying to start Docker Desktop on Windows Home and everytime getting the same error: "An unexpected error occurred. Restart Docker Desktop".

### Reproduce

1. Fresh install Windows 11 Home Single Language 64 bit (version 22H2).
1. Get updates from Windows Update. Reboot.
1. Run `wsl --install` as described [here](https://learn.microsoft.com/en-us/windows/wsl/install), now you have WSL 2 and don't have WSL 1. Reboot.
1. Install Docker Desktop 4.20.0 (109717) - no errors during installation. Reboot.
1. Start Docker Desktop. Get "An unexpected error occurred. Restart Docker Desktop" in GUI.
1. Restarting Docker Desktop doesn't help, rebooting Windows doesn't help, the error persists.
1. You can't change settings of Docker Desktop in GUI, checkbox "Use the WSL 2 based engine" is unchecked, "Apply" button is disabled.
1. But you still can run docker containers in CLI without errors.

### Expected behavior

Docker Desktop should run normally with WSL 2 backend on Windows 11 Home.

### docker version

```bash
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.20.0 (109717)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.441GiB
 Name: docker-desktop
 ID: 7fb58d8f-431b-499e-af4e-65df0879afee
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Diagnostics ID

B1DCAD74-D918-4B2D-817F-1FF6C5E0A609/20230601145912

### Additional Info

I use laptop with AMD Ryzen 5 5600H and 16 Gb RAM, virtualization is enabled in BIOS.

I tried to `wsl --update`, to reinstall WSL, to disable "Windows fast startup", to reinstall Docker Desktop, finally I tried with fresh reinstalled Windows with no success.

```
>wsl --version
Версия WSL: 1.2.5.0
Версия ядра: 5.15.90.1
Версия WSLg: 1.0.51
Версия MSRDC: 1.2.3770
Версия Direct3D: 1.608.2-61064218
Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Версия Windows: 10.0.22621.1702
```

```
>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2023-06-01T14:47:44.084560300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.vpnkit.exe is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[SKIP] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[WARN] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.112.1

Please note the following 1 warning:

1 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.112.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address


Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.vpnkit.exe is not running



Not all of the backend processes are running.
```

**Comment by vhexl** [comment] 2023-06-01 16:36
I also had this problem, after I updated Docker Desktop to 4.20.0 (109717)

**Comment by ctalledo** [comment] 2023-06-01 16:55
Hi @rc5hack, thanks for filing the issue and apologies for the problem.

Can you please execute `wsl --version` on a command prompt or powershell on your host, and post the output here?

Thanks!

**Comment by ctalledo** [comment] 2023-06-01 16:58
Looking at the diagnostics bundle, it seems this issue is caused by Docker Desktop failing to parse the WSL version on the host:

```
[com.docker.backend.exe][E] getting WSL version: unexpected WSL version format: ^R^D5^D@^DA^D8^DO^D ^@W^@S^@L^@:^@ ^@1^@.^@2^@.^@5^@.^@0^@^M^@; want <maj.min.rev.patch>E
```

It is a likely bug in the Docker Desktop WSL version parser, apparently it's not dealing with this host's language / locale correctly.

Note: this is different that issue #13518, where the DD fails to obtain the WSL version for a different reason (exit code 0xffffffff).

**Comment by rc5hack** [comment] 2023-06-01 18:14
> Can you please execute `wsl --version` on a command prompt or powershell on your host, and post the output here?

Output of `wsl --version` includes Russian since I use "Home Single-language" version of Windows 11 (comes with laptop), this language can't be changed without re-installing Windows:

```
> wsl --version
Версия WSL: 1.2.5.0
Версия ядра: 5.15.90.1
Версия WSLg: 1.0.51
Версия MSRDC: 1.2.3770
Версия Direct3D: 1.608.2-61064218
Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Версия Windows: 10.0.22621.1702

```
translation of this output (made by hands, just for better searching):

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1702
```

**Comment by ctalledo** [comment] 2023-06-01 18:23
Thanks @rc5hack. I think DD has a bug parsing the output of WSL version for this locale. We will fix it ASAP.

**Comment by ctalledo** [comment] 2023-06-01 22:11
FYI we have a fix in progress, will be available in the next few days. Apologies again and thanks for your patience.

**Comment by egor-fipu** [comment] 2023-06-02 06:40
I also had this problem, after I updated Docker Desktop to 4.20.0

**Comment by egor-fipu** [comment] 2023-06-02 06:41
I also had this problem, after I updated Docker Desktop to 4.20.0. I did all the same manipulations except reinstalling windows. Nothing helped.

**Comment by KTXKIKI** [comment] 2023-06-02 07:01
唯一方法  用4.19  等官方修复

**Comment by qinfen** [comment] 2023-06-02 08:51
> 唯一方法 用4.19 等官方修复

4.19改不了disk image location， 说是4.20修复了这个问题，结果4.20直接wsl2不能用了。。。

**Comment by KTXKIKI** [comment] 2023-06-02 09:28
> > 唯一方法 用4.19 等官方修复
> https://docs.docker.com/desktop/release-notes/
> 4.19改不了磁盘映像位置， 说是4.20修复了这个问题，结果4.20直接wsl2不能用了。。。

**Comment by sykang0223** [comment] 2023-06-05 06:21
also this problem occured on my desktop. please give us a way for downgrading 4.20.0 to 4.19 something.

**Comment by ctalledo** [comment] 2023-06-05 06:24
> please give us a way for downgrading 4.20.0 to 4.19 something.

Hi @sykang0223, you can find Docker Desktop 4.19 here: https://docs.docker.com/desktop/release-notes

**Comment by fengzhao** [comment] 2023-06-05 09:53
什么时候能修复啊？

**Comment by fengzhao** [comment] 2023-06-05 09:53
```
C:\Program Files\Docker\Docker\resources>com.docker.diagnose.exe check
[2023-06-05T09:48:04.668817200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.vpnkit.exe is not running


[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[SKIP] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?

Please investigate the following 1 issue:

1 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.vpnkit.exe is not running



Not all of the backend processes are running.


C:\Program Files\Docker\Docker\resources>


```

**Comment by KTXKIKI** [comment] 2023-06-05 10:00
> 什么时候能修复啊？

耐心等吧  开源的东西  或者打钱过去加速下

**Comment by lorenrh** [comment] 2023-06-05 16:47
We've release docker Desktop 4.20.1, containing a fix for this issue, so I'm closing this issue. 

For more information, head to https://docs.docker.com/desktop/release-notes/.

**Closed as completed by lorenrh** 2023-06-05 16:47 UTC
Labels: status/acknowledged, area/WSL2, version/4.20.0, version/4.31.1

**Comment by ctalledo** [comment] 2023-06-05 16:56
Folks, please let us know if DD 4.20.1 does in fact address the issue in your locale. If it doesn't, please post the output of `wsl --version` on your host (exactly as it shows up in your locale, without translation to english).

**Comment by gjycn** [comment] 2023-06-05 17:21
> Folks, please let us know if DD 4.20.1 does in fact address the issue in your locale. If it doesn't, please post the output of `wsl --version` on your host (exactly as it shows up in your locale, without translation to english).

Good, it's done.
Here is my version
```
WSL 版本： 1.2.5.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.51
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22631.1830
```

**Comment by rc5hack** [comment] 2023-06-05 17:32
Issue with Docker Desktop startup on Windows 11 Home Single Language 64 bit 22H2 (Russian locale) is fixed with DD 4.20.1. Thanks!  👍🏻

**Comment by syk-repository** [comment] 2023-06-07 01:28
bug fixed on windows 11 Pro 22H2. thx and all developers god saves you.

**Comment by qinfen** [comment] 2023-06-08 03:17
4.20.1改变Disk Image location后重启软件后，Containers和Images会丢失。

**Comment by fengzhao** [comment] 2023-06-08 03:25
> 4.20.1改变Disk Image location后重启软件后，Containers和Images会丢失。

改变路径后，你也要移动对应的文件吧

**Comment by qinfen** [comment] 2023-06-08 03:48
> 

改变后软件会自动迁移文件，但是重启软件之后就识别不了了，感觉像是虽然文件迁移了但是软件还是识别的默认路径

**Comment by AgentFire** [comment] 2024-06-16 18:25
Same. It gathered some data tho, and provided me with this error report id: 10ECCD38-9330-4E4C-A8E3-A8A9F2321BE1/20240616182040

**Comment by ctalledo** [comment] 2024-07-09 17:45
Thanks @AgentFire for uploading the diagnostics bundle (and sorry for the late response); looking at it now to see what's happening.

**Comment by iuv-work** [comment] 2024-07-10 12:50
Same. 8A0BBD74-A741-4F45-9D68-111A6ED44084/20240710124543

**Comment by wangzaistone** [comment] 2024-12-26 08:46
Have same problem  on windows , the latest version 2024-12-26

**Comment by ctalledo** [comment] 2025-01-06 18:03
Hi @wangzaistone , can you please provide more info by uploading a Docker Desktop [diagnostics bundle](https://docs.docker.com/desktop/troubleshoot-and-support/troubleshoot/#diagnose)?

Thanks!

**Comment by tibran19** [comment] 2025-01-27 04:10
![Image](https://github.com/user-attachments/assets/52412665-840f-40bc-9ee8-78806ecd8bde)

I cant open docker , it sans wsl failed
