### ISSUE TITLE
Docker compose can't delete container when custom file passed

### ISSUE THREAD

**Issue by borsch** [docker/for-win#11046] opened 2021-03-11 18:06 UTC
## Problem description
In same folder I have `docker-compose.yaml` & `docker-compose-custom.yaml`. These two files has common containers with same names and some specific containers. Example:
  - docker-compose might have `common-1`, `common-2`
  - docker-compose-custom might have `common-1`, `custom-1`

When I run docker-compose via `docker-compose -f docker-compose-custom.yaml up --build` and after some testing I delete group of containers via docker desktop(check screenshot). This deletes only containers that is specified in `docker-compose.yaml` not in `docker-compose-custom.yaml`. So `common-1` is deleted while `custom-1` continue exist
![image](https://user-images.githubusercontent.com/7887777/110833143-d08bc380-82a4-11eb-89f3-436afa82504f.png)

**Comment by nebuk89** [comment] 2021-04-26 15:14
Moving to for-win as not a Hub issue :)

**Comment by stephen-turner** [comment] 2021-04-26 16:33
Which version of Docker Desktop? This sounds like it might have the same root cause as #10564, but that was fixed in version 3.3.0.

**Comment by borsch** [comment] 2021-05-14 09:41
@stephen-turner just updated to 3.3.3 and I can see the same issue. Full version info

![image](https://user-images.githubusercontent.com/7887777/118252658-ad061480-b4b1-11eb-9240-3320ae360dd4.png)

**Comment by trungutt** [comment] 2021-05-17 19:57
Thanks for your report @borsch. We managed to reproduce the same behavior and that should be fixed in the next release

**Comment by mat007** [comment] 2021-06-10 06:51
A fix has been released in Docker Desktop 3.4.0, see [the release notes](https://docs.docker.com/docker-for-windows/release-notes/#bug-fixes-and-minor-changes)!

**Closed by mat007** 2021-06-10 06:51 UTC
