### ISSUE TITLE
help me it wont run im so confused 

### ISSUE THREAD

**Issue by caimin222** [docker/for-win#11889] opened 2021-08-13 07:40 UTC
7EBFBB41-A232-45AB-83FF-CECDEAA62696/20210813073611
docker run --rm -it -v %cd%:/root/env myos-buildenv:latest
Unable to find image 'sorts:latest' locally
docker: Error response from daemon: pull access denied for sorts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by StefanScherer** [comment] 2021-08-17 08:00
Looks like your absolute current directory has a space in its name. 
Sorry we cannot give individual support here, I'll close this issue as it's not a bug in Docker Desktop as it seems to be up and running.

**Closed by StefanScherer** 2021-08-17 08:00 UTC
