### ISSUE TITLE
Docker fails to start after update with "Access is denied" message

### ISSUE THREAD

**Issue by danyx23** [docker/for-win#10916] opened 2021-04-13 22:34 UTC
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 2C83E236-A7FD-494E-92C1-13F74B89F587/20210413222336

### Actual behavior

Docker fails to start after the latest update with the following stack trace:
```
System.ComponentModel.Win32Exception:
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.ManagedProcesses.ManagedProcess.StartProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, CancellationToken stopToken) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 122
   at Docker.ManagedProcesses.ManagedProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 50
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

``` 

### Expected behavior

Docker starts normally

### Information

  - Windows Version: Windows 10.0.19042
  - Docker Desktop Version: Docker engine is v20.10.5
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, normal desktop on a laptop

### Steps to reproduce the behavior

This is a pretty vanilly windows desktop installation running as a non-privileged user (no experimental features, kubernetes disabled etc). I had this problem already yesterday after the latest update. Then I uninstalled docker and installed the newest version. This morning it told me that it would update again. Now after the update it fails to start again. For the update I upgrade to admin credentials using UAC. After the update docker doesn't start anymore for me as an un-privileged user (before it worked fine)

  1. Install docker desktop for windows
  2. Wait for update to be installed
  3. Restart, docker fails to run with above stacktrace

**Comment by stephen-turner** [comment] 2021-04-14 08:24
Thanks for the report, but closing as a dupe of #10881.

**Closed by stephen-turner** 2021-04-14 08:24 UTC
