### ISSUE TITLE
Boot system, docker reports crash

### ISSUE THREAD

**Issue by jmoratilla** [docker/for-win#8450] opened 2020-09-12 09:17 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jmoratilla** [comment] 2020-09-12 09:20
## Expected behavior
Boot the system without docker crash

## Actual behavior
The system boots and docker crashses

## Information

* Windows Version: Windows 10 pro 2004
* Docker Desktop Version: Docker Desktop WSL distro
* Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, personal laptop

## Steps to reproduce the behavior
...
...

**Comment by dalexhd** [comment] 2020-09-14 20:19
See #8449

**Comment by stephen-turner** [comment] 2020-09-15 09:07
Could be a dupe of #8449, but not enough info to diagnose. Closing.

**Closed by stephen-turner** 2020-09-15 09:07 UTC
