### ISSUE TITLE
Container 'does not send any data' when request is sent

### ISSUE THREAD

**Issue by aysark** [docker/for-win#197] opened 2016-11-02 21:42 UTC
I have a dockerfile thats based off ubuntu 16.04 and i install a proprietary product thats powered by tomcat and exposes a webserver.  Then i run:
```
$ docker build -t p-installer:b6489 .
$ docker run -d -p 7080:7080 --name pcontainer --hostname pcontainer -t p-installer:b6489
```

Using Docker for Windows latest (1.12.1), i try to access the container from my local docker build machine (`http://172.17.0.2:7080`) and am unable to- the response on chrome:

> The 172.17.0.2 page isn’t working
> 
> 172.17.0.2 didn’t send any data.
> ERR_EMPTY_RESPONSE

But I can see in the docker internal logs that its passing my request to the container but there is an error also logged:
```
[13:25:48.965][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443: connected
[13:26:10.024][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443 completed: l2r = 1.5 KiB bytes at 75 bytes/sec and 0.2 IOPS/sec; r2l = 893 bytes bytes at 42 bytes/sec and 0.1 IOPS/sec
[13:27:34.589][VpnKit         ][Error  ] com.docker.slirp.exe: Socket.TCPV4.read connected TCP: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
[13:27:34.590][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443 completed: l2r = 1.6 KiB bytes at 60 bytes/sec and 0.2 IOPS/sec; r2l = 555 bytes bytes at 3 bytes/sec and 0.0 IOPS/sec
[13:38:28.196][VpnKit         ][Error  ] com.docker.slirp.exe: Socket.TCPV4.read connected TCP: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
[13:38:28.197][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443 completed: l2r = 46.4 KiB bytes at 58 bytes/sec and 0.2 IOPS/sec; r2l = 24.3 KiB bytes at 30 bytes/sec and 0.1 IOPS/sec
[13:38:38.196][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443: connected
[13:50:33.642][Analytics      ][Info   ] Usage Statistic: heartbeat
[13:52:48.829][VpnKit         ][Error  ] com.docker.slirp.exe: Socket.TCPV4.read connected TCP: caught Uwt.Uwt_error(Uwt.ECONNRESET, "uwt_read", "") returning Eof
[13:52:48.830][VpnKit         ][Debug  ] com.docker.slirp.exe: tcp:0.0.0.0:7443:tcp:172.17.0.2:7443 completed: l2r = 29.9 KiB bytes at 35 bytes/sec and 0.2 IOPS/sec; r2l = 23.4 KiB bytes at 28 bytes/sec and 0.1 IOPS/sec
```

I do the same above steps on a linux docker host machine and i am able to access the container fine.  I can only repro on a windows machine.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
 B80D073E-1272-43FE-A938-1D30BD7F7790/2016-11-02_14-18-59
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise 
10.0.10586 Build 10586

**Comment by rneugeba** [comment] 2016-11-03 12:16
does it work with `http://localhost:7080`?

**Comment by aysark** [comment] 2016-11-03 16:58
@rneugeba no, i tried localhost, 127.0.0.1 and also the machine's ip.  

When i do `localhost:7080` or `127.0.0.1:7080`, it redirects me to `localhost:7080/home` which is correct as that is what our app does (returns a 301 redirect to another page to follow).  However, then it returns a error response or no data received response.  Note: when i do the same exact steps on Ubuntu host machine, it works fine.

So my hunch is Docker for Windows is somehow not handling the request/responses correctly.

**Comment by friism** [comment] 2016-11-06 12:56
@aysark Docker for Windows doesn't intercept individual HTTP requests. The fact that your app successfully redirects to `/home` also suggests that networking is working correctly.

To help us reproduce, would you provide a smaller test-case not involving your proprietary software, that demonstrates the problem?

**Comment by aysark** [comment] 2016-11-07 18:22
So after some further investigating i fixed it.  Basically I had to make the containerized app expect requests from the windows host machine ip (not container ip).  Didn't have to do that on linux.

**Comment by friism** [comment] 2016-11-07 18:32
@aysark ok, so this was because your app was looking at the host header and expecting `localhost` and seeing something else?

**Comment by aysark** [comment] 2016-11-07 18:37
@friism yes.  The app was designed to look for the container's IP/hostname.

**Comment by friism** [comment] 2016-11-07 18:40
@aysark roger, thanks - just checking to see if I should close the issue: in your opinion, is this a problem with how Docker works?

**Comment by aysark** [comment] 2016-11-07 19:42
Well... its certainly confusing that the way Docker for Windows/OSX and
Linux work.  And its not documented.  I spent a good time going back and
forth with my colleague who was running the container fine on ubuntu and we
were scratching our heads thinking it was our app.  In the end.. it seems
that Docker for Windows proxy process routes the request to the container
as the host windows machine while- this is not the case for linux (its as
the container ip).

-Aysar

**Comment by friism** [comment] 2016-11-07 20:09
Sweet, thanks a lot. @londoncalling we should perhaps look at putting this in the FAQ, maybe @rneugeba can help.

**Closed by friism** 2016-11-07 20:09 UTC
Labels: area/network, status/0-more-info-needed

**Comment by jstray** [comment] 2017-04-10 22:18
I just lost a day to this problem on Docker for Mac. The requirement to bind to a non-localhost IP really needs to be better documented.

**Comment by RapiDash1** [comment] 2019-04-21 11:47
> So after some further investigating i fixed it. Basically I had to make the containerized app expect requests from the windows host machine ip (not container ip). Didn't have to do that on linux.

can you please explain this, i'm new to flutter.

**Comment by dotun** [comment] 2019-06-02 09:34
> So after some further investigating i fixed it. Basically I had to make the containerized app expect requests from the windows host machine ip (not container ip). Didn't have to do that on linux.

@aysark could you shed some more light on what this involves?
