### ISSUE TITLE
Error when trying to delete created containers with extended compose file

### ISSUE THREAD

**Issue by ridvanaltun** [docker/for-win#11494] opened 2021-06-21 04:26 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When I press delete button for a Docker Container, below error shows up with a red bubble on top of screen:

```
Cannot remove Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docker-compose.yml,docker-compose.override.yml" --project-name "node-restful-api" --project-directory "D:\cloud\repositories\node-restful-api" down .FileNotFoundError: [Errno 2] No such file or directory: '.\\docker-compose.yml,docker-compose.override.yml'
``` 

![Error](https://user-images.githubusercontent.com/10441216/122705859-34883580-d25f-11eb-907b-c745c318871e.png)

### Expected behavior

The container must be deleted.

### Information

  - Windows Version: 10.19042 Build 19042
  - Docker Desktop Version: 3.4.0
  - WSL2 or Hyper-V backend?  No
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Create `docker-compose.yml` and `docker-compose.override.yml` and use both.
  2. Deploy on host device using `docker-compose up -d` command.
  3. Try to delete running or stopped container.

Actually I can show you this on a basic Flask project, you can create and test:

app/app.py

```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
	return "Hello World!"

if __name__ == '__main__':
	app.run(host='0.0.0.0')
```

app/requirements.txt

```
flask
```

app/Dockerfile

```
FROM python:3.7-alpine 
WORKDIR /app 
COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /app 
ENTRYPOINT ["python3"] 
CMD ["app.py"]
```

./docker-compose.yml

```
version: '3' 
services: 
  web: 
    build: app 
```

./docker-compose.override.yml

```
services: 
  web: 
    ports: 
      - '5000:5000'
```

Run `docker-compose up -d` command and try to delete via Docker Windows. Error will shows up.

**Comment by stephen-turner** [comment] 2021-06-22 13:46
I can reproduce this. Stopping/deleting the individual containers works, it's stopping/deleting the app that gives this error. I am using docker compose 1.29.2.

**Comment by StefanScherer** [comment] 2021-06-22 18:09
Thanks @ridvanaltun for the report. I'm closing this as it is a duplicate of #11445 and we have a fix in the next release for that.

**Closed by StefanScherer** 2021-06-22 18:09 UTC

**Comment by Anjirliton** [comment] 2021-07-14 06:38
https://jumpshare.com/v/wv31yBnsi8kd0w0jJhql

**Comment by Anjirliton** [comment] 2021-07-14 06:38
please need a solution

**Comment by Carolyn95** [comment] 2021-08-12 08:05
Spotted this problem as well, any solutions yet?

**Comment by chris-gong** [comment] 2021-08-28 06:35
Try deleting the container through the command line instead of through Docker Desktop by running:
```
docker ps -l
docker rm <container-id>
```

**Comment by andryx77** [comment] 2021-08-31 11:28
> Try deleting the container through the command line instead of through Docker Desktop by running:
> 
> ```
> docker ps -l
> docker rm <container-id>
> ```

Thanks!

**Comment by Dramulas** [comment] 2021-09-21 11:33
![image](https://user-images.githubusercontent.com/61465225/134163340-dfe2b3c8-758e-439e-8a1a-00d447d96beb.png)
HELPPP!!

**Comment by chris-gong** [comment] 2021-09-22 04:06
@Dramulas try doing a force remove
`docker rm -f <container-id>`
