### ISSUE TITLE
thinkpad t410 i5 M430 4G ram cant change cpu or memory

### ISSUE THREAD

**Issue by osde8info** [docker/for-win#235] opened 2016-11-15 15:43 UTC
### Expected behavior
not crash
### Actual behavior
Unable to stop: Killed VM MobyLinuxVM did not stop
### Information
A23A7D60-5104-4597-8849-E121263D679D/2016-11-15_15-40-45
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... click settings
  2. ... click advanced
  3. reduce cpu to 1
  4. reduce mem to 1.7G
  5. click apply

**Comment by rneugeba** [comment] 2016-11-26 13:06
I'm not able to reproduce this issue and can run the Linux VM with the same settings you have.

Could you change the settings again, as you suggest, and if you see the error, quit Docker for Windows. The open the `Hyper-V Manager` and see if the VM called `MobyLinuxVM` is still marked as running. If it is, select it and the use `Turn Off..` to turn the VM off. Then restart Docker for Windows and see if the new values have been applied.
Thanks

**Comment by rneugeba** [comment] 2016-12-02 15:58
Closing this issue due to lack of response. Please re-open if the issue persists and you have further information.
Thanks

**Closed by rneugeba** 2016-12-02 15:58 UTC
Labels: status/0-more-info-needed, status/0-triage, version/1.12.3
