### ISSUE TITLE
no dockernat switch found in hyper-v manager

### ISSUE THREAD

**Issue by echnyee** [docker/for-win#5814] opened 2020-02-19 06:19 UTC
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: windows 10
  - Docker Desktop Version: 2.2.0.3(42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. hyper-v and virtualization is enabled
  2. install docker desktop successfully, no error report occurs, but there is no dockerNat switch in hyper-v manager

**Comment by stephen-turner** [comment] 2020-02-21 12:07
Closing as dupe of #5538. In particular, see https://github.com/docker/for-win/issues/5538#issuecomment-579340106 for the reasons.

**Closed by stephen-turner** 2020-02-21 12:07 UTC
