### ISSUE TITLE
--squash Data Loss

### ISSUE THREAD

**Issue by vikalyan** [docker/for-win#1410] opened 2017-12-11 22:04 UTC
# Expected behavior

I have a simple enough Windows container. The image adds some registry entries and downloads and installs the SysInternalsSuite of applications into a folder. When the container image is built with the ```squash``` option, the container should make sure to not lose any changes made to the container image.

In other words, if I run this container image, then the folder ```C:\SysInternalsSuite``` which was created and should contain the tools should be present. 

# Actual behavior

In reality, the file changes that were made are lost. The folder ```C:\SysInternalsSuite``` does not exist if ```-squash``` is used to build the image. The folder does exist if the image is not squashed.

# Information

## Contents of PowerShell Script ```install-1.ps1```

```
New-Item -Force -Path "C:\Downloads" -ItemType Container
Invoke-WebRequest -Uri "https://download.sysinternals.com/files/SysinternalsSuite.zip" -UseBasicParsing -OutFile "C:\Downloads\SysInternalsSuite.zip" -UserAgent "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)"
Expand-Archive -LiteralPath "C:\Downloads\SysInternalsSuite.zip" -DestinationPath "C:\SysInternalsSuite"
```

## Contents of CMD Script ```install-1.cmd```

```
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -WindowStyle Hidden -File "C:\install-1.ps1"
exit /B %ERRORLEVEL%
```

## Contents of Dockerfile

```
FROM microsoft/dotnet-framework:3.5-windowsservercore-10.0.14393.1480
COPY install-*.* C:\
RUN "C:/install-1.cmd"

## Output of ```docker version```

```
Client:
 Version:       master-dockerproject-2017-12-07
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    ace54179
 Built: Thu Dec  7 23:49:17 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      master-dockerproject-2017-12-07
  API version:  1.35 (minimum version 1.24)
  Go version:   go1.9.2
  Git commit:   8fe0a75
  Built:        Thu Dec  7 23:53:07 2017
  OS/Arch:      windows/amd64
  Experimental: true
```

## Output of ```docker info```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 38
Server Version: master-dockerproject-2017-12-07
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1794.amd64fre.rs1_release.171008-1615)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 32GiB
Name: cxtwimgbld
ID: TT52:TQGR:EFYZ:UIDC:KOKQ:QSUI:JRZ4:JWPW:VQKC:JX5B:QAIK:XQVC
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

# Steps to reproduce the behavior

Build the container image with the ```-squash``` option. For this to work, the ```experimental``` flag must be passed to the Docker daemon.

**Comment by friism** [comment] 2017-12-11 22:27
@vikalyan can you detail how data is lost? This is probably a moby/moby issue

**Comment by vikalyan** [comment] 2017-12-11 22:29
@friism  - Sure. The folder ```C:\SysInternalsSuite``` is missing when you run the container. If run without squash, this doesn't happen.

**Comment by friism** [comment] 2017-12-11 22:49
@jasonbivins can you try reproing?

**Comment by thaJeztah** [comment] 2017-12-11 23:08
Was this the same issue you reported in https://github.com/moby/moby/issues/34115 ? Or does it not produce an error?

**Comment by thaJeztah** [comment] 2017-12-11 23:09
Actually, this may be a duplicate of the issue reported here; https://github.com/moby/moby/issues/31468 (which I think is a platform (Windows) issue)

**Comment by vikalyan** [comment] 2017-12-12 00:26
Yes, it looks like it. I didn’t search moby/moby for issues. My fault!

**Comment by friism** [comment] 2017-12-12 00:53
thx for following up

**Closed by friism** 2017-12-12 00:53 UTC
