### ISSUE TITLE
Command 'docker' could not be found in this WSL 2 distro error.

### ISSUE THREAD

**Issue by ffyuanda** [docker/for-win#13088] opened 2022-11-23 04:54 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
AC3E4DE4-CB11-4E7A-9E41-4FED00FADFB4/20221123043209
### Actual behavior

Calling 'docker' in WSL 2 distro displays this error message:

> The command 'docker' could not be found in this WSL 2 distro.
> We recommend to activate the WSL integration in Docker Desktop settings.
> 
> For details about using Docker Desktop with WSL 2, visit:
> 
> https://docs.docker.com/go/wsl2/

Similar issues have been seen:

- https://github.com/docker/for-win/issues/7039
- https://github.com/docker/for-win/issues/12578
- https://github.com/docker/for-win/issues/6441
- https://github.com/docker/for-win/issues/12321
- https://github.com/docker/for-win/issues/11308

I have tried to:
- Reinstall Docker Desktop
- Reboot my computer
- Stop services and restart Docker Desktop
- Update my WSL 2 distro version to the latest

But unfortunately nothing really worked :(

I tried to look into the symlinks and scripts pointed by `docker` and found that the `/mnt/wsl/docker-desktop/cli-tools` folder is empty, which causes this error. It seems that this folder is not mounted correctly in WSL 2, because when I use Windows Explorer to look into this folder, everything (i.e. executables, scripts) is there, as expected.

### Expected behavior
Calling 'docker' in WSL 2 will successfully invoke the executable.

### Information

  - Windows Version:  
 
      Edition	Windows 10 Pro
      Version	21H2
      Installed on	‎3/‎4/‎2021
      OS build	19044.2251
      Experience	Windows Feature Experience Pack 120.2212.4180.0

  - Docker Desktop Version: 
  
      Docker Desktop 4.14.1 (91661)

  - WSL2 or Hyper-V backend?  
  
      WSL 2

  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
  
    No.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
[2022-11-23T04:42:45.332732400Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0031: does the Docker API work?
[PASS] DD0032: do Docker networks overlap with host IPs?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. Try to call `docker` in WSL 2 terminal.

**Comment by sheriftawaptawap** [comment] 2022-12-09 20:31
Same as my problem ,

My docker was working will for 5 months, I followed these steps to setup and download it 
( https://github.com/jstormes/php-docker-compose/blob/main/Documentation/01a_InstallingDockerOnWindows.md ) and worked nicely but yesterday it was not working although I download the latest version and followed same steps but does not work.

this command also not working with me " dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart "

**Comment by damoncasale** [comment] 2023-01-13 19:53
Same error.  This has been open since November...anyone?????

**Comment by jonaskello** [comment] 2023-01-31 06:55
I have the same problem. I tried `wsl -l` and got this output:

```
> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
docker-desktop-data
```

I think there should be an entry `docker-desktop` in there but it seems to be missing.

**Comment by samuelmaina** [comment] 2023-03-09 15:43
I have the same problem. I have tried everything. I can see that all the docker files are in wsl. Anyone who has found a way out. I have tried downgrading ubuntu and the problem persist. Anyone found a solution?

**Comment by jadeiss** [comment] 2023-03-10 21:21
I just had a similar problem. What resolved it for me was:

1. In Docker Desktop navigate to "Settings > Resources > WSL integration" and under "Enable integration with additional distros:" I selected all available distros (the checkbox for enabling integration with the default WSL distro was already checked and I was getting the error in my default distro).
2. Updated docker desktop to the latest version available. Docker Desktop is now on v4.17.0 (99724). 

Once Docker Desktop updated, I restarted WSL with `wsl --shutdown` and then within the WSL terminal `docker -v` now returns the version.

```bash
> docker -v
Docker version 20.10.23, build 7155243
```

**Comment by cforce** [comment] 2023-03-13 09:14
Same issue here,  ou of the nothing .. none of the fixes above works

**Comment by ffyuanda** [comment] 2023-03-25 01:32
The problem still exists as per Docker Desktop 4.17.1 :-(

**Comment by slikts** [comment] 2023-04-01 01:01
I've encountered this issue too, the command was working but now it's gone, and toggling the integration options off and on again doesn't fix it.

**Comment by cforce** [comment] 2023-04-01 14:21
To many issues - giving now https://podman-desktop.io/ a try

**Comment by slikts** [comment] 2023-04-02 12:56
I've not yet fully verified it, but it seems like Docker needs to be restarted too if WSL gets shut down for the CLI commands to be available.

**Comment by AmineDjeghri** [comment] 2023-04-14 12:06
updating docker in the settings also solves the problem

**Comment by cforce** [comment] 2023-04-15 15:34
This are all workarounds and not a solution anyway. Docker needs to take care. e.g listen to wsl restart's and then restart itself if need and don't let the user run into manually dealing with build in bit not monitored dependencies to other runtimes.

**Comment by viniciushrcs** [comment] 2023-04-15 16:07
I am having the same issue. Docker is not working after I upgraded to 4.18, and now even with dowgrande it does not work. :/

**Comment by kuvasney** [comment] 2023-05-19 14:14
> I just had a similar problem. What resolved it for me was:
> 
> 1. In Docker Desktop navigate to "Settings > Resources > WSL integration" and under "Enable integration with additional distros:" I selected all available distros (the checkbox for enabling integration with the default WSL distro was already checked and I was getting the error in my default distro).
> 2. Updated docker desktop to the latest version available. Docker Desktop is now on v4.17.0 (99724).
> 
> Once Docker Desktop updated, I restarted WSL with `wsl --shutdown` and then within the WSL terminal `docker -v` now returns the version.
> 
> ```shell
> > docker -v
> Docker version 20.10.23, build 7155243
> ```

this solution fixed the problem for me. Thank you!

**Comment by tomerb3** [comment] 2023-06-18 12:26
I fixed my problem. similar to [RickRosendaal] but with a little difference:
I use softlink to docker.exe and not to docker, cause docker file in resources/bin/ not worked fine 

so my commands: 

sudo rmdir /usr/bin/docker  
sudo ln -s "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" /usr/bin/docker

**Comment by HollisTech** [comment] 2023-07-04 18:46
And it happened again to me.  Updated docker for windows, my default wsl vm  had its symlinks pointing at nothing on docker-desktop-data. 
Shutting down all wsl images (wsl --shutdown) and restarting docker for windows eventually resolved the problem. 

This bug has been reported in  various  forms for years now (see the list at the top of the bug report). Is it ever going to be fixed?

**Comment by gabrielknot** [comment] 2023-07-06 22:56
that start happened with me after wsl2 update. trying to fix updating docker but had no sucess

**Comment by KiranVKumar** [comment] 2023-08-09 09:36
It worked for after switching to Linux container on docker desktop.  
Right click on running Docker icon (next to clock) and chose "Switch to Linux containers"

**Comment by diablodale** [comment] 2023-10-30 16:19
for me...this is directly related to Docker Desktop newer features related to "power savings".
When I get this error by running a command line `docker container ls`, all I need to do it click on the Docker Desktop tray icon to expand their app and fiddle around with the UI...to wake it up. Then my use of docker works again.

I suspect this is related to their "Resource saver" mode.

**Comment by TheRealAlexV** [comment] 2023-10-31 11:58
This bug has been around for nearly two years now. I am also experiencing this issue now and it's affecting my work. Microsoft needs to get their act together here.

**Comment by carlosrmendes** [comment] 2023-11-08 15:08
> for me...this is directly related to Docker Desktop newer features related to "power savings". When I get this error by running a command line `docker container ls`, all I need to do it click on the Docker Desktop tray icon to expand their app and fiddle around with the UI...to wake it up. Then my use of docker works again.
> 
> I suspect this is related to their "Resource saver" mode.

same for me, when my docker desktop is in resource saver mode I cannot execute the "docker" command on WSL terminal

**Comment by vcvitaly** [comment] 2023-11-10 10:07
I had to delete both Ubuntu-22.04 and Docker Desktop, then install them both again in that order:
1. Ubuntu-22.04
2. Docker Desktop
After that it worked.

**Comment by ffes** [comment] 2023-11-13 08:40
For me, this is clearly related to the Resource Saver mode. After starting Docker Desktop v4.25.0 I can enter the `docker` command as expected. When the Resource Saver mode kicks in, the `docker` command is no longer found (started from WSL2)

```bash
$ docker
-bash: /usr/bin/docker: No such file or directory
```

When I open "Change Settings" from the context menu and go to the "Resources" tab the Resource Saver mode stops and the `docker` command works again. Closing the settings dialog and wait for 5 minutes the Resource Saver mode kicks in again and the `docker` command is not found again.

So I disabled the Resource Saver mode to work around this annoying behavior.

**Comment by mhamra** [comment] 2023-11-16 13:03
I've turned off the Resource Saver mode. That also solved the problem for me.

**Comment by bedla** [comment] 2023-11-21 18:36
My observations are:

1. When Docker Desktop is not in Power saver mode
```
PS C:\Users\bedla.czech> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
  Ubuntu                 Running         2
```

2. Both PowerShell and WSL-Ubuntu terminals returns correct output
```
bedla@bedla-ntb:~$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default
... etc.
```

3. When Docker desktop goes to Power saver mode
```
PS C:\Users\bedla.czech> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
  Ubuntu                 Running         2
```

4. PowerShell returns, correctly
```
PS C:\Users\bedla.czech> docker version
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default
... etc.
```

5. **BUT WSL-ubuntu terminal returns error**
```
bedla@bedla-ntb:~$ docker version
-bash: /usr/bin/docker: No such file or directory
```

6. When I switch to normal mode, WSL-ubuntu terminal works correctly
```
bedla@bedla-ntb:~$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default
... etc.
```

---

I am having latest Docker Desktop installed v4.25.1
```
bedla@bedla-ntb:~$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by bmeier-pros** [comment] 2023-11-21 18:56
The root issue here appears to be a dynamic filesystem mount that is managed by docker desktop.  The mount goes away when the resource saver activates.

lrwxrwxrwx 1 root root 48 Nov 21 09:59 /usr/bin/docker -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker

**Comment by bedla** [comment] 2023-11-21 19:20
New observation, with v4.25.2 in Power saver mode WSL is not suspended
```
PS C:\Users\bedla.czech> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
  Ubuntu                 Running         2
```

AND `docker version` command in WSL-ubuntu terminal works (when command is run, Docker Desktop goes to normal mode from Power saver mode).

BUT not stopping `docker-desktop` and `docker-desktop-data` is expected behavior? I mean, when I compare it to previous versions.

**Comment by MihaelaStoica** [comment] 2023-11-22 11:32
We've released a new version of Docker Desktop, 4.25.2, containing a fix for WSL distros being stopped when entering the resource saver mode, see [the release notes](https://docs.docker.com/desktop/release-notes/).
Closing this issue for now, but if the issue persists, please let us know.

**Closed by MihaelaStoica** 2023-11-22 11:32 UTC

**Comment by danon** [comment] 2023-12-06 14:10
Make sure the default distro is set to ubuntu:

```
wsl.exe --setdefault Ubuntu
```

**Comment by aidan-doherty** [comment] 2023-12-08 07:53
> We've released a new version of Docker Desktop, 4.25.2, containing a fix for WSL distros being stopped when entering the resource saver mode, see [the release notes](https://docs.docker.com/desktop/release-notes/).
> Closing this issue for now, but if the issue persists, please let us know.

I updated docker to this version at the start of the week, and I am now starting to experience the issue mentioned here for the first time. Reinstalled docker desktop but still not getting docker command to work in any of my wsl2 installs. The diagnosis check fails with an error also. I will send on the results when I am back at my computer.

**Comment by VRolandFIN** [comment] 2023-12-15 12:14
I had this issue for about 15 minutes.
It appeared after I build the containers and tried running up -d command.

I restarted my computer, which did not resolve the issue.

Then I ran `apt install docker` as more of a test which failed,
got output 
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package docker`

but after this the docker-compose command worked again, so maybe it somehow lost the path or something?

No idea why this worked but i'm running 
Wsl2
Ubuntu 22.04.1 LTS

**Comment by mustafamagdy** [comment] 2024-01-07 15:28
> I just had a similar problem. What resolved it for me was:
> 
> 1. In Docker Desktop navigate to "Settings > Resources > WSL integration" and under "Enable integration with additional distros:" I selected all available distros (the checkbox for enabling integration with the default WSL distro was already checked and I was getting the error in my default distro).
> 2. Updated docker desktop to the latest version available. Docker Desktop is now on v4.17.0 (99724).
> 
> Once Docker Desktop updated, I restarted WSL with `wsl --shutdown` and then within the WSL terminal `docker -v` now returns the version.
> 
> ```shell
> > docker -v
> Docker version 20.10.23, build 7155243
> ```

If you face "permission denied while trying to connect to the Docker daemon " .. you need to add the current user to Docker group 

```sh
sudo usermod -aG docker $USER
```

**Comment by aaronshenhao** [comment] 2024-01-10 21:34
You have to first make sure Docker Desktop is running (visible in taskbar), otherwise it'll say that the `docker` command can't be found. I find this behavior really annoying, and not very intuitive. Is this the intended behavior?

**Comment by HollisTech** [comment] 2024-01-11 14:25
Docker for windows 'installs' docker on targeted wsl instances by creating symlinks in those instances to the docker components in the docker wsl images. Why they didn't just require docker to be installed normally on your wsl instance is a mystery, although perhaps they are trying to avoid version incompatibility issues.

Any way, for my wsl image that runs docker-compose based services, I just have a logon script that restarts those services if they aren't running.  Annoying, as you say.

**Comment by viriatis** [comment] 2024-02-21 16:41
> I have the same problem. I tried `wsl -l` and got this output:
> 
> ```
> > wsl -l
> Windows Subsystem for Linux Distributions:
> Ubuntu-20.04 (Default)
> docker-desktop-data
> ```
> 
> I think there should be an entry `docker-desktop` in there but it seems to be missing.
> 
> UPDATE: After uninstalling and reinstalling docker desktop the docker command is back in wsl2 and I have this output from `wsl -l`:
> 
> ```
> > wsl -l
> Windows Subsystem for Linux Distributions:
> Ubuntu-20.04 (Default)
> docker-desktop-data
> docker-desktop
> ```

I uninstall and install again and appeared again "docker-desktop" with status "Running".
C:\Users\herna>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2

**Comment by enesdertli** [comment] 2024-05-30 18:32
go to docker>settings>resources>WSL integration>enable ubuntu. it worked for me.

**Comment by placlam** [comment] 2024-06-24 21:02
I had this problem on my windows 10 and what simply helped in my case was going to the Task Manager, manually killing all Docker* processes (there will be 4, 5 or 6 such processes under different names like Docker Desktop, Docker Desktop Backend etc.) and restarting Docker Desktop manually

**Comment by hendra-jti** [comment] 2025-04-14 02:45
> I fixed my problem. similar to [RickRosendaal] but with a little difference: I use softlink to docker.exe and not to docker, cause docker file in resources/bin/ not worked fine
> 
> so my commands:
> 
> sudo rmdir /usr/bin/docker sudo ln -s "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" /usr/bin/docker

i need to this everyday. any suggestions to do it only once ?
